{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"responseClass"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s8AnyClassa","text":"AnyClass"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"modules":[{"name":"Airwallex"}],"title":"responseClass()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"responseClass"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s8AnyClassa","text":"AnyClass"}],"navigatorTitle":[{"text":"responseClass","kind":"identifier"}],"externalID":"c:objc(cs)AWXRequest(im)responseClass","role":"symbol","symbolKind":"method","roleHeading":"Instance Method"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRequest"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRequest\/responseClass()"},"sections":[],"variants":[{"paths":["\/documentation\/airwallex\/awxrequest\/responseclass()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxrequest\/responseclass()"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRequest/responseClass()":{"url":"\/documentation\/airwallex\/awxrequest\/responseclass()","type":"topic","title":"responseClass()","navigatorTitle":[{"text":"responseClass","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRequest\/responseClass()","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"responseClass","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"AnyClass","preciseIdentifier":"s:s8AnyClassa","kind":"typeIdentifier"}],"abstract":[],"role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","abstract":[],"role":"collection","url":"\/documentation\/airwallex","title":"Airwallex","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRequest":{"role":"symbol","abstract":[],"url":"\/documentation\/airwallex\/awxrequest","kind":"symbol","title":"AWXRequest","navigatorTitle":[{"kind":"identifier","text":"AWXRequest"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRequest","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXRequest"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"responseClass"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"responseClass","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@Class","text":"Class"},{"kind":"text","text":") "},{"kind":"identifier","text":"responseClass"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"responseClass","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRequest~1responseClass()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"responseClass","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRequest~1responseClass()\/fragments"},{"op":"replace","value":"AWXRequest","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRequest\/title"},{"value":[{"kind":"identifier","text":"AWXRequest"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRequest\/fragments"},{"value":[{"kind":"identifier","text":"AWXRequest"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRequest\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}