{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"elementType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ElementType","preciseIdentifier":"s:9Airwallex17AWXPaymentElementC0C4TypeO","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/ElementType"}]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"codeVoice","code":".paymentSheet"},{"type":"text","text":": Displays a list of available payment methods (default)"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":".addCard"},{"type":"text","text":": Displays only card payment for adding new cards"}],"type":"paragraph"}]}]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"modules":[{"name":"Airwallex"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"elementType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ElementType","preciseIdentifier":"s:9Airwallex17AWXPaymentElementC0C4TypeO"}],"title":"elementType","symbolKind":"property","externalID":"s:9Airwallex17AWXPaymentElementC13ConfigurationC11elementTypeAC0cF0Ovp","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/Configuration"]]},"abstract":[{"type":"text","text":"The type of element to display."}],"variants":[{"paths":["\/documentation\/airwallex\/awxpaymentelement\/configuration\/elementtype"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/Configuration\/elementType","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","url":"\/documentation\/airwallex","abstract":[],"title":"Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement/Configuration/elementType":{"url":"\/documentation\/airwallex\/awxpaymentelement\/configuration\/elementtype","abstract":[{"type":"text","text":"The type of element to display."}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/Configuration\/elementType","title":"elementType","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"elementType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:9Airwallex17AWXPaymentElementC0C4TypeO","text":"ElementType","kind":"typeIdentifier"}],"kind":"symbol","type":"topic","role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement":{"role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentElement"}],"navigatorTitle":[{"kind":"identifier","text":"AWXPaymentElement"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement","url":"\/documentation\/airwallex\/awxpaymentelement","abstract":[{"type":"text","text":"An embeddable payment element that can be added to any view hierarchy."}],"title":"AWXPaymentElement"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement/ElementType":{"role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ElementType"}],"navigatorTitle":[{"kind":"identifier","text":"ElementType"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/ElementType","url":"\/documentation\/airwallex\/awxpaymentelement\/elementtype","abstract":[{"type":"text","text":"The type of element to display."}],"title":"AWXPaymentElement.ElementType"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement/Configuration":{"role":"symbol","type":"topic","title":"AWXPaymentElement.Configuration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"kind":"symbol","abstract":[{"text":"Configuration options for the embedded payment element.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/Configuration","url":"\/documentation\/airwallex\/awxpaymentelement\/configuration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"AWXPaymentElement","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AWXPaymentElement"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AWXPaymentElement"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/navigatorTitle","op":"replace"}]}]}