{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"items"},{"text":": [","kind":"text"},{"text":"AWXBank","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBank","preciseIdentifier":"c:objc(cs)AWXBank"},{"text":"] { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetAvailableBanksResponse\/items"},"metadata":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"items","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AWXBank","preciseIdentifier":"c:objc(cs)AWXBank"},{"kind":"text","text":"]"}],"modules":[{"name":"Airwallex"}],"externalID":"c:objc(cs)AWXGetAvailableBanksResponse(py)items","navigatorTitle":[{"text":"items","kind":"identifier"}],"symbolKind":"property","title":"items","roleHeading":"Instance Property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxgetavailablebanksresponse\/items"]},{"paths":["\/documentation\/airwallex\/awxgetavailablebanksresponse\/items"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","abstract":[{"type":"text","text":"Payment methods."}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetAvailableBanksResponse"]]},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetAvailableBanksResponse":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetAvailableBanksResponse","type":"topic","title":"AWXGetAvailableBanksResponse","navigatorTitle":[{"text":"AWXGetAvailableBanksResponse","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/airwallex\/awxgetavailablebanksresponse","abstract":[{"code":"AWXGetAvailableBanksResponse","type":"codeVoice"},{"type":"text","text":" includes the list of banks."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AWXGetAvailableBanksResponse"}],"role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXBank":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBank","title":"AWXBank","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AWXBank"}],"navigatorTitle":[{"text":"AWXBank","kind":"identifier"}],"role":"symbol","abstract":[{"code":"AWXBank","type":"codeVoice"},{"text":" includes the bank info.","type":"text"}],"url":"\/documentation\/airwallex\/awxbank"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetAvailableBanksResponse/items":{"navigatorTitle":[{"text":"items","kind":"identifier"}],"title":"items","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"items"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)AWXBank","text":"AWXBank","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"abstract":[{"text":"Payment methods.","type":"text"}],"url":"\/documentation\/airwallex\/awxgetavailablebanksresponse\/items","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetAvailableBanksResponse\/items","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/airwallex","title":"Airwallex","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"items","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"items","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSArray<AWXBank *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"items"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"AWXGetAvailableBanksResponse","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetAvailableBanksResponse\/title","op":"replace"},{"value":[{"text":"AWXGetAvailableBanksResponse","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetAvailableBanksResponse\/fragments","op":"replace"},{"op":"replace","value":[{"text":"AWXGetAvailableBanksResponse","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetAvailableBanksResponse\/navigatorTitle"},{"value":"AWXBank","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBank\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AWXBank"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBank\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBank\/navigatorTitle","value":[{"kind":"identifier","text":"AWXBank"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetAvailableBanksResponse~1items\/title","op":"replace","value":"items"},{"value":[{"kind":"identifier","text":"items"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetAvailableBanksResponse~1items\/fragments"}]}]}