{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXShippingViewControllerDelegate"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXShippingViewControllerDelegate\/shippingViewController(_:didEditShipping:)"},"sections":[],"metadata":{"title":"shippingViewController(_:didEditShipping:)","roleHeading":"Instance Method","externalID":"c:objc(pl)AWXShippingViewControllerDelegate(im)shippingViewController:didEditShipping:","symbolKind":"method","modules":[{"name":"Airwallex"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shippingViewController","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)AWXShippingViewController","text":"AWXShippingViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didEditShipping","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AWXPlaceDetails","text":"AWXPlaceDetails","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"shippingViewController:didEditShipping:","kind":"identifier"}],"required":true},"abstract":[{"type":"text","text":"This method is called when a shipping has been saved."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shippingViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"AWXShippingViewController","preciseIdentifier":"c:objc(cs)AWXShippingViewController","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXShippingViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didEditShipping","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"shipping","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPlaceDetails","text":"AWXPlaceDetails","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPlaceDetails"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The shipping view controller.","type":"text"}]}],"name":"controller"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The selected shipping."}]}],"name":"shipping"}]}],"variants":[{"paths":["\/documentation\/airwallex\/awxshippingviewcontrollerdelegate\/shippingviewcontroller(_:dideditshipping:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxshippingviewcontrollerdelegate\/shippingviewcontroller(_:dideditshipping:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXShippingViewController":{"title":"AWXShippingViewController","role":"symbol","deprecated":true,"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXShippingViewController","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxshippingviewcontroller","abstract":[{"type":"codeVoice","code":"AWXShippingViewController"},{"type":"text","text":" provides a form to edit shipping address."}],"kind":"symbol","navigatorTitle":[{"text":"AWXShippingViewController","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXShippingViewController","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXShippingViewControllerDelegate":{"url":"\/documentation\/airwallex\/awxshippingviewcontrollerdelegate","title":"AWXShippingViewControllerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXShippingViewControllerDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"AWXShippingViewControllerDelegate","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"A delegate which handles selected shipping.","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXShippingViewControllerDelegate"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPlaceDetails":{"navigatorTitle":[{"kind":"identifier","text":"AWXPlaceDetails"}],"type":"topic","title":"AWXPlaceDetails","kind":"symbol","role":"symbol","url":"\/documentation\/airwallex\/awxplacedetails","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPlaceDetails","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"AWXPlaceDetails"},{"type":"text","text":" includes the information of a billing address."}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPlaceDetails"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/airwallex","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXShippingViewControllerDelegate/shippingViewController(_:didEditShipping:)":{"url":"\/documentation\/airwallex\/awxshippingviewcontrollerdelegate\/shippingviewcontroller(_:dideditshipping:)","title":"shippingViewController(_:didEditShipping:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shippingViewController","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)AWXShippingViewController","text":"AWXShippingViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didEditShipping","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AWXPlaceDetails","text":"AWXPlaceDetails","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"shippingViewController:didEditShipping:","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"This method is called when a shipping has been saved.","type":"text"}],"type":"topic","required":true,"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXShippingViewControllerDelegate\/shippingViewController(_:didEditShipping:)"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"shippingViewController:didEditShipping:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"shippingViewController:didEditShipping:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"shippingViewController:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AWXShippingViewController","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXShippingViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXShippingViewController"},{"text":" *) ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didEditShipping:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AWXPlaceDetails","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPlaceDetails","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPlaceDetails"},{"text":" *) ","kind":"text"},{"text":"shipping","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"controller","content":[{"type":"paragraph","inlineContent":[{"text":"The shipping view controller.","type":"text"}]}]},{"name":"shipping","content":[{"type":"paragraph","inlineContent":[{"text":"The selected shipping.","type":"text"}]}]}]},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"AWXShippingViewController","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXShippingViewController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AWXShippingViewController"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXShippingViewController\/fragments"},{"op":"replace","value":[{"text":"AWXShippingViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXShippingViewController\/navigatorTitle"},{"op":"replace","value":"AWXShippingViewControllerDelegate","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXShippingViewControllerDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AWXShippingViewControllerDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXShippingViewControllerDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AWXShippingViewControllerDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXShippingViewControllerDelegate\/navigatorTitle"},{"op":"replace","value":"AWXPlaceDetails","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPlaceDetails\/title"},{"op":"replace","value":[{"text":"AWXPlaceDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPlaceDetails\/fragments"},{"op":"replace","value":[{"text":"AWXPlaceDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPlaceDetails\/navigatorTitle"},{"op":"replace","value":"shippingViewController:didEditShipping:","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXShippingViewControllerDelegate~1shippingViewController(_:didEditShipping:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"shippingViewController:didEditShipping:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXShippingViewControllerDelegate~1shippingViewController(_:didEditShipping:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}