{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rawValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXHTTPMethod"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxhttpmethod\/rawvalue"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"symbol","title":"rawValue","externalID":"s:So13AWXHTTPMethoda8rawValueSuvp","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"rawValue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"}],"modules":[{"name":"Airwallex"}],"symbolKind":"property","roleHeading":"Instance Property"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXHTTPMethod\/rawValue"},"sections":[],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXHTTPMethod/rawValue":{"url":"\/documentation\/airwallex\/awxhttpmethod\/rawvalue","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"}],"kind":"symbol","title":"rawValue","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXHTTPMethod\/rawValue"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","title":"Airwallex","abstract":[],"type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXHTTPMethod":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXHTTPMethod"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXHTTPMethod","url":"\/documentation\/airwallex\/awxhttpmethod","type":"topic","abstract":[{"type":"text","text":"Http request"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWXHTTPMethod"}],"title":"AWXHTTPMethod"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"AWXHTTPMethod","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXHTTPMethod\/title"},{"value":[{"kind":"identifier","text":"AWXHTTPMethod"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXHTTPMethod\/fragments"},{"value":[{"kind":"identifier","text":"AWXHTTPMethod"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXHTTPMethod\/navigatorTitle"}]}]}