{"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allAvailable","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)AWXCardScheme","text":"AWXCardScheme","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardScheme"},{"text":"] { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/airwallex\/awxcardscheme\/allavailable"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"allAvailable"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)AWXCardScheme","kind":"typeIdentifier","text":"AWXCardScheme"},{"kind":"text","text":"]"}],"modules":[{"name":"Airwallex"}],"role":"symbol","extendedModule":"Airwallex","title":"allAvailable","roleHeading":"Type Property","symbolKind":"property","externalID":"s:So13AWXCardSchemeC9AirwallexE12allAvailableSayABGvpZ"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardScheme\/allAvailable"},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardScheme"]]},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardScheme":{"title":"AWXCardScheme","role":"symbol","type":"topic","abstract":[],"url":"\/documentation\/airwallex\/awxcardscheme","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardScheme","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXCardScheme"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWXCardScheme"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardScheme/allAvailable":{"title":"allAvailable","role":"symbol","type":"topic","abstract":[],"url":"\/documentation\/airwallex\/awxcardscheme\/allavailable","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardScheme\/allAvailable","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allAvailable"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXCardScheme","text":"AWXCardScheme"},{"kind":"text","text":"]"}],"kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"abstract":[],"url":"\/documentation\/airwallex","role":"collection","title":"Airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardScheme\/title","value":"AWXCardScheme","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardScheme\/fragments","value":[{"text":"AWXCardScheme","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardScheme\/navigatorTitle","value":[{"text":"AWXCardScheme","kind":"identifier"}],"op":"replace"}]}]}