{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pageSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentConsentsRequest"]]},"kind":"symbol","metadata":{"externalID":"c:objc(cs)AWXGetPaymentConsentsRequest(py)pageSize","symbolKind":"property","title":"pageSize","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pageSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"kind":"identifier","text":"pageSize"}],"modules":[{"name":"Airwallex"}],"role":"symbol","roleHeading":"Instance Property"},"abstract":[{"type":"text","text":"Number of payment methods to be listed per page."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentConsentsRequest\/pageSize"},"variants":[{"paths":["\/documentation\/airwallex\/awxgetpaymentconsentsrequest\/pagesize"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxgetpaymentconsentsrequest\/pagesize"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentConsentsRequest":{"url":"\/documentation\/airwallex\/awxgetpaymentconsentsrequest","abstract":[{"type":"codeVoice","code":"AWXGetPaymentConsentsRequest"},{"text":" includes the request of payment consents.","type":"text"}],"role":"symbol","kind":"symbol","title":"AWXGetPaymentConsentsRequest","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXGetPaymentConsentsRequest"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentConsentsRequest","navigatorTitle":[{"kind":"identifier","text":"AWXGetPaymentConsentsRequest"}],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","role":"collection","url":"\/documentation\/airwallex","kind":"symbol","title":"Airwallex","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentConsentsRequest/pageSize":{"url":"\/documentation\/airwallex\/awxgetpaymentconsentsrequest\/pagesize","abstract":[{"text":"Number of payment methods to be listed per page.","type":"text"}],"type":"topic","role":"symbol","title":"pageSize","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pageSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"pageSize","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentConsentsRequest\/pageSize"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"pageSize"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"pageSize"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageSize"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentConsentsRequest\/title","op":"replace","value":"AWXGetPaymentConsentsRequest"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentConsentsRequest\/fragments","op":"replace","value":[{"kind":"identifier","text":"AWXGetPaymentConsentsRequest"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentConsentsRequest\/navigatorTitle","op":"replace","value":[{"text":"AWXGetPaymentConsentsRequest","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentConsentsRequest~1pageSize\/title","op":"replace","value":"pageSize"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentConsentsRequest~1pageSize\/fragments","op":"replace","value":[{"text":"pageSize","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}