{"abstract":[{"type":"text","text":"Lang"}],"sections":[],"kind":"symbol","metadata":{"symbolKind":"property","navigatorTitle":[{"text":"lang","kind":"identifier"}],"roleHeading":"Instance Property","title":"lang","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lang","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"modules":[{"name":"Airwallex"}],"externalID":"c:objc(cs)AWXGetAvailableBanksRequest(py)lang"},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetAvailableBanksRequest\/lang","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxgetavailablebanksrequest\/lang"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxgetavailablebanksrequest\/lang"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"lang"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetAvailableBanksRequest"]]},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetAvailableBanksRequest":{"url":"\/documentation\/airwallex\/awxgetavailablebanksrequest","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetAvailableBanksRequest","kind":"symbol","title":"AWXGetAvailableBanksRequest","navigatorTitle":[{"kind":"identifier","text":"AWXGetAvailableBanksRequest"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXGetAvailableBanksRequest"}],"abstract":[{"type":"codeVoice","code":"AWXGetPaymentMethodTypeRequest"},{"type":"text","text":" includes all of the parameters needed to get payment method type."}],"role":"symbol","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetAvailableBanksRequest/lang":{"url":"\/documentation\/airwallex\/awxgetavailablebanksrequest\/lang","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lang","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"text":"Lang","type":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetAvailableBanksRequest\/lang","title":"lang","navigatorTitle":[{"text":"lang","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","abstract":[],"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/airwallex"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"lang","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"lang"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"lang","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"AWXGetAvailableBanksRequest","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetAvailableBanksRequest\/title"},{"op":"replace","value":[{"text":"AWXGetAvailableBanksRequest","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetAvailableBanksRequest\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AWXGetAvailableBanksRequest"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetAvailableBanksRequest\/navigatorTitle"},{"op":"replace","value":"lang","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetAvailableBanksRequest~1lang\/title"},{"op":"replace","value":[{"kind":"identifier","text":"lang"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetAvailableBanksRequest~1lang\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}