{"variants":[{"paths":["\/documentation\/airwallex\/awxsession\/validationerror\/localizederror-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"roleHeading":"API Collection","role":"collectionGroup","modules":[{"name":"Airwallex"}],"title":"LocalizedError Implementations"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession\/ValidationError"]]},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession\/ValidationError\/LocalizedError-Implementations","interfaceLanguage":"swift"},"kind":"article","topicSections":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession\/ValidationError\/failureReason","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession\/ValidationError\/helpAnchor","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession\/ValidationError\/recoverySuggestion"],"title":"Instance Properties","generated":true}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSession/ValidationError/helpAnchor":{"abstract":[],"url":"\/documentation\/airwallex\/awxsession\/validationerror\/helpanchor","kind":"symbol","type":"topic","role":"symbol","title":"helpAnchor","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession\/ValidationError\/helpAnchor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"helpAnchor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","kind":"symbol","url":"\/documentation\/airwallex","abstract":[],"title":"Airwallex","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSession/ValidationError/recoverySuggestion":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession\/ValidationError\/recoverySuggestion","abstract":[],"title":"recoverySuggestion","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recoverySuggestion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/airwallex\/awxsession\/validationerror\/recoverysuggestion","kind":"symbol","role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSession":{"navigatorTitle":[{"kind":"identifier","text":"AWXSession"}],"role":"symbol","kind":"symbol","abstract":[{"type":"codeVoice","code":"AWXSession"},{"text":" is the base session.","type":"text"}],"type":"topic","title":"AWXSession","url":"\/documentation\/airwallex\/awxsession","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXSession"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSession/ValidationError/failureReason":{"abstract":[],"url":"\/documentation\/airwallex\/awxsession\/validationerror\/failurereason","kind":"symbol","type":"topic","role":"symbol","title":"failureReason","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession\/ValidationError\/failureReason","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failureReason","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSession/ValidationError":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ValidationError"}],"navigatorTitle":[{"kind":"identifier","text":"ValidationError"}],"type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession\/ValidationError","title":"AWXSession.ValidationError","kind":"symbol","url":"\/documentation\/airwallex\/awxsession\/validationerror"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/title","value":"AWXSession","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/fragments","value":[{"kind":"identifier","text":"AWXSession"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/navigatorTitle","value":[{"text":"AWXSession","kind":"identifier"}],"op":"replace"}]}]}