{"kind":"symbol","abstract":[{"type":"text","text":"Captured amount."}],"metadata":{"externalID":"c:objc(cs)AWXPaymentAttempt(py)capturedAmount","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"capturedAmount","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSDecimalNumber","text":"NSDecimalNumber","kind":"typeIdentifier"}],"roleHeading":"Instance Property","title":"capturedAmount","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"capturedAmount"}],"modules":[{"name":"Airwallex"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentAttempt"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentAttempt\/capturedAmount"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"capturedAmount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSDecimalNumber","preciseIdentifier":"c:objc(cs)NSDecimalNumber"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/airwallex\/awxpaymentattempt\/capturedamount"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxpaymentattempt\/capturedamount"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentAttempt/capturedAmount":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"capturedAmount"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSDecimalNumber","kind":"typeIdentifier","text":"NSDecimalNumber"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentAttempt\/capturedAmount","navigatorTitle":[{"text":"capturedAmount","kind":"identifier"}],"title":"capturedAmount","type":"topic","url":"\/documentation\/airwallex\/awxpaymentattempt\/capturedamount","abstract":[{"text":"Captured amount.","type":"text"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","abstract":[],"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentAttempt":{"title":"AWXPaymentAttempt","type":"topic","navigatorTitle":[{"text":"AWXPaymentAttempt","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"AWXPaymentAttempt"},{"type":"text","text":" includes the information of payment attempt."}],"url":"\/documentation\/airwallex\/awxpaymentattempt","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPaymentAttempt","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentAttempt"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"capturedAmount","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"capturedAmount"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSDecimalNumber","preciseIdentifier":"c:objc(cs)NSDecimalNumber","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"capturedAmount","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"capturedAmount","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentAttempt~1capturedAmount\/title","op":"replace"},{"value":[{"text":"capturedAmount","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentAttempt~1capturedAmount\/fragments","op":"replace"},{"value":"AWXPaymentAttempt","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentAttempt\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AWXPaymentAttempt"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentAttempt\/fragments","op":"replace"},{"value":[{"text":"AWXPaymentAttempt","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentAttempt\/navigatorTitle","op":"replace"}]}]}