{"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"schemas","kind":"identifier"},{"text":": [","kind":"text"},{"text":"AWXSchema","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSchema","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXSchema"},{"text":"] { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Field schemas"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypeResponse"]]},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"schemas","kind":"identifier"},{"text":": [","kind":"text"},{"text":"AWXSchema","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXSchema"},{"text":"]","kind":"text"}],"roleHeading":"Instance Property","symbolKind":"property","role":"symbol","title":"schemas","modules":[{"name":"Airwallex"}],"navigatorTitle":[{"kind":"identifier","text":"schemas"}],"externalID":"c:objc(cs)AWXGetPaymentMethodTypeResponse(py)schemas"},"variants":[{"paths":["\/documentation\/airwallex\/awxgetpaymentmethodtyperesponse\/schemas"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxgetpaymentmethodtyperesponse\/schemas"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypeResponse\/schemas","interfaceLanguage":"swift"},"sections":[],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","url":"\/documentation\/airwallex","abstract":[],"title":"Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentMethodTypeResponse":{"role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXGetPaymentMethodTypeResponse","kind":"identifier"}],"navigatorTitle":[{"text":"AWXGetPaymentMethodTypeResponse","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypeResponse","url":"\/documentation\/airwallex\/awxgetpaymentmethodtyperesponse","title":"AWXGetPaymentMethodTypeResponse","abstract":[{"code":"AWXGetPaymentMethodTypeResponse","type":"codeVoice"},{"type":"text","text":" includes the list of payment methods."}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSchema":{"role":"symbol","type":"topic","title":"AWXSchema","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AWXSchema","kind":"identifier"}],"navigatorTitle":[{"text":"AWXSchema","kind":"identifier"}],"kind":"symbol","abstract":[{"code":"AWXSchema","type":"codeVoice"},{"type":"text","text":" includes the schema of payment method."}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSchema","url":"\/documentation\/airwallex\/awxschema"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentMethodTypeResponse/schemas":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"schemas"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)AWXSchema","text":"AWXSchema","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"title":"schemas","url":"\/documentation\/airwallex\/awxgetpaymentmethodtyperesponse\/schemas","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypeResponse\/schemas","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"schemas"}],"abstract":[{"text":"Field schemas","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"schemas","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"schemas","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<AWXSchema *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"schemas","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"AWXGetPaymentMethodTypeResponse","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypeResponse\/title"},{"value":[{"text":"AWXGetPaymentMethodTypeResponse","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypeResponse\/fragments"},{"value":[{"text":"AWXGetPaymentMethodTypeResponse","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypeResponse\/navigatorTitle"},{"value":"AWXSchema","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSchema\/title"},{"value":[{"text":"AWXSchema","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSchema\/fragments"},{"value":[{"text":"AWXSchema","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSchema\/navigatorTitle"},{"value":"schemas","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypeResponse~1schemas\/title"},{"value":[{"text":"schemas","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypeResponse~1schemas\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}