{"sections":[],"metadata":{"fragments":[{"kind":"identifier","text":"amount"}],"platforms":[{"unavailable":false,"beta":false,"deprecated":true}],"externalID":"c:objc(cs)AWXRecurringSession(py)amount","role":"symbol","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"amount"}],"modules":[{"name":"Airwallex"}],"roleHeading":"Instance Property","title":"amount"},"abstract":[{"text":"Payment amount. This is the order amount you would like to charge your customer.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxrecurringsession\/amount"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession\/amount","interfaceLanguage":"occ"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSDecimalNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDecimalNumber"},{"kind":"text","text":" * "},{"text":"amount","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRecurringSession":{"title":"AWXRecurringSession","abstract":[{"type":"codeVoice","code":"AWXRecurringSession"},{"type":"text","text":" is the session used for recurring."}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession","navigatorTitle":[{"text":"AWXRecurringSession","kind":"identifier"}],"deprecated":true,"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXRecurringSession","kind":"identifier"}],"type":"topic","url":"\/documentation\/airwallex\/awxrecurringsession","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRecurringSession/amount":{"title":"amount","type":"topic","abstract":[{"text":"Payment amount. This is the order amount you would like to charge your customer.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession\/amount","url":"\/documentation\/airwallex\/awxrecurringsession\/amount","kind":"symbol","role":"symbol","fragments":[{"text":"amount","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","abstract":[],"type":"topic","kind":"symbol","title":"Airwallex","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRecurringSession\/title","value":"AWXRecurringSession","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRecurringSession\/fragments","value":[{"kind":"identifier","text":"AWXRecurringSession"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRecurringSession\/navigatorTitle","op":"replace","value":[{"text":"AWXRecurringSession","kind":"identifier"}]}]}]}