{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"currency"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession\/currency()","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/airwallex\/awxrecurringsession\/currency()"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"metadata":{"role":"symbol","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"currency","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"modules":[{"name":"Airwallex"}],"platforms":[{"unavailable":false,"message":"Will be removed in next major version release, use AirwallexPayment.Session instead","deprecated":true,"beta":false}],"title":"currency()","symbolKind":"method","externalID":"c:objc(cs)AWXRecurringSession(im)currency"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession"]]},"deprecationSummary":[{"inlineContent":[{"text":"Will be removed in next major version release, use AirwallexPayment.Session instead","type":"text"}],"type":"paragraph"}],"kind":"symbol","references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRecurringSession/currency()":{"deprecated":true,"kind":"symbol","role":"symbol","title":"currency()","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession\/currency()","url":"\/documentation\/airwallex\/awxrecurringsession\/currency()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"currency"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRecurringSession":{"url":"\/documentation\/airwallex\/awxrecurringsession","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession","type":"topic","role":"symbol","kind":"symbol","title":"AWXRecurringSession","navigatorTitle":[{"text":"AWXRecurringSession","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"AWXRecurringSession"},{"type":"text","text":" is the session used for recurring."}],"deprecated":true,"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXRecurringSession","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/airwallex","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRecurringSession\/title","value":"AWXRecurringSession","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRecurringSession\/fragments","value":[{"kind":"identifier","text":"AWXRecurringSession"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRecurringSession\/navigatorTitle","value":[{"text":"AWXRecurringSession","kind":"identifier"}],"op":"replace"}]}]}