{"metadata":{"fragments":[{"kind":"identifier","text":"currency"}],"navigatorTitle":[{"text":"currency","kind":"identifier"}],"externalID":"c:objc(cs)AWXRecurringSession(py)currency","role":"symbol","modules":[{"name":"Airwallex"}],"symbolKind":"property","title":"currency","roleHeading":"Instance Property"},"abstract":[{"type":"text","text":"Currency."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxrecurringsession\/currency"]}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"currency"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession\/currency","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession"]]},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRecurringSession/currency":{"url":"\/documentation\/airwallex\/awxrecurringsession\/currency","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession\/currency","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Currency."}],"title":"currency","fragments":[{"kind":"identifier","text":"currency"}],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"abstract":[],"url":"\/documentation\/airwallex","role":"collection","title":"Airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","type":"topic","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRecurringSession":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXRecurringSession","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxrecurringsession","navigatorTitle":[{"text":"AWXRecurringSession","kind":"identifier"}],"kind":"symbol","type":"topic","title":"AWXRecurringSession","role":"symbol","abstract":[{"code":"AWXRecurringSession","type":"codeVoice"},{"type":"text","text":" is the session used for recurring."}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"AWXRecurringSession","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRecurringSession\/title"},{"op":"replace","value":[{"text":"AWXRecurringSession","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRecurringSession\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AWXRecurringSession"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRecurringSession\/navigatorTitle"}]}]}