{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxrecurringsession\/customerid"]}],"metadata":{"role":"symbol","platforms":[{"deprecated":true,"unavailable":false,"beta":false}],"fragments":[{"text":"customerId","kind":"identifier"}],"externalID":"c:objc(cs)AWXRecurringSession(py)customerId","roleHeading":"Instance Property","symbolKind":"property","title":"customerId","modules":[{"name":"Airwallex"}],"navigatorTitle":[{"text":"customerId","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"customerId","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession\/customerId","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession"]]},"abstract":[{"type":"text","text":"The customer who is paying for this payment intent."}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRecurringSession/customerId":{"role":"symbol","fragments":[{"text":"customerId","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession\/customerId","type":"topic","title":"customerId","url":"\/documentation\/airwallex\/awxrecurringsession\/customerid","abstract":[{"type":"text","text":"The customer who is paying for this payment intent."}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRecurringSession":{"deprecated":true,"title":"AWXRecurringSession","navigatorTitle":[{"text":"AWXRecurringSession","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession","url":"\/documentation\/airwallex\/awxrecurringsession","role":"symbol","abstract":[{"type":"codeVoice","code":"AWXRecurringSession"},{"text":" is the session used for recurring.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXRecurringSession","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","type":"topic","role":"collection","title":"Airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRecurringSession\/title","value":"AWXRecurringSession"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRecurringSession\/fragments","value":[{"text":"AWXRecurringSession","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRecurringSession\/navigatorTitle","value":[{"text":"AWXRecurringSession","kind":"identifier"}]}]}]}