{"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nextTriggerByType","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@AirwallexNextTriggerByType","text":"AirwallexNextTriggerByType","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexNextTriggerByType"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Next trigger by."}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession"]]},"metadata":{"navigatorTitle":[{"text":"nextTriggerByType","kind":"identifier"}],"roleHeading":"Instance Property","modules":[{"name":"Airwallex"}],"title":"nextTriggerByType","symbolKind":"property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"nextTriggerByType","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AirwallexNextTriggerByType","preciseIdentifier":"c:@E@AirwallexNextTriggerByType"}],"externalID":"c:objc(cs)AWXRecurringSession(py)nextTriggerByType"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxrecurringsession\/nexttriggerbytype"]},{"paths":["\/documentation\/airwallex\/awxrecurringsession\/nexttriggerbytype"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession\/nextTriggerByType"},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/airwallex","title":"Airwallex","role":"collection"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRecurringSession":{"type":"topic","title":"AWXRecurringSession","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AWXRecurringSession","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWXRecurringSession"}],"role":"symbol","url":"\/documentation\/airwallex\/awxrecurringsession","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession","abstract":[{"code":"AWXRecurringSession","type":"codeVoice"},{"text":" is the session used for recurring.","type":"text"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexNextTriggerByType":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexNextTriggerByType","abstract":[],"role":"symbol","navigatorTitle":[{"text":"AirwallexNextTriggerByType","kind":"identifier"}],"url":"\/documentation\/airwallex\/airwallexnexttriggerbytype","title":"AirwallexNextTriggerByType","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"AirwallexNextTriggerByType","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRecurringSession/nextTriggerByType":{"abstract":[{"type":"text","text":"Next trigger by."}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nextTriggerByType"},{"kind":"text","text":": "},{"text":"AirwallexNextTriggerByType","kind":"typeIdentifier","preciseIdentifier":"c:@E@AirwallexNextTriggerByType"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession\/nextTriggerByType","role":"symbol","url":"\/documentation\/airwallex\/awxrecurringsession\/nexttriggerbytype","title":"nextTriggerByType","type":"topic","navigatorTitle":[{"text":"nextTriggerByType","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"nextTriggerByType"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"nextTriggerByType"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexNextTriggerByType","kind":"typeIdentifier","preciseIdentifier":"c:@E@AirwallexNextTriggerByType","text":"AirwallexNextTriggerByType"},{"text":" ","kind":"text"},{"text":"nextTriggerByType","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"AWXRecurringSession","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRecurringSession\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRecurringSession\/fragments","op":"replace","value":[{"kind":"identifier","text":"AWXRecurringSession"}]},{"op":"replace","value":[{"text":"AWXRecurringSession","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRecurringSession\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexNextTriggerByType\/title","value":"AirwallexNextTriggerByType","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexNextTriggerByType\/fragments","value":[{"kind":"identifier","text":"AirwallexNextTriggerByType"}],"op":"replace"},{"op":"replace","value":[{"text":"AirwallexNextTriggerByType","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexNextTriggerByType\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRecurringSession~1nextTriggerByType\/title","op":"replace","value":"nextTriggerByType"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRecurringSession~1nextTriggerByType\/fragments","value":[{"text":"nextTriggerByType","kind":"identifier"}]}]}]}