{"metadata":{"title":"setAmount(_:)","externalID":"c:objc(cs)AWXRecurringSession(im)setAmount:","symbolKind":"method","modules":[{"name":"Airwallex"}],"role":"symbol","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setAmount"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSDecimalNumber","kind":"typeIdentifier","text":"NSDecimalNumber"},{"kind":"text","text":")"}]},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession\/setAmount(_:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession"]]},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setAmount","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"amount","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"NSDecimalNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDecimalNumber"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/airwallex\/awxrecurringsession\/setamount(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRecurringSession/setAmount(_:)":{"url":"\/documentation\/airwallex\/awxrecurringsession\/setamount(_:)","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession\/setAmount(_:)","role":"symbol","kind":"symbol","abstract":[],"title":"setAmount(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setAmount"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSDecimalNumber","preciseIdentifier":"c:objc(cs)NSDecimalNumber"},{"kind":"text","text":")"}],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRecurringSession":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXRecurringSession","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxrecurringsession","navigatorTitle":[{"text":"AWXRecurringSession","kind":"identifier"}],"kind":"symbol","type":"topic","title":"AWXRecurringSession","role":"symbol","abstract":[{"code":"AWXRecurringSession","type":"codeVoice"},{"type":"text","text":" is the session used for recurring."}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"abstract":[],"url":"\/documentation\/airwallex","role":"collection","title":"Airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRecurringSession\/title","op":"replace","value":"AWXRecurringSession"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRecurringSession\/fragments","op":"replace","value":[{"kind":"identifier","text":"AWXRecurringSession"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRecurringSession\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AWXRecurringSession"}]}]}]}