{"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringWithIntentSession"]]},"kind":"symbol","abstract":[{"type":"text","text":"The payment intent to handle."}],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Will be removed in next major version release, use AirwallexPayment.Session instead"}],"type":"paragraph"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"paymentIntent"}],"externalID":"c:objc(cs)AWXRecurringWithIntentSession(py)paymentIntent","modules":[{"name":"Airwallex"}],"roleHeading":"Instance Property","platforms":[{"message":"Will be removed in next major version release, use AirwallexPayment.Session instead","unavailable":false,"deprecated":true,"beta":false}],"role":"symbol","title":"paymentIntent","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentIntent"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AWXPaymentIntent","kind":"typeIdentifier","text":"AWXPaymentIntent"},{"kind":"text","text":"?"}],"symbolKind":"property"},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentIntent","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWXPaymentIntent","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent","preciseIdentifier":"c:objc(cs)AWXPaymentIntent","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringWithIntentSession\/paymentIntent","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/airwallex\/awxrecurringwithintentsession\/paymentintent"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxrecurringwithintentsession\/paymentintent"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRecurringWithIntentSession":{"abstract":[{"type":"codeVoice","code":"AWXRecurringWithIntentSession"},{"type":"text","text":" is the session used for recurring with intent."}],"navigatorTitle":[{"kind":"identifier","text":"AWXRecurringWithIntentSession"}],"title":"AWXRecurringWithIntentSession","kind":"symbol","deprecated":true,"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringWithIntentSession","url":"\/documentation\/airwallex\/awxrecurringwithintentsession","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXRecurringWithIntentSession"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","url":"\/documentation\/airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","kind":"symbol","role":"collection","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRecurringWithIntentSession/paymentIntent":{"abstract":[{"type":"text","text":"The payment intent to handle."}],"navigatorTitle":[{"kind":"identifier","text":"paymentIntent"}],"title":"paymentIntent","kind":"symbol","deprecated":true,"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringWithIntentSession\/paymentIntent","type":"topic","url":"\/documentation\/airwallex\/awxrecurringwithintentsession\/paymentintent","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentIntent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWXPaymentIntent","preciseIdentifier":"c:objc(cs)AWXPaymentIntent"},{"kind":"text","text":"?"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentIntent":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent","abstract":[{"type":"codeVoice","code":"AWXPaymentIntent"},{"type":"text","text":" includes the information of payment intent."}],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/airwallex\/awxpaymentintent","navigatorTitle":[{"kind":"identifier","text":"AWXPaymentIntent"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentIntent"}],"title":"AWXPaymentIntent"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[{"unavailable":false,"deprecated":true,"beta":false}],"op":"replace","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"paymentIntent","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"paymentIntent","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"AWXPaymentIntent","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent","preciseIdentifier":"c:objc(cs)AWXPaymentIntent"},{"text":" * ","kind":"text"},{"text":"paymentIntent","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":[{"inlineContent":[{"type":"text","text":"Will be removed in next major version release, use AirwallexPayment.Session instead"}],"type":"paragraph"}],"op":"replace","path":"\/deprecationSummary"},{"value":"AWXRecurringWithIntentSession","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRecurringWithIntentSession\/title"},{"value":[{"text":"AWXRecurringWithIntentSession","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRecurringWithIntentSession\/fragments"},{"value":[{"text":"AWXRecurringWithIntentSession","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRecurringWithIntentSession\/navigatorTitle"},{"value":"paymentIntent","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRecurringWithIntentSession~1paymentIntent\/title"},{"value":[{"text":"paymentIntent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRecurringWithIntentSession~1paymentIntent\/fragments"},{"value":"AWXPaymentIntent","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentIntent\/title"},{"value":[{"text":"AWXPaymentIntent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentIntent\/fragments"},{"value":[{"text":"AWXPaymentIntent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentIntent\/navigatorTitle"}]}]}