{"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPage","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","relationshipsSections":[{"title":"Conforming Types","kind":"relationships","type":"conformingTypes","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentConsentsResponse","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypesResponse"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPage","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxpage"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxpage"]}],"topicSections":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPage\/hasMore","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPage\/items"]}],"metadata":{"modules":[{"name":"Airwallex"}],"role":"symbol","externalID":"c:objc(pl)AWXPage","symbolKind":"protocol","roleHeading":"Protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPage","kind":"identifier"}],"title":"AWXPage","navigatorTitle":[{"text":"AWXPage","kind":"identifier"}]},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentMethodTypesResponse":{"navigatorTitle":[{"text":"AWXGetPaymentMethodTypesResponse","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXGetPaymentMethodTypesResponse","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypesResponse","role":"symbol","kind":"symbol","abstract":[{"code":"AWXGetPaymentMethodTypesResponse","type":"codeVoice"},{"text":" includes the list of payment methods.","type":"text"}],"title":"AWXGetPaymentMethodTypesResponse","url":"\/documentation\/airwallex\/awxgetpaymentmethodtypesresponse"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPage/hasMore":{"url":"\/documentation\/airwallex\/awxpage\/hasmore","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasMore"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","title":"hasMore","navigatorTitle":[{"kind":"identifier","text":"hasMore"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPage\/hasMore","required":true},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPage/items":{"navigatorTitle":[{"kind":"identifier","text":"items"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPage\/items","title":"items","kind":"symbol","url":"\/documentation\/airwallex\/awxpage\/items","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"items"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!"}],"abstract":[],"role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","url":"\/documentation\/airwallex","role":"collection","kind":"symbol","abstract":[],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPage":{"role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"AWXPage"}],"title":"AWXPage","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPage"}],"url":"\/documentation\/airwallex\/awxpage","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPage"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentConsentsResponse":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXGetPaymentConsentsResponse"}],"title":"AWXGetPaymentConsentsResponse","navigatorTitle":[{"kind":"identifier","text":"AWXGetPaymentConsentsResponse"}],"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentConsentsResponse","url":"\/documentation\/airwallex\/awxgetpaymentconsentsresponse","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"op":"replace","value":"AWXPage","path":"\/metadata\/title"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"AWXPage","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AWXPage"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPage\/hasMore","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPage\/items"],"title":"Instance Properties","generated":true}],"path":"\/topicSections"},{"op":"replace","value":[{"type":"conformingTypes","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentConsentsResponse","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypesResponse"],"title":"Conforming Types","kind":"relationships"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPage","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypesResponse\/title","value":"AWXGetPaymentMethodTypesResponse"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypesResponse\/fragments","value":[{"kind":"identifier","text":"AWXGetPaymentMethodTypesResponse"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypesResponse\/navigatorTitle","value":[{"text":"AWXGetPaymentMethodTypesResponse","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPage~1hasMore\/title","value":"hasMore"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPage~1hasMore\/fragments","value":[{"kind":"identifier","text":"hasMore"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPage~1items\/title","value":"items"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPage~1items\/fragments","value":[{"kind":"identifier","text":"items"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPage\/title","value":"AWXPage"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPage\/fragments","value":[{"text":"AWXPage","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPage\/navigatorTitle","value":[{"text":"AWXPage","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentConsentsResponse\/title","value":"AWXGetPaymentConsentsResponse"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentConsentsResponse\/fragments","value":[{"kind":"identifier","text":"AWXGetPaymentConsentsResponse"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentConsentsResponse\/navigatorTitle","value":[{"text":"AWXGetPaymentConsentsResponse","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}