{"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXThreeDSReturnURL","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXThreeDSReturnURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"metadata":{"navigatorTitle":[{"text":"AWXThreeDSReturnURL","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXThreeDSReturnURL","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"symbolKind":"var","title":"AWXThreeDSReturnURL","role":"symbol","modules":[{"name":"Airwallex"}],"externalID":"c:@AWXThreeDSReturnURL","roleHeading":"Global Variable"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxthreedsreturnurl"]},{"paths":["\/documentation\/airwallex\/awxthreedsreturnurl"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXThreeDSReturnURL":{"role":"symbol","kind":"symbol","abstract":[],"type":"topic","url":"\/documentation\/airwallex\/awxthreedsreturnurl","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXThreeDSReturnURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXThreeDSReturnURL","navigatorTitle":[{"kind":"identifier","text":"AWXThreeDSReturnURL"}],"title":"AWXThreeDSReturnURL"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","url":"\/documentation\/airwallex","role":"collection","kind":"symbol","abstract":[],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Global Variable","path":"\/metadata\/roleHeading"},{"op":"replace","value":"AWXThreeDSReturnURL","path":"\/metadata\/title"},{"op":"replace","value":"var","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"AWXThreeDSReturnURL"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXThreeDSReturnURL","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXThreeDSReturnURL\/title","op":"replace","value":"AWXThreeDSReturnURL"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXThreeDSReturnURL\/fragments","op":"replace","value":[{"text":"AWXThreeDSReturnURL","kind":"identifier"}]}]}]}