{"metadata":{"role":"symbol","title":"AWXWeChatPayActionProvider","roleHeading":"Class","navigatorTitle":[{"text":"AWXWeChatPayActionProvider","kind":"identifier"}],"externalID":"c:objc(cs)AWXWeChatPayActionProvider","symbolKind":"class","modules":[{"name":"Airwallex"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXWeChatPayActionProvider","kind":"identifier"}]},"abstract":[{"code":"AWXWeChatPayActionProvider","type":"codeVoice"},{"text":" handles WeChat pay flow.","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXWeChatPayActionProvider","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/airwallex\/awxwechatpayactionprovider"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxwechatpayactionprovider"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultActionProvider"],"title":"Inherits From"},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/SQ","doc:\/\/org.cocoapods.Airwallex\/SH"],"title":"Conforms To"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXWeChatPayActionProvider","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.Airwallex/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXWeChatPayActionProvider":{"url":"\/documentation\/airwallex\/awxwechatpayactionprovider","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXWeChatPayActionProvider","kind":"symbol","type":"topic","abstract":[{"type":"codeVoice","code":"AWXWeChatPayActionProvider"},{"type":"text","text":" handles WeChat pay flow."}],"role":"symbol","title":"AWXWeChatPayActionProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXWeChatPayActionProvider"}],"navigatorTitle":[{"kind":"identifier","text":"AWXWeChatPayActionProvider"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","url":"\/documentation\/airwallex","role":"collection","kind":"symbol","abstract":[],"type":"topic"},"doc://org.cocoapods.Airwallex/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SQ"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXDefaultActionProvider":{"abstract":[{"text":"A provider which handles next action business.","type":"text"}],"title":"AWXDefaultActionProvider","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXDefaultActionProvider","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultActionProvider","navigatorTitle":[{"text":"AWXDefaultActionProvider","kind":"identifier"}],"type":"topic","url":"\/documentation\/airwallex\/awxdefaultactionprovider"},"doc://org.cocoapods.Airwallex/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.Airwallex/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.Airwallex/SH":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://org.cocoapods.Airwallex/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"AWXWeChatPayActionProvider","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"AWXWeChatPayActionProvider","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"AWXWeChatPayActionProvider","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"replace","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultActionProvider"],"type":"inheritsFrom"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXWeChatPayActionProvider","kind":"identifier"},{"text":" : ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultActionProvider","text":"AWXDefaultActionProvider","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXDefaultActionProvider"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXWeChatPayActionProvider\/title","value":"AWXWeChatPayActionProvider"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXWeChatPayActionProvider\/fragments","value":[{"kind":"identifier","text":"AWXWeChatPayActionProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXWeChatPayActionProvider\/navigatorTitle","value":[{"text":"AWXWeChatPayActionProvider","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultActionProvider\/title","value":"AWXDefaultActionProvider"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultActionProvider\/fragments","value":[{"text":"AWXDefaultActionProvider","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultActionProvider\/navigatorTitle","value":[{"text":"AWXDefaultActionProvider","kind":"identifier"}]}]}]}