{"kind":"symbol","abstract":[{"text":"A protocol for providing payment intents on-demand during the payment flow.","type":"text"}],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentIntentProvider"}],"externalID":"c:@M@Airwallex@objc(pl)PaymentIntentProvider","symbolKind":"protocol","navigatorTitle":[{"text":"PaymentIntentProvider","kind":"identifier"}],"title":"PaymentIntentProvider","modules":[{"name":"Airwallex"}],"roleHeading":"Protocol"},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentIntentProvider\/amount","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentIntentProvider\/currency","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentIntentProvider\/customerId"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentIntentProvider\/createPaymentIntent()"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/paymentintentprovider"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/paymentintentprovider"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentIntentProvider"}]}]},{"kind":"content","content":[{"text":"Overview","anchor":"overview","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"PaymentIntentProvider"},{"type":"text","text":" enables delayed payment intent creation, allowing you to defer"},{"type":"text","text":" "},{"type":"text","text":"the creation of a payment intent until just before payment confirmation or when it is required."}]},{"text":"Overview","anchor":"Overview","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"When using "},{"type":"codeVoice","code":"Session"},{"type":"text","text":" with a payment intent provider instead of a pre-created intent,"},{"type":"text","text":" "},{"type":"text","text":"the SDK will call "},{"type":"codeVoice","code":"createPaymentIntent()"},{"type":"text","text":" asynchronously when needed. The provider"},{"type":"text","text":" "},{"type":"text","text":"must also supply the basic payment information (amount, currency, customerId) synchronously."}]},{"text":"Usage Example","anchor":"Usage-Example","level":2,"type":"heading"},{"syntax":"swift","code":["class MyPaymentIntentProvider: NSObject, PaymentIntentProvider {","    let amount: NSDecimalNumber = NSDecimalNumber(string: \"99.99\")","    let currency: String = \"USD\"","    let customerId: String? = \"customer_123\"","","    func createPaymentIntent() async throws -> AWXPaymentIntent {","        \/\/ Call your backend to create the payment intent","        let response = try await MyBackendAPI.createPaymentIntent(","            amount: amount.decimalValue,","            currency: currency,","            customerId: customerId","        )","        return response.paymentIntent","    }","}","","\/\/ Use with Session","let provider = MyPaymentIntentProvider()","let session = Session(","    paymentIntentProvider: provider,","    countryCode: \"US\",","    returnURL: \"myapp:\/\/payment\/return\"",")"],"type":"codeListing"},{"text":"Important Notes","anchor":"Important-Notes","level":2,"type":"heading"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"amount"},{"type":"text","text":", "},{"type":"codeVoice","code":"currency"},{"type":"text","text":" and "},{"type":"codeVoice","code":"customerId"},{"type":"text","text":" properties must return values immediately (they cannot be async)"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"The values returned by "},{"type":"codeVoice","code":"amount"},{"type":"text","text":", "},{"type":"codeVoice","code":"currency"},{"type":"text","text":" and "},{"type":"codeVoice","code":"customerId"},{"type":"text","text":" must match the values"},{"type":"text","text":" "},{"type":"text","text":"in the "},{"type":"codeVoice","code":"AWXPaymentIntent"},{"type":"text","text":" returned by "},{"type":"codeVoice","code":"createPaymentIntent()"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"amount"},{"type":"text","text":" should be zero for recurring-only payments (no immediate charge)"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"createPaymentIntent()"},{"type":"text","text":" method will only be called once, and the result is cached"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"If "},{"type":"codeVoice","code":"createPaymentIntent()"},{"type":"text","text":" throws an error, the payment flow will fail"}],"type":"paragraph"}]}]},{"name":"See Also","style":"note","type":"aside","content":[{"inlineContent":[{"text":"","type":"text"},{"code":"Session","type":"codeVoice"},{"text":", ","type":"text"},{"code":"AWXPaymentIntent","type":"codeVoice"}],"type":"paragraph"}]}]}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentIntentProvider","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentIntentProvider/customerId":{"required":true,"title":"customerId","url":"\/documentation\/airwallex\/paymentintentprovider\/customerid","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentIntentProvider\/customerId","abstract":[{"text":"The customer ID associated with this payment, if available.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"customerId"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customerId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentIntentProvider/createPaymentIntent()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createPaymentIntent"},{"kind":"text","text":"() "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPaymentIntent","text":"AWXPaymentIntent"}],"title":"createPaymentIntent()","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentIntentProvider\/createPaymentIntent()","kind":"symbol","url":"\/documentation\/airwallex\/paymentintentprovider\/createpaymentintent()","abstract":[{"text":"Creates a payment intent asynchronously.","type":"text"}],"required":true,"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"createPaymentIntentWithCompletionHandler:"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentIntentProvider":{"kind":"symbol","abstract":[{"text":"A protocol for providing payment intents on-demand during the payment flow.","type":"text"}],"url":"\/documentation\/airwallex\/paymentintentprovider","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentIntentProvider"}],"navigatorTitle":[{"kind":"identifier","text":"PaymentIntentProvider"}],"title":"PaymentIntentProvider","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentIntentProvider"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentIntentProvider/amount":{"url":"\/documentation\/airwallex\/paymentintentprovider\/amount","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentIntentProvider\/amount","abstract":[{"text":"The payment amount as an NSDecimalNumber value.","type":"text"}],"type":"topic","required":true,"role":"symbol","title":"amount","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"amount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSDecimalNumber","preciseIdentifier":"c:objc(cs)NSDecimalNumber"}],"navigatorTitle":[{"kind":"identifier","text":"amount"}],"kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"abstract":[],"kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","url":"\/documentation\/airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentIntentProvider/currency":{"required":true,"title":"currency","url":"\/documentation\/airwallex\/paymentintentprovider\/currency","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentIntentProvider\/currency","abstract":[{"text":"The three-letter ISO currency code (e.g., “USD”, “AUD”, “GBP”).","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"currency"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currency"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"PaymentIntentProvider"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PaymentIntentProvider"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PaymentIntentProvider"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentIntentProvider\/amount","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentIntentProvider\/currency","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentIntentProvider\/customerId"]},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentIntentProvider\/createPaymentIntent()"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PaymentIntentProvider","kind":"identifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentIntentProvider~1customerId\/title","value":"customerId"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentIntentProvider~1customerId\/fragments","value":[{"kind":"identifier","text":"customerId"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentIntentProvider~1createPaymentIntent()\/title","value":"createPaymentIntentWithCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentIntentProvider~1createPaymentIntent()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createPaymentIntentWithCompletionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentIntentProvider\/title","value":"PaymentIntentProvider"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentIntentProvider\/fragments","value":[{"kind":"identifier","text":"PaymentIntentProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentIntentProvider\/navigatorTitle","value":[{"kind":"identifier","text":"PaymentIntentProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentIntentProvider~1amount\/title","value":"amount"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentIntentProvider~1amount\/fragments","value":[{"kind":"identifier","text":"amount"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentIntentProvider~1currency\/title","value":"currency"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentIntentProvider~1currency\/fragments","value":[{"kind":"identifier","text":"currency"}]}]}]}