{"sections":[],"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"LocalizedError.failureReason"},{"text":".","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"failureReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxsession\/validationerror\/failurereason"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession\/ValidationError\/failureReason"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession\/ValidationError"]]},"kind":"symbol","metadata":{"role":"symbol","externalID":"s:10Foundation14LocalizedErrorPAAE13failureReasonSSSgvp::SYNTHESIZED::s:So10AWXSessionC9AirwallexE15ValidationErrorO","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"failureReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"modules":[{"name":"Airwallex","relatedModules":["Foundation"]}],"extendedModule":"Foundation","platforms":[{"name":"iOS","unavailable":false,"beta":false,"introducedAt":"8.0","deprecated":false},{"name":"iPadOS","unavailable":false,"beta":false,"introducedAt":"8.0","deprecated":false},{"name":"Mac Catalyst","unavailable":false,"beta":false,"introducedAt":"8.0","deprecated":false},{"name":"macOS","unavailable":false,"beta":false,"introducedAt":"10.10","deprecated":false},{"name":"tvOS","unavailable":false,"beta":false,"introducedAt":"9.0","deprecated":false},{"beta":false,"deprecated":false,"unavailable":false,"name":"watchOS","introducedAt":"2.0"}],"title":"failureReason","roleHeading":"Instance Property"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSession/ValidationError":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ValidationError","kind":"identifier"}],"navigatorTitle":[{"text":"ValidationError","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxsession\/validationerror","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession\/ValidationError","type":"topic","title":"AWXSession.ValidationError"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSession/ValidationError/failureReason":{"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failureReason","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession\/ValidationError\/failureReason","title":"failureReason","abstract":[],"url":"\/documentation\/airwallex\/awxsession\/validationerror\/failurereason"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","abstract":[],"title":"Airwallex","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSession":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXSession","kind":"identifier"}],"kind":"symbol","title":"AWXSession","type":"topic","abstract":[{"code":"AWXSession","type":"codeVoice"},{"text":" is the base session.","type":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession","url":"\/documentation\/airwallex\/awxsession","navigatorTitle":[{"text":"AWXSession","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"AWXSession","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/title"},{"op":"replace","value":[{"text":"AWXSession","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/fragments"},{"op":"replace","value":[{"text":"AWXSession","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}