{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxpaymentconsent\/requestid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxpaymentconsent\/requestid"]}],"abstract":[{"type":"text","text":"Request ID."}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentConsent\/requestId","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"externalID":"c:objc(cs)AWXPaymentConsent(py)requestId","title":"requestId","role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"requestId"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"symbolKind":"property","modules":[{"name":"Airwallex"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentConsent"]]},"sections":[],"kind":"symbol","references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentConsent/requestId":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"requestId"}],"url":"\/documentation\/airwallex\/awxpaymentconsent\/requestid","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentConsent\/requestId","title":"requestId","abstract":[{"type":"text","text":"Request ID."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"role":"symbol","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentConsent":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"AWXPaymentConsent"}],"url":"\/documentation\/airwallex\/awxpaymentconsent","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentConsent","title":"AWXPaymentConsent","abstract":[{"code":"AWXPaymentConsent","type":"codeVoice"},{"text":" includes the info of payment consent.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentConsent"}],"role":"symbol","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","role":"collection","title":"Airwallex","type":"topic","url":"\/documentation\/airwallex","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"requestId"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"requestId"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"requestId"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentConsent~1requestId\/title","value":"requestId"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentConsent~1requestId\/fragments","value":[{"kind":"identifier","text":"requestId"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentConsent\/title","value":"AWXPaymentConsent"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentConsent\/fragments","value":[{"kind":"identifier","text":"AWXPaymentConsent"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentConsent\/navigatorTitle","value":[{"kind":"identifier","text":"AWXPaymentConsent"}]}]}]}