{"abstract":[{"type":"text","text":"Payment method."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentAttempt\/paymentMethod"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"metadata":{"title":"paymentMethod","modules":[{"name":"Airwallex"}],"roleHeading":"Instance Property","symbolKind":"property","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"paymentMethod"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentMethod"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AWXPaymentMethod","kind":"typeIdentifier","text":"AWXPaymentMethod"}],"externalID":"c:objc(cs)AWXPaymentAttempt(py)paymentMethod"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentMethod"},{"text":": ","kind":"text"},{"text":"AWXPaymentMethod","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod","preciseIdentifier":"c:objc(cs)AWXPaymentMethod"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentAttempt"]]},"variants":[{"paths":["\/documentation\/airwallex\/awxpaymentattempt\/paymentmethod"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxpaymentattempt\/paymentmethod"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentAttempt/paymentMethod":{"title":"paymentMethod","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentAttempt\/paymentMethod","type":"topic","url":"\/documentation\/airwallex\/awxpaymentattempt\/paymentmethod","abstract":[{"text":"Payment method.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"paymentMethod","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentMethod"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AWXPaymentMethod","kind":"typeIdentifier","text":"AWXPaymentMethod"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentAttempt":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentAttempt","abstract":[{"type":"codeVoice","code":"AWXPaymentAttempt"},{"type":"text","text":" includes the information of payment attempt."}],"title":"AWXPaymentAttempt","role":"symbol","navigatorTitle":[{"text":"AWXPaymentAttempt","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/airwallex\/awxpaymentattempt","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPaymentAttempt","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentMethod":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AWXPaymentMethod","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWXPaymentMethod"}],"url":"\/documentation\/airwallex\/awxpaymentmethod","abstract":[{"code":"AWXPaymentMethod","type":"codeVoice"},{"type":"text","text":" includes the information of a payment method."}],"title":"AWXPaymentMethod","role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/airwallex","title":"Airwallex","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"paymentMethod","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"paymentMethod","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AWXPaymentMethod","kind":"typeIdentifier","text":"AWXPaymentMethod","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"paymentMethod"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentAttempt~1paymentMethod\/title","value":"paymentMethod","op":"replace"},{"value":[{"text":"paymentMethod","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentAttempt~1paymentMethod\/fragments","op":"replace"},{"value":"AWXPaymentAttempt","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentAttempt\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentAttempt\/fragments","op":"replace","value":[{"text":"AWXPaymentAttempt","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentAttempt\/navigatorTitle","value":[{"text":"AWXPaymentAttempt","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethod\/title","value":"AWXPaymentMethod"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethod\/fragments","value":[{"kind":"identifier","text":"AWXPaymentMethod"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethod\/navigatorTitle","op":"replace","value":[{"text":"AWXPaymentMethod","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}