{"sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.init(rawValue:)"},{"type":"text","text":"."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/LaunchStyle\/init(rawValue:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxuicontext\/launchstyle\/init(rawvalue:)"]}],"kind":"symbol","metadata":{"roleHeading":"Initializer","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"Airwallex"}],"symbolKind":"init","externalID":"s:9Airwallex12AWXUIContextC11LaunchStyleO8rawValueAESgSi_tcfc","title":"init(rawValue:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/LaunchStyle"]]},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXUIContext/LaunchStyle/init(rawValue:)":{"url":"\/documentation\/airwallex\/awxuicontext\/launchstyle\/init(rawvalue:)","title":"init(rawValue:)","role":"symbol","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/LaunchStyle\/init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXUIContext/LaunchStyle":{"url":"\/documentation\/airwallex\/awxuicontext\/launchstyle","title":"AWXUIContext.LaunchStyle","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LaunchStyle"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/LaunchStyle","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"LaunchStyle"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol","type":"topic","url":"\/documentation\/airwallex","role":"collection","abstract":[],"title":"Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXUIContext":{"url":"\/documentation\/airwallex\/awxuicontext","abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXUIContext","kind":"identifier"}],"navigatorTitle":[{"text":"AWXUIContext","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext","type":"topic","title":"AWXUIContext"}},"variantOverrides":[{"patch":[{"op":"replace","value":"AWXUIContext","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext\/title"},{"op":"replace","value":[{"text":"AWXUIContext","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext\/fragments"},{"op":"replace","value":[{"text":"AWXUIContext","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}