{"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodsResponse\/items","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"Airwallex"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"items"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AWXPaymentMethod","preciseIdentifier":"c:objc(cs)AWXPaymentMethod"},{"kind":"text","text":"]"}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","externalID":"c:objc(cs)AWXGetPaymentMethodsResponse(py)items","navigatorTitle":[{"text":"items","kind":"identifier"}],"title":"items"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"items"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)AWXPaymentMethod","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod","text":"AWXPaymentMethod","kind":"typeIdentifier"},{"text":"] { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxgetpaymentmethodsresponse\/items"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxgetpaymentmethodsresponse\/items"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodsResponse"]]},"kind":"symbol","abstract":[{"text":"Payment methods.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","title":"Airwallex","abstract":[],"type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentMethodsResponse/items":{"url":"\/documentation\/airwallex\/awxgetpaymentmethodsresponse\/items","abstract":[{"text":"Payment methods.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"items","kind":"identifier"},{"text":": [","kind":"text"},{"text":"AWXPaymentMethod","preciseIdentifier":"c:objc(cs)AWXPaymentMethod","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"items","kind":"identifier"}],"kind":"symbol","title":"items","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodsResponse\/items"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentMethod":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod","kind":"symbol","url":"\/documentation\/airwallex\/awxpaymentmethod","title":"AWXPaymentMethod","abstract":[{"type":"codeVoice","code":"AWXPaymentMethod"},{"type":"text","text":" includes the information of a payment method."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPaymentMethod","kind":"identifier"}],"navigatorTitle":[{"text":"AWXPaymentMethod","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentMethodsResponse":{"url":"\/documentation\/airwallex\/awxgetpaymentmethodsresponse","abstract":[{"code":"AWXGetPaymentMethodsResponse","type":"codeVoice"},{"text":" includes the list of payment methods.","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXGetPaymentMethodsResponse","kind":"identifier"}],"navigatorTitle":[{"text":"AWXGetPaymentMethodsResponse","kind":"identifier"}],"kind":"symbol","title":"AWXGetPaymentMethodsResponse","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodsResponse"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"items"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"items","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<AWXPaymentMethod *>","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"items","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodsResponse~1items\/title","value":"items"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodsResponse~1items\/fragments","value":[{"text":"items","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethod\/title","value":"AWXPaymentMethod"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethod\/fragments","value":[{"kind":"identifier","text":"AWXPaymentMethod"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethod\/navigatorTitle","value":[{"text":"AWXPaymentMethod","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodsResponse\/title","value":"AWXGetPaymentMethodsResponse"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodsResponse\/fragments","value":[{"kind":"identifier","text":"AWXGetPaymentMethodsResponse"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodsResponse\/navigatorTitle","value":[{"text":"AWXGetPaymentMethodsResponse","kind":"identifier"}]}]}]}