{"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Transaction code."}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypeRequest"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxgetpaymentmethodtyperequest\/transactionmode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxgetpaymentmethodtyperequest\/transactionmode"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypeRequest\/transactionMode"},"metadata":{"title":"transactionMode","role":"symbol","modules":[{"name":"Airwallex"}],"externalID":"c:objc(cs)AWXGetPaymentMethodTypeRequest(py)transactionMode","symbolKind":"property","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"transactionMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"transactionMode","kind":"identifier"}]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"transactionMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentMethodTypeRequest":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXGetPaymentMethodTypeRequest"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWXGetPaymentMethodTypeRequest"}],"title":"AWXGetPaymentMethodTypeRequest","url":"\/documentation\/airwallex\/awxgetpaymentmethodtyperequest","abstract":[{"type":"codeVoice","code":"AWXGetPaymentMethodTypeRequest"},{"text":" includes all of the parameters needed to get payment method type.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypeRequest","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentMethodTypeRequest/transactionMode":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"transactionMode"}],"type":"topic","url":"\/documentation\/airwallex\/awxgetpaymentmethodtyperequest\/transactionmode","title":"transactionMode","role":"symbol","abstract":[{"text":"Transaction code.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypeRequest\/transactionMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"transactionMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","abstract":[],"title":"Airwallex","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"transactionMode","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"transactionMode","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"transactionMode","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"AWXGetPaymentMethodTypeRequest","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypeRequest\/title"},{"value":[{"kind":"identifier","text":"AWXGetPaymentMethodTypeRequest"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypeRequest\/fragments"},{"value":[{"kind":"identifier","text":"AWXGetPaymentMethodTypeRequest"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypeRequest\/navigatorTitle"},{"value":"transactionMode","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypeRequest~1transactionMode\/title"},{"value":[{"kind":"identifier","text":"transactionMode"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypeRequest~1transactionMode\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}