{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxproviderdelegate\/provider(_:shouldinsert:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxproviderdelegate\/provider(_:shouldinsert:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXProviderDelegate"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"modules":[{"name":"Airwallex"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"provider","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)AWXDefaultProvider","text":"AWXDefaultProvider","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"shouldInsert","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"provider:shouldInsertViewController:","kind":"identifier"}],"title":"provider(_:shouldInsert:)","platforms":[{"deprecated":false,"beta":false,"unavailable":false,"name":"iOS","introducedAt":"2.0"},{"deprecated":false,"beta":false,"unavailable":false,"name":"iPadOS","introducedAt":"2.0"},{"deprecated":false,"beta":false,"unavailable":false,"name":"Mac Catalyst","introducedAt":"2.0"}],"externalID":"c:objc(pl)AWXProviderDelegate(im)provider:shouldInsertViewController:","symbolKind":"method"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXProviderDelegate\/provider(_:shouldInsert:)"},"abstract":[{"text":"This method is called when new controller is required. (as child view controller)","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"provider","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"provider","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider","text":"AWXDefaultProvider","preciseIdentifier":"c:objc(cs)AWXDefaultProvider","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"shouldInsert","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The provider handling payment."}]}],"name":"provider"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The view controller will be presented.","type":"text"}]}],"name":"controller"}]}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXDefaultProvider":{"navigatorTitle":[{"kind":"identifier","text":"AWXDefaultProvider"}],"abstract":[{"text":"A provider which handles payment business.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXDefaultProvider"}],"url":"\/documentation\/airwallex\/awxdefaultprovider","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider","kind":"symbol","title":"AWXDefaultProvider","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXProviderDelegate/provider(_:shouldInsert:)":{"url":"\/documentation\/airwallex\/awxproviderdelegate\/provider(_:shouldinsert:)","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXProviderDelegate\/provider(_:shouldInsert:)","kind":"symbol","role":"symbol","title":"provider(_:shouldInsert:)","navigatorTitle":[{"kind":"identifier","text":"provider:shouldInsertViewController:"}],"type":"topic","abstract":[{"type":"text","text":"This method is called when new controller is required. (as child view controller)"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"provider"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)AWXDefaultProvider","kind":"typeIdentifier","text":"AWXDefaultProvider"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldInsert"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"kind":"text","text":")"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXProviderDelegate":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXProviderDelegate","title":"AWXProviderDelegate","abstract":[{"text":"A delegate which handles checkout results.","type":"text"}],"url":"\/documentation\/airwallex\/awxproviderdelegate","navigatorTitle":[{"kind":"identifier","text":"AWXProviderDelegate"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXProviderDelegate","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","abstract":[],"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/airwallex"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"replace","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"provider:shouldInsertViewController:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"provider:shouldInsertViewController:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"provider:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AWXDefaultProvider","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider","preciseIdentifier":"c:objc(cs)AWXDefaultProvider"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"provider"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldInsertViewController:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"name":"provider","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The provider handling payment."}]}]},{"name":"controller","content":[{"inlineContent":[{"type":"text","text":"The view controller will be presented."}],"type":"paragraph"}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"AWXDefaultProvider","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider\/title"},{"value":[{"kind":"identifier","text":"AWXDefaultProvider"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider\/fragments"},{"value":[{"kind":"identifier","text":"AWXDefaultProvider"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider\/navigatorTitle"},{"value":"provider:shouldInsertViewController:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXProviderDelegate~1provider(_:shouldInsert:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"provider:shouldInsertViewController:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXProviderDelegate~1provider(_:shouldInsert:)\/fragments"},{"value":"AWXProviderDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXProviderDelegate\/title"},{"value":[{"text":"AWXProviderDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXProviderDelegate\/fragments"},{"value":[{"kind":"identifier","text":"AWXProviderDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXProviderDelegate\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}