{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session\/init(paymentIntentProvider:countryCode:applePayOptions:autoCapture:autoSaveCardForFuturePayments:billing:hidePaymentConsents:lang:paymentMethods:paymentConsentOptions:requiredBillingContactFields:returnURL:)"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"paymentIntentProvider","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PaymentIntentProvider","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentIntentProvider","kind":"typeIdentifier","preciseIdentifier":"c:@M@Airwallex@objc(pl)PaymentIntentProvider"},{"text":", ","kind":"text"},{"text":"countryCode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"applePayOptions","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AWXApplePayOptions","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXApplePayOptions"},{"text":"? = nil, ","kind":"text"},{"text":"autoCapture","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = true, ","kind":"text"},{"text":"autoSaveCardForFuturePayments","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" = true, ","kind":"text"},{"text":"billing","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AWXPlaceDetails","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPlaceDetails","text":"AWXPlaceDetails","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"hidePaymentConsents","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" = false, ","kind":"text"},{"text":"lang","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"paymentMethods","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]? = nil, ","kind":"text"},{"text":"paymentConsentOptions","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentConsentOptions","text":"PaymentConsentOptions","preciseIdentifier":"c:@M@Airwallex@objc(cs)PaymentConsentOptions","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"requiredBillingContactFields","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/RequiredBillingContactFields","text":"RequiredBillingContactFields","preciseIdentifier":"c:@E@AWXRequiredBillingContactFields","kind":"typeIdentifier"},{"text":" = .name, ","kind":"text"},{"text":"returnURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? = nil)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"An object conforming to ","type":"text"},{"code":"PaymentIntentProvider","type":"codeVoice"},{"text":" protocol that will create","type":"text"},{"text":" ","type":"text"},{"text":"the payment intent when needed. The provider must supply currency,","type":"text"},{"text":" ","type":"text"},{"text":"and customerId properties immediately, and create the actual intent asynchronously.","type":"text"}],"type":"paragraph"}],"name":"paymentIntentProvider"},{"content":[{"inlineContent":[{"text":"The ISO 3166-1 alpha-2 country code (e.g., “US”, “AU”, “GB”).","type":"text"}],"type":"paragraph"}],"name":"countryCode"},{"content":[{"inlineContent":[{"type":"text","text":"Configuration for Apple Pay integration. Default: nil."}],"type":"paragraph"}],"name":"applePayOptions"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Whether to automatically capture the payment after successful authorization. Default: true."}]}],"name":"autoCapture"},{"content":[{"inlineContent":[{"type":"text","text":"Whether to automatically save card details for future payments. Default: true."}],"type":"paragraph"}],"name":"autoSaveCardForFuturePayments"},{"content":[{"inlineContent":[{"type":"text","text":"Pre-filled billing address information. Default: nil."}],"type":"paragraph"}],"name":"billing"},{"content":[{"inlineContent":[{"text":"Whether to hide previously saved payment methods. Default: false.","type":"text"}],"type":"paragraph"}],"name":"hidePaymentConsents"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Language code for UI localization. Default: system language.","type":"text"}]}],"name":"lang"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Array of payment method identifiers to limit display. Default: nil."}]}],"name":"paymentMethods"},{"content":[{"inlineContent":[{"type":"text","text":"Configuration for recurring payments. Default: nil."}],"type":"paragraph"}],"name":"paymentConsentOptions"},{"content":[{"inlineContent":[{"type":"text","text":"Which billing contact fields are mandatory. Default: .name."}],"type":"paragraph"}],"name":"requiredBillingContactFields"},{"content":[{"inlineContent":[{"type":"text","text":"The URL to redirect users after payment completion for redirect payments."}],"type":"paragraph"}],"name":"returnURL"}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"This initializer allows you to defer the creation of the payment intent until just before"},{"type":"text","text":" "},{"type":"text","text":"payment confirmation or when it is required."}],"type":"paragraph"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/session\/init(paymentintentprovider:countrycode:applepayoptions:autocapture:autosavecardforfuturepayments:billing:hidepaymentconsents:lang:paymentmethods:paymentconsentoptions:requiredbillingcontactfields:returnurl:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/session\/init(paymentintentprovider:countrycode:applepayoptions:autocapture:autosavecardforfuturepayments:billing:hidepaymentconsents:lang:paymentmethods:paymentconsentoptions:requiredbillingcontactfields:returnurl:)"]}],"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"paymentIntentProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@Airwallex@objc(pl)PaymentIntentProvider","text":"PaymentIntentProvider"},{"kind":"text","text":", "},{"kind":"externalParam","text":"countryCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"applePayOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXApplePayOptions","text":"AWXApplePayOptions"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"autoCapture"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"autoSaveCardForFuturePayments"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"billing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPlaceDetails","text":"AWXPlaceDetails"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"hidePaymentConsents"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"lang"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"paymentMethods"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"paymentConsentOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@Airwallex@objc(cs)PaymentConsentOptions","text":"PaymentConsentOptions"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"requiredBillingContactFields"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@AWXRequiredBillingContactFields","text":"RequiredBillingContactFields"},{"kind":"text","text":", "},{"kind":"externalParam","text":"returnURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"kind":"identifier","text":"initWithPaymentIntentProvider:countryCode:applePayOptions:autoCapture:autoSaveCardForFuturePayments:billing:hidePaymentConsents:lang:paymentMethods:paymentConsentOptions:requiredBillingContactFields:returnURL:"}],"role":"symbol","roleHeading":"Initializer","title":"init(paymentIntentProvider:countryCode:applePayOptions:autoCapture:autoSaveCardForFuturePayments:billing:hidePaymentConsents:lang:paymentMethods:paymentConsentOptions:requiredBillingContactFields:returnURL:)","externalID":"c:@M@Airwallex@objc(cs)Session(im)initWithPaymentIntentProvider:countryCode:applePayOptions:autoCapture:autoSaveCardForFuturePayments:billing:hidePaymentConsents:lang:paymentMethods:paymentConsentOptions:requiredBillingContactFields:returnURL:","symbolKind":"init","modules":[{"name":"Airwallex"}]},"abstract":[{"text":"Creates a new unified Session with delayed payment intent creation.","type":"text"}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentIntentProvider":{"navigatorTitle":[{"kind":"identifier","text":"PaymentIntentProvider"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentIntentProvider","role":"symbol","title":"PaymentIntentProvider","abstract":[{"type":"text","text":"A protocol for providing payment intents on-demand during the payment flow."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentIntentProvider"}],"kind":"symbol","url":"\/documentation\/airwallex\/paymentintentprovider","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPlaceDetails":{"abstract":[{"code":"AWXPlaceDetails","type":"codeVoice"},{"type":"text","text":" includes the information of a billing address."}],"url":"\/documentation\/airwallex\/awxplacedetails","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPlaceDetails","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPlaceDetails","navigatorTitle":[{"kind":"identifier","text":"AWXPlaceDetails"}],"kind":"symbol","title":"AWXPlaceDetails"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/Session/init(paymentIntentProvider:countryCode:applePayOptions:autoCapture:autoSaveCardForFuturePayments:billing:hidePaymentConsents:lang:paymentMethods:paymentConsentOptions:requiredBillingContactFields:returnURL:)":{"kind":"symbol","url":"\/documentation\/airwallex\/session\/init(paymentintentprovider:countrycode:applepayoptions:autocapture:autosavecardforfuturepayments:billing:hidepaymentconsents:lang:paymentmethods:paymentconsentoptions:requiredbillingcontactfields:returnurl:)","navigatorTitle":[{"kind":"identifier","text":"initWithPaymentIntentProvider:countryCode:applePayOptions:autoCapture:autoSaveCardForFuturePayments:billing:hidePaymentConsents:lang:paymentMethods:paymentConsentOptions:requiredBillingContactFields:returnURL:"}],"title":"init(paymentIntentProvider:countryCode:applePayOptions:autoCapture:autoSaveCardForFuturePayments:billing:hidePaymentConsents:lang:paymentMethods:paymentConsentOptions:requiredBillingContactFields:returnURL:)","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session\/init(paymentIntentProvider:countryCode:applePayOptions:autoCapture:autoSaveCardForFuturePayments:billing:hidePaymentConsents:lang:paymentMethods:paymentConsentOptions:requiredBillingContactFields:returnURL:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"paymentIntentProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@Airwallex@objc(pl)PaymentIntentProvider","text":"PaymentIntentProvider"},{"kind":"text","text":", "},{"kind":"externalParam","text":"countryCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"applePayOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXApplePayOptions","text":"AWXApplePayOptions"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"autoCapture"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"autoSaveCardForFuturePayments"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"billing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPlaceDetails","text":"AWXPlaceDetails"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"hidePaymentConsents"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"lang"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"paymentMethods"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"paymentConsentOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@Airwallex@objc(cs)PaymentConsentOptions","text":"PaymentConsentOptions"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"requiredBillingContactFields"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@AWXRequiredBillingContactFields","text":"RequiredBillingContactFields"},{"kind":"text","text":", "},{"kind":"externalParam","text":"returnURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?)"}],"abstract":[{"text":"Creates a new unified Session with delayed payment intent creation.","type":"text"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentConsentOptions":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentConsentOptions","kind":"symbol","url":"\/documentation\/airwallex\/paymentconsentoptions","type":"topic","abstract":[{"text":"Options for payment consents","type":"text"}],"role":"symbol","title":"PaymentConsentOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentConsentOptions"}],"navigatorTitle":[{"kind":"identifier","text":"PaymentConsentOptions"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/RequiredBillingContactFields":{"title":"RequiredBillingContactFields","url":"\/documentation\/airwallex\/requiredbillingcontactfields","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/RequiredBillingContactFields","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RequiredBillingContactFields","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"RequiredBillingContactFields","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","type":"topic","url":"\/documentation\/airwallex","kind":"symbol","abstract":[],"title":"Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXApplePayOptions":{"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions","title":"AWXApplePayOptions","url":"\/documentation\/airwallex\/awxapplepayoptions","abstract":[{"text":"Object used to construct PKPaymentRequest for Apple Pay.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"AWXApplePayOptions"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXApplePayOptions"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/Session":{"url":"\/documentation\/airwallex\/session","abstract":[{"type":"codeVoice","code":"Session"},{"type":"text","text":" is a specialized subclass of "},{"type":"codeVoice","code":"AWXSession"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Session"}],"navigatorTitle":[{"kind":"identifier","text":"Session"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session","title":"Session","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initWithPaymentIntentProvider:countryCode:applePayOptions:autoCapture:autoSaveCardForFuturePayments:billing:hidePaymentConsents:lang:paymentMethods:paymentConsentOptions:requiredBillingContactFields:returnURL:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPaymentIntentProvider:countryCode:applePayOptions:autoCapture:autoSaveCardForFuturePayments:billing:hidePaymentConsents:lang:paymentMethods:paymentConsentOptions:requiredBillingContactFields:returnURL:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithPaymentIntentProvider:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<PaymentIntentProvider>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@Airwallex@objc(pl)PaymentIntentProvider"},{"text":") ","kind":"text"},{"text":"paymentIntentProvider","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"countryCode:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"countryCode","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"applePayOptions:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)AWXApplePayOptions","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions","text":"AWXApplePayOptions","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"applePayOptions","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"autoCapture:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"autoCapture"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoSaveCardForFuturePayments:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"autoSaveCardForFuturePayments"},{"kind":"text","text":" "},{"kind":"identifier","text":"billing:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPlaceDetails","preciseIdentifier":"c:objc(cs)AWXPlaceDetails","text":"AWXPlaceDetails"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"billing"},{"kind":"text","text":" "},{"kind":"identifier","text":"hidePaymentConsents:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"hidePaymentConsents"},{"kind":"text","text":" "},{"kind":"identifier","text":"lang:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"lang"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentMethods:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSString *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"paymentMethods"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentConsentOptions:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentConsentOptions","preciseIdentifier":"c:@M@Airwallex@objc(cs)PaymentConsentOptions","text":"PaymentConsentOptions"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"paymentConsentOptions"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiredBillingContactFields:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/RequiredBillingContactFields","preciseIdentifier":"c:@E@AWXRequiredBillingContactFields","text":"AWXRequiredBillingContactFields"},{"kind":"text","text":") "},{"kind":"internalParam","text":"requiredBillingContactFields"},{"kind":"text","text":" "},{"kind":"identifier","text":"returnURL:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"returnURL"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"An object conforming to "},{"type":"codeVoice","code":"PaymentIntentProvider"},{"type":"text","text":" protocol that will create"},{"type":"text","text":" "},{"type":"text","text":"the payment intent when needed. The provider must supply currency,"},{"type":"text","text":" "},{"type":"text","text":"and customerId properties immediately, and create the actual intent asynchronously."}],"type":"paragraph"}],"name":"paymentIntentProvider"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The ISO 3166-1 alpha-2 country code (e.g., “US”, “AU”, “GB”)."}]}],"name":"countryCode"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Configuration for Apple Pay integration. Default: nil."}]}],"name":"applePayOptions"},{"content":[{"inlineContent":[{"type":"text","text":"Whether to automatically capture the payment after successful authorization. Default: true."}],"type":"paragraph"}],"name":"autoCapture"},{"content":[{"inlineContent":[{"text":"Whether to automatically save card details for future payments. Default: true.","type":"text"}],"type":"paragraph"}],"name":"autoSaveCardForFuturePayments"},{"content":[{"inlineContent":[{"type":"text","text":"Pre-filled billing address information. Default: nil."}],"type":"paragraph"}],"name":"billing"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Whether to hide previously saved payment methods. Default: false.","type":"text"}]}],"name":"hidePaymentConsents"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Language code for UI localization. Default: system language."}]}],"name":"lang"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Array of payment method identifiers to limit display. Default: nil.","type":"text"}]}],"name":"paymentMethods"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Configuration for recurring payments. Default: nil."}]}],"name":"paymentConsentOptions"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Which billing contact fields are mandatory. Default: .name."}]}],"name":"requiredBillingContactFields"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The URL to redirect users after payment completion for redirect payments."}]}],"name":"returnURL"}]}},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentIntentProvider\/title","op":"replace","value":"PaymentIntentProvider"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentIntentProvider\/fragments","op":"replace","value":[{"text":"PaymentIntentProvider","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentIntentProvider\/navigatorTitle","op":"replace","value":[{"text":"PaymentIntentProvider","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPlaceDetails\/title","op":"replace","value":"AWXPlaceDetails"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPlaceDetails\/fragments","op":"replace","value":[{"text":"AWXPlaceDetails","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPlaceDetails\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AWXPlaceDetails"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session~1init(paymentIntentProvider:countryCode:applePayOptions:autoCapture:autoSaveCardForFuturePayments:billing:hidePaymentConsents:lang:paymentMethods:paymentConsentOptions:requiredBillingContactFields:returnURL:)\/title","op":"replace","value":"initWithPaymentIntentProvider:countryCode:applePayOptions:autoCapture:autoSaveCardForFuturePayments:billing:hidePaymentConsents:lang:paymentMethods:paymentConsentOptions:requiredBillingContactFields:returnURL:"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session~1init(paymentIntentProvider:countryCode:applePayOptions:autoCapture:autoSaveCardForFuturePayments:billing:hidePaymentConsents:lang:paymentMethods:paymentConsentOptions:requiredBillingContactFields:returnURL:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithPaymentIntentProvider:countryCode:applePayOptions:autoCapture:autoSaveCardForFuturePayments:billing:hidePaymentConsents:lang:paymentMethods:paymentConsentOptions:requiredBillingContactFields:returnURL:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentConsentOptions\/title","op":"replace","value":"PaymentConsentOptions"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentConsentOptions\/fragments","op":"replace","value":[{"kind":"identifier","text":"PaymentConsentOptions"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentConsentOptions\/navigatorTitle","op":"replace","value":[{"text":"PaymentConsentOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1RequiredBillingContactFields\/title","op":"replace","value":"AWXRequiredBillingContactFields"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1RequiredBillingContactFields\/fragments","op":"replace","value":[{"text":"AWXRequiredBillingContactFields","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1RequiredBillingContactFields\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AWXRequiredBillingContactFields"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions\/title","op":"replace","value":"AWXApplePayOptions"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions\/fragments","op":"replace","value":[{"text":"AWXApplePayOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions\/navigatorTitle","op":"replace","value":[{"text":"AWXApplePayOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session\/title","op":"replace","value":"Session"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session\/fragments","op":"replace","value":[{"kind":"identifier","text":"Session"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"Session"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}