{"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session\/paymentConsentOptions","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/session\/paymentconsentoptions"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/session\/paymentconsentoptions"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentConsentOptions"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentConsentOptions","preciseIdentifier":"c:@M@Airwallex@objc(cs)PaymentConsentOptions","kind":"typeIdentifier","text":"PaymentConsentOptions"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","navigatorTitle":[{"text":"paymentConsentOptions","kind":"identifier"}],"modules":[{"name":"Airwallex"}],"title":"paymentConsentOptions","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentConsentOptions","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@Airwallex@objc(cs)PaymentConsentOptions","text":"PaymentConsentOptions","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"externalID":"c:@M@Airwallex@objc(cs)Session(py)paymentConsentOptions","symbolKind":"property"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session"]]},"kind":"symbol","abstract":[{"text":"Required for recurring payment","type":"text"}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/Session":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Session","kind":"identifier"}],"title":"Session","url":"\/documentation\/airwallex\/session","abstract":[{"type":"codeVoice","code":"Session"},{"text":" is a specialized subclass of ","type":"text"},{"type":"codeVoice","code":"AWXSession"}],"navigatorTitle":[{"text":"Session","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/Session/paymentConsentOptions":{"title":"paymentConsentOptions","navigatorTitle":[{"kind":"identifier","text":"paymentConsentOptions"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentConsentOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@Airwallex@objc(cs)PaymentConsentOptions","text":"PaymentConsentOptions"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session\/paymentConsentOptions","abstract":[{"type":"text","text":"Required for recurring payment"}],"type":"topic","url":"\/documentation\/airwallex\/session\/paymentconsentoptions","role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"title":"Airwallex","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/airwallex","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentConsentOptions":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentConsentOptions","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentConsentOptions"}],"abstract":[{"type":"text","text":"Options for payment consents"}],"url":"\/documentation\/airwallex\/paymentconsentoptions","title":"PaymentConsentOptions","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PaymentConsentOptions"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"paymentConsentOptions"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"paymentConsentOptions"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@Airwallex@objc(cs)PaymentConsentOptions","text":"PaymentConsentOptions","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentConsentOptions"},{"text":" * ","kind":"text"},{"text":"paymentConsentOptions","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session\/title","op":"replace","value":"Session"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session\/fragments","op":"replace","value":[{"text":"Session","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"Session"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session~1paymentConsentOptions\/title","op":"replace","value":"paymentConsentOptions"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session~1paymentConsentOptions\/fragments","op":"replace","value":[{"text":"paymentConsentOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentConsentOptions\/title","op":"replace","value":"PaymentConsentOptions"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentConsentOptions\/fragments","op":"replace","value":[{"kind":"identifier","text":"PaymentConsentOptions"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentConsentOptions\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"PaymentConsentOptions"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}