{"abstract":[{"text":"Inherited from ","type":"text"},{"code":"AWXProviderDelegate.provider(_:shouldPresent:forceToDismiss:withAnimation:)","type":"codeVoice"},{"text":".","type":"text"}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler\/provider(_:shouldPresent:forceToDismiss:withAnimation:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/airwallex\/paymentsessionhandler\/provider(_:shouldpresent:forcetodismiss:withanimation:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/paymentsessionhandler\/provider(_:shouldpresent:forcetodismiss:withanimation:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"provider"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"provider","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"AWXDefaultProvider","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXDefaultProvider"},{"text":", ","kind":"text"},{"text":"shouldPresent","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"controller","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"forceToDismiss"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withAnimation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"navigatorTitle":[{"text":"provider:shouldPresentViewController:forceToDismiss:withAnimation:","kind":"identifier"}],"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"provider","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AWXDefaultProvider","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXDefaultProvider"},{"kind":"text","text":", "},{"text":"shouldPresent","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"forceToDismiss"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"withAnimation","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"modules":[{"name":"Airwallex"}],"extendedModule":"Airwallex","roleHeading":"Instance Method","title":"provider(_:shouldPresent:forceToDismiss:withAnimation:)","role":"symbol","externalID":"c:@CM@Airwallex@objc(cs)PaymentSessionHandler(im)provider:shouldPresentViewController:forceToDismiss:withAnimation:"},"sections":[],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXDefaultProvider":{"abstract":[{"text":"A provider which handles payment business.","type":"text"}],"title":"AWXDefaultProvider","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider","navigatorTitle":[{"kind":"identifier","text":"AWXDefaultProvider"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXDefaultProvider"}],"kind":"symbol","url":"\/documentation\/airwallex\/awxdefaultprovider","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentSessionHandler":{"title":"PaymentSessionHandler","abstract":[{"type":"text","text":"A low-level API handler for managing Airwallex payment sessions."}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler","navigatorTitle":[{"text":"PaymentSessionHandler","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PaymentSessionHandler","kind":"identifier"}],"type":"topic","url":"\/documentation\/airwallex\/paymentsessionhandler","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentSessionHandler/provider(_:shouldPresent:forceToDismiss:withAnimation:)":{"title":"provider(_:shouldPresent:forceToDismiss:withAnimation:)","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler\/provider(_:shouldPresent:forceToDismiss:withAnimation:)","navigatorTitle":[{"kind":"identifier","text":"provider:shouldPresentViewController:forceToDismiss:withAnimation:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"provider"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXDefaultProvider","text":"AWXDefaultProvider"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldPresent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"forceToDismiss"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withAnimation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"kind":"symbol","url":"\/documentation\/airwallex\/paymentsessionhandler\/provider(_:shouldpresent:forcetodismiss:withanimation:)","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","abstract":[],"type":"topic","kind":"symbol","title":"Airwallex","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"provider:shouldPresentViewController:forceToDismiss:withAnimation:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"provider:shouldPresentViewController:forceToDismiss:withAnimation:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"provider:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider","text":"AWXDefaultProvider","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXDefaultProvider"},{"text":" *) ","kind":"text"},{"text":"provider","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"shouldPresentViewController:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"forceToDismiss:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"forceToDismiss","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"withAnimation:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"withAnimation","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider\/title","value":"AWXDefaultProvider"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider\/fragments","op":"replace","value":[{"kind":"identifier","text":"AWXDefaultProvider"}]},{"value":[{"kind":"identifier","text":"AWXDefaultProvider"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider\/navigatorTitle","op":"replace"},{"value":"PaymentSessionHandler","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler\/fragments","op":"replace","value":[{"text":"PaymentSessionHandler","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"PaymentSessionHandler"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler~1provider(_:shouldPresent:forceToDismiss:withAnimation:)\/title","op":"replace","value":"provider:shouldPresentViewController:forceToDismiss:withAnimation:"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler~1provider(_:shouldPresent:forceToDismiss:withAnimation:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"provider:shouldPresentViewController:forceToDismiss:withAnimation:","kind":"identifier"}],"op":"replace"}]}]}