{"kind":"symbol","abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"AWXProviderDelegate.provider(_:didCompleteWithPaymentConsentId:)"},{"text":".","type":"text"}],"metadata":{"extendedModule":"Airwallex","role":"symbol","externalID":"c:@CM@Airwallex@objc(cs)PaymentSessionHandler(im)provider:didCompleteWithPaymentConsentId:","symbolKind":"method","title":"provider(_:didCompleteWithPaymentConsentId:)","navigatorTitle":[{"kind":"identifier","text":"provider:didCompleteWithPaymentConsentId:"}],"roleHeading":"Instance Method","modules":[{"name":"Airwallex"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"provider"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AWXDefaultProvider","preciseIdentifier":"c:objc(cs)AWXDefaultProvider"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didCompleteWithPaymentConsentId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/paymentsessionhandler\/provider(_:didcompletewithpaymentconsentid:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/paymentsessionhandler\/provider(_:didcompletewithpaymentconsentid:)"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"provider"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"provider"},{"kind":"text","text":": "},{"text":"AWXDefaultProvider","preciseIdentifier":"c:objc(cs)AWXDefaultProvider","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didCompleteWithPaymentConsentId"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"paymentConsentId"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler\/provider(_:didCompleteWithPaymentConsentId:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentSessionHandler/provider(_:didCompleteWithPaymentConsentId:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"provider"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXDefaultProvider","text":"AWXDefaultProvider"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didCompleteWithPaymentConsentId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"title":"provider(_:didCompleteWithPaymentConsentId:)","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler\/provider(_:didCompleteWithPaymentConsentId:)","kind":"symbol","url":"\/documentation\/airwallex\/paymentsessionhandler\/provider(_:didcompletewithpaymentconsentid:)","abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"provider:didCompleteWithPaymentConsentId:"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentSessionHandler":{"abstract":[{"text":"A low-level API handler for managing Airwallex payment sessions.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler","title":"PaymentSessionHandler","navigatorTitle":[{"text":"PaymentSessionHandler","kind":"identifier"}],"url":"\/documentation\/airwallex\/paymentsessionhandler","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentSessionHandler"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"abstract":[],"kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","url":"\/documentation\/airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXDefaultProvider":{"abstract":[{"type":"text","text":"A provider which handles payment business."}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider","title":"AWXDefaultProvider","navigatorTitle":[{"kind":"identifier","text":"AWXDefaultProvider"}],"url":"\/documentation\/airwallex\/awxdefaultprovider","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXDefaultProvider","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"provider:didCompleteWithPaymentConsentId:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"provider:didCompleteWithPaymentConsentId:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"provider:"},{"kind":"text","text":"("},{"text":"AWXDefaultProvider","preciseIdentifier":"c:objc(cs)AWXDefaultProvider","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"provider"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didCompleteWithPaymentConsentId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"paymentConsentId"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"provider:didCompleteWithPaymentConsentId:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler~1provider(_:didCompleteWithPaymentConsentId:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"provider:didCompleteWithPaymentConsentId:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler~1provider(_:didCompleteWithPaymentConsentId:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler\/title","value":"PaymentSessionHandler"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler\/fragments","value":[{"kind":"identifier","text":"PaymentSessionHandler"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler\/navigatorTitle","value":[{"text":"PaymentSessionHandler","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider\/title","value":"AWXDefaultProvider"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider\/fragments","value":[{"kind":"identifier","text":"AWXDefaultProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider\/navigatorTitle","value":[{"text":"AWXDefaultProvider","kind":"identifier"}]}]}]}