{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/paymentsessionhandler\/startcardpayment(with:billing:savecard:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/paymentsessionhandler\/startcardpayment(with:billing:savecard:)"]}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler\/startCardPayment(with:billing:saveCard:)","interfaceLanguage":"swift"},"metadata":{"role":"symbol","symbolKind":"method","modules":[{"name":"Airwallex"}],"navigatorTitle":[{"kind":"identifier","text":"startCardPaymentWith:billing:saveCard:"}],"title":"startCardPayment(with:billing:saveCard:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startCardPayment"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWXCard","preciseIdentifier":"c:objc(cs)AWXCard"},{"kind":"text","text":", "},{"kind":"externalParam","text":"billing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWXPlaceDetails","preciseIdentifier":"c:objc(cs)AWXPlaceDetails"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"saveCard"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"extendedModule":"Airwallex","externalID":"c:@CM@Airwallex@objc(cs)PaymentSessionHandler(im)startCardPaymentWith:billing:saveCard:","roleHeading":"Instance Method"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startCardPayment","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"card","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCard","text":"AWXCard","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXCard"},{"text":", ","kind":"text"},{"text":"billing","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AWXPlaceDetails","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPlaceDetails","preciseIdentifier":"c:objc(cs)AWXPlaceDetails","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"saveCard","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":" = false)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The card details required for processing the payment."}]}],"name":"card"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Billing information for the transaction (optional).","type":"text"}]}],"name":"billing"},{"content":[{"inlineContent":[{"text":"A boolean indicating whether to save the card for future transactions (default is ","type":"text"},{"code":"false","type":"codeVoice"},{"type":"text","text":")."}],"type":"paragraph"}],"name":"saveCard"}],"kind":"parameters"}],"abstract":[{"text":"Initiates a card payment transaction.","type":"text"},{"text":" ","type":"text"},{"text":"This method sets up and confirms a card-based payment, including optional billing and card-saving preferences.","type":"text"}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentSessionHandler/startCardPayment(with:billing:saveCard:)":{"abstract":[{"text":"Initiates a card payment transaction.","type":"text"},{"text":" ","type":"text"},{"text":"This method sets up and confirms a card-based payment, including optional billing and card-saving preferences.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler\/startCardPayment(with:billing:saveCard:)","title":"startCardPayment(with:billing:saveCard:)","navigatorTitle":[{"text":"startCardPaymentWith:billing:saveCard:","kind":"identifier"}],"url":"\/documentation\/airwallex\/paymentsessionhandler\/startcardpayment(with:billing:savecard:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startCardPayment","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AWXCard","text":"AWXCard","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"billing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWXPlaceDetails","preciseIdentifier":"c:objc(cs)AWXPlaceDetails"},{"text":"?, ","kind":"text"},{"text":"saveCard","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentSessionHandler":{"abstract":[{"text":"A low-level API handler for managing Airwallex payment sessions.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler","title":"PaymentSessionHandler","navigatorTitle":[{"text":"PaymentSessionHandler","kind":"identifier"}],"url":"\/documentation\/airwallex\/paymentsessionhandler","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentSessionHandler"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"abstract":[],"kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","url":"\/documentation\/airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPlaceDetails":{"type":"topic","title":"AWXPlaceDetails","url":"\/documentation\/airwallex\/awxplacedetails","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPlaceDetails","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPlaceDetails","abstract":[{"type":"codeVoice","code":"AWXPlaceDetails"},{"text":" includes the information of a billing address.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"AWXPlaceDetails","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCard":{"kind":"symbol","url":"\/documentation\/airwallex\/awxcard","role":"symbol","type":"topic","navigatorTitle":[{"text":"AWXCard","kind":"identifier"}],"title":"AWXCard","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCard","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AWXCard"}],"abstract":[{"code":"AWXCard","type":"codeVoice"},{"text":" includes the information of a card.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"startCardPaymentWith:billing:saveCard:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"startCardPaymentWith:billing:saveCard:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"startCardPaymentWith:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCard","text":"AWXCard","preciseIdentifier":"c:objc(cs)AWXCard"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"card"},{"kind":"text","text":" "},{"kind":"identifier","text":"billing:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPlaceDetails","text":"AWXPlaceDetails","preciseIdentifier":"c:objc(cs)AWXPlaceDetails"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"billing"},{"kind":"text","text":" "},{"kind":"identifier","text":"saveCard:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"saveCard"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The card details required for processing the payment."}],"type":"paragraph"}],"name":"card"},{"content":[{"inlineContent":[{"type":"text","text":"Billing information for the transaction (optional)."}],"type":"paragraph"}],"name":"billing"},{"content":[{"inlineContent":[{"type":"text","text":"A boolean indicating whether to save the card for future transactions (default is "},{"type":"codeVoice","code":"false"},{"type":"text","text":")."}],"type":"paragraph"}],"name":"saveCard"}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"startCardPaymentWith:billing:saveCard:","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler~1startCardPayment(with:billing:saveCard:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"startCardPaymentWith:billing:saveCard:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler~1startCardPayment(with:billing:saveCard:)\/fragments","op":"replace"},{"value":"PaymentSessionHandler","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler\/title","op":"replace"},{"value":[{"text":"PaymentSessionHandler","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler\/fragments","op":"replace"},{"value":[{"text":"PaymentSessionHandler","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler\/navigatorTitle","op":"replace"},{"value":"AWXPlaceDetails","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPlaceDetails\/title","op":"replace"},{"value":[{"text":"AWXPlaceDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPlaceDetails\/fragments","op":"replace"},{"value":[{"text":"AWXPlaceDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPlaceDetails\/navigatorTitle","op":"replace"},{"value":"AWXCard","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCard\/title","op":"replace"},{"value":[{"text":"AWXCard","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCard\/fragments","op":"replace"},{"value":[{"text":"AWXCard","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCard\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}