{"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPaymentFormViewModel","text":"AWXPaymentFormViewModel"}],"externalID":"c:objc(cs)AWXPaymentFormViewController(py)viewModel","modules":[{"name":"Airwallex"}],"title":"viewModel","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"viewModel"}],"symbolKind":"property","role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxpaymentformviewcontroller\/viewmodel"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxpaymentformviewcontroller\/viewmodel"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentFormViewController\/viewModel"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentFormViewModel","preciseIdentifier":"c:objc(cs)AWXPaymentFormViewModel","text":"AWXPaymentFormViewModel"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentFormViewController"]]},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentFormViewController":{"abstract":[{"type":"codeVoice","code":"AWXPaymentFormViewController"},{"text":" handles payment form.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentFormViewController","type":"topic","kind":"symbol","url":"\/documentation\/airwallex\/awxpaymentformviewcontroller","title":"AWXPaymentFormViewController","role":"symbol","navigatorTitle":[{"text":"AWXPaymentFormViewController","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPaymentFormViewController","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentFormViewModel":{"abstract":[],"url":"\/documentation\/airwallex\/awxpaymentformviewmodel","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentFormViewModel","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPaymentFormViewModel","kind":"identifier"}],"title":"AWXPaymentFormViewModel","role":"symbol","navigatorTitle":[{"text":"AWXPaymentFormViewModel","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentFormViewController/viewModel":{"navigatorTitle":[{"kind":"identifier","text":"viewModel"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentFormViewController\/viewModel","abstract":[],"url":"\/documentation\/airwallex\/awxpaymentformviewcontroller\/viewmodel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPaymentFormViewModel","text":"AWXPaymentFormViewModel"}],"kind":"symbol","type":"topic","title":"viewModel"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","abstract":[],"role":"collection","url":"\/documentation\/airwallex","title":"Airwallex","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"viewModel"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"viewModel","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"AWXPaymentFormViewModel","preciseIdentifier":"c:objc(cs)AWXPaymentFormViewModel","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentFormViewModel"},{"text":" * ","kind":"text"},{"text":"viewModel","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentFormViewController\/title","op":"replace","value":"AWXPaymentFormViewController"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentFormViewController\/fragments","op":"replace","value":[{"text":"AWXPaymentFormViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentFormViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AWXPaymentFormViewController"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentFormViewModel\/title","op":"replace","value":"AWXPaymentFormViewModel"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentFormViewModel\/fragments","op":"replace","value":[{"text":"AWXPaymentFormViewModel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentFormViewModel\/navigatorTitle","op":"replace","value":[{"text":"AWXPaymentFormViewModel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentFormViewController~1viewModel\/title","op":"replace","value":"viewModel"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentFormViewController~1viewModel\/fragments","op":"replace","value":[{"text":"viewModel","kind":"identifier"}]}]}]}