{"variants":[{"paths":["\/documentation\/airwallex\/awxcardcvcviewcontroller\/paymentconsent"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxcardcvcviewcontroller\/paymentconsent"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardCVCViewController"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardCVCViewController\/paymentConsent"},"metadata":{"modules":[{"name":"Airwallex"}],"externalID":"c:objc(cs)AWXCardCVCViewController(py)paymentConsent","title":"paymentConsent","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"paymentConsent"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentConsent"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AWXPaymentConsent","kind":"typeIdentifier","text":"AWXPaymentConsent"},{"kind":"text","text":"?"}],"symbolKind":"property"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentConsent","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWXPaymentConsent","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentConsent","preciseIdentifier":"c:objc(cs)AWXPaymentConsent"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"abstract":[{"text":"A payment consent.","type":"text"}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","url":"\/documentation\/airwallex","role":"collection","kind":"symbol","abstract":[],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentConsent":{"abstract":[{"type":"codeVoice","code":"AWXPaymentConsent"},{"type":"text","text":" includes the info of payment consent."}],"navigatorTitle":[{"kind":"identifier","text":"AWXPaymentConsent"}],"title":"AWXPaymentConsent","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentConsent","kind":"symbol","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentConsent"}],"url":"\/documentation\/airwallex\/awxpaymentconsent"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardCVCViewController/paymentConsent":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardCVCViewController\/paymentConsent","abstract":[{"type":"text","text":"A payment consent."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"paymentConsent"}],"url":"\/documentation\/airwallex\/awxcardcvcviewcontroller\/paymentconsent","title":"paymentConsent","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentConsent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWXPaymentConsent","preciseIdentifier":"c:objc(cs)AWXPaymentConsent"},{"kind":"text","text":"?"}],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardCVCViewController":{"role":"symbol","url":"\/documentation\/airwallex\/awxcardcvcviewcontroller","title":"AWXCardCVCViewController","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardCVCViewController","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXCardCVCViewController"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"AWXCardCVCViewController"}],"abstract":[{"type":"codeVoice","code":"AWXCardCVCViewController"},{"type":"text","text":" provides a confirm button for user to finish checkout flow with payment consent."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"paymentConsent","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"paymentConsent"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"AWXPaymentConsent","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentConsent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPaymentConsent"},{"text":" * ","kind":"text"},{"text":"paymentConsent","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentConsent\/title","value":"AWXPaymentConsent","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentConsent\/fragments","value":[{"kind":"identifier","text":"AWXPaymentConsent"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentConsent\/navigatorTitle","value":[{"kind":"identifier","text":"AWXPaymentConsent"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardCVCViewController~1paymentConsent\/title","value":"paymentConsent","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardCVCViewController~1paymentConsent\/fragments","value":[{"text":"paymentConsent","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardCVCViewController\/title","value":"AWXCardCVCViewController","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardCVCViewController\/fragments","value":[{"kind":"identifier","text":"AWXCardCVCViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardCVCViewController\/navigatorTitle","value":[{"text":"AWXCardCVCViewController","kind":"identifier"}],"op":"replace"}]}]}