{"metadata":{"symbolKind":"property","modules":[{"name":"Airwallex"}],"title":"resources","role":"symbol","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"resources"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWXResources","preciseIdentifier":"c:objc(cs)AWXResources"}],"externalID":"c:objc(cs)AWXBank(py)resources","navigatorTitle":[{"kind":"identifier","text":"resources"}]},"abstract":[{"text":"Resources","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBank"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxbank\/resources"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxbank\/resources"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBank\/resources"},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"resources"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXResources","text":"AWXResources","preciseIdentifier":"c:objc(cs)AWXResources"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXBank":{"title":"AWXBank","type":"topic","role":"symbol","navigatorTitle":[{"text":"AWXBank","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBank","url":"\/documentation\/airwallex\/awxbank","kind":"symbol","abstract":[{"code":"AWXBank","type":"codeVoice"},{"text":" includes the bank info.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXBank","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXBank/resources":{"abstract":[{"text":"Resources","type":"text"}],"kind":"symbol","title":"resources","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBank\/resources","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resources","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AWXResources","text":"AWXResources","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"resources","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxbank\/resources"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","url":"\/documentation\/airwallex","title":"Airwallex","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXResources":{"abstract":[{"code":"AWXResources","type":"codeVoice"},{"text":" includes the resources of payment method.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWXResources"}],"role":"symbol","title":"AWXResources","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXResources"}],"type":"topic","url":"\/documentation\/airwallex\/awxresources","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXResources"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"resources"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"resources"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXResources","preciseIdentifier":"c:objc(cs)AWXResources","text":"AWXResources"},{"kind":"text","text":" * "},{"kind":"identifier","text":"resources"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBank\/title","value":"AWXBank"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBank\/fragments","value":[{"kind":"identifier","text":"AWXBank"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBank\/navigatorTitle","value":[{"kind":"identifier","text":"AWXBank"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBank~1resources\/title","value":"resources"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBank~1resources\/fragments","value":[{"kind":"identifier","text":"resources"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXResources\/title","value":"AWXResources"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXResources\/fragments","value":[{"kind":"identifier","text":"AWXResources"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXResources\/navigatorTitle","value":[{"kind":"identifier","text":"AWXResources"}]}]}]}