{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"AirwallexMerchantTriggerReason"}],"title":"AirwallexMerchantTriggerReason","symbolKind":"enum","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"AirwallexMerchantTriggerReason","kind":"identifier"}],"externalID":"c:@E@AirwallexMerchantTriggerReason","roleHeading":"Enumeration","modules":[{"name":"Airwallex"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/airwallexmerchanttriggerreason"]},{"paths":["\/documentation\/airwallex\/airwallexmerchanttriggerreason"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexMerchantTriggerReason","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexMerchantTriggerReason\/scheduled","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexMerchantTriggerReason\/undefined","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexMerchantTriggerReason\/unscheduled"]},{"generated":true,"anchor":"Initializers","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexMerchantTriggerReason\/init(rawValue:)"],"title":"Initializers"},{"generated":true,"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexMerchantTriggerReason\/Equatable-Implementations","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexMerchantTriggerReason\/RawRepresentable-Implementations"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AirwallexMerchantTriggerReason","kind":"identifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/s15BitwiseCopyableP","doc:\/\/org.cocoapods.Airwallex\/SQ","doc:\/\/org.cocoapods.Airwallex\/SH","doc:\/\/org.cocoapods.Airwallex\/SY","doc:\/\/org.cocoapods.Airwallex\/s8SendableP"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/airwallex","title":"Airwallex","role":"collection"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexMerchantTriggerReason":{"kind":"symbol","type":"topic","title":"AirwallexMerchantTriggerReason","url":"\/documentation\/airwallex\/airwallexmerchanttriggerreason","abstract":[],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexMerchantTriggerReason","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AirwallexMerchantTriggerReason"}],"navigatorTitle":[{"text":"AirwallexMerchantTriggerReason","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/s15BitwiseCopyableP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s15BitwiseCopyableP","type":"unresolvable","title":"Swift.BitwiseCopyable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexMerchantTriggerReason/Equatable-Implementations":{"url":"\/documentation\/airwallex\/airwallexmerchanttriggerreason\/equatable-implementations","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexMerchantTriggerReason\/Equatable-Implementations","title":"Equatable Implementations","abstract":[],"role":"collectionGroup","type":"topic","kind":"article"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexMerchantTriggerReason/scheduled":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexMerchantTriggerReason\/scheduled","url":"\/documentation\/airwallex\/airwallexmerchanttriggerreason\/scheduled","title":"AirwallexMerchantTriggerReason.scheduled","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"scheduled"}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"AirwallexMerchantTriggerReasonScheduled","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/s8SendableP"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexMerchantTriggerReason/unscheduled":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexMerchantTriggerReason\/unscheduled","url":"\/documentation\/airwallex\/airwallexmerchanttriggerreason\/unscheduled","title":"AirwallexMerchantTriggerReason.unscheduled","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"unscheduled","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"AirwallexMerchantTriggerReasonUnscheduled","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexMerchantTriggerReason/RawRepresentable-Implementations":{"url":"\/documentation\/airwallex\/airwallexmerchanttriggerreason\/rawrepresentable-implementations","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexMerchantTriggerReason\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","abstract":[],"role":"collectionGroup","type":"topic","kind":"article"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexMerchantTriggerReason/init(rawValue:)":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexMerchantTriggerReason\/init(rawValue:)","url":"\/documentation\/airwallex\/airwallexmerchanttriggerreason\/init(rawvalue:)","title":"init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://org.cocoapods.Airwallex/SQ":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://org.cocoapods.Airwallex/SH":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexMerchantTriggerReason/undefined":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexMerchantTriggerReason\/undefined","url":"\/documentation\/airwallex\/airwallexmerchanttriggerreason\/undefined","navigatorTitle":[{"text":"AirwallexMerchantTriggerReasonUndefined","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"undefined","kind":"identifier"}],"kind":"symbol","title":"AirwallexMerchantTriggerReason.undefined","type":"topic","role":"symbol"},"doc://org.cocoapods.Airwallex/SY":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/SY","type":"unresolvable","title":"Swift.RawRepresentable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"value":"AirwallexMerchantTriggerReason","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"AirwallexMerchantTriggerReason"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"AirwallexMerchantTriggerReason","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"anchor":"Enumeration-Cases","generated":true,"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexMerchantTriggerReason\/scheduled","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexMerchantTriggerReason\/undefined","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexMerchantTriggerReason\/unscheduled"],"title":"Enumeration Cases"}],"path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AirwallexMerchantTriggerReason"},{"text":" : ","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":";","kind":"text"}]}]}},{"value":"AirwallexMerchantTriggerReason","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexMerchantTriggerReason\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexMerchantTriggerReason\/fragments","value":[{"text":"AirwallexMerchantTriggerReason","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"AirwallexMerchantTriggerReason"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexMerchantTriggerReason\/navigatorTitle"},{"value":"AirwallexMerchantTriggerReasonScheduled","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexMerchantTriggerReason~1scheduled\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AirwallexMerchantTriggerReasonScheduled"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexMerchantTriggerReason~1scheduled\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexMerchantTriggerReason~1unscheduled\/title","op":"replace","value":"AirwallexMerchantTriggerReasonUnscheduled"},{"op":"replace","value":[{"kind":"identifier","text":"AirwallexMerchantTriggerReasonUnscheduled"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexMerchantTriggerReason~1unscheduled\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexMerchantTriggerReason~1undefined\/title","op":"replace","value":"AirwallexMerchantTriggerReasonUndefined"},{"value":[{"text":"AirwallexMerchantTriggerReasonUndefined","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexMerchantTriggerReason~1undefined\/fragments","op":"replace"}]}]}