{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"topicSections":[{"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexSDKMode\/demoMode","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexSDKMode\/productionMode","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexSDKMode\/stagingMode"]},{"generated":true,"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexSDKMode\/init(rawValue:)"]},{"generated":true,"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexSDKMode\/Equatable-Implementations","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexSDKMode\/RawRepresentable-Implementations"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexSDKMode"},"relationshipsSections":[{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.Airwallex\/s15BitwiseCopyableP","doc:\/\/org.cocoapods.Airwallex\/SQ","doc:\/\/org.cocoapods.Airwallex\/SH","doc:\/\/org.cocoapods.Airwallex\/SY","doc:\/\/org.cocoapods.Airwallex\/s8SendableP"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AirwallexSDKMode"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AirwallexSDKMode"}],"externalID":"c:@E@AirwallexSDKMode","title":"AirwallexSDKMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AirwallexSDKMode"}],"roleHeading":"Enumeration","modules":[{"name":"Airwallex"}],"symbolKind":"enum"},"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/airwallex\/airwallexsdkmode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/airwallexsdkmode"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.Airwallex/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SQ"},"doc://org.cocoapods.Airwallex/SY":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexSDKMode/Equatable-Implementations":{"abstract":[],"title":"Equatable Implementations","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexSDKMode\/Equatable-Implementations","type":"topic","url":"\/documentation\/airwallex\/airwallexsdkmode\/equatable-implementations","kind":"article","role":"collectionGroup"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexSDKMode/RawRepresentable-Implementations":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexSDKMode\/RawRepresentable-Implementations","type":"topic","title":"RawRepresentable Implementations","abstract":[],"kind":"article","url":"\/documentation\/airwallex\/airwallexsdkmode\/rawrepresentable-implementations","role":"collectionGroup"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"abstract":[],"url":"\/documentation\/airwallex","role":"collection","title":"Airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","type":"topic","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexSDKMode/init(rawValue:)":{"url":"\/documentation\/airwallex\/airwallexsdkmode\/init(rawvalue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","type":"topic","title":"init(rawValue:)","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexSDKMode\/init(rawValue:)","abstract":[],"kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexSDKMode/productionMode":{"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"productionMode"}],"navigatorTitle":[{"text":"AirwallexSDKProductionMode","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"AirwallexSDKMode.productionMode","url":"\/documentation\/airwallex\/airwallexsdkmode\/productionmode","abstract":[],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexSDKMode\/productionMode"},"doc://org.cocoapods.Airwallex/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/s8SendableP","title":"Swift.Sendable"},"doc://org.cocoapods.Airwallex/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SH"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexSDKMode/demoMode":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexSDKMode\/demoMode","navigatorTitle":[{"kind":"identifier","text":"AirwallexSDKDemoMode"}],"title":"AirwallexSDKMode.demoMode","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"demoMode"}],"url":"\/documentation\/airwallex\/airwallexsdkmode\/demomode","role":"symbol","kind":"symbol","abstract":[],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexSDKMode":{"role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AirwallexSDKMode"}],"url":"\/documentation\/airwallex\/airwallexsdkmode","type":"topic","kind":"symbol","title":"AirwallexSDKMode","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexSDKMode","navigatorTitle":[{"kind":"identifier","text":"AirwallexSDKMode"}]},"doc://org.cocoapods.Airwallex/s15BitwiseCopyableP":{"type":"unresolvable","title":"Swift.BitwiseCopyable","identifier":"doc:\/\/org.cocoapods.Airwallex\/s15BitwiseCopyableP"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexSDKMode/stagingMode":{"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexSDKMode\/stagingMode","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AirwallexSDKStagingMode"}],"url":"\/documentation\/airwallex\/airwallexsdkmode\/stagingmode","kind":"symbol","title":"AirwallexSDKMode.stagingMode","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"stagingMode"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"value":"AirwallexSDKMode","path":"\/metadata\/title","op":"replace"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"AirwallexSDKMode"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"AirwallexSDKMode","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexSDKMode\/demoMode","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexSDKMode\/productionMode","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexSDKMode\/stagingMode"],"generated":true,"anchor":"Enumeration-Cases"}],"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AirwallexSDKMode","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"AirwallexSDKProductionMode","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexSDKMode~1productionMode\/title","op":"replace"},{"value":[{"text":"AirwallexSDKProductionMode","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexSDKMode~1productionMode\/fragments","op":"replace"},{"value":"AirwallexSDKDemoMode","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexSDKMode~1demoMode\/title","op":"replace"},{"value":[{"text":"AirwallexSDKDemoMode","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexSDKMode~1demoMode\/fragments","op":"replace"},{"value":"AirwallexSDKMode","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexSDKMode\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AirwallexSDKMode"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexSDKMode\/fragments","op":"replace"},{"value":[{"text":"AirwallexSDKMode","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexSDKMode\/navigatorTitle","op":"replace"},{"value":"AirwallexSDKStagingMode","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexSDKMode~1stagingMode\/title","op":"replace"},{"value":[{"text":"AirwallexSDKStagingMode","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexSDKMode~1stagingMode\/fragments","op":"replace"}]}]}