{"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AirwallexPaymentStatus","kind":"identifier"}]}],"kind":"declarations"}],"metadata":{"roleHeading":"Enumeration","navigatorTitle":[{"text":"AirwallexPaymentStatus","kind":"identifier"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AirwallexPaymentStatus","kind":"identifier"}],"externalID":"c:@E@AirwallexPaymentStatus","symbolKind":"enum","title":"AirwallexPaymentStatus","modules":[{"name":"Airwallex"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexPaymentStatus","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"topicSections":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexPaymentStatus\/cancel","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexPaymentStatus\/failure","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexPaymentStatus\/inProgress","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexPaymentStatus\/success"],"generated":true},{"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexPaymentStatus\/init(rawValue:)"],"generated":true},{"title":"Default Implementations","anchor":"Default-Implementations","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexPaymentStatus\/Equatable-Implementations","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexPaymentStatus\/RawRepresentable-Implementations"],"generated":true}],"relationshipsSections":[{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.Airwallex\/s15BitwiseCopyableP","doc:\/\/org.cocoapods.Airwallex\/SQ","doc:\/\/org.cocoapods.Airwallex\/SH","doc:\/\/org.cocoapods.Airwallex\/SY","doc:\/\/org.cocoapods.Airwallex\/s8SendableP"],"type":"conformsTo"}],"variants":[{"paths":["\/documentation\/airwallex\/airwallexpaymentstatus"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/airwallexpaymentstatus"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.Airwallex/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SQ"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexPaymentStatus":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexPaymentStatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AirwallexPaymentStatus","kind":"identifier"}],"navigatorTitle":[{"text":"AirwallexPaymentStatus","kind":"identifier"}],"type":"topic","title":"AirwallexPaymentStatus","role":"symbol","url":"\/documentation\/airwallex\/airwallexpaymentstatus"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexPaymentStatus/success":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"success"}],"title":"AirwallexPaymentStatus.success","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexPaymentStatus\/success","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"AirwallexPaymentStatusSuccess"}],"role":"symbol","url":"\/documentation\/airwallex\/airwallexpaymentstatus\/success","kind":"symbol"},"doc://org.cocoapods.Airwallex/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SH","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexPaymentStatus/RawRepresentable-Implementations":{"role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexPaymentStatus\/RawRepresentable-Implementations","type":"topic","abstract":[],"kind":"article","title":"RawRepresentable Implementations","url":"\/documentation\/airwallex\/airwallexpaymentstatus\/rawrepresentable-implementations"},"doc://org.cocoapods.Airwallex/s8SendableP":{"title":"Swift.Sendable","identifier":"doc:\/\/org.cocoapods.Airwallex\/s8SendableP","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexPaymentStatus/Equatable-Implementations":{"role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexPaymentStatus\/Equatable-Implementations","type":"topic","abstract":[],"kind":"article","title":"Equatable Implementations","url":"\/documentation\/airwallex\/airwallexpaymentstatus\/equatable-implementations"},"doc://org.cocoapods.Airwallex/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SY"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"abstract":[],"url":"\/documentation\/airwallex","role":"collection","title":"Airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","type":"topic","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexPaymentStatus/inProgress":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexPaymentStatus\/inProgress","type":"topic","abstract":[],"kind":"symbol","title":"AirwallexPaymentStatus.inProgress","url":"\/documentation\/airwallex\/airwallexpaymentstatus\/inprogress","navigatorTitle":[{"kind":"identifier","text":"AirwallexPaymentStatusInProgress"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"inProgress"}]},"doc://org.cocoapods.Airwallex/s15BitwiseCopyableP":{"type":"unresolvable","title":"Swift.BitwiseCopyable","identifier":"doc:\/\/org.cocoapods.Airwallex\/s15BitwiseCopyableP"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexPaymentStatus/cancel":{"abstract":[],"kind":"symbol","navigatorTitle":[{"text":"AirwallexPaymentStatusCancel","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancel","kind":"identifier"}],"url":"\/documentation\/airwallex\/airwallexpaymentstatus\/cancel","title":"AirwallexPaymentStatus.cancel","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexPaymentStatus\/cancel","role":"symbol","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexPaymentStatus/init(rawValue:)":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexPaymentStatus\/init(rawValue:)","kind":"symbol","url":"\/documentation\/airwallex\/airwallexpaymentstatus\/init(rawvalue:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(rawValue:)","abstract":[],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexPaymentStatus/failure":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexPaymentStatus\/failure","navigatorTitle":[{"kind":"identifier","text":"AirwallexPaymentStatusFailure"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failure"}],"title":"AirwallexPaymentStatus.failure","url":"\/documentation\/airwallex\/airwallexpaymentstatus\/failure","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"value":"AirwallexPaymentStatus","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"AirwallexPaymentStatus"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"AirwallexPaymentStatus","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Enumeration-Cases","generated":true,"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexPaymentStatus\/cancel","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexPaymentStatus\/failure","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexPaymentStatus\/inProgress","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexPaymentStatus\/success"],"title":"Enumeration Cases"}]},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AirwallexPaymentStatus","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexPaymentStatus\/title","op":"replace","value":"AirwallexPaymentStatus"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexPaymentStatus\/fragments","op":"replace","value":[{"text":"AirwallexPaymentStatus","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexPaymentStatus\/navigatorTitle","op":"replace","value":[{"text":"AirwallexPaymentStatus","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexPaymentStatus~1success\/title","op":"replace","value":"AirwallexPaymentStatusSuccess"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexPaymentStatus~1success\/fragments","op":"replace","value":[{"text":"AirwallexPaymentStatusSuccess","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexPaymentStatus~1inProgress\/title","op":"replace","value":"AirwallexPaymentStatusInProgress"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexPaymentStatus~1inProgress\/fragments","op":"replace","value":[{"text":"AirwallexPaymentStatusInProgress","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexPaymentStatus~1cancel\/title","op":"replace","value":"AirwallexPaymentStatusCancel"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexPaymentStatus~1cancel\/fragments","op":"replace","value":[{"text":"AirwallexPaymentStatusCancel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexPaymentStatus~1failure\/title","op":"replace","value":"AirwallexPaymentStatusFailure"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexPaymentStatus~1failure\/fragments","op":"replace","value":[{"kind":"identifier","text":"AirwallexPaymentStatusFailure"}]}]}]}