{"variants":[{"paths":["\/documentation\/airwallex\/airwallexpaymentversionstring"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/airwallexpaymentversionstring"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"Airwallex"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"AirwallexPaymentVersionString"},{"kind":"text","text":": <<error type>>"}],"navigatorTitle":[{"kind":"identifier","text":"AirwallexPaymentVersionString"}],"symbolKind":"var","externalID":"c:@AirwallexPaymentVersionString","title":"AirwallexPaymentVersionString","roleHeading":"Global Variable","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexPaymentVersionString"},"abstract":[{"text":"Project version string for Payment.","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AirwallexPaymentVersionString","kind":"identifier"},{"text":": <<error type>>","kind":"text"}]}]}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol","type":"topic","url":"\/documentation\/airwallex","role":"collection","abstract":[],"title":"Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexPaymentVersionString":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexPaymentVersionString","kind":"symbol","abstract":[{"type":"text","text":"Project version string for Payment."}],"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AirwallexPaymentVersionString","kind":"identifier"},{"text":": <<error type>>","kind":"text"}],"navigatorTitle":[{"text":"AirwallexPaymentVersionString","kind":"identifier"}],"title":"AirwallexPaymentVersionString","url":"\/documentation\/airwallex\/airwallexpaymentversionstring","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Global Variable","op":"replace","path":"\/metadata\/roleHeading"},{"value":"AirwallexPaymentVersionString","op":"replace","path":"\/metadata\/title"},{"value":"var","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"AirwallexPaymentVersionString","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:c","text":"unsigned char"},{"kind":"text","text":" "},{"kind":"identifier","text":"AirwallexPaymentVersionString"},{"kind":"text","text":"[];"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"AirwallexPaymentVersionString","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexPaymentVersionString\/title"},{"value":[{"kind":"identifier","text":"AirwallexPaymentVersionString"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexPaymentVersionString\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}