{"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions\/init(merchantIdentifier:)"],"generated":true,"anchor":"Initializers","title":"Initializers"},{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions\/additionalPaymentSummaryItems","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions\/merchantCapabilities","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions\/merchantIdentifier","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions\/requiredBillingContactFields","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions\/supportedCountries","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions\/supportedNetworks","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions\/totalPriceLabel"],"anchor":"Instance-Properties"}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/SQ","doc:\/\/org.cocoapods.Airwallex\/SH"],"title":"Conforms To","kind":"relationships"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxapplepayoptions"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxapplepayoptions"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXApplePayOptions","kind":"identifier"}]}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions"},"metadata":{"title":"AWXApplePayOptions","modules":[{"name":"Airwallex"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AWXApplePayOptions"}],"roleHeading":"Class","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWXApplePayOptions"}],"externalID":"c:objc(cs)AWXApplePayOptions","symbolKind":"class"},"abstract":[{"type":"text","text":"Object used to construct PKPaymentRequest for Apple Pay."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://org.cocoapods.Airwallex/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject","title":"NSObject"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXApplePayOptions/supportedCountries":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions\/supportedCountries","kind":"symbol","title":"supportedCountries","navigatorTitle":[{"text":"supportedCountries","kind":"identifier"}],"abstract":[{"type":"text","text":"A list of ISO 3166 country codes for limiting payments to cards from specific countries. Default value is null, meaning all countries are allowed."}],"url":"\/documentation\/airwallex\/awxapplepayoptions\/supportedcountries","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"supportedCountries","kind":"identifier"},{"kind":"text","text":": "},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":">?"}],"type":"topic"},"doc://org.cocoapods.Airwallex/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXApplePayOptions/supportedNetworks":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions\/supportedNetworks","kind":"symbol","title":"supportedNetworks","navigatorTitle":[{"kind":"identifier","text":"supportedNetworks"}],"abstract":[{"text":"The payment networks supported by the merchant, for example @[PKPaymentNetworkVisa, PKPaymentNetworkMasterCard].","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This property constrains payment cards that may fund the payment. Default value includes Visa, Mastercard, UnionPay, Amex, Discover and JCB."}],"url":"\/documentation\/airwallex\/awxapplepayoptions\/supportednetworks","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"supportedNetworks","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@T@PKPaymentNetwork","text":"PKPaymentNetwork","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXApplePayOptions/additionalPaymentSummaryItems":{"abstract":[{"text":"An additional array of payment summary item objects that summarize the amount of the payment. Default value is nil.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"additionalPaymentSummaryItems","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)PKPaymentSummaryItem","text":"PKPaymentSummaryItem","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"additionalPaymentSummaryItems","kind":"identifier"}],"kind":"symbol","title":"additionalPaymentSummaryItems","url":"\/documentation\/airwallex\/awxapplepayoptions\/additionalpaymentsummaryitems","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions\/additionalPaymentSummaryItems"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXApplePayOptions/totalPriceLabel":{"title":"totalPriceLabel","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"totalPriceLabel","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions\/totalPriceLabel","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"totalPriceLabel"}],"role":"symbol","abstract":[{"type":"text","text":"Description of the total price. Default value is nil."}],"url":"\/documentation\/airwallex\/awxapplepayoptions\/totalpricelabel"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXApplePayOptions/merchantCapabilities":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions\/merchantCapabilities","kind":"symbol","title":"merchantCapabilities","navigatorTitle":[{"kind":"identifier","text":"merchantCapabilities"}],"abstract":[{"type":"text","text":"Apple Pay merchant capabilities. Default value includes 3DS, EMV, Credit and Debit."}],"url":"\/documentation\/airwallex\/awxapplepayoptions\/merchantcapabilities","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"merchantCapabilities","kind":"identifier"},{"kind":"text","text":": "},{"text":"PKMerchantCapability","kind":"typeIdentifier","preciseIdentifier":"c:@E@PKMerchantCapability"}],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXApplePayOptions":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXApplePayOptions","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxapplepayoptions","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions","title":"AWXApplePayOptions","kind":"symbol","abstract":[{"type":"text","text":"Object used to construct PKPaymentRequest for Apple Pay."}],"navigatorTitle":[{"text":"AWXApplePayOptions","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXApplePayOptions/init(merchantIdentifier:)":{"abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"merchantIdentifier","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"initWithMerchantIdentifier:","kind":"identifier"}],"kind":"symbol","title":"init(merchantIdentifier:)","url":"\/documentation\/airwallex\/awxapplepayoptions\/init(merchantidentifier:)","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions\/init(merchantIdentifier:)"},"doc://org.cocoapods.Airwallex/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/airwallex","title":"Airwallex","role":"collection"},"doc://org.cocoapods.Airwallex/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.Airwallex/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.Airwallex/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","title":"Swift.CVarArg"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXApplePayOptions/merchantIdentifier":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions\/merchantIdentifier","kind":"symbol","title":"merchantIdentifier","navigatorTitle":[{"text":"merchantIdentifier","kind":"identifier"}],"abstract":[{"type":"text","text":"Apple Pay merchant identifier."}],"url":"\/documentation\/airwallex\/awxapplepayoptions\/merchantidentifier","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"merchantIdentifier","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"type":"topic"},"doc://org.cocoapods.Airwallex/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SQ","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXApplePayOptions/requiredBillingContactFields":{"kind":"symbol","abstract":[{"text":"The billing information that you require from the user in order to process the transaction. Default value is empty set.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions\/requiredBillingContactFields","title":"requiredBillingContactFields","url":"\/documentation\/airwallex\/awxapplepayoptions\/requiredbillingcontactfields","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"requiredBillingContactFields","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@T@PKContactField","text":"PKContactField","kind":"typeIdentifier"},{"text":">","kind":"text"}],"navigatorTitle":[{"text":"requiredBillingContactFields","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"AWXApplePayOptions","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"AWXApplePayOptions","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":[{"text":"AWXApplePayOptions","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions\/additionalPaymentSummaryItems","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions\/merchantCapabilities","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions\/merchantIdentifier","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions\/requiredBillingContactFields","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions\/supportedCountries","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions\/supportedNetworks","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions\/totalPriceLabel"],"title":"Instance Properties"},{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions\/init(merchantIdentifier:)"]}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"AWXApplePayOptions","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"supportedCountries","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions~1supportedCountries\/title"},{"op":"replace","value":[{"text":"supportedCountries","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions~1supportedCountries\/fragments"},{"op":"replace","value":"supportedNetworks","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions~1supportedNetworks\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions~1supportedNetworks\/fragments","value":[{"kind":"identifier","text":"supportedNetworks"}],"op":"replace"},{"value":"additionalPaymentSummaryItems","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions~1additionalPaymentSummaryItems\/title"},{"value":[{"kind":"identifier","text":"additionalPaymentSummaryItems"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions~1additionalPaymentSummaryItems\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions~1totalPriceLabel\/title","op":"replace","value":"totalPriceLabel"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions~1totalPriceLabel\/fragments","value":[{"text":"totalPriceLabel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions~1merchantCapabilities\/title","op":"replace","value":"merchantCapabilities"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions~1merchantCapabilities\/fragments","value":[{"kind":"identifier","text":"merchantCapabilities"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions\/title","value":"AWXApplePayOptions","op":"replace"},{"value":[{"kind":"identifier","text":"AWXApplePayOptions"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions\/navigatorTitle","value":[{"text":"AWXApplePayOptions","kind":"identifier"}]},{"op":"replace","value":"initWithMerchantIdentifier:","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions~1init(merchantIdentifier:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions~1init(merchantIdentifier:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithMerchantIdentifier:","kind":"identifier"}]},{"value":"merchantIdentifier","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions~1merchantIdentifier\/title"},{"value":[{"kind":"identifier","text":"merchantIdentifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions~1merchantIdentifier\/fragments"},{"op":"replace","value":"requiredBillingContactFields","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions~1requiredBillingContactFields\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions~1requiredBillingContactFields\/fragments","value":[{"text":"requiredBillingContactFields","kind":"identifier"}]}]}]}