{"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXAuthenticationData","kind":"identifier"}],"modules":[{"name":"Airwallex"}],"role":"symbol","title":"AWXAuthenticationData","externalID":"c:objc(cs)AWXAuthenticationData","symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"AWXAuthenticationData"}],"roleHeading":"Class"},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONDecodable","doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/SQ","doc:\/\/org.cocoapods.Airwallex\/SH"],"type":"conformsTo","title":"Conforms To"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAuthenticationData"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXAuthenticationData"}],"platforms":["iOS"]}]}],"abstract":[{"type":"codeVoice","code":"AWXAuthenticationData"},{"type":"text","text":" includes the parameters for 3ds authentication."}],"topicSections":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAuthenticationData\/action","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAuthenticationData\/score","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAuthenticationData\/version"],"generated":true,"title":"Instance Properties"},{"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAuthenticationData\/isThreeDSVersion2()"],"generated":true,"title":"Instance Methods"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxauthenticationdata"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxauthenticationdata"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"references":{"doc://org.cocoapods.Airwallex/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","title":"Swift.CVarArg"},"doc://org.cocoapods.Airwallex/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.Airwallex/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","role":"collection","title":"Airwallex","url":"\/documentation\/airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXAuthenticationData/score":{"navigatorTitle":[{"kind":"identifier","text":"score"}],"url":"\/documentation\/airwallex\/awxauthenticationdata\/score","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"score"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAuthenticationData\/score","type":"topic","abstract":[],"kind":"symbol","role":"symbol","title":"score"},"doc://org.cocoapods.Airwallex/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXAuthenticationData/isThreeDSVersion2()":{"type":"topic","title":"isThreeDSVersion2()","url":"\/documentation\/airwallex\/awxauthenticationdata\/isthreedsversion2()","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isThreeDSVersion2"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[{"text":"Check whether 3ds version is v2.x.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"isThreeDSVersion2"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAuthenticationData\/isThreeDSVersion2()","role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXAuthenticationData/version":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"version","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","abstract":[],"url":"\/documentation\/airwallex\/awxauthenticationdata\/version","title":"version","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAuthenticationData\/version","navigatorTitle":[{"text":"version","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXAuthenticationData/action":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"action","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","abstract":[],"url":"\/documentation\/airwallex\/awxauthenticationdata\/action","title":"action","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAuthenticationData\/action","navigatorTitle":[{"text":"action","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXJSONDecodable":{"role":"symbol","abstract":[],"url":"\/documentation\/airwallex\/awxjsondecodable","kind":"symbol","title":"AWXJSONDecodable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXJSONDecodable"}],"navigatorTitle":[{"kind":"identifier","text":"AWXJSONDecodable"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONDecodable"},"doc://org.cocoapods.Airwallex/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.Airwallex/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXAuthenticationData":{"kind":"symbol","abstract":[{"type":"codeVoice","code":"AWXAuthenticationData"},{"text":" includes the parameters for 3ds authentication.","type":"text"}],"url":"\/documentation\/airwallex\/awxauthenticationdata","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAuthenticationData","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXAuthenticationData","kind":"identifier"}],"navigatorTitle":[{"text":"AWXAuthenticationData","kind":"identifier"}],"title":"AWXAuthenticationData"},"doc://org.cocoapods.Airwallex/SQ":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/SQ","type":"unresolvable","title":"Swift.Equatable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"AWXAuthenticationData","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AWXAuthenticationData"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"AWXAuthenticationData","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAuthenticationData\/action","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAuthenticationData\/score","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAuthenticationData\/version"],"generated":true},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAuthenticationData\/isThreeDSVersion2()"],"generated":true}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"]},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONDecodable"]}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXAuthenticationData","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}]},"op":"replace"},{"value":"score","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAuthenticationData~1score\/title","op":"replace"},{"value":[{"text":"score","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAuthenticationData~1score\/fragments","op":"replace"},{"value":"isThreeDSVersion2","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAuthenticationData~1isThreeDSVersion2()\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAuthenticationData~1isThreeDSVersion2()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isThreeDSVersion2"}]},{"value":"version","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAuthenticationData~1version\/title","op":"replace"},{"value":[{"text":"version","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAuthenticationData~1version\/fragments","op":"replace"},{"value":"action","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAuthenticationData~1action\/title","op":"replace"},{"value":[{"kind":"identifier","text":"action"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAuthenticationData~1action\/fragments","op":"replace"},{"value":"AWXJSONDecodable","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONDecodable\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AWXJSONDecodable"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONDecodable\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AWXJSONDecodable"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONDecodable\/navigatorTitle","op":"replace"},{"value":"AWXAuthenticationData","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAuthenticationData\/title","op":"replace"},{"value":[{"text":"AWXAuthenticationData","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAuthenticationData\/fragments","op":"replace"},{"value":[{"text":"AWXAuthenticationData","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAuthenticationData\/navigatorTitle","op":"replace"}]}]}