{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrand"},"kind":"symbol","abstract":[{"type":"codeVoice","code":"AWXBrand"},{"type":"text","text":" manages the card scheme brand."}],"variants":[{"paths":["\/documentation\/airwallex\/awxbrand"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxbrand"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXBrand","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"]},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/SQ","doc:\/\/org.cocoapods.Airwallex\/SH"]}],"sections":[],"topicSections":[{"generated":true,"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrand\/init(name:rangeStart:rangeEnd:length:type:)"],"anchor":"Initializers"},{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrand\/length","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrand\/name","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrand\/rangeEnd","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrand\/rangeStart","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrand\/type"],"anchor":"Instance-Properties"},{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrand\/matchesPrefix(_:)"],"anchor":"Instance-Methods"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"metadata":{"modules":[{"name":"Airwallex"}],"navigatorTitle":[{"kind":"identifier","text":"AWXBrand"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXBrand"}],"role":"symbol","roleHeading":"Class","externalID":"c:objc(cs)AWXBrand","title":"AWXBrand","symbolKind":"class"},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXBrand/rangeStart":{"navigatorTitle":[{"text":"rangeStart","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rangeStart","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"rangeStart","abstract":[{"text":"The start of  card No.","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/airwallex\/awxbrand\/rangestart","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrand\/rangeStart","role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXBrand/init(name:rangeStart:rangeEnd:length:type:)":{"url":"\/documentation\/airwallex\/awxbrand\/init(name:rangestart:rangeend:length:type:)","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrand\/init(name:rangeStart:rangeEnd:length:type:)","title":"init(name:rangeStart:rangeEnd:length:type:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithName:rangeStart:rangeEnd:length:type:"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"rangeStart"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"rangeEnd"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"length"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWXBrandType","preciseIdentifier":"c:@E@AWXBrandType"},{"kind":"text","text":")"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://org.cocoapods.Airwallex/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SH"},"doc://org.cocoapods.Airwallex/SQ":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.Airwallex/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"kind":"symbol","abstract":[],"role":"collection","type":"topic","url":"\/documentation\/airwallex","title":"Airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"},"doc://org.cocoapods.Airwallex/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXBrand/length":{"navigatorTitle":[{"text":"length","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"length","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"title":"length","abstract":[{"text":"The length of  card No.","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/airwallex\/awxbrand\/length","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrand\/length","role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXBrand/rangeEnd":{"url":"\/documentation\/airwallex\/awxbrand\/rangeend","title":"rangeEnd","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrand\/rangeEnd","abstract":[{"type":"text","text":"The end of  card No."}],"navigatorTitle":[{"text":"rangeEnd","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rangeEnd","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://org.cocoapods.Airwallex/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.Airwallex/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXBrand":{"navigatorTitle":[{"kind":"identifier","text":"AWXBrand"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXBrand"}],"abstract":[{"code":"AWXBrand","type":"codeVoice"},{"text":" manages the card scheme brand.","type":"text"}],"title":"AWXBrand","kind":"symbol","type":"topic","url":"\/documentation\/airwallex\/awxbrand","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrand","role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXBrand/matchesPrefix(_:)":{"url":"\/documentation\/airwallex\/awxbrand\/matchesprefix(_:)","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrand\/matchesPrefix(_:)","title":"matchesPrefix(_:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"matchesPrefix:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"matchesPrefix"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXBrand/type":{"navigatorTitle":[{"text":"type","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWXBrandType","preciseIdentifier":"c:@E@AWXBrandType","kind":"typeIdentifier"}],"title":"type","abstract":[{"type":"text","text":"The brand type."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrand\/type","url":"\/documentation\/airwallex\/awxbrand\/type","role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXBrand/brandWithName:rangeStart:rangeEnd:length:type:":{"url":"\/documentation\/airwallex\/awxbrand\/brandwithname:rangestart:rangeend:length:type:","title":"brandWithName:rangeStart:rangeEnd:length:type:","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrand\/brandWithName:rangeStart:rangeEnd:length:type:","abstract":[],"navigatorTitle":[{"text":"brandWithName:rangeStart:rangeEnd:length:type:","kind":"identifier"}],"fragments":[{"text":"+ ","kind":"text"},{"text":"brandWithName:rangeStart:rangeEnd:length:type:","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://org.cocoapods.Airwallex/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXBrand/name":{"navigatorTitle":[{"kind":"identifier","text":"name"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"title":"name","abstract":[{"text":"The brand name.","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/airwallex\/awxbrand\/name","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrand\/name","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"AWXBrand","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"AWXBrand"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AWXBrand"}],"op":"replace"},{"path":"\/topicSections","value":[{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrand\/length","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrand\/name","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrand\/rangeEnd","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrand\/rangeStart","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrand\/type"]},{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrand\/init(name:rangeStart:rangeEnd:length:type:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrand\/matchesPrefix(_:)"]},{"anchor":"Type-Methods","generated":true,"title":"Type Methods","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrand\/brandWithName:rangeStart:rangeEnd:length:type:"]}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXBrand","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrand~1rangeStart\/title","value":"rangeStart","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrand~1rangeStart\/fragments","value":[{"text":"rangeStart","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrand~1init(name:rangeStart:rangeEnd:length:type:)\/title","value":"initWithName:rangeStart:rangeEnd:length:type:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrand~1init(name:rangeStart:rangeEnd:length:type:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithName:rangeStart:rangeEnd:length:type:"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrand~1length\/title","value":"length","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrand~1length\/fragments","value":[{"text":"length","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrand~1rangeEnd\/title","value":"rangeEnd","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrand~1rangeEnd\/fragments","value":[{"text":"rangeEnd","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrand\/title","value":"AWXBrand","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrand\/fragments","value":[{"text":"AWXBrand","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrand\/navigatorTitle","value":[{"kind":"identifier","text":"AWXBrand"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrand~1matchesPrefix(_:)\/title","value":"matchesPrefix:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrand~1matchesPrefix(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"matchesPrefix:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrand~1type\/title","value":"type"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrand~1type\/fragments","value":[{"text":"type","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrand~1name\/title","value":"name"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrand~1name\/fragments","value":[{"kind":"identifier","text":"name"}]}]}]}