{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"c:objc(cs)AWXCountryListViewController","navigatorTitle":[{"kind":"identifier","text":"AWXCountryListViewController"}],"roleHeading":"Class","modules":[{"name":"Airwallex"}],"symbolKind":"class","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXCountryListViewController"}],"title":"AWXCountryListViewController"},"abstract":[{"type":"codeVoice","code":"AWXCountryListViewController"},{"type":"text","text":" includes a list of countries."}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXViewController"]},{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSCoding","doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSExtensionRequestHandling","doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/SQ","doc:\/\/org.cocoapods.Airwallex\/SH","doc:\/\/org.cocoapods.Airwallex\/s8SendableP","doc:\/\/org.cocoapods.Airwallex\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.Airwallex\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.Airwallex\/objc(pl)UIContentContainer","doc:\/\/org.cocoapods.Airwallex\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.Airwallex\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.Airwallex\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.Airwallex\/objc(pl)UIStateRestoring","doc:\/\/org.cocoapods.Airwallex\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.Airwallex\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.Airwallex\/objc(pl)UIUserActivityRestoring"]}],"topicSections":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCountryListViewController\/country","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCountryListViewController\/delegate"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXCountryListViewController"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxcountrylistviewcontroller"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxcountrylistviewcontroller"]}],"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCountryListViewController","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.Airwallex/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)UIFocusEnvironment"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXViewController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXViewController"}],"type":"topic","abstract":[{"code":"AWXViewController","type":"codeVoice"},{"text":" is the base view controller.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWXViewController"}],"title":"AWXViewController","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXViewController","kind":"symbol","url":"\/documentation\/airwallex\/awxviewcontroller"},"doc://org.cocoapods.Airwallex/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.Airwallex/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)UIContentContainer"},"doc://org.cocoapods.Airwallex/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.Airwallex/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SH"},"doc://org.cocoapods.Airwallex/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)UITraitEnvironment","type":"unresolvable","title":"UIKit.UITraitEnvironment"},"doc://org.cocoapods.Airwallex/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)UIStateRestoring"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCountryListViewController/country":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCountryListViewController\/country","navigatorTitle":[{"kind":"identifier","text":"country"}],"url":"\/documentation\/airwallex\/awxcountrylistviewcontroller\/country","role":"symbol","title":"country","type":"topic","abstract":[{"text":"A country has been selected.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"country"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AWXCountry","kind":"typeIdentifier","text":"AWXCountry"},{"kind":"text","text":"?"}],"kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCountryListViewController/delegate":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)AWXCountryListViewControllerDelegate","text":"AWXCountryListViewControllerDelegate"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"A delegate which handles country selection events."}],"navigatorTitle":[{"text":"delegate","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/airwallex\/awxcountrylistviewcontroller\/delegate","type":"topic","title":"delegate","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCountryListViewController\/delegate"},"doc://org.cocoapods.Airwallex/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.Airwallex/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSExtensionRequestHandling"},"doc://org.cocoapods.Airwallex/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/5UIKit23UITraitChangeObservableP","type":"unresolvable","title":"UIKit.UITraitChangeObservable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCountryListViewController":{"kind":"symbol","abstract":[{"type":"codeVoice","code":"AWXCountryListViewController"},{"type":"text","text":" includes a list of countries."}],"type":"topic","title":"AWXCountryListViewController","url":"\/documentation\/airwallex\/awxcountrylistviewcontroller","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCountryListViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXCountryListViewController","kind":"identifier"}],"navigatorTitle":[{"text":"AWXCountryListViewController","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)UIAppearanceContainer"},"doc://org.cocoapods.Airwallex/objc(pl)NSCoding":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSCoding","type":"unresolvable","title":"Foundation.NSCoding"},"doc://org.cocoapods.Airwallex/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)UIPasteConfigurationSupporting"},"doc://org.cocoapods.Airwallex/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)UIResponderStandardEditActions","type":"unresolvable","title":"UIKit.UIResponderStandardEditActions"},"doc://org.cocoapods.Airwallex/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SQ"},"doc://org.cocoapods.Airwallex/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)UIUserActivityRestoring","type":"unresolvable","title":"UIKit.UIUserActivityRestoring"},"doc://org.cocoapods.Airwallex/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/org.cocoapods.Airwallex\/s8SendableP"},"doc://org.cocoapods.Airwallex/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.Airwallex/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"abstract":[],"type":"topic","url":"\/documentation\/airwallex","title":"Airwallex","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"AWXCountryListViewController","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"AWXCountryListViewController","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AWXCountryListViewController"}],"op":"replace"},{"path":"\/topicSections","value":[{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCountryListViewController\/country","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCountryListViewController\/delegate"]}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXViewController"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXCountryListViewController"},{"kind":"text","text":" : "},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXViewController","kind":"typeIdentifier","text":"AWXViewController","preciseIdentifier":"c:objc(cs)AWXViewController"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXViewController\/title","value":"AWXViewController","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXViewController\/fragments","value":[{"text":"AWXViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXViewController\/navigatorTitle","value":[{"text":"AWXViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCountryListViewController~1country\/title","value":"country","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCountryListViewController~1country\/fragments","value":[{"kind":"identifier","text":"country"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCountryListViewController~1delegate\/title","value":"delegate","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCountryListViewController~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCountryListViewController\/title","value":"AWXCountryListViewController","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCountryListViewController\/fragments","value":[{"text":"AWXCountryListViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCountryListViewController\/navigatorTitle","value":[{"kind":"identifier","text":"AWXCountryListViewController"}],"op":"replace"}]}]}