{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXCandidate"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"code":"AWXCandidate","type":"codeVoice"},{"text":" includes the values of list","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCandidate"},"topicSections":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCandidate\/displayName","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCandidate\/value"],"anchor":"Instance-Properties"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxcandidate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxcandidate"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"AWXCandidate","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXCandidate"}],"roleHeading":"Class","externalID":"c:objc(cs)AWXCandidate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWXCandidate"}],"modules":[{"name":"Airwallex"}]},"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"],"kind":"relationships"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONDecodable","doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/SQ","doc:\/\/org.cocoapods.Airwallex\/SH"],"kind":"relationships"}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","abstract":[],"role":"collection","url":"\/documentation\/airwallex","title":"Airwallex","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCandidate/displayName":{"kind":"symbol","type":"topic","abstract":[{"text":"display name.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"displayName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCandidate\/displayName","url":"\/documentation\/airwallex\/awxcandidate\/displayname","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"displayName"}],"title":"displayName"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXJSONDecodable":{"url":"\/documentation\/airwallex\/awxjsondecodable","abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXJSONDecodable"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWXJSONDecodable"}],"type":"topic","title":"AWXJSONDecodable","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONDecodable","role":"symbol"},"doc://org.cocoapods.Airwallex/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP"},"doc://org.cocoapods.Airwallex/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.Airwallex/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject"},"doc://org.cocoapods.Airwallex/objc(cs)NSObject":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCandidate":{"url":"\/documentation\/airwallex\/awxcandidate","abstract":[{"type":"codeVoice","code":"AWXCandidate"},{"text":" includes the values of list","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXCandidate"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWXCandidate"}],"type":"topic","title":"AWXCandidate","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCandidate","role":"symbol"},"doc://org.cocoapods.Airwallex/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SH"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCandidate/value":{"url":"\/documentation\/airwallex\/awxcandidate\/value","abstract":[{"type":"text","text":"value."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","navigatorTitle":[{"text":"value","kind":"identifier"}],"type":"topic","title":"value","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCandidate\/value","role":"symbol"},"doc://org.cocoapods.Airwallex/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP"},"doc://org.cocoapods.Airwallex/SQ":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/SQ","title":"Swift.Equatable","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"AWXCandidate"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"AWXCandidate"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AWXCandidate"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCandidate\/displayName","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCandidate\/value"],"anchor":"Instance-Properties","generated":true}]},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"],"kind":"relationships"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONDecodable"],"kind":"relationships"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXCandidate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCandidate~1displayName\/title","op":"replace","value":"displayName"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCandidate~1displayName\/fragments","op":"replace","value":[{"text":"displayName","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONDecodable\/title","op":"replace","value":"AWXJSONDecodable"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONDecodable\/fragments","op":"replace","value":[{"text":"AWXJSONDecodable","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONDecodable\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AWXJSONDecodable"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCandidate\/title","op":"replace","value":"AWXCandidate"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCandidate\/fragments","op":"replace","value":[{"text":"AWXCandidate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCandidate\/navigatorTitle","op":"replace","value":[{"text":"AWXCandidate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCandidate~1value\/title","op":"replace","value":"value"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCandidate~1value\/fragments","op":"replace","value":[{"text":"value","kind":"identifier"}]}]}]}