{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"metadata":{"roleHeading":"Structure","symbolKind":"struct","modules":[{"name":"Airwallex"}],"title":"AWXCardBrand","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWXCardBrand"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXCardBrand"}],"externalID":"c:AWXConstants.h@T@AWXCardBrand"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXCardBrand"}]}],"kind":"declarations"}],"kind":"symbol","topicSections":[{"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand\/init(rawValue:)"],"generated":true},{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand\/brandType"],"generated":true},{"anchor":"Type-Properties","title":"Type Properties","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand\/JCB","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand\/allAvailable","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand\/amex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand\/dinersClub","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand\/discover","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand\/mastercard","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand\/unionPay","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand\/visa"],"generated":true},{"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand\/Equatable-Implementations"],"generated":true}],"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.Airwallex\/SQ","doc:\/\/org.cocoapods.Airwallex\/SH","doc:\/\/org.cocoapods.Airwallex\/SY","doc:\/\/org.cocoapods.Airwallex\/s8SendableP"],"kind":"relationships"}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/airwallex\/awxcardbrand"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxcardbrand"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardBrand":{"type":"topic","navigatorTitle":[{"text":"AWXCardBrand","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"AWXCardBrand","kind":"identifier"}],"abstract":[],"title":"AWXCardBrand","url":"\/documentation\/airwallex\/awxcardbrand","role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardBrand/amex":{"title":"amex","url":"\/documentation\/airwallex\/awxcardbrand\/amex","kind":"symbol","type":"topic","role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand\/amex","navigatorTitle":[{"text":"AWXCardBrandAmex","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"amex","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:AWXConstants.h@T@AWXCardBrand","text":"AWXCardBrand","kind":"typeIdentifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardBrand/unionPay":{"abstract":[],"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unionPay","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWXCardBrand","kind":"typeIdentifier","preciseIdentifier":"c:AWXConstants.h@T@AWXCardBrand"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand\/unionPay","type":"topic","title":"unionPay","url":"\/documentation\/airwallex\/awxcardbrand\/unionpay","navigatorTitle":[{"kind":"identifier","text":"AWXCardBrandUnionPay"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardBrand/Equatable-Implementations":{"abstract":[],"kind":"article","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand\/Equatable-Implementations","type":"topic","url":"\/documentation\/airwallex\/awxcardbrand\/equatable-implementations","title":"Equatable Implementations","role":"collectionGroup"},"doc://org.cocoapods.Airwallex/SQ":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardBrand/JCB":{"title":"JCB","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JCB","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWXCardBrand","kind":"typeIdentifier","preciseIdentifier":"c:AWXConstants.h@T@AWXCardBrand"}],"navigatorTitle":[{"text":"AWXCardBrandJCB","kind":"identifier"}],"type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand\/JCB","url":"\/documentation\/airwallex\/awxcardbrand\/jcb"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardBrand/init(rawValue:)":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand\/init(rawValue:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/airwallex\/awxcardbrand\/init(rawvalue:)","title":"init(rawValue:)","role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardBrand/brandType":{"type":"topic","url":"\/documentation\/airwallex\/awxcardbrand\/brandtype","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand\/brandType","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"brandType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@AWXBrandType","text":"AWXBrandType"}],"title":"brandType","kind":"symbol","role":"symbol"},"doc://org.cocoapods.Airwallex/SY":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardBrand/discover":{"abstract":[],"navigatorTitle":[{"text":"AWXCardBrandDiscover","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"discover"},{"kind":"text","text":": "},{"preciseIdentifier":"c:AWXConstants.h@T@AWXCardBrand","kind":"typeIdentifier","text":"AWXCardBrand"}],"role":"symbol","type":"topic","title":"discover","url":"\/documentation\/airwallex\/awxcardbrand\/discover","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand\/discover"},"doc://org.cocoapods.Airwallex/s8SendableP":{"title":"Swift.Sendable","identifier":"doc:\/\/org.cocoapods.Airwallex\/s8SendableP","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardBrand/visa":{"url":"\/documentation\/airwallex\/awxcardbrand\/visa","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"visa","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:AWXConstants.h@T@AWXCardBrand","text":"AWXCardBrand","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand\/visa","title":"visa","navigatorTitle":[{"text":"AWXCardBrandVisa","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardBrand/mastercard":{"type":"topic","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mastercard","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWXCardBrand","kind":"typeIdentifier","preciseIdentifier":"c:AWXConstants.h@T@AWXCardBrand"}],"url":"\/documentation\/airwallex\/awxcardbrand\/mastercard","title":"mastercard","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand\/mastercard","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWXCardBrandMastercard"}],"abstract":[]},"doc://org.cocoapods.Airwallex/SH":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","abstract":[],"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardBrand/dinersClub":{"navigatorTitle":[{"text":"AWXCardBrandDinersClub","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand\/dinersClub","title":"dinersClub","url":"\/documentation\/airwallex\/awxcardbrand\/dinersclub","abstract":[],"role":"symbol","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dinersClub","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWXCardBrand","preciseIdentifier":"c:AWXConstants.h@T@AWXCardBrand","kind":"typeIdentifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardBrand/allAvailable":{"title":"allAvailable","type":"topic","kind":"symbol","abstract":[],"url":"\/documentation\/airwallex\/awxcardbrand\/allavailable","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allAvailable"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AWXCardBrand","preciseIdentifier":"c:AWXConstants.h@T@AWXCardBrand"},{"kind":"text","text":"]"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand\/allAvailable","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Type Alias","op":"replace"},{"path":"\/metadata\/title","value":"AWXCardBrand","op":"replace"},{"path":"\/metadata\/symbolKind","value":"typealias","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AWXCardBrand"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AWXCardBrand"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"AWXCardBrand"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardBrand\/title","value":"AWXCardBrand","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardBrand\/fragments","value":[{"kind":"identifier","text":"AWXCardBrand"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardBrand\/navigatorTitle","value":[{"kind":"identifier","text":"AWXCardBrand"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardBrand~1amex\/title","value":"AWXCardBrandAmex","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardBrand~1amex\/fragments","value":[{"text":"AWXCardBrandAmex","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardBrand~1unionPay\/title","value":"AWXCardBrandUnionPay","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardBrand~1unionPay\/fragments","value":[{"text":"AWXCardBrandUnionPay","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardBrand~1JCB\/title","value":"AWXCardBrandJCB","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardBrand~1JCB\/fragments","value":[{"kind":"identifier","text":"AWXCardBrandJCB"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardBrand~1discover\/title","value":"AWXCardBrandDiscover","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardBrand~1discover\/fragments","value":[{"text":"AWXCardBrandDiscover","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardBrand~1visa\/title","value":"AWXCardBrandVisa","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardBrand~1visa\/fragments","value":[{"kind":"identifier","text":"AWXCardBrandVisa"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardBrand~1mastercard\/title","value":"AWXCardBrandMastercard","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardBrand~1mastercard\/fragments","value":[{"text":"AWXCardBrandMastercard","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardBrand~1dinersClub\/title","value":"AWXCardBrandDinersClub","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardBrand~1dinersClub\/fragments","value":[{"kind":"identifier","text":"AWXCardBrandDinersClub"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}