{"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/airwallex\/awxcardoptions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxcardoptions"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"type":"codeVoice","code":"AWXCardOptions"},{"type":"text","text":" includes the options of card."}],"topicSections":[{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardOptions\/autoCapture","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardOptions\/threeDs"]}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"]},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONEncodable","doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/SQ","doc:\/\/org.cocoapods.Airwallex\/SH"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardOptions"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXCardOptions","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXCardOptions"}],"roleHeading":"Class","symbolKind":"class","externalID":"c:objc(cs)AWXCardOptions","role":"symbol","title":"AWXCardOptions","navigatorTitle":[{"kind":"identifier","text":"AWXCardOptions"}],"modules":[{"name":"Airwallex"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardOptions/autoCapture":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoCapture"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"autoCapture"}],"title":"autoCapture","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardOptions\/autoCapture","type":"topic","abstract":[{"text":"Should capture automatically when confirm. Default to false. The payment intent will be captured automatically if it is true, and authorized only if it is false.","type":"text"}],"role":"symbol","url":"\/documentation\/airwallex\/awxcardoptions\/autocapture"},"doc://org.cocoapods.Airwallex/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://org.cocoapods.Airwallex/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP"},"doc://org.cocoapods.Airwallex/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SH","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardOptions":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AWXCardOptions","kind":"identifier"}],"kind":"symbol","abstract":[{"code":"AWXCardOptions","type":"codeVoice"},{"text":" includes the options of card.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"AWXCardOptions","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxcardoptions","title":"AWXCardOptions","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardOptions"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardOptions/threeDs":{"role":"symbol","title":"threeDs","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardOptions\/threeDs","url":"\/documentation\/airwallex\/awxcardoptions\/threeds","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"threeDs","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AWXThreeDs","text":"AWXThreeDs","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"threeDs"}],"abstract":[{"text":"ThreeDs object.","type":"text"}]},"doc://org.cocoapods.Airwallex/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SQ"},"doc://org.cocoapods.Airwallex/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://org.cocoapods.Airwallex/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXJSONEncodable":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXJSONEncodable","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"AWXJSONEncodable","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxjsonencodable","abstract":[],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONEncodable","type":"topic","title":"AWXJSONEncodable"},"doc://org.cocoapods.Airwallex/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"title":"Airwallex","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/airwallex","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"AWXCardOptions","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AWXCardOptions"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"AWXCardOptions","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardOptions\/autoCapture","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardOptions\/threeDs"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"],"kind":"relationships"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONEncodable"],"kind":"relationships"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXCardOptions","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardOptions~1autoCapture\/title","op":"replace","value":"autoCapture"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardOptions~1autoCapture\/fragments","op":"replace","value":[{"text":"autoCapture","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardOptions\/title","op":"replace","value":"AWXCardOptions"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardOptions\/fragments","op":"replace","value":[{"text":"AWXCardOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardOptions\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AWXCardOptions"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardOptions~1threeDs\/title","op":"replace","value":"threeDs"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardOptions~1threeDs\/fragments","op":"replace","value":[{"kind":"identifier","text":"threeDs"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONEncodable\/title","op":"replace","value":"AWXJSONEncodable"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONEncodable\/fragments","op":"replace","value":[{"text":"AWXJSONEncodable","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONEncodable\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AWXJSONEncodable"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}