{"kind":"symbol","abstract":[{"type":"codeVoice","code":"AWXCardProvider"},{"type":"text","text":" is a provider to handle payment method with card."}],"metadata":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AWXCardProvider"}],"externalID":"c:objc(cs)AWXCardProvider","symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"AWXCardProvider"}],"platforms":[{"message":"Will be removed in next major version release, use AirwallexPayment.CardProvider instead","beta":false,"deprecated":true,"unavailable":false}],"title":"AWXCardProvider","modules":[{"name":"Airwallex"}],"roleHeading":"Class"},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardProvider\/confirmPaymentIntent(with:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardProvider\/confirmPaymentIntent(with:billing:saveCard:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardProvider\/confirmPaymentIntent(withPaymentConsentId:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/SQ","doc:\/\/org.cocoapods.Airwallex\/SH"],"type":"conformsTo","title":"Conforms To"}],"sections":[],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Will be removed in next major version release, use AirwallexPayment.CardProvider instead"}],"type":"paragraph"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxcardprovider"]},{"paths":["\/documentation\/airwallex\/awxcardprovider"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXCardProvider","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardProvider"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.Airwallex/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardProvider/confirmPaymentIntent(with:billing:saveCard:)":{"url":"\/documentation\/airwallex\/awxcardprovider\/confirmpaymentintent(with:billing:savecard:)","kind":"symbol","abstract":[{"type":"text","text":"Confirm the payment intent with card and billing."}],"type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confirmPaymentIntent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AWXCard","preciseIdentifier":"c:objc(cs)AWXCard","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"billing","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AWXPlaceDetails","preciseIdentifier":"c:objc(cs)AWXPlaceDetails","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"saveCard","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"confirmPaymentIntentWithCard:billing:saveCard:","kind":"identifier"}],"deprecated":true,"title":"confirmPaymentIntent(with:billing:saveCard:)","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardProvider\/confirmPaymentIntent(with:billing:saveCard:)"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardProvider":{"kind":"symbol","url":"\/documentation\/airwallex\/awxcardprovider","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AWXCardProvider"}],"deprecated":true,"title":"AWXCardProvider","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardProvider","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AWXCardProvider","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"AWXCardProvider"},{"type":"text","text":" is a provider to handle payment method with card."}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardProvider/confirmPaymentIntent(with:)":{"kind":"symbol","url":"\/documentation\/airwallex\/awxcardprovider\/confirmpaymentintent(with:)","role":"symbol","type":"topic","navigatorTitle":[{"text":"confirmPaymentIntentWithPaymentConsent:","kind":"identifier"}],"deprecated":true,"title":"confirmPaymentIntent(with:)","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardProvider\/confirmPaymentIntent(with:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confirmPaymentIntent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPaymentConsent","text":"AWXPaymentConsent"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Confirm the payment intent with payment consent"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXDefaultProvider":{"abstract":[{"type":"text","text":"A provider which handles payment business."}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider","title":"AWXDefaultProvider","navigatorTitle":[{"kind":"identifier","text":"AWXDefaultProvider"}],"url":"\/documentation\/airwallex\/awxdefaultprovider","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXDefaultProvider","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardProvider/confirmPaymentIntent(withPaymentConsentId:)":{"url":"\/documentation\/airwallex\/awxcardprovider\/confirmpaymentintent(withpaymentconsentid:)","kind":"symbol","abstract":[{"type":"text","text":"Confirm the payment intent with payment consent ID."}],"type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confirmPaymentIntent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withPaymentConsentId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"confirmPaymentIntentWithPaymentConsentId:","kind":"identifier"}],"deprecated":true,"title":"confirmPaymentIntent(withPaymentConsentId:)","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardProvider\/confirmPaymentIntent(withPaymentConsentId:)"},"doc://org.cocoapods.Airwallex/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.Airwallex/SQ":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://org.cocoapods.Airwallex/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"abstract":[],"kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","url":"\/documentation\/airwallex"},"doc://org.cocoapods.Airwallex/SH":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/SH","type":"unresolvable","title":"Swift.Hashable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[{"unavailable":false,"deprecated":true,"beta":false}],"op":"replace","path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"AWXCardProvider","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"AWXCardProvider"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"AWXCardProvider"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardProvider\/confirmPaymentIntent(with:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardProvider\/confirmPaymentIntent(with:billing:saveCard:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardProvider\/confirmPaymentIntent(withPaymentConsentId:)"],"anchor":"Instance-Methods","title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider"],"type":"inheritsFrom","title":"Inherits From"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXCardProvider"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"AWXDefaultProvider","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider","preciseIdentifier":"c:objc(cs)AWXDefaultProvider"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":[{"inlineContent":[{"text":"Will be removed in next major version release, use AirwallexPayment.CardProvider instead","type":"text"}],"type":"paragraph"}],"op":"replace","path":"\/deprecationSummary"},{"value":"confirmPaymentIntentWithCard:billing:saveCard:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardProvider~1confirmPaymentIntent(with:billing:saveCard:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"confirmPaymentIntentWithCard:billing:saveCard:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardProvider~1confirmPaymentIntent(with:billing:saveCard:)\/fragments"},{"value":"AWXCardProvider","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardProvider\/title"},{"value":[{"kind":"identifier","text":"AWXCardProvider"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardProvider\/fragments"},{"value":[{"kind":"identifier","text":"AWXCardProvider"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardProvider\/navigatorTitle"},{"value":"confirmPaymentIntentWithPaymentConsent:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardProvider~1confirmPaymentIntent(with:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"confirmPaymentIntentWithPaymentConsent:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardProvider~1confirmPaymentIntent(with:)\/fragments"},{"value":"AWXDefaultProvider","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider\/title"},{"value":[{"kind":"identifier","text":"AWXDefaultProvider"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider\/fragments"},{"value":[{"kind":"identifier","text":"AWXDefaultProvider"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider\/navigatorTitle"},{"value":"confirmPaymentIntentWithPaymentConsentId:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardProvider~1confirmPaymentIntent(withPaymentConsentId:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"confirmPaymentIntentWithPaymentConsentId:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardProvider~1confirmPaymentIntent(withPaymentConsentId:)\/fragments"}]}]}