{"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRequest"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/SQ","doc:\/\/org.cocoapods.Airwallex\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxgetpaymentmethodsrequest"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxgetpaymentmethodsrequest"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"topicSections":[{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodsRequest\/cardType","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodsRequest\/customerId","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodsRequest\/fromCreatedAt","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodsRequest\/methodType","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodsRequest\/pageNum","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodsRequest\/pageSize","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodsRequest\/toCreatedAt"],"generated":true}],"metadata":{"modules":[{"name":"Airwallex"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXGetPaymentMethodsRequest","kind":"identifier"}],"role":"symbol","roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"AWXGetPaymentMethodsRequest"}],"title":"AWXGetPaymentMethodsRequest","symbolKind":"class","externalID":"c:objc(cs)AWXGetPaymentMethodsRequest"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXGetPaymentMethodsRequest","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"code":"AWXGetPaymentMethodsRequest","type":"codeVoice"},{"text":" includes all of the parameters needed to get payment methods.","type":"text"}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodsRequest","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentMethodsRequest/pageSize":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pageSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"role":"symbol","url":"\/documentation\/airwallex\/awxgetpaymentmethodsrequest\/pagesize","navigatorTitle":[{"text":"pageSize","kind":"identifier"}],"type":"topic","title":"pageSize","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodsRequest\/pageSize","abstract":[{"type":"text","text":"Number of payment methods to be listed per page."}],"kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentMethodsRequest":{"title":"AWXGetPaymentMethodsRequest","abstract":[{"type":"codeVoice","code":"AWXGetPaymentMethodsRequest"},{"type":"text","text":" includes all of the parameters needed to get payment methods."}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodsRequest","navigatorTitle":[{"text":"AWXGetPaymentMethodsRequest","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXGetPaymentMethodsRequest","kind":"identifier"}],"type":"topic","url":"\/documentation\/airwallex\/awxgetpaymentmethodsrequest","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentMethodsRequest/customerId":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customerId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"role":"symbol","url":"\/documentation\/airwallex\/awxgetpaymentmethodsrequest\/customerid","navigatorTitle":[{"kind":"identifier","text":"customerId"}],"type":"topic","abstract":[{"type":"text","text":"Customer ID."}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodsRequest\/customerId","kind":"symbol","title":"customerId"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRequest":{"title":"AWXRequest","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRequest","navigatorTitle":[{"kind":"identifier","text":"AWXRequest"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXRequest","kind":"identifier"}],"type":"topic","url":"\/documentation\/airwallex\/awxrequest","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","abstract":[],"type":"topic","kind":"symbol","title":"Airwallex","role":"collection"},"doc://org.cocoapods.Airwallex/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentMethodsRequest/pageNum":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageNum"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"title":"pageNum","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodsRequest\/pageNum","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pageNum"}],"abstract":[{"text":"Page number starting from 0.","type":"text"}],"url":"\/documentation\/airwallex\/awxgetpaymentmethodsrequest\/pagenum"},"doc://org.cocoapods.Airwallex/SH":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://org.cocoapods.Airwallex/SQ":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.Airwallex/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://org.cocoapods.Airwallex/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentMethodsRequest/methodType":{"role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"methodType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"title":"methodType","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodsRequest\/methodType","type":"topic","navigatorTitle":[{"text":"methodType","kind":"identifier"}],"abstract":[{"text":"Payment method type.","type":"text"}],"url":"\/documentation\/airwallex\/awxgetpaymentmethodsrequest\/methodtype"},"doc://org.cocoapods.Airwallex/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentMethodsRequest/cardType":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cardType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"cardType","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodsRequest\/cardType","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cardType"}],"abstract":[{"type":"text","text":"Card type."}],"url":"\/documentation\/airwallex\/awxgetpaymentmethodsrequest\/cardtype"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentMethodsRequest/fromCreatedAt":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fromCreatedAt"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"title":"fromCreatedAt","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodsRequest\/fromCreatedAt","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fromCreatedAt"}],"abstract":[{"type":"text","text":"The start time of created_at in ISO8601 format."}],"url":"\/documentation\/airwallex\/awxgetpaymentmethodsrequest\/fromcreatedat"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentMethodsRequest/toCreatedAt":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toCreatedAt","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"role":"symbol","url":"\/documentation\/airwallex\/awxgetpaymentmethodsrequest\/tocreatedat","navigatorTitle":[{"text":"toCreatedAt","kind":"identifier"}],"type":"topic","title":"toCreatedAt","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodsRequest\/toCreatedAt","abstract":[{"type":"text","text":"The end time of created_at in ISO8601 format"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"AWXGetPaymentMethodsRequest","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AWXGetPaymentMethodsRequest"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"AWXGetPaymentMethodsRequest","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodsRequest\/cardType","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodsRequest\/customerId","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodsRequest\/fromCreatedAt","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodsRequest\/methodType","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodsRequest\/pageNum","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodsRequest\/pageSize","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodsRequest\/toCreatedAt"],"anchor":"Instance-Properties"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRequest"]}],"op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AWXGetPaymentMethodsRequest"},{"kind":"text","text":" : "},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRequest","preciseIdentifier":"c:objc(cs)AWXRequest","kind":"typeIdentifier","text":"AWXRequest"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodsRequest~1pageSize\/title","value":"pageSize","op":"replace"},{"value":[{"text":"pageSize","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodsRequest~1pageSize\/fragments","op":"replace"},{"value":"AWXGetPaymentMethodsRequest","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodsRequest\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodsRequest\/fragments","value":[{"kind":"identifier","text":"AWXGetPaymentMethodsRequest"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodsRequest\/navigatorTitle","value":[{"kind":"identifier","text":"AWXGetPaymentMethodsRequest"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodsRequest~1customerId\/title","value":"customerId","op":"replace"},{"value":[{"kind":"identifier","text":"customerId"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodsRequest~1customerId\/fragments","op":"replace"},{"value":"AWXRequest","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRequest\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AWXRequest"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRequest\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AWXRequest"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRequest\/navigatorTitle","op":"replace"},{"value":"pageNum","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodsRequest~1pageNum\/title","op":"replace"},{"value":[{"kind":"identifier","text":"pageNum"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodsRequest~1pageNum\/fragments","op":"replace"},{"value":"methodType","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodsRequest~1methodType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"methodType"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodsRequest~1methodType\/fragments","op":"replace"},{"value":"cardType","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodsRequest~1cardType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"cardType"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodsRequest~1cardType\/fragments","op":"replace"},{"value":"fromCreatedAt","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodsRequest~1fromCreatedAt\/title","op":"replace"},{"value":[{"kind":"identifier","text":"fromCreatedAt"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodsRequest~1fromCreatedAt\/fragments","op":"replace"},{"value":"toCreatedAt","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodsRequest~1toCreatedAt\/title","op":"replace"},{"value":[{"kind":"identifier","text":"toCreatedAt"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodsRequest~1toCreatedAt\/fragments","op":"replace"}]}]}