{"sections":[],"abstract":[{"code":"AWXGetPaymentConsentsRequest","type":"codeVoice"},{"type":"text","text":" includes the request of payment consents."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXGetPaymentConsentsRequest","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AWXGetPaymentConsentsRequest"}],"externalID":"c:objc(cs)AWXGetPaymentConsentsRequest","modules":[{"name":"Airwallex"}],"roleHeading":"Class","title":"AWXGetPaymentConsentsRequest","symbolKind":"class","role":"symbol"},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentConsentsRequest\/customerId","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentConsentsRequest\/merchantTriggerReason","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentConsentsRequest\/nextTriggeredBy","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentConsentsRequest\/pageNum","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentConsentsRequest\/pageSize","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentConsentsRequest\/status"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRequest"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/SQ","doc:\/\/org.cocoapods.Airwallex\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"variants":[{"paths":["\/documentation\/airwallex\/awxgetpaymentconsentsrequest"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxgetpaymentconsentsrequest"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXGetPaymentConsentsRequest"}]}],"kind":"declarations"}],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentConsentsRequest","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentConsentsRequest/nextTriggeredBy":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextTriggeredBy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentConsentsRequest\/nextTriggeredBy","url":"\/documentation\/airwallex\/awxgetpaymentconsentsrequest\/nexttriggeredby","type":"topic","kind":"symbol","abstract":[{"text":"Next trigger By type.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"nextTriggeredBy"}],"title":"nextTriggeredBy"},"doc://org.cocoapods.Airwallex/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP"},"doc://org.cocoapods.Airwallex/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://org.cocoapods.Airwallex/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SH"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentConsentsRequest/pageNum":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageNum"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentConsentsRequest\/pageNum","url":"\/documentation\/airwallex\/awxgetpaymentconsentsrequest\/pagenum","type":"topic","abstract":[{"type":"text","text":"Page number starting from 0."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"pageNum"}],"title":"pageNum"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentConsentsRequest/customerId":{"url":"\/documentation\/airwallex\/awxgetpaymentconsentsrequest\/customerid","abstract":[{"type":"text","text":"Customer ID."}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customerId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"customerId"}],"kind":"symbol","title":"customerId","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentConsentsRequest\/customerId"},"doc://org.cocoapods.Airwallex/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentConsentsRequest/pageSize":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageSize"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentConsentsRequest\/pageSize","url":"\/documentation\/airwallex\/awxgetpaymentconsentsrequest\/pagesize","abstract":[{"type":"text","text":"Number of payment methods to be listed per page."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"pageSize"}],"title":"pageSize"},"doc://org.cocoapods.Airwallex/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","title":"Airwallex","abstract":[],"type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol"},"doc://org.cocoapods.Airwallex/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SQ","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentConsentsRequest/status":{"url":"\/documentation\/airwallex\/awxgetpaymentconsentsrequest\/status","abstract":[{"text":"Consent status.","type":"text"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"status","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"status","kind":"identifier"}],"kind":"symbol","title":"status","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentConsentsRequest\/status"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentConsentsRequest/merchantTriggerReason":{"abstract":[{"text":"Merchant trigger reason","type":"text"}],"title":"merchantTriggerReason","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"merchantTriggerReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@AirwallexMerchantTriggerReason","text":"AirwallexMerchantTriggerReason"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"merchantTriggerReason"}],"url":"\/documentation\/airwallex\/awxgetpaymentconsentsrequest\/merchanttriggerreason","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentConsentsRequest\/merchantTriggerReason"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRequest":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRequest","kind":"symbol","url":"\/documentation\/airwallex\/awxrequest","title":"AWXRequest","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXRequest"}],"navigatorTitle":[{"kind":"identifier","text":"AWXRequest"}],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentConsentsRequest":{"role":"symbol","title":"AWXGetPaymentConsentsRequest","abstract":[{"type":"codeVoice","code":"AWXGetPaymentConsentsRequest"},{"type":"text","text":" includes the request of payment consents."}],"url":"\/documentation\/airwallex\/awxgetpaymentconsentsrequest","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AWXGetPaymentConsentsRequest","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentConsentsRequest","type":"topic","navigatorTitle":[{"text":"AWXGetPaymentConsentsRequest","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AWXGetPaymentConsentsRequest"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AWXGetPaymentConsentsRequest"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AWXGetPaymentConsentsRequest"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentConsentsRequest\/customerId","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentConsentsRequest\/merchantTriggerReason","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentConsentsRequest\/nextTriggeredBy","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentConsentsRequest\/pageNum","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentConsentsRequest\/pageSize","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentConsentsRequest\/status"],"generated":true,"anchor":"Instance-Properties"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRequest"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXGetPaymentConsentsRequest"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXRequest","text":"AWXRequest","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRequest"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentConsentsRequest~1nextTriggeredBy\/title","value":"nextTriggeredBy"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentConsentsRequest~1nextTriggeredBy\/fragments","value":[{"kind":"identifier","text":"nextTriggeredBy"}]},{"value":"pageNum","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentConsentsRequest~1pageNum\/title"},{"value":[{"text":"pageNum","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentConsentsRequest~1pageNum\/fragments"},{"value":"customerId","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentConsentsRequest~1customerId\/title"},{"value":[{"kind":"identifier","text":"customerId"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentConsentsRequest~1customerId\/fragments"},{"value":"pageSize","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentConsentsRequest~1pageSize\/title"},{"value":[{"kind":"identifier","text":"pageSize"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentConsentsRequest~1pageSize\/fragments"},{"value":"status","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentConsentsRequest~1status\/title"},{"value":[{"text":"status","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentConsentsRequest~1status\/fragments"},{"value":"merchantTriggerReason","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentConsentsRequest~1merchantTriggerReason\/title"},{"value":[{"kind":"identifier","text":"merchantTriggerReason"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentConsentsRequest~1merchantTriggerReason\/fragments"},{"value":"AWXRequest","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRequest\/title"},{"value":[{"text":"AWXRequest","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRequest\/fragments"},{"value":[{"kind":"identifier","text":"AWXRequest"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRequest\/navigatorTitle"},{"value":"AWXGetPaymentConsentsRequest","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentConsentsRequest\/title"},{"value":[{"kind":"identifier","text":"AWXGetPaymentConsentsRequest"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentConsentsRequest\/fragments"},{"value":[{"kind":"identifier","text":"AWXGetPaymentConsentsRequest"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentConsentsRequest\/navigatorTitle"}]}]}