{"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypesResponse","interfaceLanguage":"swift"},"abstract":[{"type":"codeVoice","code":"AWXGetPaymentMethodTypesResponse"},{"type":"text","text":" includes the list of payment methods."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXGetPaymentMethodTypesResponse","kind":"identifier"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXResponse"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPage","doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/SQ","doc:\/\/org.cocoapods.Airwallex\/SH"],"title":"Conforms To","type":"conformsTo"}],"variants":[{"paths":["\/documentation\/airwallex\/awxgetpaymentmethodtypesresponse"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxgetpaymentmethodtypesresponse"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypesResponse\/items"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"}],"metadata":{"symbolKind":"class","externalID":"c:objc(cs)AWXGetPaymentMethodTypesResponse","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXGetPaymentMethodTypesResponse"}],"navigatorTitle":[{"kind":"identifier","text":"AWXGetPaymentMethodTypesResponse"}],"title":"AWXGetPaymentMethodTypesResponse","modules":[{"name":"Airwallex"}],"role":"symbol","roleHeading":"Class"},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentMethodTypesResponse":{"role":"symbol","url":"\/documentation\/airwallex\/awxgetpaymentmethodtypesresponse","type":"topic","abstract":[{"type":"codeVoice","code":"AWXGetPaymentMethodTypesResponse"},{"type":"text","text":" includes the list of payment methods."}],"title":"AWXGetPaymentMethodTypesResponse","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXGetPaymentMethodTypesResponse","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"AWXGetPaymentMethodTypesResponse","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypesResponse"},"doc://org.cocoapods.Airwallex/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.Airwallex/SH":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://org.cocoapods.Airwallex/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXResponse":{"type":"topic","url":"\/documentation\/airwallex\/awxresponse","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXResponse"}],"navigatorTitle":[{"kind":"identifier","text":"AWXResponse"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXResponse","title":"AWXResponse","role":"symbol"},"doc://org.cocoapods.Airwallex/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","type":"unresolvable"},"doc://org.cocoapods.Airwallex/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol","type":"topic","url":"\/documentation\/airwallex","role":"collection","abstract":[],"title":"Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentMethodTypesResponse/items":{"abstract":[{"type":"text","text":"Payment methods."}],"type":"topic","url":"\/documentation\/airwallex\/awxgetpaymentmethodtypesresponse\/items","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"items"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)AWXPaymentMethodType","kind":"typeIdentifier","text":"AWXPaymentMethodType"},{"kind":"text","text":"]"}],"role":"symbol","kind":"symbol","title":"items","navigatorTitle":[{"kind":"identifier","text":"items"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypesResponse\/items"},"doc://org.cocoapods.Airwallex/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPage":{"navigatorTitle":[{"kind":"identifier","text":"AWXPage"}],"type":"topic","title":"AWXPage","kind":"symbol","url":"\/documentation\/airwallex\/awxpage","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPage","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPage","kind":"identifier"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"AWXGetPaymentMethodTypesResponse","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"AWXGetPaymentMethodTypesResponse","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AWXGetPaymentMethodTypesResponse"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypesResponse\/items"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true}],"path":"\/topicSections","op":"replace"},{"value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXResponse"],"title":"Inherits From"},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPage"],"title":"Conforms To"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXGetPaymentMethodTypesResponse"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)AWXResponse","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXResponse","text":"AWXResponse"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"AWXGetPaymentMethodTypesResponse","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypesResponse\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AWXGetPaymentMethodTypesResponse"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypesResponse\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AWXGetPaymentMethodTypesResponse"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypesResponse\/navigatorTitle","op":"replace"},{"value":"AWXResponse","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXResponse\/title","op":"replace"},{"value":[{"text":"AWXResponse","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXResponse\/fragments","op":"replace"},{"value":[{"text":"AWXResponse","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXResponse\/navigatorTitle","op":"replace"},{"value":"items","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypesResponse~1items\/title","op":"replace"},{"value":[{"text":"items","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypesResponse~1items\/fragments","op":"replace"},{"value":"AWXPage","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPage\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AWXPage"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPage\/fragments","op":"replace"},{"value":[{"text":"AWXPage","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPage\/navigatorTitle","op":"replace"}]}]}