{"kind":"symbol","abstract":[{"type":"codeVoice","code":"AWXGetPaymentIntentResponse"},{"type":"text","text":" includes the information of payment intent."}],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXGetPaymentIntentResponse"}],"externalID":"c:objc(cs)AWXGetPaymentIntentResponse","symbolKind":"class","navigatorTitle":[{"text":"AWXGetPaymentIntentResponse","kind":"identifier"}],"title":"AWXGetPaymentIntentResponse","modules":[{"name":"Airwallex"}],"roleHeading":"Class"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentIntentResponse\/amount","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentIntentResponse\/availablePaymentMethodTypes","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentIntentResponse\/capturedAmount","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentIntentResponse\/clientSecret","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentIntentResponse\/createdAt","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentIntentResponse\/currency","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentIntentResponse\/customerId","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentIntentResponse\/id","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentIntentResponse\/merchantOrderId","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentIntentResponse\/order","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentIntentResponse\/requestId","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentIntentResponse\/status","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentIntentResponse\/updatedAt"],"anchor":"Instance-Properties","generated":true}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXResponse"],"kind":"relationships"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/SQ","doc:\/\/org.cocoapods.Airwallex\/SH"],"kind":"relationships"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxgetpaymentintentresponse"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxgetpaymentintentresponse"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXGetPaymentIntentResponse"}],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentIntentResponse"},"references":{"doc://org.cocoapods.Airwallex/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentIntentResponse/id":{"abstract":[{"type":"text","text":"Intent id."}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentIntentResponse\/id","title":"id","navigatorTitle":[{"text":"Id","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxgetpaymentintentresponse\/id","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentIntentResponse/availablePaymentMethodTypes":{"url":"\/documentation\/airwallex\/awxgetpaymentintentresponse\/availablepaymentmethodtypes","abstract":[{"type":"text","text":"Available payment method types."}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"availablePaymentMethodTypes","kind":"identifier"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"availablePaymentMethodTypes","kind":"identifier"}],"title":"availablePaymentMethodTypes","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentIntentResponse\/availablePaymentMethodTypes"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentIntentResponse/currency":{"abstract":[{"type":"text","text":"Currency."}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentIntentResponse\/currency","title":"currency","navigatorTitle":[{"kind":"identifier","text":"currency"}],"url":"\/documentation\/airwallex\/awxgetpaymentintentresponse\/currency","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currency"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentIntentResponse/order":{"kind":"symbol","abstract":[{"type":"text","text":"Order data."}],"url":"\/documentation\/airwallex\/awxgetpaymentintentresponse\/order","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"order","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"order"}],"title":"order","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentIntentResponse\/order"},"doc://org.cocoapods.Airwallex/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentIntentResponse/amount":{"abstract":[{"text":"Payment amount.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentIntentResponse\/amount","title":"amount","navigatorTitle":[{"kind":"identifier","text":"amount"}],"url":"\/documentation\/airwallex\/awxgetpaymentintentresponse\/amount","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"amount"},{"text":": ","kind":"text"},{"text":"NSDecimalNumber","preciseIdentifier":"c:objc(cs)NSDecimalNumber","kind":"typeIdentifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentIntentResponse/status":{"abstract":[{"text":"Payment status.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentIntentResponse\/status","title":"status","navigatorTitle":[{"text":"status","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxgetpaymentintentresponse\/status","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"status","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"abstract":[],"kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","url":"\/documentation\/airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentIntentResponse/requestId":{"url":"\/documentation\/airwallex\/awxgetpaymentintentresponse\/requestid","abstract":[{"type":"text","text":"Request id."}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"requestId","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"requestId","kind":"identifier"}],"title":"requestId","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentIntentResponse\/requestId"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentIntentResponse/updatedAt":{"url":"\/documentation\/airwallex\/awxgetpaymentintentresponse\/updatedat","kind":"symbol","abstract":[{"type":"text","text":"Updated date."}],"type":"topic","role":"symbol","title":"updatedAt","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updatedAt","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"updatedAt","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentIntentResponse\/updatedAt"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentIntentResponse/capturedAmount":{"abstract":[{"text":"Captured amount.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentIntentResponse\/capturedAmount","title":"capturedAmount","navigatorTitle":[{"text":"capturedAmount","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxgetpaymentintentresponse\/capturedamount","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"capturedAmount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSDecimalNumber","preciseIdentifier":"c:objc(cs)NSDecimalNumber"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXResponse":{"kind":"symbol","abstract":[],"url":"\/documentation\/airwallex\/awxresponse","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXResponse","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AWXResponse"}],"title":"AWXResponse","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXResponse"},"doc://org.cocoapods.Airwallex/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SQ"},"doc://org.cocoapods.Airwallex/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SH"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentIntentResponse":{"url":"\/documentation\/airwallex\/awxgetpaymentintentresponse","kind":"symbol","abstract":[{"code":"AWXGetPaymentIntentResponse","type":"codeVoice"},{"type":"text","text":" includes the information of payment intent."}],"type":"topic","role":"symbol","title":"AWXGetPaymentIntentResponse","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXGetPaymentIntentResponse","kind":"identifier"}],"navigatorTitle":[{"text":"AWXGetPaymentIntentResponse","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentIntentResponse"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentIntentResponse/clientSecret":{"url":"\/documentation\/airwallex\/awxgetpaymentintentresponse\/clientsecret","abstract":[{"type":"text","text":"Client secret."}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clientSecret","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"clientSecret","kind":"identifier"}],"title":"clientSecret","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentIntentResponse\/clientSecret"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentIntentResponse/merchantOrderId":{"url":"\/documentation\/airwallex\/awxgetpaymentintentresponse\/merchantorderid","kind":"symbol","abstract":[{"type":"text","text":"Merchant order id."}],"type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"merchantOrderId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"navigatorTitle":[{"text":"merchantOrderId","kind":"identifier"}],"title":"merchantOrderId","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentIntentResponse\/merchantOrderId"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentIntentResponse/createdAt":{"url":"\/documentation\/airwallex\/awxgetpaymentintentresponse\/createdat","abstract":[{"text":"Created date.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createdAt","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"createdAt","kind":"identifier"}],"title":"createdAt","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentIntentResponse\/createdAt"},"doc://org.cocoapods.Airwallex/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentIntentResponse/customerId":{"url":"\/documentation\/airwallex\/awxgetpaymentintentresponse\/customerid","abstract":[{"type":"text","text":"Customer id."}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customerId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"customerId"}],"title":"customerId","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentIntentResponse\/customerId"},"doc://org.cocoapods.Airwallex/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"AWXGetPaymentIntentResponse","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"AWXGetPaymentIntentResponse"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"AWXGetPaymentIntentResponse"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentIntentResponse\/amount","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentIntentResponse\/availablePaymentMethodTypes","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentIntentResponse\/capturedAmount","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentIntentResponse\/clientSecret","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentIntentResponse\/createdAt","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentIntentResponse\/currency","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentIntentResponse\/customerId","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentIntentResponse\/id","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentIntentResponse\/merchantOrderId","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentIntentResponse\/order","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentIntentResponse\/requestId","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentIntentResponse\/status","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentIntentResponse\/updatedAt"],"anchor":"Instance-Properties","generated":true}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXResponse"],"kind":"relationships"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"AWXGetPaymentIntentResponse","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXResponse","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXResponse","text":"AWXResponse"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"Id","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentIntentResponse~1id\/title"},{"value":[{"kind":"identifier","text":"Id"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentIntentResponse~1id\/fragments"},{"value":"availablePaymentMethodTypes","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentIntentResponse~1availablePaymentMethodTypes\/title"},{"value":[{"kind":"identifier","text":"availablePaymentMethodTypes"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentIntentResponse~1availablePaymentMethodTypes\/fragments"},{"value":"currency","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentIntentResponse~1currency\/title"},{"value":[{"kind":"identifier","text":"currency"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentIntentResponse~1currency\/fragments"},{"value":"order","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentIntentResponse~1order\/title"},{"value":[{"text":"order","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentIntentResponse~1order\/fragments"},{"value":"amount","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentIntentResponse~1amount\/title"},{"value":[{"text":"amount","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentIntentResponse~1amount\/fragments"},{"value":"status","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentIntentResponse~1status\/title"},{"value":[{"kind":"identifier","text":"status"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentIntentResponse~1status\/fragments"},{"value":"requestId","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentIntentResponse~1requestId\/title"},{"value":[{"kind":"identifier","text":"requestId"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentIntentResponse~1requestId\/fragments"},{"value":"updatedAt","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentIntentResponse~1updatedAt\/title"},{"value":[{"text":"updatedAt","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentIntentResponse~1updatedAt\/fragments"},{"value":"capturedAmount","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentIntentResponse~1capturedAmount\/title"},{"value":[{"text":"capturedAmount","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentIntentResponse~1capturedAmount\/fragments"},{"value":"AWXResponse","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXResponse\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXResponse\/fragments","value":[{"text":"AWXResponse","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXResponse\/navigatorTitle","value":[{"text":"AWXResponse","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentIntentResponse\/title","value":"AWXGetPaymentIntentResponse"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentIntentResponse\/fragments","value":[{"kind":"identifier","text":"AWXGetPaymentIntentResponse"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentIntentResponse\/navigatorTitle","value":[{"text":"AWXGetPaymentIntentResponse","kind":"identifier"}]},{"op":"replace","value":"clientSecret","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentIntentResponse~1clientSecret\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentIntentResponse~1clientSecret\/fragments","value":[{"kind":"identifier","text":"clientSecret"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentIntentResponse~1merchantOrderId\/title","value":"merchantOrderId"},{"value":[{"text":"merchantOrderId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentIntentResponse~1merchantOrderId\/fragments"},{"value":"createdAt","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentIntentResponse~1createdAt\/title"},{"value":[{"kind":"identifier","text":"createdAt"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentIntentResponse~1createdAt\/fragments"},{"value":"customerId","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentIntentResponse~1customerId\/title"},{"value":[{"text":"customerId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentIntentResponse~1customerId\/fragments"}]}]}