{"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXHTTPMethodPOST","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWXHTTPMethod","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXHTTPMethod","preciseIdentifier":"c:@EA@AWXHTTPMethod","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxhttpmethodpost"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxhttpmethodpost"]}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXHTTPMethodPOST","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWXHTTPMethod","kind":"typeIdentifier","preciseIdentifier":"c:@EA@AWXHTTPMethod"}],"role":"symbol","navigatorTitle":[{"text":"AWXHTTPMethodPOST","kind":"identifier"}],"modules":[{"name":"Airwallex"}],"symbolKind":"var","title":"AWXHTTPMethodPOST","roleHeading":"Global Variable","externalID":"c:@EA@AWXHTTPMethod@AWXHTTPMethodPOST"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXHTTPMethodPOST"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","abstract":[],"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXHTTPMethod":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXHTTPMethod","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXHTTPMethod","kind":"identifier"}],"type":"topic","abstract":[{"text":"Http request","type":"text"}],"url":"\/documentation\/airwallex\/awxhttpmethod","title":"AWXHTTPMethod","role":"symbol","navigatorTitle":[{"text":"AWXHTTPMethod","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXHTTPMethodPOST":{"title":"AWXHTTPMethodPOST","abstract":[],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXHTTPMethodPOST","kind":"symbol","type":"topic","navigatorTitle":[{"text":"AWXHTTPMethodPOST","kind":"identifier"}],"role":"symbol","url":"\/documentation\/airwallex\/awxhttpmethodpost","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXHTTPMethodPOST","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWXHTTPMethod","kind":"typeIdentifier","preciseIdentifier":"c:@EA@AWXHTTPMethod"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"AWXHTTPMethodPOST"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"AWXHTTPMethodPOST","kind":"identifier"}]},{"path":"\/hierarchy","op":"replace","value":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXHTTPMethod"]]}},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"AWXHTTPMethodPOST","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXHTTPMethod\/title","op":"replace","value":"AWXHTTPMethod"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXHTTPMethod\/fragments","op":"replace","value":[{"text":"AWXHTTPMethod","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXHTTPMethod\/navigatorTitle","op":"replace","value":[{"text":"AWXHTTPMethod","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXHTTPMethodPOST\/title","op":"replace","value":"AWXHTTPMethodPOST"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXHTTPMethodPOST\/fragments","op":"replace","value":[{"text":"AWXHTTPMethodPOST","kind":"identifier"}]}]}]}