{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXHTTPMethodGET","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@EA@AWXHTTPMethod","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXHTTPMethod","text":"AWXHTTPMethod","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXHTTPMethodGET"},"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxhttpmethodget"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxhttpmethodget"]}],"metadata":{"externalID":"c:@EA@AWXHTTPMethod@AWXHTTPMethodGET","title":"AWXHTTPMethodGET","navigatorTitle":[{"text":"AWXHTTPMethodGET","kind":"identifier"}],"role":"symbol","symbolKind":"var","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXHTTPMethodGET"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@EA@AWXHTTPMethod","text":"AWXHTTPMethod"}],"roleHeading":"Global Variable","modules":[{"name":"Airwallex"}]},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","url":"\/documentation\/airwallex","title":"Airwallex","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXHTTPMethodGET":{"title":"AWXHTTPMethodGET","type":"topic","role":"symbol","navigatorTitle":[{"text":"AWXHTTPMethodGET","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXHTTPMethodGET","url":"\/documentation\/airwallex\/awxhttpmethodget","kind":"symbol","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXHTTPMethodGET","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@EA@AWXHTTPMethod","text":"AWXHTTPMethod","kind":"typeIdentifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXHTTPMethod":{"kind":"symbol","type":"topic","abstract":[{"text":"Http request","type":"text"}],"role":"symbol","url":"\/documentation\/airwallex\/awxhttpmethod","title":"AWXHTTPMethod","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXHTTPMethod","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXHTTPMethod","kind":"identifier"}],"navigatorTitle":[{"text":"AWXHTTPMethod","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"AWXHTTPMethodGET","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"AWXHTTPMethodGET"}],"path":"\/metadata\/fragments"},{"op":"replace","value":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXHTTPMethod"]]},"path":"\/hierarchy"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"AWXHTTPMethodGET"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"AWXHTTPMethodGET","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXHTTPMethodGET\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AWXHTTPMethodGET"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXHTTPMethodGET\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXHTTPMethod\/title","value":"AWXHTTPMethod"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXHTTPMethod\/fragments","value":[{"text":"AWXHTTPMethod","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXHTTPMethod\/navigatorTitle","value":[{"text":"AWXHTTPMethod","kind":"identifier"}]}]}]}