{"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONEncodable","interfaceLanguage":"swift"},"metadata":{"symbolKind":"protocol","roleHeading":"Protocol","navigatorTitle":[{"kind":"identifier","text":"AWXJSONEncodable"}],"title":"AWXJSONEncodable","externalID":"c:objc(pl)AWXJSONEncodable","role":"symbol","modules":[{"name":"Airwallex"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXJSONEncodable"}]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxjsonencodable"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxjsonencodable"]}],"topicSections":[{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONEncodable\/encodeToJSON()"]}],"kind":"symbol","relationshipsSections":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject"]},{"title":"Conforming Types","kind":"relationships","type":"conformingTypes","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAddress","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCard","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardOptions","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDevice","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethodOptions","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPlaceDetails","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXThreeDs"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXJSONEncodable"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCard":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCard","url":"\/documentation\/airwallex\/awxcard","abstract":[{"type":"codeVoice","code":"AWXCard"},{"type":"text","text":" includes the information of a card."}],"navigatorTitle":[{"kind":"identifier","text":"AWXCard"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXCard"}],"title":"AWXCard","kind":"symbol","type":"topic","role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXThreeDs":{"title":"AWXThreeDs","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXThreeDs","kind":"symbol","url":"\/documentation\/airwallex\/awxthreeds","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXThreeDs","kind":"identifier"}],"navigatorTitle":[{"text":"AWXThreeDs","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"AWXThreeDs"},{"type":"text","text":" includes the information of 3ds."}]},"doc://org.cocoapods.Airwallex/objc(pl)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPlaceDetails":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPlaceDetails","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPlaceDetails"}],"type":"topic","navigatorTitle":[{"text":"AWXPlaceDetails","kind":"identifier"}],"abstract":[{"code":"AWXPlaceDetails","type":"codeVoice"},{"text":" includes the information of a billing address.","type":"text"}],"url":"\/documentation\/airwallex\/awxplacedetails","kind":"symbol","title":"AWXPlaceDetails"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardOptions":{"abstract":[{"code":"AWXCardOptions","type":"codeVoice"},{"text":" includes the options of card.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardOptions","url":"\/documentation\/airwallex\/awxcardoptions","role":"symbol","navigatorTitle":[{"text":"AWXCardOptions","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXCardOptions","kind":"identifier"}],"title":"AWXCardOptions","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXJSONEncodable":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONEncodable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXJSONEncodable"}],"title":"AWXJSONEncodable","navigatorTitle":[{"kind":"identifier","text":"AWXJSONEncodable"}],"abstract":[],"url":"\/documentation\/airwallex\/awxjsonencodable","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentMethodOptions":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethodOptions","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPaymentMethodOptions","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxpaymentmethodoptions","abstract":[{"type":"codeVoice","code":"AWXPaymentMethodOptions"},{"text":" includes the information of payment method options","type":"text"}],"title":"AWXPaymentMethodOptions","kind":"symbol","navigatorTitle":[{"text":"AWXPaymentMethodOptions","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXDevice":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDevice","navigatorTitle":[{"kind":"identifier","text":"AWXDevice"}],"kind":"symbol","title":"AWXDevice","url":"\/documentation\/airwallex\/awxdevice","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXDevice"}],"abstract":[{"type":"codeVoice","code":"AWXDevice"},{"text":" includes the information of device.","type":"text"}],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXAddress":{"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXAddress","kind":"identifier"}],"navigatorTitle":[{"text":"AWXAddress","kind":"identifier"}],"abstract":[{"code":"AWXAddress","type":"codeVoice"},{"text":" includes the information of an address.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAddress","title":"AWXAddress","url":"\/documentation\/airwallex\/awxaddress"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXJSONEncodable/encodeToJSON()":{"navigatorTitle":[{"text":"encodeToJSON","kind":"identifier"}],"abstract":[],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"encodeToJSON","kind":"identifier"},{"text":"() -> [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"url":"\/documentation\/airwallex\/awxjsonencodable\/encodetojson()","title":"encodeToJSON()","role":"symbol","required":true,"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONEncodable\/encodeToJSON()"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentMethod":{"abstract":[{"type":"codeVoice","code":"AWXPaymentMethod"},{"text":" includes the information of a payment method.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWXPaymentMethod"}],"url":"\/documentation\/airwallex\/awxpaymentmethod","title":"AWXPaymentMethod","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentMethod"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","role":"collection","title":"Airwallex","url":"\/documentation\/airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"AWXJSONEncodable"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"AWXJSONEncodable","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"AWXJSONEncodable","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONEncodable\/encodeToJSON()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAddress","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCard","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardOptions","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDevice","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethodOptions","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPlaceDetails","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXThreeDs"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXJSONEncodable"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCard\/title","value":"AWXCard"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCard\/fragments","value":[{"text":"AWXCard","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCard\/navigatorTitle","value":[{"text":"AWXCard","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXThreeDs\/title","value":"AWXThreeDs"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXThreeDs\/fragments","value":[{"kind":"identifier","text":"AWXThreeDs"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXThreeDs\/navigatorTitle","value":[{"text":"AWXThreeDs","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPlaceDetails\/title","value":"AWXPlaceDetails"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPlaceDetails\/fragments","value":[{"text":"AWXPlaceDetails","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPlaceDetails\/navigatorTitle","value":[{"text":"AWXPlaceDetails","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardOptions\/title","value":"AWXCardOptions"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardOptions\/fragments","value":[{"kind":"identifier","text":"AWXCardOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardOptions\/navigatorTitle","value":[{"text":"AWXCardOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONEncodable\/title","value":"AWXJSONEncodable"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONEncodable\/fragments","value":[{"kind":"identifier","text":"AWXJSONEncodable"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONEncodable\/navigatorTitle","value":[{"text":"AWXJSONEncodable","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethodOptions\/title","value":"AWXPaymentMethodOptions"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethodOptions\/fragments","value":[{"kind":"identifier","text":"AWXPaymentMethodOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethodOptions\/navigatorTitle","value":[{"text":"AWXPaymentMethodOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDevice\/title","value":"AWXDevice"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDevice\/fragments","value":[{"kind":"identifier","text":"AWXDevice"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDevice\/navigatorTitle","value":[{"kind":"identifier","text":"AWXDevice"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAddress\/title","value":"AWXAddress"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAddress\/fragments","value":[{"text":"AWXAddress","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAddress\/navigatorTitle","value":[{"kind":"identifier","text":"AWXAddress"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONEncodable~1encodeToJSON()\/title","value":"encodeToJSON"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONEncodable~1encodeToJSON()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"encodeToJSON"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethod\/title","value":"AWXPaymentMethod"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethod\/fragments","value":[{"kind":"identifier","text":"AWXPaymentMethod"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethod\/navigatorTitle","value":[{"text":"AWXPaymentMethod","kind":"identifier"}]}]}]}