{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXNextActionHandler","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxnextactionhandler"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxnextactionhandler"]}],"topicSections":[{"anchor":"Initializers","generated":true,"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXNextActionHandler\/init(delegate:session:)"]},{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXNextActionHandler\/paymentConsent"]},{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXNextActionHandler\/handle(_:)"]}],"metadata":{"symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXNextActionHandler","kind":"identifier"}],"modules":[{"name":"Airwallex"}],"title":"AWXNextActionHandler","navigatorTitle":[{"text":"AWXNextActionHandler","kind":"identifier"}],"externalID":"c:objc(cs)AWXNextActionHandler","role":"symbol","roleHeading":"Class"},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXNextActionHandler","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/SQ","doc:\/\/org.cocoapods.Airwallex\/SH"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXNextActionHandler/init(delegate:session:)":{"role":"symbol","kind":"symbol","url":"\/documentation\/airwallex\/awxnextactionhandler\/init(delegate:session:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"AWXProviderDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)AWXProviderDelegate"},{"text":", ","kind":"text"},{"text":"session","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AWXSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXSession"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithDelegate:session:","kind":"identifier"}],"abstract":[],"title":"init(delegate:session:)","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXNextActionHandler\/init(delegate:session:)"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol","type":"topic","url":"\/documentation\/airwallex","role":"collection","abstract":[],"title":"Airwallex"},"doc://org.cocoapods.Airwallex/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP"},"doc://org.cocoapods.Airwallex/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"},"doc://org.cocoapods.Airwallex/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP"},"doc://org.cocoapods.Airwallex/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.Airwallex/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXNextActionHandler/paymentConsent":{"role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"paymentConsent"}],"url":"\/documentation\/airwallex\/awxnextactionhandler\/paymentconsent","abstract":[{"type":"text","text":"Previously used\/generated payment consent"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentConsent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPaymentConsent","text":"AWXPaymentConsent"},{"kind":"text","text":"?"}],"title":"paymentConsent","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXNextActionHandler\/paymentConsent"},"doc://org.cocoapods.Airwallex/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SH"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXNextActionHandler":{"role":"symbol","kind":"symbol","url":"\/documentation\/airwallex\/awxnextactionhandler","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXNextActionHandler","kind":"identifier"}],"navigatorTitle":[{"text":"AWXNextActionHandler","kind":"identifier"}],"abstract":[],"title":"AWXNextActionHandler","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXNextActionHandler"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXNextActionHandler/handle(_:)":{"navigatorTitle":[{"kind":"identifier","text":"handleNextAction:"}],"kind":"symbol","url":"\/documentation\/airwallex\/awxnextactionhandler\/handle(_:)","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXNextActionHandler\/handle(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handle"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXConfirmPaymentNextAction","text":"AWXConfirmPaymentNextAction"},{"kind":"text","text":")"}],"type":"topic","role":"symbol","abstract":[],"title":"handle(_:)"},"doc://org.cocoapods.Airwallex/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SQ"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"AWXNextActionHandler"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"AWXNextActionHandler"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"AWXNextActionHandler","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXNextActionHandler\/paymentConsent"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"},{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXNextActionHandler\/handle(_:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXNextActionHandler\/init(delegate:session:)"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXNextActionHandler"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXNextActionHandler~1init(delegate:session:)\/title","op":"replace","value":"initWithDelegate:session:"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXNextActionHandler~1init(delegate:session:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithDelegate:session:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXNextActionHandler~1paymentConsent\/title","op":"replace","value":"paymentConsent"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXNextActionHandler~1paymentConsent\/fragments","op":"replace","value":[{"text":"paymentConsent","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXNextActionHandler\/title","op":"replace","value":"AWXNextActionHandler"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXNextActionHandler\/fragments","op":"replace","value":[{"kind":"identifier","text":"AWXNextActionHandler"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXNextActionHandler\/navigatorTitle","op":"replace","value":[{"text":"AWXNextActionHandler","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXNextActionHandler~1handle(_:)\/title","op":"replace","value":"handleNextAction:"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXNextActionHandler~1handle(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"handleNextAction:"}]}]}]}