{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentFormViewControllerDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxpaymentformviewcontrollerdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxpaymentformviewcontrollerdelegate"]}],"metadata":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPaymentFormViewControllerDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"AWXPaymentFormViewControllerDelegate","kind":"identifier"}],"symbolKind":"protocol","externalID":"c:objc(pl)AWXPaymentFormViewControllerDelegate","role":"symbol","title":"AWXPaymentFormViewControllerDelegate","roleHeading":"Protocol","modules":[{"name":"Airwallex"}]},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentFormViewControllerDelegate","interfaceLanguage":"swift"},"abstract":[{"text":"A delegate handles payment form result.","type":"text"}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject"],"type":"inheritsFrom"}],"topicSections":[{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentFormViewControllerDelegate\/paymentFormViewController(_:didConfirmPaymentMethod:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentFormViewControllerDelegate\/paymentFormViewController(_:didSelectOption:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentFormViewControllerDelegate\/paymentFormViewController(_:didUpdate:)"]}],"references":{"doc://org.cocoapods.Airwallex/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","title":"NSObject","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentFormViewControllerDelegate/paymentFormViewController(_:didConfirmPaymentMethod:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"paymentFormViewController:didConfirmPaymentMethod:"}],"url":"\/documentation\/airwallex\/awxpaymentformviewcontrollerdelegate\/paymentformviewcontroller(_:didconfirmpaymentmethod:)","abstract":[],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentFormViewControllerDelegate\/paymentFormViewController(_:didConfirmPaymentMethod:)","kind":"symbol","type":"topic","title":"paymentFormViewController(_:didConfirmPaymentMethod:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentFormViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AWXPaymentFormViewController","preciseIdentifier":"c:objc(cs)AWXPaymentFormViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didConfirmPaymentMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWXPaymentMethod","preciseIdentifier":"c:objc(cs)AWXPaymentMethod"},{"kind":"text","text":")"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","role":"collection","url":"\/documentation\/airwallex","kind":"symbol","title":"Airwallex","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentFormViewControllerDelegate/paymentFormViewController(_:didSelectOption:)":{"url":"\/documentation\/airwallex\/awxpaymentformviewcontrollerdelegate\/paymentformviewcontroller(_:didselectoption:)","title":"paymentFormViewController(_:didSelectOption:)","type":"topic","abstract":[{"text":"temporary solution, used for handling bank selection in ","type":"text"},{"code":"SchemaPaymentSectionController","type":"codeVoice"},{"text":" only","type":"text"},{"text":" ","type":"text"},{"text":"will be called after user select an option and before ","type":"text"},{"code":"paymentFormViewController:didUpdatePaymentMethod:","type":"codeVoice"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentFormViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AWXPaymentFormViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPaymentFormViewController"},{"text":", ","kind":"text"},{"text":"didSelectOption","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentFormViewControllerDelegate\/paymentFormViewController(_:didSelectOption:)","navigatorTitle":[{"text":"paymentFormViewController:didSelectOption:","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentFormViewControllerDelegate":{"kind":"symbol","title":"AWXPaymentFormViewControllerDelegate","role":"symbol","abstract":[{"type":"text","text":"A delegate handles payment form result."}],"navigatorTitle":[{"text":"AWXPaymentFormViewControllerDelegate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentFormViewControllerDelegate","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPaymentFormViewControllerDelegate","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxpaymentformviewcontrollerdelegate"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentFormViewControllerDelegate/paymentFormViewController(_:didUpdate:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"paymentFormViewController:didUpdatePaymentMethod:"}],"url":"\/documentation\/airwallex\/awxpaymentformviewcontrollerdelegate\/paymentformviewcontroller(_:didupdate:)","abstract":[],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentFormViewControllerDelegate\/paymentFormViewController(_:didUpdate:)","kind":"symbol","type":"topic","title":"paymentFormViewController(_:didUpdate:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentFormViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AWXPaymentFormViewController","preciseIdentifier":"c:objc(cs)AWXPaymentFormViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWXPaymentMethod","preciseIdentifier":"c:objc(cs)AWXPaymentMethod"},{"kind":"text","text":")"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"value":"AWXPaymentFormViewControllerDelegate","path":"\/metadata\/title","op":"replace"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"AWXPaymentFormViewControllerDelegate","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AWXPaymentFormViewControllerDelegate"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentFormViewControllerDelegate\/paymentFormViewController(_:didConfirmPaymentMethod:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentFormViewControllerDelegate\/paymentFormViewController(_:didSelectOption:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentFormViewControllerDelegate\/paymentFormViewController(_:didUpdate:)"],"generated":true,"anchor":"Instance-Methods"}],"path":"\/topicSections","op":"replace"},{"value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject"],"type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentFormViewControllerDelegate"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"paymentFormViewController:didConfirmPaymentMethod:","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentFormViewControllerDelegate~1paymentFormViewController(_:didConfirmPaymentMethod:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"paymentFormViewController:didConfirmPaymentMethod:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentFormViewControllerDelegate~1paymentFormViewController(_:didConfirmPaymentMethod:)\/fragments","op":"replace"},{"value":"paymentFormViewController:didSelectOption:","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentFormViewControllerDelegate~1paymentFormViewController(_:didSelectOption:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"paymentFormViewController:didSelectOption:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentFormViewControllerDelegate~1paymentFormViewController(_:didSelectOption:)\/fragments","op":"replace"},{"value":"AWXPaymentFormViewControllerDelegate","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentFormViewControllerDelegate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AWXPaymentFormViewControllerDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentFormViewControllerDelegate\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AWXPaymentFormViewControllerDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentFormViewControllerDelegate\/navigatorTitle","op":"replace"},{"value":"paymentFormViewController:didUpdatePaymentMethod:","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentFormViewControllerDelegate~1paymentFormViewController(_:didUpdate:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"paymentFormViewController:didUpdatePaymentMethod:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentFormViewControllerDelegate~1paymentFormViewController(_:didUpdate:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}