{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxpaymentintent"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxpaymentintent"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONDecodable","doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/SQ","doc:\/\/org.cocoapods.Airwallex\/SH"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent"},"abstract":[{"type":"codeVoice","code":"AWXPaymentIntent"},{"type":"text","text":" includes the information of payment intent."}],"seeAlsoSections":[{"anchor":"Preparation","generated":true,"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentConsentOptions","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAPIClientConfiguration"],"title":"Preparation"}],"metadata":{"title":"AWXPaymentIntent","symbolKind":"class","role":"symbol","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPaymentIntent","kind":"identifier"}],"modules":[{"name":"Airwallex"}],"externalID":"c:objc(cs)AWXPaymentIntent","navigatorTitle":[{"text":"AWXPaymentIntent","kind":"identifier"}]},"kind":"symbol","topicSections":[{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent\/amount","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent\/availablePaymentMethodTypes","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent\/clientSecret","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent\/currency","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent\/customerId","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent\/id","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent\/paymentConsents","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent\/paymentMethods","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent\/status"],"title":"Instance Properties"},{"anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent\/paymentSummaryItem(withTotalPriceLabel:)"],"title":"Instance Methods"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentIntent"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/Session":{"url":"\/documentation\/airwallex\/session","abstract":[{"type":"codeVoice","code":"Session"},{"type":"text","text":" is a specialized subclass of "},{"type":"codeVoice","code":"AWXSession"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Session"}],"navigatorTitle":[{"kind":"identifier","text":"Session"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session","title":"Session","role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentIntent/paymentConsents":{"title":"paymentConsents","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentConsents","kind":"identifier"},{"text":": [","kind":"text"},{"text":"AWXPaymentConsent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPaymentConsent"},{"text":"]","kind":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent\/paymentConsents","abstract":[{"text":"Payment consents .","type":"text"}],"url":"\/documentation\/airwallex\/awxpaymentintent\/paymentconsents","type":"topic","kind":"symbol","navigatorTitle":[{"text":"paymentConsents","kind":"identifier"}],"deprecated":true},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentIntent/customerId":{"url":"\/documentation\/airwallex\/awxpaymentintent\/customerid","title":"customerId","abstract":[{"type":"text","text":"The customer who is paying for this payment intent."}],"navigatorTitle":[{"kind":"identifier","text":"customerId"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customerId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent\/customerId","role":"symbol"},"doc://org.cocoapods.Airwallex/SH":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentIntent/paymentSummaryItem(withTotalPriceLabel:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentSummaryItem"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withTotalPriceLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"PKPaymentSummaryItem","preciseIdentifier":"c:objc(cs)PKPaymentSummaryItem"}],"type":"topic","title":"paymentSummaryItem(withTotalPriceLabel:)","url":"\/documentation\/airwallex\/awxpaymentintent\/paymentsummaryitem(withtotalpricelabel:)","role":"symbol","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"paymentSummaryItemWithTotalPriceLabel:"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent\/paymentSummaryItem(withTotalPriceLabel:)"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentConsentOptions":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentConsentOptions","kind":"symbol","url":"\/documentation\/airwallex\/paymentconsentoptions","type":"topic","abstract":[{"text":"Options for payment consents","type":"text"}],"role":"symbol","title":"PaymentConsentOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentConsentOptions"}],"navigatorTitle":[{"kind":"identifier","text":"PaymentConsentOptions"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentIntent/id":{"abstract":[{"type":"text","text":"Unique identifier for the payment intent."}],"navigatorTitle":[{"kind":"identifier","text":"Id"}],"role":"symbol","title":"id","url":"\/documentation\/airwallex\/awxpaymentintent\/id","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"id"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent\/id","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXAPIClientConfiguration":{"title":"AWXAPIClientConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXAPIClientConfiguration","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAPIClientConfiguration","role":"symbol","navigatorTitle":[{"text":"AWXAPIClientConfiguration","kind":"identifier"}],"type":"topic","abstract":[{"type":"codeVoice","code":"AWXAPIClientConfiguration"},{"type":"text","text":" contains the base configuration the API client needs."}],"kind":"symbol","url":"\/documentation\/airwallex\/awxapiclientconfiguration"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentIntent/paymentMethods":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent\/paymentMethods","kind":"symbol","type":"topic","url":"\/documentation\/airwallex\/awxpaymentintent\/paymentmethods","title":"paymentMethods","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentMethods"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AWXPaymentMethod","preciseIdentifier":"c:objc(cs)AWXPaymentMethod"},{"kind":"text","text":"]"}],"role":"symbol","abstract":[{"type":"text","text":"Payment methods."}],"deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"paymentMethods"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentIntent":{"title":"AWXPaymentIntent","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPaymentIntent","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/airwallex\/awxpaymentintent","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent","type":"topic","abstract":[{"type":"codeVoice","code":"AWXPaymentIntent"},{"type":"text","text":" includes the information of payment intent."}],"navigatorTitle":[{"text":"AWXPaymentIntent","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentIntent/status":{"title":"status","type":"topic","url":"\/documentation\/airwallex\/awxpaymentintent\/status","abstract":[{"type":"text","text":"Payment intent status. REQUIRES_PAYMENT_METHOD, REQUIRES_CUSTOMER_ACTION, REQUIRES_MERCHANT_ACTION, SUCCEEDED, CANCELLED"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent\/status","navigatorTitle":[{"kind":"identifier","text":"status"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentIntent/amount":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"amount","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSDecimalNumber","preciseIdentifier":"c:objc(cs)NSDecimalNumber","kind":"typeIdentifier"}],"role":"symbol","title":"amount","kind":"symbol","navigatorTitle":[{"text":"amount","kind":"identifier"}],"type":"topic","abstract":[{"text":"Payment amount. This is the order amount you would like to charge your customer.","type":"text"}],"url":"\/documentation\/airwallex\/awxpaymentintent\/amount","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent\/amount"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXJSONDecodable":{"abstract":[],"title":"AWXJSONDecodable","url":"\/documentation\/airwallex\/awxjsondecodable","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONDecodable","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXJSONDecodable"}],"navigatorTitle":[{"kind":"identifier","text":"AWXJSONDecodable"}],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXApplePayOptions":{"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions","title":"AWXApplePayOptions","url":"\/documentation\/airwallex\/awxapplepayoptions","abstract":[{"text":"Object used to construct PKPaymentRequest for Apple Pay.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"AWXApplePayOptions"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXApplePayOptions"}]},"doc://org.cocoapods.Airwallex/objc(cs)NSObject":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://org.cocoapods.Airwallex/SQ":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://org.cocoapods.Airwallex/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","type":"topic","url":"\/documentation\/airwallex","kind":"symbol","abstract":[],"title":"Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentIntent/clientSecret":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent\/clientSecret","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientSecret"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"url":"\/documentation\/airwallex\/awxpaymentintent\/clientsecret","title":"clientSecret","navigatorTitle":[{"kind":"identifier","text":"clientSecret"}],"abstract":[{"text":"Client secret for browser or app.","type":"text"}],"kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentIntent/currency":{"title":"currency","navigatorTitle":[{"kind":"identifier","text":"currency"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent\/currency","type":"topic","url":"\/documentation\/airwallex\/awxpaymentintent\/currency","abstract":[{"type":"text","text":"Amount currency."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currency"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"role":"symbol"},"doc://org.cocoapods.Airwallex/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.Airwallex/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentIntent/availablePaymentMethodTypes":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"availablePaymentMethodTypes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"navigatorTitle":[{"kind":"identifier","text":"availablePaymentMethodTypes"}],"role":"symbol","type":"topic","title":"availablePaymentMethodTypes","kind":"symbol","url":"\/documentation\/airwallex\/awxpaymentintent\/availablepaymentmethodtypes","abstract":[{"type":"text","text":"Available payment method types."}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent\/availablePaymentMethodTypes"},"doc://org.cocoapods.Airwallex/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AWXPaymentIntent"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"AWXPaymentIntent","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"AWXPaymentIntent","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent\/amount","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent\/availablePaymentMethodTypes","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent\/clientSecret","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent\/currency","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent\/customerId","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent\/id","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent\/paymentConsents","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent\/paymentMethods","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent\/status"],"anchor":"Instance-Properties","generated":true},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent\/paymentSummaryItem(withTotalPriceLabel:)"],"anchor":"Instance-Methods","generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"]},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONDecodable"]}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"anchor":"Preparation","generated":true,"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentConsentOptions","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAPIClientConfiguration"],"title":"Preparation"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPaymentIntent","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"Session","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session\/title","op":"replace"},{"value":[{"kind":"identifier","text":"Session"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"Session"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session\/navigatorTitle","op":"replace"},{"value":"paymentConsents","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentIntent~1paymentConsents\/title","op":"replace"},{"value":[{"kind":"identifier","text":"paymentConsents"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentIntent~1paymentConsents\/fragments","op":"replace"},{"value":"customerId","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentIntent~1customerId\/title","op":"replace"},{"value":[{"kind":"identifier","text":"customerId"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentIntent~1customerId\/fragments","op":"replace"},{"value":"paymentSummaryItemWithTotalPriceLabel:","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentIntent~1paymentSummaryItem(withTotalPriceLabel:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"paymentSummaryItemWithTotalPriceLabel:"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentIntent~1paymentSummaryItem(withTotalPriceLabel:)\/fragments","op":"replace"},{"value":"PaymentConsentOptions","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentConsentOptions\/title","op":"replace"},{"value":[{"kind":"identifier","text":"PaymentConsentOptions"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentConsentOptions\/fragments","op":"replace"},{"value":[{"text":"PaymentConsentOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentConsentOptions\/navigatorTitle","op":"replace"},{"value":"Id","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentIntent~1id\/title","op":"replace"},{"value":[{"kind":"identifier","text":"Id"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentIntent~1id\/fragments","op":"replace"},{"value":"AWXAPIClientConfiguration","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIClientConfiguration\/title","op":"replace"},{"value":[{"text":"AWXAPIClientConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIClientConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AWXAPIClientConfiguration"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIClientConfiguration\/navigatorTitle","op":"replace"},{"value":"paymentMethods","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentIntent~1paymentMethods\/title","op":"replace"},{"value":[{"kind":"identifier","text":"paymentMethods"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentIntent~1paymentMethods\/fragments","op":"replace"},{"value":"AWXPaymentIntent","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentIntent\/title","op":"replace"},{"value":[{"text":"AWXPaymentIntent","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentIntent\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AWXPaymentIntent"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentIntent\/navigatorTitle","op":"replace"},{"value":"status","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentIntent~1status\/title","op":"replace"},{"value":[{"text":"status","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentIntent~1status\/fragments","op":"replace"},{"value":"amount","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentIntent~1amount\/title","op":"replace"},{"value":[{"text":"amount","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentIntent~1amount\/fragments","op":"replace"},{"value":"AWXJSONDecodable","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONDecodable\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AWXJSONDecodable"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONDecodable\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AWXJSONDecodable"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONDecodable\/navigatorTitle","op":"replace"},{"value":"AWXApplePayOptions","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AWXApplePayOptions"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AWXApplePayOptions"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions\/navigatorTitle","op":"replace"},{"value":"clientSecret","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentIntent~1clientSecret\/title","op":"replace"},{"value":[{"text":"clientSecret","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentIntent~1clientSecret\/fragments","op":"replace"},{"value":"currency","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentIntent~1currency\/title","op":"replace"},{"value":[{"kind":"identifier","text":"currency"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentIntent~1currency\/fragments","op":"replace"},{"value":"availablePaymentMethodTypes","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentIntent~1availablePaymentMethodTypes\/title","op":"replace"},{"value":[{"kind":"identifier","text":"availablePaymentMethodTypes"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentIntent~1availablePaymentMethodTypes\/fragments","op":"replace"}]}]}