{"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentTransactionModeRecurring"},"metadata":{"roleHeading":"Global Variable","symbolKind":"var","externalID":"c:@AWXPaymentTransactionModeRecurring","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPaymentTransactionModeRecurring","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"title":"AWXPaymentTransactionModeRecurring","navigatorTitle":[{"text":"AWXPaymentTransactionModeRecurring","kind":"identifier"}],"role":"symbol","modules":[{"name":"Airwallex"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxpaymenttransactionmoderecurring"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxpaymenttransactionmoderecurring"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPaymentTransactionModeRecurring","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","sections":[],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentTransactionModeRecurring":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWXPaymentTransactionModeRecurring"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentTransactionModeRecurring","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentTransactionModeRecurring"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"title":"AWXPaymentTransactionModeRecurring","role":"symbol","type":"topic","url":"\/documentation\/airwallex\/awxpaymenttransactionmoderecurring","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","role":"collection","url":"\/documentation\/airwallex","kind":"symbol","title":"Airwallex","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"AWXPaymentTransactionModeRecurring"},{"value":"var","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"AWXPaymentTransactionModeRecurring","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentTransactionModeRecurring"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"AWXPaymentTransactionModeRecurring","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentTransactionModeRecurring\/title"},{"value":[{"kind":"identifier","text":"AWXPaymentTransactionModeRecurring"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentTransactionModeRecurring\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}