{"metadata":{"title":"AWXProviderDelegate","symbolKind":"protocol","externalID":"c:objc(pl)AWXProviderDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXProviderDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"AWXProviderDelegate","kind":"identifier"}],"role":"symbol","modules":[{"name":"Airwallex"}],"roleHeading":"Protocol"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/airwallex\/awxproviderdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxproviderdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXProviderDelegate\/hostViewController()","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXProviderDelegate\/provider(_:didCompleteWith:error:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXProviderDelegate\/provider(_:didCompleteWithPaymentConsentId:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXProviderDelegate\/provider(_:didInitializePaymentIntentId:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXProviderDelegate\/provider(_:shouldHandle:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXProviderDelegate\/provider(_:shouldInsert:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXProviderDelegate\/provider(_:shouldPresent:forceToDismiss:withAnimation:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXProviderDelegate\/providerDidEndRequest(_:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXProviderDelegate\/providerDidStartRequest(_:)"],"generated":true}],"abstract":[{"text":"A delegate which handles checkout results.","type":"text"}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject"],"kind":"relationships"},{"title":"Conforming Types","type":"conformingTypes","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler"],"kind":"relationships"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXProviderDelegate","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXProviderDelegate"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXProviderDelegate/providerDidStartRequest(_:)":{"abstract":[{"type":"text","text":"This method is called when it is doing requesting."}],"kind":"symbol","title":"providerDidStartRequest(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"providerDidStartRequest"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXDefaultProvider","text":"AWXDefaultProvider"},{"kind":"text","text":")"}],"url":"\/documentation\/airwallex\/awxproviderdelegate\/providerdidstartrequest(_:)","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXProviderDelegate\/providerDidStartRequest(_:)","required":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"providerDidStartRequest:"}]},"doc://org.cocoapods.Airwallex/objc(pl)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXProviderDelegate/provider(_:shouldPresent:forceToDismiss:withAnimation:)":{"url":"\/documentation\/airwallex\/awxproviderdelegate\/provider(_:shouldpresent:forcetodismiss:withanimation:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"provider","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AWXDefaultProvider","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXDefaultProvider"},{"text":", ","kind":"text"},{"text":"shouldPresent","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":"?, ","kind":"text"},{"text":"forceToDismiss","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"withAnimation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"provider:shouldPresentViewController:forceToDismiss:withAnimation:","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXProviderDelegate\/provider(_:shouldPresent:forceToDismiss:withAnimation:)","abstract":[{"text":"This method is called when new controller is required.","type":"text"}],"title":"provider(_:shouldPresent:forceToDismiss:withAnimation:)","role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXProviderDelegate/provider(_:shouldHandle:)":{"navigatorTitle":[{"text":"provider:shouldHandleNextAction:","kind":"identifier"}],"type":"topic","title":"provider(_:shouldHandle:)","url":"\/documentation\/airwallex\/awxproviderdelegate\/provider(_:shouldhandle:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"provider"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)AWXDefaultProvider","kind":"typeIdentifier","text":"AWXDefaultProvider"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldHandle"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AWXConfirmPaymentNextAction","kind":"typeIdentifier","text":"AWXConfirmPaymentNextAction"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXProviderDelegate\/provider(_:shouldHandle:)","abstract":[{"text":"This method is called when the next action is required.","type":"text"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/airwallex","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXProviderDelegate/provider(_:didInitializePaymentIntentId:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXProviderDelegate\/provider(_:didInitializePaymentIntentId:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"provider","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AWXDefaultProvider","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXDefaultProvider"},{"text":", ","kind":"text"},{"text":"didInitializePaymentIntentId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"url":"\/documentation\/airwallex\/awxproviderdelegate\/provider(_:didinitializepaymentintentid:)","abstract":[{"text":"This method is called when it is generated new payment intent.","type":"text"}],"navigatorTitle":[{"text":"provider:didInitializePaymentIntentId:","kind":"identifier"}],"kind":"symbol","title":"provider(_:didInitializePaymentIntentId:)","required":true,"role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXProviderDelegate/provider(_:didCompleteWith:error:)":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXProviderDelegate\/provider(_:didCompleteWith:error:)","type":"topic","abstract":[{"type":"text","text":"This method is called when payment is completed."}],"url":"\/documentation\/airwallex\/awxproviderdelegate\/provider(_:didcompletewith:error:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"provider:didCompleteWithStatus:error:"}],"title":"provider(_:didCompleteWith:error:)","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"provider"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXDefaultProvider","text":"AWXDefaultProvider"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didCompleteWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@AirwallexPaymentStatus","text":"AirwallexPaymentStatus"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")?)"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXProviderDelegate":{"role":"symbol","kind":"symbol","type":"topic","title":"AWXProviderDelegate","url":"\/documentation\/airwallex\/awxproviderdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXProviderDelegate"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXProviderDelegate","abstract":[{"type":"text","text":"A delegate which handles checkout results."}],"navigatorTitle":[{"kind":"identifier","text":"AWXProviderDelegate"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXProviderDelegate/provider(_:shouldInsert:)":{"kind":"symbol","title":"provider(_:shouldInsert:)","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXProviderDelegate\/provider(_:shouldInsert:)","navigatorTitle":[{"text":"provider:shouldInsertViewController:","kind":"identifier"}],"abstract":[{"type":"text","text":"This method is called when new controller is required. (as child view controller)"}],"role":"symbol","type":"topic","url":"\/documentation\/airwallex\/awxproviderdelegate\/provider(_:shouldinsert:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"provider"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXDefaultProvider","text":"AWXDefaultProvider"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldInsert"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"kind":"text","text":")"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXProviderDelegate/providerDidEndRequest(_:)":{"role":"symbol","title":"providerDidEndRequest(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"providerDidEndRequest","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AWXDefaultProvider","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXDefaultProvider"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"providerDidEndRequest:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/airwallex\/awxproviderdelegate\/providerdidendrequest(_:)","abstract":[{"type":"text","text":"This method is called when it is completing requesting."}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXProviderDelegate\/providerDidEndRequest(_:)","type":"topic","required":true},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXProviderDelegate/provider(_:didCompleteWithPaymentConsentId:)":{"kind":"symbol","role":"symbol","url":"\/documentation\/airwallex\/awxproviderdelegate\/provider(_:didcompletewithpaymentconsentid:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"provider","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AWXDefaultProvider","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXDefaultProvider"},{"text":", ","kind":"text"},{"text":"didCompleteWithPaymentConsentId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXProviderDelegate\/provider(_:didCompleteWithPaymentConsentId:)","title":"provider(_:didCompleteWithPaymentConsentId:)","type":"topic","abstract":[{"type":"text","text":"This method is called when payment is completed and payment consent id is produced."}],"navigatorTitle":[{"text":"provider:didCompleteWithPaymentConsentId:","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXProviderDelegate/hostViewController()":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"hostViewController"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hostViewController"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"}],"abstract":[{"text":"The view controller that any additional UI (e.g. 3DS view, error alert view) will be presented on.","type":"text"}],"url":"\/documentation\/airwallex\/awxproviderdelegate\/hostviewcontroller()","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXProviderDelegate\/hostViewController()","title":"hostViewController()"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentSessionHandler":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PaymentSessionHandler","kind":"identifier"}],"role":"symbol","abstract":[{"text":"A low-level API handler for managing Airwallex payment sessions.","type":"text"}],"navigatorTitle":[{"text":"PaymentSessionHandler","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler","type":"topic","title":"PaymentSessionHandler","url":"\/documentation\/airwallex\/paymentsessionhandler"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","value":"AWXProviderDelegate","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"AWXProviderDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"AWXProviderDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXProviderDelegate\/hostViewController()","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXProviderDelegate\/provider(_:didCompleteWith:error:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXProviderDelegate\/provider(_:didCompleteWithPaymentConsentId:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXProviderDelegate\/provider(_:didInitializePaymentIntentId:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXProviderDelegate\/provider(_:shouldHandle:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXProviderDelegate\/provider(_:shouldInsert:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXProviderDelegate\/provider(_:shouldPresent:forceToDismiss:withAnimation:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXProviderDelegate\/providerDidEndRequest(_:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXProviderDelegate\/providerDidStartRequest(_:)"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler"],"title":"Conforming Types","kind":"relationships","type":"conformingTypes"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXProviderDelegate"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject"},{"kind":"text","text":">"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXProviderDelegate~1providerDidStartRequest(_:)\/title","value":"providerDidStartRequest:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXProviderDelegate~1providerDidStartRequest(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"providerDidStartRequest:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXProviderDelegate~1provider(_:shouldPresent:forceToDismiss:withAnimation:)\/title","value":"provider:shouldPresentViewController:forceToDismiss:withAnimation:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXProviderDelegate~1provider(_:shouldPresent:forceToDismiss:withAnimation:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"provider:shouldPresentViewController:forceToDismiss:withAnimation:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXProviderDelegate~1provider(_:shouldHandle:)\/title","value":"provider:shouldHandleNextAction:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXProviderDelegate~1provider(_:shouldHandle:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"provider:shouldHandleNextAction:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXProviderDelegate~1provider(_:didInitializePaymentIntentId:)\/title","value":"provider:didInitializePaymentIntentId:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXProviderDelegate~1provider(_:didInitializePaymentIntentId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"provider:didInitializePaymentIntentId:"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXProviderDelegate~1provider(_:didCompleteWith:error:)\/title","value":"provider:didCompleteWithStatus:error:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXProviderDelegate~1provider(_:didCompleteWith:error:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"provider:didCompleteWithStatus:error:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXProviderDelegate\/title","value":"AWXProviderDelegate","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXProviderDelegate\/fragments","value":[{"text":"AWXProviderDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXProviderDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"AWXProviderDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXProviderDelegate~1provider(_:shouldInsert:)\/title","value":"provider:shouldInsertViewController:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXProviderDelegate~1provider(_:shouldInsert:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"provider:shouldInsertViewController:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXProviderDelegate~1providerDidEndRequest(_:)\/title","value":"providerDidEndRequest:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXProviderDelegate~1providerDidEndRequest(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"providerDidEndRequest:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXProviderDelegate~1provider(_:didCompleteWithPaymentConsentId:)\/title","value":"provider:didCompleteWithPaymentConsentId:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXProviderDelegate~1provider(_:didCompleteWithPaymentConsentId:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"provider:didCompleteWithPaymentConsentId:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXProviderDelegate~1hostViewController()\/title","value":"hostViewController","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXProviderDelegate~1hostViewController()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"hostViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler\/title","value":"PaymentSessionHandler","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler\/fragments","value":[{"kind":"identifier","text":"PaymentSessionHandler"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler\/navigatorTitle","value":[{"text":"PaymentSessionHandler","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}