{"metadata":{"modules":[{"name":"Airwallex"}],"title":"AWXPaymentMethod","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentMethod"}],"role":"symbol","roleHeading":"Class","externalID":"c:objc(cs)AWXPaymentMethod","navigatorTitle":[{"kind":"identifier","text":"AWXPaymentMethod"}],"symbolKind":"class"},"topicSections":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod\/additionalParams","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod\/billing","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod\/card","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod\/customerId","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod\/id","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod\/type"]},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod\/appendAdditionalParams(_:)"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentMethod"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"kind":"symbol","relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"]},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONDecodable","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONEncodable","doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/SQ","doc:\/\/org.cocoapods.Airwallex\/SH"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/airwallex\/awxpaymentmethod"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxpaymentmethod"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"code":"AWXPaymentMethod","type":"codeVoice"},{"text":" includes the information of a payment method.","type":"text"}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXJSONEncodable":{"navigatorTitle":[{"text":"AWXJSONEncodable","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"AWXJSONEncodable","kind":"identifier"}],"abstract":[],"title":"AWXJSONEncodable","kind":"symbol","type":"topic","url":"\/documentation\/airwallex\/awxjsonencodable","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONEncodable","role":"symbol"},"doc://org.cocoapods.Airwallex/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentMethod":{"title":"AWXPaymentMethod","url":"\/documentation\/airwallex\/awxpaymentmethod","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPaymentMethod","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod","navigatorTitle":[{"text":"AWXPaymentMethod","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"AWXPaymentMethod"},{"type":"text","text":" includes the information of a payment method."}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"kind":"symbol","abstract":[],"role":"collection","type":"topic","url":"\/documentation\/airwallex","title":"Airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"},"doc://org.cocoapods.Airwallex/objc(cs)NSObject":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXJSONDecodable":{"url":"\/documentation\/airwallex\/awxjsondecodable","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONDecodable","title":"AWXJSONDecodable","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"AWXJSONDecodable"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXJSONDecodable","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentMethod/type":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"type"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod\/type","kind":"symbol","role":"symbol","url":"\/documentation\/airwallex\/awxpaymentmethod\/type","abstract":[{"text":"Type of the payment method. One of card, wechatpay, applepay.","type":"text"}],"type":"topic","title":"type"},"doc://org.cocoapods.Airwallex/SQ":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentMethod/card":{"navigatorTitle":[{"text":"card","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"card","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWXCard","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXCard"},{"text":"?","kind":"text"}],"title":"card","abstract":[{"type":"text","text":"Card object."}],"kind":"symbol","type":"topic","url":"\/documentation\/airwallex\/awxpaymentmethod\/card","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod\/card","role":"symbol"},"doc://org.cocoapods.Airwallex/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentMethod/id":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Id"}],"abstract":[{"type":"text","text":"Unique identifier for the payment method."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"role":"symbol","type":"topic","url":"\/documentation\/airwallex\/awxpaymentmethod\/id","title":"id","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod\/id"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentMethod/appendAdditionalParams(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"appendAdditionalParams"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"])","kind":"text"}],"navigatorTitle":[{"text":"appendAdditionalParams:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod\/appendAdditionalParams(_:)","kind":"symbol","role":"symbol","url":"\/documentation\/airwallex\/awxpaymentmethod\/appendadditionalparams(_:)","abstract":[],"type":"topic","title":"appendAdditionalParams(_:)"},"doc://org.cocoapods.Airwallex/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.Airwallex/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentMethod/customerId":{"title":"customerId","url":"\/documentation\/airwallex\/awxpaymentmethod\/customerid","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customerId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod\/customerId","navigatorTitle":[{"text":"customerId","kind":"identifier"}],"abstract":[{"text":"The customer this payment method belongs to.","type":"text"}]},"doc://org.cocoapods.Airwallex/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentMethod/billing":{"title":"billing","url":"\/documentation\/airwallex\/awxpaymentmethod\/billing","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"billing","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPlaceDetails","text":"AWXPlaceDetails"},{"text":"?","kind":"text"}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod\/billing","navigatorTitle":[{"text":"billing","kind":"identifier"}],"abstract":[{"type":"text","text":"Billing object."}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentMethod/additionalParams":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"additionalParams"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"navigatorTitle":[{"kind":"identifier","text":"additionalParams"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod\/additionalParams","kind":"symbol","role":"symbol","url":"\/documentation\/airwallex\/awxpaymentmethod\/additionalparams","abstract":[{"type":"text","text":"Additional params  for wechat, redirect or applepay type."}],"type":"topic","title":"additionalParams"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"AWXPaymentMethod","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"AWXPaymentMethod","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AWXPaymentMethod"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod\/additionalParams","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod\/billing","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod\/card","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod\/customerId","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod\/id","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod\/type"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"},{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod\/appendAdditionalParams(_:)"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}],"path":"\/topicSections"},{"op":"replace","value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"]},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONDecodable","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONEncodable"]}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPaymentMethod","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"AWXJSONEncodable","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONEncodable\/title"},{"op":"replace","value":[{"text":"AWXJSONEncodable","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONEncodable\/fragments"},{"op":"replace","value":[{"text":"AWXJSONEncodable","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONEncodable\/navigatorTitle"},{"op":"replace","value":"AWXPaymentMethod","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethod\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AWXPaymentMethod"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethod\/fragments"},{"op":"replace","value":[{"text":"AWXPaymentMethod","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethod\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONDecodable\/title","op":"replace","value":"AWXJSONDecodable"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONDecodable\/fragments","op":"replace","value":[{"text":"AWXJSONDecodable","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONDecodable\/navigatorTitle","op":"replace","value":[{"text":"AWXJSONDecodable","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethod~1type\/title","op":"replace","value":"type"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethod~1type\/fragments","op":"replace","value":[{"text":"type","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethod~1card\/title","op":"replace","value":"card"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethod~1card\/fragments","op":"replace","value":[{"kind":"identifier","text":"card"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethod~1id\/title","op":"replace","value":"Id"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethod~1id\/fragments","op":"replace","value":[{"kind":"identifier","text":"Id"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethod~1appendAdditionalParams(_:)\/title","op":"replace","value":"appendAdditionalParams:"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethod~1appendAdditionalParams(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"appendAdditionalParams:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethod~1customerId\/title","value":"customerId","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethod~1customerId\/fragments","value":[{"kind":"identifier","text":"customerId"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethod~1billing\/title","value":"billing","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethod~1billing\/fragments","value":[{"text":"billing","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethod~1additionalParams\/title","value":"additionalParams","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethod~1additionalParams\/fragments","value":[{"kind":"identifier","text":"additionalParams"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}