{"metadata":{"navigatorTitle":[{"text":"AWXPageViewTrackable","kind":"identifier"}],"symbolKind":"protocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPageViewTrackable"}],"role":"symbol","roleHeading":"Protocol","externalID":"c:objc(pl)AWXPageViewTrackable","title":"AWXPageViewTrackable","modules":[{"name":"Airwallex"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPageViewTrackable"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPageViewTrackable","interfaceLanguage":"swift"},"relationshipsSections":[{"type":"conformingTypes","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentFormViewController"],"title":"Conforming Types","kind":"relationships"}],"variants":[{"paths":["\/documentation\/airwallex\/awxpageviewtrackable"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxpageviewtrackable"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPageViewTrackable\/additionalInfo","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPageViewTrackable\/pageName"],"anchor":"Instance-Properties"}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPageViewTrackable/additionalInfo":{"kind":"symbol","url":"\/documentation\/airwallex\/awxpageviewtrackable\/additionalinfo","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"additionalInfo"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPageViewTrackable\/additionalInfo","title":"additionalInfo","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"additionalInfo"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentFormViewController":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentFormViewController","type":"topic","abstract":[{"type":"codeVoice","code":"AWXPaymentFormViewController"},{"type":"text","text":" handles payment form."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWXPaymentFormViewController"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentFormViewController"}],"url":"\/documentation\/airwallex\/awxpaymentformviewcontroller","title":"AWXPaymentFormViewController","role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPageViewTrackable/pageName":{"abstract":[],"type":"topic","url":"\/documentation\/airwallex\/awxpageviewtrackable\/pagename","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPageViewTrackable\/pageName","kind":"symbol","required":true,"role":"symbol","navigatorTitle":[{"text":"pageName","kind":"identifier"}],"title":"pageName","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pageName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"abstract":[],"url":"\/documentation\/airwallex","role":"collection","title":"Airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","type":"topic","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPageViewTrackable":{"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPageViewTrackable","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"AWXPageViewTrackable","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxpageviewtrackable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPageViewTrackable","kind":"identifier"}],"role":"symbol","title":"AWXPageViewTrackable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"value":"AWXPageViewTrackable","path":"\/metadata\/title","op":"replace"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"AWXPageViewTrackable","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"AWXPageViewTrackable","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPageViewTrackable\/additionalInfo","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPageViewTrackable\/pageName"]}],"path":"\/topicSections","op":"replace"},{"value":[{"title":"Conforming Types","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentFormViewController"],"type":"conformingTypes","kind":"relationships"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPageViewTrackable"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"additionalInfo","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPageViewTrackable~1additionalInfo\/title","op":"replace"},{"value":[{"kind":"identifier","text":"additionalInfo"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPageViewTrackable~1additionalInfo\/fragments","op":"replace"},{"value":"AWXPaymentFormViewController","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentFormViewController\/title","op":"replace"},{"value":[{"text":"AWXPaymentFormViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentFormViewController\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AWXPaymentFormViewController"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentFormViewController\/navigatorTitle","op":"replace"},{"value":"pageName","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPageViewTrackable~1pageName\/title","op":"replace"},{"value":[{"text":"pageName","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPageViewTrackable~1pageName\/fragments","op":"replace"},{"value":"AWXPageViewTrackable","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPageViewTrackable\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AWXPageViewTrackable"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPageViewTrackable\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AWXPageViewTrackable"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPageViewTrackable\/navigatorTitle","op":"replace"}]}]}