{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxpaymentresultdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxpaymentresultdelegate"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentResultDelegate"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentResultDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol"}],"platforms":["iOS"]}]}],"kind":"symbol","metadata":{"navigatorTitle":[{"text":"AWXPaymentResultDelegate","kind":"identifier"}],"symbolKind":"protocol","role":"symbol","modules":[{"name":"Airwallex"}],"externalID":"c:objc(pl)AWXPaymentResultDelegate","roleHeading":"Protocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentResultDelegate"}],"title":"AWXPaymentResultDelegate"},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement"],"title":"Conforming Types","type":"conformingTypes"}],"sections":[],"topicSections":[{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentResultDelegate\/paymentViewController(_:didCompleteWith:error:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentResultDelegate\/paymentViewController(_:didCompleteWithPaymentConsentId:)"],"generated":true}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentResultDelegate/paymentViewController(_:didCompleteWith:error:)":{"title":"paymentViewController(_:didCompleteWith:error:)","url":"\/documentation\/airwallex\/awxpaymentresultdelegate\/paymentviewcontroller(_:didcompletewith:error:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"didCompleteWith","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AirwallexPaymentStatus","preciseIdentifier":"c:@E@AirwallexPaymentStatus","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": (any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"type":"topic","role":"symbol","kind":"symbol","required":true,"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentResultDelegate\/paymentViewController(_:didCompleteWith:error:)","navigatorTitle":[{"text":"paymentViewController:didCompleteWithStatus:error:","kind":"identifier"}],"abstract":[{"type":"text","text":"This method is called when the user has completed the checkout."}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentResultDelegate/paymentViewController(_:didCompleteWithPaymentConsentId:)":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentResultDelegate\/paymentViewController(_:didCompleteWithPaymentConsentId:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":"?, ","kind":"text"},{"text":"didCompleteWithPaymentConsentId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"paymentViewController:didCompleteWithPaymentConsentId:"}],"url":"\/documentation\/airwallex\/awxpaymentresultdelegate\/paymentviewcontroller(_:didcompletewithpaymentconsentid:)","title":"paymentViewController(_:didCompleteWithPaymentConsentId:)","type":"topic","abstract":[{"type":"text","text":"This method is called when the user has completed the checkout and payment consent id is produced."}],"role":"symbol"},"doc://org.cocoapods.Airwallex/objc(pl)NSObject":{"title":"NSObject","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentResultDelegate":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWXPaymentResultDelegate"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentResultDelegate"}],"abstract":[],"title":"AWXPaymentResultDelegate","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentResultDelegate","url":"\/documentation\/airwallex\/awxpaymentresultdelegate"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"kind":"symbol","abstract":[],"role":"collection","type":"topic","url":"\/documentation\/airwallex","title":"Airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement":{"navigatorTitle":[{"text":"AWXPaymentElement","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPaymentElement","kind":"identifier"}],"title":"AWXPaymentElement","abstract":[{"text":"An embeddable payment element that can be added to any view hierarchy.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement","url":"\/documentation\/airwallex\/awxpaymentelement","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"value":"AWXPaymentResultDelegate","path":"\/metadata\/title","op":"replace"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"AWXPaymentResultDelegate"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AWXPaymentResultDelegate"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentResultDelegate\/paymentViewController(_:didCompleteWith:error:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentResultDelegate\/paymentViewController(_:didCompleteWithPaymentConsentId:)"],"anchor":"Instance-Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement"],"type":"conformingTypes","kind":"relationships","title":"Conforming Types"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPaymentResultDelegate","kind":"identifier"},{"text":" <","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"text":">","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentResultDelegate~1paymentViewController(_:didCompleteWith:error:)\/title","op":"replace","value":"paymentViewController:didCompleteWithStatus:error:"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentResultDelegate~1paymentViewController(_:didCompleteWith:error:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"paymentViewController:didCompleteWithStatus:error:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentResultDelegate~1paymentViewController(_:didCompleteWithPaymentConsentId:)\/title","op":"replace","value":"paymentViewController:didCompleteWithPaymentConsentId:"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentResultDelegate~1paymentViewController(_:didCompleteWithPaymentConsentId:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentViewController:didCompleteWithPaymentConsentId:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentResultDelegate\/title","op":"replace","value":"AWXPaymentResultDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentResultDelegate\/fragments","op":"replace","value":[{"text":"AWXPaymentResultDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentResultDelegate\/navigatorTitle","op":"replace","value":[{"text":"AWXPaymentResultDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/title","op":"replace","value":"AWXPaymentElement"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/fragments","op":"replace","value":[{"text":"AWXPaymentElement","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/navigatorTitle","op":"replace","value":[{"text":"AWXPaymentElement","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}