{"kind":"symbol","topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRequest\/requestId"],"anchor":"Instance-Properties","generated":true},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRequest\/headers()","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRequest\/method()","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRequest\/parameters()","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRequest\/path()","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRequest\/postData()","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRequest\/responseClass()"],"anchor":"Instance-Methods","generated":true}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"]},{"title":"Inherited By","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentRequest","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmThreeDSRequest","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCreatePaymentConsentRequest","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCreatePaymentMethodRequest","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDisablePaymentConsentRequest","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetAvailableBanksRequest","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaResRequest","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentConsentsRequest","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypeRequest","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypesRequest","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodsRequest","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRetrievePaymentConsentRequest","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRetrievePaymentIntentRequest","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXVerifyPaymentConsentRequest"],"type":"inheritedBy"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/SQ","doc:\/\/org.cocoapods.Airwallex\/SH"],"type":"conformsTo"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxrequest"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxrequest"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRequest"},"metadata":{"role":"symbol","symbolKind":"class","modules":[{"name":"Airwallex"}],"navigatorTitle":[{"kind":"identifier","text":"AWXRequest"}],"title":"AWXRequest","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXRequest","kind":"identifier"}],"roleHeading":"Class","externalID":"c:objc(cs)AWXRequest"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AWXRequest"}]}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.Airwallex/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRetrievePaymentConsentRequest":{"kind":"symbol","url":"\/documentation\/airwallex\/awxretrievepaymentconsentrequest","role":"symbol","type":"topic","navigatorTitle":[{"text":"AWXRetrievePaymentConsentRequest","kind":"identifier"}],"title":"AWXRetrievePaymentConsentRequest","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRetrievePaymentConsentRequest","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXRetrievePaymentConsentRequest","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"AWXRetrievePaymentConsentRequest"},{"type":"text","text":" includes the request of payment consent."}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentMethodTypeRequest":{"abstract":[{"type":"codeVoice","code":"AWXGetPaymentMethodTypeRequest"},{"type":"text","text":" includes all of the parameters needed to get payment method type."}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypeRequest","title":"AWXGetPaymentMethodTypeRequest","navigatorTitle":[{"kind":"identifier","text":"AWXGetPaymentMethodTypeRequest"}],"url":"\/documentation\/airwallex\/awxgetpaymentmethodtyperequest","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXGetPaymentMethodTypeRequest"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetAvailableBanksRequest":{"abstract":[{"code":"AWXGetPaymentMethodTypeRequest","type":"codeVoice"},{"text":" includes all of the parameters needed to get payment method type.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetAvailableBanksRequest","title":"AWXGetAvailableBanksRequest","navigatorTitle":[{"text":"AWXGetAvailableBanksRequest","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxgetavailablebanksrequest","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXGetAvailableBanksRequest","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRequest/headers()":{"kind":"symbol","url":"\/documentation\/airwallex\/awxrequest\/headers()","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"headers"}],"title":"headers()","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRequest\/headers()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"headers","kind":"identifier"},{"text":"() -> [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRetrievePaymentIntentRequest":{"kind":"symbol","url":"\/documentation\/airwallex\/awxretrievepaymentintentrequest","role":"symbol","type":"topic","navigatorTitle":[{"text":"AWXRetrievePaymentIntentRequest","kind":"identifier"}],"title":"AWXRetrievePaymentIntentRequest","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRetrievePaymentIntentRequest","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXRetrievePaymentIntentRequest","kind":"identifier"}],"abstract":[{"code":"AWXRetrievePaymentIntentRequest","type":"codeVoice"},{"type":"text","text":" includes all of the parameters needed to get payment intent."}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRequest/path()":{"kind":"symbol","url":"\/documentation\/airwallex\/awxrequest\/path()","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"path"}],"title":"path()","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRequest\/path()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"path"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"abstract":[],"kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","url":"\/documentation\/airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCreatePaymentConsentRequest":{"kind":"symbol","url":"\/documentation\/airwallex\/awxcreatepaymentconsentrequest","abstract":[{"code":"AWXCreatePaymentConsentRequest","type":"codeVoice"},{"text":" includes the request of creating payment consent.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXCreatePaymentConsentRequest"}],"navigatorTitle":[{"kind":"identifier","text":"AWXCreatePaymentConsentRequest"}],"title":"AWXCreatePaymentConsentRequest","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCreatePaymentConsentRequest"},"doc://org.cocoapods.Airwallex/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","title":"Swift.CVarArg"},"doc://org.cocoapods.Airwallex/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.Airwallex/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRequest/method()":{"abstract":[],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRequest\/method()","title":"method()","navigatorTitle":[{"kind":"identifier","text":"method"}],"url":"\/documentation\/airwallex\/awxrequest\/method()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"method","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@EA@AWXHTTPMethod","text":"AWXHTTPMethod"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRequest/postData()":{"kind":"symbol","url":"\/documentation\/airwallex\/awxrequest\/postdata()","role":"symbol","type":"topic","navigatorTitle":[{"text":"postData","kind":"identifier"}],"title":"postData()","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRequest\/postData()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"postData","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXDisablePaymentConsentRequest":{"abstract":[{"type":"codeVoice","code":"AWXDisablePaymentMethodRequest"},{"type":"text","text":" disable a payment method."}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDisablePaymentConsentRequest","title":"AWXDisablePaymentConsentRequest","navigatorTitle":[{"kind":"identifier","text":"AWXDisablePaymentConsentRequest"}],"url":"\/documentation\/airwallex\/awxdisablepaymentconsentrequest","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXDisablePaymentConsentRequest"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaResRequest":{"abstract":[{"type":"codeVoice","code":"AWXRetrievePaymentIntentRequest"},{"type":"text","text":" includes all of the parameters needed to get payment intent."}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaResRequest","title":"AWXGetPaResRequest","navigatorTitle":[{"kind":"identifier","text":"AWXGetPaResRequest"}],"url":"\/documentation\/airwallex\/awxgetparesrequest","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXGetPaResRequest"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRequest":{"kind":"symbol","url":"\/documentation\/airwallex\/awxrequest","abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXRequest"}],"navigatorTitle":[{"text":"AWXRequest","kind":"identifier"}],"title":"AWXRequest","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRequest"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXVerifyPaymentConsentRequest":{"url":"\/documentation\/airwallex\/awxverifypaymentconsentrequest","kind":"symbol","abstract":[{"type":"codeVoice","code":"AWXVerifyPaymentConsentRequest"},{"type":"text","text":" includes the request of verifying payment consent."}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AWXVerifyPaymentConsentRequest","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AWXVerifyPaymentConsentRequest"}],"title":"AWXVerifyPaymentConsentRequest","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXVerifyPaymentConsentRequest"},"doc://org.cocoapods.Airwallex/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"},"doc://org.cocoapods.Airwallex/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SQ"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRequest/responseClass()":{"kind":"symbol","url":"\/documentation\/airwallex\/awxrequest\/responseclass()","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"responseClass"}],"title":"responseClass()","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRequest\/responseClass()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"responseClass","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:s8AnyClassa","text":"AnyClass","kind":"typeIdentifier"}],"abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentMethodsRequest":{"kind":"symbol","url":"\/documentation\/airwallex\/awxgetpaymentmethodsrequest","role":"symbol","type":"topic","navigatorTitle":[{"text":"AWXGetPaymentMethodsRequest","kind":"identifier"}],"title":"AWXGetPaymentMethodsRequest","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodsRequest","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXGetPaymentMethodsRequest","kind":"identifier"}],"abstract":[{"code":"AWXGetPaymentMethodsRequest","type":"codeVoice"},{"type":"text","text":" includes all of the parameters needed to get payment methods."}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRequest/parameters()":{"abstract":[],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRequest\/parameters()","title":"parameters()","navigatorTitle":[{"kind":"identifier","text":"parameters"}],"url":"\/documentation\/airwallex\/awxrequest\/parameters()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"parameters","kind":"identifier"},{"text":"() -> [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXConfirmThreeDSRequest":{"url":"\/documentation\/airwallex\/awxconfirmthreedsrequest","abstract":[{"type":"codeVoice","code":"AWXConfirmThreeDSRequest"},{"text":" includes all of the parameters needed to confirm 3ds.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXConfirmThreeDSRequest","kind":"identifier"}],"navigatorTitle":[{"text":"AWXConfirmThreeDSRequest","kind":"identifier"}],"title":"AWXConfirmThreeDSRequest","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmThreeDSRequest"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRequest/requestId":{"abstract":[{"type":"text","text":"lazy initialized UUID"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRequest\/requestId","title":"requestId","navigatorTitle":[{"kind":"identifier","text":"requestId"}],"url":"\/documentation\/airwallex\/awxrequest\/requestid","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"requestId","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentMethodTypesRequest":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypesRequest","navigatorTitle":[{"kind":"identifier","text":"AWXGetPaymentMethodTypesRequest"}],"url":"\/documentation\/airwallex\/awxgetpaymentmethodtypesrequest","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AWXGetPaymentMethodTypesRequest"}],"role":"symbol","title":"AWXGetPaymentMethodTypesRequest","abstract":[{"code":"AWXGetPaymentMethodTypesRequest","type":"codeVoice"},{"type":"text","text":" includes all of the parameters needed to get payment method types."}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentConsentsRequest":{"kind":"symbol","abstract":[{"type":"codeVoice","code":"AWXGetPaymentConsentsRequest"},{"type":"text","text":" includes the request of payment consents."}],"url":"\/documentation\/airwallex\/awxgetpaymentconsentsrequest","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXGetPaymentConsentsRequest"}],"navigatorTitle":[{"kind":"identifier","text":"AWXGetPaymentConsentsRequest"}],"title":"AWXGetPaymentConsentsRequest","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentConsentsRequest"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXConfirmPaymentIntentRequest":{"abstract":[{"code":"AWXConfirmPaymentIntentRequest","type":"codeVoice"},{"type":"text","text":" includes all of the parameters needed to confirm payment intent."}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentRequest","title":"AWXConfirmPaymentIntentRequest","navigatorTitle":[{"text":"AWXConfirmPaymentIntentRequest","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxconfirmpaymentintentrequest","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXConfirmPaymentIntentRequest","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCreatePaymentMethodRequest":{"kind":"symbol","url":"\/documentation\/airwallex\/awxcreatepaymentmethodrequest","abstract":[{"code":"AWXCreatePaymentMethodRequest","type":"codeVoice"},{"type":"text","text":" includes all of the parameters needed to create a payment method."}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AWXCreatePaymentMethodRequest"}],"navigatorTitle":[{"kind":"identifier","text":"AWXCreatePaymentMethodRequest"}],"title":"AWXCreatePaymentMethodRequest","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCreatePaymentMethodRequest"},"doc://org.cocoapods.Airwallex/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"AWXRequest","op":"replace","path":"\/metadata\/title"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"AWXRequest"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"AWXRequest","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRequest\/requestId"],"anchor":"Instance-Properties","title":"Instance Properties"},{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRequest\/headers()","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRequest\/method()","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRequest\/parameters()","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRequest\/path()","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRequest\/postData()","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRequest\/responseClass()"]}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"]},{"kind":"relationships","type":"inheritedBy","title":"Inherited By","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentRequest","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmThreeDSRequest","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCreatePaymentConsentRequest","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCreatePaymentMethodRequest","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDisablePaymentConsentRequest","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetAvailableBanksRequest","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaResRequest","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentConsentsRequest","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypeRequest","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypesRequest","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodsRequest","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRetrievePaymentConsentRequest","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRetrievePaymentIntentRequest","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXVerifyPaymentConsentRequest"]}],"op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXRequest"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"AWXRetrievePaymentConsentRequest","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRetrievePaymentConsentRequest\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AWXRetrievePaymentConsentRequest"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRetrievePaymentConsentRequest\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRetrievePaymentConsentRequest\/navigatorTitle","value":[{"text":"AWXRetrievePaymentConsentRequest","kind":"identifier"}],"op":"replace"},{"value":"AWXGetPaymentMethodTypeRequest","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypeRequest\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypeRequest\/fragments","value":[{"text":"AWXGetPaymentMethodTypeRequest","kind":"identifier"}],"op":"replace"},{"value":[{"text":"AWXGetPaymentMethodTypeRequest","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypeRequest\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetAvailableBanksRequest\/title","value":"AWXGetAvailableBanksRequest","op":"replace"},{"value":[{"text":"AWXGetAvailableBanksRequest","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetAvailableBanksRequest\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AWXGetAvailableBanksRequest"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetAvailableBanksRequest\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRequest~1headers()\/title","value":"headers"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRequest~1headers()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"headers","kind":"identifier"}],"op":"replace"},{"value":"AWXRetrievePaymentIntentRequest","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRetrievePaymentIntentRequest\/title"},{"value":[{"text":"AWXRetrievePaymentIntentRequest","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRetrievePaymentIntentRequest\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRetrievePaymentIntentRequest\/navigatorTitle","value":[{"text":"AWXRetrievePaymentIntentRequest","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRequest~1path()\/title","value":"path"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRequest~1path()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"path"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCreatePaymentConsentRequest\/title","value":"AWXCreatePaymentConsentRequest"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCreatePaymentConsentRequest\/fragments","value":[{"kind":"identifier","text":"AWXCreatePaymentConsentRequest"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCreatePaymentConsentRequest\/navigatorTitle","value":[{"kind":"identifier","text":"AWXCreatePaymentConsentRequest"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRequest~1method()\/title","value":"method"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRequest~1method()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"method"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRequest~1postData()\/title","value":"postData"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRequest~1postData()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"postData"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDisablePaymentConsentRequest\/title","value":"AWXDisablePaymentConsentRequest"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDisablePaymentConsentRequest\/fragments","value":[{"kind":"identifier","text":"AWXDisablePaymentConsentRequest"}]},{"value":[{"kind":"identifier","text":"AWXDisablePaymentConsentRequest"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDisablePaymentConsentRequest\/navigatorTitle"},{"value":"AWXGetPaResRequest","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaResRequest\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaResRequest\/fragments","value":[{"text":"AWXGetPaResRequest","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaResRequest\/navigatorTitle","value":[{"text":"AWXGetPaResRequest","kind":"identifier"}],"op":"replace"},{"value":"AWXRequest","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRequest\/title"},{"value":[{"kind":"identifier","text":"AWXRequest"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRequest\/fragments"},{"value":[{"kind":"identifier","text":"AWXRequest"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRequest\/navigatorTitle"},{"value":"AWXVerifyPaymentConsentRequest","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXVerifyPaymentConsentRequest\/title"},{"value":[{"kind":"identifier","text":"AWXVerifyPaymentConsentRequest"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXVerifyPaymentConsentRequest\/fragments"},{"value":[{"kind":"identifier","text":"AWXVerifyPaymentConsentRequest"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXVerifyPaymentConsentRequest\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRequest~1responseClass()\/title","value":"responseClass"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRequest~1responseClass()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"responseClass"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodsRequest\/title","value":"AWXGetPaymentMethodsRequest"},{"value":[{"kind":"identifier","text":"AWXGetPaymentMethodsRequest"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodsRequest\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodsRequest\/navigatorTitle","value":[{"text":"AWXGetPaymentMethodsRequest","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRequest~1parameters()\/title","value":"parameters"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRequest~1parameters()\/fragments","value":[{"kind":"text","text":"- "},{"text":"parameters","kind":"identifier"}]},{"value":"AWXConfirmThreeDSRequest","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmThreeDSRequest\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmThreeDSRequest\/fragments","value":[{"kind":"identifier","text":"AWXConfirmThreeDSRequest"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmThreeDSRequest\/navigatorTitle","value":[{"kind":"identifier","text":"AWXConfirmThreeDSRequest"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRequest~1requestId\/title","value":"requestId"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRequest~1requestId\/fragments","value":[{"text":"requestId","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypesRequest\/title","value":"AWXGetPaymentMethodTypesRequest"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypesRequest\/fragments","value":[{"text":"AWXGetPaymentMethodTypesRequest","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypesRequest\/navigatorTitle","value":[{"kind":"identifier","text":"AWXGetPaymentMethodTypesRequest"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentConsentsRequest\/title","value":"AWXGetPaymentConsentsRequest"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentConsentsRequest\/fragments","value":[{"kind":"identifier","text":"AWXGetPaymentConsentsRequest"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentConsentsRequest\/navigatorTitle","value":[{"kind":"identifier","text":"AWXGetPaymentConsentsRequest"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentRequest\/title","value":"AWXConfirmPaymentIntentRequest"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentRequest\/fragments","value":[{"kind":"identifier","text":"AWXConfirmPaymentIntentRequest"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentRequest\/navigatorTitle","value":[{"kind":"identifier","text":"AWXConfirmPaymentIntentRequest"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCreatePaymentMethodRequest\/title","value":"AWXCreatePaymentMethodRequest"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCreatePaymentMethodRequest\/fragments","value":[{"kind":"identifier","text":"AWXCreatePaymentMethodRequest"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCreatePaymentMethodRequest\/navigatorTitle","value":[{"text":"AWXCreatePaymentMethodRequest","kind":"identifier"}]}]}]}