{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxrecurringsession"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxrecurringsession"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession"},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession\/merchantTriggerReason","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession\/nextTriggerByType"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession\/amount()","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession\/currency()","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession\/customerId()","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession\/requiresCVC()","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession\/setAmount(_:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession\/setCurrency(_:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession\/setCustomerId(_:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession\/setRequiresCVC(_:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"kind":"symbol","abstract":[{"code":"AWXRecurringSession","type":"codeVoice"},{"type":"text","text":" is the session used for recurring."}],"metadata":{"modules":[{"name":"Airwallex"}],"role":"symbol","externalID":"c:objc(cs)AWXRecurringSession","title":"AWXRecurringSession","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXRecurringSession"}],"navigatorTitle":[{"kind":"identifier","text":"AWXRecurringSession"}],"roleHeading":"Class","symbolKind":"class"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/SQ","doc:\/\/org.cocoapods.Airwallex\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXRecurringSession","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRecurringSession/setCustomerId(_:)":{"url":"\/documentation\/airwallex\/awxrecurringsession\/setcustomerid(_:)","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession\/setCustomerId(_:)","role":"symbol","kind":"symbol","title":"setCustomerId(_:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setCustomerId","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRecurringSession/setRequiresCVC(_:)":{"url":"\/documentation\/airwallex\/awxrecurringsession\/setrequirescvc(_:)","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession\/setRequiresCVC(_:)","role":"symbol","kind":"symbol","abstract":[],"title":"setRequiresCVC(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setRequiresCVC"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"type":"topic","deprecated":true},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRecurringSession/currency()":{"url":"\/documentation\/airwallex\/awxrecurringsession\/currency()","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession\/currency()","role":"symbol","kind":"symbol","title":"currency()","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"currency","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"abstract":[],"url":"\/documentation\/airwallex","role":"collection","title":"Airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","type":"topic","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRecurringSession":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXRecurringSession","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxrecurringsession","navigatorTitle":[{"text":"AWXRecurringSession","kind":"identifier"}],"kind":"symbol","type":"topic","title":"AWXRecurringSession","role":"symbol","abstract":[{"code":"AWXRecurringSession","type":"codeVoice"},{"type":"text","text":" is the session used for recurring."}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession"},"doc://org.cocoapods.Airwallex/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.Airwallex/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRecurringSession/currency":{"url":"\/documentation\/airwallex\/awxrecurringsession\/currency","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession\/currency","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Currency."}],"title":"currency","fragments":[{"kind":"identifier","text":"currency"}],"type":"topic"},"doc://org.cocoapods.Airwallex/SH":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRecurringSession/amount":{"url":"\/documentation\/airwallex\/awxrecurringsession\/amount","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession\/amount","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Payment amount. This is the order amount you would like to charge your customer."}],"title":"amount","fragments":[{"kind":"identifier","text":"amount"}],"type":"topic"},"doc://org.cocoapods.Airwallex/SQ":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRecurringSession/setCurrency(_:)":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession\/setCurrency(_:)","url":"\/documentation\/airwallex\/awxrecurringsession\/setcurrency(_:)","role":"symbol","title":"setCurrency(_:)","abstract":[],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setCurrency","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRecurringSession/customerId":{"url":"\/documentation\/airwallex\/awxrecurringsession\/customerid","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession\/customerId","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The customer who is paying for this payment intent."}],"title":"customerId","fragments":[{"kind":"identifier","text":"customerId"}],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRecurringSession/amount()":{"url":"\/documentation\/airwallex\/awxrecurringsession\/amount()","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession\/amount()","role":"symbol","kind":"symbol","abstract":[],"title":"amount()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"amount"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"NSDecimalNumber","preciseIdentifier":"c:objc(cs)NSDecimalNumber"}],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRecurringSession/setAmount(_:)":{"url":"\/documentation\/airwallex\/awxrecurringsession\/setamount(_:)","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession\/setAmount(_:)","role":"symbol","kind":"symbol","abstract":[],"title":"setAmount(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setAmount"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSDecimalNumber","preciseIdentifier":"c:objc(cs)NSDecimalNumber"},{"kind":"text","text":")"}],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRecurringSession/customerId()":{"url":"\/documentation\/airwallex\/awxrecurringsession\/customerid()","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession\/customerId()","role":"symbol","kind":"symbol","abstract":[],"title":"customerId()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"customerId"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"type":"topic"},"doc://org.cocoapods.Airwallex/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRecurringSession/merchantTriggerReason":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession\/merchantTriggerReason","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"merchantTriggerReason","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AirwallexMerchantTriggerReason","kind":"typeIdentifier","preciseIdentifier":"c:@E@AirwallexMerchantTriggerReason"}],"url":"\/documentation\/airwallex\/awxrecurringsession\/merchanttriggerreason","type":"topic","kind":"symbol","abstract":[{"text":"Merchant trigger reason","type":"text"}],"role":"symbol","title":"merchantTriggerReason","navigatorTitle":[{"text":"merchantTriggerReason","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRecurringSession/nextTriggerByType":{"url":"\/documentation\/airwallex\/awxrecurringsession\/nexttriggerbytype","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession\/nextTriggerByType","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Next trigger by."}],"title":"nextTriggerByType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextTriggerByType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AirwallexNextTriggerByType","preciseIdentifier":"c:@E@AirwallexNextTriggerByType"}],"navigatorTitle":[{"kind":"identifier","text":"nextTriggerByType"}],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSession":{"url":"\/documentation\/airwallex\/awxsession","abstract":[{"type":"codeVoice","code":"AWXSession"},{"type":"text","text":" is the base session."}],"navigatorTitle":[{"kind":"identifier","text":"AWXSession"}],"title":"AWXSession","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXSession"}]},"doc://org.cocoapods.Airwallex/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRecurringSession/requiresCVC()":{"deprecated":true,"title":"requiresCVC()","abstract":[],"type":"topic","url":"\/documentation\/airwallex\/awxrecurringsession\/requirescvc()","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession\/requiresCVC()","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiresCVC"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRecurringSession/requiresCVC":{"title":"requiresCVC","abstract":[{"type":"text","text":"Only applicable when next_triggered_by is customer and the payment_method.type is card. If true, the customer must provide cvc for the subsequent payment with this PaymentConsent."},{"type":"text","text":" "},{"type":"text","text":"Default: NO"}],"type":"topic","url":"\/documentation\/airwallex\/awxrecurringsession\/requirescvc","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession\/requiresCVC","kind":"symbol","fragments":[{"kind":"identifier","text":"requiresCVC"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"AWXRecurringSession"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"AWXRecurringSession"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"AWXRecurringSession","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession\/amount","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession\/currency","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession\/customerId","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession\/merchantTriggerReason","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession\/nextTriggerByType","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession\/requiresCVC"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXRecurringSession","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"AWXSession","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession","preciseIdentifier":"c:objc(cs)AWXSession"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRecurringSession\/title","op":"replace","value":"AWXRecurringSession"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRecurringSession\/fragments","op":"replace","value":[{"kind":"identifier","text":"AWXRecurringSession"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRecurringSession\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AWXRecurringSession"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRecurringSession~1merchantTriggerReason\/title","op":"replace","value":"merchantTriggerReason"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRecurringSession~1merchantTriggerReason\/fragments","op":"replace","value":[{"text":"merchantTriggerReason","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRecurringSession~1nextTriggerByType\/title","op":"replace","value":"nextTriggerByType"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRecurringSession~1nextTriggerByType\/fragments","op":"replace","value":[{"kind":"identifier","text":"nextTriggerByType"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/title","op":"replace","value":"AWXSession"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/fragments","op":"replace","value":[{"kind":"identifier","text":"AWXSession"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AWXSession"}]}]}]}