{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxresponse"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxresponse"]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","title":"AWXResponse","navigatorTitle":[{"text":"AWXResponse","kind":"identifier"}],"externalID":"c:objc(cs)AWXResponse","roleHeading":"Class","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXResponse","kind":"identifier"}],"modules":[{"name":"Airwallex"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXResponse"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXResponse"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"]},{"type":"inheritedBy","title":"Inherited By","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAPIErrorResponse","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentResponse","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCreatePaymentConsentResponse","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCreatePaymentMethodResponse","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDisablePaymentConsentResponse","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetAvailableBanksResponse","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaResResponse","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentConsentsResponse","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentIntentResponse","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypeResponse","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypesResponse","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodsResponse","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXVerifyPaymentConsentResponse"]},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/SQ","doc:\/\/org.cocoapods.Airwallex\/SH"]}],"topicSections":[{"title":"Type Methods","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXResponse\/parse(_:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXResponse\/parseError(_:)"],"generated":true,"anchor":"Type-Methods"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"references":{"doc://org.cocoapods.Airwallex/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentMethodTypeResponse":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypeResponse","type":"topic","title":"AWXGetPaymentMethodTypeResponse","url":"\/documentation\/airwallex\/awxgetpaymentmethodtyperesponse","abstract":[{"type":"codeVoice","code":"AWXGetPaymentMethodTypeResponse"},{"type":"text","text":" includes the list of payment methods."}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXGetPaymentMethodTypeResponse"}],"navigatorTitle":[{"kind":"identifier","text":"AWXGetPaymentMethodTypeResponse"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXResponse":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXResponse","url":"\/documentation\/airwallex\/awxresponse","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"AWXResponse"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXResponse"}],"title":"AWXResponse","kind":"symbol","type":"topic","role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","role":"collection","title":"Airwallex","url":"\/documentation\/airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentMethodsResponse":{"title":"AWXGetPaymentMethodsResponse","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXGetPaymentMethodsResponse"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodsResponse","navigatorTitle":[{"text":"AWXGetPaymentMethodsResponse","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxgetpaymentmethodsresponse","abstract":[{"code":"AWXGetPaymentMethodsResponse","type":"codeVoice"},{"text":" includes the list of payment methods.","type":"text"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaResResponse":{"kind":"symbol","type":"topic","title":"AWXGetPaResResponse","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaResResponse","abstract":[{"type":"codeVoice","code":"AWXGetPaResResponse"},{"type":"text","text":" includes the 3ds information of payment."}],"url":"\/documentation\/airwallex\/awxgetparesresponse","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXGetPaResResponse"}],"navigatorTitle":[{"kind":"identifier","text":"AWXGetPaResResponse"}],"role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXVerifyPaymentConsentResponse":{"abstract":[{"code":"AWXVerifyPaymentConsentResponse","type":"codeVoice"},{"text":" includes the response of payment consent.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXVerifyPaymentConsentResponse"}],"navigatorTitle":[{"text":"AWXVerifyPaymentConsentResponse","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXVerifyPaymentConsentResponse","type":"topic","kind":"symbol","title":"AWXVerifyPaymentConsentResponse","url":"\/documentation\/airwallex\/awxverifypaymentconsentresponse"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXConfirmPaymentIntentResponse":{"role":"symbol","abstract":[{"type":"codeVoice","code":"AWXConfirmPaymentIntentResponse"},{"text":" includes the result of payment flow.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXConfirmPaymentIntentResponse"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"AWXConfirmPaymentIntentResponse"}],"kind":"symbol","title":"AWXConfirmPaymentIntentResponse","url":"\/documentation\/airwallex\/awxconfirmpaymentintentresponse","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentResponse"},"doc://org.cocoapods.Airwallex/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SQ","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentMethodTypesResponse":{"title":"AWXGetPaymentMethodTypesResponse","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypesResponse","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXGetPaymentMethodTypesResponse","kind":"identifier"}],"abstract":[{"code":"AWXGetPaymentMethodTypesResponse","type":"codeVoice"},{"text":" includes the list of payment methods.","type":"text"}],"url":"\/documentation\/airwallex\/awxgetpaymentmethodtypesresponse","type":"topic","navigatorTitle":[{"text":"AWXGetPaymentMethodTypesResponse","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXDisablePaymentConsentResponse":{"title":"AWXDisablePaymentConsentResponse","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDisablePaymentConsentResponse","navigatorTitle":[{"text":"AWXDisablePaymentConsentResponse","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXDisablePaymentConsentResponse","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"AWXDisablePaymentMethodResponse"},{"text":" includes the payment method disabled.","type":"text"}],"url":"\/documentation\/airwallex\/awxdisablepaymentconsentresponse"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCreatePaymentConsentResponse":{"url":"\/documentation\/airwallex\/awxcreatepaymentconsentresponse","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCreatePaymentConsentResponse","abstract":[{"code":"AWXCreatePaymentConsentResponse","type":"codeVoice"},{"text":" includes the response of payment consent.","type":"text"}],"title":"AWXCreatePaymentConsentResponse","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXCreatePaymentConsentResponse"}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWXCreatePaymentConsentResponse"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentConsentsResponse":{"abstract":[],"url":"\/documentation\/airwallex\/awxgetpaymentconsentsresponse","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXGetPaymentConsentsResponse"}],"role":"symbol","title":"AWXGetPaymentConsentsResponse","navigatorTitle":[{"text":"AWXGetPaymentConsentsResponse","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentConsentsResponse","type":"topic","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXAPIErrorResponse":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAPIErrorResponse","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWXAPIErrorResponse"}],"title":"AWXAPIErrorResponse","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXAPIErrorResponse"}],"type":"topic","abstract":[{"text":"An ","type":"text"},{"code":"AWXAPIErrorResponse","type":"codeVoice"},{"text":" includes error details.","type":"text"}],"url":"\/documentation\/airwallex\/awxapierrorresponse","role":"symbol"},"doc://org.cocoapods.Airwallex/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetAvailableBanksResponse":{"role":"symbol","navigatorTitle":[{"text":"AWXGetAvailableBanksResponse","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXGetAvailableBanksResponse","kind":"identifier"}],"title":"AWXGetAvailableBanksResponse","abstract":[{"type":"codeVoice","code":"AWXGetAvailableBanksResponse"},{"type":"text","text":" includes the list of banks."}],"type":"topic","url":"\/documentation\/airwallex\/awxgetavailablebanksresponse","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetAvailableBanksResponse","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXResponse/parse(_:)":{"kind":"symbol","abstract":[],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"parse","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AWXResponse","text":"AWXResponse","kind":"typeIdentifier"}],"title":"parse(_:)","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXResponse\/parse(_:)","navigatorTitle":[{"text":"parse:","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxresponse\/parse(_:)","role":"symbol"},"doc://org.cocoapods.Airwallex/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentIntentResponse":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXGetPaymentIntentResponse","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxgetpaymentintentresponse","abstract":[{"type":"codeVoice","code":"AWXGetPaymentIntentResponse"},{"text":" includes the information of payment intent.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentIntentResponse","title":"AWXGetPaymentIntentResponse","role":"symbol","navigatorTitle":[{"text":"AWXGetPaymentIntentResponse","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXResponse/parseError(_:)":{"role":"symbol","abstract":[],"kind":"symbol","title":"parseError(_:)","url":"\/documentation\/airwallex\/awxresponse\/parseerror(_:)","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXResponse\/parseError(_:)","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"parseError","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AWXResponse","text":"AWXResponse","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"parseError:","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP"},"doc://org.cocoapods.Airwallex/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SH"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCreatePaymentMethodResponse":{"url":"\/documentation\/airwallex\/awxcreatepaymentmethodresponse","abstract":[{"type":"codeVoice","code":"AWXCreatePaymentMethodResponse"},{"type":"text","text":" includes the payment method created."}],"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXCreatePaymentMethodResponse","kind":"identifier"}],"title":"AWXCreatePaymentMethodResponse","role":"symbol","navigatorTitle":[{"text":"AWXCreatePaymentMethodResponse","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCreatePaymentMethodResponse"},"doc://org.cocoapods.Airwallex/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"AWXResponse","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"AWXResponse","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"AWXResponse","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"title":"Type Methods","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXResponse\/parse(_:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXResponse\/parseError(_:)"],"anchor":"Type-Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"]},{"kind":"relationships","title":"Inherited By","type":"inheritedBy","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAPIErrorResponse","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentResponse","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCreatePaymentConsentResponse","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCreatePaymentMethodResponse","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDisablePaymentConsentResponse","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetAvailableBanksResponse","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaResResponse","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentConsentsResponse","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentIntentResponse","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypeResponse","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypesResponse","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodsResponse","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXVerifyPaymentConsentResponse"]}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXResponse","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"AWXGetPaymentMethodTypeResponse","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypeResponse\/title"},{"value":[{"text":"AWXGetPaymentMethodTypeResponse","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypeResponse\/fragments"},{"value":[{"text":"AWXGetPaymentMethodTypeResponse","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypeResponse\/navigatorTitle"},{"value":"AWXResponse","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXResponse\/title"},{"value":[{"kind":"identifier","text":"AWXResponse"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXResponse\/fragments"},{"value":[{"kind":"identifier","text":"AWXResponse"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXResponse\/navigatorTitle"},{"value":"AWXGetPaymentMethodsResponse","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodsResponse\/title"},{"value":[{"kind":"identifier","text":"AWXGetPaymentMethodsResponse"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodsResponse\/fragments"},{"value":[{"kind":"identifier","text":"AWXGetPaymentMethodsResponse"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodsResponse\/navigatorTitle"},{"value":"AWXGetPaResResponse","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaResResponse\/title"},{"value":[{"kind":"identifier","text":"AWXGetPaResResponse"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaResResponse\/fragments"},{"value":[{"kind":"identifier","text":"AWXGetPaResResponse"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaResResponse\/navigatorTitle"},{"value":"AWXVerifyPaymentConsentResponse","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXVerifyPaymentConsentResponse\/title"},{"value":[{"text":"AWXVerifyPaymentConsentResponse","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXVerifyPaymentConsentResponse\/fragments"},{"value":[{"text":"AWXVerifyPaymentConsentResponse","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXVerifyPaymentConsentResponse\/navigatorTitle"},{"value":"AWXConfirmPaymentIntentResponse","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentResponse\/title"},{"value":[{"text":"AWXConfirmPaymentIntentResponse","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentResponse\/fragments"},{"value":[{"kind":"identifier","text":"AWXConfirmPaymentIntentResponse"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentResponse\/navigatorTitle"},{"value":"AWXGetPaymentMethodTypesResponse","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypesResponse\/title"},{"value":[{"kind":"identifier","text":"AWXGetPaymentMethodTypesResponse"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypesResponse\/fragments"},{"value":[{"kind":"identifier","text":"AWXGetPaymentMethodTypesResponse"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypesResponse\/navigatorTitle"},{"value":"AWXDisablePaymentConsentResponse","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDisablePaymentConsentResponse\/title"},{"value":[{"text":"AWXDisablePaymentConsentResponse","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDisablePaymentConsentResponse\/fragments"},{"value":[{"kind":"identifier","text":"AWXDisablePaymentConsentResponse"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDisablePaymentConsentResponse\/navigatorTitle"},{"value":"AWXCreatePaymentConsentResponse","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCreatePaymentConsentResponse\/title"},{"value":[{"kind":"identifier","text":"AWXCreatePaymentConsentResponse"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCreatePaymentConsentResponse\/fragments"},{"value":[{"kind":"identifier","text":"AWXCreatePaymentConsentResponse"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCreatePaymentConsentResponse\/navigatorTitle"},{"value":"AWXGetPaymentConsentsResponse","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentConsentsResponse\/title"},{"value":[{"text":"AWXGetPaymentConsentsResponse","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentConsentsResponse\/fragments"},{"value":[{"text":"AWXGetPaymentConsentsResponse","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentConsentsResponse\/navigatorTitle"},{"value":"AWXAPIErrorResponse","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIErrorResponse\/title"},{"value":[{"kind":"identifier","text":"AWXAPIErrorResponse"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIErrorResponse\/fragments"},{"value":[{"text":"AWXAPIErrorResponse","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIErrorResponse\/navigatorTitle"},{"value":"AWXGetAvailableBanksResponse","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetAvailableBanksResponse\/title"},{"value":[{"kind":"identifier","text":"AWXGetAvailableBanksResponse"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetAvailableBanksResponse\/fragments"},{"value":[{"text":"AWXGetAvailableBanksResponse","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetAvailableBanksResponse\/navigatorTitle"},{"value":"parse:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXResponse~1parse(_:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"parse:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXResponse~1parse(_:)\/fragments"},{"value":"AWXGetPaymentIntentResponse","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentIntentResponse\/title"},{"value":[{"kind":"identifier","text":"AWXGetPaymentIntentResponse"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentIntentResponse\/fragments"},{"value":[{"kind":"identifier","text":"AWXGetPaymentIntentResponse"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentIntentResponse\/navigatorTitle"},{"value":"parseError:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXResponse~1parseError(_:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"parseError:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXResponse~1parseError(_:)\/fragments"},{"value":"AWXCreatePaymentMethodResponse","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCreatePaymentMethodResponse\/title"},{"value":[{"kind":"identifier","text":"AWXCreatePaymentMethodResponse"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCreatePaymentMethodResponse\/fragments"},{"value":[{"text":"AWXCreatePaymentMethodResponse","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCreatePaymentMethodResponse\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}