{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"metadata":{"roleHeading":"Class","modules":[{"name":"Airwallex"}],"title":"AWXShippingViewController","platforms":[{"unavailable":false,"beta":false,"deprecated":true}],"symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXShippingViewController","kind":"identifier"}],"role":"symbol","externalID":"c:objc(cs)AWXShippingViewController","navigatorTitle":[{"text":"AWXShippingViewController","kind":"identifier"}]},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXShippingViewController","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"codeVoice","code":"AWXShippingViewController"},{"text":" provides a form to edit shipping address.","type":"text"}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXViewController"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSCoding","doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSExtensionRequestHandling","doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/SQ","doc:\/\/org.cocoapods.Airwallex\/SH","doc:\/\/org.cocoapods.Airwallex\/s8SendableP","doc:\/\/org.cocoapods.Airwallex\/s16SendableMetatypeP","doc:\/\/org.cocoapods.Airwallex\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.Airwallex\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.Airwallex\/objc(pl)UIContentContainer","doc:\/\/org.cocoapods.Airwallex\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.Airwallex\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.Airwallex\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.Airwallex\/objc(pl)UIStateRestoring","doc:\/\/org.cocoapods.Airwallex\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.Airwallex\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.Airwallex\/objc(pl)UIUserActivityRestoring"],"title":"Conforms To","type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXShippingViewController","kind":"identifier"}],"platforms":["iOS"]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxshippingviewcontroller"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxshippingviewcontroller"]}],"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXShippingViewController\/delegate","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXShippingViewController\/shipping"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXViewController":{"role":"symbol","kind":"symbol","title":"AWXViewController","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXViewController","abstract":[{"type":"codeVoice","code":"AWXViewController"},{"text":" is the base view controller.","type":"text"}],"url":"\/documentation\/airwallex\/awxviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXViewController"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"AWXViewController"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXShippingViewController/shipping":{"deprecated":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shipping","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AWXPlaceDetails","text":"AWXPlaceDetails","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"text":"Saved shippping.","type":"text"}],"navigatorTitle":[{"text":"shipping","kind":"identifier"}],"title":"shipping","role":"symbol","url":"\/documentation\/airwallex\/awxshippingviewcontroller\/shipping","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXShippingViewController\/shipping","kind":"symbol","type":"topic"},"doc://org.cocoapods.Airwallex/objc(pl)NSExtensionRequestHandling":{"title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSExtensionRequestHandling","type":"unresolvable"},"doc://org.cocoapods.Airwallex/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)UIFocusEnvironment"},"doc://org.cocoapods.Airwallex/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)UIAppearanceContainer","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXShippingViewController/delegate":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)AWXShippingViewControllerDelegate","text":"AWXShippingViewControllerDelegate","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"url":"\/documentation\/airwallex\/awxshippingviewcontroller\/delegate","type":"topic","abstract":[{"text":"A delegate which handles saved shipping.","type":"text"}],"title":"delegate","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXShippingViewController\/delegate","role":"symbol","deprecated":true,"navigatorTitle":[{"text":"delegate","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/s16SendableMetatypeP":{"title":"Swift.SendableMetatype","identifier":"doc:\/\/org.cocoapods.Airwallex\/s16SendableMetatypeP","type":"unresolvable"},"doc://org.cocoapods.Airwallex/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP"},"doc://org.cocoapods.Airwallex/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SQ","type":"unresolvable"},"doc://org.cocoapods.Airwallex/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject"},"doc://org.cocoapods.Airwallex/objc(pl)UIPasteConfigurationSupporting":{"title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"title":"Airwallex","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/airwallex","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"},"doc://org.cocoapods.Airwallex/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/org.cocoapods.Airwallex\/5UIKit23UITraitChangeObservableP"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXShippingViewController":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXShippingViewController","kind":"identifier"}],"navigatorTitle":[{"text":"AWXShippingViewController","kind":"identifier"}],"deprecated":true,"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXShippingViewController","abstract":[{"code":"AWXShippingViewController","type":"codeVoice"},{"text":" provides a form to edit shipping address.","type":"text"}],"url":"\/documentation\/airwallex\/awxshippingviewcontroller","type":"topic","role":"symbol","title":"AWXShippingViewController","kind":"symbol"},"doc://org.cocoapods.Airwallex/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.Airwallex/objc(pl)UIUserActivityRestoring":{"title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)UIUserActivityRestoring","type":"unresolvable"},"doc://org.cocoapods.Airwallex/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.Airwallex/s8SendableP":{"title":"Swift.Sendable","identifier":"doc:\/\/org.cocoapods.Airwallex\/s8SendableP","type":"unresolvable"},"doc://org.cocoapods.Airwallex/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)UIStateRestoring"},"doc://org.cocoapods.Airwallex/objc(pl)UIContentContainer":{"title":"UIKit.UIContentContainer","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)UIContentContainer","type":"unresolvable"},"doc://org.cocoapods.Airwallex/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SH"},"doc://org.cocoapods.Airwallex/objc(pl)NSCoding":{"title":"Foundation.NSCoding","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSCoding","type":"unresolvable"},"doc://org.cocoapods.Airwallex/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP"},"doc://org.cocoapods.Airwallex/objc(pl)UITraitEnvironment":{"title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)UITraitEnvironment","type":"unresolvable"},"doc://org.cocoapods.Airwallex/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)UIResponderStandardEditActions"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[{"deprecated":true,"beta":false,"unavailable":false}],"op":"replace","path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"AWXShippingViewController","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"AWXShippingViewController","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"AWXShippingViewController","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXShippingViewController\/delegate","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXShippingViewController\/shipping"],"generated":true,"title":"Instance Properties"}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXViewController"],"type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXShippingViewController","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"AWXViewController","preciseIdentifier":"c:objc(cs)AWXViewController","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXViewController"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXViewController\/title","value":"AWXViewController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXViewController\/fragments","value":[{"text":"AWXViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXViewController\/navigatorTitle","value":[{"text":"AWXViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXShippingViewController~1shipping\/title","value":"shipping"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXShippingViewController~1shipping\/fragments","value":[{"text":"shipping","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXShippingViewController~1delegate\/title","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXShippingViewController~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXShippingViewController\/title","value":"AWXShippingViewController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXShippingViewController\/fragments","value":[{"text":"AWXShippingViewController","kind":"identifier"}]},{"value":[{"text":"AWXShippingViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXShippingViewController\/navigatorTitle"}]}]}