{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXSchema","kind":"identifier"}],"languages":["swift"]}]}],"abstract":[{"type":"codeVoice","code":"AWXSchema"},{"type":"text","text":" includes the schema of payment method."}],"topicSections":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSchema\/fields","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSchema\/flow","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSchema\/transactionMode"],"generated":true,"title":"Instance Properties"}],"metadata":{"externalID":"c:objc(cs)AWXSchema","role":"symbol","modules":[{"name":"Airwallex"}],"symbolKind":"class","title":"AWXSchema","navigatorTitle":[{"text":"AWXSchema","kind":"identifier"}],"roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXSchema","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"},{"type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONDecodable","doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/SQ","doc:\/\/org.cocoapods.Airwallex\/SH"],"kind":"relationships","title":"Conforms To"}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSchema","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxschema"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxschema"]}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSchema":{"abstract":[{"type":"codeVoice","code":"AWXSchema"},{"type":"text","text":" includes the schema of payment method."}],"kind":"symbol","title":"AWXSchema","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSchema","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXSchema","kind":"identifier"}],"navigatorTitle":[{"text":"AWXSchema","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxschema"},"doc://org.cocoapods.Airwallex/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSchema/transactionMode":{"abstract":[{"text":"transaction_mode of the payment method. One of oneoff, recurring.","type":"text"}],"kind":"symbol","title":"transactionMode","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSchema\/transactionMode","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transactionMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"transactionMode","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxschema\/transactionmode"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","url":"\/documentation\/airwallex","title":"Airwallex","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSchema/flow":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Flow."}],"role":"symbol","url":"\/documentation\/airwallex\/awxschema\/flow","title":"flow","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSchema\/flow","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"flow","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"flow","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.Airwallex/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.Airwallex/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","title":"Swift.CVarArg"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSchema/fields":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Fields."}],"role":"symbol","url":"\/documentation\/airwallex\/awxschema\/fields","title":"fields","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSchema\/fields","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fields","kind":"identifier"},{"text":": [","kind":"text"},{"text":"AWXField","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXField"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"fields","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.Airwallex/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXJSONDecodable":{"abstract":[],"kind":"symbol","title":"AWXJSONDecodable","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONDecodable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXJSONDecodable"}],"navigatorTitle":[{"kind":"identifier","text":"AWXJSONDecodable"}],"url":"\/documentation\/airwallex\/awxjsondecodable"},"doc://org.cocoapods.Airwallex/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject","title":"NSObject"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"AWXSchema"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"AWXSchema","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"AWXSchema","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSchema\/fields","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSchema\/flow","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSchema\/transactionMode"],"title":"Instance Properties","generated":true}]},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONDecodable"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXSchema","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSchema\/title","op":"replace","value":"AWXSchema"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSchema\/fragments","op":"replace","value":[{"text":"AWXSchema","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSchema\/navigatorTitle","op":"replace","value":[{"text":"AWXSchema","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSchema~1transactionMode\/title","op":"replace","value":"transactionMode"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSchema~1transactionMode\/fragments","op":"replace","value":[{"text":"transactionMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSchema~1flow\/title","op":"replace","value":"flow"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSchema~1flow\/fragments","op":"replace","value":[{"text":"flow","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSchema~1fields\/title","op":"replace","value":"fields"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSchema~1fields\/fragments","op":"replace","value":[{"text":"fields","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONDecodable\/title","op":"replace","value":"AWXJSONDecodable"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONDecodable\/fragments","op":"replace","value":[{"text":"AWXJSONDecodable","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONDecodable\/navigatorTitle","op":"replace","value":[{"text":"AWXJSONDecodable","kind":"identifier"}]}]}]}