{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXShippingViewControllerDelegate","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"metadata":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXShippingViewControllerDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AWXShippingViewControllerDelegate"}],"roleHeading":"Protocol","externalID":"c:@M@Airwallex@objc(pl)AWXShippingViewControllerDelegate","title":"AWXShippingViewControllerDelegate","symbolKind":"protocol","modules":[{"name":"Airwallex"}],"role":"symbol"},"topicSections":[{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXShippingViewControllerDelegate\/shippingViewController(_:didEditShipping:)"],"generated":true}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXShippingViewControllerDelegate","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxshippingviewcontrollerdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxshippingviewcontrollerdelegate"]}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXShippingViewControllerDelegate/shippingViewController(_:didEditShipping:)":{"navigatorTitle":[{"text":"shippingViewController:didEditShipping:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXShippingViewControllerDelegate\/shippingViewController(_:didEditShipping:)","required":true,"abstract":[],"title":"shippingViewController(_:didEditShipping:)","type":"topic","url":"\/documentation\/airwallex\/awxshippingviewcontrollerdelegate\/shippingviewcontroller(_:dideditshipping:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shippingViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AWXShippingViewController","preciseIdentifier":"c:@M@Airwallex@objc(cs)AWXShippingViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didEditShipping","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AWXPlaceDetails","preciseIdentifier":"c:objc(cs)AWXPlaceDetails","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXShippingViewControllerDelegate":{"url":"\/documentation\/airwallex\/awxshippingviewcontrollerdelegate","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AWXShippingViewControllerDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXShippingViewControllerDelegate"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXShippingViewControllerDelegate","kind":"symbol","title":"AWXShippingViewControllerDelegate","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","type":"topic","role":"collection","title":"Airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"AWXShippingViewControllerDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"AWXShippingViewControllerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"AWXShippingViewControllerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXShippingViewControllerDelegate\/shippingViewController(_:didEditShipping:)"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXShippingViewControllerDelegate","kind":"identifier"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXShippingViewControllerDelegate~1shippingViewController(_:didEditShipping:)\/title","value":"shippingViewController:didEditShipping:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXShippingViewControllerDelegate~1shippingViewController(_:didEditShipping:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"shippingViewController:didEditShipping:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXShippingViewControllerDelegate\/title","value":"AWXShippingViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXShippingViewControllerDelegate\/fragments","value":[{"text":"AWXShippingViewControllerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXShippingViewControllerDelegate\/navigatorTitle","value":[{"text":"AWXShippingViewControllerDelegate","kind":"identifier"}]}]}]}