{"kind":"symbol","sections":[],"topicSections":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/CVC","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/cardNumber","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/city","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/country","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/default","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/email","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/expires","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/firstName","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/lastName","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/nameOnCard","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/phoneNumber","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/state","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/street","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/zipcode"],"anchor":"Enumeration-Cases","title":"Enumeration Cases"},{"generated":true,"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/init(rawValue:)"],"anchor":"Initializers","title":"Initializers"},{"generated":true,"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/Equatable-Implementations","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/RawRepresentable-Implementations"],"anchor":"Default-Implementations","title":"Default Implementations"}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@E@AWXTextFieldType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXTextFieldType","kind":"identifier"}],"symbolKind":"enum","role":"symbol","roleHeading":"Enumeration","title":"AWXTextFieldType","modules":[{"name":"Airwallex"}],"navigatorTitle":[{"text":"AWXTextFieldType","kind":"identifier"}]},"relationshipsSections":[{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.Airwallex\/s15BitwiseCopyableP","doc:\/\/org.cocoapods.Airwallex\/SQ","doc:\/\/org.cocoapods.Airwallex\/SH","doc:\/\/org.cocoapods.Airwallex\/SY","doc:\/\/org.cocoapods.Airwallex\/s8SendableP"],"type":"conformsTo"}],"variants":[{"paths":["\/documentation\/airwallex\/awxtextfieldtype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxtextfieldtype"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXTextFieldType","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","role":"collection","title":"Airwallex","url":"\/documentation\/airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXTextFieldType/expires":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/expires","title":"AWXTextFieldType.expires","kind":"symbol","navigatorTitle":[{"text":"AWXTextFieldTypeExpires","kind":"identifier"}],"role":"symbol","abstract":[],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"expires","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxtextfieldtype\/expires"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXTextFieldType/init(rawValue:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/init(rawValue:)","title":"init(rawValue:)","type":"topic","abstract":[],"role":"symbol","url":"\/documentation\/airwallex\/awxtextfieldtype\/init(rawvalue:)"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXTextFieldType/phoneNumber":{"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/phoneNumber","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"AWXTextFieldTypePhoneNumber"}],"url":"\/documentation\/airwallex\/awxtextfieldtype\/phonenumber","role":"symbol","title":"AWXTextFieldType.phoneNumber","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"phoneNumber"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXTextFieldType/default":{"url":"\/documentation\/airwallex\/awxtextfieldtype\/default","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/default","title":"AWXTextFieldType.default","type":"topic","abstract":[],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"`default`","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"AWXTextFieldTypeDefault","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXTextFieldType/CVC":{"url":"\/documentation\/airwallex\/awxtextfieldtype\/cvc","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AWXTextFieldTypeCVC"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"CVC"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/CVC","role":"symbol","title":"AWXTextFieldType.CVC","abstract":[],"kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXTextFieldType/firstName":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWXTextFieldTypeFirstName"}],"url":"\/documentation\/airwallex\/awxtextfieldtype\/firstname","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/firstName","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"firstName"}],"type":"topic","title":"AWXTextFieldType.firstName"},"doc://org.cocoapods.Airwallex/s15BitwiseCopyableP":{"title":"Swift.BitwiseCopyable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/s15BitwiseCopyableP"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXTextFieldType/Equatable-Implementations":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/Equatable-Implementations","kind":"article","url":"\/documentation\/airwallex\/awxtextfieldtype\/equatable-implementations","type":"topic","title":"Equatable Implementations","role":"collectionGroup","abstract":[]},"doc://org.cocoapods.Airwallex/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/s8SendableP"},"doc://org.cocoapods.Airwallex/SQ":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXTextFieldType/city":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/city","title":"AWXTextFieldType.city","navigatorTitle":[{"text":"AWXTextFieldTypeCity","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxtextfieldtype\/city","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"city"}],"role":"symbol"},"doc://org.cocoapods.Airwallex/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SH"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXTextFieldType":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXTextFieldType","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"AWXTextFieldType","kind":"identifier"}],"abstract":[],"type":"topic","url":"\/documentation\/airwallex\/awxtextfieldtype","title":"AWXTextFieldType","role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXTextFieldType/state":{"title":"AWXTextFieldType.state","kind":"symbol","url":"\/documentation\/airwallex\/awxtextfieldtype\/state","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/state","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"state","kind":"identifier"}],"navigatorTitle":[{"text":"AWXTextFieldTypeState","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXTextFieldType/zipcode":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AWXTextFieldTypeZipcode"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/zipcode","kind":"symbol","title":"AWXTextFieldType.zipcode","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"zipcode"}],"url":"\/documentation\/airwallex\/awxtextfieldtype\/zipcode"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXTextFieldType/cardNumber":{"url":"\/documentation\/airwallex\/awxtextfieldtype\/cardnumber","kind":"symbol","title":"AWXTextFieldType.cardNumber","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"AWXTextFieldTypeCardNumber"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cardNumber","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/cardNumber","type":"topic","role":"symbol"},"doc://org.cocoapods.Airwallex/SY":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXTextFieldType/nameOnCard":{"type":"topic","navigatorTitle":[{"text":"AWXTextFieldTypeNameOnCard","kind":"identifier"}],"kind":"symbol","title":"AWXTextFieldType.nameOnCard","abstract":[],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/nameOnCard","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nameOnCard","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxtextfieldtype\/nameoncard"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXTextFieldType/RawRepresentable-Implementations":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/RawRepresentable-Implementations","kind":"article","url":"\/documentation\/airwallex\/awxtextfieldtype\/rawrepresentable-implementations","type":"topic","title":"RawRepresentable Implementations","role":"collectionGroup","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXTextFieldType/street":{"url":"\/documentation\/airwallex\/awxtextfieldtype\/street","title":"AWXTextFieldType.street","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"AWXTextFieldTypeStreet","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"street","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/street","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXTextFieldType/country":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/country","title":"AWXTextFieldType.country","role":"symbol","type":"topic","navigatorTitle":[{"text":"AWXTextFieldTypeCountry","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxtextfieldtype\/country","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"country"}],"kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXTextFieldType/lastName":{"navigatorTitle":[{"kind":"identifier","text":"AWXTextFieldTypeLastName"}],"title":"AWXTextFieldType.lastName","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/lastName","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/airwallex\/awxtextfieldtype\/lastname","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"lastName"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXTextFieldType/email":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/email","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"email"}],"type":"topic","title":"AWXTextFieldType.email","url":"\/documentation\/airwallex\/awxtextfieldtype\/email","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"AWXTextFieldTypeEmail"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","value":"AWXTextFieldType","path":"\/metadata\/title"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"AWXTextFieldType","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"AWXTextFieldType","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"anchor":"Enumeration-Cases","generated":true,"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/CVC","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/cardNumber","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/city","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/country","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/default","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/email","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/expires","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/firstName","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/lastName","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/nameOnCard","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/phoneNumber","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/state","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/street","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/zipcode"],"title":"Enumeration Cases"}],"path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXTextFieldType","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"AWXTextFieldTypeExpires","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType~1expires\/title"},{"op":"replace","value":[{"text":"AWXTextFieldTypeExpires","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType~1expires\/fragments"},{"op":"replace","value":"AWXTextFieldTypePhoneNumber","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType~1phoneNumber\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AWXTextFieldTypePhoneNumber"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType~1phoneNumber\/fragments"},{"op":"replace","value":"AWXTextFieldTypeDefault","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType~1default\/title"},{"op":"replace","value":[{"text":"AWXTextFieldTypeDefault","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType~1default\/fragments"},{"op":"replace","value":"AWXTextFieldTypeCVC","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType~1CVC\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AWXTextFieldTypeCVC"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType~1CVC\/fragments"},{"op":"replace","value":"AWXTextFieldTypeFirstName","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType~1firstName\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AWXTextFieldTypeFirstName"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType~1firstName\/fragments"},{"op":"replace","value":"AWXTextFieldTypeCity","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType~1city\/title"},{"op":"replace","value":[{"text":"AWXTextFieldTypeCity","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType~1city\/fragments"},{"op":"replace","value":"AWXTextFieldType","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType\/title"},{"op":"replace","value":[{"text":"AWXTextFieldType","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType\/fragments"},{"op":"replace","value":[{"text":"AWXTextFieldType","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType\/navigatorTitle"},{"op":"replace","value":"AWXTextFieldTypeState","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType~1state\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AWXTextFieldTypeState"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType~1state\/fragments"},{"op":"replace","value":"AWXTextFieldTypeZipcode","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType~1zipcode\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AWXTextFieldTypeZipcode"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType~1zipcode\/fragments"},{"op":"replace","value":"AWXTextFieldTypeCardNumber","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType~1cardNumber\/title"},{"op":"replace","value":[{"text":"AWXTextFieldTypeCardNumber","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType~1cardNumber\/fragments"},{"op":"replace","value":"AWXTextFieldTypeNameOnCard","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType~1nameOnCard\/title"},{"op":"replace","value":[{"text":"AWXTextFieldTypeNameOnCard","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType~1nameOnCard\/fragments"},{"op":"replace","value":"AWXTextFieldTypeStreet","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType~1street\/title"},{"op":"replace","value":[{"text":"AWXTextFieldTypeStreet","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType~1street\/fragments"},{"op":"replace","value":"AWXTextFieldTypeCountry","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType~1country\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AWXTextFieldTypeCountry"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType~1country\/fragments"},{"op":"replace","value":"AWXTextFieldTypeLastName","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType~1lastName\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AWXTextFieldTypeLastName"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType~1lastName\/fragments"},{"op":"replace","value":"AWXTextFieldTypeEmail","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType~1email\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AWXTextFieldTypeEmail"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType~1email\/fragments"}]}]}