{"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONEncodable","doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/SQ","doc:\/\/org.cocoapods.Airwallex\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"metadata":{"symbolKind":"class","modules":[{"name":"Airwallex"}],"title":"AWXThreeDs","roleHeading":"Class","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXThreeDs","kind":"identifier"}],"externalID":"c:objc(cs)AWXThreeDs","navigatorTitle":[{"text":"AWXThreeDs","kind":"identifier"}]},"abstract":[{"type":"codeVoice","code":"AWXThreeDs"},{"text":" includes the information of 3ds.","type":"text"}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"topicSections":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXThreeDs\/attemptId","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXThreeDs\/deviceDataCollectionRes","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXThreeDs\/dsTransactionId","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXThreeDs\/paRes","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXThreeDs\/returnURL"],"title":"Instance Properties","generated":true}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"variants":[{"paths":["\/documentation\/airwallex\/awxthreeds"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxthreeds"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXThreeDs","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AWXThreeDs","kind":"identifier"}]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.Airwallex/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","url":"\/documentation\/airwallex","title":"Airwallex","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXThreeDs/returnURL":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Return url."}],"role":"symbol","url":"\/documentation\/airwallex\/awxthreeds\/returnurl","title":"returnURL","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXThreeDs\/returnURL","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"returnURL","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"returnURL","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXThreeDs/dsTransactionId":{"abstract":[{"type":"text","text":"3DS transaction ID."}],"kind":"symbol","title":"dsTransactionId","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXThreeDs\/dsTransactionId","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"dsTransactionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"dsTransactionId","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxthreeds\/dstransactionid"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXThreeDs/paRes":{"title":"paRes","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"paRes"}],"url":"\/documentation\/airwallex\/awxthreeds\/pares","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXThreeDs\/paRes","kind":"symbol","abstract":[{"type":"text","text":"Three domain request."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paRes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}]},"doc://org.cocoapods.Airwallex/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXThreeDs/attemptId":{"title":"attemptId","type":"topic","role":"symbol","navigatorTitle":[{"text":"attemptId","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxthreeds\/attemptid","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXThreeDs\/attemptId","kind":"symbol","abstract":[{"text":"Attempt ID.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attemptId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://org.cocoapods.Airwallex/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.Airwallex/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject","title":"NSObject"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXThreeDs":{"title":"AWXThreeDs","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWXThreeDs"}],"url":"\/documentation\/airwallex\/awxthreeds","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXThreeDs","kind":"symbol","abstract":[{"type":"codeVoice","code":"AWXThreeDs"},{"type":"text","text":" includes the information of 3ds."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXThreeDs"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXThreeDs/deviceDataCollectionRes":{"abstract":[{"text":"Device data collection response.","type":"text"}],"kind":"symbol","title":"deviceDataCollectionRes","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXThreeDs\/deviceDataCollectionRes","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deviceDataCollectionRes","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"deviceDataCollectionRes","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxthreeds\/devicedatacollectionres"},"doc://org.cocoapods.Airwallex/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.Airwallex/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.Airwallex/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","title":"Swift.CVarArg"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXJSONEncodable":{"abstract":[],"kind":"symbol","title":"AWXJSONEncodable","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONEncodable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXJSONEncodable","kind":"identifier"}],"navigatorTitle":[{"text":"AWXJSONEncodable","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxjsonencodable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AWXThreeDs"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"AWXThreeDs","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"AWXThreeDs","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXThreeDs\/attemptId","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXThreeDs\/deviceDataCollectionRes","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXThreeDs\/dsTransactionId","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXThreeDs\/paRes","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXThreeDs\/returnURL"],"title":"Instance Properties","generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONEncodable"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXThreeDs","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXThreeDs~1returnURL\/title","value":"returnURL"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXThreeDs~1returnURL\/fragments","value":[{"text":"returnURL","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXThreeDs~1dsTransactionId\/title","value":"dsTransactionId"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXThreeDs~1dsTransactionId\/fragments","value":[{"text":"dsTransactionId","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXThreeDs~1paRes\/title","value":"paRes"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXThreeDs~1paRes\/fragments","value":[{"text":"paRes","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXThreeDs~1attemptId\/title","value":"attemptId"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXThreeDs~1attemptId\/fragments","value":[{"text":"attemptId","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXThreeDs\/title","value":"AWXThreeDs"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXThreeDs\/fragments","value":[{"text":"AWXThreeDs","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXThreeDs\/navigatorTitle","value":[{"text":"AWXThreeDs","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXThreeDs~1deviceDataCollectionRes\/title","value":"deviceDataCollectionRes"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXThreeDs~1deviceDataCollectionRes\/fragments","value":[{"text":"deviceDataCollectionRes","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONEncodable\/title","value":"AWXJSONEncodable"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONEncodable\/fragments","value":[{"text":"AWXJSONEncodable","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONEncodable\/navigatorTitle","value":[{"text":"AWXJSONEncodable","kind":"identifier"}]}]}]}