{"abstract":[{"text":"The main UI context for Airwallex payment flows.","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"anchor":"Classes","title":"Classes","generated":true,"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/Configuration"]},{"anchor":"Type-Properties","title":"Type Properties","generated":true,"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/shared"]},{"anchor":"Type-Methods","title":"Type Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/launchCardPayment(from:session:paymentResultDelegate:supportedBrands:launchStyle:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/launchCardPayment(from:session:supportedBrands:launchStyle:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/launchPayment(from:session:configuration:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/launchPayment(from:session:filterBy:launchStyle:layout:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/launchPayment(from:session:paymentResultDelegate:configuration:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/launchPayment(from:session:paymentResultDelegate:filterBy:launchStyle:layout:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/launchPayment(name:from:session:paymentResultDelegate:supportedBrands:launchStyle:)"]},{"anchor":"Enumerations","title":"Enumerations","generated":true,"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/ElementType","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/LaunchError","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/LaunchStyle","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/PaymentLayout"]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/SQ","doc:\/\/org.cocoapods.Airwallex\/SH","doc:\/\/org.cocoapods.Airwallex\/s8SendableP"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@Airwallex@objc(cs)AWXUIContext","symbolKind":"class","roleHeading":"Class","modules":[{"name":"Airwallex"}],"navigatorTitle":[{"text":"AWXUIContext","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXUIContext","kind":"identifier"}],"title":"AWXUIContext"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXUIContext"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"text":"Overview","level":2,"type":"heading","anchor":"overview"},{"inlineContent":[{"code":"AWXUIContext","type":"codeVoice"},{"type":"text","text":" provides a high-level interface for launching pre-built payment flows."},{"type":"text","text":" "},{"type":"text","text":"It handles the presentation of payment forms, user interactions, and payment processing"},{"type":"text","text":" "},{"type":"text","text":"with minimal integration effort."}],"type":"paragraph"},{"text":"Usage","level":2,"type":"heading","anchor":"Usage"},{"syntax":"swift","type":"codeListing","code":["let context = AWXUIContext()","context.launchPayment(","    from: viewController,","    session: session",")"]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/airwallex\/awxuicontext"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxuicontext"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"kind":"symbol","sections":[],"references":{"doc://org.cocoapods.Airwallex/SQ":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXUIContext/LaunchError":{"role":"symbol","type":"topic","title":"AWXUIContext.LaunchError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LaunchError"}],"navigatorTitle":[{"kind":"identifier","text":"LaunchError"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/LaunchError","url":"\/documentation\/airwallex\/awxuicontext\/launcherror"},"doc://org.cocoapods.Airwallex/s8SendableP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXUIContext/launchCardPayment(from:session:supportedBrands:launchStyle:)":{"abstract":[{"type":"text","text":"Launches the Airwallex card payment flow."}],"url":"\/documentation\/airwallex\/awxuicontext\/launchcardpayment(from:session:supportedbrands:launchstyle:)","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/launchCardPayment(from:session:supportedBrands:launchStyle:)","navigatorTitle":[{"kind":"identifier","text":"launchCardPaymentFrom:session:supportedBrands:launchStyle:"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"launchCardPayment"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"kind":"text","text":" & "},{"preciseIdentifier":"c:objc(pl)AWXPaymentResultDelegate","kind":"typeIdentifier","text":"AWXPaymentResultDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"session"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AWXSession","kind":"typeIdentifier","text":"AWXSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"supportedBrands"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:AWXConstants.h@T@AWXCardBrand","kind":"typeIdentifier","text":"AWXCardBrand"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"launchStyle"},{"kind":"text","text":": "},{"preciseIdentifier":"s:9Airwallex12AWXUIContextC11LaunchStyleO","kind":"typeIdentifier","text":"LaunchStyle"},{"kind":"text","text":")"}],"kind":"symbol","title":"launchCardPayment(from:session:supportedBrands:launchStyle:)"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXUIContext/launchPayment(from:session:filterBy:launchStyle:layout:)":{"abstract":[{"type":"text","text":"Launches the Airwallex payment sheet."}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/launchPayment(from:session:filterBy:launchStyle:layout:)","url":"\/documentation\/airwallex\/awxuicontext\/launchpayment(from:session:filterby:launchstyle:layout:)","navigatorTitle":[{"kind":"identifier","text":"launchPaymentFrom:session:filterBy:launchStyle:layout:"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"launchPayment"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"kind":"text","text":" & "},{"preciseIdentifier":"c:objc(pl)AWXPaymentResultDelegate","kind":"typeIdentifier","text":"AWXPaymentResultDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"session"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AWXSession","kind":"typeIdentifier","text":"AWXSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"filterBy"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"launchStyle"},{"kind":"text","text":": "},{"preciseIdentifier":"s:9Airwallex12AWXUIContextC11LaunchStyleO","kind":"typeIdentifier","text":"LaunchStyle"},{"kind":"text","text":", "},{"kind":"externalParam","text":"layout"},{"kind":"text","text":": "},{"preciseIdentifier":"s:9Airwallex12AWXUIContextC13PaymentLayoutO","kind":"typeIdentifier","text":"PaymentLayout"},{"kind":"text","text":")"}],"kind":"symbol","title":"launchPayment(from:session:filterBy:launchStyle:layout:)"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXUIContext/launchPayment(from:session:paymentResultDelegate:configuration:)":{"abstract":[{"type":"text","text":"Launches the Airwallex payment UI using a configuration object."}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/launchPayment(from:session:paymentResultDelegate:configuration:)","url":"\/documentation\/airwallex\/awxuicontext\/launchpayment(from:session:paymentresultdelegate:configuration:)","navigatorTitle":[{"kind":"identifier","text":"launchPaymentFrom:session:paymentResultDelegate:configuration:"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"launchPayment"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"session"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AWXSession","kind":"typeIdentifier","text":"AWXSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"paymentResultDelegate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(pl)AWXPaymentResultDelegate","kind":"typeIdentifier","text":"AWXPaymentResultDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"preciseIdentifier":"s:9Airwallex12AWXUIContextC13ConfigurationC","kind":"typeIdentifier","text":"Configuration"},{"kind":"text","text":")"}],"kind":"symbol","title":"launchPayment(from:session:paymentResultDelegate:configuration:)"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXUIContext/launchPayment(name:from:session:paymentResultDelegate:supportedBrands:launchStyle:)":{"abstract":[{"type":"text","text":"Launches the Airwallex payment sheet for a specified payment method."}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/launchPayment(name:from:session:paymentResultDelegate:supportedBrands:launchStyle:)","url":"\/documentation\/airwallex\/awxuicontext\/launchpayment(name:from:session:paymentresultdelegate:supportedbrands:launchstyle:)","navigatorTitle":[{"kind":"identifier","text":"launchPaymentWithName:from:session:paymentResultDelegate:supportedBrands:launchStyle:"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"launchPayment"},{"kind":"text","text":"("},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"session"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AWXSession","kind":"typeIdentifier","text":"AWXSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"paymentResultDelegate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(pl)AWXPaymentResultDelegate","kind":"typeIdentifier","text":"AWXPaymentResultDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"supportedBrands"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:AWXConstants.h@T@AWXCardBrand","kind":"typeIdentifier","text":"AWXCardBrand"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"launchStyle"},{"kind":"text","text":": "},{"preciseIdentifier":"s:9Airwallex12AWXUIContextC11LaunchStyleO","kind":"typeIdentifier","text":"LaunchStyle"},{"kind":"text","text":")"}],"kind":"symbol","title":"launchPayment(name:from:session:paymentResultDelegate:supportedBrands:launchStyle:)"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","url":"\/documentation\/airwallex","abstract":[],"title":"Airwallex"},"doc://org.cocoapods.Airwallex/objc(cs)NSObject":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXUIContext/shared":{"abstract":[],"url":"\/documentation\/airwallex\/awxuicontext\/shared","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/shared","navigatorTitle":[{"text":"shared","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWXUIContext","kind":"typeIdentifier","preciseIdentifier":"c:@M@Airwallex@objc(cs)AWXUIContext"}],"kind":"symbol","title":"shared"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXUIContext/launchCardPayment(from:session:paymentResultDelegate:supportedBrands:launchStyle:)":{"abstract":[{"type":"text","text":"Launches the Airwallex card payment flow."}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/launchCardPayment(from:session:paymentResultDelegate:supportedBrands:launchStyle:)","url":"\/documentation\/airwallex\/awxuicontext\/launchcardpayment(from:session:paymentresultdelegate:supportedbrands:launchstyle:)","navigatorTitle":[{"kind":"identifier","text":"launchCardPaymentFrom:session:paymentResultDelegate:supportedBrands:launchStyle:"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"launchCardPayment"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"session"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AWXSession","kind":"typeIdentifier","text":"AWXSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"paymentResultDelegate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(pl)AWXPaymentResultDelegate","kind":"typeIdentifier","text":"AWXPaymentResultDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"supportedBrands"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:AWXConstants.h@T@AWXCardBrand","kind":"typeIdentifier","text":"AWXCardBrand"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"launchStyle"},{"kind":"text","text":": "},{"preciseIdentifier":"s:9Airwallex12AWXUIContextC11LaunchStyleO","kind":"typeIdentifier","text":"LaunchStyle"},{"kind":"text","text":")"}],"kind":"symbol","title":"launchCardPayment(from:session:paymentResultDelegate:supportedBrands:launchStyle:)"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXUIContext/LaunchStyle":{"abstract":[],"url":"\/documentation\/airwallex\/awxuicontext\/launchstyle","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/LaunchStyle","navigatorTitle":[{"kind":"identifier","text":"LaunchStyle"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LaunchStyle"}],"kind":"symbol","title":"AWXUIContext.LaunchStyle"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXUIContext/launchPayment(from:session:configuration:)":{"abstract":[{"type":"text","text":"Launches the Airwallex payment UI using a configuration object."}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/launchPayment(from:session:configuration:)","url":"\/documentation\/airwallex\/awxuicontext\/launchpayment(from:session:configuration:)","navigatorTitle":[{"kind":"identifier","text":"launchPaymentFrom:session:configuration:"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"launchPayment"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"kind":"text","text":" & "},{"preciseIdentifier":"c:objc(pl)AWXPaymentResultDelegate","kind":"typeIdentifier","text":"AWXPaymentResultDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"session"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AWXSession","kind":"typeIdentifier","text":"AWXSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"preciseIdentifier":"s:9Airwallex12AWXUIContextC13ConfigurationC","kind":"typeIdentifier","text":"Configuration"},{"kind":"text","text":")"}],"kind":"symbol","title":"launchPayment(from:session:configuration:)"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXUIContext/PaymentLayout":{"role":"symbol","type":"topic","title":"AWXUIContext.PaymentLayout","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentLayout"}],"navigatorTitle":[{"kind":"identifier","text":"PaymentLayout"}],"kind":"symbol","abstract":[{"type":"text","text":"Defines the layout style for payment method selection."}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/PaymentLayout","url":"\/documentation\/airwallex\/awxuicontext\/paymentlayout"},"doc://org.cocoapods.Airwallex/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://org.cocoapods.Airwallex/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://org.cocoapods.Airwallex/SH":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://org.cocoapods.Airwallex/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://org.cocoapods.Airwallex/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXUIContext/launchPayment(from:session:paymentResultDelegate:filterBy:launchStyle:layout:)":{"abstract":[{"type":"text","text":"Launches the Airwallex payment sheet."}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/launchPayment(from:session:paymentResultDelegate:filterBy:launchStyle:layout:)","url":"\/documentation\/airwallex\/awxuicontext\/launchpayment(from:session:paymentresultdelegate:filterby:launchstyle:layout:)","navigatorTitle":[{"kind":"identifier","text":"launchPaymentFrom:session:paymentResultDelegate:filterBy:launchStyle:layout:"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"launchPayment"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"session"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AWXSession","kind":"typeIdentifier","text":"AWXSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"paymentResultDelegate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(pl)AWXPaymentResultDelegate","kind":"typeIdentifier","text":"AWXPaymentResultDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"filterBy"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"launchStyle"},{"kind":"text","text":": "},{"preciseIdentifier":"s:9Airwallex12AWXUIContextC11LaunchStyleO","kind":"typeIdentifier","text":"LaunchStyle"},{"kind":"text","text":", "},{"kind":"externalParam","text":"layout"},{"kind":"text","text":": "},{"preciseIdentifier":"s:9Airwallex12AWXUIContextC13PaymentLayoutO","kind":"typeIdentifier","text":"PaymentLayout"},{"kind":"text","text":")"}],"kind":"symbol","title":"launchPayment(from:session:paymentResultDelegate:filterBy:launchStyle:layout:)"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXUIContext/Configuration":{"abstract":[{"type":"text","text":"Configuration options for launching the payment UI."}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/Configuration","url":"\/documentation\/airwallex\/awxuicontext\/configuration","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"kind":"symbol","title":"AWXUIContext.Configuration"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXUIContext/ElementType":{"role":"symbol","type":"topic","title":"AWXUIContext.ElementType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ElementType"}],"navigatorTitle":[{"kind":"identifier","text":"ElementType"}],"kind":"symbol","abstract":[{"type":"text","text":"The type of payment flow to display."}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/ElementType","url":"\/documentation\/airwallex\/awxuicontext\/elementtype"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXUIContext":{"role":"symbol","type":"topic","title":"AWXUIContext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXUIContext"}],"navigatorTitle":[{"kind":"identifier","text":"AWXUIContext"}],"kind":"symbol","abstract":[{"type":"text","text":"The main UI context for Airwallex payment flows."}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext","url":"\/documentation\/airwallex\/awxuicontext"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"AWXUIContext","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AWXUIContext"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AWXUIContext"}],"op":"replace"},{"path":"\/topicSections","value":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/shared"],"title":"Type Properties","anchor":"Type-Properties"},{"generated":true,"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/launchCardPayment(from:session:paymentResultDelegate:supportedBrands:launchStyle:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/launchCardPayment(from:session:supportedBrands:launchStyle:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/launchPayment(from:session:configuration:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/launchPayment(from:session:filterBy:launchStyle:layout:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/launchPayment(from:session:paymentResultDelegate:configuration:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/launchPayment(from:session:paymentResultDelegate:filterBy:launchStyle:layout:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/launchPayment(name:from:session:paymentResultDelegate:supportedBrands:launchStyle:)"],"title":"Type Methods","anchor":"Type-Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXUIContext","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext~1launchCardPayment(from:session:supportedBrands:launchStyle:)\/title","value":"launchCardPaymentFrom:session:supportedBrands:launchStyle:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext~1launchCardPayment(from:session:supportedBrands:launchStyle:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"launchCardPaymentFrom:session:supportedBrands:launchStyle:"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext~1launchPayment(from:session:filterBy:launchStyle:layout:)\/title","value":"launchPaymentFrom:session:filterBy:launchStyle:layout:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext~1launchPayment(from:session:filterBy:launchStyle:layout:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"launchPaymentFrom:session:filterBy:launchStyle:layout:"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext~1launchPayment(from:session:paymentResultDelegate:configuration:)\/title","value":"launchPaymentFrom:session:paymentResultDelegate:configuration:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext~1launchPayment(from:session:paymentResultDelegate:configuration:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"launchPaymentFrom:session:paymentResultDelegate:configuration:"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext~1launchPayment(name:from:session:paymentResultDelegate:supportedBrands:launchStyle:)\/title","value":"launchPaymentWithName:from:session:paymentResultDelegate:supportedBrands:launchStyle:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext~1launchPayment(name:from:session:paymentResultDelegate:supportedBrands:launchStyle:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"launchPaymentWithName:from:session:paymentResultDelegate:supportedBrands:launchStyle:"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext~1shared\/title","value":"shared","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext~1shared\/fragments","value":[{"kind":"identifier","text":"shared"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext~1launchCardPayment(from:session:paymentResultDelegate:supportedBrands:launchStyle:)\/title","value":"launchCardPaymentFrom:session:paymentResultDelegate:supportedBrands:launchStyle:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext~1launchCardPayment(from:session:paymentResultDelegate:supportedBrands:launchStyle:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"launchCardPaymentFrom:session:paymentResultDelegate:supportedBrands:launchStyle:"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext~1launchPayment(from:session:configuration:)\/title","value":"launchPaymentFrom:session:configuration:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext~1launchPayment(from:session:configuration:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"launchPaymentFrom:session:configuration:"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext~1launchPayment(from:session:paymentResultDelegate:filterBy:launchStyle:layout:)\/title","value":"launchPaymentFrom:session:paymentResultDelegate:filterBy:launchStyle:layout:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext~1launchPayment(from:session:paymentResultDelegate:filterBy:launchStyle:layout:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"launchPaymentFrom:session:paymentResultDelegate:filterBy:launchStyle:layout:"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext\/title","value":"AWXUIContext","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext\/fragments","value":[{"kind":"identifier","text":"AWXUIContext"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext\/navigatorTitle","value":[{"kind":"identifier","text":"AWXUIContext"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}