{"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXWeChatPaySDKResponse\/appId","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXWeChatPaySDKResponse\/nonceStr","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXWeChatPaySDKResponse\/package","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXWeChatPaySDKResponse\/partnerId","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXWeChatPaySDKResponse\/prepayId","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXWeChatPaySDKResponse\/sign","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXWeChatPaySDKResponse\/timeStamp"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"}],"variants":[{"paths":["\/documentation\/airwallex\/awxwechatpaysdkresponse"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxwechatpaysdkresponse"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"metadata":{"title":"AWXWeChatPaySDKResponse","navigatorTitle":[{"kind":"identifier","text":"AWXWeChatPaySDKResponse"}],"roleHeading":"Class","role":"symbol","modules":[{"name":"Airwallex"}],"externalID":"c:objc(cs)AWXWeChatPaySDKResponse","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AWXWeChatPaySDKResponse"}]},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXWeChatPaySDKResponse","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"code":"AWXWeChatPaySDKResponse","type":"codeVoice"},{"type":"text","text":" includes the parameters for WeChatSDK."}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AWXWeChatPaySDKResponse"}],"platforms":["iOS"]}],"kind":"declarations"}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONDecodable","doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/SQ","doc:\/\/org.cocoapods.Airwallex\/SH"],"type":"conformsTo"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXWeChatPaySDKResponse/package":{"abstract":[{"type":"text","text":"Package"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXWeChatPaySDKResponse\/package","url":"\/documentation\/airwallex\/awxwechatpaysdkresponse\/package","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"package","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"kind":"symbol","title":"package","navigatorTitle":[{"text":"package","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXJSONDecodable":{"title":"AWXJSONDecodable","url":"\/documentation\/airwallex\/awxjsondecodable","type":"topic","navigatorTitle":[{"text":"AWXJSONDecodable","kind":"identifier"}],"abstract":[],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"AWXJSONDecodable","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONDecodable"},"doc://org.cocoapods.Airwallex/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXWeChatPaySDKResponse/appId":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXWeChatPaySDKResponse\/appId","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"appId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"title":"appId","navigatorTitle":[{"text":"appId","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/airwallex\/awxwechatpaysdkresponse\/appid","abstract":[{"type":"text","text":"WeChat pay app id."}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXWeChatPaySDKResponse/timeStamp":{"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXWeChatPaySDKResponse\/timeStamp","kind":"symbol","title":"timeStamp","navigatorTitle":[{"kind":"identifier","text":"timeStamp"}],"url":"\/documentation\/airwallex\/awxwechatpaysdkresponse\/timestamp","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"timeStamp"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Timestamp"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXWeChatPaySDKResponse/sign":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXWeChatPaySDKResponse\/sign","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"sign","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"sign","navigatorTitle":[{"text":"sign","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/airwallex\/awxwechatpaysdkresponse\/sign","abstract":[{"text":"Sign","type":"text"}]},"doc://org.cocoapods.Airwallex/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/airwallex","title":"Airwallex","role":"collection"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXWeChatPaySDKResponse/nonceStr":{"abstract":[{"type":"text","text":"Nonce string"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"nonceStr","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXWeChatPaySDKResponse\/nonceStr","role":"symbol","url":"\/documentation\/airwallex\/awxwechatpaysdkresponse\/noncestr","title":"nonceStr","type":"topic","navigatorTitle":[{"text":"nonceStr","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXWeChatPaySDKResponse/prepayId":{"abstract":[{"type":"text","text":"Prepay id"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXWeChatPaySDKResponse\/prepayId","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"prepayId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"prepayId","kind":"identifier"}],"title":"prepayId","url":"\/documentation\/airwallex\/awxwechatpaysdkresponse\/prepayid"},"doc://org.cocoapods.Airwallex/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SH"},"doc://org.cocoapods.Airwallex/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.Airwallex/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://org.cocoapods.Airwallex/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXWeChatPaySDKResponse/partnerId":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXWeChatPaySDKResponse\/partnerId","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"partnerId","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"partnerId","navigatorTitle":[{"text":"partnerId","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/airwallex\/awxwechatpaysdkresponse\/partnerid","abstract":[{"text":"Partner id","type":"text"}]},"doc://org.cocoapods.Airwallex/SQ":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXWeChatPaySDKResponse":{"url":"\/documentation\/airwallex\/awxwechatpaysdkresponse","navigatorTitle":[{"text":"AWXWeChatPaySDKResponse","kind":"identifier"}],"kind":"symbol","type":"topic","title":"AWXWeChatPaySDKResponse","role":"symbol","abstract":[{"type":"codeVoice","code":"AWXWeChatPaySDKResponse"},{"text":" includes the parameters for WeChatSDK.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXWeChatPaySDKResponse","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXWeChatPaySDKResponse"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AWXWeChatPaySDKResponse"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"value":[{"kind":"identifier","text":"AWXWeChatPaySDKResponse"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"AWXWeChatPaySDKResponse","kind":"identifier"}]},{"op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXWeChatPaySDKResponse\/appId","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXWeChatPaySDKResponse\/nonceStr","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXWeChatPaySDKResponse\/package","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXWeChatPaySDKResponse\/partnerId","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXWeChatPaySDKResponse\/prepayId","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXWeChatPaySDKResponse\/sign","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXWeChatPaySDKResponse\/timeStamp"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"}],"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONDecodable"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXWeChatPaySDKResponse","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXWeChatPaySDKResponse~1package\/title","value":"package"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXWeChatPaySDKResponse~1package\/fragments","value":[{"text":"package","kind":"identifier"}]},{"value":"AWXJSONDecodable","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONDecodable\/title","op":"replace"},{"value":[{"text":"AWXJSONDecodable","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONDecodable\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONDecodable\/navigatorTitle","value":[{"text":"AWXJSONDecodable","kind":"identifier"}]},{"value":"appId","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXWeChatPaySDKResponse~1appId\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXWeChatPaySDKResponse~1appId\/fragments","value":[{"text":"appId","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXWeChatPaySDKResponse~1timeStamp\/title","op":"replace","value":"timeStamp"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXWeChatPaySDKResponse~1timeStamp\/fragments","value":[{"text":"timeStamp","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXWeChatPaySDKResponse~1sign\/title","value":"sign","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXWeChatPaySDKResponse~1sign\/fragments","value":[{"kind":"identifier","text":"sign"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXWeChatPaySDKResponse~1nonceStr\/title","value":"nonceStr"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXWeChatPaySDKResponse~1nonceStr\/fragments","value":[{"text":"nonceStr","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXWeChatPaySDKResponse~1prepayId\/title","op":"replace","value":"prepayId"},{"op":"replace","value":[{"kind":"identifier","text":"prepayId"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXWeChatPaySDKResponse~1prepayId\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXWeChatPaySDKResponse~1partnerId\/title","op":"replace","value":"partnerId"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXWeChatPaySDKResponse~1partnerId\/fragments","op":"replace","value":[{"kind":"identifier","text":"partnerId"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXWeChatPaySDKResponse\/title","value":"AWXWeChatPaySDKResponse"},{"value":[{"text":"AWXWeChatPaySDKResponse","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXWeChatPaySDKResponse\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXWeChatPaySDKResponse\/navigatorTitle","value":[{"text":"AWXWeChatPaySDKResponse","kind":"identifier"}]}]}]}