{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/ClassToHandleFlowForPaymentMethodType(_:)"},"metadata":{"title":"ClassToHandleFlowForPaymentMethodType(_:)","externalID":"c:@F@ClassToHandleFlowForPaymentMethodType","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ClassToHandleFlowForPaymentMethodType","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AWXPaymentMethodType","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPaymentMethodType"},{"text":") -> ","kind":"text"},{"text":"AnyClass","kind":"typeIdentifier","preciseIdentifier":"s:s8AnyClassa"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"ClassToHandleFlowForPaymentMethodType","kind":"identifier"}],"roleHeading":"Function","symbolKind":"func","modules":[{"name":"Airwallex"}],"role":"symbol"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClassToHandleFlowForPaymentMethodType"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWXPaymentMethodType","preciseIdentifier":"c:objc(cs)AWXPaymentMethodType","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethodType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"AnyClass","preciseIdentifier":"s:s8AnyClassa"},{"kind":"text","text":"?"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/classtohandleflowforpaymentmethodtype(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/classtohandleflowforpaymentmethodtype(_:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","role":"collection","title":"Airwallex","url":"\/documentation\/airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentMethodType":{"abstract":[{"code":"AWXPaymentMethodType","type":"codeVoice"},{"text":" includes the information of a payment method.","type":"text"}],"title":"AWXPaymentMethodType","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethodType","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentMethodType"}],"navigatorTitle":[{"kind":"identifier","text":"AWXPaymentMethodType"}],"type":"topic","url":"\/documentation\/airwallex\/awxpaymentmethodtype","role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/ClassToHandleFlowForPaymentMethodType(_:)":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/ClassToHandleFlowForPaymentMethodType(_:)","type":"topic","url":"\/documentation\/airwallex\/classtohandleflowforpaymentmethodtype(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ClassToHandleFlowForPaymentMethodType","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AWXPaymentMethodType","preciseIdentifier":"c:objc(cs)AWXPaymentMethodType","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"AnyClass","preciseIdentifier":"s:s8AnyClassa","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[],"role":"symbol","navigatorTitle":[{"text":"ClassToHandleFlowForPaymentMethodType","kind":"identifier"}],"title":"ClassToHandleFlowForPaymentMethodType(_:)"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Function","op":"replace","path":"\/metadata\/roleHeading"},{"value":"ClassToHandleFlowForPaymentMethodType","op":"replace","path":"\/metadata\/title"},{"value":"func","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"ClassToHandleFlowForPaymentMethodType"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@T@Class","text":"Class","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"ClassToHandleFlowForPaymentMethodType","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethodType","preciseIdentifier":"c:objc(cs)AWXPaymentMethodType","text":"AWXPaymentMethodType","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"type","kind":"internalParam"},{"text":");","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"AWXPaymentMethodType","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethodType\/title"},{"value":[{"kind":"identifier","text":"AWXPaymentMethodType"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethodType\/fragments"},{"value":[{"kind":"identifier","text":"AWXPaymentMethodType"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethodType\/navigatorTitle"},{"value":"ClassToHandleFlowForPaymentMethodType","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1ClassToHandleFlowForPaymentMethodType(_:)\/title"},{"value":[{"text":"ClassToHandleFlowForPaymentMethodType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1ClassToHandleFlowForPaymentMethodType(_:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}