{"variants":[{"paths":["\/documentation\/airwallex\/formatairwallexsdkmode(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/formatairwallexsdkmode(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormatAirwallexSDKMode","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"mode","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexSDKMode","text":"AirwallexSDKMode","preciseIdentifier":"c:@E@AirwallexSDKMode","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormatAirwallexSDKMode","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AirwallexSDKMode","kind":"typeIdentifier","preciseIdentifier":"c:@E@AirwallexSDKMode"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","roleHeading":"Function","externalID":"c:@F@FormatAirwallexSDKMode","symbolKind":"func","modules":[{"name":"Airwallex"}],"title":"FormatAirwallexSDKMode(_:)","navigatorTitle":[{"kind":"identifier","text":"FormatAirwallexSDKMode"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/FormatAirwallexSDKMode(_:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","abstract":[],"title":"Airwallex","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexSDKMode":{"navigatorTitle":[{"text":"AirwallexSDKMode","kind":"identifier"}],"url":"\/documentation\/airwallex\/airwallexsdkmode","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexSDKMode","kind":"symbol","type":"topic","title":"AirwallexSDKMode","abstract":[],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AirwallexSDKMode","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/FormatAirwallexSDKMode(_:)":{"url":"\/documentation\/airwallex\/formatairwallexsdkmode(_:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/FormatAirwallexSDKMode(_:)","kind":"symbol","title":"FormatAirwallexSDKMode(_:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormatAirwallexSDKMode"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@AirwallexSDKMode","kind":"typeIdentifier","text":"AirwallexSDKMode"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"FormatAirwallexSDKMode"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Function","op":"replace"},{"path":"\/metadata\/title","value":"FormatAirwallexSDKMode","op":"replace"},{"path":"\/metadata\/symbolKind","value":"func","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FormatAirwallexSDKMode"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"FormatAirwallexSDKMode"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexSDKMode","preciseIdentifier":"c:@E@AirwallexSDKMode","text":"AirwallexSDKMode"},{"kind":"text","text":" "},{"kind":"internalParam","text":"mode"},{"kind":"text","text":");"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexSDKMode\/title","value":"AirwallexSDKMode","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexSDKMode\/fragments","value":[{"kind":"identifier","text":"AirwallexSDKMode"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexSDKMode\/navigatorTitle","value":[{"text":"AirwallexSDKMode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1FormatAirwallexSDKMode(_:)\/title","value":"FormatAirwallexSDKMode","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1FormatAirwallexSDKMode(_:)\/fragments","value":[{"kind":"identifier","text":"FormatAirwallexSDKMode"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}