{"variants":[{"paths":["\/documentation\/airwallex\/paymentsessionhandler"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/paymentsessionhandler"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler\/init(session:viewController:methodType:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler\/init(session:viewController:paymentResultDelegate:methodType:)"],"title":"Initializers","generated":true,"anchor":"Initializers"},{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler\/startApplePay()","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler\/startCardPayment(with:billing:saveCard:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler\/startConsentPayment(with:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler\/startConsentPayment(withId:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler\/startConsentPayment(withId:requiresCVC:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler\/startRedirectPayment(with:additionalInfo:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"},{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler\/canHandle(methodType:session:)"],"title":"Type Methods","generated":true,"anchor":"Type-Methods"},{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler\/AWXProviderDelegate-Implementations"],"title":"Default Implementations","generated":true,"anchor":"Default-Implementations"}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXProviderDelegate","doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","doc:\/\/org.cocoapods.Airwallex\/s8CopyableP","doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/SQ","doc:\/\/org.cocoapods.Airwallex\/SH"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"abstract":[{"type":"text","text":"A low-level API handler for managing Airwallex payment sessions."}],"seeAlsoSections":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentConsent"],"title":"API Integration","generated":true,"anchor":"API-Integration"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentSessionHandler"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"level":2,"anchor":"overview","text":"Overview","type":"heading"},{"inlineContent":[{"type":"codeVoice","code":"PaymentSessionHandler"},{"type":"text","text":" provides direct control over payment processing without pre-built UI components."},{"type":"text","text":" "},{"type":"text","text":"It’s designed for developers who want to implement custom payment flows while leveraging Airwallex’s"},{"type":"text","text":" "},{"type":"text","text":"payment processing capabilities."}],"type":"paragraph"},{"level":2,"anchor":"Usage","text":"Usage","type":"heading"},{"syntax":"swift","code":["let handler = PaymentSessionHandler(","    session: session,","    viewController: self,","    paymentResultDelegate: self",")","","\/\/ Handle card payment","handler.startCardPayment(","    card: card,","    billing: billing,","    saveCard: true",")","","\/\/ Handle Apple Pay","handler.startApplePay()"],"type":"codeListing"},{"inlineContent":[{"type":"text","text":"This class handles:"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"text":"Direct payment method processing","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Payment result callbacks"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Error handling and validation"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Custom payment flow integration"}],"type":"paragraph"}]}],"type":"unorderedList"}],"kind":"content"}],"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentSessionHandler"}],"title":"PaymentSessionHandler","symbolKind":"class","navigatorTitle":[{"text":"PaymentSessionHandler","kind":"identifier"}],"externalID":"c:@M@Airwallex@objc(cs)PaymentSessionHandler","roleHeading":"Class","modules":[{"name":"Airwallex"}],"role":"symbol"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentConsent":{"kind":"symbol","title":"AWXPaymentConsent","abstract":[{"code":"AWXPaymentConsent","type":"codeVoice"},{"text":" includes the info of payment consent.","type":"text"}],"navigatorTitle":[{"text":"AWXPaymentConsent","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPaymentConsent","kind":"identifier"}],"role":"symbol","url":"\/documentation\/airwallex\/awxpaymentconsent","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentConsent","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentSessionHandler/init(session:viewController:paymentResultDelegate:methodType:)":{"url":"\/documentation\/airwallex\/paymentsessionhandler\/init(session:viewcontroller:paymentresultdelegate:methodtype:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler\/init(session:viewController:paymentResultDelegate:methodType:)","abstract":[{"type":"text","text":"Initializes a "},{"type":"codeVoice","code":"PaymentSessionHandler"},{"type":"text","text":" with a payment session and the view controller from which the payment is initiated."}],"title":"init(session:viewController:paymentResultDelegate:methodType:)","role":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"session"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWXSession","preciseIdentifier":"c:objc(cs)AWXSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"viewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"paymentResultDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWXPaymentResultDelegate","preciseIdentifier":"c:objc(pl)AWXPaymentResultDelegate"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"methodType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWXPaymentMethodType","preciseIdentifier":"c:objc(cs)AWXPaymentMethodType"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"kind":"identifier","text":"initWithSession:viewController:paymentResultDelegate:methodType:"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentSessionHandler/startCardPayment(with:billing:saveCard:)":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startCardPayment"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXCard","text":"AWXCard"},{"kind":"text","text":", "},{"kind":"externalParam","text":"billing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPlaceDetails","text":"AWXPlaceDetails"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"saveCard"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"kind":"symbol","title":"startCardPayment(with:billing:saveCard:)","role":"symbol","url":"\/documentation\/airwallex\/paymentsessionhandler\/startcardpayment(with:billing:savecard:)","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler\/startCardPayment(with:billing:saveCard:)","abstract":[{"text":"Initiates a card payment transaction.","type":"text"},{"text":" ","type":"text"},{"text":"This method sets up and confirms a card-based payment, including optional billing and card-saving preferences.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"startCardPaymentWith:billing:saveCard:"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentSessionHandler/startConsentPayment(withId:)":{"title":"startConsentPayment(withId:)","kind":"symbol","navigatorTitle":[{"text":"startConsentPaymentWithId:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startConsentPayment"},{"text":"(","kind":"text"},{"text":"withId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Initiates a consent-based  subsequent one-off payment using a consent identifier without CVC requirement."}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler\/startConsentPayment(withId:)","type":"topic","url":"\/documentation\/airwallex\/paymentsessionhandler\/startconsentpayment(withid:)"},"doc://org.cocoapods.Airwallex/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.Airwallex/objc(cs)NSObject":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentSessionHandler/startConsentPayment(withId:requiresCVC:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startConsentPayment","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"requiresCVC","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/airwallex\/paymentsessionhandler\/startconsentpayment(withid:requirescvc:)","type":"topic","kind":"symbol","abstract":[{"text":"Initiates a consent-based subsequent one-off payment using a consent identifier with optional CVC requirement.","type":"text"}],"navigatorTitle":[{"text":"startConsentPaymentWithId:requiresCVC:","kind":"identifier"}],"role":"symbol","title":"startConsentPayment(withId:requiresCVC:)","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler\/startConsentPayment(withId:requiresCVC:)"},"doc://org.cocoapods.Airwallex/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentSessionHandler/startRedirectPayment(with:additionalInfo:)":{"navigatorTitle":[{"text":"startRedirectPaymentWith:additionalInfo:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler\/startRedirectPayment(with:additionalInfo:)","abstract":[{"text":"Initiates a schema-based payment transaction.","type":"text"},{"text":" ","type":"text"},{"text":"This method processes a payment with schema-based payment methods such as digital wallets or bank transfers.","type":"text"},{"text":" ","type":"text"},{"text":"You should collect all information from your user before calling this api","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"startRedirectPayment"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"additionalInfo"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"]?)"}],"type":"topic","title":"startRedirectPayment(with:additionalInfo:)","kind":"symbol","role":"symbol","url":"\/documentation\/airwallex\/paymentsessionhandler\/startredirectpayment(with:additionalinfo:)"},"doc://org.cocoapods.Airwallex/s8CopyableP":{"title":"Swift.Copyable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/s8CopyableP"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentSessionHandler/init(session:viewController:methodType:)":{"navigatorTitle":[{"text":"initWithSession:viewController:methodType:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler\/init(session:viewController:methodType:)","abstract":[{"text":"Initializes a ","type":"text"},{"code":"PaymentSessionHandler","type":"codeVoice"},{"text":" with a payment session and a view controller that also acts as a payment result delegate.","type":"text"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"session","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AWXSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXSession"},{"text":", ","kind":"text"},{"text":"viewController","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":" & ","kind":"text"},{"text":"AWXPaymentResultDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)AWXPaymentResultDelegate"},{"text":", ","kind":"text"},{"text":"methodType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AWXPaymentMethodType","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPaymentMethodType"},{"text":"?)","kind":"text"}],"type":"topic","title":"init(session:viewController:methodType:)","kind":"symbol","role":"symbol","url":"\/documentation\/airwallex\/paymentsessionhandler\/init(session:viewcontroller:methodtype:)"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXProviderDelegate":{"navigatorTitle":[{"text":"AWXProviderDelegate","kind":"identifier"}],"role":"symbol","url":"\/documentation\/airwallex\/awxproviderdelegate","abstract":[{"type":"text","text":"A delegate which handles checkout results."}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXProviderDelegate","title":"AWXProviderDelegate","type":"topic","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXProviderDelegate","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentSessionHandler/startConsentPayment(with:)":{"abstract":[{"text":"Initiates a consent-based payment using a previously obtained payment consent object.","type":"text"}],"type":"topic","url":"\/documentation\/airwallex\/paymentsessionhandler\/startconsentpayment(with:)","navigatorTitle":[{"text":"startConsentPaymentWith:","kind":"identifier"}],"role":"symbol","title":"startConsentPayment(with:)","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler\/startConsentPayment(with:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startConsentPayment","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AWXPaymentConsent","preciseIdentifier":"c:objc(cs)AWXPaymentConsent","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentSessionHandler":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PaymentSessionHandler","kind":"identifier"}],"url":"\/documentation\/airwallex\/paymentsessionhandler","type":"topic","kind":"symbol","abstract":[{"text":"A low-level API handler for managing Airwallex payment sessions.","type":"text"}],"navigatorTitle":[{"text":"PaymentSessionHandler","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler","title":"PaymentSessionHandler"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentSessionHandler/canHandle(methodType:session:)":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canHandle","kind":"identifier"},{"text":"(","kind":"text"},{"text":"methodType","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AWXPaymentMethodType","text":"AWXPaymentMethodType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"session","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AWXSession","text":"AWXSession","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"url":"\/documentation\/airwallex\/paymentsessionhandler\/canhandle(methodtype:session:)","type":"topic","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"canHandleWithMethodType:session:"}],"role":"symbol","title":"canHandle(methodType:session:)","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler\/canHandle(methodType:session:)"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentSessionHandler/AWXProviderDelegate-Implementations":{"type":"topic","abstract":[],"url":"\/documentation\/airwallex\/paymentsessionhandler\/awxproviderdelegate-implementations","kind":"article","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler\/AWXProviderDelegate-Implementations","title":"AWXProviderDelegate Implementations","role":"collectionGroup"},"doc://org.cocoapods.Airwallex/SQ":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://org.cocoapods.Airwallex/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://org.cocoapods.Airwallex/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentSessionHandler/startApplePay()":{"navigatorTitle":[{"text":"startApplePay","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/airwallex\/paymentsessionhandler\/startapplepay()","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler\/startApplePay()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startApplePay","kind":"identifier"},{"text":"()","kind":"text"}],"title":"startApplePay()","role":"symbol","abstract":[{"text":"Initiates an Apple Pay transaction.","type":"text"},{"text":" ","type":"text"},{"text":"This method sets up and starts the Apple Pay payment flow.","type":"text"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","url":"\/documentation\/airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol","title":"Airwallex","abstract":[],"role":"collection"},"doc://org.cocoapods.Airwallex/SH":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/SH","type":"unresolvable","title":"Swift.Hashable"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"PaymentSessionHandler","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"PaymentSessionHandler"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PaymentSessionHandler"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler\/init(session:viewController:methodType:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler\/init(session:viewController:paymentResultDelegate:methodType:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler\/startApplePay()","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler\/startCardPayment(with:billing:saveCard:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler\/startConsentPayment(with:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler\/startConsentPayment(withId:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler\/startConsentPayment(withId:requiresCVC:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler\/startRedirectPayment(with:additionalInfo:)"]},{"title":"Type Methods","generated":true,"anchor":"Type-Methods","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler\/canHandle(methodType:session:)"]},{"title":"Default Implementations","generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler\/AWXProviderDelegate-Implementations"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"],"kind":"relationships"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXProviderDelegate"],"kind":"relationships"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentConsent"],"anchor":"API-Integration","title":"API Integration","generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PaymentSessionHandler","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentConsent\/title","value":"AWXPaymentConsent"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentConsent\/fragments","value":[{"kind":"identifier","text":"AWXPaymentConsent"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentConsent\/navigatorTitle","value":[{"text":"AWXPaymentConsent","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler~1init(session:viewController:paymentResultDelegate:methodType:)\/title","value":"initWithSession:viewController:paymentResultDelegate:methodType:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler~1init(session:viewController:paymentResultDelegate:methodType:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithSession:viewController:paymentResultDelegate:methodType:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler~1startCardPayment(with:billing:saveCard:)\/title","value":"startCardPaymentWith:billing:saveCard:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler~1startCardPayment(with:billing:saveCard:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startCardPaymentWith:billing:saveCard:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler~1startConsentPayment(withId:)\/title","value":"startConsentPaymentWithId:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler~1startConsentPayment(withId:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"startConsentPaymentWithId:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler~1startConsentPayment(withId:requiresCVC:)\/title","value":"startConsentPaymentWithId:requiresCVC:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler~1startConsentPayment(withId:requiresCVC:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startConsentPaymentWithId:requiresCVC:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler~1startRedirectPayment(with:additionalInfo:)\/title","value":"startRedirectPaymentWith:additionalInfo:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler~1startRedirectPayment(with:additionalInfo:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startRedirectPaymentWith:additionalInfo:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler~1init(session:viewController:methodType:)\/title","value":"initWithSession:viewController:methodType:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler~1init(session:viewController:methodType:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSession:viewController:methodType:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXProviderDelegate\/title","value":"AWXProviderDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXProviderDelegate\/fragments","value":[{"text":"AWXProviderDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXProviderDelegate\/navigatorTitle","value":[{"text":"AWXProviderDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler~1startConsentPayment(with:)\/title","value":"startConsentPaymentWith:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler~1startConsentPayment(with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startConsentPaymentWith:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler\/title","value":"PaymentSessionHandler"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler\/fragments","value":[{"text":"PaymentSessionHandler","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler\/navigatorTitle","value":[{"text":"PaymentSessionHandler","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler~1canHandle(methodType:session:)\/title","value":"canHandleWithMethodType:session:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler~1canHandle(methodType:session:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"canHandleWithMethodType:session:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler~1startApplePay()\/title","value":"startApplePay","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler~1startApplePay()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startApplePay"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}