{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"symbolKind":"class","role":"symbol","title":"PaymentConsentOptions","modules":[{"name":"Airwallex"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PaymentConsentOptions","kind":"identifier"}],"externalID":"c:@M@Airwallex@objc(cs)PaymentConsentOptions","navigatorTitle":[{"text":"PaymentConsentOptions","kind":"identifier"}],"roleHeading":"Class"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentConsentOptions"}],"platforms":["iOS"]}]}],"topicSections":[{"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentConsentOptions\/init(nextTriggeredBy:merchantTriggerReason:termsOfUse:)"],"generated":true},{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentConsentOptions\/merchantTriggerReason","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentConsentOptions\/nextTriggeredBy","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentConsentOptions\/termsOfUse"],"generated":true},{"title":"Default Implementations","anchor":"Default-Implementations","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentConsentOptions\/AWXJSONEncodable-Implementations","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentConsentOptions\/Encodable-Implementations"],"generated":true}],"abstract":[{"type":"text","text":"Options for payment consents"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/paymentconsentoptions"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/paymentconsentoptions"]}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONEncodable","doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","doc:\/\/org.cocoapods.Airwallex\/s8CopyableP","doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/SE","doc:\/\/org.cocoapods.Airwallex\/SQ","doc:\/\/org.cocoapods.Airwallex\/SH"],"type":"conformsTo"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentConsentOptions"},"seeAlsoSections":[{"title":"Preparation","anchor":"Preparation","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions"],"generated":true}],"references":{"doc://org.cocoapods.Airwallex/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentConsentOptions/nextTriggeredBy":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentConsentOptions\/nextTriggeredBy","type":"topic","url":"\/documentation\/airwallex\/paymentconsentoptions\/nexttriggeredby","role":"symbol","title":"nextTriggeredBy","abstract":[{"type":"text","text":"The party to trigger subsequent payments. One of "},{"type":"codeVoice","code":"merchant"},{"type":"text","text":", "},{"type":"codeVoice","code":"customer"},{"type":"text","text":"."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextTriggeredBy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AirwallexNextTriggerByType","preciseIdentifier":"c:@E@AirwallexNextTriggerByType"}],"navigatorTitle":[{"text":"nextTriggeredBy","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.Airwallex/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP"},"doc://org.cocoapods.Airwallex/SH":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentConsentOptions/merchantTriggerReason":{"title":"merchantTriggerReason","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"merchantTriggerReason","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AirwallexMerchantTriggerReason","kind":"typeIdentifier","preciseIdentifier":"c:@E@AirwallexMerchantTriggerReason"}],"abstract":[{"type":"text","text":"indicate whether the subsequent payments are scheduled."},{"type":"text","text":" "},{"type":"text","text":"Only applicable when next_triggered_by is merchant. One of "},{"type":"codeVoice","code":".undefined"},{"type":"text","text":", "},{"type":"codeVoice","code":"scheduled"},{"type":"text","text":", "},{"type":"codeVoice","code":"unscheduled"},{"type":"text","text":", "},{"type":"codeVoice","code":"installments"},{"type":"text","text":". Default: "},{"type":"codeVoice","code":".undefined"}],"navigatorTitle":[{"text":"merchantTriggerReason","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentConsentOptions\/merchantTriggerReason","url":"\/documentation\/airwallex\/paymentconsentoptions\/merchanttriggerreason","type":"topic","role":"symbol"},"doc://org.cocoapods.Airwallex/s8CopyableP":{"title":"Swift.Copyable","identifier":"doc:\/\/org.cocoapods.Airwallex\/s8CopyableP","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXJSONEncodable":{"url":"\/documentation\/airwallex\/awxjsonencodable","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONEncodable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXJSONEncodable","kind":"identifier"}],"title":"AWXJSONEncodable","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AWXJSONEncodable"}],"abstract":[],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/airwallex","kind":"symbol"},"doc://org.cocoapods.Airwallex/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SQ"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentConsentOptions/AWXJSONEncodable-Implementations":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentConsentOptions\/AWXJSONEncodable-Implementations","url":"\/documentation\/airwallex\/paymentconsentoptions\/awxjsonencodable-implementations","role":"collectionGroup","title":"AWXJSONEncodable Implementations","abstract":[],"type":"topic","kind":"article"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentConsentOptions/Encodable-Implementations":{"url":"\/documentation\/airwallex\/paymentconsentoptions\/encodable-implementations","kind":"article","type":"topic","abstract":[],"title":"Encodable Implementations","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentConsentOptions\/Encodable-Implementations","role":"collectionGroup"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentConsentOptions/termsOfUse":{"navigatorTitle":[{"kind":"identifier","text":"termsOfUse"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"termsOfUse","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TermsOfUse","kind":"typeIdentifier","preciseIdentifier":"c:@M@Airwallex@objc(cs)TermsOfUse"},{"text":"?","kind":"text"}],"abstract":[{"text":"Terms to specify how this Payment Consent will be used.","type":"text"},{"text":" ","type":"text"},{"text":"Optional.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentConsentOptions\/termsOfUse","type":"topic","kind":"symbol","title":"termsOfUse","role":"symbol","url":"\/documentation\/airwallex\/paymentconsentoptions\/termsofuse"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentConsentOptions":{"navigatorTitle":[{"text":"PaymentConsentOptions","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentConsentOptions","url":"\/documentation\/airwallex\/paymentconsentoptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentConsentOptions"}],"type":"topic","abstract":[{"text":"Options for payment consents","type":"text"}],"title":"PaymentConsentOptions","role":"symbol","kind":"symbol"},"doc://org.cocoapods.Airwallex/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentIntent":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent","navigatorTitle":[{"text":"AWXPaymentIntent","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"codeVoice","code":"AWXPaymentIntent"},{"type":"text","text":" includes the information of payment intent."}],"title":"AWXPaymentIntent","url":"\/documentation\/airwallex\/awxpaymentintent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentIntent"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentConsentOptions/init(nextTriggeredBy:merchantTriggerReason:termsOfUse:)":{"type":"topic","title":"init(nextTriggeredBy:merchantTriggerReason:termsOfUse:)","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentConsentOptions\/init(nextTriggeredBy:merchantTriggerReason:termsOfUse:)","url":"\/documentation\/airwallex\/paymentconsentoptions\/init(nexttriggeredby:merchanttriggerreason:termsofuse:)","navigatorTitle":[{"kind":"identifier","text":"initWithNextTriggeredBy:merchantTriggerReason:termsOfUse:"}],"abstract":[{"text":"Creates a new payment consent options instance for recurring payments.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"nextTriggeredBy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@AirwallexNextTriggerByType","text":"AirwallexNextTriggerByType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"merchantTriggerReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AirwallexMerchantTriggerReason","preciseIdentifier":"c:@E@AirwallexMerchantTriggerReason"},{"kind":"text","text":", "},{"kind":"externalParam","text":"termsOfUse"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@Airwallex@objc(cs)TermsOfUse","text":"TermsOfUse","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]},"doc://org.cocoapods.Airwallex/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/Session":{"navigatorTitle":[{"text":"Session","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Session"}],"title":"Session","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session","type":"topic","url":"\/documentation\/airwallex\/session","abstract":[{"type":"codeVoice","code":"Session"},{"type":"text","text":" is a specialized subclass of "},{"type":"codeVoice","code":"AWXSession"}]},"doc://org.cocoapods.Airwallex/SE":{"title":"Swift.Encodable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SE","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXApplePayOptions":{"title":"AWXApplePayOptions","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXApplePayOptions","kind":"identifier"}],"navigatorTitle":[{"text":"AWXApplePayOptions","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Object used to construct PKPaymentRequest for Apple Pay."}],"type":"topic","url":"\/documentation\/airwallex\/awxapplepayoptions"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"PaymentConsentOptions","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"PaymentConsentOptions","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PaymentConsentOptions"}],"op":"replace"},{"path":"\/topicSections","value":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentConsentOptions\/merchantTriggerReason","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentConsentOptions\/nextTriggeredBy","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentConsentOptions\/termsOfUse"],"anchor":"Instance-Properties"},{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentConsentOptions\/init(nextTriggeredBy:merchantTriggerReason:termsOfUse:)"],"anchor":"Instance-Methods"},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentConsentOptions\/AWXJSONEncodable-Implementations"],"anchor":"Default-Implementations"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONEncodable"],"kind":"relationships","type":"conformsTo"}],"op":"replace"},{"path":"\/seeAlsoSections","value":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions"],"anchor":"Preparation","title":"Preparation"}],"op":"replace"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentConsentOptions"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentConsentOptions~1nextTriggeredBy\/title","value":"nextTriggeredBy","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentConsentOptions~1nextTriggeredBy\/fragments","value":[{"kind":"identifier","text":"nextTriggeredBy"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentConsentOptions~1merchantTriggerReason\/title","value":"merchantTriggerReason","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentConsentOptions~1merchantTriggerReason\/fragments","value":[{"text":"merchantTriggerReason","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONEncodable\/title","value":"AWXJSONEncodable","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONEncodable\/fragments","value":[{"kind":"identifier","text":"AWXJSONEncodable"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONEncodable\/navigatorTitle","value":[{"kind":"identifier","text":"AWXJSONEncodable"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentConsentOptions~1termsOfUse\/title","value":"termsOfUse","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentConsentOptions~1termsOfUse\/fragments","value":[{"text":"termsOfUse","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentConsentOptions\/title","value":"PaymentConsentOptions","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentConsentOptions\/fragments","value":[{"text":"PaymentConsentOptions","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentConsentOptions\/navigatorTitle","value":[{"kind":"identifier","text":"PaymentConsentOptions"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentIntent\/title","value":"AWXPaymentIntent","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentIntent\/fragments","value":[{"kind":"identifier","text":"AWXPaymentIntent"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentIntent\/navigatorTitle","value":[{"kind":"identifier","text":"AWXPaymentIntent"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentConsentOptions~1init(nextTriggeredBy:merchantTriggerReason:termsOfUse:)\/title","value":"initWithNextTriggeredBy:merchantTriggerReason:termsOfUse:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentConsentOptions~1init(nextTriggeredBy:merchantTriggerReason:termsOfUse:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithNextTriggeredBy:merchantTriggerReason:termsOfUse:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session\/title","value":"Session","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session\/fragments","value":[{"text":"Session","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session\/navigatorTitle","value":[{"kind":"identifier","text":"Session"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions\/title","value":"AWXApplePayOptions","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions\/fragments","value":[{"kind":"identifier","text":"AWXApplePayOptions"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions\/navigatorTitle","value":[{"text":"AWXApplePayOptions","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}