{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Session"}]}]},{"content":[{"anchor":"overview","type":"heading","level":2,"text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This class provides a unified interface for working with the simplified consent flow,"},{"type":"text","text":" "},{"type":"text","text":"abstracting away the complexity of different payment scenarios (one-off and recurring payments)."},{"type":"text","text":" "},{"type":"text","text":"It handles both standard payment intents and recurring payment configurations through a"},{"type":"text","text":" "},{"type":"text","text":"consistent API, making it easier to implement payment processing in your application."}]},{"type":"aside","name":"See Also","style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"code":"AWXSession","type":"codeVoice"},{"type":"text","text":", "},{"code":"PaymentConsentOptions","type":"codeVoice"}]}]}],"kind":"content"}],"abstract":[{"type":"codeVoice","code":"Session"},{"type":"text","text":" is a specialized subclass of "},{"type":"codeVoice","code":"AWXSession"}],"metadata":{"title":"Session","modules":[{"name":"Airwallex"}],"externalID":"c:@M@Airwallex@objc(cs)Session","symbolKind":"class","roleHeading":"Class","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Session","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Session"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session"},"sections":[],"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session\/init(paymentIntent:countryCode:applePayOptions:autoCapture:autoSaveCardForFuturePayments:billing:hidePaymentConsents:lang:paymentMethods:paymentConsentOptions:requiredBillingContactFields:returnURL:)"],"anchor":"Initializers","title":"Initializers","generated":true},{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session\/autoCapture","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session\/autoSaveCardForFuturePayments","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session\/paymentConsentOptions","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session\/paymentIntent"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session\/amount()","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session\/currency()","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session\/customerId()","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session\/paymentIntentId()","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session\/transactionMode()"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/SQ","doc:\/\/org.cocoapods.Airwallex\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","seeAlsoSections":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentConsentOptions","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions"],"anchor":"Preparation","title":"Preparation","generated":true}],"variants":[{"paths":["\/documentation\/airwallex\/session"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/session"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/Session/transactionMode()":{"navigatorTitle":[{"kind":"identifier","text":"transactionMode"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session\/transactionMode()","title":"transactionMode()","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Determines the transaction mode based on the presence of recurring options."}],"role":"symbol","url":"\/documentation\/airwallex\/session\/transactionmode()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"transactionMode"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/Session/autoSaveCardForFuturePayments":{"url":"\/documentation\/airwallex\/session\/autosavecardforfuturepayments","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session\/autoSaveCardForFuturePayments","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autoSaveCardForFuturePayments","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","navigatorTitle":[{"text":"autoSaveCardForFuturePayments","kind":"identifier"}],"kind":"symbol","title":"autoSaveCardForFuturePayments","abstract":[{"text":"Indicates whether card saving is enabled by default.","type":"text"},{"text":" ","type":"text"},{"text":"Defaults to YES.","type":"text"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/Session":{"navigatorTitle":[{"text":"Session","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Session"}],"title":"Session","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session","type":"topic","url":"\/documentation\/airwallex\/session","abstract":[{"type":"codeVoice","code":"Session"},{"type":"text","text":" is a specialized subclass of "},{"type":"codeVoice","code":"AWXSession"}]},"doc://org.cocoapods.Airwallex/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SH"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/airwallex","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/Session/autoCapture":{"role":"symbol","url":"\/documentation\/airwallex\/session\/autocapture","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session\/autoCapture","title":"autoCapture","abstract":[{"text":"Only applicable when payment_method.type is card. If true the payment will be captured immediately after authorization succeeds.","type":"text"},{"text":" ","type":"text"},{"text":"Default: YES","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoCapture"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"navigatorTitle":[{"text":"autoCapture","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/Session/paymentIntentId()":{"role":"symbol","abstract":[{"text":"Returns the payment intent ID.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentIntentId"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session\/paymentIntentId()","type":"topic","navigatorTitle":[{"text":"paymentIntentId","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/airwallex\/session\/paymentintentid()","title":"paymentIntentId()"},"doc://org.cocoapods.Airwallex/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/Session/init(paymentIntent:countryCode:applePayOptions:autoCapture:autoSaveCardForFuturePayments:billing:hidePaymentConsents:lang:paymentMethods:paymentConsentOptions:requiredBillingContactFields:returnURL:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session\/init(paymentIntent:countryCode:applePayOptions:autoCapture:autoSaveCardForFuturePayments:billing:hidePaymentConsents:lang:paymentMethods:paymentConsentOptions:requiredBillingContactFields:returnURL:)","url":"\/documentation\/airwallex\/session\/init(paymentintent:countrycode:applepayoptions:autocapture:autosavecardforfuturepayments:billing:hidepaymentconsents:lang:paymentmethods:paymentconsentoptions:requiredbillingcontactfields:returnurl:)","abstract":[{"type":"text","text":"Creates a new unified Session for payment processing."}],"role":"symbol","kind":"symbol","title":"init(paymentIntent:countryCode:applePayOptions:autoCapture:autoSaveCardForFuturePayments:billing:hidePaymentConsents:lang:paymentMethods:paymentConsentOptions:requiredBillingContactFields:returnURL:)","navigatorTitle":[{"kind":"identifier","text":"initWithPaymentIntent:countryCode:applePayOptions:autoCapture:autoSaveCardForFuturePayments:billing:hidePaymentConsents:lang:paymentMethods:paymentConsentOptions:requiredBillingContactFields:returnURL:"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"paymentIntent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWXPaymentIntent","preciseIdentifier":"c:objc(cs)AWXPaymentIntent"},{"kind":"text","text":", "},{"kind":"externalParam","text":"countryCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"applePayOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWXApplePayOptions","preciseIdentifier":"c:objc(cs)AWXApplePayOptions"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"autoCapture"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"autoSaveCardForFuturePayments"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"billing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWXPlaceDetails","preciseIdentifier":"c:objc(cs)AWXPlaceDetails"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"hidePaymentConsents"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"lang"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"paymentMethods"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"paymentConsentOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PaymentConsentOptions","preciseIdentifier":"c:@M@Airwallex@objc(cs)PaymentConsentOptions"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"requiredBillingContactFields"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RequiredBillingContactFields","preciseIdentifier":"c:@E@AWXRequiredBillingContactFields"},{"kind":"text","text":", "},{"kind":"externalParam","text":"returnURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentIntent":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent","navigatorTitle":[{"text":"AWXPaymentIntent","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"codeVoice","code":"AWXPaymentIntent"},{"type":"text","text":" includes the information of payment intent."}],"title":"AWXPaymentIntent","url":"\/documentation\/airwallex\/awxpaymentintent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentIntent"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/Session/customerId()":{"type":"topic","url":"\/documentation\/airwallex\/session\/customerid()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"customerId"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"customerId()","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session\/customerId()","role":"symbol","navigatorTitle":[{"text":"customerId","kind":"identifier"}],"abstract":[{"type":"text","text":"Returns the customer ID associated with the current payment intent."}],"kind":"symbol"},"doc://org.cocoapods.Airwallex/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/Session/amount()":{"type":"topic","abstract":[{"text":"Returns the payment amount.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session\/amount()","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"amount"}],"title":"amount()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"amount"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:objc(cs)NSDecimalNumber","kind":"typeIdentifier","text":"NSDecimalNumber"}],"url":"\/documentation\/airwallex\/session\/amount()"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/Session/paymentIntent":{"title":"paymentIntent","type":"topic","url":"\/documentation\/airwallex\/session\/paymentintent","abstract":[{"type":"text","text":"The payment intent to handle."}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentIntent"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AWXPaymentIntent","kind":"typeIdentifier","text":"AWXPaymentIntent"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"paymentIntent"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session\/paymentIntent","role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/Session/paymentConsentOptions":{"title":"paymentConsentOptions","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentConsentOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PaymentConsentOptions","preciseIdentifier":"c:@M@Airwallex@objc(cs)PaymentConsentOptions"},{"kind":"text","text":"?"}],"url":"\/documentation\/airwallex\/session\/paymentconsentoptions","type":"topic","navigatorTitle":[{"kind":"identifier","text":"paymentConsentOptions"}],"abstract":[{"type":"text","text":"Required for recurring payment"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session\/paymentConsentOptions","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXApplePayOptions":{"title":"AWXApplePayOptions","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXApplePayOptions","kind":"identifier"}],"navigatorTitle":[{"text":"AWXApplePayOptions","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Object used to construct PKPaymentRequest for Apple Pay."}],"type":"topic","url":"\/documentation\/airwallex\/awxapplepayoptions"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSession":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXSession"}],"navigatorTitle":[{"text":"AWXSession","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxsession","type":"topic","title":"AWXSession","abstract":[{"code":"AWXSession","type":"codeVoice"},{"type":"text","text":" is the base session."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentConsentOptions":{"navigatorTitle":[{"text":"PaymentConsentOptions","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentConsentOptions","url":"\/documentation\/airwallex\/paymentconsentoptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentConsentOptions"}],"type":"topic","abstract":[{"text":"Options for payment consents","type":"text"}],"title":"PaymentConsentOptions","role":"symbol","kind":"symbol"},"doc://org.cocoapods.Airwallex/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SQ","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/Session/currency()":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session\/currency()","title":"currency()","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Returns the currency code for the current payment."}],"url":"\/documentation\/airwallex\/session\/currency()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"currency","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"currency","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.Airwallex/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://org.cocoapods.Airwallex/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"Session","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"Session","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"Session"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session\/autoCapture","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session\/autoSaveCardForFuturePayments","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session\/paymentConsentOptions","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session\/paymentIntent"],"generated":true},{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session\/amount()","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session\/currency()","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session\/customerId()","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session\/init(paymentIntent:countryCode:applePayOptions:autoCapture:autoSaveCardForFuturePayments:billing:hidePaymentConsents:lang:paymentMethods:paymentConsentOptions:requiredBillingContactFields:returnURL:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session\/paymentIntentId()","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session\/transactionMode()"],"generated":true}],"path":"\/topicSections"},{"op":"replace","value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession"]}],"path":"\/relationshipsSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentConsentOptions","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions"],"title":"Preparation","anchor":"Preparation","generated":true}],"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"Session"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)AWXSession","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession","text":"AWXSession"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"transactionMode","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session~1transactionMode()\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"transactionMode"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session~1transactionMode()\/fragments"},{"op":"replace","value":"autoSaveCardForFuturePayments","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session~1autoSaveCardForFuturePayments\/title"},{"op":"replace","value":[{"text":"autoSaveCardForFuturePayments","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session~1autoSaveCardForFuturePayments\/fragments"},{"op":"replace","value":"Session","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session\/title"},{"op":"replace","value":[{"text":"Session","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"Session"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session\/navigatorTitle"},{"op":"replace","value":"autoCapture","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session~1autoCapture\/title"},{"op":"replace","value":[{"text":"autoCapture","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session~1autoCapture\/fragments"},{"op":"replace","value":"paymentIntentId","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session~1paymentIntentId()\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentIntentId"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session~1paymentIntentId()\/fragments"},{"op":"replace","value":"initWithPaymentIntent:countryCode:applePayOptions:autoCapture:autoSaveCardForFuturePayments:billing:hidePaymentConsents:lang:paymentMethods:paymentConsentOptions:requiredBillingContactFields:returnURL:","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session~1init(paymentIntent:countryCode:applePayOptions:autoCapture:autoSaveCardForFuturePayments:billing:hidePaymentConsents:lang:paymentMethods:paymentConsentOptions:requiredBillingContactFields:returnURL:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithPaymentIntent:countryCode:applePayOptions:autoCapture:autoSaveCardForFuturePayments:billing:hidePaymentConsents:lang:paymentMethods:paymentConsentOptions:requiredBillingContactFields:returnURL:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session~1init(paymentIntent:countryCode:applePayOptions:autoCapture:autoSaveCardForFuturePayments:billing:hidePaymentConsents:lang:paymentMethods:paymentConsentOptions:requiredBillingContactFields:returnURL:)\/fragments"},{"op":"replace","value":"AWXPaymentIntent","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentIntent\/title"},{"op":"replace","value":[{"text":"AWXPaymentIntent","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentIntent\/fragments"},{"op":"replace","value":[{"text":"AWXPaymentIntent","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentIntent\/navigatorTitle"},{"op":"replace","value":"customerId","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session~1customerId()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"customerId","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session~1customerId()\/fragments"},{"op":"replace","value":"amount","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session~1amount()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"amount","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session~1amount()\/fragments"},{"op":"replace","value":"paymentIntent","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session~1paymentIntent\/title"},{"op":"replace","value":[{"text":"paymentIntent","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session~1paymentIntent\/fragments"},{"op":"replace","value":"paymentConsentOptions","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session~1paymentConsentOptions\/title"},{"op":"replace","value":[{"kind":"identifier","text":"paymentConsentOptions"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session~1paymentConsentOptions\/fragments"},{"op":"replace","value":"AWXApplePayOptions","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions\/title"},{"op":"replace","value":[{"text":"AWXApplePayOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions\/fragments"},{"op":"replace","value":[{"text":"AWXApplePayOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions\/navigatorTitle"},{"op":"replace","value":"AWXSession","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/title"},{"op":"replace","value":[{"text":"AWXSession","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AWXSession"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/navigatorTitle"},{"op":"replace","value":"PaymentConsentOptions","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentConsentOptions\/title"},{"op":"replace","value":[{"kind":"identifier","text":"PaymentConsentOptions"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentConsentOptions\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"PaymentConsentOptions"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentConsentOptions\/navigatorTitle"},{"op":"replace","value":"currency","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session~1currency()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"currency","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session~1currency()\/fragments"}]}]}