{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Airwallex"]]},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Airwallex\/disableLocalLogFile()","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/airwallex\/disablelocallogfile()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/airwallex\/disablelocallogfile()"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disableLocalLogFile","kind":"identifier"},{"text":"()","kind":"text"}],"title":"disableLocalLogFile()","externalID":"c:objc(cs)Airwallex(cm)disableLocalLogFile","navigatorTitle":[{"kind":"identifier","text":"disableLocalLogFile"}],"roleHeading":"Type Method","symbolKind":"method","modules":[{"name":"Airwallex"}]},"abstract":[{"type":"text","text":"Disable local log file."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disableLocalLogFile","kind":"identifier"},{"text":"()","kind":"text"}]}]}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","abstract":[],"type":"topic","kind":"symbol","title":"Airwallex","role":"collection"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/Airwallex":{"abstract":[{"code":"Airwallex","type":"codeVoice"},{"text":" contains the base configuration the SDK needs.","type":"text"}],"title":"Airwallex","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Airwallex","navigatorTitle":[{"kind":"identifier","text":"Airwallex"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Airwallex"}],"kind":"symbol","url":"\/documentation\/airwallex\/airwallex","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/Airwallex/disableLocalLogFile()":{"type":"topic","title":"disableLocalLogFile()","abstract":[{"type":"text","text":"Disable local log file."}],"url":"\/documentation\/airwallex\/airwallex\/disablelocallogfile()","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Airwallex\/disableLocalLogFile()","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"disableLocalLogFile"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableLocalLogFile"},{"kind":"text","text":"()"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"disableLocalLogFile","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"+ ","kind":"text"},{"text":"disableLocalLogFile","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"disableLocalLogFile","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"Airwallex","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Airwallex\/title"},{"value":[{"text":"Airwallex","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Airwallex\/fragments"},{"value":[{"text":"Airwallex","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Airwallex\/navigatorTitle"},{"value":"disableLocalLogFile","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Airwallex~1disableLocalLogFile()\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"disableLocalLogFile","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Airwallex~1disableLocalLogFile()\/fragments"}]}]}