{"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Airwallex"]]},"variants":[{"paths":["\/documentation\/airwallex\/airwallex\/setmode(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/airwallex\/setmode(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Airwallex\/setMode(_:)","interfaceLanguage":"swift"},"sections":[],"metadata":{"roleHeading":"Type Method","externalID":"c:objc(cs)Airwallex(cm)setMode:","symbolKind":"method","role":"symbol","title":"setMode(_:)","modules":[{"name":"Airwallex"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMode"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AirwallexSDKMode","preciseIdentifier":"c:@E@AirwallexSDKMode"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"setMode:","kind":"identifier"}]},"kind":"symbol","abstract":[{"text":"Set sdk mode.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"mode"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexSDKMode","preciseIdentifier":"c:@E@AirwallexSDKMode","kind":"typeIdentifier","text":"AirwallexSDKMode"},{"kind":"text","text":")"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"mode","content":[{"type":"paragraph","inlineContent":[{"text":"A mode required.","type":"text"}]}]}]}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/Airwallex/setMode(_:)":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMode"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@AirwallexSDKMode","kind":"typeIdentifier","text":"AirwallexSDKMode"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"setMode:"}],"type":"topic","abstract":[{"text":"Set sdk mode.","type":"text"}],"role":"symbol","title":"setMode(_:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Airwallex\/setMode(_:)","url":"\/documentation\/airwallex\/airwallex\/setmode(_:)"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexSDKMode":{"role":"symbol","url":"\/documentation\/airwallex\/airwallexsdkmode","type":"topic","kind":"symbol","abstract":[],"title":"AirwallexSDKMode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AirwallexSDKMode","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexSDKMode","navigatorTitle":[{"text":"AirwallexSDKMode","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","role":"collection","title":"Airwallex","url":"\/documentation\/airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/Airwallex":{"abstract":[{"type":"codeVoice","code":"Airwallex"},{"type":"text","text":" contains the base configuration the SDK needs."}],"title":"Airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Airwallex","role":"symbol","kind":"symbol","url":"\/documentation\/airwallex\/airwallex","navigatorTitle":[{"kind":"identifier","text":"Airwallex"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Airwallex","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","value":"setMode:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setMode:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"setMode:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AirwallexSDKMode","preciseIdentifier":"c:@E@AirwallexSDKMode","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexSDKMode"},{"text":") ","kind":"text"},{"text":"mode","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"mode","content":[{"type":"paragraph","inlineContent":[{"text":"A mode required.","type":"text"}]}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Airwallex~1setMode(_:)\/title","value":"setMode:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Airwallex~1setMode(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"setMode:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexSDKMode\/title","value":"AirwallexSDKMode","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexSDKMode\/fragments","value":[{"text":"AirwallexSDKMode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexSDKMode\/navigatorTitle","value":[{"text":"AirwallexSDKMode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Airwallex\/title","value":"Airwallex","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Airwallex\/fragments","value":[{"kind":"identifier","text":"Airwallex"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Airwallex\/navigatorTitle","value":[{"kind":"identifier","text":"Airwallex"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}