{"metadata":{"role":"symbol","externalID":"c:objc(cs)AWXApplePayProvider(im)startPayment","roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"Airwallex"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startPayment","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"startPayment","kind":"identifier"}],"title":"startPayment()"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxapplepayprovider\/startpayment()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxapplepayprovider\/startpayment()"]}],"abstract":[{"text":"Launch Apple Pay sheet to confirm the payment intent.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startPayment"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayProvider\/startPayment()"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayProvider"]]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXApplePayProvider":{"navigatorTitle":[{"text":"AWXApplePayProvider","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxapplepayprovider","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXApplePayProvider","kind":"identifier"}],"title":"AWXApplePayProvider","kind":"symbol","abstract":[{"type":"codeVoice","code":"AWXApplePayProvider"},{"type":"text","text":" is a provider to handle payment method with Apple Pay."}],"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayProvider"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXApplePayProvider/startPayment()":{"url":"\/documentation\/airwallex\/awxapplepayprovider\/startpayment()","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startPayment"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"startPayment","kind":"identifier"}],"type":"topic","abstract":[{"text":"Launch Apple Pay sheet to confirm the payment intent.","type":"text"}],"role":"symbol","title":"startPayment()","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayProvider\/startPayment()"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","role":"collection","title":"Airwallex","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"startPayment"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startPayment"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"startPayment","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayProvider\/title","value":"AWXApplePayProvider"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayProvider\/fragments","value":[{"text":"AWXApplePayProvider","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayProvider\/navigatorTitle","value":[{"text":"AWXApplePayProvider","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayProvider~1startPayment()\/title","value":"startPayment"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayProvider~1startPayment()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"startPayment","kind":"identifier"}]}]}]}