{"metadata":{"fragments":[{"text":"+ ","kind":"text"},{"text":"brandWithName:rangeStart:rangeEnd:length:type:","kind":"identifier"}],"externalID":"c:objc(cs)AWXBrand(cm)brandWithName:rangeStart:rangeEnd:length:type:","navigatorTitle":[{"kind":"identifier","text":"brandWithName:rangeStart:rangeEnd:length:type:"}],"modules":[{"name":"Airwallex"}],"role":"symbol","roleHeading":"Type Method","symbolKind":"method","title":"brandWithName:rangeStart:rangeEnd:length:type:"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxbrand\/brandwithname:rangestart:rangeend:length:type:"]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"brandWithName:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"name","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"rangeStart:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"rangeStart","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"rangeEnd:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"rangeEnd","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"length:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"length","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"type:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AWXBrandType","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrandType","preciseIdentifier":"c:@E@AWXBrandType"},{"text":") ","kind":"text"},{"text":"type","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrand"]]},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrand\/brandWithName:rangeStart:rangeEnd:length:type:","interfaceLanguage":"occ"},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXBrand":{"url":"\/documentation\/airwallex\/awxbrand","title":"AWXBrand","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXBrand"}],"abstract":[{"type":"codeVoice","code":"AWXBrand"},{"type":"text","text":" manages the card scheme brand."}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrand","navigatorTitle":[{"kind":"identifier","text":"AWXBrand"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXBrandType":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXBrandType","kind":"identifier"}],"type":"topic","abstract":[],"url":"\/documentation\/airwallex\/awxbrandtype","navigatorTitle":[{"text":"AWXBrandType","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrandType","title":"AWXBrandType"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","url":"\/documentation\/airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","kind":"symbol","role":"collection","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXBrand/brandWithName:rangeStart:rangeEnd:length:type:":{"role":"symbol","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrand\/brandWithName:rangeStart:rangeEnd:length:type:","title":"brandWithName:rangeStart:rangeEnd:length:type:","fragments":[{"text":"+ ","kind":"text"},{"text":"brandWithName:rangeStart:rangeEnd:length:type:","kind":"identifier"}],"navigatorTitle":[{"text":"brandWithName:rangeStart:rangeEnd:length:type:","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxbrand\/brandwithname:rangestart:rangeend:length:type:","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"AWXBrand","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrand\/title","op":"replace"},{"value":[{"text":"AWXBrand","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrand\/fragments","op":"replace"},{"value":[{"text":"AWXBrand","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrand\/navigatorTitle","op":"replace"},{"value":"AWXBrandType","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrandType\/title","op":"replace"},{"value":[{"text":"AWXBrandType","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrandType\/fragments","op":"replace"},{"value":[{"text":"AWXBrandType","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrandType\/navigatorTitle","op":"replace"}]}]}