{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentConsentOptions"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/airwallex\/paymentconsentoptions\/merchanttriggerreason"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/paymentconsentoptions\/merchanttriggerreason"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@Airwallex@objc(cs)PaymentConsentOptions(py)merchantTriggerReason","title":"merchantTriggerReason","roleHeading":"Instance Property","modules":[{"name":"Airwallex"}],"symbolKind":"property","navigatorTitle":[{"text":"merchantTriggerReason","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"merchantTriggerReason","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AirwallexMerchantTriggerReason","preciseIdentifier":"c:@E@AirwallexMerchantTriggerReason","kind":"typeIdentifier"}],"role":"symbol"},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentConsentOptions\/merchantTriggerReason"},"sections":[],"abstract":[{"text":"indicate whether the subsequent payments are scheduled.","type":"text"},{"text":" ","type":"text"},{"text":"Only applicable when next_triggered_by is merchant. One of ","type":"text"},{"type":"codeVoice","code":".undefined"},{"text":", ","type":"text"},{"type":"codeVoice","code":"scheduled"},{"text":", ","type":"text"},{"type":"codeVoice","code":"unscheduled"},{"text":", ","type":"text"},{"type":"codeVoice","code":"installments"},{"text":". Default: ","type":"text"},{"code":".undefined","type":"codeVoice"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"merchantTriggerReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexMerchantTriggerReason","text":"AirwallexMerchantTriggerReason","preciseIdentifier":"c:@E@AirwallexMerchantTriggerReason"}]}]}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexMerchantTriggerReason":{"title":"AirwallexMerchantTriggerReason","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexMerchantTriggerReason","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AirwallexMerchantTriggerReason"}],"navigatorTitle":[{"text":"AirwallexMerchantTriggerReason","kind":"identifier"}],"kind":"symbol","abstract":[],"url":"\/documentation\/airwallex\/airwallexmerchanttriggerreason"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentConsentOptions":{"abstract":[{"text":"Options for payment consents","type":"text"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentConsentOptions","type":"topic","url":"\/documentation\/airwallex\/paymentconsentoptions","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PaymentConsentOptions","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"PaymentConsentOptions","kind":"identifier"}],"title":"PaymentConsentOptions"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentConsentOptions/merchantTriggerReason":{"title":"merchantTriggerReason","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentConsentOptions\/merchantTriggerReason","navigatorTitle":[{"kind":"identifier","text":"merchantTriggerReason"}],"type":"topic","abstract":[{"type":"text","text":"indicate whether the subsequent payments are scheduled."},{"type":"text","text":" "},{"type":"text","text":"Only applicable when next_triggered_by is merchant. One of "},{"type":"codeVoice","code":".undefined"},{"type":"text","text":", "},{"type":"codeVoice","code":"scheduled"},{"type":"text","text":", "},{"type":"codeVoice","code":"unscheduled"},{"type":"text","text":", "},{"type":"codeVoice","code":"installments"},{"type":"text","text":". Default: "},{"type":"codeVoice","code":".undefined"}],"url":"\/documentation\/airwallex\/paymentconsentoptions\/merchanttriggerreason","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"merchantTriggerReason","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AirwallexMerchantTriggerReason","preciseIdentifier":"c:@E@AirwallexMerchantTriggerReason","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","abstract":[],"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/airwallex"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"merchantTriggerReason","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"merchantTriggerReason"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@E@AirwallexMerchantTriggerReason","text":"AirwallexMerchantTriggerReason","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexMerchantTriggerReason"},{"text":" ","kind":"text"},{"text":"merchantTriggerReason","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"AirwallexMerchantTriggerReason","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexMerchantTriggerReason\/title"},{"op":"replace","value":[{"text":"AirwallexMerchantTriggerReason","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexMerchantTriggerReason\/fragments"},{"op":"replace","value":[{"text":"AirwallexMerchantTriggerReason","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexMerchantTriggerReason\/navigatorTitle"},{"op":"replace","value":"PaymentConsentOptions","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentConsentOptions\/title"},{"op":"replace","value":[{"text":"PaymentConsentOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentConsentOptions\/fragments"},{"op":"replace","value":[{"text":"PaymentConsentOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentConsentOptions\/navigatorTitle"},{"op":"replace","value":"merchantTriggerReason","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentConsentOptions~1merchantTriggerReason\/title"},{"op":"replace","value":[{"text":"merchantTriggerReason","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentConsentOptions~1merchantTriggerReason\/fragments"}]}]}