{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentConsentOptions\/AWXJSONEncodable-Implementations"},"kind":"article","metadata":{"modules":[{"name":"Airwallex"}],"roleHeading":"API Collection","role":"collectionGroup","title":"AWXJSONEncodable Implementations"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentConsentOptions"]]},"topicSections":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentConsentOptions\/encodeToJSON()"],"anchor":"Instance-Methods"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/paymentconsentoptions\/awxjsonencodable-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/paymentconsentoptions\/awxjsonencodable-implementations"]}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","url":"\/documentation\/airwallex","role":"collection","kind":"symbol","abstract":[],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentConsentOptions/encodeToJSON()":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"encodeToJSON","kind":"identifier"}],"abstract":[],"url":"\/documentation\/airwallex\/paymentconsentoptions\/encodetojson()","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentConsentOptions\/encodeToJSON()","title":"encodeToJSON()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"encodeToJSON","kind":"identifier"},{"text":"() -> [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentConsentOptions":{"abstract":[{"text":"Options for payment consents","type":"text"}],"title":"PaymentConsentOptions","type":"topic","url":"\/documentation\/airwallex\/paymentconsentoptions","kind":"symbol","navigatorTitle":[{"text":"PaymentConsentOptions","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PaymentConsentOptions","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentConsentOptions"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentConsentOptions\/encodeToJSON()"],"anchor":"Instance-Methods","generated":true}],"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":"encodeToJSON","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentConsentOptions~1encodeToJSON()\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"encodeToJSON"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentConsentOptions~1encodeToJSON()\/fragments","op":"replace"},{"value":"PaymentConsentOptions","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentConsentOptions\/title","op":"replace"},{"value":[{"text":"PaymentConsentOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentConsentOptions\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"PaymentConsentOptions"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentConsentOptions\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}