{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxuicontext\/launchpayment(from:session:paymentresultdelegate:filterby:launchstyle:layout:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxuicontext\/launchpayment(from:session:paymentresultdelegate:filterby:launchstyle:layout:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"symbolKind":"method","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"launchPayment"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"text":"session","kind":"externalParam"},{"kind":"text","text":": "},{"text":"AWXSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXSession"},{"kind":"text","text":", "},{"text":"paymentResultDelegate","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWXPaymentResultDelegate","preciseIdentifier":"c:objc(pl)AWXPaymentResultDelegate"},{"text":", ","kind":"text"},{"text":"filterBy","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?, "},{"text":"launchStyle","kind":"externalParam"},{"kind":"text","text":": "},{"text":"LaunchStyle","preciseIdentifier":"s:9Airwallex12AWXUIContextC11LaunchStyleO","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"layout","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:9Airwallex12AWXUIContextC13PaymentLayoutO","kind":"typeIdentifier","text":"PaymentLayout"},{"kind":"text","text":")"}],"extendedModule":"Airwallex","modules":[{"name":"Airwallex"}],"navigatorTitle":[{"kind":"identifier","text":"launchPaymentFrom:session:paymentResultDelegate:filterBy:launchStyle:layout:"}],"title":"launchPayment(from:session:paymentResultDelegate:filterBy:launchStyle:layout:)","externalID":"c:@CM@Airwallex@objc(cs)AWXUIContext(cm)launchPaymentFrom:session:paymentResultDelegate:filterBy:launchStyle:layout:","roleHeading":"Type Method","role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/launchPayment(from:session:paymentResultDelegate:filterBy:launchStyle:layout:)"},"abstract":[{"type":"text","text":"Launches the Airwallex payment sheet."}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"launchPayment","kind":"identifier"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"hostingVC"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"session","kind":"externalParam"},{"kind":"text","text":": "},{"text":"AWXSession","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession","preciseIdentifier":"c:objc(cs)AWXSession","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"paymentResultDelegate"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentResultDelegate","kind":"typeIdentifier","text":"AWXPaymentResultDelegate","preciseIdentifier":"c:objc(pl)AWXPaymentResultDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"filterBy"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"methodNames"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"]? = nil, ","kind":"text"},{"text":"launchStyle","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/LaunchStyle","kind":"typeIdentifier","text":"LaunchStyle","preciseIdentifier":"s:9Airwallex12AWXUIContextC11LaunchStyleO"},{"text":" = .push, ","kind":"text"},{"kind":"externalParam","text":"layout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/PaymentLayout","text":"PaymentLayout","preciseIdentifier":"s:9Airwallex12AWXUIContextC13PaymentLayoutO"},{"text":" = .tab)","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The view controller that launch the payment sheet","type":"text"}]}],"name":"hostingVC"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The current payment session.","type":"text"}]}],"name":"session"},{"name":"paymentResultDelegate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The delegate responsible for handling the payment result."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"An optional array of payment method names used to filter the payment methods returned by the server."}],"type":"paragraph"}],"name":"methodNames"},{"name":"launchStyle","content":[{"type":"paragraph","inlineContent":[{"text":"The presentation style of the payment sheet. Defaults to ","type":"text"},{"code":".push","type":"codeVoice"},{"type":"text","text":"."}]}]},{"name":"layout","content":[{"inlineContent":[{"type":"text","text":"Layout of payment sheet"}],"type":"paragraph"}]}]}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSession":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AWXSession"}],"abstract":[{"type":"codeVoice","code":"AWXSession"},{"type":"text","text":" is the base session."}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession","url":"\/documentation\/airwallex\/awxsession","role":"symbol","type":"topic","title":"AWXSession","navigatorTitle":[{"kind":"identifier","text":"AWXSession"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXUIContext":{"title":"AWXUIContext","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext","abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXUIContext"}],"url":"\/documentation\/airwallex\/awxuicontext","navigatorTitle":[{"text":"AWXUIContext","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXUIContext/LaunchStyle":{"url":"\/documentation\/airwallex\/awxuicontext\/launchstyle","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"LaunchStyle","kind":"identifier"}],"navigatorTitle":[{"text":"LaunchStyle","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/LaunchStyle","abstract":[],"kind":"symbol","role":"symbol","type":"topic","title":"AWXUIContext.LaunchStyle"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXUIContext/launchPayment(from:session:paymentResultDelegate:filterBy:launchStyle:layout:)":{"type":"topic","role":"symbol","title":"launchPayment(from:session:paymentResultDelegate:filterBy:launchStyle:layout:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"launchPayment","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":", ","kind":"text"},{"text":"session","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AWXSession","preciseIdentifier":"c:objc(cs)AWXSession","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"paymentResultDelegate","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(pl)AWXPaymentResultDelegate","text":"AWXPaymentResultDelegate","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"filterBy","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"]?, ","kind":"text"},{"text":"launchStyle","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:9Airwallex12AWXUIContextC11LaunchStyleO","text":"LaunchStyle","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"layout","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PaymentLayout","preciseIdentifier":"s:9Airwallex12AWXUIContextC13PaymentLayoutO"},{"kind":"text","text":")"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/launchPayment(from:session:paymentResultDelegate:filterBy:launchStyle:layout:)","url":"\/documentation\/airwallex\/awxuicontext\/launchpayment(from:session:paymentresultdelegate:filterby:launchstyle:layout:)","abstract":[{"type":"text","text":"Launches the Airwallex payment sheet."}],"navigatorTitle":[{"kind":"identifier","text":"launchPaymentFrom:session:paymentResultDelegate:filterBy:launchStyle:layout:"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/LaunchStyle":{"role":"symbol","abstract":[],"kind":"symbol","url":"\/documentation\/airwallex\/launchstyle","fragments":[{"kind":"identifier","text":"LaunchStyle"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/LaunchStyle","title":"LaunchStyle"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/airwallex","title":"Airwallex","role":"collection"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentLayout":{"kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentLayout","url":"\/documentation\/airwallex\/paymentlayout","role":"symbol","fragments":[{"text":"PaymentLayout","kind":"identifier"}],"type":"topic","title":"PaymentLayout"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentResultDelegate":{"url":"\/documentation\/airwallex\/awxpaymentresultdelegate","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentResultDelegate","role":"symbol","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentResultDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"AWXPaymentResultDelegate"}],"title":"AWXPaymentResultDelegate"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXUIContext/PaymentLayout":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentLayout"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/PaymentLayout","kind":"symbol","url":"\/documentation\/airwallex\/awxuicontext\/paymentlayout","title":"AWXUIContext.PaymentLayout","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"PaymentLayout"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"value":"launchPaymentFrom:session:paymentResultDelegate:filterBy:launchStyle:layout:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"launchPaymentFrom:session:paymentResultDelegate:filterBy:launchStyle:layout:"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"launchPaymentFrom:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"hostingVC"},{"text":" ","kind":"text"},{"text":"session:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession","text":"AWXSession","preciseIdentifier":"c:objc(cs)AWXSession"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"session"},{"text":" ","kind":"text"},{"text":"paymentResultDelegate:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<AWXPaymentResultDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)AWXPaymentResultDelegate"},{"text":") ","kind":"text"},{"text":"paymentResultDelegate","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"filterBy:"},{"kind":"text","text":"("},{"text":"NSArray<NSString *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"methodNames"},{"kind":"text","text":" "},{"kind":"identifier","text":"launchStyle:"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LaunchStyle","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/LaunchStyle","preciseIdentifier":"c:@M@Airwallex@E@LaunchStyle","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"launchStyle","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"layout:"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentLayout","kind":"typeIdentifier","text":"PaymentLayout","preciseIdentifier":"c:@M@Airwallex@E@PaymentLayout"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"layout"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"hostingVC","content":[{"inlineContent":[{"text":"The view controller that launch the payment sheet","type":"text"}],"type":"paragraph"}]},{"name":"session","content":[{"inlineContent":[{"text":"The current payment session.","type":"text"}],"type":"paragraph"}]},{"name":"paymentResultDelegate","content":[{"type":"paragraph","inlineContent":[{"text":"The delegate responsible for handling the payment result.","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"An optional array of payment method names used to filter the payment methods returned by the server."}],"type":"paragraph"}],"name":"methodNames"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The presentation style of the payment sheet. Defaults to "},{"type":"codeVoice","code":".push"},{"text":".","type":"text"}]}],"name":"launchStyle"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Layout of payment sheet"}]}],"name":"layout"}]},"op":"replace"},{"value":"AWXSession","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/fragments","value":[{"kind":"identifier","text":"AWXSession"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/navigatorTitle","op":"replace","value":[{"text":"AWXSession","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext\/title","value":"AWXUIContext","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext\/fragments","value":[{"kind":"identifier","text":"AWXUIContext"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AWXUIContext"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext~1launchPayment(from:session:paymentResultDelegate:filterBy:launchStyle:layout:)\/title","op":"replace","value":"launchPaymentFrom:session:paymentResultDelegate:filterBy:launchStyle:layout:"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"launchPaymentFrom:session:paymentResultDelegate:filterBy:launchStyle:layout:"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext~1launchPayment(from:session:paymentResultDelegate:filterBy:launchStyle:layout:)\/fragments"},{"value":"AWXPaymentResultDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentResultDelegate\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentResultDelegate\/fragments","value":[{"kind":"identifier","text":"AWXPaymentResultDelegate"}],"op":"replace"},{"value":[{"text":"AWXPaymentResultDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentResultDelegate\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}