{"sections":[],"abstract":[{"text":"Return all of the supported countries.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allCountries","kind":"identifier"},{"text":"() -> [","kind":"text"},{"preciseIdentifier":"c:objc(cs)AWXCountry","text":"AWXCountry","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCountry"},{"text":"]","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCountry\/allCountries()"},"metadata":{"symbolKind":"method","role":"symbol","modules":[{"name":"Airwallex"}],"navigatorTitle":[{"text":"allCountries","kind":"identifier"}],"extendedModule":"Airwallex","roleHeading":"Type Method","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allCountries","kind":"identifier"},{"text":"() -> [","kind":"text"},{"text":"AWXCountry","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXCountry"},{"text":"]","kind":"text"}],"externalID":"c:objc(cs)AWXCountry(cm)allCountries","title":"allCountries()"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCountry"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxcountry\/allcountries()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxcountry\/allcountries()"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCountry":{"kind":"symbol","type":"topic","title":"AWXCountry","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCountry","abstract":[{"code":"AWXCountry","type":"codeVoice"},{"type":"text","text":" includes the information of a country."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXCountry","kind":"identifier"}],"navigatorTitle":[{"text":"AWXCountry","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxcountry"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCountry/allCountries()":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allCountries","kind":"identifier"},{"text":"() -> [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXCountry","text":"AWXCountry"},{"kind":"text","text":"]"}],"abstract":[{"text":"Return all of the supported countries.","type":"text"}],"url":"\/documentation\/airwallex\/awxcountry\/allcountries()","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCountry\/allCountries()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"allCountries"}],"kind":"symbol","title":"allCountries()","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","url":"\/documentation\/airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol","title":"Airwallex","abstract":[],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","value":"allCountries","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"allCountries","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<AWXCountry *>"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"allCountries"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCountry\/title","value":"AWXCountry","op":"replace"},{"value":[{"text":"AWXCountry","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCountry\/fragments"},{"value":[{"kind":"identifier","text":"AWXCountry"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCountry\/navigatorTitle"},{"value":"allCountries","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCountry~1allCountries()\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"allCountries"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCountry~1allCountries()\/fragments"}]}]}