{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"billing","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWXPlaceDetails","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPlaceDetails","preciseIdentifier":"c:objc(cs)AWXPlaceDetails"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxsession\/billing"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxsession\/billing"]}],"abstract":[{"text":"The billing address.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession\/billing","interfaceLanguage":"swift"},"sections":[],"metadata":{"title":"billing","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"billing","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWXPlaceDetails","preciseIdentifier":"c:objc(cs)AWXPlaceDetails","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"text":"billing","kind":"identifier"}],"modules":[{"name":"Airwallex"}],"externalID":"c:objc(cs)AWXSession(py)billing"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession"]]},"kind":"symbol","references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSession/billing":{"url":"\/documentation\/airwallex\/awxsession\/billing","abstract":[{"text":"The billing address.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"billing"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AWXPlaceDetails","kind":"typeIdentifier","text":"AWXPlaceDetails"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession\/billing","type":"topic","navigatorTitle":[{"kind":"identifier","text":"billing"}],"title":"billing","role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"abstract":[],"type":"topic","url":"\/documentation\/airwallex","title":"Airwallex","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSession":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXSession"}],"navigatorTitle":[{"kind":"identifier","text":"AWXSession"}],"title":"AWXSession","type":"topic","abstract":[{"code":"AWXSession","type":"codeVoice"},{"text":" is the base session.","type":"text"}],"kind":"symbol","url":"\/documentation\/airwallex\/awxsession"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPlaceDetails":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPlaceDetails"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWXPlaceDetails"}],"title":"AWXPlaceDetails","abstract":[{"type":"codeVoice","code":"AWXPlaceDetails"},{"type":"text","text":" includes the information of a billing address."}],"type":"topic","url":"\/documentation\/airwallex\/awxplacedetails","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPlaceDetails"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"billing"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"billing","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPlaceDetails","text":"AWXPlaceDetails","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPlaceDetails"},{"kind":"text","text":" * "},{"kind":"identifier","text":"billing"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession~1billing\/title","op":"replace","value":"billing"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession~1billing\/fragments","op":"replace","value":[{"kind":"identifier","text":"billing"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/title","op":"replace","value":"AWXSession"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/fragments","op":"replace","value":[{"kind":"identifier","text":"AWXSession"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/navigatorTitle","op":"replace","value":[{"text":"AWXSession","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPlaceDetails\/title","op":"replace","value":"AWXPlaceDetails"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPlaceDetails\/fragments","op":"replace","value":[{"text":"AWXPlaceDetails","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPlaceDetails\/navigatorTitle","op":"replace","value":[{"text":"AWXPlaceDetails","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}