{"abstract":[{"type":"text","text":"Return all of customer payment methods"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxsession\/customerpaymentmethods()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxsession\/customerpaymentmethods()"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"customerPaymentMethods"},{"kind":"text","text":"() -> ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"languages":["swift"]}]}],"metadata":{"title":"customerPaymentMethods()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"customerPaymentMethods"},{"kind":"text","text":"() -> ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"roleHeading":"Instance Method","modules":[{"name":"Airwallex"}],"externalID":"c:objc(cs)AWXSession(im)customerPaymentMethods","extendedModule":"Airwallex","role":"symbol","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"customerPaymentMethods"}],"platforms":[{"unavailable":false,"beta":false,"deprecated":true}]},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession\/customerPaymentMethods()","interfaceLanguage":"swift"},"sections":[],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/airwallex","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSession":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXSession"}],"navigatorTitle":[{"text":"AWXSession","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxsession","type":"topic","title":"AWXSession","abstract":[{"code":"AWXSession","type":"codeVoice"},{"type":"text","text":" is the base session."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSession/customerPaymentMethods()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"customerPaymentMethods"},{"kind":"text","text":"() -> ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession\/customerPaymentMethods()","url":"\/documentation\/airwallex\/awxsession\/customerpaymentmethods()","role":"symbol","type":"topic","kind":"symbol","deprecated":true,"title":"customerPaymentMethods()","navigatorTitle":[{"kind":"identifier","text":"customerPaymentMethods"}],"abstract":[{"text":"Return all of customer payment methods","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[{"deprecated":true,"beta":false,"unavailable":false}]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"customerPaymentMethods"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"customerPaymentMethods","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"NSArray","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"customerPaymentMethods","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/title","value":"AWXSession","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/fragments","value":[{"kind":"identifier","text":"AWXSession"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/navigatorTitle","value":[{"text":"AWXSession","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession~1customerPaymentMethods()\/title","value":"customerPaymentMethods","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession~1customerPaymentMethods()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"customerPaymentMethods"}],"op":"replace"}]}]}