{"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"glyphColor"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/airwallex\/awxtheme\/glyphcolor()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxtheme\/glyphcolor()"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme"]]},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"glyphColor","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"roleHeading":"Instance Method","symbolKind":"method","role":"symbol","title":"glyphColor()","modules":[{"name":"Airwallex"}],"navigatorTitle":[{"kind":"identifier","text":"glyphColor"}],"externalID":"c:objc(cs)AWXTheme(im)glyphColor"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme\/glyphColor()"},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXTheme":{"role":"symbol","type":"topic","title":"AWXTheme","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXTheme"}],"navigatorTitle":[{"kind":"identifier","text":"AWXTheme"}],"kind":"symbol","abstract":[{"type":"codeVoice","code":"AWXTheme"},{"type":"text","text":" manages text styles."}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme","url":"\/documentation\/airwallex\/awxtheme"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXTheme/glyphColor()":{"type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"text":"glyphColor","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme\/glyphColor()","title":"glyphColor()","url":"\/documentation\/airwallex\/awxtheme\/glyphcolor()","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"glyphColor","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","url":"\/documentation\/airwallex","abstract":[],"title":"Airwallex"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"glyphColor"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"glyphColor","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"glyphColor"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTheme\/title","value":"AWXTheme"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTheme\/fragments","value":[{"text":"AWXTheme","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTheme\/navigatorTitle","value":[{"text":"AWXTheme","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTheme~1glyphColor()\/title","value":"glyphColor"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTheme~1glyphColor()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"glyphColor","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}