{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"didCompleteWith"},{"kind":"text","text":" "},{"kind":"internalParam","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexPaymentStatus","preciseIdentifier":"c:@E@AirwallexPaymentStatus","text":"AirwallexPaymentStatus"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")?)"}]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The controller handling payment result. Could be nil for low level API integration or when user dismiss the payment view controller.","type":"text"}]}],"name":"controller"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The status of checkout result.","type":"text"}]}],"name":"status"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The error if checkout failed.","type":"text"}]}],"name":"error"}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentResultDelegate"]]},"metadata":{"navigatorTitle":[{"text":"paymentViewController:didCompleteWithStatus:error:","kind":"identifier"}],"externalID":"c:objc(pl)AWXPaymentResultDelegate(im)paymentViewController:didCompleteWithStatus:error:","symbolKind":"method","platforms":[{"name":"iOS","unavailable":false,"beta":false,"deprecated":false,"introducedAt":"2.0"},{"name":"iPadOS","unavailable":false,"beta":false,"deprecated":false,"introducedAt":"2.0"},{"name":"Mac Catalyst","unavailable":false,"beta":false,"deprecated":false,"introducedAt":"2.0"}],"modules":[{"name":"Airwallex"}],"roleHeading":"Instance Method","role":"symbol","required":true,"title":"paymentViewController(_:didCompleteWith:error:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":"?, ","kind":"text"},{"text":"didCompleteWith","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AirwallexPaymentStatus","kind":"typeIdentifier","preciseIdentifier":"c:@E@AirwallexPaymentStatus"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": (any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?)","kind":"text"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentResultDelegate\/paymentViewController(_:didCompleteWith:error:)"},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxpaymentresultdelegate\/paymentviewcontroller(_:didcompletewith:error:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxpaymentresultdelegate\/paymentviewcontroller(_:didcompletewith:error:)"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"This method is called when the user has completed the checkout.","type":"text"}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentResultDelegate":{"url":"\/documentation\/airwallex\/awxpaymentresultdelegate","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AWXPaymentResultDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentResultDelegate"}],"role":"symbol","title":"AWXPaymentResultDelegate","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentResultDelegate","kind":"symbol","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexPaymentStatus":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexPaymentStatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AirwallexPaymentStatus","kind":"identifier"}],"type":"topic","url":"\/documentation\/airwallex\/airwallexpaymentstatus","role":"symbol","navigatorTitle":[{"text":"AirwallexPaymentStatus","kind":"identifier"}],"kind":"symbol","abstract":[],"title":"AirwallexPaymentStatus"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentResultDelegate/paymentViewController(_:didCompleteWith:error:)":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentResultDelegate\/paymentViewController(_:didCompleteWith:error:)","type":"topic","title":"paymentViewController(_:didCompleteWith:error:)","kind":"symbol","abstract":[{"type":"text","text":"This method is called when the user has completed the checkout."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"?, "},{"text":"didCompleteWith","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AirwallexPaymentStatus","kind":"typeIdentifier","preciseIdentifier":"c:@E@AirwallexPaymentStatus"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"error"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":")?)","kind":"text"}],"required":true,"navigatorTitle":[{"text":"paymentViewController:didCompleteWithStatus:error:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/airwallex\/awxpaymentresultdelegate\/paymentviewcontroller(_:didcompletewith:error:)"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","type":"topic","role":"collection","title":"Airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"paymentViewController:didCompleteWithStatus:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentViewController:didCompleteWithStatus:error:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"paymentViewController:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":" *) ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didCompleteWithStatus:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexPaymentStatus","text":"AirwallexPaymentStatus","kind":"typeIdentifier","preciseIdentifier":"c:@E@AirwallexPaymentStatus"},{"text":") ","kind":"text"},{"text":"status","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The controller handling payment result. Could be nil for low level API integration or when user dismiss the payment view controller."}]}],"name":"controller"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The status of checkout result."}]}],"name":"status"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The error if checkout failed."}]}],"name":"error"}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentResultDelegate\/title","value":"AWXPaymentResultDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentResultDelegate\/fragments","value":[{"kind":"identifier","text":"AWXPaymentResultDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentResultDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"AWXPaymentResultDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexPaymentStatus\/title","value":"AirwallexPaymentStatus"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexPaymentStatus\/fragments","value":[{"kind":"identifier","text":"AirwallexPaymentStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexPaymentStatus\/navigatorTitle","value":[{"kind":"identifier","text":"AirwallexPaymentStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentResultDelegate~1paymentViewController(_:didCompleteWith:error:)\/title","value":"paymentViewController:didCompleteWithStatus:error:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentResultDelegate~1paymentViewController(_:didCompleteWith:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentViewController:didCompleteWithStatus:error:"}]}]}]}