{"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentFormViewControllerDelegate\/paymentFormViewController(_:didUpdate:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentFormViewControllerDelegate"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxpaymentformviewcontrollerdelegate\/paymentformviewcontroller(_:didupdate:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxpaymentformviewcontrollerdelegate\/paymentformviewcontroller(_:didupdate:)"]}],"metadata":{"roleHeading":"Instance Method","role":"symbol","title":"paymentFormViewController(_:didUpdate:)","externalID":"c:objc(pl)AWXPaymentFormViewControllerDelegate(im)paymentFormViewController:didUpdatePaymentMethod:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentFormViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AWXPaymentFormViewController","preciseIdentifier":"c:objc(cs)AWXPaymentFormViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didUpdate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AWXPaymentMethod","preciseIdentifier":"c:objc(cs)AWXPaymentMethod","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"Airwallex"}],"navigatorTitle":[{"text":"paymentFormViewController:didUpdatePaymentMethod:","kind":"identifier"}],"symbolKind":"method"},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentFormViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"paymentFormViewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPaymentFormViewController","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentFormViewController","text":"AWXPaymentFormViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdate"},{"kind":"text","text":" "},{"kind":"internalParam","text":"paymentMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPaymentMethod","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod","text":"AWXPaymentMethod"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentFormViewControllerDelegate/paymentFormViewController(_:didUpdate:)":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentFormViewControllerDelegate\/paymentFormViewController(_:didUpdate:)","abstract":[],"title":"paymentFormViewController(_:didUpdate:)","url":"\/documentation\/airwallex\/awxpaymentformviewcontrollerdelegate\/paymentformviewcontroller(_:didupdate:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentFormViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AWXPaymentFormViewController","preciseIdentifier":"c:objc(cs)AWXPaymentFormViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didUpdate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AWXPaymentMethod","preciseIdentifier":"c:objc(cs)AWXPaymentMethod","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"paymentFormViewController:didUpdatePaymentMethod:","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentFormViewController":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentFormViewController","abstract":[{"code":"AWXPaymentFormViewController","type":"codeVoice"},{"type":"text","text":" handles payment form."}],"title":"AWXPaymentFormViewController","url":"\/documentation\/airwallex\/awxpaymentformviewcontroller","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPaymentFormViewController","kind":"identifier"}],"navigatorTitle":[{"text":"AWXPaymentFormViewController","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentFormViewControllerDelegate":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentFormViewControllerDelegate","kind":"symbol","title":"AWXPaymentFormViewControllerDelegate","url":"\/documentation\/airwallex\/awxpaymentformviewcontrollerdelegate","abstract":[{"text":"A delegate handles payment form result.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentFormViewControllerDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"AWXPaymentFormViewControllerDelegate"}],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentMethod":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod","kind":"symbol","url":"\/documentation\/airwallex\/awxpaymentmethod","title":"AWXPaymentMethod","abstract":[{"type":"codeVoice","code":"AWXPaymentMethod"},{"type":"text","text":" includes the information of a payment method."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPaymentMethod","kind":"identifier"}],"navigatorTitle":[{"text":"AWXPaymentMethod","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","title":"Airwallex","abstract":[],"type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"paymentFormViewController:didUpdatePaymentMethod:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"paymentFormViewController:didUpdatePaymentMethod:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"paymentFormViewController:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AWXPaymentFormViewController","preciseIdentifier":"c:objc(cs)AWXPaymentFormViewController","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentFormViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"paymentFormViewController","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didUpdatePaymentMethod:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AWXPaymentMethod","preciseIdentifier":"c:objc(cs)AWXPaymentMethod","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"paymentMethod","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"paymentFormViewController:didUpdatePaymentMethod:","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentFormViewControllerDelegate~1paymentFormViewController(_:didUpdate:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"paymentFormViewController:didUpdatePaymentMethod:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentFormViewControllerDelegate~1paymentFormViewController(_:didUpdate:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentFormViewController\/title","value":"AWXPaymentFormViewController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentFormViewController\/fragments","value":[{"kind":"identifier","text":"AWXPaymentFormViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentFormViewController\/navigatorTitle","value":[{"kind":"identifier","text":"AWXPaymentFormViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentFormViewControllerDelegate\/title","value":"AWXPaymentFormViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentFormViewControllerDelegate\/fragments","value":[{"text":"AWXPaymentFormViewControllerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentFormViewControllerDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"AWXPaymentFormViewControllerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethod\/title","value":"AWXPaymentMethod"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethod\/fragments","value":[{"text":"AWXPaymentMethod","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethod\/navigatorTitle","value":[{"kind":"identifier","text":"AWXPaymentMethod"}]}]}]}