{"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Initializer."}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAPIErrorResponse\/init(message:code:)","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"code","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Error message."}]}],"name":"message"},{"content":[{"inlineContent":[{"text":"Error code.","type":"text"}],"type":"paragraph"}],"name":"code"}]},{"content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The initialized error object."}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxapierrorresponse\/init(message:code:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxapierrorresponse\/init(message:code:)"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAPIErrorResponse"]]},"metadata":{"title":"init(message:code:)","symbolKind":"init","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"code","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"c:objc(cs)AWXAPIErrorResponse(im)initWithMessage:code:","navigatorTitle":[{"kind":"identifier","text":"initWithMessage:code:"}],"modules":[{"name":"Airwallex"}],"roleHeading":"Initializer"},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"abstract":[],"url":"\/documentation\/airwallex","role":"collection","title":"Airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","type":"topic","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXAPIErrorResponse/init(message:code:)":{"title":"init(message:code:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"code","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAPIErrorResponse\/init(message:code:)","abstract":[{"type":"text","text":"Initializer."}],"role":"symbol","navigatorTitle":[{"text":"initWithMessage:code:","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxapierrorresponse\/init(message:code:)"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXAPIErrorResponse":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXAPIErrorResponse","kind":"identifier"}],"title":"AWXAPIErrorResponse","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAPIErrorResponse","abstract":[{"text":"An ","type":"text"},{"code":"AWXAPIErrorResponse","type":"codeVoice"},{"text":" includes error details.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"AWXAPIErrorResponse","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxapierrorresponse","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"initWithMessage:code:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMessage:code:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithMessage:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"message","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"code:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"code","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Error message."}],"type":"paragraph"}],"name":"message"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Error code."}]}],"name":"code"}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"value":{"kind":"content","content":[{"text":"Return Value","level":2,"anchor":"return-value","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"The initialized error object.","type":"text"}]}]},"path":"\/primaryContentSections\/2","op":"replace"},{"value":"initWithMessage:code:","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIErrorResponse~1init(message:code:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithMessage:code:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIErrorResponse~1init(message:code:)\/fragments","op":"replace"},{"value":"AWXAPIErrorResponse","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIErrorResponse\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AWXAPIErrorResponse"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIErrorResponse\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AWXAPIErrorResponse"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIErrorResponse\/navigatorTitle","op":"replace"}]}]}