{"metadata":{"roleHeading":"API Collection","role":"collectionGroup","modules":[{"name":"Airwallex"}],"title":"AWXPaymentResultDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxpaymentelement\/awxpaymentresultdelegate-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxpaymentelement\/awxpaymentresultdelegate-implementations"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"article","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/AWXPaymentResultDelegate-Implementations"},"topicSections":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/paymentViewController(_:didCompleteWith:error:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/paymentViewController(_:didCompleteWithPaymentConsentId:)"],"title":"Instance Methods","anchor":"Instance-Methods"}],"sections":[],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","type":"topic","role":"collection","title":"Airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement":{"title":"AWXPaymentElement","navigatorTitle":[{"text":"AWXPaymentElement","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxpaymentelement","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement","role":"symbol","abstract":[{"text":"An embeddable payment element that can be added to any view hierarchy.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPaymentElement","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement/paymentViewController(_:didCompleteWithPaymentConsentId:)":{"navigatorTitle":[{"kind":"identifier","text":"paymentViewController:didCompleteWithPaymentConsentId:"}],"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/paymentViewController(_:didCompleteWithPaymentConsentId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"didCompleteWithPaymentConsentId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"abstract":[],"kind":"symbol","url":"\/documentation\/airwallex\/awxpaymentelement\/paymentviewcontroller(_:didcompletewithpaymentconsentid:)","title":"paymentViewController(_:didCompleteWithPaymentConsentId:)"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement/paymentViewController(_:didCompleteWith:error:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"didCompleteWith","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AirwallexPaymentStatus","preciseIdentifier":"c:@E@AirwallexPaymentStatus","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/paymentViewController(_:didCompleteWith:error:)","title":"paymentViewController(_:didCompleteWith:error:)","role":"symbol","url":"\/documentation\/airwallex\/awxpaymentelement\/paymentviewcontroller(_:didcompletewith:error:)","navigatorTitle":[{"kind":"identifier","text":"paymentViewController:didCompleteWithStatus:error:"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/paymentViewController(_:didCompleteWith:error:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/paymentViewController(_:didCompleteWithPaymentConsentId:)"],"generated":true}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/title","value":"AWXPaymentElement"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/fragments","value":[{"text":"AWXPaymentElement","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/navigatorTitle","value":[{"text":"AWXPaymentElement","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement~1paymentViewController(_:didCompleteWithPaymentConsentId:)\/title","value":"paymentViewController:didCompleteWithPaymentConsentId:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement~1paymentViewController(_:didCompleteWithPaymentConsentId:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"paymentViewController:didCompleteWithPaymentConsentId:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement~1paymentViewController(_:didCompleteWith:error:)\/title","value":"paymentViewController:didCompleteWithStatus:error:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement~1paymentViewController(_:didCompleteWith:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentViewController:didCompleteWithStatus:error:"}]}]}]}