{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/create(session:delegate:configuration:)"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"session"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXSession","text":"AWXSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElementDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@Airwallex@objc(pl)AWXPaymentElementDelegate","text":"AWXPaymentElementDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/Configuration","kind":"typeIdentifier","preciseIdentifier":"s:9Airwallex17AWXPaymentElementC13ConfigurationC","text":"Configuration"},{"kind":"text","text":" = Configuration()) "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@Airwallex@objc(cs)AWXPaymentElement","text":"AWXPaymentElement"}],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The payment session containing transaction details.","type":"text"}]}],"name":"session"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The delegate that receives payment lifecycle callbacks.","type":"text"}]}],"name":"delegate"},{"content":[{"inlineContent":[{"type":"text","text":"Configuration options for the payment element."}],"type":"paragraph"}],"name":"configuration"}],"kind":"parameters"},{"content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A configured "},{"code":"AWXPaymentElement","type":"codeVoice"},{"text":" ready to be embedded.","type":"text"}]}],"kind":"content"},{"kind":"content","content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This factory method validates the session, fetches available payment methods,"},{"type":"text","text":" "},{"type":"text","text":"and creates a fully configured payment element."}]},{"type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"code":"AWXUIContext.LaunchError","type":"codeVoice"},{"type":"text","text":" if session validation fails or payment methods cannot be fetched."}]}],"style":"note","name":"Throws"}]}],"metadata":{"modules":[{"name":"Airwallex"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"session"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXSession","text":"AWXSession"},{"kind":"text","text":", "},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AWXPaymentElementDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@Airwallex@objc(pl)AWXPaymentElementDelegate"},{"text":", ","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Configuration","kind":"typeIdentifier","preciseIdentifier":"s:9Airwallex17AWXPaymentElementC13ConfigurationC"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"AWXPaymentElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@Airwallex@objc(cs)AWXPaymentElement"}],"navigatorTitle":[{"text":"createWithSession:delegate:configuration:completionHandler:","kind":"identifier"}],"role":"symbol","externalID":"c:@M@Airwallex@objc(cs)AWXPaymentElement(cm)createWithSession:delegate:configuration:completionHandler:","roleHeading":"Type Method","title":"create(session:delegate:configuration:)","symbolKind":"method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxpaymentelement\/create(session:delegate:configuration:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxpaymentelement\/create(session:delegate:configuration:)"]}],"abstract":[{"text":"Creates an embedded payment element.","type":"text"}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElementDelegate":{"navigatorTitle":[{"text":"AWXPaymentElementDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPaymentElementDelegate","kind":"identifier"}],"title":"AWXPaymentElementDelegate","abstract":[{"type":"text","text":"Delegate protocol for receiving payment events from AWXPaymentElement."}],"kind":"symbol","type":"topic","url":"\/documentation\/airwallex\/awxpaymentelementdelegate","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElementDelegate","role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSession":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWXSession"}],"abstract":[{"type":"codeVoice","code":"AWXSession"},{"type":"text","text":" is the base session."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AWXSession"}],"role":"symbol","type":"topic","url":"\/documentation\/airwallex\/awxsession","title":"AWXSession","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"kind":"symbol","abstract":[],"role":"collection","type":"topic","url":"\/documentation\/airwallex","title":"Airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement/Configuration":{"navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"title":"AWXPaymentElement.Configuration","abstract":[{"text":"Configuration options for the embedded payment element.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/Configuration","url":"\/documentation\/airwallex\/awxpaymentelement\/configuration","role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement":{"navigatorTitle":[{"text":"AWXPaymentElement","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPaymentElement","kind":"identifier"}],"title":"AWXPaymentElement","abstract":[{"text":"An embeddable payment element that can be added to any view hierarchy.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement","url":"\/documentation\/airwallex\/awxpaymentelement","role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElementConfiguration":{"url":"\/documentation\/airwallex\/awxpaymentelementconfiguration","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElementConfiguration","title":"AWXPaymentElementConfiguration","abstract":[{"text":"Configuration options for the embedded payment element.","type":"text"},{"text":" ","type":"text"},{"text":"Use this class to customize the appearance and behavior of the payment element.","type":"text"}],"fragments":[{"text":"AWXPaymentElementConfiguration","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement/create(session:delegate:configuration:)":{"role":"symbol","url":"\/documentation\/airwallex\/awxpaymentelement\/create(session:delegate:configuration:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"session"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWXSession","preciseIdentifier":"c:objc(cs)AWXSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWXPaymentElementDelegate","preciseIdentifier":"c:@M@Airwallex@objc(pl)AWXPaymentElementDelegate"},{"kind":"text","text":", "},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Configuration","preciseIdentifier":"s:9Airwallex17AWXPaymentElementC13ConfigurationC","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"AWXPaymentElement","preciseIdentifier":"c:@M@Airwallex@objc(cs)AWXPaymentElement","kind":"typeIdentifier"}],"title":"create(session:delegate:configuration:)","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/create(session:delegate:configuration:)","navigatorTitle":[{"text":"createWithSession:delegate:configuration:completionHandler:","kind":"identifier"}],"abstract":[{"type":"text","text":"Creates an embedded payment element."}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"createWithSession:delegate:configuration:completionHandler:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"createWithSession:delegate:configuration:completionHandler:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"createWithSession:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)AWXSession","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession","text":"AWXSession","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"session","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"delegate:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<AWXPaymentElementDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@Airwallex@objc(pl)AWXPaymentElementDelegate"},{"kind":"text","text":") "},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":" "},{"kind":"identifier","text":"configuration:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AWXPaymentElementConfiguration","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElementConfiguration","preciseIdentifier":"c:@M@Airwallex@objc(cs)AWXPaymentElementConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"configuration"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completionHandler:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":" (^)("},{"preciseIdentifier":"c:@M@Airwallex@objc(cs)AWXPaymentElement","kind":"typeIdentifier","text":"AWXPaymentElement","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":", "},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completionHandler","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The payment session containing transaction details."}]}],"name":"session"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The delegate that receives payment lifecycle callbacks."}]}],"name":"delegate"},{"content":[{"inlineContent":[{"text":"Configuration options for the payment element.","type":"text"}],"type":"paragraph"}],"name":"configuration"}]},"path":"\/primaryContentSections\/1","op":"replace"},{"value":null,"op":"replace","path":"\/primaryContentSections\/2"},{"value":"AWXPaymentElementDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElementDelegate\/title"},{"value":[{"text":"AWXPaymentElementDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElementDelegate\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElementDelegate\/navigatorTitle","op":"replace","value":[{"text":"AWXPaymentElementDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/title","op":"replace","value":"AWXSession"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/fragments","op":"replace","value":[{"kind":"identifier","text":"AWXSession"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AWXSession"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/title","op":"replace","value":"AWXPaymentElement"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/fragments","op":"replace","value":[{"kind":"identifier","text":"AWXPaymentElement"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AWXPaymentElement"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement~1create(session:delegate:configuration:)\/title","op":"replace","value":"createWithSession:delegate:configuration:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement~1create(session:delegate:configuration:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWithSession:delegate:configuration:completionHandler:"}]}]}]}