{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCountryListViewControllerDelegate","preciseIdentifier":"c:objc(pl)AWXCountryListViewControllerDelegate","text":"AWXCountryListViewControllerDelegate"},{"kind":"text","text":")? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxcountrylistviewcontroller\/delegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxcountrylistviewcontroller\/delegate"]}],"metadata":{"symbolKind":"property","externalID":"c:objc(cs)AWXCountryListViewController(py)delegate","role":"symbol","modules":[{"name":"Airwallex"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)AWXCountryListViewControllerDelegate","text":"AWXCountryListViewControllerDelegate"},{"kind":"text","text":")?"}],"title":"delegate","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCountryListViewController"]]},"abstract":[{"text":"A delegate which handles country selection events.","type":"text"}],"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCountryListViewController\/delegate"},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCountryListViewControllerDelegate":{"abstract":[{"text":"A delegate which handles selected country.","type":"text"}],"url":"\/documentation\/airwallex\/awxcountrylistviewcontrollerdelegate","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCountryListViewControllerDelegate","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXCountryListViewControllerDelegate","kind":"identifier"}],"title":"AWXCountryListViewControllerDelegate","role":"symbol","navigatorTitle":[{"text":"AWXCountryListViewControllerDelegate","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCountryListViewController":{"url":"\/documentation\/airwallex\/awxcountrylistviewcontroller","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXCountryListViewController","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"AWXCountryListViewController","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCountryListViewController","abstract":[{"code":"AWXCountryListViewController","type":"codeVoice"},{"text":" includes a list of countries.","type":"text"}],"title":"AWXCountryListViewController"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","abstract":[],"role":"collection","url":"\/documentation\/airwallex","title":"Airwallex","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCountryListViewController/delegate":{"abstract":[{"text":"A delegate which handles country selection events.","type":"text"}],"url":"\/documentation\/airwallex\/awxcountrylistviewcontroller\/delegate","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCountryListViewController\/delegate","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)AWXCountryListViewControllerDelegate","text":"AWXCountryListViewControllerDelegate","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"title":"delegate","role":"symbol","navigatorTitle":[{"text":"delegate","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"delegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"id<AWXCountryListViewControllerDelegate>","preciseIdentifier":"c:Qoobjc(pl)AWXCountryListViewControllerDelegate"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCountryListViewControllerDelegate\/title","value":"AWXCountryListViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCountryListViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"AWXCountryListViewControllerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCountryListViewControllerDelegate\/navigatorTitle","value":[{"text":"AWXCountryListViewControllerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCountryListViewController\/title","value":"AWXCountryListViewController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCountryListViewController\/fragments","value":[{"kind":"identifier","text":"AWXCountryListViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCountryListViewController\/navigatorTitle","value":[{"text":"AWXCountryListViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCountryListViewController~1delegate\/title","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCountryListViewController~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}]}]}]}