{"topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAddress\/city","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAddress\/countryCode","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAddress\/isComplete","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAddress\/postcode","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAddress\/state","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAddress\/street"],"generated":true}],"kind":"symbol","abstract":[{"type":"codeVoice","code":"AWXAddress"},{"type":"text","text":" includes the information of an address."}],"variants":[{"paths":["\/documentation\/airwallex\/awxaddress"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxaddress"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAddress"},"metadata":{"externalID":"c:objc(cs)AWXAddress","navigatorTitle":[{"text":"AWXAddress","kind":"identifier"}],"modules":[{"name":"Airwallex"}],"role":"symbol","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXAddress","kind":"identifier"}],"title":"AWXAddress","roleHeading":"Class"},"schemaVersion":{"patch":0,"major":0,"minor":3},"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"]},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONDecodable","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONEncodable","doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSCopying","doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/SQ","doc:\/\/org.cocoapods.Airwallex\/SH"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXAddress"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://org.cocoapods.Airwallex/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXAddress/countryCode":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"countryCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"countryCode","abstract":[{"text":"Country code of the address. Use the two-character ISO Standard Country Codes.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"countryCode"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAddress\/countryCode","role":"symbol","url":"\/documentation\/airwallex\/awxaddress\/countrycode"},"doc://org.cocoapods.Airwallex/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","kind":"symbol","url":"\/documentation\/airwallex","abstract":[],"title":"Airwallex","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXJSONEncodable":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONEncodable","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"AWXJSONEncodable"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXJSONEncodable"}],"url":"\/documentation\/airwallex\/awxjsonencodable","kind":"symbol","title":"AWXJSONEncodable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXAddress/postcode":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAddress\/postcode","title":"postcode","url":"\/documentation\/airwallex\/awxaddress\/postcode","abstract":[{"type":"text","text":"Postcode of the address."}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"postcode","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"postcode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXAddress/isComplete":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isComplete","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/airwallex\/awxaddress\/iscomplete","abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAddress\/isComplete","title":"isComplete"},"doc://org.cocoapods.Airwallex/objc(cs)NSObject":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://org.cocoapods.Airwallex/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SH"},"doc://org.cocoapods.Airwallex/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.Airwallex/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SQ"},"doc://org.cocoapods.Airwallex/objc(pl)NSCopying":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSCopying","type":"unresolvable","title":"NSCopying"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXAddress/state":{"kind":"symbol","type":"topic","navigatorTitle":[{"text":"state","kind":"identifier"}],"title":"state","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAddress\/state","url":"\/documentation\/airwallex\/awxaddress\/state","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"state","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"text":"State or province of the address.","type":"text"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXAddress/city":{"kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"text","text":"City of the address."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"city","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"city","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAddress\/city","url":"\/documentation\/airwallex\/awxaddress\/city","title":"city"},"doc://org.cocoapods.Airwallex/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXJSONDecodable":{"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONDecodable","title":"AWXJSONDecodable","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXJSONDecodable"}],"navigatorTitle":[{"kind":"identifier","text":"AWXJSONDecodable"}],"url":"\/documentation\/airwallex\/awxjsondecodable","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXAddress":{"title":"AWXAddress","role":"symbol","abstract":[{"code":"AWXAddress","type":"codeVoice"},{"text":" includes the information of an address.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAddress","url":"\/documentation\/airwallex\/awxaddress","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXAddress","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"AWXAddress","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXAddress/street":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAddress\/street","role":"symbol","navigatorTitle":[{"text":"street","kind":"identifier"}],"title":"street","url":"\/documentation\/airwallex\/awxaddress\/street","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"street","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Street of the address."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"AWXAddress","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"AWXAddress","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"AWXAddress","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAddress\/city","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAddress\/countryCode","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAddress\/postcode","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAddress\/state","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAddress\/street"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"]},{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONDecodable","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONEncodable","doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSCopying"]}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXAddress"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAddress~1countryCode\/title","value":"countryCode"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAddress~1countryCode\/fragments","value":[{"kind":"identifier","text":"countryCode"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONEncodable\/title","value":"AWXJSONEncodable"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONEncodable\/fragments","value":[{"text":"AWXJSONEncodable","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONEncodable\/navigatorTitle","value":[{"text":"AWXJSONEncodable","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAddress~1postcode\/title","value":"postcode"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAddress~1postcode\/fragments","value":[{"kind":"identifier","text":"postcode"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAddress~1state\/title","value":"state"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAddress~1state\/fragments","value":[{"kind":"identifier","text":"state"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAddress~1city\/title","value":"city"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAddress~1city\/fragments","value":[{"text":"city","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONDecodable\/title","value":"AWXJSONDecodable"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONDecodable\/fragments","value":[{"kind":"identifier","text":"AWXJSONDecodable"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONDecodable\/navigatorTitle","value":[{"text":"AWXJSONDecodable","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAddress\/title","value":"AWXAddress"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAddress\/fragments","value":[{"text":"AWXAddress","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAddress\/navigatorTitle","value":[{"text":"AWXAddress","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAddress~1street\/title","value":"street"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAddress~1street\/fragments","value":[{"kind":"identifier","text":"street"}]}]}]}