{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"AWXBrandType"}],"roleHeading":"Enumeration","symbolKind":"enum","role":"symbol","externalID":"c:@E@AWXBrandType","modules":[{"name":"Airwallex"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXBrandType"}],"title":"AWXBrandType"},"sections":[],"topicSections":[{"generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrandType\/JCB","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrandType\/amex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrandType\/dinersClub","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrandType\/discover","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrandType\/mastercard","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrandType\/unionPay","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrandType\/unknown","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrandType\/visa"],"title":"Enumeration Cases"},{"generated":true,"anchor":"Initializers","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrandType\/init(rawValue:)"],"title":"Initializers"},{"generated":true,"anchor":"Type-Properties","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrandType\/allAvailable"],"title":"Type Properties"},{"generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrandType\/Equatable-Implementations","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrandType\/RawRepresentable-Implementations"],"title":"Default Implementations"}],"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.Airwallex\/s15BitwiseCopyableP","doc:\/\/org.cocoapods.Airwallex\/SQ","doc:\/\/org.cocoapods.Airwallex\/SH","doc:\/\/org.cocoapods.Airwallex\/SY","doc:\/\/org.cocoapods.Airwallex\/s8SendableP"],"kind":"relationships","type":"conformsTo"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXBrandType"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrandType"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxbrandtype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxbrandtype"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://org.cocoapods.Airwallex/s15BitwiseCopyableP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s15BitwiseCopyableP","title":"Swift.BitwiseCopyable","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXBrandType":{"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrandType","title":"AWXBrandType","navigatorTitle":[{"kind":"identifier","text":"AWXBrandType"}],"role":"symbol","url":"\/documentation\/airwallex\/awxbrandtype","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXBrandType"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXBrandType/allAvailable":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allAvailable"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AWXBrandType","preciseIdentifier":"c:@E@AWXBrandType"},{"kind":"text","text":"]"}],"role":"symbol","kind":"symbol","abstract":[],"title":"allAvailable","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrandType\/allAvailable","url":"\/documentation\/airwallex\/awxbrandtype\/allavailable","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXBrandType/dinersClub":{"abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dinersClub"}],"url":"\/documentation\/airwallex\/awxbrandtype\/dinersclub","title":"AWXBrandType.dinersClub","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWXBrandTypeDinersClub"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrandType\/dinersClub"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXBrandType/amex":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrandType\/amex","url":"\/documentation\/airwallex\/awxbrandtype\/amex","navigatorTitle":[{"kind":"identifier","text":"AWXBrandTypeAmex"}],"kind":"symbol","title":"AWXBrandType.amex","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"amex"}],"role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXBrandType/RawRepresentable-Implementations":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrandType\/RawRepresentable-Implementations","url":"\/documentation\/airwallex\/awxbrandtype\/rawrepresentable-implementations","kind":"article","title":"RawRepresentable Implementations","type":"topic","role":"collectionGroup"},"doc://org.cocoapods.Airwallex/SQ":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.Airwallex/SY":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXBrandType/visa":{"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"visa","kind":"identifier"}],"kind":"symbol","title":"AWXBrandType.visa","navigatorTitle":[{"text":"AWXBrandTypeVisa","kind":"identifier"}],"abstract":[],"url":"\/documentation\/airwallex\/awxbrandtype\/visa","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrandType\/visa"},"doc://org.cocoapods.Airwallex/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SH"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXBrandType/discover":{"navigatorTitle":[{"text":"AWXBrandTypeDiscover","kind":"identifier"}],"kind":"symbol","title":"AWXBrandType.discover","type":"topic","url":"\/documentation\/airwallex\/awxbrandtype\/discover","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrandType\/discover","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"discover","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXBrandType/mastercard":{"role":"symbol","navigatorTitle":[{"text":"AWXBrandTypeMastercard","kind":"identifier"}],"abstract":[],"kind":"symbol","title":"AWXBrandType.mastercard","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrandType\/mastercard","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mastercard","kind":"identifier"}],"type":"topic","url":"\/documentation\/airwallex\/awxbrandtype\/mastercard"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","kind":"symbol","url":"\/documentation\/airwallex","abstract":[],"title":"Airwallex","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXBrandType/JCB":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"JCB"}],"role":"symbol","type":"topic","url":"\/documentation\/airwallex\/awxbrandtype\/jcb","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWXBrandTypeJCB"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrandType\/JCB","abstract":[],"title":"AWXBrandType.JCB"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXBrandType/unknown":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrandType\/unknown","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWXBrandTypeUnknown"}],"url":"\/documentation\/airwallex\/awxbrandtype\/unknown","title":"AWXBrandType.unknown","role":"symbol","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXBrandType/init(rawValue:)":{"kind":"symbol","type":"topic","url":"\/documentation\/airwallex\/awxbrandtype\/init(rawvalue:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(rawValue:)","abstract":[],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrandType\/init(rawValue:)"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXBrandType/unionPay":{"url":"\/documentation\/airwallex\/awxbrandtype\/unionpay","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unionPay","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrandType\/unionPay","kind":"symbol","navigatorTitle":[{"text":"AWXBrandTypeUnionPay","kind":"identifier"}],"title":"AWXBrandType.unionPay","role":"symbol","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXBrandType/Equatable-Implementations":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrandType\/Equatable-Implementations","abstract":[],"url":"\/documentation\/airwallex\/awxbrandtype\/equatable-implementations","kind":"article","title":"Equatable Implementations","type":"topic","role":"collectionGroup"},"doc://org.cocoapods.Airwallex/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/org.cocoapods.Airwallex\/s8SendableP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"value":"AWXBrandType","path":"\/metadata\/title","op":"replace"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"AWXBrandType"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"AWXBrandType","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrandType\/JCB","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrandType\/amex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrandType\/dinersClub","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrandType\/discover","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrandType\/mastercard","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrandType\/unionPay","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrandType\/unknown","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrandType\/visa"],"title":"Enumeration Cases","anchor":"Enumeration-Cases","generated":true}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXBrandType"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier","text":"NSUInteger"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"AWXBrandType","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrandType\/title"},{"value":[{"kind":"identifier","text":"AWXBrandType"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrandType\/fragments"},{"value":[{"kind":"identifier","text":"AWXBrandType"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrandType\/navigatorTitle"},{"value":"AWXBrandTypeDinersClub","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrandType~1dinersClub\/title"},{"value":[{"kind":"identifier","text":"AWXBrandTypeDinersClub"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrandType~1dinersClub\/fragments"},{"value":"AWXBrandTypeAmex","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrandType~1amex\/title"},{"value":[{"kind":"identifier","text":"AWXBrandTypeAmex"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrandType~1amex\/fragments"},{"value":"AWXBrandTypeVisa","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrandType~1visa\/title"},{"value":[{"text":"AWXBrandTypeVisa","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrandType~1visa\/fragments"},{"value":"AWXBrandTypeDiscover","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrandType~1discover\/title"},{"value":[{"text":"AWXBrandTypeDiscover","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrandType~1discover\/fragments"},{"value":"AWXBrandTypeMastercard","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrandType~1mastercard\/title"},{"value":[{"text":"AWXBrandTypeMastercard","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrandType~1mastercard\/fragments"},{"value":"AWXBrandTypeJCB","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrandType~1JCB\/title"},{"value":[{"kind":"identifier","text":"AWXBrandTypeJCB"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrandType~1JCB\/fragments"},{"value":"AWXBrandTypeUnknown","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrandType~1unknown\/title"},{"value":[{"text":"AWXBrandTypeUnknown","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrandType~1unknown\/fragments"},{"value":"AWXBrandTypeUnionPay","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrandType~1unionPay\/title"},{"value":[{"kind":"identifier","text":"AWXBrandTypeUnionPay"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrandType~1unionPay\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}