{"metadata":{"roleHeading":"Class","externalID":"c:objc(cs)AWXCardScheme","modules":[{"name":"Airwallex"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AWXCardScheme","kind":"identifier"}],"navigatorTitle":[{"text":"AWXCardScheme","kind":"identifier"}],"role":"symbol","title":"AWXCardScheme","symbolKind":"class"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardScheme"},"schemaVersion":{"patch":0,"major":0,"minor":3},"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONDecodable","doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/SQ","doc:\/\/org.cocoapods.Airwallex\/SH"]}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXCardScheme"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","topicSections":[{"anchor":"Initializers","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardScheme\/init(name:)"],"title":"Initializers","generated":true},{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardScheme\/brandType","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardScheme\/name"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"title":"Type Properties","anchor":"Type-Properties","generated":true,"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardScheme\/allAvailable"]}],"variants":[{"paths":["\/documentation\/airwallex\/awxcardscheme"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxcardscheme"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"references":{"doc://org.cocoapods.Airwallex/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardScheme/name":{"kind":"symbol","title":"name","abstract":[],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardScheme\/name","url":"\/documentation\/airwallex\/awxcardscheme\/name","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"name","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"navigatorTitle":[{"text":"name","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXJSONDecodable":{"title":"AWXJSONDecodable","url":"\/documentation\/airwallex\/awxjsondecodable","type":"topic","navigatorTitle":[{"text":"AWXJSONDecodable","kind":"identifier"}],"abstract":[],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"AWXJSONDecodable","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONDecodable"},"doc://org.cocoapods.Airwallex/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardScheme/allAvailable":{"type":"topic","kind":"symbol","title":"allAvailable","url":"\/documentation\/airwallex\/awxcardscheme\/allavailable","abstract":[],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardScheme\/allAvailable","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allAvailable"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXCardScheme","text":"AWXCardScheme"},{"text":"]","kind":"text"}]},"doc://org.cocoapods.Airwallex/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://org.cocoapods.Airwallex/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SH","type":"unresolvable"},"doc://org.cocoapods.Airwallex/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardScheme/init(name:)":{"url":"\/documentation\/airwallex\/awxcardscheme\/init(name:)","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardScheme\/init(name:)","type":"topic","role":"symbol","kind":"symbol","title":"init(name:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"name"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardScheme/brandType":{"url":"\/documentation\/airwallex\/awxcardscheme\/brandtype","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardScheme\/brandType","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"brandType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@AWXBrandType","text":"AWXBrandType","kind":"typeIdentifier"}],"title":"brandType"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardScheme":{"url":"\/documentation\/airwallex\/awxcardscheme","title":"AWXCardScheme","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWXCardScheme"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AWXCardScheme"}],"abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardScheme","kind":"symbol"},"doc://org.cocoapods.Airwallex/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SQ"},"doc://org.cocoapods.Airwallex/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/airwallex","title":"Airwallex","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"AWXCardScheme"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"AWXCardScheme","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"AWXCardScheme","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardScheme\/name"],"title":"Instance Properties","generated":true}]},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONDecodable"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"AWXCardScheme","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardScheme~1name\/title","value":"name","op":"replace"},{"value":[{"text":"name","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardScheme~1name\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONDecodable\/title","value":"AWXJSONDecodable"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONDecodable\/fragments","value":[{"text":"AWXJSONDecodable","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONDecodable\/navigatorTitle","value":[{"kind":"identifier","text":"AWXJSONDecodable"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardScheme\/title","value":"AWXCardScheme","op":"replace"},{"value":[{"text":"AWXCardScheme","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardScheme\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardScheme\/navigatorTitle","value":[{"kind":"identifier","text":"AWXCardScheme"}]}]}]}