{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxgetpaymentmethodtypesrequest"]},{"paths":["\/documentation\/airwallex\/awxgetpaymentmethodtypesrequest"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:objc(cs)AWXGetPaymentMethodTypesRequest","title":"AWXGetPaymentMethodTypesRequest","symbolKind":"class","navigatorTitle":[{"text":"AWXGetPaymentMethodTypesRequest","kind":"identifier"}],"modules":[{"name":"Airwallex"}],"roleHeading":"Class","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AWXGetPaymentMethodTypesRequest"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AWXGetPaymentMethodTypesRequest","kind":"identifier"}]}]}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRequest"],"title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/SQ","doc:\/\/org.cocoapods.Airwallex\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypesRequest","interfaceLanguage":"swift"},"abstract":[{"code":"AWXGetPaymentMethodTypesRequest","type":"codeVoice"},{"type":"text","text":" includes all of the parameters needed to get payment method types."}],"topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypesRequest\/active","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypesRequest\/countryCode","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypesRequest\/flow","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypesRequest\/lang","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypesRequest\/pageNum","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypesRequest\/pageSize","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypesRequest\/resources","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypesRequest\/transactionCurrency","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypesRequest\/transactionMode"],"generated":true}],"kind":"symbol","references":{"doc://org.cocoapods.Airwallex/SQ":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://org.cocoapods.Airwallex/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.Airwallex/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentMethodTypesRequest/transactionCurrency":{"kind":"symbol","role":"symbol","title":"transactionCurrency","navigatorTitle":[{"kind":"identifier","text":"transactionCurrency"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypesRequest\/transactionCurrency","type":"topic","abstract":[{"type":"text","text":"A currency code."}],"url":"\/documentation\/airwallex\/awxgetpaymentmethodtypesrequest\/transactioncurrency","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"transactionCurrency"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentMethodTypesRequest/transactionMode":{"navigatorTitle":[{"text":"transactionMode","kind":"identifier"}],"role":"symbol","type":"topic","title":"transactionMode","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"transactionMode"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"url":"\/documentation\/airwallex\/awxgetpaymentmethodtypesrequest\/transactionmode","abstract":[{"type":"text","text":"Transaction code."}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypesRequest\/transactionMode","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentMethodTypesRequest/active":{"url":"\/documentation\/airwallex\/awxgetpaymentmethodtypesrequest\/active","abstract":[{"type":"text","text":"active ."}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypesRequest\/active","title":"active","navigatorTitle":[{"kind":"identifier","text":"active"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"active"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://org.cocoapods.Airwallex/SH":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentMethodTypesRequest/pageSize":{"navigatorTitle":[{"kind":"identifier","text":"pageSize"}],"role":"symbol","type":"topic","title":"pageSize","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pageSize","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"url":"\/documentation\/airwallex\/awxgetpaymentmethodtypesrequest\/pagesize","abstract":[{"type":"text","text":"Number of payment methods to be listed per page."}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypesRequest\/pageSize","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentMethodTypesRequest":{"abstract":[{"type":"codeVoice","code":"AWXGetPaymentMethodTypesRequest"},{"type":"text","text":" includes all of the parameters needed to get payment method types."}],"title":"AWXGetPaymentMethodTypesRequest","url":"\/documentation\/airwallex\/awxgetpaymentmethodtypesrequest","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypesRequest","role":"symbol","navigatorTitle":[{"text":"AWXGetPaymentMethodTypesRequest","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AWXGetPaymentMethodTypesRequest","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentMethodTypesRequest/flow":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"flow","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Filter payment methods for a specific flow. Defaults to inapp."}],"kind":"symbol","title":"flow","navigatorTitle":[{"text":"flow","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypesRequest\/flow","type":"topic","url":"\/documentation\/airwallex\/awxgetpaymentmethodtypesrequest\/flow","role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentMethodTypesRequest/resources":{"role":"symbol","title":"resources","abstract":[{"type":"text","text":"Whether it requres resources"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypesRequest\/resources","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"resources","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"resources"}],"url":"\/documentation\/airwallex\/awxgetpaymentmethodtypesrequest\/resources","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/airwallex","title":"Airwallex","role":"collection"},"doc://org.cocoapods.Airwallex/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentMethodTypesRequest/pageNum":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypesRequest\/pageNum","title":"pageNum","navigatorTitle":[{"text":"pageNum","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxgetpaymentmethodtypesrequest\/pagenum","abstract":[{"type":"text","text":"Page number starting from 0."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pageNum","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"type":"topic"},"doc://org.cocoapods.Airwallex/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRequest":{"navigatorTitle":[{"text":"AWXRequest","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXRequest"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRequest","kind":"symbol","abstract":[],"title":"AWXRequest","url":"\/documentation\/airwallex\/awxrequest"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentMethodTypesRequest/countryCode":{"kind":"symbol","navigatorTitle":[{"text":"countryCode","kind":"identifier"}],"title":"countryCode","role":"symbol","abstract":[{"type":"text","text":"Country code."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"countryCode"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypesRequest\/countryCode","url":"\/documentation\/airwallex\/awxgetpaymentmethodtypesrequest\/countrycode","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentMethodTypesRequest/lang":{"abstract":[{"type":"text","text":"Lang"}],"kind":"symbol","title":"lang","type":"topic","navigatorTitle":[{"text":"lang","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"lang","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypesRequest\/lang","url":"\/documentation\/airwallex\/awxgetpaymentmethodtypesrequest\/lang"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"AWXGetPaymentMethodTypesRequest","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AWXGetPaymentMethodTypesRequest"}]},{"op":"replace","value":[{"text":"AWXGetPaymentMethodTypesRequest","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypesRequest\/active","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypesRequest\/countryCode","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypesRequest\/flow","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypesRequest\/lang","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypesRequest\/pageNum","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypesRequest\/pageSize","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypesRequest\/resources","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypesRequest\/transactionCurrency","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypesRequest\/transactionMode"],"generated":true}]},{"value":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRequest"],"title":"Inherits From","type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"AWXGetPaymentMethodTypesRequest","kind":"identifier"},{"text":" : ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRequest","text":"AWXRequest","preciseIdentifier":"c:objc(cs)AWXRequest","kind":"typeIdentifier"}],"platforms":["iOS"]}]}},{"value":"transactionCurrency","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypesRequest~1transactionCurrency\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypesRequest~1transactionCurrency\/fragments","value":[{"kind":"identifier","text":"transactionCurrency"}]},{"value":"transactionMode","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypesRequest~1transactionMode\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypesRequest~1transactionMode\/fragments","op":"replace","value":[{"text":"transactionMode","kind":"identifier"}]},{"op":"replace","value":"active","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypesRequest~1active\/title"},{"op":"replace","value":[{"text":"active","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypesRequest~1active\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypesRequest~1pageSize\/title","value":"pageSize"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypesRequest~1pageSize\/fragments","value":[{"text":"pageSize","kind":"identifier"}]},{"value":"AWXGetPaymentMethodTypesRequest","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypesRequest\/title"},{"value":[{"kind":"identifier","text":"AWXGetPaymentMethodTypesRequest"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypesRequest\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypesRequest\/navigatorTitle","value":[{"kind":"identifier","text":"AWXGetPaymentMethodTypesRequest"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypesRequest~1flow\/title","value":"flow","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypesRequest~1flow\/fragments","value":[{"kind":"identifier","text":"flow"}],"op":"replace"},{"value":"resources","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypesRequest~1resources\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypesRequest~1resources\/fragments","value":[{"kind":"identifier","text":"resources"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypesRequest~1pageNum\/title","op":"replace","value":"pageNum"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypesRequest~1pageNum\/fragments","value":[{"text":"pageNum","kind":"identifier"}]},{"op":"replace","value":"AWXRequest","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRequest\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AWXRequest"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRequest\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRequest\/navigatorTitle","value":[{"text":"AWXRequest","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypesRequest~1countryCode\/title","op":"replace","value":"countryCode"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypesRequest~1countryCode\/fragments","value":[{"kind":"identifier","text":"countryCode"}]},{"value":"lang","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypesRequest~1lang\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypesRequest~1lang\/fragments","op":"replace","value":[{"text":"lang","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}