{"topicSections":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentAttempt\/amount","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentAttempt\/authenticationData","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentAttempt\/capturedAmount","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentAttempt\/id","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentAttempt\/paymentMethod","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentAttempt\/refundedAmount","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentAttempt\/status"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentAttempt","interfaceLanguage":"swift"},"abstract":[{"code":"AWXPaymentAttempt","type":"codeVoice"},{"text":" includes the information of payment attempt.","type":"text"}],"sections":[],"variants":[{"paths":["\/documentation\/airwallex\/awxpaymentattempt"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxpaymentattempt"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentAttempt"}],"symbolKind":"class","externalID":"c:objc(cs)AWXPaymentAttempt","title":"AWXPaymentAttempt","roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"AWXPaymentAttempt"}],"role":"symbol","modules":[{"name":"Airwallex"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentAttempt"}],"languages":["swift"],"platforms":["iOS"]}]}],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"]},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONDecodable","doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/SQ","doc:\/\/org.cocoapods.Airwallex\/SH"]}],"kind":"symbol","references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentAttempt/paymentMethod":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentAttempt\/paymentMethod","navigatorTitle":[{"text":"paymentMethod","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentMethod","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWXPaymentMethod","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPaymentMethod"}],"url":"\/documentation\/airwallex\/awxpaymentattempt\/paymentmethod","abstract":[{"text":"Payment method.","type":"text"}],"title":"paymentMethod","role":"symbol","kind":"symbol","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentAttempt/status":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"status","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"status","kind":"identifier"}],"title":"status","abstract":[{"text":"The status of payment attempt","type":"text"}],"role":"symbol","url":"\/documentation\/airwallex\/awxpaymentattempt\/status","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentAttempt\/status","kind":"symbol"},"doc://org.cocoapods.Airwallex/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","kind":"symbol","url":"\/documentation\/airwallex","abstract":[],"title":"Airwallex","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentAttempt":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentAttempt","title":"AWXPaymentAttempt","url":"\/documentation\/airwallex\/awxpaymentattempt","type":"topic","abstract":[{"code":"AWXPaymentAttempt","type":"codeVoice"},{"text":" includes the information of payment attempt.","type":"text"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"AWXPaymentAttempt","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPaymentAttempt","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SQ"},"doc://org.cocoapods.Airwallex/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentAttempt/refundedAmount":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"refundedAmount"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"refundedAmount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSDecimalNumber","preciseIdentifier":"c:objc(cs)NSDecimalNumber"}],"url":"\/documentation\/airwallex\/awxpaymentattempt\/refundedamount","abstract":[{"type":"text","text":"Refunded amount."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentAttempt\/refundedAmount","title":"refundedAmount"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentAttempt/amount":{"role":"symbol","url":"\/documentation\/airwallex\/awxpaymentattempt\/amount","navigatorTitle":[{"text":"amount","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"amount","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSDecimalNumber","preciseIdentifier":"c:objc(cs)NSDecimalNumber","kind":"typeIdentifier"}],"title":"amount","abstract":[{"text":"Payment amount.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentAttempt\/amount"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentAttempt/capturedAmount":{"abstract":[{"text":"Captured amount.","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/airwallex\/awxpaymentattempt\/capturedamount","title":"capturedAmount","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"capturedAmount","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSDecimalNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDecimalNumber"}],"navigatorTitle":[{"text":"capturedAmount","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentAttempt\/capturedAmount"},"doc://org.cocoapods.Airwallex/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXJSONDecodable":{"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONDecodable","title":"AWXJSONDecodable","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXJSONDecodable"}],"navigatorTitle":[{"kind":"identifier","text":"AWXJSONDecodable"}],"url":"\/documentation\/airwallex\/awxjsondecodable","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentAttempt/id":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"Id","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentAttempt\/id","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Attempt id."}],"title":"id","url":"\/documentation\/airwallex\/awxpaymentattempt\/id"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentAttempt/authenticationData":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentAttempt\/authenticationData","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticationData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXAuthenticationData","text":"AWXAuthenticationData"}],"role":"symbol","title":"authenticationData","kind":"symbol","abstract":[{"text":"3DS authentication data.","type":"text"}],"url":"\/documentation\/airwallex\/awxpaymentattempt\/authenticationdata","type":"topic","navigatorTitle":[{"kind":"identifier","text":"authenticationData"}]},"doc://org.cocoapods.Airwallex/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject","type":"unresolvable"},"doc://org.cocoapods.Airwallex/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.Airwallex/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SH","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"AWXPaymentAttempt","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"AWXPaymentAttempt","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"AWXPaymentAttempt","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentAttempt\/amount","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentAttempt\/authenticationData","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentAttempt\/capturedAmount","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentAttempt\/id","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentAttempt\/paymentMethod","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentAttempt\/refundedAmount","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentAttempt\/status"],"title":"Instance Properties"}],"op":"replace","path":"\/topicSections"},{"value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONDecodable"],"type":"conformsTo"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPaymentAttempt","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"paymentMethod","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentAttempt~1paymentMethod\/title"},{"value":[{"text":"paymentMethod","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentAttempt~1paymentMethod\/fragments"},{"value":"status","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentAttempt~1status\/title"},{"value":[{"kind":"identifier","text":"status"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentAttempt~1status\/fragments"},{"value":"AWXPaymentAttempt","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentAttempt\/title"},{"value":[{"text":"AWXPaymentAttempt","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentAttempt\/fragments"},{"value":[{"text":"AWXPaymentAttempt","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentAttempt\/navigatorTitle"},{"value":"refundedAmount","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentAttempt~1refundedAmount\/title"},{"value":[{"text":"refundedAmount","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentAttempt~1refundedAmount\/fragments"},{"value":"amount","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentAttempt~1amount\/title"},{"value":[{"kind":"identifier","text":"amount"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentAttempt~1amount\/fragments"},{"value":"capturedAmount","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentAttempt~1capturedAmount\/title"},{"value":[{"text":"capturedAmount","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentAttempt~1capturedAmount\/fragments"},{"value":"AWXJSONDecodable","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONDecodable\/title"},{"value":[{"text":"AWXJSONDecodable","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONDecodable\/fragments"},{"value":[{"kind":"identifier","text":"AWXJSONDecodable"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONDecodable\/navigatorTitle"},{"value":"Id","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentAttempt~1id\/title"},{"value":[{"text":"Id","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentAttempt~1id\/fragments"},{"value":"authenticationData","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentAttempt~1authenticationData\/title"},{"value":[{"text":"authenticationData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentAttempt~1authenticationData\/fragments"}]}]}