{"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme\/tintColor"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"},{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme\/disabledButtonColor()","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme\/errorColor()","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme\/glyphColor()","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme\/lineColor()","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme\/primaryBackgroundColor()","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme\/primaryButtonTextColor()","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme\/primaryTextColor()","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme\/secondaryTextColor()","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme\/shadowColor()","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme\/surfaceBackgroundColor()","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme\/toolbarColor()"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"},{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme\/shared()"],"anchor":"Type-Methods","generated":true,"title":"Type Methods"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/SQ","doc:\/\/org.cocoapods.Airwallex\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXTheme","kind":"identifier"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxtheme"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxtheme"]}],"abstract":[{"code":"AWXTheme","type":"codeVoice"},{"text":" manages text styles.","type":"text"}],"metadata":{"modules":[{"name":"Airwallex"}],"symbolKind":"class","externalID":"c:objc(cs)AWXTheme","title":"AWXTheme","role":"symbol","navigatorTitle":[{"text":"AWXTheme","kind":"identifier"}],"roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXTheme","kind":"identifier"}]},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","kind":"symbol","url":"\/documentation\/airwallex","abstract":[],"title":"Airwallex","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXTheme/lineColor()":{"navigatorTitle":[{"text":"lineColor","kind":"identifier"}],"title":"lineColor()","abstract":[],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme\/lineColor()","url":"\/documentation\/airwallex\/awxtheme\/linecolor()","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lineColor","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXTheme/primaryBackgroundColor()":{"url":"\/documentation\/airwallex\/awxtheme\/primarybackgroundcolor()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"primaryBackgroundColor"}],"type":"topic","kind":"symbol","abstract":[],"title":"primaryBackgroundColor()","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme\/primaryBackgroundColor()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"primaryBackgroundColor"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXTheme":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXTheme","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme","kind":"symbol","type":"topic","navigatorTitle":[{"text":"AWXTheme","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxtheme","title":"AWXTheme","abstract":[{"type":"codeVoice","code":"AWXTheme"},{"type":"text","text":" manages text styles."}],"role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXTheme/glyphColor()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"glyphColor"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme\/glyphColor()","navigatorTitle":[{"kind":"identifier","text":"glyphColor"}],"type":"topic","kind":"symbol","abstract":[],"url":"\/documentation\/airwallex\/awxtheme\/glyphcolor()","role":"symbol","title":"glyphColor()"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXTheme/surfaceBackgroundColor()":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme\/surfaceBackgroundColor()","abstract":[],"type":"topic","title":"surfaceBackgroundColor()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"surfaceBackgroundColor","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"url":"\/documentation\/airwallex\/awxtheme\/surfacebackgroundcolor()","navigatorTitle":[{"text":"surfaceBackgroundColor","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXTheme/disabledButtonColor()":{"abstract":[],"title":"disabledButtonColor()","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme\/disabledButtonColor()","kind":"symbol","url":"\/documentation\/airwallex\/awxtheme\/disabledbuttoncolor()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disabledButtonColor","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"navigatorTitle":[{"kind":"identifier","text":"disabledButtonColor"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.Airwallex/objc(cs)NSObject":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXTheme/toolbarColor()":{"url":"\/documentation\/airwallex\/awxtheme\/toolbarcolor()","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme\/toolbarColor()","title":"toolbarColor()","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toolbarColor","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"toolbarColor","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.Airwallex/SQ":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXTheme/tintColor":{"url":"\/documentation\/airwallex\/awxtheme\/tintcolor","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tintColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":"!","kind":"text"}],"navigatorTitle":[{"text":"tintColor","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme\/tintColor","abstract":[{"text":"The primary tint color used for theming.","type":"text"}],"title":"tintColor"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXTheme/shadowColor()":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme\/shadowColor()","url":"\/documentation\/airwallex\/awxtheme\/shadowcolor()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shadowColor","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"shadowColor","kind":"identifier"}],"kind":"symbol","type":"topic","title":"shadowColor()","abstract":[],"role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXTheme/secondaryTextColor()":{"kind":"symbol","url":"\/documentation\/airwallex\/awxtheme\/secondarytextcolor()","navigatorTitle":[{"text":"secondaryTextColor","kind":"identifier"}],"abstract":[],"title":"secondaryTextColor()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"secondaryTextColor","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme\/secondaryTextColor()"},"doc://org.cocoapods.Airwallex/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://org.cocoapods.Airwallex/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXTheme/primaryButtonTextColor()":{"abstract":[],"url":"\/documentation\/airwallex\/awxtheme\/primarybuttontextcolor()","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme\/primaryButtonTextColor()","role":"symbol","kind":"symbol","title":"primaryButtonTextColor()","navigatorTitle":[{"kind":"identifier","text":"primaryButtonTextColor"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"primaryButtonTextColor"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}],"type":"topic"},"doc://org.cocoapods.Airwallex/SH":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXTheme/shared()":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme\/shared()","abstract":[{"type":"text","text":"Convenience constructor for a theme."}],"role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Self"}],"url":"\/documentation\/airwallex\/awxtheme\/shared()","title":"shared()","navigatorTitle":[{"kind":"identifier","text":"sharedTheme"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXTheme/errorColor()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorColor","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme\/errorColor()","url":"\/documentation\/airwallex\/awxtheme\/errorcolor()","abstract":[],"title":"errorColor()","role":"symbol","navigatorTitle":[{"text":"errorColor","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.Airwallex/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://org.cocoapods.Airwallex/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXTheme/primaryTextColor()":{"type":"topic","url":"\/documentation\/airwallex\/awxtheme\/primarytextcolor()","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme\/primaryTextColor()","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"primaryTextColor","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"title":"primaryTextColor()","navigatorTitle":[{"text":"primaryTextColor","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"AWXTheme","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"AWXTheme","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AWXTheme"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme\/tintColor"],"generated":true,"title":"Instance Properties"},{"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme\/disabledButtonColor()","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme\/errorColor()","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme\/glyphColor()","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme\/lineColor()","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme\/primaryBackgroundColor()","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme\/primaryButtonTextColor()","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme\/primaryTextColor()","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme\/secondaryTextColor()","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme\/shadowColor()","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme\/surfaceBackgroundColor()","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme\/toolbarColor()"],"generated":true,"title":"Instance Methods"},{"anchor":"Type-Methods","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme\/shared()"],"generated":true,"title":"Type Methods"}],"path":"\/topicSections","op":"replace"},{"value":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXTheme","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"lineColor","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTheme~1lineColor()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"lineColor","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTheme~1lineColor()\/fragments","op":"replace"},{"value":"primaryBackgroundColor","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTheme~1primaryBackgroundColor()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"primaryBackgroundColor","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTheme~1primaryBackgroundColor()\/fragments","op":"replace"},{"value":"AWXTheme","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTheme\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AWXTheme"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTheme\/fragments","op":"replace"},{"value":[{"text":"AWXTheme","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTheme\/navigatorTitle","op":"replace"},{"value":"glyphColor","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTheme~1glyphColor()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"glyphColor","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTheme~1glyphColor()\/fragments","op":"replace"},{"value":"surfaceBackgroundColor","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTheme~1surfaceBackgroundColor()\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"surfaceBackgroundColor"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTheme~1surfaceBackgroundColor()\/fragments","op":"replace"},{"value":"disabledButtonColor","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTheme~1disabledButtonColor()\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"disabledButtonColor"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTheme~1disabledButtonColor()\/fragments","op":"replace"},{"value":"toolbarColor","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTheme~1toolbarColor()\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toolbarColor"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTheme~1toolbarColor()\/fragments","op":"replace"},{"value":"tintColor","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTheme~1tintColor\/title","op":"replace"},{"value":[{"kind":"identifier","text":"tintColor"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTheme~1tintColor\/fragments","op":"replace"},{"value":"shadowColor","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTheme~1shadowColor()\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"shadowColor","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTheme~1shadowColor()\/fragments","op":"replace"},{"value":"secondaryTextColor","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTheme~1secondaryTextColor()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"secondaryTextColor","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTheme~1secondaryTextColor()\/fragments","op":"replace"},{"value":"primaryButtonTextColor","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTheme~1primaryButtonTextColor()\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"primaryButtonTextColor"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTheme~1primaryButtonTextColor()\/fragments","op":"replace"},{"value":"sharedTheme","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTheme~1shared()\/title","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"sharedTheme"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTheme~1shared()\/fragments","op":"replace"},{"value":"errorColor","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTheme~1errorColor()\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"errorColor"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTheme~1errorColor()\/fragments","op":"replace"},{"value":"primaryTextColor","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTheme~1primaryTextColor()\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"primaryTextColor"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTheme~1primaryTextColor()\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}