{"metadata":{"externalID":"c:@M@Airwallex@E@PaymentAmountType","navigatorTitle":[{"kind":"identifier","text":"PaymentAmountType"}],"roleHeading":"Enumeration","title":"PaymentAmountType","modules":[{"name":"Airwallex"}],"role":"symbol","symbolKind":"enum","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentAmountType"}]},"abstract":[{"type":"text","text":"Payment amount type enumeration"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/s12CaseIterableP","doc:\/\/org.cocoapods.Airwallex\/SQ","doc:\/\/org.cocoapods.Airwallex\/SH","doc:\/\/org.cocoapods.Airwallex\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentAmountType","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentAmountType\/fixed","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentAmountType\/variable"],"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases"},{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentAmountType\/init(rawValue:)"],"title":"Initializers","generated":true,"anchor":"Initializers"},{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentAmountType\/Equatable-Implementations","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentAmountType\/RawRepresentable-Implementations"],"title":"Default Implementations","generated":true,"anchor":"Default-Implementations"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PaymentAmountType","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/paymentamounttype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/paymentamounttype"]}],"kind":"symbol","references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentAmountType/variable":{"kind":"symbol","type":"topic","url":"\/documentation\/airwallex\/paymentamounttype\/variable","title":"PaymentAmountType.variable","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"variable"}],"role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"PaymentAmountTypeVariable"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentAmountType\/variable"},"doc://org.cocoapods.Airwallex/s12CaseIterableP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s12CaseIterableP","title":"Swift.CaseIterable","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentAmountType/fixed":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentAmountType\/fixed","navigatorTitle":[{"text":"PaymentAmountTypeFixed","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fixed","kind":"identifier"}],"type":"topic","url":"\/documentation\/airwallex\/paymentamounttype\/fixed","abstract":[],"title":"PaymentAmountType.fixed"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentAmountType":{"url":"\/documentation\/airwallex\/paymentamounttype","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentAmountType","title":"PaymentAmountType","navigatorTitle":[{"text":"PaymentAmountType","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PaymentAmountType","kind":"identifier"}],"type":"topic","abstract":[{"text":"Payment amount type enumeration","type":"text"}],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","kind":"symbol","url":"\/documentation\/airwallex","abstract":[],"title":"Airwallex","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentAmountType/RawRepresentable-Implementations":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentAmountType\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","role":"collectionGroup","kind":"article","url":"\/documentation\/airwallex\/paymentamounttype\/rawrepresentable-implementations","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentAmountType/Equatable-Implementations":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentAmountType\/Equatable-Implementations","title":"Equatable Implementations","role":"collectionGroup","kind":"article","url":"\/documentation\/airwallex\/paymentamounttype\/equatable-implementations","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentAmountType/init(rawValue:)":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentAmountType\/init(rawValue:)","title":"init(rawValue:)","role":"symbol","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"url":"\/documentation\/airwallex\/paymentamounttype\/init(rawvalue:)","type":"topic"},"doc://org.cocoapods.Airwallex/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SH"},"doc://org.cocoapods.Airwallex/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SY"},"doc://org.cocoapods.Airwallex/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SQ"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","value":"PaymentAmountType","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"PaymentAmountType","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PaymentAmountType"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentAmountType\/fixed","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentAmountType\/variable"],"generated":true,"anchor":"Enumeration-Cases"}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentAmountType"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"PaymentAmountTypeVariable","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentAmountType~1variable\/title"},{"value":[{"text":"PaymentAmountTypeVariable","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentAmountType~1variable\/fragments"},{"value":"PaymentAmountTypeFixed","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentAmountType~1fixed\/title"},{"value":[{"text":"PaymentAmountTypeFixed","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentAmountType~1fixed\/fragments"},{"value":"PaymentAmountType","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentAmountType\/title"},{"value":[{"text":"PaymentAmountType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentAmountType\/fragments"},{"value":[{"text":"PaymentAmountType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentAmountType\/navigatorTitle"}]}]}