{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PaymentVersionString","kind":"identifier"},{"text":": <<error type>>","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"metadata":{"roleHeading":"Global Variable","externalID":"c:@PaymentVersionString","title":"PaymentVersionString","navigatorTitle":[{"text":"PaymentVersionString","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PaymentVersionString","kind":"identifier"},{"text":": <<error type>>","kind":"text"}],"role":"symbol","symbolKind":"var","modules":[{"name":"Airwallex"}]},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentVersionString","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Project version string for Payment."}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/paymentversionstring"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/paymentversionstring"]}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentVersionString":{"type":"topic","url":"\/documentation\/airwallex\/paymentversionstring","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"PaymentVersionString","kind":"identifier"}],"abstract":[{"type":"text","text":"Project version string for Payment."}],"title":"PaymentVersionString","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PaymentVersionString","kind":"identifier"},{"text":": <<error type>>","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentVersionString"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","role":"collection","title":"Airwallex","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Global Variable"},{"path":"\/metadata\/title","op":"replace","value":"PaymentVersionString"},{"path":"\/metadata\/symbolKind","op":"replace","value":"var"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"PaymentVersionString","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unsigned char","kind":"typeIdentifier","preciseIdentifier":"c:c"},{"text":" ","kind":"text"},{"text":"PaymentVersionString","kind":"identifier"},{"text":"[];","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentVersionString\/title","op":"replace","value":"PaymentVersionString"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentVersionString\/fragments","op":"replace","value":[{"kind":"identifier","text":"PaymentVersionString"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}