{"metadata":{"externalID":"c:@E@AirwallexNextTriggerByType@AirwallexNextTriggerByCustomerType","role":"symbol","modules":[{"name":"Airwallex"}],"symbolKind":"case","title":"AirwallexNextTriggerByType.customerType","navigatorTitle":[{"text":"AirwallexNextTriggerByCustomerType","kind":"identifier"}],"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customerType","kind":"identifier"}]},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexNextTriggerByType"]]},"variants":[{"paths":["\/documentation\/airwallex\/airwallexnexttriggerbytype\/customertype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/airwallexnexttriggerbytype\/customertype"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexNextTriggerByType\/customerType","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customerType","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexNextTriggerByType":{"title":"AirwallexNextTriggerByType","type":"topic","role":"symbol","navigatorTitle":[{"text":"AirwallexNextTriggerByType","kind":"identifier"}],"url":"\/documentation\/airwallex\/airwallexnexttriggerbytype","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexNextTriggerByType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AirwallexNextTriggerByType","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","url":"\/documentation\/airwallex","title":"Airwallex","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexNextTriggerByType/customerType":{"abstract":[],"kind":"symbol","title":"AirwallexNextTriggerByType.customerType","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexNextTriggerByType\/customerType","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customerType","kind":"identifier"}],"navigatorTitle":[{"text":"AirwallexNextTriggerByCustomerType","kind":"identifier"}],"url":"\/documentation\/airwallex\/airwallexnexttriggerbytype\/customertype"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"AirwallexNextTriggerByCustomerType","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"AirwallexNextTriggerByCustomerType","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"AirwallexNextTriggerByCustomerType","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"AirwallexNextTriggerByType","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexNextTriggerByType\/title"},{"op":"replace","value":[{"text":"AirwallexNextTriggerByType","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexNextTriggerByType\/fragments"},{"op":"replace","value":[{"text":"AirwallexNextTriggerByType","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexNextTriggerByType\/navigatorTitle"},{"op":"replace","value":"AirwallexNextTriggerByCustomerType","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexNextTriggerByType~1customerType\/title"},{"op":"replace","value":[{"text":"AirwallexNextTriggerByCustomerType","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexNextTriggerByType~1customerType\/fragments"}]}]}