{"metadata":{"title":"Equatable Implementations","roleHeading":"API Collection","modules":[{"name":"Airwallex"}],"role":"collectionGroup"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/airwallexnexttriggerbytype\/equatable-implementations"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"topicSections":[{"title":"Operators","anchor":"Operators","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexNextTriggerByType\/!=(_:_:)"],"generated":true}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexNextTriggerByType"]]},"kind":"article","identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexNextTriggerByType\/Equatable-Implementations","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexNextTriggerByType":{"title":"AirwallexNextTriggerByType","navigatorTitle":[{"text":"AirwallexNextTriggerByType","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexNextTriggerByType","role":"symbol","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AirwallexNextTriggerByType","kind":"identifier"}],"url":"\/documentation\/airwallex\/airwallexnexttriggerbytype","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexNextTriggerByType/!=(_:_:)":{"title":"!=(_:_:)","abstract":[],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexNextTriggerByType\/!=(_:_:)","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"url":"\/documentation\/airwallex\/airwallexnexttriggerbytype\/!=(_:_:)"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol","type":"topic","url":"\/documentation\/airwallex","role":"collection","abstract":[],"title":"Airwallex"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexNextTriggerByType\/title","value":"AirwallexNextTriggerByType","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexNextTriggerByType\/fragments","value":[{"text":"AirwallexNextTriggerByType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexNextTriggerByType\/navigatorTitle","value":[{"text":"AirwallexNextTriggerByType","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}