{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/airwallex\/mode()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/airwallex\/mode()"]}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Airwallex\/mode()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Get sdk mode. Test mode as default."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mode","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"AirwallexSDKMode","kind":"typeIdentifier","preciseIdentifier":"c:@E@AirwallexSDKMode","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexSDKMode"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Airwallex"]]},"metadata":{"symbolKind":"method","roleHeading":"Type Method","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mode","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"AirwallexSDKMode","kind":"typeIdentifier","preciseIdentifier":"c:@E@AirwallexSDKMode"}],"navigatorTitle":[{"text":"mode","kind":"identifier"}],"title":"mode()","externalID":"c:objc(cs)Airwallex(cm)mode","role":"symbol","modules":[{"name":"Airwallex"}]},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexSDKMode":{"navigatorTitle":[{"text":"AirwallexSDKMode","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexSDKMode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AirwallexSDKMode","kind":"identifier"}],"title":"AirwallexSDKMode","kind":"symbol","type":"topic","url":"\/documentation\/airwallex\/airwallexsdkmode","abstract":[],"role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"abstract":[],"type":"topic","url":"\/documentation\/airwallex","title":"Airwallex","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/Airwallex":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Airwallex","url":"\/documentation\/airwallex\/airwallex","type":"topic","title":"Airwallex","abstract":[{"code":"Airwallex","type":"codeVoice"},{"text":" contains the base configuration the SDK needs.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"Airwallex"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Airwallex"}],"role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/Airwallex/mode()":{"title":"mode()","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mode","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"AirwallexSDKMode","kind":"typeIdentifier","preciseIdentifier":"c:@E@AirwallexSDKMode"}],"kind":"symbol","url":"\/documentation\/airwallex\/airwallex\/mode()","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Airwallex\/mode()","role":"symbol","navigatorTitle":[{"text":"mode","kind":"identifier"}],"type":"topic","abstract":[{"text":"Get sdk mode. Test mode as default.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"mode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"mode"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"AirwallexSDKMode","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexSDKMode","preciseIdentifier":"c:@E@AirwallexSDKMode"},{"kind":"text","text":") "},{"kind":"identifier","text":"mode"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexSDKMode\/title","value":"AirwallexSDKMode","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexSDKMode\/fragments","value":[{"text":"AirwallexSDKMode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexSDKMode\/navigatorTitle","value":[{"text":"AirwallexSDKMode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Airwallex\/title","value":"Airwallex","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Airwallex\/fragments","value":[{"kind":"identifier","text":"Airwallex"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Airwallex\/navigatorTitle","value":[{"kind":"identifier","text":"Airwallex"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Airwallex~1mode()\/title","value":"mode","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Airwallex~1mode()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"mode","kind":"identifier"}],"op":"replace"}]}]}