{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXProviderDelegate"]]},"metadata":{"externalID":"c:objc(pl)AWXProviderDelegate(im)provider:didCompleteWithStatus:error:","modules":[{"name":"Airwallex"}],"title":"provider(_:didCompleteWith:error:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"provider","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AWXDefaultProvider","preciseIdentifier":"c:objc(cs)AWXDefaultProvider","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didCompleteWith","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AirwallexPaymentStatus","preciseIdentifier":"c:@E@AirwallexPaymentStatus","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": (any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"navigatorTitle":[{"text":"provider:didCompleteWithStatus:error:","kind":"identifier"}],"symbolKind":"method","roleHeading":"Instance Method","required":true},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXProviderDelegate\/provider(_:didCompleteWith:error:)","interfaceLanguage":"swift"},"abstract":[{"text":"This method is called when payment is completed.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"provider","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"provider","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider","text":"AWXDefaultProvider","preciseIdentifier":"c:objc(cs)AWXDefaultProvider","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didCompleteWith","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexPaymentStatus","preciseIdentifier":"c:@E@AirwallexPaymentStatus","text":"AirwallexPaymentStatus"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")?)"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The provider handling payment.","type":"text"}]}],"name":"provider"},{"content":[{"inlineContent":[{"type":"text","text":"The status of payment."}],"type":"paragraph"}],"name":"status"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The error of payment."}]}],"name":"error"}],"kind":"parameters"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/airwallex\/awxproviderdelegate\/provider(_:didcompletewith:error:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxproviderdelegate\/provider(_:didcompletewith:error:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXDefaultProvider":{"navigatorTitle":[{"text":"AWXDefaultProvider","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider","abstract":[{"type":"text","text":"A provider which handles payment business."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXDefaultProvider","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxdefaultprovider","type":"topic","title":"AWXDefaultProvider","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexPaymentStatus":{"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AirwallexPaymentStatus"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexPaymentStatus","navigatorTitle":[{"kind":"identifier","text":"AirwallexPaymentStatus"}],"kind":"symbol","title":"AirwallexPaymentStatus","type":"topic","url":"\/documentation\/airwallex\/airwallexpaymentstatus","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"abstract":[],"type":"topic","url":"\/documentation\/airwallex","title":"Airwallex","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXProviderDelegate":{"abstract":[{"text":"A delegate which handles checkout results.","type":"text"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXProviderDelegate","kind":"identifier"}],"title":"AWXProviderDelegate","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXProviderDelegate","navigatorTitle":[{"text":"AWXProviderDelegate","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxproviderdelegate","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXProviderDelegate/provider(_:didCompleteWith:error:)":{"navigatorTitle":[{"text":"provider:didCompleteWithStatus:error:","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxproviderdelegate\/provider(_:didcompletewith:error:)","title":"provider(_:didCompleteWith:error:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"provider","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AWXDefaultProvider","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXDefaultProvider"},{"text":", ","kind":"text"},{"text":"didCompleteWith","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AirwallexPaymentStatus","kind":"typeIdentifier","preciseIdentifier":"c:@E@AirwallexPaymentStatus"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": (any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?)","kind":"text"}],"abstract":[{"text":"This method is called when payment is completed.","type":"text"}],"kind":"symbol","type":"topic","required":true,"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXProviderDelegate\/provider(_:didCompleteWith:error:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"provider:didCompleteWithStatus:error:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"provider:didCompleteWithStatus:error:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"provider:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AWXDefaultProvider","preciseIdentifier":"c:objc(cs)AWXDefaultProvider","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider"},{"text":" *) ","kind":"text"},{"text":"provider","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didCompleteWithStatus:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AirwallexPaymentStatus","preciseIdentifier":"c:@E@AirwallexPaymentStatus","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexPaymentStatus"},{"text":") ","kind":"text"},{"text":"status","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"provider","content":[{"inlineContent":[{"type":"text","text":"The provider handling payment."}],"type":"paragraph"}]},{"name":"status","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The status of payment."}]}]},{"name":"error","content":[{"type":"paragraph","inlineContent":[{"text":"The error of payment.","type":"text"}]}]}]},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"AWXDefaultProvider","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider\/title"},{"op":"replace","value":[{"text":"AWXDefaultProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AWXDefaultProvider"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider\/navigatorTitle"},{"op":"replace","value":"AirwallexPaymentStatus","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexPaymentStatus\/title"},{"op":"replace","value":[{"text":"AirwallexPaymentStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexPaymentStatus\/fragments"},{"op":"replace","value":[{"text":"AirwallexPaymentStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexPaymentStatus\/navigatorTitle"},{"op":"replace","value":"AWXProviderDelegate","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXProviderDelegate\/title"},{"op":"replace","value":[{"text":"AWXProviderDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXProviderDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AWXProviderDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXProviderDelegate\/navigatorTitle"},{"op":"replace","value":"provider:didCompleteWithStatus:error:","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXProviderDelegate~1provider(_:didCompleteWith:error:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"provider:didCompleteWithStatus:error:"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXProviderDelegate~1provider(_:didCompleteWith:error:)\/fragments"}]}]}