{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxpaymentelement\/configuration\/layout"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/Configuration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"layout","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWXUIContext","preciseIdentifier":"c:@M@Airwallex@objc(cs)AWXUIContext","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext"},{"text":".","kind":"text"},{"text":"PaymentLayout","preciseIdentifier":"s:9Airwallex12AWXUIContextC13PaymentLayoutO","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/PaymentLayout"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Only applies when ","type":"text"},{"code":"elementType","type":"codeVoice"},{"text":" is ","type":"text"},{"code":".paymentSheet","type":"codeVoice"},{"text":".","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"code":".tab","type":"codeVoice"},{"text":": Displays payment methods in a horizontal tab bar (default)","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"code":".accordion","type":"codeVoice"},{"text":": Displays payment methods in an expandable accordion layout","type":"text"}]}]}]}]}],"abstract":[{"text":"The layout style for payment sections.","type":"text"}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/Configuration\/layout","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","metadata":{"roleHeading":"Instance Property","symbolKind":"property","title":"layout","modules":[{"name":"Airwallex"}],"externalID":"s:9Airwallex17AWXPaymentElementC13ConfigurationC6layoutAA12AWXUIContextC13PaymentLayoutOvp","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"layout","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@Airwallex@objc(cs)AWXUIContext","text":"AWXUIContext","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:9Airwallex12AWXUIContextC13PaymentLayoutO","text":"PaymentLayout","kind":"typeIdentifier"}],"role":"symbol"},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","type":"topic","role":"collection","title":"Airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXUIContext/PaymentLayout":{"title":"AWXUIContext.PaymentLayout","navigatorTitle":[{"text":"PaymentLayout","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/PaymentLayout","url":"\/documentation\/airwallex\/awxuicontext\/paymentlayout","role":"symbol","abstract":[{"text":"Defines the layout style for payment method selection.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PaymentLayout","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement/Configuration/layout":{"url":"\/documentation\/airwallex\/awxpaymentelement\/configuration\/layout","title":"layout","type":"topic","abstract":[{"text":"The layout style for payment sections.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"layout","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWXUIContext","kind":"typeIdentifier","preciseIdentifier":"c:@M@Airwallex@objc(cs)AWXUIContext"},{"text":".","kind":"text"},{"text":"PaymentLayout","kind":"typeIdentifier","preciseIdentifier":"s:9Airwallex12AWXUIContextC13PaymentLayoutO"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/Configuration\/layout","kind":"symbol","role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement/Configuration":{"url":"\/documentation\/airwallex\/awxpaymentelement\/configuration","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"role":"symbol","title":"AWXPaymentElement.Configuration","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/Configuration","kind":"symbol","abstract":[{"type":"text","text":"Configuration options for the embedded payment element."}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXUIContext":{"navigatorTitle":[{"text":"AWXUIContext","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext","abstract":[{"type":"text","text":"The main UI context for Airwallex payment flows."}],"title":"AWXUIContext","type":"topic","kind":"symbol","url":"\/documentation\/airwallex\/awxuicontext","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXUIContext","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement":{"title":"AWXPaymentElement","navigatorTitle":[{"text":"AWXPaymentElement","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxpaymentelement","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement","role":"symbol","abstract":[{"text":"An embeddable payment element that can be added to any view hierarchy.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPaymentElement","kind":"identifier"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext\/title","op":"replace","value":"AWXUIContext"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext\/fragments","value":[{"text":"AWXUIContext","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext\/navigatorTitle","op":"replace","value":[{"text":"AWXUIContext","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/title","op":"replace","value":"AWXPaymentElement"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/fragments","op":"replace","value":[{"text":"AWXPaymentElement","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/navigatorTitle","op":"replace","value":[{"text":"AWXPaymentElement","kind":"identifier"}]}]}]}