{"metadata":{"externalID":"c:objc(cs)AWXCard(py)expiryYear","modules":[{"name":"Airwallex"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"expiryYear"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"title":"expiryYear","symbolKind":"property","role":"symbol","navigatorTitle":[{"text":"expiryYear","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"expiryYear"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCard"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxcard\/expiryyear"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxcard\/expiryyear"]}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCard\/expiryYear","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"Four digit number representing the card’s expiration year. Example: 2030."}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCard":{"url":"\/documentation\/airwallex\/awxcard","role":"symbol","type":"topic","navigatorTitle":[{"text":"AWXCard","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXCard","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCard","title":"AWXCard","abstract":[{"code":"AWXCard","type":"codeVoice"},{"text":" includes the information of a card.","type":"text"}],"kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","url":"\/documentation\/airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol","title":"Airwallex","abstract":[],"role":"collection"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCard/expiryYear":{"abstract":[{"text":"Four digit number representing the card’s expiration year. Example: 2030.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/airwallex\/awxcard\/expiryyear","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCard\/expiryYear","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"expiryYear","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"expiryYear","kind":"identifier"}],"title":"expiryYear"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"expiryYear","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"expiryYear"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"expiryYear","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCard\/title","value":"AWXCard","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCard\/fragments","value":[{"text":"AWXCard","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCard\/navigatorTitle","value":[{"kind":"identifier","text":"AWXCard"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCard~1expiryYear\/title","value":"expiryYear","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCard~1expiryYear\/fragments","value":[{"text":"expiryYear","kind":"identifier"}],"op":"replace"}]}]}