{"schemaVersion":{"minor":3,"major":0,"patch":0},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"mark as deprecated in api changelog 2021-08-06"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentConsents"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPaymentConsent","text":"AWXPaymentConsent","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentConsent"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"Payment consents ."}],"metadata":{"symbolKind":"property","navigatorTitle":[{"text":"paymentConsents","kind":"identifier"}],"modules":[{"name":"Airwallex"}],"platforms":[{"beta":false,"message":"mark as deprecated in api changelog 2021-08-06","deprecated":true,"unavailable":false}],"externalID":"c:objc(cs)AWXPaymentIntent(py)paymentConsents","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentConsents"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AWXPaymentConsent","preciseIdentifier":"c:objc(cs)AWXPaymentConsent"},{"kind":"text","text":"]"}],"role":"symbol","title":"paymentConsents"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent"]]},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent\/paymentConsents","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxpaymentintent\/paymentconsents"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxpaymentintent\/paymentconsents"]}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentIntent/paymentConsents":{"navigatorTitle":[{"kind":"identifier","text":"paymentConsents"}],"deprecated":true,"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent\/paymentConsents","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentConsents"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AWXPaymentConsent","preciseIdentifier":"c:objc(cs)AWXPaymentConsent"},{"kind":"text","text":"]"}],"url":"\/documentation\/airwallex\/awxpaymentintent\/paymentconsents","kind":"symbol","title":"paymentConsents","type":"topic","abstract":[{"text":"Payment consents .","type":"text"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","abstract":[],"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentIntent":{"abstract":[{"code":"AWXPaymentIntent","type":"codeVoice"},{"text":" includes the information of payment intent.","type":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AWXPaymentIntent","kind":"identifier"}],"kind":"symbol","title":"AWXPaymentIntent","navigatorTitle":[{"text":"AWXPaymentIntent","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxpaymentintent"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentConsent":{"navigatorTitle":[{"text":"AWXPaymentConsent","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"AWXPaymentConsent","url":"\/documentation\/airwallex\/awxpaymentconsent","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentConsent","abstract":[{"code":"AWXPaymentConsent","type":"codeVoice"},{"type":"text","text":" includes the info of payment consent."}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentConsent"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":[{"beta":false,"unavailable":false,"deprecated":true}],"op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"paymentConsents","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"paymentConsents","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<AWXPaymentConsent *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"paymentConsents","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/deprecationSummary","value":[{"type":"paragraph","inlineContent":[{"type":"text","text":"mark as deprecated in api changelog 2021-08-06"}]}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentIntent~1paymentConsents\/title","op":"replace","value":"paymentConsents"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentIntent~1paymentConsents\/fragments","op":"replace","value":[{"text":"paymentConsents","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentIntent\/title","op":"replace","value":"AWXPaymentIntent"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentIntent\/fragments","op":"replace","value":[{"kind":"identifier","text":"AWXPaymentIntent"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentIntent\/navigatorTitle","op":"replace","value":[{"text":"AWXPaymentIntent","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentConsent\/title","op":"replace","value":"AWXPaymentConsent"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentConsent\/fragments","op":"replace","value":[{"text":"AWXPaymentConsent","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentConsent\/navigatorTitle","op":"replace","value":[{"text":"AWXPaymentConsent","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}