{"kind":"symbol","metadata":{"role":"symbol","title":"airwallexNetworkToken","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"airwallexNetworkToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"symbolKind":"property","externalID":"s:So7AWXCardC9AirwallexE10NumberTypeO21airwallexNetworkTokenSSvpZ","modules":[{"name":"Airwallex"}],"roleHeading":"Type Property"},"variants":[{"paths":["\/documentation\/airwallex\/awxcard\/numbertype-swift.enum\/airwallexnetworktoken"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCard","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCard\/NumberType-swift.enum"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"airwallexNetworkToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCard\/NumberType-swift.enum\/airwallexNetworkToken","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"for consent payment, we can checkout with this consent without CVC verification"}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCard/NumberType-swift.enum":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCard\/NumberType-swift.enum","url":"\/documentation\/airwallex\/awxcard\/numbertype-swift.enum","type":"topic","title":"AWXCard.NumberType","abstract":[],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NumberType","kind":"identifier"}],"navigatorTitle":[{"text":"NumberType","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCard":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCard","title":"AWXCard","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXCard"}],"kind":"symbol","navigatorTitle":[{"text":"AWXCard","kind":"identifier"}],"abstract":[{"code":"AWXCard","type":"codeVoice"},{"type":"text","text":" includes the information of a card."}],"type":"topic","url":"\/documentation\/airwallex\/awxcard"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","abstract":[],"title":"Airwallex","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCard/NumberType-swift.enum/airwallexNetworkToken":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"airwallexNetworkToken","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","type":"topic","url":"\/documentation\/airwallex\/awxcard\/numbertype-swift.enum\/airwallexnetworktoken","title":"airwallexNetworkToken","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCard\/NumberType-swift.enum\/airwallexNetworkToken","abstract":[{"type":"text","text":"for consent payment, we can checkout with this consent without CVC verification"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCard\/title","op":"replace","value":"AWXCard"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCard\/fragments","op":"replace","value":[{"kind":"identifier","text":"AWXCard"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCard\/navigatorTitle","op":"replace","value":[{"text":"AWXCard","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}