{"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodsRequest\/toCreatedAt","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"Airwallex"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"toCreatedAt"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","externalID":"c:objc(cs)AWXGetPaymentMethodsRequest(py)toCreatedAt","navigatorTitle":[{"kind":"identifier","text":"toCreatedAt"}],"title":"toCreatedAt"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"toCreatedAt"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxgetpaymentmethodsrequest\/tocreatedat"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxgetpaymentmethodsrequest\/tocreatedat"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodsRequest"]]},"kind":"symbol","abstract":[{"text":"The end time of created_at in ISO8601 format","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentMethodsRequest":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodsRequest","abstract":[{"type":"codeVoice","code":"AWXGetPaymentMethodsRequest"},{"text":" includes all of the parameters needed to get payment methods.","type":"text"}],"title":"AWXGetPaymentMethodsRequest","url":"\/documentation\/airwallex\/awxgetpaymentmethodsrequest","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXGetPaymentMethodsRequest","kind":"identifier"}],"navigatorTitle":[{"text":"AWXGetPaymentMethodsRequest","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentMethodsRequest/toCreatedAt":{"navigatorTitle":[{"kind":"identifier","text":"toCreatedAt"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"toCreatedAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodsRequest\/toCreatedAt","type":"topic","abstract":[{"text":"The end time of created_at in ISO8601 format","type":"text"}],"title":"toCreatedAt","url":"\/documentation\/airwallex\/awxgetpaymentmethodsrequest\/tocreatedat","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","title":"Airwallex","abstract":[],"type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"toCreatedAt"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","value":[{"text":"toCreatedAt","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"toCreatedAt","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"AWXGetPaymentMethodsRequest","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodsRequest\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AWXGetPaymentMethodsRequest"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodsRequest\/fragments"},{"op":"replace","value":[{"text":"AWXGetPaymentMethodsRequest","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodsRequest\/navigatorTitle"},{"op":"replace","value":"toCreatedAt","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodsRequest~1toCreatedAt\/title"},{"op":"replace","value":[{"text":"toCreatedAt","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodsRequest~1toCreatedAt\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}