{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"length","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrand"]]},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrand\/length","interfaceLanguage":"swift"},"abstract":[{"text":"The length of  card No.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/airwallex\/awxbrand\/length"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxbrand\/length"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:objc(cs)AWXBrand(py)length","title":"length","navigatorTitle":[{"text":"length","kind":"identifier"}],"role":"symbol","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"length","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"roleHeading":"Instance Property","modules":[{"name":"Airwallex"}]},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXBrand/length":{"title":"length","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"length"}],"url":"\/documentation\/airwallex\/awxbrand\/length","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrand\/length","kind":"symbol","abstract":[{"type":"text","text":"The length of  card No."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"length"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXBrand":{"url":"\/documentation\/airwallex\/awxbrand","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AWXBrand","kind":"identifier"}],"title":"AWXBrand","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWXBrand"}],"abstract":[{"type":"codeVoice","code":"AWXBrand"},{"type":"text","text":" manages the card scheme brand."}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrand"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","url":"\/documentation\/airwallex","title":"Airwallex","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"length"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"length"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"length"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrand~1length\/title","value":"length"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrand~1length\/fragments","value":[{"kind":"identifier","text":"length"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrand\/title","value":"AWXBrand"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrand\/fragments","value":[{"text":"AWXBrand","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrand\/navigatorTitle","value":[{"text":"AWXBrand","kind":"identifier"}]}]}]}