{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rangeEnd"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrand"]]},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrand\/rangeEnd","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The end of  card No."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxbrand\/rangeend"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxbrand\/rangeend"]}],"metadata":{"externalID":"c:objc(cs)AWXBrand(py)rangeEnd","title":"rangeEnd","navigatorTitle":[{"text":"rangeEnd","kind":"identifier"}],"role":"symbol","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rangeEnd"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"roleHeading":"Instance Property","modules":[{"name":"Airwallex"}]},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXBrand":{"url":"\/documentation\/airwallex\/awxbrand","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AWXBrand","kind":"identifier"}],"title":"AWXBrand","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWXBrand"}],"abstract":[{"type":"codeVoice","code":"AWXBrand"},{"type":"text","text":" manages the card scheme brand."}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrand"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","url":"\/documentation\/airwallex","title":"Airwallex","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXBrand/rangeEnd":{"abstract":[{"type":"text","text":"The end of  card No."}],"kind":"symbol","title":"rangeEnd","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrand\/rangeEnd","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rangeEnd","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"rangeEnd","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxbrand\/rangeend"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"rangeEnd","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"rangeEnd"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"rangeEnd","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrand\/title","value":"AWXBrand","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrand\/fragments","value":[{"kind":"identifier","text":"AWXBrand"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrand\/navigatorTitle","value":[{"kind":"identifier","text":"AWXBrand"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrand~1rangeEnd\/title","value":"rangeEnd","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrand~1rangeEnd\/fragments","value":[{"kind":"identifier","text":"rangeEnd"}],"op":"replace"}]}]}