{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"currency","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"inlineContent":[{"type":"text","text":"The three-letter currency code as a String."}],"type":"paragraph"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"Airwallex"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"currency","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"title":"currency()","symbolKind":"method","externalID":"c:@M@Airwallex@objc(cs)Session(im)currency","role":"symbol","navigatorTitle":[{"text":"currency","kind":"identifier"}]},"abstract":[{"text":"Returns the currency code for the current payment.","type":"text"}],"variants":[{"paths":["\/documentation\/airwallex\/session\/currency()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/session\/currency()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session\/currency()"},"kind":"symbol","sections":[],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/Session":{"role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Session","kind":"identifier"}],"navigatorTitle":[{"text":"Session","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session","url":"\/documentation\/airwallex\/session","title":"Session","abstract":[{"type":"codeVoice","code":"Session"},{"type":"text","text":" is a specialized subclass of "},{"type":"codeVoice","code":"AWXSession"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","url":"\/documentation\/airwallex","abstract":[],"title":"Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/Session/currency()":{"abstract":[{"type":"text","text":"Returns the currency code for the current payment."}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session\/currency()","url":"\/documentation\/airwallex\/session\/currency()","navigatorTitle":[{"text":"currency","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"currency","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"kind":"symbol","title":"currency()"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"currency","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"currency","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"currency"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"The three-letter currency code as a String."}],"type":"paragraph"}],"kind":"content"},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"Session","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session\/title","op":"replace"},{"value":[{"text":"Session","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session\/fragments","op":"replace"},{"value":[{"text":"Session","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session\/navigatorTitle","op":"replace"},{"value":"currency","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session~1currency()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"currency","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session~1currency()\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}