{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/session\/paymentintentprovider"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/session\/paymentintentprovider"]}],"metadata":{"externalID":"c:@M@Airwallex@objc(cs)Session(py)paymentIntentProvider","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"Airwallex"}],"navigatorTitle":[{"text":"paymentIntentProvider","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"paymentIntentProvider","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@Airwallex@objc(pl)PaymentIntentProvider","text":"PaymentIntentProvider","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"paymentIntentProvider"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session"]]},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session\/paymentIntentProvider","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"weak","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentIntentProvider","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentIntentProvider","preciseIdentifier":"c:@M@Airwallex@objc(pl)PaymentIntentProvider","text":"PaymentIntentProvider","kind":"typeIdentifier"},{"text":"? { get }","kind":"text"}],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"Provider for delayed payment intent creation."},{"type":"text","text":" "},{"type":"text","text":"When set, the payment intent will be created just before confirmation."}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentIntentProvider":{"abstract":[{"type":"text","text":"A protocol for providing payment intents on-demand during the payment flow."}],"url":"\/documentation\/airwallex\/paymentintentprovider","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentIntentProvider","navigatorTitle":[{"kind":"identifier","text":"PaymentIntentProvider"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentIntentProvider"}],"kind":"symbol","title":"PaymentIntentProvider"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","url":"\/documentation\/airwallex","abstract":[],"title":"Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/Session":{"role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Session","kind":"identifier"}],"navigatorTitle":[{"text":"Session","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session","url":"\/documentation\/airwallex\/session","title":"Session","abstract":[{"type":"codeVoice","code":"Session"},{"type":"text","text":" is a specialized subclass of "},{"type":"codeVoice","code":"AWXSession"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/Session/paymentIntentProvider":{"role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentIntentProvider","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PaymentIntentProvider","preciseIdentifier":"c:@M@Airwallex@objc(pl)PaymentIntentProvider","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"paymentIntentProvider","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session\/paymentIntentProvider","url":"\/documentation\/airwallex\/session\/paymentintentprovider","title":"paymentIntentProvider","abstract":[{"type":"text","text":"Provider for delayed payment intent creation."},{"type":"text","text":" "},{"type":"text","text":"When set, the payment intent will be created just before confirmation."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"paymentIntentProvider"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"paymentIntentProvider","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"weak","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"id<PaymentIntentProvider>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@Airwallex@objc(pl)PaymentIntentProvider"},{"text":" ","kind":"text"},{"text":"paymentIntentProvider","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"PaymentIntentProvider","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentIntentProvider\/title"},{"value":[{"text":"PaymentIntentProvider","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentIntentProvider\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentIntentProvider\/navigatorTitle","value":[{"text":"PaymentIntentProvider","kind":"identifier"}],"op":"replace"},{"value":"Session","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session\/fragments","value":[{"text":"Session","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session\/navigatorTitle","value":[{"text":"Session","kind":"identifier"}],"op":"replace"},{"value":"paymentIntentProvider","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session~1paymentIntentProvider\/title","op":"replace"},{"value":[{"kind":"identifier","text":"paymentIntentProvider"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session~1paymentIntentProvider\/fragments","op":"replace"}]}]}