{"kind":"symbol","metadata":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"externalNetworkToken","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"role":"symbol","symbolKind":"property","roleHeading":"Type Property","modules":[{"name":"Airwallex"}],"externalID":"s:So7AWXCardC9AirwallexE10NumberTypeO20externalNetworkTokenSSvpZ","title":"externalNetworkToken"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCard","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCard\/NumberType-swift.enum"]]},"variants":[{"paths":["\/documentation\/airwallex\/awxcard\/numbertype-swift.enum\/externalnetworktoken"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCard\/NumberType-swift.enum\/externalNetworkToken","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"for consent payment, we can checkout with this consent without CVC verification"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"externalNetworkToken","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"platforms":["iOS"]}]}],"sections":[],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCard":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCard","url":"\/documentation\/airwallex\/awxcard","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXCard"}],"title":"AWXCard","type":"topic","abstract":[{"type":"codeVoice","code":"AWXCard"},{"type":"text","text":" includes the information of a card."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWXCard"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","role":"collection","title":"Airwallex","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCard/NumberType-swift.enum":{"abstract":[],"role":"symbol","navigatorTitle":[{"text":"NumberType","kind":"identifier"}],"title":"AWXCard.NumberType","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NumberType","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCard\/NumberType-swift.enum","url":"\/documentation\/airwallex\/awxcard\/numbertype-swift.enum"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCard/NumberType-swift.enum/externalNetworkToken":{"kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"for consent payment, we can checkout with this consent without CVC verification","type":"text"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCard\/NumberType-swift.enum\/externalNetworkToken","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"externalNetworkToken","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"title":"externalNetworkToken","url":"\/documentation\/airwallex\/awxcard\/numbertype-swift.enum\/externalnetworktoken"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCard\/title","value":"AWXCard"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCard\/fragments","value":[{"text":"AWXCard","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCard\/navigatorTitle","value":[{"text":"AWXCard","kind":"identifier"}]}]}]}