{"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/airwallex\/awxcreatepaymentmethodrequest\/paymentmethod"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxcreatepaymentmethodrequest\/paymentmethod"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCreatePaymentMethodRequest"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCreatePaymentMethodRequest\/paymentMethod"},"abstract":[{"text":"Payment method object.","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentMethod","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod","preciseIdentifier":"c:objc(cs)AWXPaymentMethod","text":"AWXPaymentMethod","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"title":"paymentMethod","externalID":"c:objc(cs)AWXCreatePaymentMethodRequest(py)paymentMethod","modules":[{"name":"Airwallex"}],"roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"text":"paymentMethod","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentMethod","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWXPaymentMethod","preciseIdentifier":"c:objc(cs)AWXPaymentMethod","kind":"typeIdentifier"}]},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCreatePaymentMethodRequest/paymentMethod":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCreatePaymentMethodRequest\/paymentMethod","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentMethod"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AWXPaymentMethod","kind":"typeIdentifier","text":"AWXPaymentMethod"}],"url":"\/documentation\/airwallex\/awxcreatepaymentmethodrequest\/paymentmethod","abstract":[{"type":"text","text":"Payment method object."}],"title":"paymentMethod","navigatorTitle":[{"kind":"identifier","text":"paymentMethod"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentMethod":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentMethod"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod","navigatorTitle":[{"text":"AWXPaymentMethod","kind":"identifier"}],"abstract":[{"code":"AWXPaymentMethod","type":"codeVoice"},{"text":" includes the information of a payment method.","type":"text"}],"title":"AWXPaymentMethod","url":"\/documentation\/airwallex\/awxpaymentmethod","kind":"symbol","role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCreatePaymentMethodRequest":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCreatePaymentMethodRequest","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXCreatePaymentMethodRequest","kind":"identifier"}],"navigatorTitle":[{"text":"AWXCreatePaymentMethodRequest","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"code":"AWXCreatePaymentMethodRequest","type":"codeVoice"},{"type":"text","text":" includes all of the parameters needed to create a payment method."}],"url":"\/documentation\/airwallex\/awxcreatepaymentmethodrequest","title":"AWXCreatePaymentMethodRequest","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"abstract":[],"type":"topic","url":"\/documentation\/airwallex","title":"Airwallex","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"paymentMethod","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"paymentMethod"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)AWXPaymentMethod","kind":"typeIdentifier","text":"AWXPaymentMethod","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod"},{"kind":"text","text":" * "},{"kind":"identifier","text":"paymentMethod"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"paymentMethod","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCreatePaymentMethodRequest~1paymentMethod\/title"},{"value":[{"text":"paymentMethod","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCreatePaymentMethodRequest~1paymentMethod\/fragments"},{"value":"AWXPaymentMethod","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethod\/title"},{"value":[{"kind":"identifier","text":"AWXPaymentMethod"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethod\/fragments"},{"value":[{"kind":"identifier","text":"AWXPaymentMethod"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethod\/navigatorTitle"},{"value":"AWXCreatePaymentMethodRequest","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCreatePaymentMethodRequest\/title"},{"value":[{"kind":"identifier","text":"AWXCreatePaymentMethodRequest"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCreatePaymentMethodRequest\/fragments"},{"value":[{"text":"AWXCreatePaymentMethodRequest","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCreatePaymentMethodRequest\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}