{"variants":[{"paths":["\/documentation\/airwallex\/awxwechatpaysdkresponse\/sign"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxwechatpaysdkresponse\/sign"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","modules":[{"name":"Airwallex"}],"externalID":"c:objc(cs)AWXWeChatPaySDKResponse(py)sign","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sign","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"roleHeading":"Instance Property","title":"sign","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"sign"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sign"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXWeChatPaySDKResponse"]]},"abstract":[{"type":"text","text":"Sign"}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXWeChatPaySDKResponse\/sign","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXWeChatPaySDKResponse":{"kind":"symbol","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXWeChatPaySDKResponse"}],"abstract":[{"type":"codeVoice","code":"AWXWeChatPaySDKResponse"},{"type":"text","text":" includes the parameters for WeChatSDK."}],"title":"AWXWeChatPaySDKResponse","url":"\/documentation\/airwallex\/awxwechatpaysdkresponse","navigatorTitle":[{"kind":"identifier","text":"AWXWeChatPaySDKResponse"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXWeChatPaySDKResponse"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","role":"collection","title":"Airwallex","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXWeChatPaySDKResponse/sign":{"kind":"symbol","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sign"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"abstract":[{"text":"Sign","type":"text"}],"title":"sign","url":"\/documentation\/airwallex\/awxwechatpaysdkresponse\/sign","navigatorTitle":[{"kind":"identifier","text":"sign"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXWeChatPaySDKResponse\/sign"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"sign"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"sign","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"sign"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXWeChatPaySDKResponse\/title","op":"replace","value":"AWXWeChatPaySDKResponse"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXWeChatPaySDKResponse\/fragments","op":"replace","value":[{"text":"AWXWeChatPaySDKResponse","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXWeChatPaySDKResponse\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AWXWeChatPaySDKResponse"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXWeChatPaySDKResponse~1sign\/title","op":"replace","value":"sign"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXWeChatPaySDKResponse~1sign\/fragments","op":"replace","value":[{"kind":"identifier","text":"sign"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}