{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPlaceDetails"]]},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"convertToPaymentContact","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"PKContact","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKContact"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPlaceDetails\/convertToPaymentContact()","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxplacedetails\/converttopaymentcontact()"]},{"paths":["\/documentation\/airwallex\/awxplacedetails\/converttopaymentcontact()"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"Airwallex"}],"roleHeading":"Instance Method","title":"convertToPaymentContact()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"convertToPaymentContact","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)PKContact","text":"PKContact","kind":"typeIdentifier"}],"role":"symbol","symbolKind":"method","navigatorTitle":[{"text":"convertToPaymentContact","kind":"identifier"}],"extendedModule":"Airwallex","externalID":"c:objc(cs)AWXPlaceDetails(im)convertToPaymentContact"},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPlaceDetails/convertToPaymentContact()":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPlaceDetails\/convertToPaymentContact()","kind":"symbol","title":"convertToPaymentContact()","role":"symbol","navigatorTitle":[{"text":"convertToPaymentContact","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"convertToPaymentContact","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)PKContact","text":"PKContact","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/airwallex\/awxplacedetails\/converttopaymentcontact()","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","kind":"symbol","url":"\/documentation\/airwallex","abstract":[],"title":"Airwallex","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPlaceDetails":{"abstract":[{"code":"AWXPlaceDetails","type":"codeVoice"},{"text":" includes the information of a billing address.","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/airwallex\/awxplacedetails","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPlaceDetails","navigatorTitle":[{"kind":"identifier","text":"AWXPlaceDetails"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPlaceDetails"}],"type":"topic","title":"AWXPlaceDetails"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"convertToPaymentContact"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"convertToPaymentContact","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"PKContact","preciseIdentifier":"c:objc(cs)PKContact","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"convertToPaymentContact","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPlaceDetails~1convertToPaymentContact()\/title","value":"convertToPaymentContact"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPlaceDetails~1convertToPaymentContact()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"convertToPaymentContact","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPlaceDetails\/title","value":"AWXPlaceDetails"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPlaceDetails\/fragments","value":[{"kind":"identifier","text":"AWXPlaceDetails"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPlaceDetails\/navigatorTitle","value":[{"kind":"identifier","text":"AWXPlaceDetails"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}