{"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAPIClientConfiguration","interfaceLanguage":"swift"},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSCopying","doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/SQ","doc:\/\/org.cocoapods.Airwallex\/SH"],"type":"conformsTo","kind":"relationships"}],"topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAPIClientConfiguration\/accountID","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAPIClientConfiguration\/baseURL","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAPIClientConfiguration\/clientSecret","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAPIClientConfiguration\/sessionConfiguration"],"generated":true},{"anchor":"Type-Methods","title":"Type Methods","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAPIClientConfiguration\/shared()"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"abstract":[{"type":"codeVoice","code":"AWXAPIClientConfiguration"},{"type":"text","text":" contains the base configuration the API client needs."}],"seeAlsoSections":[{"title":"Preparation","generated":true,"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentConsentOptions","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions"],"anchor":"Preparation"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXAPIClientConfiguration"}]}]}],"metadata":{"title":"AWXAPIClientConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXAPIClientConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"AWXAPIClientConfiguration"}],"role":"symbol","modules":[{"name":"Airwallex"}],"roleHeading":"Class","externalID":"c:objc(cs)AWXAPIClientConfiguration","symbolKind":"class"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"variants":[{"paths":["\/documentation\/airwallex\/awxapiclientconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxapiclientconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXAPIClientConfiguration/baseURL":{"type":"topic","title":"baseURL","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"baseURL","kind":"identifier"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"baseURL","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAPIClientConfiguration\/baseURL","abstract":[{"type":"text","text":"The base URL."}],"kind":"symbol","url":"\/documentation\/airwallex\/awxapiclientconfiguration\/baseurl"},"doc://org.cocoapods.Airwallex/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentIntent":{"url":"\/documentation\/airwallex\/awxpaymentintent","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPaymentIntent","kind":"identifier"}],"role":"symbol","title":"AWXPaymentIntent","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent","navigatorTitle":[{"text":"AWXPaymentIntent","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"AWXPaymentIntent"},{"type":"text","text":" includes the information of payment intent."}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","abstract":[],"role":"collection","url":"\/documentation\/airwallex","title":"Airwallex","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/Session":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Session","kind":"identifier"}],"navigatorTitle":[{"text":"Session","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/airwallex\/session","type":"topic","abstract":[{"type":"codeVoice","code":"Session"},{"text":" is a specialized subclass of ","type":"text"},{"type":"codeVoice","code":"AWXSession"}],"role":"symbol","title":"Session","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session"},"doc://org.cocoapods.Airwallex/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","title":"Swift.CVarArg"},"doc://org.cocoapods.Airwallex/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXAPIClientConfiguration/accountID":{"title":"accountID","url":"\/documentation\/airwallex\/awxapiclientconfiguration\/accountid","kind":"symbol","abstract":[{"text":"The account ID from client secret.","type":"text"}],"navigatorTitle":[{"text":"accountID","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAPIClientConfiguration\/accountID","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accountID","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentConsentOptions":{"type":"topic","title":"PaymentConsentOptions","url":"\/documentation\/airwallex\/paymentconsentoptions","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PaymentConsentOptions"}],"abstract":[{"text":"Options for payment consents","type":"text"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentConsentOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentConsentOptions"}],"kind":"symbol"},"doc://org.cocoapods.Airwallex/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.Airwallex/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.Airwallex/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.Airwallex/objc(pl)NSCopying":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSCopying","title":"NSCopying"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXAPIClientConfiguration":{"title":"AWXAPIClientConfiguration","role":"symbol","url":"\/documentation\/airwallex\/awxapiclientconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXAPIClientConfiguration","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAPIClientConfiguration","abstract":[{"type":"codeVoice","code":"AWXAPIClientConfiguration"},{"type":"text","text":" contains the base configuration the API client needs."}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"AWXAPIClientConfiguration","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXAPIClientConfiguration/sessionConfiguration":{"url":"\/documentation\/airwallex\/awxapiclientconfiguration\/sessionconfiguration","navigatorTitle":[{"text":"sessionConfiguration","kind":"identifier"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sessionConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURLSessionConfiguration","text":"URLSessionConfiguration","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","abstract":[{"type":"text","text":"Optional session configuration"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAPIClientConfiguration\/sessionConfiguration","title":"sessionConfiguration","kind":"symbol"},"doc://org.cocoapods.Airwallex/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject","title":"NSObject"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXAPIClientConfiguration/shared()":{"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAPIClientConfiguration\/shared()","title":"shared()","url":"\/documentation\/airwallex\/awxapiclientconfiguration\/shared()","abstract":[{"text":"Convenience constructor for a configuration.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Self"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"sharedConfiguration"}],"kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXApplePayOptions":{"navigatorTitle":[{"kind":"identifier","text":"AWXApplePayOptions"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions","url":"\/documentation\/airwallex\/awxapplepayoptions","abstract":[{"text":"Object used to construct PKPaymentRequest for Apple Pay.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXApplePayOptions"}],"title":"AWXApplePayOptions"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXAPIClientConfiguration/clientSecret":{"title":"clientSecret","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientSecret"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAPIClientConfiguration\/clientSecret","navigatorTitle":[{"kind":"identifier","text":"clientSecret"}],"url":"\/documentation\/airwallex\/awxapiclientconfiguration\/clientsecret","abstract":[{"type":"text","text":"The client secret for payment."}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"AWXAPIClientConfiguration","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"AWXAPIClientConfiguration"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"AWXAPIClientConfiguration","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAPIClientConfiguration\/accountID","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAPIClientConfiguration\/baseURL","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAPIClientConfiguration\/clientSecret","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAPIClientConfiguration\/sessionConfiguration"],"anchor":"Instance-Properties"},{"generated":true,"title":"Type Methods","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAPIClientConfiguration\/shared()"],"anchor":"Type-Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"],"kind":"relationships"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSCopying"],"kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"value":[{"title":"Preparation","generated":true,"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentConsentOptions","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions"],"anchor":"Preparation"}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXAPIClientConfiguration"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"baseURL","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIClientConfiguration~1baseURL\/title"},{"value":[{"kind":"identifier","text":"baseURL"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIClientConfiguration~1baseURL\/fragments"},{"value":"AWXPaymentIntent","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentIntent\/title"},{"value":[{"text":"AWXPaymentIntent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentIntent\/fragments"},{"value":[{"text":"AWXPaymentIntent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentIntent\/navigatorTitle"},{"value":"Session","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session\/title"},{"value":[{"kind":"identifier","text":"Session"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session\/fragments"},{"value":[{"text":"Session","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session\/navigatorTitle"},{"value":"accountID","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIClientConfiguration~1accountID\/title"},{"value":[{"text":"accountID","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIClientConfiguration~1accountID\/fragments"},{"value":"PaymentConsentOptions","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentConsentOptions\/title"},{"value":[{"text":"PaymentConsentOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentConsentOptions\/fragments"},{"value":[{"text":"PaymentConsentOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentConsentOptions\/navigatorTitle"},{"value":"AWXAPIClientConfiguration","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIClientConfiguration\/title"},{"value":[{"text":"AWXAPIClientConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIClientConfiguration\/fragments"},{"value":[{"text":"AWXAPIClientConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIClientConfiguration\/navigatorTitle"},{"value":"sessionConfiguration","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIClientConfiguration~1sessionConfiguration\/title"},{"value":[{"kind":"identifier","text":"sessionConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIClientConfiguration~1sessionConfiguration\/fragments"},{"value":"sharedConfiguration","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIClientConfiguration~1shared()\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"sharedConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIClientConfiguration~1shared()\/fragments"},{"value":"AWXApplePayOptions","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions\/title"},{"value":[{"text":"AWXApplePayOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions\/fragments"},{"value":[{"text":"AWXApplePayOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions\/navigatorTitle"},{"value":"clientSecret","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIClientConfiguration~1clientSecret\/title"},{"value":[{"text":"clientSecret","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIClientConfiguration~1clientSecret\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}