{"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"]},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/SQ","doc:\/\/org.cocoapods.Airwallex\/SH"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"roleHeading":"Class","role":"symbol","symbolKind":"class","modules":[{"name":"Airwallex"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXCountry","kind":"identifier"}],"externalID":"c:objc(cs)AWXCountry","title":"AWXCountry","navigatorTitle":[{"text":"AWXCountry","kind":"identifier"}]},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"abstract":[{"type":"codeVoice","code":"AWXCountry"},{"type":"text","text":" includes the information of a country."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXCountry"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/airwallex\/awxcountry"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxcountry"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCountry\/init(code:)"],"generated":true},{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCountry\/countryCode","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCountry\/countryName"],"generated":true},{"title":"Type Methods","anchor":"Type-Methods","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCountry\/allCountries()"],"generated":true}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCountry","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","abstract":[],"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/airwallex"},"doc://org.cocoapods.Airwallex/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCountry":{"type":"topic","title":"AWXCountry","navigatorTitle":[{"kind":"identifier","text":"AWXCountry"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCountry","kind":"symbol","url":"\/documentation\/airwallex\/awxcountry","abstract":[{"type":"codeVoice","code":"AWXCountry"},{"type":"text","text":" includes the information of a country."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXCountry"}]},"doc://org.cocoapods.Airwallex/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP"},"doc://org.cocoapods.Airwallex/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SH","type":"unresolvable"},"doc://org.cocoapods.Airwallex/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCountry/countryName":{"url":"\/documentation\/airwallex\/awxcountry\/countryname","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"countryName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"countryName","type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCountry\/countryName","abstract":[{"type":"text","text":"Country name."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"countryName"}]},"doc://org.cocoapods.Airwallex/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"},"doc://org.cocoapods.Airwallex/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SQ","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCountry/countryCode":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"countryCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"type":"topic","title":"countryCode","navigatorTitle":[{"text":"countryCode","kind":"identifier"}],"abstract":[{"text":"Country code.","type":"text"}],"role":"symbol","url":"\/documentation\/airwallex\/awxcountry\/countrycode","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCountry\/countryCode"},"doc://org.cocoapods.Airwallex/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCountry/allCountries()":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCountry\/allCountries()","abstract":[{"text":"Return all of the supported countries.","type":"text"}],"url":"\/documentation\/airwallex\/awxcountry\/allcountries()","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allCountries","kind":"identifier"},{"text":"() -> [","kind":"text"},{"text":"AWXCountry","preciseIdentifier":"c:objc(cs)AWXCountry","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"allCountries","kind":"identifier"}],"type":"topic","title":"allCountries()","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCountry/init(code:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"code","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCountry\/init(code:)","url":"\/documentation\/airwallex\/awxcountry\/init(code:)","navigatorTitle":[{"text":"countryWithCode:","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Get a matched country object.","type":"text"}],"role":"symbol","type":"topic","title":"init(code:)"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"AWXCountry","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"AWXCountry","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"AWXCountry","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCountry\/countryCode","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCountry\/countryName"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCountry\/allCountries()","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCountry\/init(code:)"],"title":"Type Methods","generated":true,"anchor":"Type-Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"],"type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXCountry","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"AWXCountry","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCountry\/title"},{"value":[{"kind":"identifier","text":"AWXCountry"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCountry\/fragments"},{"value":[{"text":"AWXCountry","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCountry\/navigatorTitle"},{"value":"countryName","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCountry~1countryName\/title"},{"value":[{"kind":"identifier","text":"countryName"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCountry~1countryName\/fragments"},{"value":"countryCode","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCountry~1countryCode\/title"},{"value":[{"kind":"identifier","text":"countryCode"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCountry~1countryCode\/fragments"},{"value":"allCountries","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCountry~1allCountries()\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"allCountries","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCountry~1allCountries()\/fragments"},{"value":"countryWithCode:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCountry~1init(code:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"countryWithCode:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCountry~1init(code:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}