{"metadata":{"modules":[{"name":"Airwallex"}],"title":"AWXCountryListViewControllerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXCountryListViewControllerDelegate","kind":"identifier"}],"externalID":"c:objc(pl)AWXCountryListViewControllerDelegate","symbolKind":"protocol","roleHeading":"Protocol","navigatorTitle":[{"kind":"identifier","text":"AWXCountryListViewControllerDelegate"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject"]}],"abstract":[{"text":"A delegate which handles selected country.","type":"text"}],"topicSections":[{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCountryListViewControllerDelegate\/countryListViewController(_:didSelect:)"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/airwallex\/awxcountrylistviewcontrollerdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxcountrylistviewcontrollerdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXCountryListViewControllerDelegate","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCountryListViewControllerDelegate"},"references":{"doc://org.cocoapods.Airwallex/objc(pl)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/airwallex","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCountryListViewControllerDelegate/countryListViewController(_:didSelect:)":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCountryListViewControllerDelegate\/countryListViewController(_:didSelect:)","type":"topic","required":true,"navigatorTitle":[{"kind":"identifier","text":"countryListViewController:didSelectCountry:"}],"role":"symbol","url":"\/documentation\/airwallex\/awxcountrylistviewcontrollerdelegate\/countrylistviewcontroller(_:didselect:)","title":"countryListViewController(_:didSelect:)","abstract":[{"type":"text","text":"This method is called when a country has been selected."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"countryListViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXCountryListViewController","text":"AWXCountryListViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXCountry","text":"AWXCountry"},{"kind":"text","text":")"}],"kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCountryListViewControllerDelegate":{"navigatorTitle":[{"text":"AWXCountryListViewControllerDelegate","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCountryListViewControllerDelegate","kind":"symbol","title":"AWXCountryListViewControllerDelegate","role":"symbol","abstract":[{"type":"text","text":"A delegate which handles selected country."}],"url":"\/documentation\/airwallex\/awxcountrylistviewcontrollerdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXCountryListViewControllerDelegate","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"value":"AWXCountryListViewControllerDelegate","path":"\/metadata\/title","op":"replace"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"AWXCountryListViewControllerDelegate"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"AWXCountryListViewControllerDelegate","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCountryListViewControllerDelegate\/countryListViewController(_:didSelect:)"],"generated":true}],"path":"\/topicSections","op":"replace"},{"value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject"],"type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXCountryListViewControllerDelegate","kind":"identifier"},{"text":" <","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"},{"text":">","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"countryListViewController:didSelectCountry:","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCountryListViewControllerDelegate~1countryListViewController(_:didSelect:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"countryListViewController:didSelectCountry:"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCountryListViewControllerDelegate~1countryListViewController(_:didSelect:)\/fragments","op":"replace"},{"value":"AWXCountryListViewControllerDelegate","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCountryListViewControllerDelegate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AWXCountryListViewControllerDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCountryListViewControllerDelegate\/fragments","op":"replace"},{"value":[{"text":"AWXCountryListViewControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCountryListViewControllerDelegate\/navigatorTitle","op":"replace"}]}]}