{"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDevice","interfaceLanguage":"swift"},"sections":[],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"},{"type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONEncodable","doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/SQ","doc:\/\/org.cocoapods.Airwallex\/SH"],"title":"Conforms To","kind":"relationships"}],"topicSections":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDevice\/deviceId"],"generated":true,"title":"Instance Properties"},{"anchor":"Type-Methods","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDevice\/withRiskSessionId()"],"generated":true,"title":"Type Methods"}],"abstract":[{"code":"AWXDevice","type":"codeVoice"},{"text":" includes the information of device.","type":"text"}],"variants":[{"paths":["\/documentation\/airwallex\/awxdevice"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxdevice"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"class","title":"AWXDevice","roleHeading":"Class","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXDevice","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AWXDevice"}],"modules":[{"name":"Airwallex"}],"externalID":"c:objc(cs)AWXDevice"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXDevice"}]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXDevice":{"role":"symbol","type":"topic","abstract":[{"code":"AWXDevice","type":"codeVoice"},{"text":" includes the information of device.","type":"text"}],"url":"\/documentation\/airwallex\/awxdevice","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXDevice","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDevice","title":"AWXDevice","navigatorTitle":[{"kind":"identifier","text":"AWXDevice"}],"kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","abstract":[],"title":"Airwallex","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXDevice/withRiskSessionId()":{"navigatorTitle":[{"text":"deviceWithRiskSessionId","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxdevice\/withrisksessionid()","type":"topic","abstract":[{"type":"text","text":"Return an instance with AirwallexRisk session id as device id"}],"title":"withRiskSessionId()","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDevice\/withRiskSessionId()","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"withRiskSessionId","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"}]},"doc://org.cocoapods.Airwallex/SH":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://org.cocoapods.Airwallex/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.Airwallex/objc(cs)NSObject":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://org.cocoapods.Airwallex/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXDevice/deviceId":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDevice\/deviceId","kind":"symbol","type":"topic","title":"deviceId","url":"\/documentation\/airwallex\/awxdevice\/deviceid","navigatorTitle":[{"text":"deviceId","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deviceId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Device id."}]},"doc://org.cocoapods.Airwallex/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXJSONEncodable":{"title":"AWXJSONEncodable","navigatorTitle":[{"kind":"identifier","text":"AWXJSONEncodable"}],"type":"topic","url":"\/documentation\/airwallex\/awxjsonencodable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXJSONEncodable","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONEncodable","abstract":[]},"doc://org.cocoapods.Airwallex/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.Airwallex/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"AWXDevice","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"AWXDevice"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"AWXDevice","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDevice\/deviceId"]},{"anchor":"Type-Methods","title":"Type Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDevice\/withRiskSessionId()"]}],"path":"\/topicSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONEncodable"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXDevice"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"AWXDevice","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDevice\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AWXDevice"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDevice\/fragments"},{"op":"replace","value":[{"text":"AWXDevice","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDevice\/navigatorTitle"},{"op":"replace","value":"deviceWithRiskSessionId","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDevice~1withRiskSessionId()\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"deviceWithRiskSessionId"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDevice~1withRiskSessionId()\/fragments"},{"op":"replace","value":"deviceId","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDevice~1deviceId\/title"},{"op":"replace","value":[{"text":"deviceId","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDevice~1deviceId\/fragments"},{"op":"replace","value":"AWXJSONEncodable","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONEncodable\/title"},{"op":"replace","value":[{"text":"AWXJSONEncodable","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONEncodable\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AWXJSONEncodable"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONEncodable\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}