{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONDecodable"},"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAddress","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAuthenticationData","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBank","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCandidate","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCard","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardScheme","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentNextAction","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXField","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXFieldValidation","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentAttempt","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentConsent","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethodType","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPlaceDetails","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXResources","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSchema","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXWeChatPaySDKResponse"],"type":"conformingTypes","kind":"relationships","title":"Conforming Types"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxjsondecodable"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxjsondecodable"]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"metadata":{"externalID":"c:objc(pl)AWXJSONDecodable","role":"symbol","symbolKind":"protocol","roleHeading":"Protocol","modules":[{"name":"Airwallex"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXJSONDecodable"}],"navigatorTitle":[{"kind":"identifier","text":"AWXJSONDecodable"}],"title":"AWXJSONDecodable"},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONDecodable\/decode(fromJSON:)"],"anchor":"Type-Methods","title":"Type Methods","generated":true}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXJSONDecodable","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentIntent":{"abstract":[{"code":"AWXPaymentIntent","type":"codeVoice"},{"text":" includes the information of payment intent.","type":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AWXPaymentIntent","kind":"identifier"}],"kind":"symbol","title":"AWXPaymentIntent","navigatorTitle":[{"text":"AWXPaymentIntent","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxpaymentintent"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCandidate":{"kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"codeVoice","code":"AWXCandidate"},{"type":"text","text":" includes the values of list"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXCandidate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCandidate","navigatorTitle":[{"text":"AWXCandidate","kind":"identifier"}],"title":"AWXCandidate","url":"\/documentation\/airwallex\/awxcandidate"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXResources":{"role":"symbol","title":"AWXResources","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXResources","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXResources","url":"\/documentation\/airwallex\/awxresources","abstract":[{"type":"codeVoice","code":"AWXResources"},{"type":"text","text":" includes the resources of payment method."}],"navigatorTitle":[{"text":"AWXResources","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXJSONDecodable/decode(fromJSON:)":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONDecodable\/decode(fromJSON:)","required":true,"url":"\/documentation\/airwallex\/awxjsondecodable\/decode(fromjson:)","type":"topic","kind":"symbol","title":"decode(fromJSON:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decode","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fromJSON","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?) -> ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"decodeFromJSON:","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardScheme":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXCardScheme","kind":"identifier"}],"navigatorTitle":[{"text":"AWXCardScheme","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxcardscheme","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardScheme","kind":"symbol","title":"AWXCardScheme","role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCard":{"url":"\/documentation\/airwallex\/awxcard","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXCard","kind":"identifier"}],"navigatorTitle":[{"text":"AWXCard","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCard","title":"AWXCard","role":"symbol","abstract":[{"code":"AWXCard","type":"codeVoice"},{"text":" includes the information of a card.","type":"text"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXField":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXField","navigatorTitle":[{"kind":"identifier","text":"AWXField"}],"role":"symbol","type":"topic","url":"\/documentation\/airwallex\/awxfield","title":"AWXField","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXField"}],"abstract":[{"type":"codeVoice","code":"AWXField"},{"type":"text","text":" includes the field of schema."}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPlaceDetails":{"title":"AWXPlaceDetails","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPlaceDetails","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPlaceDetails","kind":"identifier"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"AWXPlaceDetails","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxplacedetails","abstract":[{"type":"codeVoice","code":"AWXPlaceDetails"},{"type":"text","text":" includes the information of a billing address."}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentAttempt":{"title":"AWXPaymentAttempt","type":"topic","navigatorTitle":[{"text":"AWXPaymentAttempt","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"AWXPaymentAttempt"},{"type":"text","text":" includes the information of payment attempt."}],"url":"\/documentation\/airwallex\/awxpaymentattempt","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPaymentAttempt","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentAttempt"},"doc://org.cocoapods.Airwallex/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","title":"NSObject","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXJSONDecodable":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONDecodable","title":"AWXJSONDecodable","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXJSONDecodable"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"AWXJSONDecodable","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxjsondecodable","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentMethodType":{"url":"\/documentation\/airwallex\/awxpaymentmethodtype","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPaymentMethodType","kind":"identifier"}],"title":"AWXPaymentMethodType","abstract":[{"type":"codeVoice","code":"AWXPaymentMethodType"},{"text":" includes the information of a payment method.","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethodType","role":"symbol","navigatorTitle":[{"text":"AWXPaymentMethodType","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXFieldValidation":{"role":"symbol","url":"\/documentation\/airwallex\/awxfieldvalidation","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXFieldValidation","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"validation returned for AWXField","type":"text"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXFieldValidation","navigatorTitle":[{"text":"AWXFieldValidation","kind":"identifier"}],"title":"AWXFieldValidation","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXWeChatPaySDKResponse":{"title":"AWXWeChatPaySDKResponse","kind":"symbol","url":"\/documentation\/airwallex\/awxwechatpaysdkresponse","abstract":[{"code":"AWXWeChatPaySDKResponse","type":"codeVoice"},{"text":" includes the parameters for WeChatSDK.","type":"text"}],"navigatorTitle":[{"text":"AWXWeChatPaySDKResponse","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXWeChatPaySDKResponse","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXWeChatPaySDKResponse"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXAuthenticationData":{"abstract":[{"code":"AWXAuthenticationData","type":"codeVoice"},{"type":"text","text":" includes the parameters for 3ds authentication."}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAuthenticationData","kind":"symbol","title":"AWXAuthenticationData","role":"symbol","type":"topic","url":"\/documentation\/airwallex\/awxauthenticationdata","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXAuthenticationData"}],"navigatorTitle":[{"text":"AWXAuthenticationData","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentConsent":{"navigatorTitle":[{"text":"AWXPaymentConsent","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"AWXPaymentConsent","url":"\/documentation\/airwallex\/awxpaymentconsent","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentConsent","abstract":[{"code":"AWXPaymentConsent","type":"codeVoice"},{"type":"text","text":" includes the info of payment consent."}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentConsent"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSchema":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXSchema"}],"abstract":[{"code":"AWXSchema","type":"codeVoice"},{"type":"text","text":" includes the schema of payment method."}],"title":"AWXSchema","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSchema","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWXSchema"}],"url":"\/documentation\/airwallex\/awxschema"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXAddress":{"url":"\/documentation\/airwallex\/awxaddress","kind":"symbol","abstract":[{"type":"codeVoice","code":"AWXAddress"},{"text":" includes the information of an address.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXAddress","kind":"identifier"}],"title":"AWXAddress","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAddress","navigatorTitle":[{"text":"AWXAddress","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXBank":{"type":"topic","title":"AWXBank","url":"\/documentation\/airwallex\/awxbank","navigatorTitle":[{"text":"AWXBank","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXBank","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBank","kind":"symbol","abstract":[{"type":"codeVoice","code":"AWXBank"},{"text":" includes the bank info.","type":"text"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentMethod":{"abstract":[{"type":"codeVoice","code":"AWXPaymentMethod"},{"type":"text","text":" includes the information of a payment method."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentMethod"}],"kind":"symbol","url":"\/documentation\/airwallex\/awxpaymentmethod","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod","title":"AWXPaymentMethod","navigatorTitle":[{"kind":"identifier","text":"AWXPaymentMethod"}],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXConfirmPaymentNextAction":{"url":"\/documentation\/airwallex\/awxconfirmpaymentnextaction","title":"AWXConfirmPaymentNextAction","type":"topic","navigatorTitle":[{"text":"AWXConfirmPaymentNextAction","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXConfirmPaymentNextAction","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentNextAction","kind":"symbol","abstract":[{"type":"codeVoice","code":"AWXConfirmPaymentNextAction"},{"type":"text","text":" includes the parameters for next action."}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","abstract":[],"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/airwallex"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"AWXJSONDecodable"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AWXJSONDecodable"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"AWXJSONDecodable","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Type Methods","generated":true,"anchor":"Type-Methods","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONDecodable\/decode(fromJSON:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAddress","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAuthenticationData","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBank","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCandidate","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCard","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardScheme","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentNextAction","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXField","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXFieldValidation","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentAttempt","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentConsent","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethodType","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPlaceDetails","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXResources","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSchema","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXWeChatPaySDKResponse"],"kind":"relationships","type":"conformingTypes","title":"Conforming Types"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXJSONDecodable","kind":"identifier"},{"text":" <","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"},{"text":">","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentIntent\/title","value":"AWXPaymentIntent"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentIntent\/fragments","value":[{"text":"AWXPaymentIntent","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentIntent\/navigatorTitle","value":[{"kind":"identifier","text":"AWXPaymentIntent"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCandidate\/title","value":"AWXCandidate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCandidate\/fragments","value":[{"kind":"identifier","text":"AWXCandidate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCandidate\/navigatorTitle","value":[{"text":"AWXCandidate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXResources\/title","value":"AWXResources"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXResources\/fragments","value":[{"kind":"identifier","text":"AWXResources"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXResources\/navigatorTitle","value":[{"text":"AWXResources","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONDecodable~1decode(fromJSON:)\/title","value":"decodeFromJSON:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONDecodable~1decode(fromJSON:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"decodeFromJSON:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardScheme\/title","value":"AWXCardScheme"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardScheme\/fragments","value":[{"kind":"identifier","text":"AWXCardScheme"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardScheme\/navigatorTitle","value":[{"text":"AWXCardScheme","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCard\/title","value":"AWXCard"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCard\/fragments","value":[{"kind":"identifier","text":"AWXCard"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCard\/navigatorTitle","value":[{"kind":"identifier","text":"AWXCard"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXField\/title","value":"AWXField"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXField\/fragments","value":[{"kind":"identifier","text":"AWXField"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXField\/navigatorTitle","value":[{"kind":"identifier","text":"AWXField"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPlaceDetails\/title","value":"AWXPlaceDetails"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPlaceDetails\/fragments","value":[{"text":"AWXPlaceDetails","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPlaceDetails\/navigatorTitle","value":[{"kind":"identifier","text":"AWXPlaceDetails"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentAttempt\/title","value":"AWXPaymentAttempt"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentAttempt\/fragments","value":[{"text":"AWXPaymentAttempt","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentAttempt\/navigatorTitle","value":[{"kind":"identifier","text":"AWXPaymentAttempt"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONDecodable\/title","value":"AWXJSONDecodable"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONDecodable\/fragments","value":[{"kind":"identifier","text":"AWXJSONDecodable"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONDecodable\/navigatorTitle","value":[{"text":"AWXJSONDecodable","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethodType\/title","value":"AWXPaymentMethodType"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethodType\/fragments","value":[{"text":"AWXPaymentMethodType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethodType\/navigatorTitle","value":[{"kind":"identifier","text":"AWXPaymentMethodType"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXFieldValidation\/title","value":"AWXFieldValidation"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXFieldValidation\/fragments","value":[{"text":"AWXFieldValidation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXFieldValidation\/navigatorTitle","value":[{"kind":"identifier","text":"AWXFieldValidation"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXWeChatPaySDKResponse\/title","value":"AWXWeChatPaySDKResponse"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXWeChatPaySDKResponse\/fragments","value":[{"text":"AWXWeChatPaySDKResponse","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXWeChatPaySDKResponse\/navigatorTitle","value":[{"text":"AWXWeChatPaySDKResponse","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAuthenticationData\/title","value":"AWXAuthenticationData"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAuthenticationData\/fragments","value":[{"text":"AWXAuthenticationData","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAuthenticationData\/navigatorTitle","value":[{"text":"AWXAuthenticationData","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentConsent\/title","value":"AWXPaymentConsent"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentConsent\/fragments","value":[{"kind":"identifier","text":"AWXPaymentConsent"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentConsent\/navigatorTitle","value":[{"kind":"identifier","text":"AWXPaymentConsent"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSchema\/title","value":"AWXSchema"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSchema\/fragments","value":[{"text":"AWXSchema","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSchema\/navigatorTitle","value":[{"text":"AWXSchema","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAddress\/title","value":"AWXAddress"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAddress\/fragments","value":[{"kind":"identifier","text":"AWXAddress"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAddress\/navigatorTitle","value":[{"text":"AWXAddress","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBank\/title","value":"AWXBank"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBank\/fragments","value":[{"text":"AWXBank","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBank\/navigatorTitle","value":[{"text":"AWXBank","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethod\/title","value":"AWXPaymentMethod"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethod\/fragments","value":[{"kind":"identifier","text":"AWXPaymentMethod"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethod\/navigatorTitle","value":[{"text":"AWXPaymentMethod","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentNextAction\/title","value":"AWXConfirmPaymentNextAction"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentNextAction\/fragments","value":[{"kind":"identifier","text":"AWXConfirmPaymentNextAction"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentNextAction\/navigatorTitle","value":[{"text":"AWXConfirmPaymentNextAction","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}