{"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXSDKErrorCode","kind":"identifier"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSDKErrorCode","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSDKErrorCode\/internalError","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSDKErrorCode\/userCancelled"],"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases"},{"title":"Initializers","anchor":"Initializers","generated":true,"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSDKErrorCode\/init(rawValue:)"]},{"title":"Default Implementations","anchor":"Default-Implementations","generated":true,"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSDKErrorCode\/Equatable-Implementations","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSDKErrorCode\/RawRepresentable-Implementations"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","sections":[],"relationshipsSections":[{"type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.Airwallex\/s15BitwiseCopyableP","doc:\/\/org.cocoapods.Airwallex\/SQ","doc:\/\/org.cocoapods.Airwallex\/SH","doc:\/\/org.cocoapods.Airwallex\/SY","doc:\/\/org.cocoapods.Airwallex\/s8SendableP","doc:\/\/org.cocoapods.Airwallex\/s16SendableMetatypeP"],"kind":"relationships","title":"Conforms To"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxsdkerrorcode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxsdkerrorcode"]}],"metadata":{"externalID":"c:@E@AWXSDKErrorCode","title":"AWXSDKErrorCode","navigatorTitle":[{"kind":"identifier","text":"AWXSDKErrorCode"}],"role":"symbol","symbolKind":"enum","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXSDKErrorCode","kind":"identifier"}],"roleHeading":"Enumeration","modules":[{"name":"Airwallex"}]},"references":{"doc://org.cocoapods.Airwallex/SQ":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.Airwallex/s15BitwiseCopyableP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s15BitwiseCopyableP","title":"Swift.BitwiseCopyable","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSDKErrorCode/userCancelled":{"title":"AWXSDKErrorCode.userCancelled","type":"topic","role":"symbol","navigatorTitle":[{"text":"AWXSDKErrorCodeUserCancelled","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxsdkerrorcode\/usercancelled","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSDKErrorCode\/userCancelled","kind":"symbol","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"userCancelled","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSDKErrorCode/internalError":{"kind":"symbol","type":"topic","abstract":[],"role":"symbol","url":"\/documentation\/airwallex\/awxsdkerrorcode\/internalerror","title":"AWXSDKErrorCode.internalError","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSDKErrorCode\/internalError","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalError","kind":"identifier"}],"navigatorTitle":[{"text":"AWXSDKErrorCodeInternalError","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/s16SendableMetatypeP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s16SendableMetatypeP","title":"Swift.SendableMetatype","type":"unresolvable"},"doc://org.cocoapods.Airwallex/s8SendableP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSDKErrorCode/Equatable-Implementations":{"kind":"article","type":"topic","abstract":[],"role":"collectionGroup","url":"\/documentation\/airwallex\/awxsdkerrorcode\/equatable-implementations","title":"Equatable Implementations","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSDKErrorCode\/Equatable-Implementations"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","url":"\/documentation\/airwallex","title":"Airwallex","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSDKErrorCode/init(rawValue:)":{"kind":"symbol","type":"topic","abstract":[],"role":"symbol","url":"\/documentation\/airwallex\/awxsdkerrorcode\/init(rawvalue:)","title":"init(rawValue:)","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSDKErrorCode\/init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSDKErrorCode/RawRepresentable-Implementations":{"kind":"article","type":"topic","abstract":[],"role":"collectionGroup","url":"\/documentation\/airwallex\/awxsdkerrorcode\/rawrepresentable-implementations","title":"RawRepresentable Implementations","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSDKErrorCode\/RawRepresentable-Implementations"},"doc://org.cocoapods.Airwallex/SY":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://org.cocoapods.Airwallex/SH":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSDKErrorCode":{"kind":"symbol","type":"topic","abstract":[],"role":"symbol","url":"\/documentation\/airwallex\/awxsdkerrorcode","title":"AWXSDKErrorCode","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSDKErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXSDKErrorCode"}],"navigatorTitle":[{"kind":"identifier","text":"AWXSDKErrorCode"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","value":"AWXSDKErrorCode","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"AWXSDKErrorCode","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"AWXSDKErrorCode","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"anchor":"Enumeration-Cases","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSDKErrorCode\/internalError","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSDKErrorCode\/userCancelled"],"generated":true,"title":"Enumeration Cases"}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXSDKErrorCode","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSDKErrorCode~1userCancelled\/title","value":"AWXSDKErrorCodeUserCancelled","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSDKErrorCode~1userCancelled\/fragments","value":[{"text":"AWXSDKErrorCodeUserCancelled","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSDKErrorCode~1internalError\/title","value":"AWXSDKErrorCodeInternalError","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSDKErrorCode~1internalError\/fragments","value":[{"text":"AWXSDKErrorCodeInternalError","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSDKErrorCode\/title","value":"AWXSDKErrorCode","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSDKErrorCode\/fragments","value":[{"text":"AWXSDKErrorCode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSDKErrorCode\/navigatorTitle","value":[{"text":"AWXSDKErrorCode","kind":"identifier"}],"op":"replace"}]}]}