{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXThreeDSWaitingUserInfoInput"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"AWXThreeDSWaitingUserInfoInput"}],"externalID":"c:@AWXThreeDSWaitingUserInfoInput","symbolKind":"var","modules":[{"name":"Airwallex"}],"roleHeading":"Global Variable","role":"symbol","title":"AWXThreeDSWaitingUserInfoInput","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXThreeDSWaitingUserInfoInput","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXThreeDSWaitingUserInfoInput","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxthreedswaitinguserinfoinput"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxthreedswaitinguserinfoinput"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXThreeDSWaitingUserInfoInput":{"url":"\/documentation\/airwallex\/awxthreedswaitinguserinfoinput","title":"AWXThreeDSWaitingUserInfoInput","type":"topic","abstract":[],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"AWXThreeDSWaitingUserInfoInput","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXThreeDSWaitingUserInfoInput","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"AWXThreeDSWaitingUserInfoInput","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","type":"topic","role":"collection","title":"Airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Global Variable"},{"path":"\/metadata\/title","op":"replace","value":"AWXThreeDSWaitingUserInfoInput"},{"path":"\/metadata\/symbolKind","op":"replace","value":"var"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"AWXThreeDSWaitingUserInfoInput","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXThreeDSWaitingUserInfoInput","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXThreeDSWaitingUserInfoInput\/title","op":"replace","value":"AWXThreeDSWaitingUserInfoInput"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXThreeDSWaitingUserInfoInput\/fragments","op":"replace","value":[{"text":"AWXThreeDSWaitingUserInfoInput","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}