{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXVerifyPaymentConsentResponse"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXVerifyPaymentConsentResponse"},"kind":"symbol","relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXResponse"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/SQ","doc:\/\/org.cocoapods.Airwallex\/SH"],"type":"conformsTo"}],"metadata":{"roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"AWXVerifyPaymentConsentResponse"}],"symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXVerifyPaymentConsentResponse","kind":"identifier"}],"modules":[{"name":"Airwallex"}],"role":"symbol","externalID":"c:objc(cs)AWXVerifyPaymentConsentResponse","title":"AWXVerifyPaymentConsentResponse"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"codeVoice","code":"AWXVerifyPaymentConsentResponse"},{"type":"text","text":" includes the response of payment consent."}],"topicSections":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXVerifyPaymentConsentResponse\/initialPaymentIntentId","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXVerifyPaymentConsentResponse\/nextAction","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXVerifyPaymentConsentResponse\/status"],"anchor":"Instance-Properties"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxverifypaymentconsentresponse"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxverifypaymentconsentresponse"]}],"sections":[],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXVerifyPaymentConsentResponse/nextAction":{"abstract":[{"type":"text","text":"Next action."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"nextAction"}],"title":"nextAction","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextAction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXConfirmPaymentNextAction","text":"AWXConfirmPaymentNextAction"},{"kind":"text","text":"?"}],"role":"symbol","kind":"symbol","url":"\/documentation\/airwallex\/awxverifypaymentconsentresponse\/nextaction","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXVerifyPaymentConsentResponse\/nextAction"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXVerifyPaymentConsentResponse/initialPaymentIntentId":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"initialPaymentIntentId"}],"abstract":[{"text":"Payment intent id.","type":"text"}],"url":"\/documentation\/airwallex\/awxverifypaymentconsentresponse\/initialpaymentintentid","title":"initialPaymentIntentId","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXVerifyPaymentConsentResponse\/initialPaymentIntentId","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialPaymentIntentId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"doc://org.cocoapods.Airwallex/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SH"},"doc://org.cocoapods.Airwallex/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"title":"Airwallex","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/airwallex","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXVerifyPaymentConsentResponse":{"type":"topic","navigatorTitle":[{"text":"AWXVerifyPaymentConsentResponse","kind":"identifier"}],"abstract":[{"code":"AWXVerifyPaymentConsentResponse","type":"codeVoice"},{"text":" includes the response of payment consent.","type":"text"}],"url":"\/documentation\/airwallex\/awxverifypaymentconsentresponse","title":"AWXVerifyPaymentConsentResponse","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXVerifyPaymentConsentResponse","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXVerifyPaymentConsentResponse","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXVerifyPaymentConsentResponse/status":{"title":"status","url":"\/documentation\/airwallex\/awxverifypaymentconsentresponse\/status","role":"symbol","abstract":[{"type":"text","text":"Payment status."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"status"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXVerifyPaymentConsentResponse\/status"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXResponse":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXResponse","type":"topic","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXResponse","kind":"identifier"}],"navigatorTitle":[{"text":"AWXResponse","kind":"identifier"}],"title":"AWXResponse","url":"\/documentation\/airwallex\/awxresponse"},"doc://org.cocoapods.Airwallex/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SQ"},"doc://org.cocoapods.Airwallex/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.Airwallex/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.Airwallex/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"AWXVerifyPaymentConsentResponse","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"AWXVerifyPaymentConsentResponse","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AWXVerifyPaymentConsentResponse"}],"op":"replace"},{"path":"\/topicSections","value":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXVerifyPaymentConsentResponse\/initialPaymentIntentId","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXVerifyPaymentConsentResponse\/nextAction","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXVerifyPaymentConsentResponse\/status"],"generated":true}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXResponse"]}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXVerifyPaymentConsentResponse","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"AWXResponse","preciseIdentifier":"c:objc(cs)AWXResponse","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXResponse"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXVerifyPaymentConsentResponse~1nextAction\/title","value":"nextAction","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXVerifyPaymentConsentResponse~1nextAction\/fragments","value":[{"text":"nextAction","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXVerifyPaymentConsentResponse~1initialPaymentIntentId\/title","value":"initialPaymentIntentId","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXVerifyPaymentConsentResponse~1initialPaymentIntentId\/fragments","value":[{"kind":"identifier","text":"initialPaymentIntentId"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXVerifyPaymentConsentResponse\/title","value":"AWXVerifyPaymentConsentResponse","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXVerifyPaymentConsentResponse\/fragments","value":[{"kind":"identifier","text":"AWXVerifyPaymentConsentResponse"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXVerifyPaymentConsentResponse\/navigatorTitle","value":[{"kind":"identifier","text":"AWXVerifyPaymentConsentResponse"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXVerifyPaymentConsentResponse~1status\/title","value":"status","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXVerifyPaymentConsentResponse~1status\/fragments","value":[{"text":"status","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXResponse\/title","value":"AWXResponse","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXResponse\/fragments","value":[{"kind":"identifier","text":"AWXResponse"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXResponse\/navigatorTitle","value":[{"kind":"identifier","text":"AWXResponse"}],"op":"replace"}]}]}