{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/formatnexttriggerbytype(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/formatnexttriggerbytype(_:)"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormatNextTriggerByType"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexNextTriggerByType","preciseIdentifier":"c:@E@AirwallexNextTriggerByType","text":"AirwallexNextTriggerByType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"sections":[],"metadata":{"role":"symbol","externalID":"c:@F@FormatNextTriggerByType","roleHeading":"Function","navigatorTitle":[{"text":"FormatNextTriggerByType","kind":"identifier"}],"modules":[{"name":"Airwallex"}],"title":"FormatNextTriggerByType(_:)","symbolKind":"func","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormatNextTriggerByType","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AirwallexNextTriggerByType","kind":"typeIdentifier","preciseIdentifier":"c:@E@AirwallexNextTriggerByType"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/FormatNextTriggerByType(_:)","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/FormatNextTriggerByType(_:)":{"url":"\/documentation\/airwallex\/formatnexttriggerbytype(_:)","role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/FormatNextTriggerByType(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormatNextTriggerByType","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AirwallexNextTriggerByType","kind":"typeIdentifier","preciseIdentifier":"c:@E@AirwallexNextTriggerByType"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","title":"FormatNextTriggerByType(_:)","navigatorTitle":[{"text":"FormatNextTriggerByType","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","url":"\/documentation\/airwallex","role":"collection","kind":"symbol","abstract":[],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexNextTriggerByType":{"type":"topic","url":"\/documentation\/airwallex\/airwallexnexttriggerbytype","role":"symbol","abstract":[],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AirwallexNextTriggerByType","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexNextTriggerByType","navigatorTitle":[{"text":"AirwallexNextTriggerByType","kind":"identifier"}],"title":"AirwallexNextTriggerByType"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Function","op":"replace"},{"path":"\/metadata\/title","value":"FormatNextTriggerByType","op":"replace"},{"path":"\/metadata\/symbolKind","value":"func","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"FormatNextTriggerByType","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"FormatNextTriggerByType","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@AirwallexNextTriggerByType","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexNextTriggerByType","text":"AirwallexNextTriggerByType","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"type","kind":"internalParam"},{"text":");","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1FormatNextTriggerByType(_:)\/title","value":"FormatNextTriggerByType","op":"replace"},{"value":[{"kind":"identifier","text":"FormatNextTriggerByType"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1FormatNextTriggerByType(_:)\/fragments"},{"value":"AirwallexNextTriggerByType","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexNextTriggerByType\/title"},{"value":[{"text":"AirwallexNextTriggerByType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexNextTriggerByType\/fragments"},{"value":[{"text":"AirwallexNextTriggerByType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexNextTriggerByType\/navigatorTitle"}]}]}