{"topicSections":[{"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSchedule\/init(period:periodUnit:)"],"generated":true},{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSchedule\/period","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSchedule\/periodUnit"],"generated":true},{"generated":true,"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSchedule\/Encodable-Implementations"],"title":"Default Implementations","anchor":"Default-Implementations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","sections":[],"metadata":{"modules":[{"name":"Airwallex"}],"roleHeading":"Class","role":"symbol","navigatorTitle":[{"text":"PaymentSchedule","kind":"identifier"}],"symbolKind":"class","externalID":"c:@M@Airwallex@objc(cs)PaymentSchedule","title":"PaymentSchedule","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PaymentSchedule","kind":"identifier"}]},"abstract":[{"text":"Payment schedule configuration","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"},{"type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","doc:\/\/org.cocoapods.Airwallex\/s8CopyableP","doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/SE","doc:\/\/org.cocoapods.Airwallex\/SQ","doc:\/\/org.cocoapods.Airwallex\/SH"],"kind":"relationships","title":"Conforms To"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSchedule"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentSchedule"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/airwallex\/paymentschedule"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/paymentschedule"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.Airwallex/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SE"},"doc://org.cocoapods.Airwallex/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://org.cocoapods.Airwallex/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","type":"unresolvable"},"doc://org.cocoapods.Airwallex/SQ":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.Airwallex/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SH"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentSchedule":{"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/airwallex\/paymentschedule","navigatorTitle":[{"kind":"identifier","text":"PaymentSchedule"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSchedule","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentSchedule"}],"title":"PaymentSchedule","abstract":[{"text":"Payment schedule configuration","type":"text"}]},"doc://org.cocoapods.Airwallex/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentSchedule/init(period:periodUnit:)":{"abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"text":"initWithPeriod:periodUnit:","kind":"identifier"}],"url":"\/documentation\/airwallex\/paymentschedule\/init(period:periodunit:)","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSchedule\/init(period:periodUnit:)","title":"init(period:periodUnit:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"period","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"periodUnit","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PeriodUnit","preciseIdentifier":"c:@M@Airwallex@E@PeriodUnit","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol"},"doc://org.cocoapods.Airwallex/s8CopyableP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s8CopyableP","type":"unresolvable","title":"Swift.Copyable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentSchedule/period":{"abstract":[{"text":"The number of period units between billing cycles.","type":"text"},{"text":" ","type":"text"},{"text":"Required when merchant_trigger_reason = scheduled","type":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"period","kind":"identifier"}],"url":"\/documentation\/airwallex\/paymentschedule\/period","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSchedule\/period","title":"period","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"period","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"kind":"symbol"},"doc://org.cocoapods.Airwallex/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentSchedule/Encodable-Implementations":{"abstract":[],"type":"topic","role":"collectionGroup","url":"\/documentation\/airwallex\/paymentschedule\/encodable-implementations","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSchedule\/Encodable-Implementations","title":"Encodable Implementations","kind":"article"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentSchedule/periodUnit":{"abstract":[{"text":"Specifies billing frequency. One of DAY, WEEK, MONTH, and YEAR.","type":"text"},{"text":" ","type":"text"},{"text":"Required when merchant_trigger_reason = scheduled","type":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"periodUnit","kind":"identifier"}],"url":"\/documentation\/airwallex\/paymentschedule\/periodunit","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSchedule\/periodUnit","title":"periodUnit","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"periodUnit","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PeriodUnit","preciseIdentifier":"c:@M@Airwallex@E@PeriodUnit","kind":"typeIdentifier"}],"kind":"symbol"},"doc://org.cocoapods.Airwallex/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","type":"topic","role":"collection","title":"Airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"PaymentSchedule","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"PaymentSchedule","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"PaymentSchedule","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSchedule\/period","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSchedule\/periodUnit"],"anchor":"Instance-Properties"},{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSchedule\/init(period:periodUnit:)"],"anchor":"Instance-Methods"}],"path":"\/topicSections","op":"replace"},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentSchedule"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"PaymentSchedule","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSchedule\/title","op":"replace"},{"value":[{"text":"PaymentSchedule","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSchedule\/fragments","op":"replace"},{"value":[{"text":"PaymentSchedule","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSchedule\/navigatorTitle","op":"replace"},{"value":"initWithPeriod:periodUnit:","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSchedule~1init(period:periodUnit:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithPeriod:periodUnit:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSchedule~1init(period:periodUnit:)\/fragments","op":"replace"},{"value":"period","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSchedule~1period\/title","op":"replace"},{"value":[{"text":"period","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSchedule~1period\/fragments","op":"replace"},{"value":"periodUnit","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSchedule~1periodUnit\/title","op":"replace"},{"value":[{"text":"periodUnit","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSchedule~1periodUnit\/fragments","op":"replace"}]}]}