{"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentIntentResponse"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxgetpaymentintentresponse\/requestid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxgetpaymentintentresponse\/requestid"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"requestId","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"abstract":[{"type":"text","text":"Request id."}],"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentIntentResponse\/requestId","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"requestId"}],"externalID":"c:objc(cs)AWXGetPaymentIntentResponse(py)requestId","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"requestId","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"modules":[{"name":"Airwallex"}],"title":"requestId","role":"symbol"},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentIntentResponse/requestId":{"url":"\/documentation\/airwallex\/awxgetpaymentintentresponse\/requestid","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentIntentResponse\/requestId","abstract":[{"type":"text","text":"Request id."}],"navigatorTitle":[{"kind":"identifier","text":"requestId"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"requestId","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"kind":"symbol","type":"topic","title":"requestId","role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentIntentResponse":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AWXGetPaymentIntentResponse","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AWXGetPaymentIntentResponse"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentIntentResponse","title":"AWXGetPaymentIntentResponse","abstract":[{"code":"AWXGetPaymentIntentResponse","type":"codeVoice"},{"text":" includes the information of payment intent.","type":"text"}],"kind":"symbol","url":"\/documentation\/airwallex\/awxgetpaymentintentresponse"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/airwallex","title":"Airwallex","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"requestId","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"requestId"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"requestId","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentIntentResponse~1requestId\/title","value":"requestId"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentIntentResponse~1requestId\/fragments","op":"replace","value":[{"text":"requestId","kind":"identifier"}]},{"op":"replace","value":"AWXGetPaymentIntentResponse","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentIntentResponse\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentIntentResponse\/fragments","value":[{"kind":"identifier","text":"AWXGetPaymentIntentResponse"}]},{"op":"replace","value":[{"text":"AWXGetPaymentIntentResponse","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentIntentResponse\/navigatorTitle"}]}]}