{"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"One of one-off \/ recurring \/ recurring with intent session."}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXViewController"]]},"variants":[{"paths":["\/documentation\/airwallex\/awxviewcontroller\/session"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxviewcontroller\/session"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXViewController\/session","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Property","title":"session","symbolKind":"property","externalID":"c:objc(cs)AWXViewController(py)session","role":"symbol","modules":[{"name":"Airwallex"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"session"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AWXSession","kind":"typeIdentifier","text":"AWXSession"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"session","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"session"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession","text":"AWXSession","preciseIdentifier":"c:objc(cs)AWXSession"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXViewController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXViewController"}],"type":"topic","abstract":[{"code":"AWXViewController","type":"codeVoice"},{"text":" is the base view controller.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWXViewController"}],"title":"AWXViewController","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXViewController","kind":"symbol","url":"\/documentation\/airwallex\/awxviewcontroller"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXViewController/session":{"title":"session","abstract":[{"type":"text","text":"One of one-off \/ recurring \/ recurring with intent session."}],"role":"symbol","url":"\/documentation\/airwallex\/awxviewcontroller\/session","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"session","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AWXSession","text":"AWXSession","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXViewController\/session","navigatorTitle":[{"text":"session","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSession":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXSession"}],"navigatorTitle":[{"kind":"identifier","text":"AWXSession"}],"title":"AWXSession","type":"topic","abstract":[{"code":"AWXSession","type":"codeVoice"},{"text":" is the base session.","type":"text"}],"kind":"symbol","url":"\/documentation\/airwallex\/awxsession"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"abstract":[],"type":"topic","url":"\/documentation\/airwallex","title":"Airwallex","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"session","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"session","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession","preciseIdentifier":"c:objc(cs)AWXSession","text":"AWXSession","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"session","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"AWXViewController","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXViewController\/title"},{"value":[{"kind":"identifier","text":"AWXViewController"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXViewController\/fragments"},{"value":[{"text":"AWXViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXViewController\/navigatorTitle"},{"value":"session","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXViewController~1session\/title"},{"value":[{"kind":"identifier","text":"session"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXViewController~1session\/fragments"},{"value":"AWXSession","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/title"},{"value":[{"kind":"identifier","text":"AWXSession"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/fragments"},{"value":[{"kind":"identifier","text":"AWXSession"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}