{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/Configuration"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/Configuration\/checkoutButton"},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/airwallex\/awxuicontext\/configuration\/checkoutbutton"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"externalID":"s:9Airwallex12AWXUIContextC13ConfigurationC14checkoutButtonAA17AWXPaymentElementCADC08CheckoutE0Cvp","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"checkoutButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWXPaymentElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@Airwallex@objc(cs)AWXPaymentElement"},{"text":".","kind":"text"},{"preciseIdentifier":"s:9Airwallex17AWXPaymentElementC13ConfigurationC","text":"Configuration","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"CheckoutButton","kind":"typeIdentifier","preciseIdentifier":"s:9Airwallex17AWXPaymentElementC13ConfigurationC14CheckoutButtonC"}],"title":"checkoutButton","symbolKind":"property","modules":[{"name":"Airwallex"}],"roleHeading":"Instance Property"},"sections":[],"abstract":[{"text":"Configuration for the checkout button title.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"checkoutButton"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@Airwallex@objc(cs)AWXPaymentElement","text":"AWXPaymentElement"},{"kind":"text","text":"."},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/Configuration","kind":"typeIdentifier","preciseIdentifier":"s:9Airwallex17AWXPaymentElementC13ConfigurationC","text":"Configuration"},{"kind":"text","text":"."},{"preciseIdentifier":"s:9Airwallex17AWXPaymentElementC13ConfigurationC14CheckoutButtonC","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/Configuration\/CheckoutButton-swift.class","text":"CheckoutButton","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement/Configuration/CheckoutButton-swift.class":{"type":"topic","abstract":[{"type":"text","text":"Configuration for the checkout button title."}],"title":"AWXPaymentElement.Configuration.CheckoutButton","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/Configuration\/CheckoutButton-swift.class","navigatorTitle":[{"kind":"identifier","text":"CheckoutButton"}],"url":"\/documentation\/airwallex\/awxpaymentelement\/configuration\/checkoutbutton-swift.class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CheckoutButton"}],"kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement/Configuration":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"url":"\/documentation\/airwallex\/awxpaymentelement\/configuration","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/Configuration","title":"AWXPaymentElement.Configuration","abstract":[{"type":"text","text":"Configuration options for the embedded payment element."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"role":"symbol","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"AWXPaymentElement"}],"url":"\/documentation\/airwallex\/awxpaymentelement","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement","title":"AWXPaymentElement","abstract":[{"text":"An embeddable payment element that can be added to any view hierarchy.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentElement"}],"role":"symbol","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXUIContext":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"AWXUIContext"}],"url":"\/documentation\/airwallex\/awxuicontext","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext","title":"AWXUIContext","abstract":[{"type":"text","text":"The main UI context for Airwallex payment flows."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXUIContext"}],"role":"symbol","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXUIContext/Configuration/checkoutButton":{"kind":"symbol","title":"checkoutButton","url":"\/documentation\/airwallex\/awxuicontext\/configuration\/checkoutbutton","abstract":[{"text":"Configuration for the checkout button title.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/Configuration\/checkoutButton","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkoutButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWXPaymentElement","preciseIdentifier":"c:@M@Airwallex@objc(cs)AWXPaymentElement"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"s:9Airwallex17AWXPaymentElementC13ConfigurationC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"CheckoutButton","preciseIdentifier":"s:9Airwallex17AWXPaymentElementC13ConfigurationC14CheckoutButtonC"}],"role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","role":"collection","title":"Airwallex","type":"topic","url":"\/documentation\/airwallex","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXUIContext/Configuration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/Configuration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"abstract":[{"type":"text","text":"Configuration options for launching the payment UI."}],"url":"\/documentation\/airwallex\/awxuicontext\/configuration","title":"AWXUIContext.Configuration","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"AWXPaymentElement","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/title"},{"op":"replace","value":[{"text":"AWXPaymentElement","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/fragments"},{"op":"replace","value":[{"text":"AWXPaymentElement","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/navigatorTitle"},{"op":"replace","value":"AWXUIContext","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext\/title"},{"op":"replace","value":[{"text":"AWXUIContext","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext\/fragments"},{"op":"replace","value":[{"text":"AWXUIContext","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext\/navigatorTitle"}]}]}