{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONEncodable\/encodeToJSON()"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxjsonencodable\/encodetojson()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxjsonencodable\/encodetojson()"]}],"kind":"symbol","metadata":{"title":"encodeToJSON()","required":true,"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"encodeToJSON"},{"kind":"text","text":"() -> ["},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"modules":[{"name":"Airwallex"}],"role":"symbol","externalID":"c:objc(pl)AWXJSONEncodable(im)encodeToJSON","navigatorTitle":[{"kind":"identifier","text":"encodeToJSON"}],"symbolKind":"method"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"encodeToJSON"},{"kind":"text","text":"() -> ["},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONEncodable"]]},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXJSONEncodable/encodeToJSON()":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONEncodable\/encodeToJSON()","title":"encodeToJSON()","url":"\/documentation\/airwallex\/awxjsonencodable\/encodetojson()","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"encodeToJSON"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"encodeToJSON"}],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXJSONEncodable":{"type":"topic","url":"\/documentation\/airwallex\/awxjsonencodable","navigatorTitle":[{"text":"AWXJSONEncodable","kind":"identifier"}],"title":"AWXJSONEncodable","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXJSONEncodable","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXJSONEncodable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","url":"\/documentation\/airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol","title":"Airwallex","abstract":[],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"encodeToJSON","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"encodeToJSON"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"encodeToJSON"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"encodeToJSON","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONEncodable~1encodeToJSON()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"encodeToJSON","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONEncodable~1encodeToJSON()\/fragments"},{"op":"replace","value":"AWXJSONEncodable","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONEncodable\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AWXJSONEncodable"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONEncodable\/fragments"},{"op":"replace","value":[{"text":"AWXJSONEncodable","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXJSONEncodable\/navigatorTitle"}]}]}