{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxpaymentmethodtype\/transactioncurrencies"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxpaymentmethodtype\/transactioncurrencies"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethodType"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"transactionCurrencies"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethodType\/transactionCurrencies","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:objc(cs)AWXPaymentMethodType(py)transactionCurrencies","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"transactionCurrencies"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"transactionCurrencies"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"title":"transactionCurrencies","symbolKind":"property","modules":[{"name":"Airwallex"}],"roleHeading":"Instance Property"},"abstract":[{"text":"transaction_currencies of the payment method.  “*”, “AUD”, “CHF”, “HKD”, “SGD”, “JPY”, “EUR”, “GBP”, “USD”, “CAD”, “NZD”, “CNY”","type":"text"}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","type":"topic","role":"collection","title":"Airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentMethodType":{"type":"topic","navigatorTitle":[{"text":"AWXPaymentMethodType","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxpaymentmethodtype","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPaymentMethodType","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethodType","title":"AWXPaymentMethodType","role":"symbol","kind":"symbol","abstract":[{"type":"codeVoice","code":"AWXPaymentMethodType"},{"text":" includes the information of a payment method.","type":"text"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentMethodType/transactionCurrencies":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transactionCurrencies","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"title":"transactionCurrencies","navigatorTitle":[{"text":"transactionCurrencies","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethodType\/transactionCurrencies","url":"\/documentation\/airwallex\/awxpaymentmethodtype\/transactioncurrencies","abstract":[{"type":"text","text":"transaction_currencies of the payment method.  “*”, “AUD”, “CHF”, “HKD”, “SGD”, “JPY”, “EUR”, “GBP”, “USD”, “CAD”, “NZD”, “CNY”"}],"type":"topic","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"transactionCurrencies"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"transactionCurrencies"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"transactionCurrencies","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethodType\/title","op":"replace","value":"AWXPaymentMethodType"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethodType\/fragments","op":"replace","value":[{"kind":"identifier","text":"AWXPaymentMethodType"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethodType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AWXPaymentMethodType"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethodType~1transactionCurrencies\/title","op":"replace","value":"transactionCurrencies"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethodType~1transactionCurrencies\/fragments","op":"replace","value":[{"kind":"identifier","text":"transactionCurrencies"}]}]}]}