{"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentIntentProvider\/customerId","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentIntentProvider"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/paymentintentprovider\/customerid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/paymentintentprovider\/customerid"]}],"abstract":[{"text":"The customer ID associated with this payment, if available.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customerId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]},{"content":[{"level":2,"anchor":"discussion","text":"Discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"This value must be available immediately. If not nil, it should match the"},{"type":"text","text":" "},{"type":"text","text":"customer ID of the payment intent that will be created by "},{"code":"createPaymentIntent()","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"},{"name":"Important","content":[{"inlineContent":[{"type":"text","text":"Required for recurring payments and saved payment methods."}],"type":"paragraph"}],"type":"aside","style":"important"}],"kind":"content"}],"metadata":{"role":"symbol","symbolKind":"property","modules":[{"name":"Airwallex"}],"title":"customerId","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customerId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"externalID":"c:@M@Airwallex@objc(pl)PaymentIntentProvider(py)customerId","required":true,"navigatorTitle":[{"text":"customerId","kind":"identifier"}]},"kind":"symbol","references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","title":"Airwallex","abstract":[],"type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentIntentProvider":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentIntentProvider","abstract":[{"text":"A protocol for providing payment intents on-demand during the payment flow.","type":"text"}],"url":"\/documentation\/airwallex\/paymentintentprovider","title":"PaymentIntentProvider","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentIntentProvider"}],"navigatorTitle":[{"kind":"identifier","text":"PaymentIntentProvider"}],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentIntentProvider/customerId":{"url":"\/documentation\/airwallex\/paymentintentprovider\/customerid","abstract":[{"type":"text","text":"The customer ID associated with this payment, if available."}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customerId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"customerId"}],"required":true,"kind":"symbol","title":"customerId","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentIntentProvider\/customerId"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"customerId"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"customerId"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"customerId","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentIntentProvider\/title","op":"replace","value":"PaymentIntentProvider"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentIntentProvider\/fragments","op":"replace","value":[{"text":"PaymentIntentProvider","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentIntentProvider\/navigatorTitle","op":"replace","value":[{"text":"PaymentIntentProvider","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentIntentProvider~1customerId\/title","op":"replace","value":"customerId"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentIntentProvider~1customerId\/fragments","op":"replace","value":[{"text":"customerId","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}