{"sections":[],"metadata":{"navigatorTitle":[{"text":"capturedAmount","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"capturedAmount","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSDecimalNumber","text":"NSDecimalNumber","kind":"typeIdentifier"}],"role":"symbol","title":"capturedAmount","modules":[{"name":"Airwallex"}],"symbolKind":"property","externalID":"c:objc(cs)AWXGetPaymentIntentResponse(py)capturedAmount","roleHeading":"Instance Property"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentIntentResponse"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/airwallex\/awxgetpaymentintentresponse\/capturedamount"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxgetpaymentintentresponse\/capturedamount"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Captured amount.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"capturedAmount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSDecimalNumber","preciseIdentifier":"c:objc(cs)NSDecimalNumber"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentIntentResponse\/capturedAmount","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentIntentResponse/capturedAmount":{"url":"\/documentation\/airwallex\/awxgetpaymentintentresponse\/capturedamount","abstract":[{"type":"text","text":"Captured amount."}],"title":"capturedAmount","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"capturedAmount","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSDecimalNumber","preciseIdentifier":"c:objc(cs)NSDecimalNumber","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"capturedAmount","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentIntentResponse\/capturedAmount"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentIntentResponse":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentIntentResponse","kind":"symbol","type":"topic","url":"\/documentation\/airwallex\/awxgetpaymentintentresponse","abstract":[{"code":"AWXGetPaymentIntentResponse","type":"codeVoice"},{"text":" includes the information of payment intent.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXGetPaymentIntentResponse","kind":"identifier"}],"navigatorTitle":[{"text":"AWXGetPaymentIntentResponse","kind":"identifier"}],"title":"AWXGetPaymentIntentResponse"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","url":"\/documentation\/airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol","title":"Airwallex","abstract":[],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"capturedAmount","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"capturedAmount"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDecimalNumber","text":"NSDecimalNumber"},{"kind":"text","text":" * "},{"kind":"identifier","text":"capturedAmount"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"capturedAmount","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentIntentResponse~1capturedAmount\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentIntentResponse~1capturedAmount\/fragments","value":[{"kind":"identifier","text":"capturedAmount"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentIntentResponse\/title","value":"AWXGetPaymentIntentResponse"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentIntentResponse\/fragments","value":[{"kind":"identifier","text":"AWXGetPaymentIntentResponse"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentIntentResponse\/navigatorTitle","value":[{"kind":"identifier","text":"AWXGetPaymentIntentResponse"}]}]}]}