{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCard\/NumberType-swift.enum"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxcard\/numbertype-swift.enum"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NumberType","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCard\/NumberType-swift.enum\/PAN","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCard\/NumberType-swift.enum\/airwallexNetworkToken","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCard\/NumberType-swift.enum\/externalNetworkToken"],"generated":true,"title":"Type Properties","anchor":"Type-Properties"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCard"]]},"metadata":{"modules":[{"name":"Airwallex"}],"navigatorTitle":[{"kind":"identifier","text":"NumberType"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"NumberType"}],"extendedModule":"Airwallex","role":"symbol","roleHeading":"Enumeration","externalID":"s:So7AWXCardC9AirwallexE10NumberTypeO","title":"AWXCard.NumberType","symbolKind":"enum"},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCard/NumberType-swift.enum/PAN":{"role":"symbol","url":"\/documentation\/airwallex\/awxcard\/numbertype-swift.enum\/pan","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"PAN"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"PAN","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCard\/NumberType-swift.enum\/PAN","abstract":[{"type":"text","text":"for consent payment, NumberType.PAN requires CVC"}],"type":"topic","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCard/NumberType-swift.enum":{"title":"AWXCard.NumberType","url":"\/documentation\/airwallex\/awxcard\/numbertype-swift.enum","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"NumberType"}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCard\/NumberType-swift.enum","navigatorTitle":[{"kind":"identifier","text":"NumberType"}],"abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCard":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCard","navigatorTitle":[{"kind":"identifier","text":"AWXCard"}],"abstract":[{"type":"codeVoice","code":"AWXCard"},{"text":" includes the information of a card.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXCard"}],"role":"symbol","type":"topic","url":"\/documentation\/airwallex\/awxcard","title":"AWXCard","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCard/NumberType-swift.enum/externalNetworkToken":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"externalNetworkToken"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCard\/NumberType-swift.enum\/externalNetworkToken","kind":"symbol","role":"symbol","url":"\/documentation\/airwallex\/awxcard\/numbertype-swift.enum\/externalnetworktoken","abstract":[{"text":"for consent payment, we can checkout with this consent without CVC verification","type":"text"}],"type":"topic","title":"externalNetworkToken"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCard/NumberType-swift.enum/airwallexNetworkToken":{"kind":"symbol","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"airwallexNetworkToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"text":"for consent payment, we can checkout with this consent without CVC verification","type":"text"}],"title":"airwallexNetworkToken","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCard\/NumberType-swift.enum\/airwallexNetworkToken","url":"\/documentation\/airwallex\/awxcard\/numbertype-swift.enum\/airwallexnetworktoken"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"kind":"symbol","abstract":[],"role":"collection","type":"topic","url":"\/documentation\/airwallex","title":"Airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"AWXCard","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCard\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AWXCard"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCard\/fragments"},{"op":"replace","value":[{"text":"AWXCard","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCard\/navigatorTitle"}]}]}