{"metadata":{"modules":[{"name":"Airwallex"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"status","externalID":"c:objc(cs)AWXVerifyPaymentConsentResponse(py)status","navigatorTitle":[{"text":"status","kind":"identifier"}],"symbolKind":"property","roleHeading":"Instance Property","role":"symbol"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXVerifyPaymentConsentResponse"]]},"abstract":[{"type":"text","text":"Payment status."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXVerifyPaymentConsentResponse\/status"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxverifypaymentconsentresponse\/status"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxverifypaymentconsentresponse\/status"]}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","abstract":[],"type":"topic","kind":"symbol","title":"Airwallex","role":"collection"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXVerifyPaymentConsentResponse/status":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"status","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","url":"\/documentation\/airwallex\/awxverifypaymentconsentresponse\/status","navigatorTitle":[{"text":"status","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Payment status."}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXVerifyPaymentConsentResponse\/status","kind":"symbol","title":"status"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXVerifyPaymentConsentResponse":{"abstract":[{"code":"AWXVerifyPaymentConsentResponse","type":"codeVoice"},{"text":" includes the response of payment consent.","type":"text"}],"title":"AWXVerifyPaymentConsentResponse","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXVerifyPaymentConsentResponse","navigatorTitle":[{"kind":"identifier","text":"AWXVerifyPaymentConsentResponse"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXVerifyPaymentConsentResponse"}],"kind":"symbol","url":"\/documentation\/airwallex\/awxverifypaymentconsentresponse","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"status","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"status"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"status"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXVerifyPaymentConsentResponse~1status\/title","value":"status","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXVerifyPaymentConsentResponse~1status\/fragments","value":[{"kind":"identifier","text":"status"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXVerifyPaymentConsentResponse\/title","value":"AWXVerifyPaymentConsentResponse"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXVerifyPaymentConsentResponse\/fragments","value":[{"kind":"identifier","text":"AWXVerifyPaymentConsentResponse"}],"op":"replace"},{"value":[{"kind":"identifier","text":"AWXVerifyPaymentConsentResponse"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXVerifyPaymentConsentResponse\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}