{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"session","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AWXSession","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession","preciseIdentifier":"c:objc(cs)AWXSession"},{"text":", ","kind":"text"},{"text":"viewController","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":" & ","kind":"text"},{"text":"AWXPaymentResultDelegate","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentResultDelegate","preciseIdentifier":"c:objc(pl)AWXPaymentResultDelegate"},{"text":", ","kind":"text"},{"text":"methodType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AWXPaymentMethodType","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethodType","preciseIdentifier":"c:objc(cs)AWXPaymentMethodType"},{"text":"? = nil)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"session","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The payment session containing relevant transaction details."}]}]},{"name":"viewController","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The view controller initiating the payment, which conforms to "},{"type":"codeVoice","code":"AWXPaymentResultDelegate"},{"type":"text","text":" for handling payment results."}]}]},{"name":"methodType","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The payment method type returned from the server (optional)."}]}]}],"kind":"parameters"}],"sections":[],"metadata":{"symbolKind":"init","navigatorTitle":[{"kind":"identifier","text":"initWithSession:viewController:methodType:"}],"title":"init(session:viewController:methodType:)","modules":[{"name":"Airwallex"}],"externalID":"c:@M@Airwallex@objc(cs)PaymentSessionHandler(im)initWithSession:viewController:methodType:","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"session","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AWXSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXSession"},{"text":", ","kind":"text"},{"text":"viewController","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":" & ","kind":"text"},{"text":"AWXPaymentResultDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)AWXPaymentResultDelegate"},{"text":", ","kind":"text"},{"text":"methodType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AWXPaymentMethodType","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPaymentMethodType"},{"text":"?)","kind":"text"}],"roleHeading":"Initializer"},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler\/init(session:viewController:methodType:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/paymentsessionhandler\/init(session:viewcontroller:methodtype:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/paymentsessionhandler\/init(session:viewcontroller:methodtype:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler"]]},"abstract":[{"text":"Initializes a ","type":"text"},{"code":"PaymentSessionHandler","type":"codeVoice"},{"text":" with a payment session and a view controller that also acts as a payment result delegate.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSession":{"url":"\/documentation\/airwallex\/awxsession","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession","abstract":[{"type":"codeVoice","code":"AWXSession"},{"text":" is the base session.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXSession","kind":"identifier"}],"navigatorTitle":[{"text":"AWXSession","kind":"identifier"}],"title":"AWXSession","type":"topic","role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentResultDelegate":{"type":"topic","role":"symbol","abstract":[],"title":"AWXPaymentResultDelegate","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWXPaymentResultDelegate"}],"url":"\/documentation\/airwallex\/awxpaymentresultdelegate","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentResultDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentResultDelegate"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentMethodType":{"role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPaymentMethodType","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethodType","navigatorTitle":[{"text":"AWXPaymentMethodType","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxpaymentmethodtype","title":"AWXPaymentMethodType","abstract":[{"type":"codeVoice","code":"AWXPaymentMethodType"},{"text":" includes the information of a payment method.","type":"text"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentSessionHandler/init(session:viewController:methodType:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithSession:viewController:methodType:"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler\/init(session:viewController:methodType:)","url":"\/documentation\/airwallex\/paymentsessionhandler\/init(session:viewcontroller:methodtype:)","title":"init(session:viewController:methodType:)","abstract":[{"text":"Initializes a ","type":"text"},{"code":"PaymentSessionHandler","type":"codeVoice"},{"text":" with a payment session and a view controller that also acts as a payment result delegate.","type":"text"}],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"session"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWXSession","preciseIdentifier":"c:objc(cs)AWXSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"viewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"AWXPaymentResultDelegate","preciseIdentifier":"c:objc(pl)AWXPaymentResultDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"methodType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWXPaymentMethodType","preciseIdentifier":"c:objc(cs)AWXPaymentMethodType"},{"kind":"text","text":"?)"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","type":"topic","url":"\/documentation\/airwallex","kind":"symbol","abstract":[],"title":"Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentSessionHandler":{"abstract":[{"type":"text","text":"A low-level API handler for managing Airwallex payment sessions."}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PaymentSessionHandler"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentSessionHandler"}],"title":"PaymentSessionHandler","url":"\/documentation\/airwallex\/paymentsessionhandler"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"initWithSession:viewController:methodType:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithSession:viewController:methodType:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithSession:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AWXSession","preciseIdentifier":"c:objc(cs)AWXSession","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"session"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewController:"},{"kind":"text","text":"("},{"text":"UIViewController<AWXPaymentResultDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)UIViewControllerobjc(pl)AWXPaymentResultDelegate"},{"text":" *) ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"methodType:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AWXPaymentMethodType","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethodType","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPaymentMethodType"},{"text":" *) ","kind":"text"},{"text":"methodType","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"parameters":[{"name":"session","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The payment session containing relevant transaction details."}]}]},{"name":"viewController","content":[{"inlineContent":[{"text":"The view controller initiating the payment, which conforms to ","type":"text"},{"code":"AWXPaymentResultDelegate","type":"codeVoice"},{"text":" for handling payment results.","type":"text"}],"type":"paragraph"}]},{"name":"methodType","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The payment method type returned from the server (optional)."}]}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"AWXSession","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/title","op":"replace"},{"value":[{"text":"AWXSession","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/fragments","op":"replace"},{"value":[{"text":"AWXSession","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/navigatorTitle","op":"replace"},{"value":"AWXPaymentResultDelegate","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentResultDelegate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AWXPaymentResultDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentResultDelegate\/fragments","op":"replace"},{"value":[{"text":"AWXPaymentResultDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentResultDelegate\/navigatorTitle","op":"replace"},{"value":"AWXPaymentMethodType","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethodType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AWXPaymentMethodType"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethodType\/fragments","op":"replace"},{"value":[{"text":"AWXPaymentMethodType","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethodType\/navigatorTitle","op":"replace"},{"value":"initWithSession:viewController:methodType:","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler~1init(session:viewController:methodType:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"initWithSession:viewController:methodType:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler~1init(session:viewController:methodType:)\/fragments","op":"replace"},{"value":"PaymentSessionHandler","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler\/title","op":"replace"},{"value":[{"text":"PaymentSessionHandler","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"PaymentSessionHandler"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}