{"abstract":[{"type":"text","text":"Options object."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/airwallex\/awxconfirmpaymentintentrequest\/options"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxconfirmpaymentintentrequest\/options"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentRequest\/options","interfaceLanguage":"swift"},"metadata":{"title":"options","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"Airwallex"}],"navigatorTitle":[{"kind":"identifier","text":"options"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPaymentMethodOptions","text":"AWXPaymentMethodOptions"},{"kind":"text","text":"?"}],"externalID":"c:objc(cs)AWXConfirmPaymentIntentRequest(py)options"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPaymentMethodOptions","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethodOptions","text":"AWXPaymentMethodOptions"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentRequest"]]},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXConfirmPaymentIntentRequest/options":{"abstract":[{"type":"text","text":"Options object."}],"url":"\/documentation\/airwallex\/awxconfirmpaymentintentrequest\/options","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentRequest\/options","navigatorTitle":[{"text":"options","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"options","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AWXPaymentMethodOptions","text":"AWXPaymentMethodOptions","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","title":"options"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentMethodOptions":{"abstract":[{"code":"AWXPaymentMethodOptions","type":"codeVoice"},{"type":"text","text":" includes the information of payment method options"}],"url":"\/documentation\/airwallex\/awxpaymentmethodoptions","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethodOptions","navigatorTitle":[{"text":"AWXPaymentMethodOptions","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPaymentMethodOptions","kind":"identifier"}],"kind":"symbol","title":"AWXPaymentMethodOptions"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","url":"\/documentation\/airwallex","abstract":[],"title":"Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXConfirmPaymentIntentRequest":{"abstract":[{"code":"AWXConfirmPaymentIntentRequest","type":"codeVoice"},{"type":"text","text":" includes all of the parameters needed to confirm payment intent."}],"url":"\/documentation\/airwallex\/awxconfirmpaymentintentrequest","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentRequest","navigatorTitle":[{"text":"AWXConfirmPaymentIntentRequest","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXConfirmPaymentIntentRequest","kind":"identifier"}],"kind":"symbol","title":"AWXConfirmPaymentIntentRequest"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"options","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"options","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethodOptions","preciseIdentifier":"c:objc(cs)AWXPaymentMethodOptions","kind":"typeIdentifier","text":"AWXPaymentMethodOptions"},{"kind":"text","text":" * "},{"kind":"identifier","text":"options"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentRequest~1options\/title","value":"options","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentRequest~1options\/fragments","value":[{"kind":"identifier","text":"options"}],"op":"replace"},{"op":"replace","value":"AWXPaymentMethodOptions","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethodOptions\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethodOptions\/fragments","value":[{"kind":"identifier","text":"AWXPaymentMethodOptions"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethodOptions\/navigatorTitle","value":[{"text":"AWXPaymentMethodOptions","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentRequest\/title","value":"AWXConfirmPaymentIntentRequest","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentRequest\/fragments","value":[{"kind":"identifier","text":"AWXConfirmPaymentIntentRequest"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentRequest\/navigatorTitle","value":[{"kind":"identifier","text":"AWXConfirmPaymentIntentRequest"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}