{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentRequest\/paymentConsent"},"metadata":{"modules":[{"name":"Airwallex"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentConsent","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWXPaymentConsent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPaymentConsent"},{"text":"?","kind":"text"}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","externalID":"c:objc(cs)AWXConfirmPaymentIntentRequest(py)paymentConsent","navigatorTitle":[{"kind":"identifier","text":"paymentConsent"}],"title":"paymentConsent"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentConsent","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AWXPaymentConsent","text":"AWXPaymentConsent","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentConsent"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxconfirmpaymentintentrequest\/paymentconsent"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxconfirmpaymentintentrequest\/paymentconsent"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentRequest"]]},"abstract":[{"type":"text","text":"PaymentConsent method object."}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXConfirmPaymentIntentRequest":{"url":"\/documentation\/airwallex\/awxconfirmpaymentintentrequest","abstract":[{"code":"AWXConfirmPaymentIntentRequest","type":"codeVoice"},{"text":" includes all of the parameters needed to confirm payment intent.","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXConfirmPaymentIntentRequest","kind":"identifier"}],"navigatorTitle":[{"text":"AWXConfirmPaymentIntentRequest","kind":"identifier"}],"kind":"symbol","title":"AWXConfirmPaymentIntentRequest","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentRequest"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","title":"Airwallex","abstract":[],"type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentConsent":{"abstract":[{"code":"AWXPaymentConsent","type":"codeVoice"},{"type":"text","text":" includes the info of payment consent."}],"title":"AWXPaymentConsent","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPaymentConsent","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"AWXPaymentConsent","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxpaymentconsent","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentConsent","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXConfirmPaymentIntentRequest/paymentConsent":{"role":"symbol","title":"paymentConsent","abstract":[{"text":"PaymentConsent method object.","type":"text"}],"url":"\/documentation\/airwallex\/awxconfirmpaymentintentrequest\/paymentconsent","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentConsent","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWXPaymentConsent","preciseIdentifier":"c:objc(cs)AWXPaymentConsent","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentRequest\/paymentConsent","type":"topic","navigatorTitle":[{"text":"paymentConsent","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"paymentConsent","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"paymentConsent","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)AWXPaymentConsent","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentConsent","kind":"typeIdentifier","text":"AWXPaymentConsent"},{"kind":"text","text":" * "},{"kind":"identifier","text":"paymentConsent"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentRequest\/title","value":"AWXConfirmPaymentIntentRequest"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentRequest\/fragments","value":[{"kind":"identifier","text":"AWXConfirmPaymentIntentRequest"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentRequest\/navigatorTitle","value":[{"text":"AWXConfirmPaymentIntentRequest","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentConsent\/title","value":"AWXPaymentConsent"},{"value":[{"text":"AWXPaymentConsent","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentConsent\/fragments","op":"replace"},{"value":[{"text":"AWXPaymentConsent","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentConsent\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentRequest~1paymentConsent\/title","value":"paymentConsent","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentRequest~1paymentConsent\/fragments","value":[{"text":"paymentConsent","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}