{"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"providerDidStartRequest"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AWXDefaultProvider","preciseIdentifier":"c:objc(cs)AWXDefaultProvider"},{"kind":"text","text":")"}],"externalID":"c:@CM@Airwallex@objc(cs)PaymentSessionHandler(im)providerDidStartRequest:","navigatorTitle":[{"kind":"identifier","text":"providerDidStartRequest:"}],"extendedModule":"Airwallex","modules":[{"name":"Airwallex"}],"role":"symbol","roleHeading":"Instance Method","title":"providerDidStartRequest(_:)","symbolKind":"method"},"variants":[{"paths":["\/documentation\/airwallex\/paymentsessionhandler\/providerdidstartrequest(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/paymentsessionhandler\/providerdidstartrequest(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"providerDidStartRequest"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"provider"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AWXDefaultProvider","text":"AWXDefaultProvider","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler"]]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"AWXProviderDelegate.providerDidStartRequest(_:)"},{"type":"text","text":"."}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler\/providerDidStartRequest(_:)","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentSessionHandler/providerDidStartRequest(_:)":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"providerDidStartRequest:"}],"title":"providerDidStartRequest(_:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler\/providerDidStartRequest(_:)","url":"\/documentation\/airwallex\/paymentsessionhandler\/providerdidstartrequest(_:)","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"providerDidStartRequest","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AWXDefaultProvider","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXDefaultProvider"},{"kind":"text","text":")"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXDefaultProvider":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider","kind":"symbol","title":"AWXDefaultProvider","abstract":[{"type":"text","text":"A provider which handles payment business."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXDefaultProvider","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxdefaultprovider","navigatorTitle":[{"text":"AWXDefaultProvider","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentSessionHandler":{"role":"symbol","url":"\/documentation\/airwallex\/paymentsessionhandler","abstract":[{"text":"A low-level API handler for managing Airwallex payment sessions.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentSessionHandler"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler","navigatorTitle":[{"kind":"identifier","text":"PaymentSessionHandler"}],"title":"PaymentSessionHandler","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","url":"\/documentation\/airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","kind":"symbol","role":"collection","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"providerDidStartRequest:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"providerDidStartRequest:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"providerDidStartRequest:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AWXDefaultProvider","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXDefaultProvider","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider"},{"text":" *) ","kind":"text"},{"text":"provider","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler~1providerDidStartRequest(_:)\/title","value":"providerDidStartRequest:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler~1providerDidStartRequest(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"providerDidStartRequest:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider\/title","value":"AWXDefaultProvider"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider\/fragments","value":[{"text":"AWXDefaultProvider","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider\/navigatorTitle","value":[{"text":"AWXDefaultProvider","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler\/title","value":"PaymentSessionHandler"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler\/fragments","value":[{"text":"PaymentSessionHandler","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler\/navigatorTitle","value":[{"text":"PaymentSessionHandler","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}