{"sections":[],"variants":[{"paths":["\/documentation\/airwallex\/awxschema\/fields"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxschema\/fields"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fields","kind":"identifier"},{"text":": [","kind":"text"},{"text":"AWXField","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXField","preciseIdentifier":"c:objc(cs)AWXField"},{"text":"] { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSchema"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fields"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)AWXField","kind":"typeIdentifier","text":"AWXField"},{"kind":"text","text":"]"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"fields"}],"modules":[{"name":"Airwallex"}],"role":"symbol","title":"fields","externalID":"c:objc(cs)AWXSchema(py)fields","roleHeading":"Instance Property"},"abstract":[{"type":"text","text":"Fields."}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSchema\/fields","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSchema":{"abstract":[{"type":"codeVoice","code":"AWXSchema"},{"type":"text","text":" includes the schema of payment method."}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSchema","navigatorTitle":[{"kind":"identifier","text":"AWXSchema"}],"title":"AWXSchema","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXSchema"}],"url":"\/documentation\/airwallex\/awxschema"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSchema/fields":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fields"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)AWXField","kind":"typeIdentifier","text":"AWXField"},{"kind":"text","text":"]"}],"title":"fields","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSchema\/fields","navigatorTitle":[{"kind":"identifier","text":"fields"}],"url":"\/documentation\/airwallex\/awxschema\/fields","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Fields."}],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","role":"collection","url":"\/documentation\/airwallex","kind":"symbol","title":"Airwallex","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXField":{"role":"symbol","abstract":[{"code":"AWXField","type":"codeVoice"},{"text":" includes the field of schema.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXField","url":"\/documentation\/airwallex\/awxfield","kind":"symbol","type":"topic","navigatorTitle":[{"text":"AWXField","kind":"identifier"}],"title":"AWXField","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXField","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"fields"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"fields","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<AWXField *>","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"fields","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSchema\/title","value":"AWXSchema"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSchema\/fragments","value":[{"text":"AWXSchema","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSchema\/navigatorTitle","value":[{"text":"AWXSchema","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSchema~1fields\/title","value":"fields"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSchema~1fields\/fragments","value":[{"text":"fields","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXField\/title","value":"AWXField"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXField\/fragments","value":[{"text":"AWXField","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXField\/navigatorTitle","value":[{"kind":"identifier","text":"AWXField"}]}]}]}