{"metadata":{"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"customerId"}],"externalID":"c:objc(cs)AWXGetPaymentMethodsRequest(py)customerId","modules":[{"name":"Airwallex"}],"title":"customerId","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customerId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","roleHeading":"Instance Property"},"variants":[{"paths":["\/documentation\/airwallex\/awxgetpaymentmethodsrequest\/customerid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxgetpaymentmethodsrequest\/customerid"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodsRequest"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodsRequest\/customerId"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"Customer ID.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customerId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}]}],"kind":"symbol","references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","role":"collection","title":"Airwallex","type":"topic","url":"\/documentation\/airwallex","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentMethodsRequest/customerId":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"customerId"}],"url":"\/documentation\/airwallex\/awxgetpaymentmethodsrequest\/customerid","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodsRequest\/customerId","title":"customerId","abstract":[{"type":"text","text":"Customer ID."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customerId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"role":"symbol","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentMethodsRequest":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"AWXGetPaymentMethodsRequest"}],"url":"\/documentation\/airwallex\/awxgetpaymentmethodsrequest","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodsRequest","title":"AWXGetPaymentMethodsRequest","abstract":[{"code":"AWXGetPaymentMethodsRequest","type":"codeVoice"},{"text":" includes all of the parameters needed to get payment methods.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXGetPaymentMethodsRequest"}],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"customerId","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"customerId","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"customerId"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"customerId","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodsRequest~1customerId\/title"},{"value":[{"text":"customerId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodsRequest~1customerId\/fragments"},{"value":"AWXGetPaymentMethodsRequest","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodsRequest\/title"},{"value":[{"text":"AWXGetPaymentMethodsRequest","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodsRequest\/fragments"},{"value":[{"text":"AWXGetPaymentMethodsRequest","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodsRequest\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}