{"variants":[{"paths":["\/documentation\/airwallex\/awxpaymentelement\/configuration"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","metadata":{"title":"AWXPaymentElement.Configuration","externalID":"s:9Airwallex17AWXPaymentElementC13ConfigurationC","modules":[{"name":"Airwallex"}],"role":"symbol","roleHeading":"Class","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"extendedModule":"Airwallex"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement"]]},"abstract":[{"text":"Configuration options for the embedded payment element.","type":"text"}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/Configuration","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(AWXPaymentElementConfiguration) "},{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"anchor":"overview","type":"heading","text":"Overview","level":2},{"type":"paragraph","inlineContent":[{"text":"Use this class to customize the appearance and behavior of the payment element.","type":"text"}]}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"title":"Classes","generated":true,"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/Configuration\/Appearance-swift.class","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/Configuration\/ApplePayButton-swift.class","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/Configuration\/CheckoutButton-swift.class"],"anchor":"Classes"},{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/Configuration\/appearance-swift.property","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/Configuration\/applePayButton-swift.property","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/Configuration\/checkoutButton-swift.property","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/Configuration\/elementType","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/Configuration\/layout","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/Configuration\/supportedCardBrands"],"anchor":"Instance-Properties"}],"sections":[],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"]},{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/SQ","doc:\/\/org.cocoapods.Airwallex\/SH"]}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement/Configuration/appearance-swift.property":{"type":"topic","title":"appearance","abstract":[{"text":"Appearance configuration for customizing the visual style.","type":"text"}],"kind":"symbol","url":"\/documentation\/airwallex\/awxpaymentelement\/configuration\/appearance-swift.property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"appearance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:9Airwallex17AWXPaymentElementC13ConfigurationC10AppearanceC","text":"Appearance"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/Configuration\/appearance-swift.property","role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement/Configuration/supportedCardBrands":{"type":"topic","title":"supportedCardBrands","abstract":[{"type":"text","text":"Supported card brands for card payment."}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/Configuration\/supportedCardBrands","url":"\/documentation\/airwallex\/awxpaymentelement\/configuration\/supportedcardbrands","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"supportedCardBrands","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:AWXConstants.h@T@AWXCardBrand","text":"AWXCardBrand","kind":"typeIdentifier"},{"text":"]","kind":"text"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement/Configuration/layout":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/Configuration\/layout","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"layout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@Airwallex@objc(cs)AWXUIContext","text":"AWXUIContext"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:9Airwallex12AWXUIContextC13PaymentLayoutO","text":"PaymentLayout"}],"kind":"symbol","role":"symbol","abstract":[{"text":"The layout style for payment sections.","type":"text"}],"title":"layout","url":"\/documentation\/airwallex\/awxpaymentelement\/configuration\/layout"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement/Configuration/CheckoutButton-swift.class":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CheckoutButton"}],"role":"symbol","url":"\/documentation\/airwallex\/awxpaymentelement\/configuration\/checkoutbutton-swift.class","navigatorTitle":[{"kind":"identifier","text":"CheckoutButton"}],"type":"topic","abstract":[{"type":"text","text":"Configuration for the checkout button title."}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/Configuration\/CheckoutButton-swift.class","title":"AWXPaymentElement.Configuration.CheckoutButton","kind":"symbol"},"doc://org.cocoapods.Airwallex/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement":{"abstract":[{"text":"An embeddable payment element that can be added to any view hierarchy.","type":"text"}],"title":"AWXPaymentElement","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement","navigatorTitle":[{"kind":"identifier","text":"AWXPaymentElement"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentElement"}],"kind":"symbol","url":"\/documentation\/airwallex\/awxpaymentelement","type":"topic"},"doc://org.cocoapods.Airwallex/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.Airwallex/SH":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","abstract":[],"type":"topic","kind":"symbol","title":"Airwallex","role":"collection"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement/Configuration/applePayButton-swift.property":{"url":"\/documentation\/airwallex\/awxpaymentelement\/configuration\/applepaybutton-swift.property","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/Configuration\/applePayButton-swift.property","abstract":[{"type":"text","text":"Configuration for the Apple Pay button appearance and behavior."}],"type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applePayButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWXPaymentElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@Airwallex@objc(cs)AWXPaymentElement"},{"text":".","kind":"text"},{"text":"Configuration","kind":"typeIdentifier","preciseIdentifier":"s:9Airwallex17AWXPaymentElementC13ConfigurationC"},{"text":".","kind":"text"},{"text":"ApplePayButton","kind":"typeIdentifier","preciseIdentifier":"s:9Airwallex17AWXPaymentElementC13ConfigurationC14ApplePayButtonC"}],"title":"applePayButton","role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement/Configuration/ApplePayButton-swift.class":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApplePayButton"}],"role":"symbol","url":"\/documentation\/airwallex\/awxpaymentelement\/configuration\/applepaybutton-swift.class","navigatorTitle":[{"kind":"identifier","text":"ApplePayButton"}],"type":"topic","title":"AWXPaymentElement.Configuration.ApplePayButton","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/Configuration\/ApplePayButton-swift.class","kind":"symbol","abstract":[{"text":"Configuration for the Apple Pay button appearance and behavior.","type":"text"}]},"doc://org.cocoapods.Airwallex/objc(cs)NSObject":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject","type":"unresolvable","title":"ObjectiveC.NSObject"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement/Configuration/elementType":{"title":"elementType","type":"topic","abstract":[{"text":"The type of element to display.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/Configuration\/elementType","url":"\/documentation\/airwallex\/awxpaymentelement\/configuration\/elementtype","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"elementType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ElementType","kind":"typeIdentifier","preciseIdentifier":"s:9Airwallex17AWXPaymentElementC0C4TypeO"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement/Configuration/Appearance-swift.class":{"type":"topic","title":"AWXPaymentElement.Configuration.Appearance","abstract":[{"type":"text","text":"Appearance configuration for customizing the visual style."}],"url":"\/documentation\/airwallex\/awxpaymentelement\/configuration\/appearance-swift.class","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/Configuration\/Appearance-swift.class","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Appearance"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Appearance"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement/Configuration":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"title":"AWXPaymentElement.Configuration","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/Configuration","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"abstract":[{"text":"Configuration options for the embedded payment element.","type":"text"}],"url":"\/documentation\/airwallex\/awxpaymentelement\/configuration"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement/Configuration/checkoutButton-swift.property":{"type":"topic","title":"checkoutButton","kind":"symbol","abstract":[{"type":"text","text":"Configuration for the checkout button title."}],"url":"\/documentation\/airwallex\/awxpaymentelement\/configuration\/checkoutbutton-swift.property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkoutButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@Airwallex@objc(cs)AWXPaymentElement","text":"AWXPaymentElement"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:9Airwallex17AWXPaymentElementC13ConfigurationC","text":"Configuration"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:9Airwallex17AWXPaymentElementC13ConfigurationC14CheckoutButtonC","text":"CheckoutButton"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/Configuration\/checkoutButton-swift.property","role":"symbol"},"doc://org.cocoapods.Airwallex/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.Airwallex/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.Airwallex/SQ":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/SQ","type":"unresolvable","title":"Swift.Equatable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"AWXPaymentElement","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/title"},{"value":[{"kind":"identifier","text":"AWXPaymentElement"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/fragments"},{"value":[{"kind":"identifier","text":"AWXPaymentElement"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/navigatorTitle"}]}]}