{"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"brand","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forCardName","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"name","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"text":"AWXBrand","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrand","preciseIdentifier":"c:objc(cs)AWXBrand"},{"text":"?","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardValidator"]]},"metadata":{"externalID":"c:objc(cs)AWXCardValidator(im)brandForCardName:","title":"brand(forCardName:)","navigatorTitle":[{"kind":"text","text":"- "},{"kind":"identifier","text":"brandForCardName:"}],"role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"brand","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forCardName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"text":"AWXBrand","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXBrand"},{"text":"?","kind":"text"}],"roleHeading":"Instance Method","modules":[{"name":"Airwallex"}]},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardValidator\/brand(forCardName:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/airwallex\/awxcardvalidator\/brand(forcardname:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxcardvalidator\/brand(forcardname:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","url":"\/documentation\/airwallex","title":"Airwallex","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardValidator/brand(forCardName:)":{"abstract":[],"kind":"symbol","title":"brand(forCardName:)","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardValidator\/brand(forCardName:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"brand","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forCardName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"text":"AWXBrand","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXBrand"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"- ","kind":"text"},{"text":"brandForCardName:","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxcardvalidator\/brand(forcardname:)"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXBrand":{"url":"\/documentation\/airwallex\/awxbrand","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AWXBrand","kind":"identifier"}],"title":"AWXBrand","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWXBrand"}],"abstract":[{"type":"codeVoice","code":"AWXBrand"},{"type":"text","text":" manages the card scheme brand."}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrand"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardValidator":{"title":"AWXCardValidator","type":"topic","role":"symbol","navigatorTitle":[{"text":"AWXCardValidator","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardValidator","url":"\/documentation\/airwallex\/awxcardvalidator","kind":"symbol","abstract":[{"code":"AWXCardValidator","type":"codeVoice"},{"type":"text","text":" manages the card info."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXCardValidator","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"brandForCardName:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"brandForCardName:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"AWXBrand","preciseIdentifier":"c:objc(cs)AWXBrand","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrand"},{"text":" *) ","kind":"text"},{"text":"brandForCardName:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"name","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardValidator~1brand(forCardName:)\/title","op":"replace","value":"brandForCardName:"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardValidator~1brand(forCardName:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"brandForCardName:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrand\/title","op":"replace","value":"AWXBrand"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrand\/fragments","op":"replace","value":[{"kind":"identifier","text":"AWXBrand"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrand\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AWXBrand"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardValidator\/title","op":"replace","value":"AWXCardValidator"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardValidator\/fragments","op":"replace","value":[{"kind":"identifier","text":"AWXCardValidator"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardValidator\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AWXCardValidator"}]}]}]}