{"abstract":[{"type":"text","text":"Whether show stored card."}],"metadata":{"navigatorTitle":[{"text":"hidePaymentConsents","kind":"identifier"}],"externalID":"c:objc(cs)AWXOneOffSession(py)hidePaymentConsents","symbolKind":"property","role":"symbol","roleHeading":"Instance Property","modules":[{"name":"Airwallex"}],"title":"hidePaymentConsents","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hidePaymentConsents","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXOneOffSession\/hidePaymentConsents","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/airwallex\/awxoneoffsession\/hidepaymentconsents"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxoneoffsession\/hidepaymentconsents"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXOneOffSession"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hidePaymentConsents","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","role":"collection","title":"Airwallex","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXOneOffSession/hidePaymentConsents":{"abstract":[{"type":"text","text":"Whether show stored card."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hidePaymentConsents"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"hidePaymentConsents"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXOneOffSession\/hidePaymentConsents","kind":"symbol","role":"symbol","type":"topic","title":"hidePaymentConsents","url":"\/documentation\/airwallex\/awxoneoffsession\/hidepaymentconsents"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXOneOffSession":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXOneOffSession","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXOneOffSession","kind":"symbol","url":"\/documentation\/airwallex\/awxoneoffsession","title":"AWXOneOffSession","role":"symbol","abstract":[{"code":"AWXOneOffSession","type":"codeVoice"},{"type":"text","text":" is the session used for one-off payment."}],"type":"topic","navigatorTitle":[{"text":"AWXOneOffSession","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"hidePaymentConsents"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"hidePaymentConsents","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"hidePaymentConsents","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXOneOffSession~1hidePaymentConsents\/title","value":"hidePaymentConsents"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXOneOffSession~1hidePaymentConsents\/fragments","value":[{"kind":"identifier","text":"hidePaymentConsents"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXOneOffSession\/title","value":"AWXOneOffSession"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXOneOffSession\/fragments","value":[{"kind":"identifier","text":"AWXOneOffSession"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXOneOffSession\/navigatorTitle","value":[{"kind":"identifier","text":"AWXOneOffSession"}]}]}]}