{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"launchPayment","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"hostingVC"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)AWXPaymentResultDelegate","text":"AWXPaymentResultDelegate","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentResultDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"session"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession","text":"AWXSession","preciseIdentifier":"c:objc(cs)AWXSession","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/Configuration","text":"Configuration","preciseIdentifier":"s:9Airwallex12AWXUIContextC13ConfigurationC","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The view controller that launches the payment UI and also acts as the "},{"type":"codeVoice","code":"AWXPaymentResultDelegate"},{"type":"text","text":"."}],"type":"paragraph"}],"name":"hostingVC"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The current payment session."}]}],"name":"session"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Configuration for the payment flow."}]}],"name":"configuration"}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/launchPayment(from:session:configuration:)"},"kind":"symbol","abstract":[{"type":"text","text":"Launches the Airwallex payment UI using a configuration object."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxuicontext\/launchpayment(from:session:configuration:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxuicontext\/launchpayment(from:session:configuration:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"modules":[{"name":"Airwallex"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"launchPayment"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"kind":"text","text":" & "},{"preciseIdentifier":"c:objc(pl)AWXPaymentResultDelegate","text":"AWXPaymentResultDelegate","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"session","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXSession","text":"AWXSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"preciseIdentifier":"s:9Airwallex12AWXUIContextC13ConfigurationC","text":"Configuration","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"c:@CM@Airwallex@objc(cs)AWXUIContext(cm)launchPaymentFrom:session:configuration:","title":"launchPayment(from:session:configuration:)","extendedModule":"Airwallex","navigatorTitle":[{"kind":"identifier","text":"launchPaymentFrom:session:configuration:"}],"roleHeading":"Type Method","symbolKind":"method","role":"symbol"},"sections":[],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSession":{"abstract":[{"type":"codeVoice","code":"AWXSession"},{"type":"text","text":" is the base session."}],"title":"AWXSession","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession","navigatorTitle":[{"kind":"identifier","text":"AWXSession"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXSession"}],"kind":"symbol","url":"\/documentation\/airwallex\/awxsession","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","abstract":[],"type":"topic","kind":"symbol","title":"Airwallex","role":"collection"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXUIContextConfiguration":{"abstract":[{"text":"Configuration options for launching the payment UI.","type":"text"},{"text":" ","type":"text"},{"text":"Use this class to customize the payment flow launched by ","type":"text"},{"text":"AWXUIContext","type":"text"},{"text":".","type":"text"}],"title":"AWXUIContextConfiguration","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContextConfiguration","fragments":[{"kind":"identifier","text":"AWXUIContextConfiguration"}],"kind":"symbol","url":"\/documentation\/airwallex\/awxuicontextconfiguration","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXUIContext/Configuration":{"title":"AWXUIContext.Configuration","abstract":[{"type":"text","text":"Configuration options for launching the payment UI."}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/Configuration","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"kind":"symbol","url":"\/documentation\/airwallex\/awxuicontext\/configuration","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXUIContext":{"title":"AWXUIContext","abstract":[{"text":"The main UI context for Airwallex payment flows.","type":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext","navigatorTitle":[{"text":"AWXUIContext","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXUIContext","kind":"identifier"}],"type":"topic","url":"\/documentation\/airwallex\/awxuicontext","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentResultDelegate":{"title":"AWXPaymentResultDelegate","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentResultDelegate","navigatorTitle":[{"kind":"identifier","text":"AWXPaymentResultDelegate"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPaymentResultDelegate","kind":"identifier"}],"type":"topic","url":"\/documentation\/airwallex\/awxpaymentresultdelegate","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXUIContext/launchPayment(from:session:configuration:)":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"launchPayment"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)AWXPaymentResultDelegate","text":"AWXPaymentResultDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"session"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AWXSession","text":"AWXSession","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"configuration","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:9Airwallex12AWXUIContextC13ConfigurationC","text":"Configuration"},{"kind":"text","text":")"}],"role":"symbol","url":"\/documentation\/airwallex\/awxuicontext\/launchpayment(from:session:configuration:)","navigatorTitle":[{"kind":"identifier","text":"launchPaymentFrom:session:configuration:"}],"type":"topic","abstract":[{"text":"Launches the Airwallex payment UI using a configuration object.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/launchPayment(from:session:configuration:)","title":"launchPayment(from:session:configuration:)","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"launchPaymentFrom:session:configuration:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"launchPaymentFrom:session:configuration:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"launchPaymentFrom:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)UIViewControllerobjc(pl)AWXPaymentResultDelegate","kind":"typeIdentifier","text":"UIViewController<AWXPaymentResultDelegate>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"hostingVC"},{"text":" ","kind":"text"},{"text":"session:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AWXSession","preciseIdentifier":"c:objc(cs)AWXSession","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"session"},{"kind":"text","text":" "},{"kind":"identifier","text":"configuration:"},{"text":"(","kind":"text"},{"text":"AWXUIContextConfiguration","preciseIdentifier":"c:@M@Airwallex@objc(cs)AWXUIContextConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContextConfiguration"},{"text":" *) ","kind":"text"},{"text":"configuration","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"hostingVC","content":[{"inlineContent":[{"type":"text","text":"The view controller that launches the payment UI and also acts as the "},{"type":"codeVoice","code":"AWXPaymentResultDelegate"},{"type":"text","text":"."}],"type":"paragraph"}]},{"name":"session","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The current payment session."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Configuration for the payment flow."}]}],"name":"configuration"}]},"op":"replace"},{"value":"AWXSession","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/title","op":"replace"},{"value":[{"text":"AWXSession","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/fragments","op":"replace"},{"value":[{"text":"AWXSession","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/navigatorTitle","op":"replace"},{"value":"AWXUIContext","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext\/title","op":"replace"},{"value":[{"text":"AWXUIContext","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AWXUIContext"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentResultDelegate\/title","op":"replace","value":"AWXPaymentResultDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentResultDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"AWXPaymentResultDelegate"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentResultDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AWXPaymentResultDelegate"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext~1launchPayment(from:session:configuration:)\/title","op":"replace","value":"launchPaymentFrom:session:configuration:"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext~1launchPayment(from:session:configuration:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"launchPaymentFrom:session:configuration:","kind":"identifier"}]}]}]}