{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/TermsOfUse"]]},"metadata":{"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxPaymentAmount","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSDecimalNumber","text":"NSDecimalNumber","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"symbolKind":"property","modules":[{"name":"Airwallex"}],"roleHeading":"Instance Property","title":"maxPaymentAmount","externalID":"c:@M@Airwallex@objc(cs)TermsOfUse(py)maxPaymentAmount","navigatorTitle":[{"text":"maxPaymentAmount","kind":"identifier"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/termsofuse\/maxpaymentamount"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/termsofuse\/maxpaymentamount"]}],"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxPaymentAmount"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSDecimalNumber","kind":"typeIdentifier","text":"NSDecimalNumber"},{"kind":"text","text":"?"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/TermsOfUse\/maxPaymentAmount"},"abstract":[{"text":"The maximum payment amount that can be charged for a single payment.","type":"text"},{"text":" ","type":"text"},{"text":"Optional if payment agreement type is VARIABLE.","type":"text"}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/TermsOfUse/maxPaymentAmount":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/TermsOfUse\/maxPaymentAmount","type":"topic","role":"symbol","kind":"symbol","title":"maxPaymentAmount","abstract":[{"type":"text","text":"The maximum payment amount that can be charged for a single payment."},{"type":"text","text":" "},{"type":"text","text":"Optional if payment agreement type is VARIABLE."}],"navigatorTitle":[{"kind":"identifier","text":"maxPaymentAmount"}],"url":"\/documentation\/airwallex\/termsofuse\/maxpaymentamount","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxPaymentAmount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDecimalNumber","text":"NSDecimalNumber"},{"kind":"text","text":"?"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/TermsOfUse":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/TermsOfUse","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TermsOfUse","kind":"identifier"}],"abstract":[{"type":"text","text":"Terms to specify how this Payment Consent will be used"}],"type":"topic","url":"\/documentation\/airwallex\/termsofuse","navigatorTitle":[{"text":"TermsOfUse","kind":"identifier"}],"title":"TermsOfUse"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"title":"Airwallex","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/airwallex","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"maxPaymentAmount","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"maxPaymentAmount"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSDecimalNumber","kind":"typeIdentifier","text":"NSDecimalNumber"},{"kind":"text","text":" * "},{"kind":"identifier","text":"maxPaymentAmount"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1TermsOfUse~1maxPaymentAmount\/title","value":"maxPaymentAmount"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1TermsOfUse~1maxPaymentAmount\/fragments","value":[{"kind":"identifier","text":"maxPaymentAmount"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1TermsOfUse\/title","value":"TermsOfUse"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1TermsOfUse\/fragments","value":[{"text":"TermsOfUse","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1TermsOfUse\/navigatorTitle","value":[{"kind":"identifier","text":"TermsOfUse"}]}]}]}