{"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAPIClientConfiguration\/accountID","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accountID","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"metadata":{"modules":[{"name":"Airwallex"}],"title":"accountID","externalID":"c:objc(cs)AWXAPIClientConfiguration(py)accountID","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"accountID"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"accountID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"role":"symbol"},"kind":"symbol","abstract":[{"type":"text","text":"The account ID from client secret."}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAPIClientConfiguration"]]},"variants":[{"paths":["\/documentation\/airwallex\/awxapiclientconfiguration\/accountid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxapiclientconfiguration\/accountid"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","role":"collection","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXAPIClientConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"AWXAPIClientConfiguration"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAPIClientConfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXAPIClientConfiguration"}],"title":"AWXAPIClientConfiguration","kind":"symbol","abstract":[{"type":"codeVoice","code":"AWXAPIClientConfiguration"},{"type":"text","text":" contains the base configuration the API client needs."}],"url":"\/documentation\/airwallex\/awxapiclientconfiguration"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXAPIClientConfiguration/accountID":{"title":"accountID","role":"symbol","url":"\/documentation\/airwallex\/awxapiclientconfiguration\/accountid","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accountID","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAPIClientConfiguration\/accountID","abstract":[{"type":"text","text":"The account ID from client secret."}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"accountID","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"accountID"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"accountID"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"accountID"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIClientConfiguration\/title","value":"AWXAPIClientConfiguration"},{"op":"replace","value":[{"kind":"identifier","text":"AWXAPIClientConfiguration"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIClientConfiguration\/fragments"},{"op":"replace","value":[{"text":"AWXAPIClientConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIClientConfiguration\/navigatorTitle"},{"op":"replace","value":"accountID","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIClientConfiguration~1accountID\/title"},{"op":"replace","value":[{"text":"accountID","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIClientConfiguration~1accountID\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}