{"variants":[{"paths":["\/documentation\/airwallex\/awxapiclientconfiguration\/shared()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxapiclientconfiguration\/shared()"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Self"}]}],"kind":"declarations"},{"content":[{"anchor":"return-value","type":"heading","text":"Return Value","level":2},{"inlineContent":[{"type":"text","text":"The shared configuration."}],"type":"paragraph"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAPIClientConfiguration"]]},"metadata":{"externalID":"c:objc(cs)AWXAPIClientConfiguration(cm)sharedConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"}],"symbolKind":"method","title":"shared()","navigatorTitle":[{"kind":"identifier","text":"sharedConfiguration"}],"modules":[{"name":"Airwallex"}],"roleHeading":"Type Method","role":"symbol"},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAPIClientConfiguration\/shared()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Convenience constructor for a configuration."}],"kind":"symbol","references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXAPIClientConfiguration":{"title":"AWXAPIClientConfiguration","abstract":[{"code":"AWXAPIClientConfiguration","type":"codeVoice"},{"type":"text","text":" contains the base configuration the API client needs."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXAPIClientConfiguration","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAPIClientConfiguration","url":"\/documentation\/airwallex\/awxapiclientconfiguration","navigatorTitle":[{"text":"AWXAPIClientConfiguration","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXAPIClientConfiguration/shared()":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAPIClientConfiguration\/shared()","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"}],"title":"shared()","kind":"symbol","abstract":[{"type":"text","text":"Convenience constructor for a configuration."}],"role":"symbol","url":"\/documentation\/airwallex\/awxapiclientconfiguration\/shared()","navigatorTitle":[{"text":"sharedConfiguration","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol","type":"topic","url":"\/documentation\/airwallex","role":"collection","abstract":[],"title":"Airwallex"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"sharedConfiguration","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"sharedConfiguration"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"sharedConfiguration"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"The shared configuration.","type":"text"}]}],"kind":"content"},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"AWXAPIClientConfiguration","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIClientConfiguration\/title","op":"replace"},{"value":[{"text":"AWXAPIClientConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIClientConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AWXAPIClientConfiguration"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIClientConfiguration\/navigatorTitle","op":"replace"},{"value":"sharedConfiguration","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIClientConfiguration~1shared()\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"sharedConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIClientConfiguration~1shared()\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}