{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypesRequest"]]},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypesRequest\/countryCode","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/airwallex\/awxgetpaymentmethodtypesrequest\/countrycode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxgetpaymentmethodtypesrequest\/countrycode"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"Airwallex"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"countryCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"title":"countryCode","externalID":"c:objc(cs)AWXGetPaymentMethodTypesRequest(py)countryCode","navigatorTitle":[{"text":"countryCode","kind":"identifier"}],"roleHeading":"Instance Property","symbolKind":"property","role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Country code."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"countryCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentMethodTypesRequest/countryCode":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"countryCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"countryCode","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypesRequest\/countryCode","type":"topic","navigatorTitle":[{"kind":"identifier","text":"countryCode"}],"abstract":[{"type":"text","text":"Country code."}],"url":"\/documentation\/airwallex\/awxgetpaymentmethodtypesrequest\/countrycode"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","abstract":[],"type":"topic","kind":"symbol","title":"Airwallex","role":"collection"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentMethodTypesRequest":{"abstract":[{"code":"AWXGetPaymentMethodTypesRequest","type":"codeVoice"},{"text":" includes all of the parameters needed to get payment method types.","type":"text"}],"title":"AWXGetPaymentMethodTypesRequest","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypesRequest","navigatorTitle":[{"kind":"identifier","text":"AWXGetPaymentMethodTypesRequest"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXGetPaymentMethodTypesRequest"}],"kind":"symbol","url":"\/documentation\/airwallex\/awxgetpaymentmethodtypesrequest","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"countryCode","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"countryCode"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"countryCode","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"countryCode","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypesRequest~1countryCode\/title"},{"value":[{"kind":"identifier","text":"countryCode"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypesRequest~1countryCode\/fragments"},{"value":"AWXGetPaymentMethodTypesRequest","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypesRequest\/title"},{"value":[{"kind":"identifier","text":"AWXGetPaymentMethodTypesRequest"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypesRequest\/fragments"},{"value":[{"kind":"identifier","text":"AWXGetPaymentMethodTypesRequest"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypesRequest\/navigatorTitle"}]}]}