{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethodFlow"]]},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethodFlow\/Equatable-Implementations","interfaceLanguage":"swift"},"kind":"article","metadata":{"role":"collectionGroup","title":"Equatable Implementations","modules":[{"name":"Airwallex"}],"roleHeading":"API Collection"},"topicSections":[{"anchor":"Operators","generated":true,"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethodFlow\/!=(_:_:)"],"title":"Operators"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxpaymentmethodflow\/equatable-implementations"]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"kind":"symbol","abstract":[],"role":"collection","type":"topic","url":"\/documentation\/airwallex","title":"Airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentMethodFlow/!=(_:_:)":{"kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[],"title":"!=(_:_:)","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethodFlow\/!=(_:_:)","url":"\/documentation\/airwallex\/awxpaymentmethodflow\/!=(_:_:)"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentMethodFlow":{"title":"AWXPaymentMethodFlow","url":"\/documentation\/airwallex\/awxpaymentmethodflow","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentMethodFlow"}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethodFlow","navigatorTitle":[{"kind":"identifier","text":"AWXPaymentMethodFlow"}],"abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethodFlow\/title","value":"AWXPaymentMethodFlow","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethodFlow\/fragments","value":[{"kind":"identifier","text":"AWXPaymentMethodFlow"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethodFlow\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AWXPaymentMethodFlow"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}