{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxrecurringsession\/merchanttriggerreason"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxrecurringsession\/merchanttriggerreason"]}],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Will be removed in next major version release, use AirwallexPayment.Session instead"}],"type":"paragraph"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"merchantTriggerReason","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@AirwallexMerchantTriggerReason","text":"AirwallexMerchantTriggerReason","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexMerchantTriggerReason"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"platforms":[{"beta":false,"message":"Will be removed in next major version release, use AirwallexPayment.Session instead","deprecated":true,"unavailable":false}],"title":"merchantTriggerReason","roleHeading":"Instance Property","role":"symbol","modules":[{"name":"Airwallex"}],"externalID":"c:objc(cs)AWXRecurringSession(py)merchantTriggerReason","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"merchantTriggerReason","kind":"identifier"},{"kind":"text","text":": "},{"text":"AirwallexMerchantTriggerReason","preciseIdentifier":"c:@E@AirwallexMerchantTriggerReason","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"merchantTriggerReason"}]},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession\/merchantTriggerReason","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"Merchant trigger reason"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession"]]},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRecurringSession":{"deprecated":true,"title":"AWXRecurringSession","navigatorTitle":[{"text":"AWXRecurringSession","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession","url":"\/documentation\/airwallex\/awxrecurringsession","role":"symbol","abstract":[{"type":"codeVoice","code":"AWXRecurringSession"},{"text":" is the session used for recurring.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXRecurringSession","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRecurringSession/merchantTriggerReason":{"type":"topic","abstract":[{"type":"text","text":"Merchant trigger reason"}],"deprecated":true,"role":"symbol","navigatorTitle":[{"text":"merchantTriggerReason","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxrecurringsession\/merchanttriggerreason","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringSession\/merchantTriggerReason","title":"merchantTriggerReason","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"merchantTriggerReason","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AirwallexMerchantTriggerReason","kind":"typeIdentifier","preciseIdentifier":"c:@E@AirwallexMerchantTriggerReason"}],"kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexMerchantTriggerReason":{"url":"\/documentation\/airwallex\/airwallexmerchanttriggerreason","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"AirwallexMerchantTriggerReason","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AirwallexMerchantTriggerReason","kind":"identifier"}],"title":"AirwallexMerchantTriggerReason","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexMerchantTriggerReason","abstract":[],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","type":"topic","role":"collection","title":"Airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":[{"deprecated":true,"beta":false,"unavailable":false}],"op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"merchantTriggerReason","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"merchantTriggerReason","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"AirwallexMerchantTriggerReason","preciseIdentifier":"c:@E@AirwallexMerchantTriggerReason","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexMerchantTriggerReason"},{"kind":"text","text":" "},{"kind":"identifier","text":"merchantTriggerReason"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/deprecationSummary","value":[{"inlineContent":[{"text":"Will be removed in next major version release, use AirwallexPayment.Session instead","type":"text"}],"type":"paragraph"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRecurringSession\/title","value":"AWXRecurringSession","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRecurringSession\/fragments","value":[{"text":"AWXRecurringSession","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRecurringSession\/navigatorTitle","value":[{"text":"AWXRecurringSession","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRecurringSession~1merchantTriggerReason\/title","value":"merchantTriggerReason","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRecurringSession~1merchantTriggerReason\/fragments","value":[{"text":"merchantTriggerReason","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexMerchantTriggerReason\/title","value":"AirwallexMerchantTriggerReason","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexMerchantTriggerReason\/fragments","value":[{"text":"AirwallexMerchantTriggerReason","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexMerchantTriggerReason\/navigatorTitle","value":[{"text":"AirwallexMerchantTriggerReason","kind":"identifier"}],"op":"replace"}]}]}