{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"shipping","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AWXPlaceDetails","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPlaceDetails","text":"AWXPlaceDetails","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@Airwallex@objc(pl)AWXShippingViewControllerDelegate","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXShippingViewControllerDelegate","text":"AWXShippingViewControllerDelegate","kind":"typeIdentifier"},{"text":")? = nil)","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/airwallex\/awxshippingviewcontroller\/init(shipping:delegate:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXShippingViewController\/init(shipping:delegate:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"externalID":"s:9Airwallex25AWXShippingViewControllerC8shipping8delegateACSo15AWXPlaceDetailsCSg_AA0bcD8Delegate_pSgtcfc","title":"init(shipping:delegate:)","role":"symbol","roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"shipping","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AWXPlaceDetails","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPlaceDetails"},{"text":"?, ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXShippingViewControllerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@Airwallex@objc(pl)AWXShippingViewControllerDelegate"},{"text":")?)","kind":"text"}],"modules":[{"name":"Airwallex"}],"symbolKind":"init"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXShippingViewController"]]},"sections":[],"kind":"symbol","references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXShippingViewController":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"AWXShippingViewController"}],"url":"\/documentation\/airwallex\/awxshippingviewcontroller","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXShippingViewController","title":"AWXShippingViewController","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXShippingViewController"}],"role":"symbol","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","role":"collection","title":"Airwallex","type":"topic","url":"\/documentation\/airwallex","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXShippingViewController/init(shipping:delegate:)":{"type":"topic","abstract":[],"title":"init(shipping:delegate:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXShippingViewController\/init(shipping:delegate:)","url":"\/documentation\/airwallex\/awxshippingviewcontroller\/init(shipping:delegate:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"shipping","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AWXPlaceDetails","text":"AWXPlaceDetails","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@Airwallex@objc(pl)AWXShippingViewControllerDelegate","text":"AWXShippingViewControllerDelegate","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPlaceDetails":{"type":"topic","navigatorTitle":[{"text":"AWXPlaceDetails","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxplacedetails","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPlaceDetails","title":"AWXPlaceDetails","abstract":[{"type":"codeVoice","code":"AWXPlaceDetails"},{"type":"text","text":" includes the information of a billing address."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPlaceDetails","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXShippingViewControllerDelegate":{"type":"topic","abstract":[],"title":"AWXShippingViewControllerDelegate","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXShippingViewControllerDelegate","navigatorTitle":[{"kind":"identifier","text":"AWXShippingViewControllerDelegate"}],"url":"\/documentation\/airwallex\/awxshippingviewcontrollerdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXShippingViewControllerDelegate"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXShippingViewController\/title","value":"AWXShippingViewController","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXShippingViewController\/fragments","op":"replace","value":[{"text":"AWXShippingViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXShippingViewController\/navigatorTitle","op":"replace","value":[{"text":"AWXShippingViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPlaceDetails\/title","op":"replace","value":"AWXPlaceDetails"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPlaceDetails\/fragments","op":"replace","value":[{"text":"AWXPlaceDetails","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPlaceDetails\/navigatorTitle","op":"replace","value":[{"text":"AWXPlaceDetails","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXShippingViewControllerDelegate\/title","op":"replace","value":"AWXShippingViewControllerDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXShippingViewControllerDelegate\/fragments","op":"replace","value":[{"text":"AWXShippingViewControllerDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXShippingViewControllerDelegate\/navigatorTitle","op":"replace","value":[{"text":"AWXShippingViewControllerDelegate","kind":"identifier"}]}]}]}