{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"launchCardPayment","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"hostingVC","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"session","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession","text":"AWXSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXSession"},{"text":", ","kind":"text"},{"text":"paymentResultDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentResultDelegate","text":"AWXPaymentResultDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)AWXPaymentResultDelegate"},{"text":", ","kind":"text"},{"text":"supportedBrands","kind":"externalParam"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand","text":"AWXCardBrand","kind":"typeIdentifier","preciseIdentifier":"c:AWXConstants.h@T@AWXCardBrand"},{"text":"] = AWXCardBrand.allAvailable, ","kind":"text"},{"text":"launchStyle","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/LaunchStyle","text":"LaunchStyle","kind":"typeIdentifier","preciseIdentifier":"s:9Airwallex12AWXUIContextC11LaunchStyleO"},{"text":" = .push)","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"hostingVC","content":[{"type":"paragraph","inlineContent":[{"text":"The view controller that presents the payment sheet","type":"text"}]}]},{"name":"session","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The active payment session."}]}]},{"name":"paymentResultDelegate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The delegate responsible for handling the payment result."}]}]},{"name":"supportedBrands","content":[{"inlineContent":[{"type":"text","text":"A list of supported card brands for the payment session."}],"type":"paragraph"}]},{"name":"launchStyle","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The presentation style of the payment sheet, which defaults to "},{"code":".push","type":"codeVoice"},{"type":"text","text":"."}]}]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/launchCardPayment(from:session:paymentResultDelegate:supportedBrands:launchStyle:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxuicontext\/launchcardpayment(from:session:paymentresultdelegate:supportedbrands:launchstyle:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxuicontext\/launchcardpayment(from:session:paymentresultdelegate:supportedbrands:launchstyle:)"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"abstract":[{"type":"text","text":"Launches the Airwallex card payment flow."}],"metadata":{"title":"launchCardPayment(from:session:paymentResultDelegate:supportedBrands:launchStyle:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"launchCardPayment"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"session"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXSession","text":"AWXSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"paymentResultDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)AWXPaymentResultDelegate","text":"AWXPaymentResultDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"supportedBrands"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:AWXConstants.h@T@AWXCardBrand","text":"AWXCardBrand"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"launchStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:9Airwallex12AWXUIContextC11LaunchStyleO","text":"LaunchStyle"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"launchCardPaymentFrom:session:paymentResultDelegate:supportedBrands:launchStyle:"}],"externalID":"c:@CM@Airwallex@objc(cs)AWXUIContext(cm)launchCardPaymentFrom:session:paymentResultDelegate:supportedBrands:launchStyle:","extendedModule":"Airwallex","modules":[{"name":"Airwallex"}],"role":"symbol","roleHeading":"Type Method","symbolKind":"method"},"kind":"symbol","references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","url":"\/documentation\/airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol","title":"Airwallex","abstract":[],"role":"collection"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentResultDelegate":{"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentResultDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentResultDelegate"}],"title":"AWXPaymentResultDelegate","url":"\/documentation\/airwallex\/awxpaymentresultdelegate","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWXPaymentResultDelegate"}],"abstract":[],"role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXUIContext/LaunchStyle":{"kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/LaunchStyle","role":"symbol","title":"AWXUIContext.LaunchStyle","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LaunchStyle","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"LaunchStyle","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxuicontext\/launchstyle"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXUIContext":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXUIContext","kind":"identifier"}],"title":"AWXUIContext","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext","abstract":[{"type":"text","text":"The main UI context for Airwallex payment flows."}],"kind":"symbol","url":"\/documentation\/airwallex\/awxuicontext","navigatorTitle":[{"text":"AWXUIContext","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXUIContext/launchCardPayment(from:session:paymentResultDelegate:supportedBrands:launchStyle:)":{"title":"launchCardPayment(from:session:paymentResultDelegate:supportedBrands:launchStyle:)","type":"topic","kind":"symbol","url":"\/documentation\/airwallex\/awxuicontext\/launchcardpayment(from:session:paymentresultdelegate:supportedbrands:launchstyle:)","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/launchCardPayment(from:session:paymentResultDelegate:supportedBrands:launchStyle:)","role":"symbol","abstract":[{"type":"text","text":"Launches the Airwallex card payment flow."}],"navigatorTitle":[{"kind":"identifier","text":"launchCardPaymentFrom:session:paymentResultDelegate:supportedBrands:launchStyle:"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"launchCardPayment"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"session"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXSession","text":"AWXSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"paymentResultDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)AWXPaymentResultDelegate","text":"AWXPaymentResultDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"supportedBrands"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:AWXConstants.h@T@AWXCardBrand","text":"AWXCardBrand"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"launchStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:9Airwallex12AWXUIContextC11LaunchStyleO","text":"LaunchStyle"},{"kind":"text","text":")"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/LaunchStyle":{"kind":"symbol","type":"topic","abstract":[],"fragments":[{"kind":"identifier","text":"LaunchStyle"}],"url":"\/documentation\/airwallex\/launchstyle","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/LaunchStyle","role":"symbol","title":"LaunchStyle"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSession":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXSession","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxsession","type":"topic","navigatorTitle":[{"text":"AWXSession","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"AWXSession"},{"text":" is the base session.","type":"text"}],"kind":"symbol","title":"AWXSession"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardBrand":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXCardBrand"}],"navigatorTitle":[{"kind":"identifier","text":"AWXCardBrand"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand","abstract":[],"title":"AWXCardBrand","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/airwallex\/awxcardbrand"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"launchCardPaymentFrom:session:paymentResultDelegate:supportedBrands:launchStyle:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"launchCardPaymentFrom:session:paymentResultDelegate:supportedBrands:launchStyle:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"launchCardPaymentFrom:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"hostingVC","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"session:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AWXSession","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession","preciseIdentifier":"c:objc(cs)AWXSession"},{"text":" *) ","kind":"text"},{"text":"session","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"paymentResultDelegate:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<AWXPaymentResultDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)AWXPaymentResultDelegate"},{"text":") ","kind":"text"},{"text":"paymentResultDelegate","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"supportedBrands:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"supportedBrands","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"launchStyle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LaunchStyle","preciseIdentifier":"c:@M@Airwallex@E@LaunchStyle","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/LaunchStyle","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"launchStyle","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The view controller that presents the payment sheet","type":"text"}]}],"name":"hostingVC"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The active payment session.","type":"text"}]}],"name":"session"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The delegate responsible for handling the payment result."}]}],"name":"paymentResultDelegate"},{"content":[{"type":"paragraph","inlineContent":[{"text":"A list of supported card brands for the payment session.","type":"text"}]}],"name":"supportedBrands"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The presentation style of the payment sheet, which defaults to ","type":"text"},{"code":".push","type":"codeVoice"},{"text":".","type":"text"}]}],"name":"launchStyle"}],"kind":"parameters"}},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentResultDelegate\/title","op":"replace","value":"AWXPaymentResultDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentResultDelegate\/fragments","op":"replace","value":[{"text":"AWXPaymentResultDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentResultDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AWXPaymentResultDelegate"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext\/title","op":"replace","value":"AWXUIContext"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext\/fragments","op":"replace","value":[{"kind":"identifier","text":"AWXUIContext"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext\/navigatorTitle","op":"replace","value":[{"text":"AWXUIContext","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext~1launchCardPayment(from:session:paymentResultDelegate:supportedBrands:launchStyle:)\/title","op":"replace","value":"launchCardPaymentFrom:session:paymentResultDelegate:supportedBrands:launchStyle:"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext~1launchCardPayment(from:session:paymentResultDelegate:supportedBrands:launchStyle:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"launchCardPaymentFrom:session:paymentResultDelegate:supportedBrands:launchStyle:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/title","op":"replace","value":"AWXSession"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/fragments","op":"replace","value":[{"text":"AWXSession","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/navigatorTitle","op":"replace","value":[{"text":"AWXSession","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardBrand\/title","op":"replace","value":"AWXCardBrand"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardBrand\/fragments","op":"replace","value":[{"kind":"identifier","text":"AWXCardBrand"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardBrand\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AWXCardBrand"}]}]}]}