{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler\/canHandle(methodType:session:)"},"kind":"symbol","metadata":{"extendedModule":"Airwallex","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"canHandle"},{"kind":"text","text":"("},{"kind":"externalParam","text":"methodType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPaymentMethodType","text":"AWXPaymentMethodType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"session"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXSession","text":"AWXSession"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"role":"symbol","externalID":"c:@CM@Airwallex@objc(cs)PaymentSessionHandler(cm)canHandleWithMethodType:session:","navigatorTitle":[{"text":"canHandleWithMethodType:session:","kind":"identifier"}],"modules":[{"name":"Airwallex"}],"symbolKind":"method","title":"canHandle(methodType:session:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"canHandle"},{"kind":"text","text":"("},{"kind":"externalParam","text":"methodType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethodType","text":"AWXPaymentMethodType","preciseIdentifier":"c:objc(cs)AWXPaymentMethodType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"session"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession","text":"AWXSession","preciseIdentifier":"c:objc(cs)AWXSession"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/airwallex\/paymentsessionhandler\/canhandle(methodtype:session:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/paymentsessionhandler\/canhandle(methodtype:session:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSession":{"navigatorTitle":[{"kind":"identifier","text":"AWXSession"}],"title":"AWXSession","kind":"symbol","type":"topic","url":"\/documentation\/airwallex\/awxsession","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession","abstract":[{"code":"AWXSession","type":"codeVoice"},{"type":"text","text":" is the base session."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXSession"}],"role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentSessionHandler/canHandle(methodType:session:)":{"title":"canHandle(methodType:session:)","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"canHandle"},{"kind":"text","text":"("},{"kind":"externalParam","text":"methodType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWXPaymentMethodType","preciseIdentifier":"c:objc(cs)AWXPaymentMethodType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"session"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWXSession","preciseIdentifier":"c:objc(cs)AWXSession"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","url":"\/documentation\/airwallex\/paymentsessionhandler\/canhandle(methodtype:session:)","navigatorTitle":[{"text":"canHandleWithMethodType:session:","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler\/canHandle(methodType:session:)"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","url":"\/documentation\/airwallex","role":"collection","kind":"symbol","abstract":[],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentSessionHandler":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler","navigatorTitle":[{"text":"PaymentSessionHandler","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PaymentSessionHandler","kind":"identifier"}],"title":"PaymentSessionHandler","role":"symbol","url":"\/documentation\/airwallex\/paymentsessionhandler","kind":"symbol","abstract":[{"type":"text","text":"A low-level API handler for managing Airwallex payment sessions."}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentMethodType":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentMethodType"}],"navigatorTitle":[{"kind":"identifier","text":"AWXPaymentMethodType"}],"title":"AWXPaymentMethodType","role":"symbol","type":"topic","abstract":[{"code":"AWXPaymentMethodType","type":"codeVoice"},{"text":" includes the information of a payment method.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethodType","url":"\/documentation\/airwallex\/awxpaymentmethodtype"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"canHandleWithMethodType:session:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"canHandleWithMethodType:session:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"canHandleWithMethodType:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethodType","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPaymentMethodType","text":"AWXPaymentMethodType"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"methodType"},{"kind":"text","text":" "},{"kind":"identifier","text":"session:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXSession","text":"AWXSession"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"session"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"AWXSession","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AWXSession"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/fragments"},{"op":"replace","value":[{"text":"AWXSession","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/navigatorTitle"},{"op":"replace","value":"canHandleWithMethodType:session:","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler~1canHandle(methodType:session:)\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"canHandleWithMethodType:session:"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler~1canHandle(methodType:session:)\/fragments"},{"op":"replace","value":"PaymentSessionHandler","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler\/title"},{"op":"replace","value":[{"text":"PaymentSessionHandler","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"PaymentSessionHandler"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler\/navigatorTitle"},{"op":"replace","value":"AWXPaymentMethodType","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethodType\/title"},{"op":"replace","value":[{"text":"AWXPaymentMethodType","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethodType\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AWXPaymentMethodType"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethodType\/navigatorTitle"}]}]}