{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"showIndicator"}],"title":"showIndicator","modules":[{"name":"Airwallex"}],"roleHeading":"Instance Property","role":"symbol","externalID":"c:@M@Airwallex@objc(cs)PaymentSessionHandler(py)showIndicator","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"showIndicator"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"kind":"symbol","variants":[{"paths":["\/documentation\/airwallex\/paymentsessionhandler\/showindicator"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/paymentsessionhandler\/showindicator"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler\/showIndicator","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showIndicator","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"text":"whether display the default loading indicator","type":"text"},{"text":" ","type":"text"},{"text":"Set this to false if you prefer to display your own indicator instead of the default one","type":"text"}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentSessionHandler/showIndicator":{"abstract":[{"type":"text","text":"whether display the default loading indicator"},{"type":"text","text":" "},{"type":"text","text":"Set this to false if you prefer to display your own indicator instead of the default one"}],"url":"\/documentation\/airwallex\/paymentsessionhandler\/showindicator","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler\/showIndicator","navigatorTitle":[{"text":"showIndicator","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showIndicator","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","title":"showIndicator"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","url":"\/documentation\/airwallex","abstract":[],"title":"Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentSessionHandler":{"role":"symbol","type":"topic","title":"PaymentSessionHandler","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentSessionHandler"}],"navigatorTitle":[{"kind":"identifier","text":"PaymentSessionHandler"}],"kind":"symbol","abstract":[{"type":"text","text":"A low-level API handler for managing Airwallex payment sessions."}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler","url":"\/documentation\/airwallex\/paymentsessionhandler"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"showIndicator"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"showIndicator"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"showIndicator","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler~1showIndicator\/title","op":"replace","value":"showIndicator"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler~1showIndicator\/fragments","op":"replace","value":[{"kind":"identifier","text":"showIndicator"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler\/title","op":"replace","value":"PaymentSessionHandler"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler\/fragments","op":"replace","value":[{"kind":"identifier","text":"PaymentSessionHandler"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"PaymentSessionHandler"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}