{"abstract":[{"type":"text","text":"Initiates an Apple Pay transaction."},{"type":"text","text":" "},{"type":"text","text":"This method sets up and starts the Apple Pay payment flow."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/airwallex\/paymentsessionhandler\/startapplepay()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/paymentsessionhandler\/startapplepay()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler\/startApplePay()"},"metadata":{"externalID":"c:@CM@Airwallex@objc(cs)PaymentSessionHandler(im)startApplePay","extendedModule":"Airwallex","symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"Airwallex"}],"navigatorTitle":[{"text":"startApplePay","kind":"identifier"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startApplePay","kind":"identifier"},{"text":"()","kind":"text"}],"title":"startApplePay()"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startApplePay"},{"kind":"text","text":"()"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler"]]},"kind":"symbol","sections":[],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentSessionHandler":{"role":"symbol","type":"topic","title":"PaymentSessionHandler","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentSessionHandler"}],"navigatorTitle":[{"kind":"identifier","text":"PaymentSessionHandler"}],"kind":"symbol","abstract":[{"type":"text","text":"A low-level API handler for managing Airwallex payment sessions."}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler","url":"\/documentation\/airwallex\/paymentsessionhandler"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentSessionHandler/startApplePay()":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"startApplePay","kind":"identifier"},{"kind":"text","text":"()"}],"title":"startApplePay()","url":"\/documentation\/airwallex\/paymentsessionhandler\/startapplepay()","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler\/startApplePay()","role":"symbol","type":"topic","navigatorTitle":[{"text":"startApplePay","kind":"identifier"}],"abstract":[{"text":"Initiates an Apple Pay transaction.","type":"text"},{"text":" ","type":"text"},{"text":"This method sets up and starts the Apple Pay payment flow.","type":"text"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","url":"\/documentation\/airwallex","abstract":[],"title":"Airwallex"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"startApplePay","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"startApplePay","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"startApplePay","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"PaymentSessionHandler","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler\/title","op":"replace"},{"value":[{"text":"PaymentSessionHandler","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler\/fragments","op":"replace"},{"value":[{"text":"PaymentSessionHandler","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler\/navigatorTitle","op":"replace"},{"value":"startApplePay","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler~1startApplePay()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"startApplePay","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler~1startApplePay()\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}