{"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Initiates a consent-based subsequent one-off payment using a consent identifier with optional CVC requirement."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startConsentPayment","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withId","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"consentId","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"requiresCVC","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":" = false)"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The unique identifier of the previously created payment consent.","type":"text"}]}],"name":"consentId"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Whether to prompt the user for CVC input. Defaults to "},{"type":"codeVoice","code":"false"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Set to "},{"type":"codeVoice","code":"true"},{"type":"text","text":" for PAN-type consents that require CVC validation."}]}],"name":"requiresCVC"}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use this method when you have stored the consent ID and want to control whether CVC input is required."}]},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"CVC Requirement Guidelines:"}]}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Set "},{"code":"requiresCVC","type":"codeVoice"},{"type":"text","text":" to "},{"code":"true","type":"codeVoice"},{"type":"text","text":" when the consent’s "},{"code":"numberType","type":"codeVoice"},{"type":"text","text":" is “PAN” for enhanced security"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Set "},{"type":"codeVoice","code":"requiresCVC"},{"type":"text","text":" to "},{"type":"codeVoice","code":"false"},{"type":"text","text":" for tokenized payment methods that don’t require CVC re-entry"}]}]}]}]}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler\/startConsentPayment(withId:requiresCVC:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/paymentsessionhandler\/startconsentpayment(withid:requirescvc:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/paymentsessionhandler\/startconsentpayment(withid:requirescvc:)"]}],"metadata":{"title":"startConsentPayment(withId:requiresCVC:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startConsentPayment"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"requiresCVC"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"modules":[{"name":"Airwallex"}],"extendedModule":"Airwallex","navigatorTitle":[{"kind":"identifier","text":"startConsentPaymentWithId:requiresCVC:"}],"externalID":"c:@CM@Airwallex@objc(cs)PaymentSessionHandler(im)startConsentPaymentWithId:requiresCVC:","role":"symbol","symbolKind":"method","roleHeading":"Instance Method"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler"]]},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","abstract":[],"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentSessionHandler/startConsentPayment(withId:requiresCVC:)":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"startConsentPaymentWithId:requiresCVC:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler\/startConsentPayment(withId:requiresCVC:)","title":"startConsentPayment(withId:requiresCVC:)","url":"\/documentation\/airwallex\/paymentsessionhandler\/startconsentpayment(withid:requirescvc:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startConsentPayment"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withId"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"requiresCVC","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Initiates a consent-based subsequent one-off payment using a consent identifier with optional CVC requirement."}],"kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentSessionHandler":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler","abstract":[{"type":"text","text":"A low-level API handler for managing Airwallex payment sessions."}],"title":"PaymentSessionHandler","url":"\/documentation\/airwallex\/paymentsessionhandler","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PaymentSessionHandler","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"PaymentSessionHandler","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"startConsentPaymentWithId:requiresCVC:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"startConsentPaymentWithId:requiresCVC:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"startConsentPaymentWithId:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"consentId","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"requiresCVC:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"requiresCVC","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"name":"consentId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The unique identifier of the previously created payment consent."}]}]},{"name":"requiresCVC","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Whether to prompt the user for CVC input. Defaults to "},{"type":"codeVoice","code":"false"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Set to "},{"type":"codeVoice","code":"true"},{"type":"text","text":" for PAN-type consents that require CVC validation."}]}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"startConsentPaymentWithId:requiresCVC:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler~1startConsentPayment(withId:requiresCVC:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startConsentPaymentWithId:requiresCVC:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler~1startConsentPayment(withId:requiresCVC:)\/fragments"},{"value":"PaymentSessionHandler","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler\/title"},{"value":[{"kind":"identifier","text":"PaymentSessionHandler"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler\/fragments"},{"value":[{"text":"PaymentSessionHandler","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}