{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PeriodUnit"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"day","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PeriodUnit\/day","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/airwallex\/periodunit\/day"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/periodunit\/day"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"c:@M@Airwallex@E@PeriodUnit@PeriodUnitDay","modules":[{"name":"Airwallex"}],"role":"symbol","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"day"}],"navigatorTitle":[{"text":"PeriodUnitDay","kind":"identifier"}],"title":"PeriodUnit.day","roleHeading":"Case"},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","url":"\/documentation\/airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol","title":"Airwallex","abstract":[],"role":"collection"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PeriodUnit":{"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PeriodUnit","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PeriodUnit"}],"title":"PeriodUnit","url":"\/documentation\/airwallex\/periodunit","kind":"symbol","navigatorTitle":[{"text":"PeriodUnit","kind":"identifier"}],"abstract":[{"text":"Period unit enumeration for billing frequency","type":"text"}],"role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PeriodUnit/day":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PeriodUnit\/day","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"day","kind":"identifier"}],"abstract":[],"type":"topic","title":"PeriodUnit.day","navigatorTitle":[{"text":"PeriodUnitDay","kind":"identifier"}],"url":"\/documentation\/airwallex\/periodunit\/day","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"PeriodUnitDay"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"PeriodUnitDay","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"PeriodUnitDay"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PeriodUnit\/title","value":"PeriodUnit"},{"value":[{"kind":"identifier","text":"PeriodUnit"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PeriodUnit\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"PeriodUnit"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PeriodUnit\/navigatorTitle","op":"replace"},{"value":"PeriodUnitDay","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PeriodUnit~1day\/title","op":"replace"},{"value":[{"text":"PeriodUnitDay","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PeriodUnit~1day\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}