{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confirmPaymentIntent","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"paymentConsent"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentConsent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPaymentConsent","text":"AWXPaymentConsent"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"AWXPaymentConsent Object"}],"type":"paragraph"}],"name":"paymentConsent"}]}],"variants":[{"paths":["\/documentation\/airwallex\/awxcardprovider\/confirmpaymentintent(with:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxcardprovider\/confirmpaymentintent(with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Will be removed in next major version release, use AirwallexPayment.CardProvider instead"}],"type":"paragraph"}],"abstract":[{"type":"text","text":"Confirm the payment intent with payment consent"}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardProvider\/confirmPaymentIntent(with:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"c:objc(cs)AWXCardProvider(im)confirmPaymentIntentWithPaymentConsent:","platforms":[],"title":"confirmPaymentIntent(with:)","role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"kind":"text","text":"- "},{"kind":"identifier","text":"confirmPaymentIntentWithPaymentConsent:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"confirmPaymentIntent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPaymentConsent","text":"AWXPaymentConsent"},{"kind":"text","text":")"}],"modules":[{"name":"Airwallex"}],"symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardProvider"]]},"sections":[],"kind":"symbol","references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardProvider":{"type":"topic","abstract":[{"code":"AWXCardProvider","type":"codeVoice"},{"type":"text","text":" is a provider to handle payment method with card."}],"title":"AWXCardProvider","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardProvider","navigatorTitle":[{"kind":"identifier","text":"AWXCardProvider"}],"url":"\/documentation\/airwallex\/awxcardprovider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXCardProvider"}],"deprecated":true,"kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardProvider/confirmPaymentIntent(with:)":{"type":"topic","navigatorTitle":[{"text":"- ","kind":"text"},{"text":"confirmPaymentIntentWithPaymentConsent:","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxcardprovider\/confirmpaymentintent(with:)","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardProvider\/confirmPaymentIntent(with:)","title":"confirmPaymentIntent(with:)","abstract":[{"type":"text","text":"Confirm the payment intent with payment consent"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confirmPaymentIntent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AWXPaymentConsent","text":"AWXPaymentConsent","kind":"typeIdentifier"},{"text":")","kind":"text"}],"deprecated":true,"role":"symbol","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","role":"collection","title":"Airwallex","type":"topic","url":"\/documentation\/airwallex","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentConsent":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"AWXPaymentConsent"}],"url":"\/documentation\/airwallex\/awxpaymentconsent","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentConsent","title":"AWXPaymentConsent","abstract":[{"code":"AWXPaymentConsent","type":"codeVoice"},{"text":" includes the info of payment consent.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentConsent"}],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":[],"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"confirmPaymentIntentWithPaymentConsent:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"confirmPaymentIntentWithPaymentConsent:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"confirmPaymentIntentWithPaymentConsent:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentConsent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPaymentConsent","text":"AWXPaymentConsent"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"paymentConsent"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"AWXPaymentConsent Object"}],"type":"paragraph"}],"name":"paymentConsent"}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"op":"replace","value":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Will be removed in next major version release, use AirwallexPayment.CardProvider instead"}]}],"path":"\/deprecationSummary"},{"op":"replace","value":"AWXCardProvider","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardProvider\/title"},{"op":"replace","value":[{"text":"AWXCardProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardProvider\/fragments"},{"op":"replace","value":[{"text":"AWXCardProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardProvider\/navigatorTitle"},{"op":"replace","value":"confirmPaymentIntentWithPaymentConsent:","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardProvider~1confirmPaymentIntent(with:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"confirmPaymentIntentWithPaymentConsent:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardProvider~1confirmPaymentIntent(with:)\/fragments"},{"op":"replace","value":"AWXPaymentConsent","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentConsent\/title"},{"op":"replace","value":[{"text":"AWXPaymentConsent","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentConsent\/fragments"},{"op":"replace","value":[{"text":"AWXPaymentConsent","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentConsent\/navigatorTitle"}]}]}