{"variants":[{"paths":["\/documentation\/airwallex\/awxcardprovider\/confirmpaymentintent(with:billing:savecard:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxcardprovider\/confirmpaymentintent(with:billing:savecard:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:objc(cs)AWXCardProvider(im)confirmPaymentIntentWithCard:billing:saveCard:","role":"symbol","title":"confirmPaymentIntent(with:billing:saveCard:)","platforms":[{"unavailable":false,"deprecated":true,"message":"Will be removed in next major version release, use AirwallexPayment.CardProvider instead","beta":false}],"symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"text":"confirmPaymentIntentWithCard:billing:saveCard:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confirmPaymentIntent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AWXCard","text":"AWXCard","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"billing","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AWXPlaceDetails","text":"AWXPlaceDetails","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"saveCard","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"Airwallex"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"confirmPaymentIntent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"card"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCard","kind":"typeIdentifier","text":"AWXCard","preciseIdentifier":"c:objc(cs)AWXCard"},{"kind":"text","text":", "},{"kind":"externalParam","text":"billing"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPlaceDetails","kind":"typeIdentifier","text":"AWXPlaceDetails","preciseIdentifier":"c:objc(cs)AWXPlaceDetails"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"saveCard"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}]}]},{"kind":"parameters","parameters":[{"name":"card","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The card info."}]}]},{"name":"billing","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The billing info."}]}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"abstract":[{"type":"text","text":"Confirm the payment intent with card and billing."}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardProvider"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Will be removed in next major version release, use AirwallexPayment.CardProvider instead"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardProvider\/confirmPaymentIntent(with:billing:saveCard:)"},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCard":{"abstract":[{"type":"codeVoice","code":"AWXCard"},{"type":"text","text":" includes the information of a card."}],"title":"AWXCard","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXCard"}],"url":"\/documentation\/airwallex\/awxcard","navigatorTitle":[{"kind":"identifier","text":"AWXCard"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCard"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardProvider/confirmPaymentIntent(with:billing:saveCard:)":{"title":"confirmPaymentIntent(with:billing:saveCard:)","url":"\/documentation\/airwallex\/awxcardprovider\/confirmpaymentintent(with:billing:savecard:)","role":"symbol","type":"topic","kind":"symbol","abstract":[{"text":"Confirm the payment intent with card and billing.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"confirmPaymentIntentWithCard:billing:saveCard:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"confirmPaymentIntent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWXCard","preciseIdentifier":"c:objc(cs)AWXCard"},{"text":", ","kind":"text"},{"text":"billing","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AWXPlaceDetails","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPlaceDetails"},{"text":"?, ","kind":"text"},{"text":"saveCard","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardProvider\/confirmPaymentIntent(with:billing:saveCard:)","deprecated":true},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardProvider":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWXCardProvider"}],"url":"\/documentation\/airwallex\/awxcardprovider","abstract":[{"type":"codeVoice","code":"AWXCardProvider"},{"type":"text","text":" is a provider to handle payment method with card."}],"kind":"symbol","deprecated":true,"title":"AWXCardProvider","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardProvider","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXCardProvider"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPlaceDetails":{"abstract":[{"code":"AWXPlaceDetails","type":"codeVoice"},{"type":"text","text":" includes the information of a billing address."}],"url":"\/documentation\/airwallex\/awxplacedetails","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPlaceDetails","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPlaceDetails","navigatorTitle":[{"kind":"identifier","text":"AWXPlaceDetails"}],"kind":"symbol","title":"AWXPlaceDetails"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","type":"topic","url":"\/documentation\/airwallex","kind":"symbol","abstract":[],"title":"Airwallex"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[{"beta":false,"deprecated":true,"unavailable":false}]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"confirmPaymentIntentWithCard:billing:saveCard:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"confirmPaymentIntentWithCard:billing:saveCard:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"confirmPaymentIntentWithCard:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCard","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXCard","text":"AWXCard"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"card"},{"kind":"text","text":" "},{"kind":"identifier","text":"billing:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPlaceDetails","text":"AWXPlaceDetails","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPlaceDetails"},{"text":" *) ","kind":"text"},{"text":"billing","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"saveCard:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"saveCard","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"card","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The card info."}]}]},{"name":"billing","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The billing info."}]}]}]}},{"op":"replace","path":"\/deprecationSummary","value":[{"type":"paragraph","inlineContent":[{"text":"Will be removed in next major version release, use AirwallexPayment.CardProvider instead","type":"text"}]}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCard\/title","value":"AWXCard"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCard\/fragments","value":[{"text":"AWXCard","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCard\/navigatorTitle","value":[{"text":"AWXCard","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardProvider~1confirmPaymentIntent(with:billing:saveCard:)\/title","value":"confirmPaymentIntentWithCard:billing:saveCard:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardProvider~1confirmPaymentIntent(with:billing:saveCard:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"confirmPaymentIntentWithCard:billing:saveCard:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardProvider\/title","value":"AWXCardProvider"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardProvider\/fragments","value":[{"text":"AWXCardProvider","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardProvider\/navigatorTitle","value":[{"text":"AWXCardProvider","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPlaceDetails\/title","value":"AWXPlaceDetails"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPlaceDetails\/fragments","value":[{"kind":"identifier","text":"AWXPlaceDetails"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPlaceDetails\/navigatorTitle","value":[{"kind":"identifier","text":"AWXPlaceDetails"}]}]}]}