{"metadata":{"modules":[{"name":"Airwallex"}],"symbolKind":"property","role":"symbol","title":"paymentSchedule","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentSchedule"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@Airwallex@objc(cs)PaymentSchedule","text":"PaymentSchedule"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"paymentSchedule"}],"roleHeading":"Instance Property","externalID":"c:@M@Airwallex@objc(cs)TermsOfUse(py)paymentSchedule"},"variants":[{"paths":["\/documentation\/airwallex\/termsofuse\/paymentschedule"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/termsofuse\/paymentschedule"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/TermsOfUse\/paymentSchedule","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"Payment schedule configuration"},{"type":"text","text":" "},{"type":"text","text":"Required if merchant_trigger_reason = scheduled"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentSchedule","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PaymentSchedule","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSchedule","preciseIdentifier":"c:@M@Airwallex@objc(cs)PaymentSchedule"},{"text":"?","kind":"text"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/TermsOfUse"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/TermsOfUse":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TermsOfUse","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/TermsOfUse","title":"TermsOfUse","role":"symbol","navigatorTitle":[{"text":"TermsOfUse","kind":"identifier"}],"abstract":[{"type":"text","text":"Terms to specify how this Payment Consent will be used"}],"kind":"symbol","url":"\/documentation\/airwallex\/termsofuse"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","url":"\/documentation\/airwallex","role":"collection","kind":"symbol","abstract":[],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentSchedule":{"type":"topic","navigatorTitle":[{"text":"PaymentSchedule","kind":"identifier"}],"abstract":[{"text":"Payment schedule configuration","type":"text"}],"url":"\/documentation\/airwallex\/paymentschedule","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSchedule","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PaymentSchedule","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"PaymentSchedule"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/TermsOfUse/paymentSchedule":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentSchedule"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PaymentSchedule","preciseIdentifier":"c:@M@Airwallex@objc(cs)PaymentSchedule"},{"kind":"text","text":"?"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/TermsOfUse\/paymentSchedule","abstract":[{"type":"text","text":"Payment schedule configuration"},{"type":"text","text":" "},{"type":"text","text":"Required if merchant_trigger_reason = scheduled"}],"kind":"symbol","url":"\/documentation\/airwallex\/termsofuse\/paymentschedule","navigatorTitle":[{"kind":"identifier","text":"paymentSchedule"}],"type":"topic","title":"paymentSchedule"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"paymentSchedule"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"paymentSchedule","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSchedule","text":"PaymentSchedule","kind":"typeIdentifier","preciseIdentifier":"c:@M@Airwallex@objc(cs)PaymentSchedule"},{"text":" * ","kind":"text"},{"text":"paymentSchedule","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1TermsOfUse\/title","value":"TermsOfUse","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1TermsOfUse\/fragments","value":[{"kind":"identifier","text":"TermsOfUse"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1TermsOfUse\/navigatorTitle","value":[{"text":"TermsOfUse","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSchedule\/title","value":"PaymentSchedule","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSchedule\/fragments","value":[{"text":"PaymentSchedule","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSchedule\/navigatorTitle","value":[{"kind":"identifier","text":"PaymentSchedule"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1TermsOfUse~1paymentSchedule\/title","value":"paymentSchedule","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1TermsOfUse~1paymentSchedule\/fragments","value":[{"kind":"identifier","text":"paymentSchedule"}],"op":"replace"}]}]}