{"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localizedDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"Error.localizedDescription","type":"codeVoice"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession\/ValidationError"]]},"metadata":{"externalID":"s:s5ErrorP10FoundationE20localizedDescriptionSSvp::SYNTHESIZED::s:So10AWXSessionC9AirwallexE15ValidationErrorO","role":"symbol","modules":[{"name":"Airwallex","relatedModules":["Swift"]}],"extendedModule":"Swift","symbolKind":"property","platforms":[{"introducedAt":"8.0","beta":false,"deprecated":false,"name":"iOS","unavailable":false},{"introducedAt":"8.0","beta":false,"deprecated":false,"name":"iPadOS","unavailable":false},{"introducedAt":"8.0","beta":false,"deprecated":false,"name":"Mac Catalyst","unavailable":false},{"introducedAt":"10.10","beta":false,"deprecated":false,"name":"macOS","unavailable":false},{"introducedAt":"9.0","beta":false,"deprecated":false,"name":"tvOS","unavailable":false},{"introducedAt":"2.0","beta":false,"deprecated":false,"name":"watchOS","unavailable":false}],"title":"localizedDescription","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localizedDescription","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession\/ValidationError\/localizedDescription"},"variants":[{"paths":["\/documentation\/airwallex\/awxsession\/validationerror\/localizeddescription"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSession/ValidationError":{"title":"AWXSession.ValidationError","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ValidationError"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession\/ValidationError","kind":"symbol","url":"\/documentation\/airwallex\/awxsession\/validationerror","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ValidationError"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSession/ValidationError/localizedDescription":{"kind":"symbol","type":"topic","abstract":[],"role":"symbol","url":"\/documentation\/airwallex\/awxsession\/validationerror\/localizeddescription","title":"localizedDescription","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession\/ValidationError\/localizedDescription","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizedDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSession":{"url":"\/documentation\/airwallex\/awxsession","navigatorTitle":[{"kind":"identifier","text":"AWXSession"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXSession"}],"abstract":[{"type":"codeVoice","code":"AWXSession"},{"type":"text","text":" is the base session."}],"title":"AWXSession","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","url":"\/documentation\/airwallex","title":"Airwallex","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/title","op":"replace","value":"AWXSession"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/fragments","op":"replace","value":[{"text":"AWXSession","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/navigatorTitle","op":"replace","value":[{"text":"AWXSession","kind":"identifier"}]}]}]}