{"relationshipsSections":[{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.Airwallex\/s15BitwiseCopyableP","doc:\/\/org.cocoapods.Airwallex\/SQ","doc:\/\/org.cocoapods.Airwallex\/SH","doc:\/\/org.cocoapods.Airwallex\/SY","doc:\/\/org.cocoapods.Airwallex\/s8SendableP","doc:\/\/org.cocoapods.Airwallex\/s16SendableMetatypeP"],"type":"conformsTo"}],"sections":[],"metadata":{"externalID":"c:@E@AWXFormType","role":"symbol","roleHeading":"Enumeration","symbolKind":"enum","title":"AWXFormType","modules":[{"name":"Airwallex"}],"navigatorTitle":[{"kind":"identifier","text":"AWXFormType"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXFormType"}]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXFormType\/button","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXFormType\/listCell","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXFormType\/text"],"generated":true,"anchor":"Enumeration-Cases"},{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXFormType\/init(rawValue:)"],"generated":true,"anchor":"Initializers"},{"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXFormType\/Equatable-Implementations","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXFormType\/RawRepresentable-Implementations"],"generated":true,"anchor":"Default-Implementations"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXFormType","kind":"identifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxformtype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxformtype"]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXFormType"},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXFormType/listCell":{"title":"AWXFormType.listCell","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"listCell"}],"navigatorTitle":[{"kind":"identifier","text":"AWXFormTypeListCell"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXFormType\/listCell","type":"topic","url":"\/documentation\/airwallex\/awxformtype\/listcell","role":"symbol","kind":"symbol","abstract":[]},"doc://org.cocoapods.Airwallex/s16SendableMetatypeP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s16SendableMetatypeP","title":"Swift.SendableMetatype","type":"unresolvable"},"doc://org.cocoapods.Airwallex/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SY"},"doc://org.cocoapods.Airwallex/s8SendableP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://org.cocoapods.Airwallex/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SQ"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXFormType/init(rawValue:)":{"title":"init(rawValue:)","kind":"symbol","role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXFormType\/init(rawValue:)","type":"topic","url":"\/documentation\/airwallex\/awxformtype\/init(rawvalue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXFormType/Equatable-Implementations":{"title":"Equatable Implementations","role":"collectionGroup","kind":"article","url":"\/documentation\/airwallex\/awxformtype\/equatable-implementations","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXFormType\/Equatable-Implementations"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXFormType/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","role":"collectionGroup","kind":"article","url":"\/documentation\/airwallex\/awxformtype\/rawrepresentable-implementations","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXFormType\/RawRepresentable-Implementations"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXFormType/button":{"title":"AWXFormType.button","kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"button","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"AWXFormTypeButton","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXFormType\/button","url":"\/documentation\/airwallex\/awxformtype\/button","role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","role":"collection","url":"\/documentation\/airwallex","kind":"symbol","title":"Airwallex","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXFormType/text":{"role":"symbol","navigatorTitle":[{"text":"AWXFormTypeText","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXFormType\/text","title":"AWXFormType.text","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"text","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxformtype\/text"},"doc://org.cocoapods.Airwallex/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SH"},"doc://org.cocoapods.Airwallex/s15BitwiseCopyableP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s15BitwiseCopyableP","title":"Swift.BitwiseCopyable","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXFormType":{"abstract":[],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXFormType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXFormType","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxformtype","title":"AWXFormType","navigatorTitle":[{"text":"AWXFormType","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"value":"AWXFormType","path":"\/metadata\/title","op":"replace"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"AWXFormType","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AWXFormType"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXFormType\/button","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXFormType\/listCell","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXFormType\/text"],"generated":true}],"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXFormType","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXFormType~1listCell\/title","value":"AWXFormTypeListCell"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXFormType~1listCell\/fragments","value":[{"kind":"identifier","text":"AWXFormTypeListCell"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXFormType~1button\/title","value":"AWXFormTypeButton"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXFormType~1button\/fragments","value":[{"kind":"identifier","text":"AWXFormTypeButton"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXFormType~1text\/title","value":"AWXFormTypeText"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXFormType~1text\/fragments","value":[{"text":"AWXFormTypeText","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXFormType\/title","value":"AWXFormType"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXFormType\/fragments","value":[{"kind":"identifier","text":"AWXFormType"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXFormType\/navigatorTitle","value":[{"text":"AWXFormType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}