{"sections":[],"metadata":{"roleHeading":"API Collection","title":"Equatable Implementations","modules":[{"name":"Airwallex"}],"role":"collectionGroup"},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand\/Equatable-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Operators","generated":true,"anchor":"Operators","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand\/!=(_:_:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxcardbrand\/equatable-implementations"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"article","references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardBrand":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXCardBrand"}],"url":"\/documentation\/airwallex\/awxcardbrand","title":"AWXCardBrand","kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWXCardBrand"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/airwallex","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardBrand/!=(_:_:)":{"abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/airwallex\/awxcardbrand\/!=(_:_:)","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand\/!=(_:_:)","title":"!=(_:_:)"}},"variantOverrides":[{"patch":[{"value":"AWXCardBrand","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardBrand\/title"},{"value":[{"text":"AWXCardBrand","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardBrand\/fragments"},{"value":[{"kind":"identifier","text":"AWXCardBrand"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardBrand\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}