{"variants":[{"paths":["\/documentation\/airwallex\/awxcardbrand\/mastercard"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxcardbrand\/mastercard"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"extendedModule":"Airwallex","externalID":"c:@AWXCardBrandMastercard","role":"symbol","symbolKind":"property","title":"mastercard","navigatorTitle":[{"kind":"identifier","text":"AWXCardBrandMastercard"}],"modules":[{"name":"Airwallex"}],"roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"mastercard"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:AWXConstants.h@T@AWXCardBrand","text":"AWXCardBrand"}]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand\/mastercard","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mastercard","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand","preciseIdentifier":"c:AWXConstants.h@T@AWXCardBrand","text":"AWXCardBrand","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand"]]},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardBrand/mastercard":{"abstract":[],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand\/mastercard","title":"mastercard","navigatorTitle":[{"text":"AWXCardBrandMastercard","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxcardbrand\/mastercard","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mastercard","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"AWXCardBrand","preciseIdentifier":"c:AWXConstants.h@T@AWXCardBrand"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"abstract":[],"kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","url":"\/documentation\/airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardBrand":{"kind":"symbol","abstract":[],"url":"\/documentation\/airwallex\/awxcardbrand","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXCardBrand"}],"navigatorTitle":[{"kind":"identifier","text":"AWXCardBrand"}],"title":"AWXCardBrand","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"AWXCardBrandMastercard"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AWXCardBrandMastercard"}]},{"op":"replace","path":"\/hierarchy","value":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]}},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand","text":"AWXCardBrand","preciseIdentifier":"c:AWXConstants.h@T@AWXCardBrand"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXCardBrandMastercard"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardBrand~1mastercard\/title","value":"AWXCardBrandMastercard"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardBrand~1mastercard\/fragments","value":[{"kind":"identifier","text":"AWXCardBrandMastercard"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardBrand\/title","value":"AWXCardBrand"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardBrand\/fragments","value":[{"kind":"identifier","text":"AWXCardBrand"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardBrand\/navigatorTitle","value":[{"kind":"identifier","text":"AWXCardBrand"}]}]}]}