{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"brandType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@AWXBrandType","text":"AWXBrandType","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrandType","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"metadata":{"roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"Airwallex"}],"extendedModule":"Airwallex","externalID":"s:So12AWXCardBranda9AirwallexE9brandTypeSo08AWXBrandE0Vvp","role":"symbol","title":"brandType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"brandType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@AWXBrandType","text":"AWXBrandType"}]},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand\/brandType","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxcardbrand\/brandtype"]}],"sections":[],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardBrand":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXCardBrand"}],"navigatorTitle":[{"kind":"identifier","text":"AWXCardBrand"}],"title":"AWXCardBrand","kind":"symbol","type":"topic","url":"\/documentation\/airwallex\/awxcardbrand","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXBrandType":{"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrandType","title":"AWXBrandType","navigatorTitle":[{"kind":"identifier","text":"AWXBrandType"}],"role":"symbol","url":"\/documentation\/airwallex\/awxbrandtype","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXBrandType"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","kind":"symbol","url":"\/documentation\/airwallex","abstract":[],"title":"Airwallex","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardBrand/brandType":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"brandType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@AWXBrandType","text":"AWXBrandType"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand\/brandType","title":"brandType","abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/airwallex\/awxcardbrand\/brandtype"}},"variantOverrides":[{"patch":[{"value":"AWXCardBrand","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardBrand\/title"},{"value":[{"kind":"identifier","text":"AWXCardBrand"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardBrand\/fragments"},{"value":[{"kind":"identifier","text":"AWXCardBrand"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardBrand\/navigatorTitle"},{"value":"AWXBrandType","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrandType\/title"},{"value":[{"text":"AWXBrandType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrandType\/fragments"},{"value":[{"kind":"identifier","text":"AWXBrandType"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrandType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}