{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"dinersClub"},{"kind":"text","text":": "},{"preciseIdentifier":"c:AWXConstants.h@T@AWXCardBrand","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand","text":"AWXCardBrand"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand\/dinersClub","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","variants":[{"paths":["\/documentation\/airwallex\/awxcardbrand\/dinersclub"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxcardbrand\/dinersclub"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand"]]},"metadata":{"navigatorTitle":[{"text":"AWXCardBrandDinersClub","kind":"identifier"}],"modules":[{"name":"Airwallex"}],"title":"dinersClub","roleHeading":"Type Property","role":"symbol","externalID":"c:@AWXCardBrandDinersClub","extendedModule":"Airwallex","symbolKind":"property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dinersClub","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:AWXConstants.h@T@AWXCardBrand","text":"AWXCardBrand","kind":"typeIdentifier"}]},"sections":[],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardBrand/dinersClub":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand\/dinersClub","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"dinersClub"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:AWXConstants.h@T@AWXCardBrand","text":"AWXCardBrand"}],"title":"dinersClub","kind":"symbol","url":"\/documentation\/airwallex\/awxcardbrand\/dinersclub","navigatorTitle":[{"text":"AWXCardBrandDinersClub","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardBrand":{"role":"symbol","title":"AWXCardBrand","navigatorTitle":[{"kind":"identifier","text":"AWXCardBrand"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXCardBrand"}],"url":"\/documentation\/airwallex\/awxcardbrand","abstract":[],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","role":"collection","title":"Airwallex","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"AWXCardBrandDinersClub"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"AWXCardBrandDinersClub","kind":"identifier"}]},{"op":"replace","path":"\/hierarchy","value":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]}},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"preciseIdentifier":"c:AWXConstants.h@T@AWXCardBrand","kind":"typeIdentifier","text":"AWXCardBrand","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXCardBrandDinersClub"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardBrand~1dinersClub\/title","value":"AWXCardBrandDinersClub"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardBrand~1dinersClub\/fragments","value":[{"text":"AWXCardBrandDinersClub","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardBrand\/title","value":"AWXCardBrand"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardBrand\/fragments","value":[{"text":"AWXCardBrand","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardBrand\/navigatorTitle","value":[{"kind":"identifier","text":"AWXCardBrand"}]}]}]}