{"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringWithIntentSession\/merchantTriggerReason","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"merchantTriggerReason","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@AirwallexMerchantTriggerReason","text":"AirwallexMerchantTriggerReason","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexMerchantTriggerReason"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxrecurringwithintentsession\/merchanttriggerreason"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxrecurringwithintentsession\/merchanttriggerreason"]}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Will be removed in next major version release, use AirwallexPayment.Session instead","type":"text"}]}],"sections":[],"metadata":{"roleHeading":"Instance Property","role":"symbol","modules":[{"name":"Airwallex"}],"platforms":[{"beta":false,"deprecated":true,"unavailable":false,"message":"Will be removed in next major version release, use AirwallexPayment.Session instead"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"merchantTriggerReason","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@AirwallexMerchantTriggerReason","text":"AirwallexMerchantTriggerReason","kind":"typeIdentifier"}],"title":"merchantTriggerReason","externalID":"c:objc(cs)AWXRecurringWithIntentSession(py)merchantTriggerReason","navigatorTitle":[{"text":"merchantTriggerReason","kind":"identifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringWithIntentSession"]]},"abstract":[{"type":"text","text":"Merchant trigger reason"}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","kind":"symbol","url":"\/documentation\/airwallex","abstract":[],"title":"Airwallex","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRecurringWithIntentSession/merchantTriggerReason":{"type":"topic","abstract":[{"type":"text","text":"Merchant trigger reason"}],"kind":"symbol","deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"merchantTriggerReason"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"merchantTriggerReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AirwallexMerchantTriggerReason","preciseIdentifier":"c:@E@AirwallexMerchantTriggerReason"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringWithIntentSession\/merchantTriggerReason","role":"symbol","title":"merchantTriggerReason","url":"\/documentation\/airwallex\/awxrecurringwithintentsession\/merchanttriggerreason"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRecurringWithIntentSession":{"deprecated":true,"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXRecurringWithIntentSession","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringWithIntentSession","title":"AWXRecurringWithIntentSession","navigatorTitle":[{"text":"AWXRecurringWithIntentSession","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxrecurringwithintentsession","abstract":[{"code":"AWXRecurringWithIntentSession","type":"codeVoice"},{"type":"text","text":" is the session used for recurring with intent."}],"kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexMerchantTriggerReason":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexMerchantTriggerReason","navigatorTitle":[{"kind":"identifier","text":"AirwallexMerchantTriggerReason"}],"kind":"symbol","url":"\/documentation\/airwallex\/airwallexmerchanttriggerreason","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AirwallexMerchantTriggerReason"}],"abstract":[],"title":"AirwallexMerchantTriggerReason","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"replace","value":[{"deprecated":true,"unavailable":false,"beta":false}]},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"merchantTriggerReason"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"merchantTriggerReason","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"AirwallexMerchantTriggerReason","kind":"typeIdentifier","preciseIdentifier":"c:@E@AirwallexMerchantTriggerReason","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexMerchantTriggerReason"},{"text":" ","kind":"text"},{"text":"merchantTriggerReason","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/deprecationSummary","op":"replace","value":[{"type":"paragraph","inlineContent":[{"text":"Will be removed in next major version release, use AirwallexPayment.Session instead","type":"text"}]}]},{"value":"merchantTriggerReason","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRecurringWithIntentSession~1merchantTriggerReason\/title","op":"replace"},{"value":[{"text":"merchantTriggerReason","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRecurringWithIntentSession~1merchantTriggerReason\/fragments","op":"replace"},{"value":"AWXRecurringWithIntentSession","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRecurringWithIntentSession\/title","op":"replace"},{"value":[{"text":"AWXRecurringWithIntentSession","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRecurringWithIntentSession\/fragments","op":"replace"},{"value":[{"text":"AWXRecurringWithIntentSession","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRecurringWithIntentSession\/navigatorTitle","op":"replace"},{"value":"AirwallexMerchantTriggerReason","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexMerchantTriggerReason\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AirwallexMerchantTriggerReason"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexMerchantTriggerReason\/fragments","op":"replace"},{"value":[{"text":"AirwallexMerchantTriggerReason","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexMerchantTriggerReason\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}