{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"session","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AWXSession","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession","text":"AWXSession","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"viewController","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"paymentResultDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(pl)AWXPaymentResultDelegate","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentResultDelegate","text":"AWXPaymentResultDelegate","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"methodType","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AWXPaymentMethodType","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethodType","text":"AWXPaymentMethodType","kind":"typeIdentifier"},{"text":"? = nil)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"session","content":[{"inlineContent":[{"type":"text","text":"The payment session containing relevant transaction details."}],"type":"paragraph"}]},{"name":"viewController","content":[{"inlineContent":[{"type":"text","text":"The view controller that initiates the payment process."}],"type":"paragraph"}]},{"name":"paymentResultDelegate","content":[{"type":"paragraph","inlineContent":[{"text":"Delegate which conforms to ","type":"text"},{"code":"AWXPaymentResultDelegate","type":"codeVoice"},{"text":" for handling payment results","type":"text"}]}]},{"name":"methodType","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The payment method type returned from the server (optional)."}]}]}],"kind":"parameters"}],"metadata":{"role":"symbol","roleHeading":"Initializer","navigatorTitle":[{"text":"initWithSession:viewController:paymentResultDelegate:methodType:","kind":"identifier"}],"externalID":"c:@M@Airwallex@objc(cs)PaymentSessionHandler(im)initWithSession:viewController:paymentResultDelegate:methodType:","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"session"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AWXSession","kind":"typeIdentifier","text":"AWXSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"viewController"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"paymentResultDelegate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(pl)AWXPaymentResultDelegate","kind":"typeIdentifier","text":"AWXPaymentResultDelegate"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"methodType"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AWXPaymentMethodType","kind":"typeIdentifier","text":"AWXPaymentMethodType"},{"kind":"text","text":"?)"}],"title":"init(session:viewController:paymentResultDelegate:methodType:)","symbolKind":"init","modules":[{"name":"Airwallex"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler\/init(session:viewController:paymentResultDelegate:methodType:)","interfaceLanguage":"swift"},"abstract":[{"text":"Initializes a ","type":"text"},{"code":"PaymentSessionHandler","type":"codeVoice"},{"text":" with a payment session and the view controller from which the payment is initiated.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/paymentsessionhandler\/init(session:viewcontroller:paymentresultdelegate:methodtype:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/paymentsessionhandler\/init(session:viewcontroller:paymentresultdelegate:methodtype:)"]}],"kind":"symbol","references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentSessionHandler":{"url":"\/documentation\/airwallex\/paymentsessionhandler","abstract":[],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PaymentSessionHandler","kind":"identifier"}],"navigatorTitle":[{"text":"PaymentSessionHandler","kind":"identifier"}],"title":"PaymentSessionHandler","role":"symbol","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSession":{"kind":"symbol","abstract":[{"code":"AWXSession","type":"codeVoice"},{"text":" is the base session.","type":"text"}],"title":"AWXSession","url":"\/documentation\/airwallex\/awxsession","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXSession","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession","role":"symbol","navigatorTitle":[{"text":"AWXSession","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentResultDelegate":{"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentResultDelegate"}],"title":"AWXPaymentResultDelegate","url":"\/documentation\/airwallex\/awxpaymentresultdelegate","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWXPaymentResultDelegate"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentResultDelegate"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","role":"collection","title":"Airwallex","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentMethodType":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPaymentMethodType","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethodType","role":"symbol","type":"topic","url":"\/documentation\/airwallex\/awxpaymentmethodtype","navigatorTitle":[{"text":"AWXPaymentMethodType","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"AWXPaymentMethodType"},{"text":" includes the information of a payment method.","type":"text"}],"title":"AWXPaymentMethodType"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentSessionHandler/init(session:viewController:paymentResultDelegate:methodType:)":{"url":"\/documentation\/airwallex\/paymentsessionhandler\/init(session:viewcontroller:paymentresultdelegate:methodtype:)","navigatorTitle":[{"kind":"identifier","text":"initWithSession:viewController:paymentResultDelegate:methodType:"}],"kind":"symbol","title":"init(session:viewController:paymentResultDelegate:methodType:)","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler\/init(session:viewController:paymentResultDelegate:methodType:)","type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"session"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWXSession","preciseIdentifier":"c:objc(cs)AWXSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"viewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"paymentResultDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWXPaymentResultDelegate","preciseIdentifier":"c:objc(pl)AWXPaymentResultDelegate"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"methodType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWXPaymentMethodType","preciseIdentifier":"c:objc(cs)AWXPaymentMethodType"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Initializes a "},{"code":"PaymentSessionHandler","type":"codeVoice"},{"type":"text","text":" with a payment session and the view controller from which the payment is initiated."}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"initWithSession:viewController:paymentResultDelegate:methodType:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithSession:viewController:paymentResultDelegate:methodType:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithSession:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)AWXSession","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession","kind":"typeIdentifier","text":"AWXSession"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"session"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewController:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentResultDelegate:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qoobjc(pl)AWXPaymentResultDelegate","kind":"typeIdentifier","text":"id<AWXPaymentResultDelegate>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"paymentResultDelegate"},{"kind":"text","text":" "},{"kind":"identifier","text":"methodType:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)AWXPaymentMethodType","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethodType","kind":"typeIdentifier","text":"AWXPaymentMethodType"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"methodType"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The payment session containing relevant transaction details."}],"type":"paragraph"}],"name":"session"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The view controller that initiates the payment process.","type":"text"}]}],"name":"viewController"},{"content":[{"inlineContent":[{"type":"text","text":"Delegate which conforms to "},{"type":"codeVoice","code":"AWXPaymentResultDelegate"},{"type":"text","text":" for handling payment results"}],"type":"paragraph"}],"name":"paymentResultDelegate"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The payment method type returned from the server (optional)."}]}],"name":"methodType"}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"PaymentSessionHandler","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler\/title"},{"op":"replace","value":[{"text":"PaymentSessionHandler","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"PaymentSessionHandler"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler\/navigatorTitle"},{"op":"replace","value":"AWXSession","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AWXSession"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AWXSession"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/navigatorTitle"},{"op":"replace","value":"AWXPaymentResultDelegate","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentResultDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AWXPaymentResultDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentResultDelegate\/fragments"},{"op":"replace","value":[{"text":"AWXPaymentResultDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentResultDelegate\/navigatorTitle"},{"op":"replace","value":"AWXPaymentMethodType","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethodType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AWXPaymentMethodType"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethodType\/fragments"},{"op":"replace","value":[{"text":"AWXPaymentMethodType","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethodType\/navigatorTitle"},{"op":"replace","value":"initWithSession:viewController:paymentResultDelegate:methodType:","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler~1init(session:viewController:paymentResultDelegate:methodType:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSession:viewController:paymentResultDelegate:methodType:"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler~1init(session:viewController:paymentResultDelegate:methodType:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}