{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/paymentsessionhandler\/provider(_:didcompletewith:error:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/paymentsessionhandler\/provider(_:didcompletewith:error:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler\/provider(_:didCompleteWith:error:)"},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"AWXProviderDelegate.provider(_:didCompleteWith:error:)"},{"text":".","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"provider","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"provider","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AWXDefaultProvider","text":"AWXDefaultProvider","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didCompleteWith","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"status"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexPaymentStatus","kind":"typeIdentifier","preciseIdentifier":"c:@E@AirwallexPaymentStatus","text":"AirwallexPaymentStatus"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": ("},{"kind":"keyword","text":"any"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler"]]},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"provider","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AWXDefaultProvider","preciseIdentifier":"c:objc(cs)AWXDefaultProvider","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didCompleteWith","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AirwallexPaymentStatus","preciseIdentifier":"c:@E@AirwallexPaymentStatus","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"kind":"text","text":": ("},{"kind":"keyword","text":"any"},{"text":" ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?)","kind":"text"}],"role":"symbol","title":"provider(_:didCompleteWith:error:)","modules":[{"name":"Airwallex"}],"roleHeading":"Instance Method","externalID":"c:@CM@Airwallex@objc(cs)PaymentSessionHandler(im)provider:didCompleteWithStatus:error:","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"provider:didCompleteWithStatus:error:"}],"extendedModule":"Airwallex"},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentSessionHandler":{"title":"PaymentSessionHandler","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PaymentSessionHandler","kind":"identifier"}],"url":"\/documentation\/airwallex\/paymentsessionhandler","role":"symbol","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"PaymentSessionHandler","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXDefaultProvider":{"title":"AWXDefaultProvider","kind":"symbol","url":"\/documentation\/airwallex\/awxdefaultprovider","navigatorTitle":[{"kind":"identifier","text":"AWXDefaultProvider"}],"abstract":[{"text":"A provider which handles payment business.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXDefaultProvider","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexPaymentStatus":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AirwallexPaymentStatus","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"AirwallexPaymentStatus","kind":"identifier"}],"title":"AirwallexPaymentStatus","url":"\/documentation\/airwallex\/airwallexpaymentstatus","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexPaymentStatus","type":"topic","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","kind":"symbol","url":"\/documentation\/airwallex","abstract":[],"title":"Airwallex","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentSessionHandler/provider(_:didCompleteWith:error:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"provider","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AWXDefaultProvider","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXDefaultProvider"},{"text":", ","kind":"text"},{"text":"didCompleteWith","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AirwallexPaymentStatus","kind":"typeIdentifier","preciseIdentifier":"c:@E@AirwallexPaymentStatus"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?)","kind":"text"}],"navigatorTitle":[{"text":"provider:didCompleteWithStatus:error:","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler\/provider(_:didCompleteWith:error:)","abstract":[],"kind":"symbol","url":"\/documentation\/airwallex\/paymentsessionhandler\/provider(_:didcompletewith:error:)","title":"provider(_:didCompleteWith:error:)","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"provider:didCompleteWithStatus:error:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"provider:didCompleteWithStatus:error:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"provider:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXDefaultProvider","text":"AWXDefaultProvider","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"provider"},{"kind":"text","text":" "},{"kind":"identifier","text":"didCompleteWithStatus:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@AirwallexPaymentStatus","text":"AirwallexPaymentStatus","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexPaymentStatus"},{"kind":"text","text":") "},{"kind":"internalParam","text":"status"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","value":"PaymentSessionHandler","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler\/fragments","op":"replace","value":[{"text":"PaymentSessionHandler","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler\/navigatorTitle","op":"replace","value":[{"text":"PaymentSessionHandler","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider\/title","op":"replace","value":"AWXDefaultProvider"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider\/fragments","op":"replace","value":[{"text":"AWXDefaultProvider","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider\/navigatorTitle","op":"replace","value":[{"text":"AWXDefaultProvider","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexPaymentStatus\/title","op":"replace","value":"AirwallexPaymentStatus"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexPaymentStatus\/fragments","op":"replace","value":[{"kind":"identifier","text":"AirwallexPaymentStatus"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexPaymentStatus\/navigatorTitle","op":"replace","value":[{"text":"AirwallexPaymentStatus","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler~1provider(_:didCompleteWith:error:)\/title","op":"replace","value":"provider:didCompleteWithStatus:error:"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler~1provider(_:didCompleteWith:error:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"provider:didCompleteWithStatus:error:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}