{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"startRedirectPayment(with:additionalInfo:)","roleHeading":"Instance Method","extendedModule":"Airwallex","symbolKind":"method","role":"symbol","modules":[{"name":"Airwallex"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startRedirectPayment","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"additionalInfo","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]?)","kind":"text"}],"externalID":"c:@CM@Airwallex@objc(cs)PaymentSessionHandler(im)startRedirectPaymentWith:additionalInfo:","navigatorTitle":[{"kind":"identifier","text":"startRedirectPaymentWith:additionalInfo:"}]},"abstract":[{"text":"Initiates a schema-based payment transaction.","type":"text"},{"text":" ","type":"text"},{"text":"This method processes a payment with schema-based payment methods such as digital wallets or bank transfers.","type":"text"},{"text":" ","type":"text"},{"text":"You should collect all information from your user before calling this api","type":"text"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startRedirectPayment"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"additionalInfo"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]?)"}]}]},{"kind":"parameters","parameters":[{"name":"name","content":[{"inlineContent":[{"type":"text","text":"The name of the payment method, as defined by the payment platform."}],"type":"paragraph"}]},{"name":"additionalInfo","content":[{"type":"paragraph","inlineContent":[{"text":"A dictionary containing any additional data required for processing the payment.","type":"text"}]}]}]}],"variants":[{"paths":["\/documentation\/airwallex\/paymentsessionhandler\/startredirectpayment(with:additionalinfo:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/paymentsessionhandler\/startredirectpayment(with:additionalinfo:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler\/startRedirectPayment(with:additionalInfo:)"},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentSessionHandler":{"url":"\/documentation\/airwallex\/paymentsessionhandler","abstract":[],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PaymentSessionHandler","kind":"identifier"}],"navigatorTitle":[{"text":"PaymentSessionHandler","kind":"identifier"}],"title":"PaymentSessionHandler","role":"symbol","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentSessionHandler/startRedirectPayment(with:additionalInfo:)":{"url":"\/documentation\/airwallex\/paymentsessionhandler\/startredirectpayment(with:additionalinfo:)","title":"startRedirectPayment(with:additionalInfo:)","type":"topic","navigatorTitle":[{"text":"startRedirectPaymentWith:additionalInfo:","kind":"identifier"}],"abstract":[{"text":"Initiates a schema-based payment transaction.","type":"text"},{"text":" ","type":"text"},{"text":"This method processes a payment with schema-based payment methods such as digital wallets or bank transfers.","type":"text"},{"text":" ","type":"text"},{"text":"You should collect all information from your user before calling this api","type":"text"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSessionHandler\/startRedirectPayment(with:additionalInfo:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startRedirectPayment","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"additionalInfo","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"]?)","kind":"text"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","role":"collection","title":"Airwallex","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"startRedirectPaymentWith:additionalInfo:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"startRedirectPaymentWith:additionalInfo:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"startRedirectPaymentWith:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"name","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"additionalInfo:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSDictionary<NSString *,NSString *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"text":" *) ","kind":"text"},{"text":"additionalInfo","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"parameters":[{"content":[{"inlineContent":[{"text":"The name of the payment method, as defined by the payment platform.","type":"text"}],"type":"paragraph"}],"name":"name"},{"content":[{"inlineContent":[{"type":"text","text":"A dictionary containing any additional data required for processing the payment."}],"type":"paragraph"}],"name":"additionalInfo"}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"PaymentSessionHandler","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler\/title","op":"replace"},{"value":[{"kind":"identifier","text":"PaymentSessionHandler"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler\/fragments","op":"replace"},{"value":[{"text":"PaymentSessionHandler","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler\/navigatorTitle","op":"replace"},{"value":"startRedirectPaymentWith:additionalInfo:","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler~1startRedirectPayment(with:additionalInfo:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startRedirectPaymentWith:additionalInfo:"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSessionHandler~1startRedirectPayment(with:additionalInfo:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}