{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentIntentResponse\/order"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentIntentResponse"]]},"variants":[{"paths":["\/documentation\/airwallex\/awxgetpaymentintentresponse\/order"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxgetpaymentintentresponse\/order"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Order data.","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"order"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"order","kind":"identifier"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"externalID":"c:objc(cs)AWXGetPaymentIntentResponse(py)order","symbolKind":"property","modules":[{"name":"Airwallex"}],"title":"order","roleHeading":"Instance Property","navigatorTitle":[{"text":"order","kind":"identifier"}]},"kind":"symbol","references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentIntentResponse/order":{"url":"\/documentation\/airwallex\/awxgetpaymentintentresponse\/order","abstract":[{"text":"Order data.","type":"text"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"order","kind":"identifier"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"order","kind":"identifier"}],"kind":"symbol","title":"order","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentIntentResponse\/order"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentIntentResponse":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentIntentResponse","abstract":[{"code":"AWXGetPaymentIntentResponse","type":"codeVoice"},{"text":" includes the information of payment intent.","type":"text"}],"title":"AWXGetPaymentIntentResponse","url":"\/documentation\/airwallex\/awxgetpaymentintentresponse","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXGetPaymentIntentResponse","kind":"identifier"}],"navigatorTitle":[{"text":"AWXGetPaymentIntentResponse","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","title":"Airwallex","abstract":[],"type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"order","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"order"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSDictionary","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"order"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","value":"order","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentIntentResponse~1order\/title"},{"op":"replace","value":[{"kind":"identifier","text":"order"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentIntentResponse~1order\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentIntentResponse\/title","value":"AWXGetPaymentIntentResponse"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentIntentResponse\/fragments","value":[{"text":"AWXGetPaymentIntentResponse","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentIntentResponse\/navigatorTitle","value":[{"text":"AWXGetPaymentIntentResponse","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}