{"sections":[],"abstract":[{"type":"text","text":"Payment method object."}],"metadata":{"role":"symbol","title":"paymentMethod","externalID":"c:objc(cs)AWXConfirmPaymentIntentRequest(py)paymentMethod","navigatorTitle":[{"text":"paymentMethod","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentMethod","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AWXPaymentMethod","text":"AWXPaymentMethod","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"modules":[{"name":"Airwallex"}],"symbolKind":"property","roleHeading":"Instance Property"},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentMethod","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod","preciseIdentifier":"c:objc(cs)AWXPaymentMethod","text":"AWXPaymentMethod","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentRequest\/paymentMethod","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxconfirmpaymentintentrequest\/paymentmethod"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxconfirmpaymentintentrequest\/paymentmethod"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentRequest"]]},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXConfirmPaymentIntentRequest":{"url":"\/documentation\/airwallex\/awxconfirmpaymentintentrequest","abstract":[{"code":"AWXConfirmPaymentIntentRequest","type":"codeVoice"},{"text":" includes all of the parameters needed to confirm payment intent.","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXConfirmPaymentIntentRequest","kind":"identifier"}],"navigatorTitle":[{"text":"AWXConfirmPaymentIntentRequest","kind":"identifier"}],"kind":"symbol","title":"AWXConfirmPaymentIntentRequest","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentRequest"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","title":"Airwallex","abstract":[],"type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXConfirmPaymentIntentRequest/paymentMethod":{"title":"paymentMethod","abstract":[{"text":"Payment method object.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentMethod","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWXPaymentMethod","preciseIdentifier":"c:objc(cs)AWXPaymentMethod","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"paymentMethod","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxconfirmpaymentintentrequest\/paymentmethod","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentRequest\/paymentMethod"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentMethod":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod","kind":"symbol","url":"\/documentation\/airwallex\/awxpaymentmethod","title":"AWXPaymentMethod","abstract":[{"type":"codeVoice","code":"AWXPaymentMethod"},{"type":"text","text":" includes the information of a payment method."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPaymentMethod","kind":"identifier"}],"navigatorTitle":[{"text":"AWXPaymentMethod","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"paymentMethod","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"paymentMethod","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod","preciseIdentifier":"c:objc(cs)AWXPaymentMethod","text":"AWXPaymentMethod"},{"kind":"text","text":" * "},{"kind":"identifier","text":"paymentMethod"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"AWXConfirmPaymentIntentRequest","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentRequest\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AWXConfirmPaymentIntentRequest"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentRequest\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AWXConfirmPaymentIntentRequest"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentRequest\/navigatorTitle"},{"op":"replace","value":"paymentMethod","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentRequest~1paymentMethod\/title"},{"op":"replace","value":[{"text":"paymentMethod","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentRequest~1paymentMethod\/fragments"},{"op":"replace","value":"AWXPaymentMethod","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethod\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AWXPaymentMethod"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethod\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethod\/navigatorTitle","value":[{"text":"AWXPaymentMethod","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}