{"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/RequiredBillingContactFields"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/RequiredBillingContactFields\/email"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"email","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/RequiredBillingContactFields","text":"RequiredBillingContactFields","preciseIdentifier":"c:@E@AWXRequiredBillingContactFields","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/requiredbillingcontactfields\/email"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/requiredbillingcontactfields\/email"]}],"metadata":{"externalID":"c:@E@AWXRequiredBillingContactFields@AWXRequiredBillingContactFieldEmail","navigatorTitle":[{"text":"AWXRequiredBillingContactFieldEmail","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"email","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@AWXRequiredBillingContactFields","text":"RequiredBillingContactFields","kind":"typeIdentifier"}],"symbolKind":"property","modules":[{"name":"Airwallex"}],"title":"email","role":"symbol","roleHeading":"Type Property"},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"abstract":[],"type":"topic","url":"\/documentation\/airwallex","title":"Airwallex","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/RequiredBillingContactFields/email":{"abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"email","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@AWXRequiredBillingContactFields","text":"RequiredBillingContactFields","kind":"typeIdentifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/RequiredBillingContactFields\/email","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWXRequiredBillingContactFieldEmail"}],"title":"email","type":"topic","url":"\/documentation\/airwallex\/requiredbillingcontactfields\/email","role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/RequiredBillingContactFields":{"abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/RequiredBillingContactFields","url":"\/documentation\/airwallex\/requiredbillingcontactfields","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"RequiredBillingContactFields"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"RequiredBillingContactFields"}],"title":"RequiredBillingContactFields"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"AWXRequiredBillingContactFieldEmail"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"AWXRequiredBillingContactFieldEmail"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"AWXRequiredBillingContactFieldEmail"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1RequiredBillingContactFields~1email\/title","op":"replace","value":"AWXRequiredBillingContactFieldEmail"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1RequiredBillingContactFields~1email\/fragments","op":"replace","value":[{"text":"AWXRequiredBillingContactFieldEmail","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1RequiredBillingContactFields\/title","op":"replace","value":"AWXRequiredBillingContactFields"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1RequiredBillingContactFields\/fragments","op":"replace","value":[{"kind":"identifier","text":"AWXRequiredBillingContactFields"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1RequiredBillingContactFields\/navigatorTitle","op":"replace","value":[{"text":"AWXRequiredBillingContactFields","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}