{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"mutating","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"formIntersection","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"other","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/RequiredBillingContactFields\/formIntersection(_:)"},"variants":[{"paths":["\/documentation\/airwallex\/requiredbillingcontactfields\/formintersection(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/RequiredBillingContactFields"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"OptionSet.formIntersection(_:)"},{"type":"text","text":"."}],"metadata":{"externalID":"s:s9OptionSetPss17FixedWidthInteger8RawValueRpzrlE16formIntersectionyyxF::SYNTHESIZED::c:@E@AWXRequiredBillingContactFields","symbolKind":"method","role":"symbol","extendedModule":"Swift","modules":[{"name":"Airwallex","relatedModules":["Swift"]}],"roleHeading":"Instance Method","conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"FixedWidthInteger","type":"codeVoice"},{"type":"text","text":"."}]},"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"formIntersection"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":")"}],"title":"formIntersection(_:)"},"sections":[],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","kind":"symbol","url":"\/documentation\/airwallex","abstract":[],"title":"Airwallex","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/RequiredBillingContactFields/formIntersection(_:)":{"conformance":{"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"FixedWidthInteger"},{"text":".","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}]},"type":"topic","kind":"symbol","title":"formIntersection(_:)","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/RequiredBillingContactFields\/formIntersection(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"formIntersection","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","abstract":[],"url":"\/documentation\/airwallex\/requiredbillingcontactfields\/formintersection(_:)"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/RequiredBillingContactFields":{"role":"symbol","abstract":[],"url":"\/documentation\/airwallex\/requiredbillingcontactfields","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/RequiredBillingContactFields","kind":"symbol","title":"RequiredBillingContactFields","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RequiredBillingContactFields","kind":"identifier"}],"navigatorTitle":[{"text":"RequiredBillingContactFields","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1RequiredBillingContactFields\/title","value":"AWXRequiredBillingContactFields"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1RequiredBillingContactFields\/fragments","value":[{"text":"AWXRequiredBillingContactFields","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1RequiredBillingContactFields\/navigatorTitle","value":[{"text":"AWXRequiredBillingContactFields","kind":"identifier"}]}]}]}