{"variants":[{"paths":["\/documentation\/airwallex\/awxcardvalidator\/cardnumberformat(for:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxcardvalidator\/cardnumberformat(for:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","title":"cardNumberFormat(for:)","navigatorTitle":[{"text":"cardNumberFormatForBrand:","kind":"identifier"}],"modules":[{"name":"Airwallex"}],"roleHeading":"Type Method","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cardNumberFormat","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AWXBrandType","kind":"typeIdentifier","preciseIdentifier":"c:@E@AWXBrandType"},{"text":") -> [","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"]","kind":"text"}],"symbolKind":"method","externalID":"c:objc(cs)AWXCardValidator(cm)cardNumberFormatForBrand:"},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cardNumberFormat"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWXBrandType","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrandType","preciseIdentifier":"c:@E@AWXBrandType"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"]"}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardValidator"]]},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardValidator\/cardNumberFormat(for:)","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","role":"collection","title":"Airwallex","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardValidator":{"abstract":[{"code":"AWXCardValidator","type":"codeVoice"},{"type":"text","text":" manages the card info."}],"url":"\/documentation\/airwallex\/awxcardvalidator","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXCardValidator"}],"role":"symbol","title":"AWXCardValidator","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardValidator","navigatorTitle":[{"kind":"identifier","text":"AWXCardValidator"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXBrandType":{"abstract":[],"url":"\/documentation\/airwallex\/awxbrandtype","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXBrandType"}],"role":"symbol","title":"AWXBrandType","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrandType","navigatorTitle":[{"kind":"identifier","text":"AWXBrandType"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardValidator/cardNumberFormat(for:)":{"abstract":[],"url":"\/documentation\/airwallex\/awxcardvalidator\/cardnumberformat(for:)","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cardNumberFormat"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AWXBrandType","kind":"typeIdentifier","preciseIdentifier":"c:@E@AWXBrandType"},{"text":") -> [","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"]","kind":"text"}],"role":"symbol","title":"cardNumberFormat(for:)","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardValidator\/cardNumberFormat(for:)","navigatorTitle":[{"text":"cardNumberFormatForBrand:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"cardNumberFormatForBrand:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"cardNumberFormatForBrand:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"NSArray<NSNumber *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"cardNumberFormatForBrand:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AWXBrandType","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrandType","preciseIdentifier":"c:@E@AWXBrandType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"type"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"AWXCardValidator","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardValidator\/title"},{"op":"replace","value":[{"text":"AWXCardValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardValidator\/fragments"},{"op":"replace","value":[{"text":"AWXCardValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardValidator\/navigatorTitle"},{"op":"replace","value":"AWXBrandType","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrandType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AWXBrandType"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrandType\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AWXBrandType"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrandType\/navigatorTitle"},{"op":"replace","value":"cardNumberFormatForBrand:","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardValidator~1cardNumberFormat(for:)\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"cardNumberFormatForBrand:"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardValidator~1cardNumberFormat(for:)\/fragments"}]}]}