{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAPIClient\/init(configuration:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxapiclient\/init(configuration:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxapiclient\/init(configuration:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAPIClientConfiguration","preciseIdentifier":"c:objc(cs)AWXAPIClientConfiguration","kind":"typeIdentifier","text":"AWXAPIClientConfiguration"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"name":"configuration","content":[{"inlineContent":[{"type":"text","text":"A configuration required."}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"text":"Return Value","level":2,"anchor":"return-value","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The initialized http request client."}]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAPIClient"]]},"abstract":[{"text":"Initializer.","type":"text"}],"metadata":{"navigatorTitle":[{"text":"initWithConfiguration:","kind":"identifier"}],"roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AWXAPIClientConfiguration","preciseIdentifier":"c:objc(cs)AWXAPIClientConfiguration","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","modules":[{"name":"Airwallex"}],"title":"init(configuration:)","externalID":"c:objc(cs)AWXAPIClient(im)initWithConfiguration:","symbolKind":"init"},"kind":"symbol","references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXAPIClient/init(configuration:)":{"abstract":[{"type":"text","text":"Initializer."}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAPIClient\/init(configuration:)","role":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AWXAPIClientConfiguration","preciseIdentifier":"c:objc(cs)AWXAPIClientConfiguration","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithConfiguration:","kind":"identifier"}],"title":"init(configuration:)","url":"\/documentation\/airwallex\/awxapiclient\/init(configuration:)","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","type":"topic","url":"\/documentation\/airwallex","kind":"symbol","abstract":[],"title":"Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXAPIClient":{"abstract":[{"type":"codeVoice","code":"AWXAPIClient"},{"type":"text","text":" is a http request client."}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAPIClient","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXAPIClient"}],"navigatorTitle":[{"kind":"identifier","text":"AWXAPIClient"}],"title":"AWXAPIClient","url":"\/documentation\/airwallex\/awxapiclient","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXAPIClientConfiguration":{"title":"AWXAPIClientConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXAPIClientConfiguration","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAPIClientConfiguration","role":"symbol","navigatorTitle":[{"text":"AWXAPIClientConfiguration","kind":"identifier"}],"type":"topic","abstract":[{"type":"codeVoice","code":"AWXAPIClientConfiguration"},{"type":"text","text":" contains the base configuration the API client needs."}],"kind":"symbol","url":"\/documentation\/airwallex\/awxapiclientconfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithConfiguration:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithConfiguration:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithConfiguration:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AWXAPIClientConfiguration","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAPIClientConfiguration","preciseIdentifier":"c:objc(cs)AWXAPIClientConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"configuration"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"configuration","content":[{"type":"paragraph","inlineContent":[{"text":"A configuration required.","type":"text"}]}]}],"kind":"parameters"}},{"op":"replace","value":{"content":[{"text":"Return Value","anchor":"return-value","level":2,"type":"heading"},{"inlineContent":[{"text":"The initialized http request client.","type":"text"}],"type":"paragraph"}],"kind":"content"},"path":"\/primaryContentSections\/2"},{"op":"replace","value":"initWithConfiguration:","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIClient~1init(configuration:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfiguration:"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIClient~1init(configuration:)\/fragments"},{"op":"replace","value":"AWXAPIClient","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIClient\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AWXAPIClient"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIClient\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AWXAPIClient"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIClient\/navigatorTitle"},{"op":"replace","value":"AWXAPIClientConfiguration","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIClientConfiguration\/title"},{"op":"replace","value":[{"text":"AWXAPIClientConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIClientConfiguration\/fragments"},{"op":"replace","value":[{"text":"AWXAPIClientConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIClientConfiguration\/navigatorTitle"}]}]}