{"variants":[{"paths":["\/documentation\/airwallex\/airwallexmerchanttriggerreason\/scheduled"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/airwallexmerchanttriggerreason\/scheduled"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"externalID":"c:@E@AirwallexMerchantTriggerReason@AirwallexMerchantTriggerReasonScheduled","role":"symbol","navigatorTitle":[{"text":"AirwallexMerchantTriggerReasonScheduled","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"scheduled"}],"title":"AirwallexMerchantTriggerReason.scheduled","symbolKind":"case","modules":[{"name":"Airwallex"}],"roleHeading":"Case"},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexMerchantTriggerReason\/scheduled","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexMerchantTriggerReason"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"scheduled","kind":"identifier"}]}]}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexMerchantTriggerReason/scheduled":{"url":"\/documentation\/airwallex\/airwallexmerchanttriggerreason\/scheduled","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"AirwallexMerchantTriggerReasonScheduled","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scheduled","kind":"identifier"}],"title":"AirwallexMerchantTriggerReason.scheduled","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexMerchantTriggerReason\/scheduled","abstract":[],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexMerchantTriggerReason":{"url":"\/documentation\/airwallex\/airwallexmerchanttriggerreason","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"AirwallexMerchantTriggerReason","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AirwallexMerchantTriggerReason","kind":"identifier"}],"title":"AirwallexMerchantTriggerReason","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexMerchantTriggerReason","abstract":[],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","type":"topic","role":"collection","title":"Airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AirwallexMerchantTriggerReasonScheduled"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"AirwallexMerchantTriggerReasonScheduled","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"AirwallexMerchantTriggerReasonScheduled"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexMerchantTriggerReason~1scheduled\/title","value":"AirwallexMerchantTriggerReasonScheduled"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexMerchantTriggerReason~1scheduled\/fragments","value":[{"text":"AirwallexMerchantTriggerReasonScheduled","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexMerchantTriggerReason\/title","value":"AirwallexMerchantTriggerReason"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexMerchantTriggerReason\/fragments","value":[{"text":"AirwallexMerchantTriggerReason","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexMerchantTriggerReason\/navigatorTitle","value":[{"text":"AirwallexMerchantTriggerReason","kind":"identifier"}]}]}]}