{"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"undefined","kind":"identifier"}]}]}],"variants":[{"paths":["\/documentation\/airwallex\/airwallexmerchanttriggerreason\/undefined"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/airwallexmerchanttriggerreason\/undefined"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexMerchantTriggerReason"]]},"metadata":{"title":"AirwallexMerchantTriggerReason.undefined","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"AirwallexMerchantTriggerReasonUndefined"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"undefined"}],"externalID":"c:@E@AirwallexMerchantTriggerReason@AirwallexMerchantTriggerReasonUndefined","symbolKind":"case","modules":[{"name":"Airwallex"}]},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexMerchantTriggerReason\/undefined","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexMerchantTriggerReason/undefined":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AirwallexMerchantTriggerReasonUndefined"}],"title":"AirwallexMerchantTriggerReason.undefined","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"undefined"}],"type":"topic","url":"\/documentation\/airwallex\/airwallexmerchanttriggerreason\/undefined","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexMerchantTriggerReason\/undefined","kind":"symbol","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"title":"Airwallex","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/airwallex","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexMerchantTriggerReason":{"type":"topic","abstract":[],"url":"\/documentation\/airwallex\/airwallexmerchanttriggerreason","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexMerchantTriggerReason","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AirwallexMerchantTriggerReason","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"AirwallexMerchantTriggerReason","kind":"identifier"}],"title":"AirwallexMerchantTriggerReason"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"AirwallexMerchantTriggerReasonUndefined"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"AirwallexMerchantTriggerReasonUndefined","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"AirwallexMerchantTriggerReasonUndefined","kind":"identifier"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexMerchantTriggerReason~1undefined\/title","op":"replace","value":"AirwallexMerchantTriggerReasonUndefined"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexMerchantTriggerReason~1undefined\/fragments","op":"replace","value":[{"kind":"identifier","text":"AirwallexMerchantTriggerReasonUndefined"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexMerchantTriggerReason\/title","op":"replace","value":"AirwallexMerchantTriggerReason"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexMerchantTriggerReason\/fragments","op":"replace","value":[{"text":"AirwallexMerchantTriggerReason","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexMerchantTriggerReason\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AirwallexMerchantTriggerReason"}]}]}]}