{"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXFormType\/button","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxformtype\/button"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxformtype\/button"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXFormType"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"button","kind":"identifier"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"AWXFormType.button","modules":[{"name":"Airwallex"}],"role":"symbol","externalID":"c:@E@AWXFormType@AWXFormTypeButton","roleHeading":"Case","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"button"}],"navigatorTitle":[{"kind":"identifier","text":"AWXFormTypeButton"}]},"sections":[],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXFormType":{"title":"AWXFormType","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXFormType","navigatorTitle":[{"text":"AWXFormType","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXFormType","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/airwallex\/awxformtype"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","abstract":[],"type":"topic","kind":"symbol","title":"Airwallex","role":"collection"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXFormType/button":{"title":"AWXFormType.button","type":"topic","abstract":[],"url":"\/documentation\/airwallex\/awxformtype\/button","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXFormType\/button","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWXFormTypeButton"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"button"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","value":"AWXFormTypeButton","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"AWXFormTypeButton"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"AWXFormTypeButton"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"AWXFormType","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXFormType\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXFormType\/fragments","op":"replace","value":[{"text":"AWXFormType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXFormType\/navigatorTitle","op":"replace","value":[{"text":"AWXFormType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXFormType~1button\/title","op":"replace","value":"AWXFormTypeButton"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXFormType~1button\/fragments","op":"replace","value":[{"text":"AWXFormTypeButton","kind":"identifier"}]}]}]}