{"variants":[{"paths":["\/documentation\/airwallex\/awxformtype\/listcell"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxformtype\/listcell"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@E@AWXFormType@AWXFormTypeListCell","symbolKind":"case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"listCell","kind":"identifier"}],"navigatorTitle":[{"text":"AWXFormTypeListCell","kind":"identifier"}],"roleHeading":"Case","title":"AWXFormType.listCell","modules":[{"name":"Airwallex"}]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXFormType"]]},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXFormType\/listCell","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"listCell"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"kind":"symbol","abstract":[],"role":"collection","type":"topic","url":"\/documentation\/airwallex","title":"Airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXFormType":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXFormType","navigatorTitle":[{"text":"AWXFormType","kind":"identifier"}],"abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXFormType","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/airwallex\/awxformtype","title":"AWXFormType","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXFormType/listCell":{"navigatorTitle":[{"kind":"identifier","text":"AWXFormTypeListCell"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXFormType\/listCell","url":"\/documentation\/airwallex\/awxformtype\/listcell","type":"topic","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"listCell"}],"title":"AWXFormType.listCell"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"AWXFormTypeListCell"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"AWXFormTypeListCell"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"AWXFormTypeListCell","kind":"identifier"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXFormType\/title","value":"AWXFormType"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXFormType\/fragments","value":[{"kind":"identifier","text":"AWXFormType"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXFormType\/navigatorTitle","value":[{"kind":"identifier","text":"AWXFormType"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXFormType~1listCell\/title","value":"AWXFormTypeListCell"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXFormType~1listCell\/fragments","value":[{"kind":"identifier","text":"AWXFormTypeListCell"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}