{"variants":[{"paths":["\/documentation\/airwallex\/awxpaymentelement\/paymentviewcontroller(_:didcompletewithpaymentconsentid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxpaymentelement\/paymentviewcontroller(_:didcompletewithpaymentconsentid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","symbolKind":"method","title":"paymentViewController(_:didCompleteWithPaymentConsentId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"didCompleteWithPaymentConsentId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"paymentViewController:didCompleteWithPaymentConsentId:","kind":"identifier"}],"roleHeading":"Instance Method","extendedModule":"Airwallex","modules":[{"name":"Airwallex"}],"externalID":"c:@CM@Airwallex@objc(cs)AWXPaymentElement(im)paymentViewController:didCompleteWithPaymentConsentId:"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement"]]},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/paymentViewController(_:didCompleteWithPaymentConsentId:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"controller","kind":"internalParam"},{"kind":"text","text":": "},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"?, "},{"text":"didCompleteWithPaymentConsentId","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"paymentConsentId","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"AWXPaymentResultDelegate.paymentViewController(_:didCompleteWithPaymentConsentId:)","type":"codeVoice"},{"type":"text","text":"."}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","url":"\/documentation\/airwallex","abstract":[],"title":"Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement/paymentViewController(_:didCompleteWithPaymentConsentId:)":{"role":"symbol","type":"topic","title":"paymentViewController(_:didCompleteWithPaymentConsentId:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"paymentViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"didCompleteWithPaymentConsentId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"paymentViewController:didCompleteWithPaymentConsentId:"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/paymentViewController(_:didCompleteWithPaymentConsentId:)","url":"\/documentation\/airwallex\/awxpaymentelement\/paymentviewcontroller(_:didcompletewithpaymentconsentid:)"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement":{"role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentElement"}],"navigatorTitle":[{"kind":"identifier","text":"AWXPaymentElement"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement","url":"\/documentation\/airwallex\/awxpaymentelement","abstract":[{"type":"text","text":"An embeddable payment element that can be added to any view hierarchy."}],"title":"AWXPaymentElement"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"paymentViewController:didCompleteWithPaymentConsentId:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"paymentViewController:didCompleteWithPaymentConsentId:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"paymentViewController:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didCompleteWithPaymentConsentId:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"paymentConsentId","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"paymentViewController:didCompleteWithPaymentConsentId:","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement~1paymentViewController(_:didCompleteWithPaymentConsentId:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentViewController:didCompleteWithPaymentConsentId:"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement~1paymentViewController(_:didCompleteWithPaymentConsentId:)\/fragments","op":"replace"},{"value":"AWXPaymentElement","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AWXPaymentElement"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/fragments","op":"replace"},{"value":[{"text":"AWXPaymentElement","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}