{"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/Configuration\/applePayButton","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/airwallex\/awxuicontext\/configuration\/applepaybutton"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applePayButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWXPaymentElement","preciseIdentifier":"c:@M@Airwallex@objc(cs)AWXPaymentElement","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Configuration","preciseIdentifier":"s:9Airwallex17AWXPaymentElementC13ConfigurationC","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"ApplePayButton","preciseIdentifier":"s:9Airwallex17AWXPaymentElementC13ConfigurationC14ApplePayButtonC","kind":"typeIdentifier"}],"title":"applePayButton","roleHeading":"Instance Property","role":"symbol","externalID":"s:9Airwallex12AWXUIContextC13ConfigurationC14applePayButtonAA17AWXPaymentElementCADC05AppleeF0Cvp","symbolKind":"property","modules":[{"name":"Airwallex"}]},"abstract":[{"type":"text","text":"Configuration for the Apple Pay button (buttonType, disableCardArt)."},{"text":" ","type":"text"},{"type":"text","text":"Note: showsAsPrimaryButton has no effect in sheet context."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/Configuration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applePayButton","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement","preciseIdentifier":"c:@M@Airwallex@objc(cs)AWXPaymentElement","text":"AWXPaymentElement","kind":"typeIdentifier"},{"text":".","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/Configuration","preciseIdentifier":"s:9Airwallex17AWXPaymentElementC13ConfigurationC","text":"Configuration","kind":"typeIdentifier"},{"text":".","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/Configuration\/ApplePayButton-swift.class","preciseIdentifier":"s:9Airwallex17AWXPaymentElementC13ConfigurationC14ApplePayButtonC","text":"ApplePayButton","kind":"typeIdentifier"}],"languages":["swift"]}]}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","type":"topic","role":"collection","title":"Airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement/Configuration":{"url":"\/documentation\/airwallex\/awxpaymentelement\/configuration","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"role":"symbol","title":"AWXPaymentElement.Configuration","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/Configuration","kind":"symbol","abstract":[{"type":"text","text":"Configuration options for the embedded payment element."}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement/Configuration/ApplePayButton-swift.class":{"abstract":[{"type":"text","text":"Configuration for the Apple Pay button appearance and behavior."}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/Configuration\/ApplePayButton-swift.class","title":"AWXPaymentElement.Configuration.ApplePayButton","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ApplePayButton","kind":"identifier"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"ApplePayButton","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxpaymentelement\/configuration\/applepaybutton-swift.class"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXUIContext":{"navigatorTitle":[{"text":"AWXUIContext","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext","abstract":[{"type":"text","text":"The main UI context for Airwallex payment flows."}],"title":"AWXUIContext","type":"topic","kind":"symbol","url":"\/documentation\/airwallex\/awxuicontext","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXUIContext","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement":{"title":"AWXPaymentElement","navigatorTitle":[{"text":"AWXPaymentElement","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxpaymentelement","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement","role":"symbol","abstract":[{"text":"An embeddable payment element that can be added to any view hierarchy.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPaymentElement","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXUIContext/Configuration":{"title":"AWXUIContext.Configuration","abstract":[{"type":"text","text":"Configuration options for launching the payment UI."}],"navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/airwallex\/awxuicontext\/configuration","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/Configuration","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXUIContext/Configuration/applePayButton":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/Configuration\/applePayButton","role":"symbol","type":"topic","title":"applePayButton","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"applePayButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWXPaymentElement","preciseIdentifier":"c:@M@Airwallex@objc(cs)AWXPaymentElement","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Configuration","preciseIdentifier":"s:9Airwallex17AWXPaymentElementC13ConfigurationC","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"ApplePayButton","preciseIdentifier":"s:9Airwallex17AWXPaymentElementC13ConfigurationC14ApplePayButtonC","kind":"typeIdentifier"}],"abstract":[{"text":"Configuration for the Apple Pay button (buttonType, disableCardArt).","type":"text"},{"text":" ","type":"text"},{"text":"Note: showsAsPrimaryButton has no effect in sheet context.","type":"text"}],"url":"\/documentation\/airwallex\/awxuicontext\/configuration\/applepaybutton"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext\/title","value":"AWXUIContext"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext\/fragments","value":[{"kind":"identifier","text":"AWXUIContext"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext\/navigatorTitle","value":[{"kind":"identifier","text":"AWXUIContext"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/title","value":"AWXPaymentElement"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/fragments","value":[{"kind":"identifier","text":"AWXPaymentElement"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/navigatorTitle","value":[{"kind":"identifier","text":"AWXPaymentElement"}]}]}]}