{"sections":[],"metadata":{"role":"collectionGroup","modules":[{"name":"Airwallex"}],"title":"RawRepresentable Implementations","roleHeading":"API Collection"},"variants":[{"paths":["\/documentation\/airwallex\/periodunit\/rawrepresentable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PeriodUnit\/RawRepresentable-Implementations"},"schemaVersion":{"major":0,"patch":0,"minor":3},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PeriodUnit\/hashValue"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PeriodUnit\/hash(into:)"],"generated":true,"anchor":"Instance-Methods"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PeriodUnit"]]},"kind":"article","references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","url":"\/documentation\/airwallex","role":"collection","kind":"symbol","abstract":[],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PeriodUnit":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PeriodUnit","url":"\/documentation\/airwallex\/periodunit","navigatorTitle":[{"text":"PeriodUnit","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"Period unit enumeration for billing frequency","type":"text"}],"title":"PeriodUnit","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PeriodUnit","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PeriodUnit/hashValue":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PeriodUnit\/hashValue","role":"symbol","title":"hashValue","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"url":"\/documentation\/airwallex\/periodunit\/hashvalue","kind":"symbol","type":"topic","conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}]},"abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PeriodUnit/hash(into:)":{"title":"hash(into:)","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PeriodUnit\/hash(into:)","abstract":[],"role":"symbol","conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}]},"url":"\/documentation\/airwallex\/periodunit\/hash(into:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hasher","kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PeriodUnit\/title","value":"PeriodUnit"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PeriodUnit\/fragments","value":[{"kind":"identifier","text":"PeriodUnit"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PeriodUnit\/navigatorTitle","value":[{"kind":"identifier","text":"PeriodUnit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}