{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"abstract":[{"text":"Stage.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxconfirmpaymentnextaction\/stage"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxconfirmpaymentnextaction\/stage"]}],"metadata":{"title":"stage","modules":[{"name":"Airwallex"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"stage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"role":"symbol","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"stage"}],"roleHeading":"Instance Property","externalID":"c:objc(cs)AWXConfirmPaymentNextAction(py)stage"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentNextAction\/stage","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentNextAction"]]},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol","type":"topic","url":"\/documentation\/airwallex","role":"collection","abstract":[],"title":"Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXConfirmPaymentNextAction/stage":{"title":"stage","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stage","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/airwallex\/awxconfirmpaymentnextaction\/stage","abstract":[{"type":"text","text":"Stage."}],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentNextAction\/stage","kind":"symbol","navigatorTitle":[{"text":"stage","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXConfirmPaymentNextAction":{"title":"AWXConfirmPaymentNextAction","abstract":[{"type":"codeVoice","code":"AWXConfirmPaymentNextAction"},{"text":" includes the parameters for next action.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXConfirmPaymentNextAction","kind":"identifier"}],"navigatorTitle":[{"text":"AWXConfirmPaymentNextAction","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentNextAction","url":"\/documentation\/airwallex\/awxconfirmpaymentnextaction","type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"stage"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"stage"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"stage","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentNextAction~1stage\/title","value":"stage"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentNextAction~1stage\/fragments","value":[{"text":"stage","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentNextAction\/title","value":"AWXConfirmPaymentNextAction"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentNextAction\/fragments","value":[{"kind":"identifier","text":"AWXConfirmPaymentNextAction"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentNextAction\/navigatorTitle","value":[{"kind":"identifier","text":"AWXConfirmPaymentNextAction"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}