{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Airwallex"]]},"variants":[{"paths":["\/documentation\/airwallex\/airwallex\/defaultbaseurl()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/airwallex\/defaultbaseurl()"]}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Airwallex\/defaultBaseURL()","interfaceLanguage":"swift"},"metadata":{"role":"symbol","symbolKind":"method","modules":[{"name":"Airwallex"}],"navigatorTitle":[{"kind":"identifier","text":"defaultBaseURL"}],"title":"defaultBaseURL()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultBaseURL"},{"text":"() -> ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"}],"externalID":"c:objc(cs)Airwallex(cm)defaultBaseURL","roleHeading":"Type Method"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultBaseURL"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"}]}],"kind":"declarations"}],"abstract":[{"text":"Get base URL.","type":"text"}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"abstract":[],"kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","url":"\/documentation\/airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/Airwallex":{"abstract":[{"type":"codeVoice","code":"Airwallex"},{"type":"text","text":" contains the base configuration the SDK needs."}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Airwallex","title":"Airwallex","navigatorTitle":[{"kind":"identifier","text":"Airwallex"}],"url":"\/documentation\/airwallex\/airwallex","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Airwallex"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/Airwallex/defaultBaseURL()":{"abstract":[{"text":"Get base URL.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Airwallex\/defaultBaseURL()","title":"defaultBaseURL()","navigatorTitle":[{"text":"defaultBaseURL","kind":"identifier"}],"url":"\/documentation\/airwallex\/airwallex\/defaultbaseurl()","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultBaseURL","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"defaultBaseURL","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"defaultBaseURL"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL","text":"NSURL"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"defaultBaseURL"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"value":"Airwallex","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Airwallex\/title","op":"replace"},{"op":"replace","value":[{"text":"Airwallex","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Airwallex\/fragments"},{"value":[{"kind":"identifier","text":"Airwallex"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Airwallex\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Airwallex~1defaultBaseURL()\/title","value":"defaultBaseURL"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"defaultBaseURL"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Airwallex~1defaultBaseURL()\/fragments"}]}]}