{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxuicontext\/launchpayment(from:session:paymentresultdelegate:configuration:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxuicontext\/launchpayment(from:session:paymentresultdelegate:configuration:)"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext"]]},"abstract":[{"text":"Launches the Airwallex payment UI using a configuration object.","type":"text"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/launchPayment(from:session:paymentResultDelegate:configuration:)"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"launchPayment"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"kind":"internalParam","text":"hostingVC"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"session"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession","preciseIdentifier":"c:objc(cs)AWXSession","text":"AWXSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"paymentResultDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentResultDelegate","preciseIdentifier":"c:objc(pl)AWXPaymentResultDelegate","text":"AWXPaymentResultDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/Configuration","preciseIdentifier":"s:9Airwallex12AWXUIContextC13ConfigurationC","text":"Configuration"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The view controller that launches the payment UI.","type":"text"}]}],"name":"hostingVC"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The current payment session.","type":"text"}]}],"name":"session"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The delegate responsible for handling the payment result.","type":"text"}]}],"name":"paymentResultDelegate"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Configuration for the payment flow.","type":"text"}]}],"name":"configuration"}],"kind":"parameters"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"roleHeading":"Type Method","externalID":"c:@CM@Airwallex@objc(cs)AWXUIContext(cm)launchPaymentFrom:session:paymentResultDelegate:configuration:","role":"symbol","symbolKind":"method","title":"launchPayment(from:session:paymentResultDelegate:configuration:)","modules":[{"name":"Airwallex"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"launchPayment","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"session","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AWXSession","preciseIdentifier":"c:objc(cs)AWXSession","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"paymentResultDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AWXPaymentResultDelegate","preciseIdentifier":"c:objc(pl)AWXPaymentResultDelegate","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Configuration","preciseIdentifier":"s:9Airwallex12AWXUIContextC13ConfigurationC","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"launchPaymentFrom:session:paymentResultDelegate:configuration:","kind":"identifier"}],"extendedModule":"Airwallex"},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXUIContext/Configuration":{"title":"AWXUIContext.Configuration","abstract":[{"type":"text","text":"Configuration options for launching the payment UI."}],"navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/airwallex\/awxuicontext\/configuration","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/Configuration","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXUIContext/launchPayment(from:session:paymentResultDelegate:configuration:)":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"launchPayment","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"session"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWXSession","preciseIdentifier":"c:objc(cs)AWXSession"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"paymentResultDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWXPaymentResultDelegate","preciseIdentifier":"c:objc(pl)AWXPaymentResultDelegate"},{"text":", ","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Configuration","preciseIdentifier":"s:9Airwallex12AWXUIContextC13ConfigurationC","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"launchPaymentFrom:session:paymentResultDelegate:configuration:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/launchPayment(from:session:paymentResultDelegate:configuration:)","kind":"symbol","type":"topic","url":"\/documentation\/airwallex\/awxuicontext\/launchpayment(from:session:paymentresultdelegate:configuration:)","role":"symbol","title":"launchPayment(from:session:paymentResultDelegate:configuration:)","abstract":[{"type":"text","text":"Launches the Airwallex payment UI using a configuration object."}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXUIContextConfiguration":{"url":"\/documentation\/airwallex\/awxuicontextconfiguration","title":"AWXUIContextConfiguration","type":"topic","abstract":[{"type":"text","text":"Configuration options for launching the payment UI."},{"type":"text","text":" "},{"type":"text","text":"Use this class to customize the payment flow launched by "},{"type":"text","text":"AWXUIContext"},{"type":"text","text":"."}],"fragments":[{"kind":"identifier","text":"AWXUIContextConfiguration"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContextConfiguration","kind":"symbol","role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentResultDelegate":{"url":"\/documentation\/airwallex\/awxpaymentresultdelegate","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AWXPaymentResultDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentResultDelegate"}],"role":"symbol","title":"AWXPaymentResultDelegate","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentResultDelegate","kind":"symbol","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSession":{"url":"\/documentation\/airwallex\/awxsession","type":"topic","navigatorTitle":[{"text":"AWXSession","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXSession","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession","kind":"symbol","title":"AWXSession","abstract":[{"type":"codeVoice","code":"AWXSession"},{"text":" is the base session.","type":"text"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","type":"topic","role":"collection","title":"Airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXUIContext":{"navigatorTitle":[{"text":"AWXUIContext","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext","abstract":[{"type":"text","text":"The main UI context for Airwallex payment flows."}],"title":"AWXUIContext","type":"topic","kind":"symbol","url":"\/documentation\/airwallex\/awxuicontext","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXUIContext","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"launchPaymentFrom:session:paymentResultDelegate:configuration:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"launchPaymentFrom:session:paymentResultDelegate:configuration:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"launchPaymentFrom:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"hostingVC","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"session:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession","preciseIdentifier":"c:objc(cs)AWXSession","text":"AWXSession","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"session","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"paymentResultDelegate:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qoobjc(pl)AWXPaymentResultDelegate","text":"id<AWXPaymentResultDelegate>","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"paymentResultDelegate","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"configuration:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContextConfiguration","preciseIdentifier":"c:@M@Airwallex@objc(cs)AWXUIContextConfiguration","text":"AWXUIContextConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"configuration","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"name":"hostingVC","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The view controller that launches the payment UI."}]}]},{"name":"session","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The current payment session."}]}]},{"name":"paymentResultDelegate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The delegate responsible for handling the payment result."}]}]},{"name":"configuration","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Configuration for the payment flow."}]}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"launchPaymentFrom:session:paymentResultDelegate:configuration:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext~1launchPayment(from:session:paymentResultDelegate:configuration:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"launchPaymentFrom:session:paymentResultDelegate:configuration:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext~1launchPayment(from:session:paymentResultDelegate:configuration:)\/fragments"},{"value":"AWXPaymentResultDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentResultDelegate\/title"},{"value":[{"kind":"identifier","text":"AWXPaymentResultDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentResultDelegate\/fragments"},{"value":[{"kind":"identifier","text":"AWXPaymentResultDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentResultDelegate\/navigatorTitle"},{"value":"AWXSession","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/title"},{"value":[{"kind":"identifier","text":"AWXSession"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/fragments"},{"value":[{"kind":"identifier","text":"AWXSession"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/navigatorTitle"},{"value":"AWXUIContext","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext\/title"},{"value":[{"kind":"identifier","text":"AWXUIContext"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext\/fragments"},{"value":[{"kind":"identifier","text":"AWXUIContext"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext\/navigatorTitle"}]}]}