{"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/requiredbillingcontactfields\/issuperset(of:)"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSuperset"},{"kind":"text","text":"("},{"kind":"externalParam","text":"of"},{"kind":"text","text":" "},{"kind":"internalParam","text":"other"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/RequiredBillingContactFields"]]},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"SetAlgebra.isSuperset(of:)","type":"codeVoice"},{"text":".","type":"text"}],"metadata":{"extendedModule":"Swift","roleHeading":"Instance Method","title":"isSuperset(of:)","symbolKind":"method","externalID":"s:s10SetAlgebraPsE10isSuperset2ofSbx_tF::SYNTHESIZED::c:@E@AWXRequiredBillingContactFields","modules":[{"name":"Airwallex","relatedModules":["Swift"]}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSuperset"},{"kind":"text","text":"("},{"kind":"externalParam","text":"of"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/RequiredBillingContactFields\/isSuperset(of:)","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","role":"collection","url":"\/documentation\/airwallex","kind":"symbol","title":"Airwallex","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/RequiredBillingContactFields/isSuperset(of:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSuperset"},{"kind":"text","text":"("},{"kind":"externalParam","text":"of"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"isSuperset(of:)","abstract":[],"url":"\/documentation\/airwallex\/requiredbillingcontactfields\/issuperset(of:)","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/RequiredBillingContactFields\/isSuperset(of:)"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/RequiredBillingContactFields":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RequiredBillingContactFields","kind":"identifier"}],"url":"\/documentation\/airwallex\/requiredbillingcontactfields","title":"RequiredBillingContactFields","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/RequiredBillingContactFields","type":"topic","role":"symbol","navigatorTitle":[{"text":"RequiredBillingContactFields","kind":"identifier"}],"kind":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1RequiredBillingContactFields\/title","value":"AWXRequiredBillingContactFields"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1RequiredBillingContactFields\/fragments","value":[{"text":"AWXRequiredBillingContactFields","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1RequiredBillingContactFields\/navigatorTitle","value":[{"kind":"identifier","text":"AWXRequiredBillingContactFields"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}