{"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentFormViewControllerDelegate\/paymentFormViewController(_:didSelectOption:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentFormViewControllerDelegate"]]},"abstract":[{"text":"temporary solution, used for handling bank selection in ","type":"text"},{"code":"SchemaPaymentSectionController","type":"codeVoice"},{"text":" only","type":"text"},{"text":" ","type":"text"},{"text":"will be called after user select an option and before ","type":"text"},{"code":"paymentFormViewController:didUpdatePaymentMethod:","type":"codeVoice"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentFormViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"paymentFormViewController"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AWXPaymentFormViewController","kind":"typeIdentifier","text":"AWXPaymentFormViewController","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentFormViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelectOption"},{"kind":"text","text":" "},{"kind":"internalParam","text":"optionKey"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"paymentFormViewController","content":[{"type":"paragraph","inlineContent":[{"text":"Controller","type":"text"}]}]},{"name":"optionKey","content":[{"type":"paragraph","inlineContent":[{"text":"Key for the selected option","type":"text"}]}]}]}],"metadata":{"navigatorTitle":[{"text":"paymentFormViewController:didSelectOption:","kind":"identifier"}],"roleHeading":"Instance Method","title":"paymentFormViewController(_:didSelectOption:)","modules":[{"name":"Airwallex"}],"externalID":"c:objc(pl)AWXPaymentFormViewControllerDelegate(im)paymentFormViewController:didSelectOption:","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentFormViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AWXPaymentFormViewController","preciseIdentifier":"c:objc(cs)AWXPaymentFormViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didSelectOption","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"method"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/airwallex\/awxpaymentformviewcontrollerdelegate\/paymentformviewcontroller(_:didselectoption:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxpaymentformviewcontrollerdelegate\/paymentformviewcontroller(_:didselectoption:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentFormViewControllerDelegate":{"url":"\/documentation\/airwallex\/awxpaymentformviewcontrollerdelegate","type":"topic","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPaymentFormViewControllerDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"AWXPaymentFormViewControllerDelegate","kind":"identifier"}],"title":"AWXPaymentFormViewControllerDelegate","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentFormViewControllerDelegate","abstract":[{"text":"A delegate handles payment form result.","type":"text"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentFormViewControllerDelegate/paymentFormViewController(_:didSelectOption:)":{"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/airwallex\/awxpaymentformviewcontrollerdelegate\/paymentformviewcontroller(_:didselectoption:)","abstract":[{"text":"temporary solution, used for handling bank selection in ","type":"text"},{"code":"SchemaPaymentSectionController","type":"codeVoice"},{"text":" only","type":"text"},{"text":" ","type":"text"},{"text":"will be called after user select an option and before ","type":"text"},{"code":"paymentFormViewController:didUpdatePaymentMethod:","type":"codeVoice"}],"title":"paymentFormViewController(_:didSelectOption:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"paymentFormViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AWXPaymentFormViewController","preciseIdentifier":"c:objc(cs)AWXPaymentFormViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didSelectOption","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"paymentFormViewController:didSelectOption:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentFormViewControllerDelegate\/paymentFormViewController(_:didSelectOption:)"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentFormViewController":{"url":"\/documentation\/airwallex\/awxpaymentformviewcontroller","abstract":[{"code":"AWXPaymentFormViewController","type":"codeVoice"},{"text":" handles payment form.","type":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentFormViewController","title":"AWXPaymentFormViewController","navigatorTitle":[{"kind":"identifier","text":"AWXPaymentFormViewController"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentFormViewController"}],"type":"topic","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","abstract":[],"title":"Airwallex","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"paymentFormViewController:didSelectOption:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentFormViewController:didSelectOption:"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"paymentFormViewController:"},{"kind":"text","text":"("},{"text":"AWXPaymentFormViewController","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentFormViewController","preciseIdentifier":"c:objc(cs)AWXPaymentFormViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"paymentFormViewController"},{"kind":"text","text":" "},{"kind":"identifier","text":"didSelectOption:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"optionKey"},{"text":";","kind":"text"}]}]},"op":"replace"},{"value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Controller"}]}],"name":"paymentFormViewController"},{"content":[{"inlineContent":[{"text":"Key for the selected option","type":"text"}],"type":"paragraph"}],"name":"optionKey"}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"AWXPaymentFormViewControllerDelegate","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentFormViewControllerDelegate\/title","op":"replace"},{"value":[{"text":"AWXPaymentFormViewControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentFormViewControllerDelegate\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AWXPaymentFormViewControllerDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentFormViewControllerDelegate\/navigatorTitle","op":"replace"},{"value":"paymentFormViewController:didSelectOption:","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentFormViewControllerDelegate~1paymentFormViewController(_:didSelectOption:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"paymentFormViewController:didSelectOption:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentFormViewControllerDelegate~1paymentFormViewController(_:didSelectOption:)\/fragments","op":"replace"},{"value":"AWXPaymentFormViewController","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentFormViewController\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AWXPaymentFormViewController"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentFormViewController\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AWXPaymentFormViewController"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentFormViewController\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}