{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"AWXSDKErrorCodeInternalError"}],"title":"AWXSDKErrorCode.internalError","modules":[{"name":"Airwallex"}],"roleHeading":"Case","role":"symbol","externalID":"c:@E@AWXSDKErrorCode@AWXSDKErrorCodeInternalError","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalError"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSDKErrorCode"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSDKErrorCode\/internalError"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"internalError","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/airwallex\/awxsdkerrorcode\/internalerror"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxsdkerrorcode\/internalerror"]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","url":"\/documentation\/airwallex","abstract":[],"title":"Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSDKErrorCode/internalError":{"role":"symbol","type":"topic","title":"AWXSDKErrorCode.internalError","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"internalError"}],"navigatorTitle":[{"kind":"identifier","text":"AWXSDKErrorCodeInternalError"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSDKErrorCode\/internalError","url":"\/documentation\/airwallex\/awxsdkerrorcode\/internalerror"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSDKErrorCode":{"role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXSDKErrorCode"}],"navigatorTitle":[{"kind":"identifier","text":"AWXSDKErrorCode"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSDKErrorCode","url":"\/documentation\/airwallex\/awxsdkerrorcode","title":"AWXSDKErrorCode","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AWXSDKErrorCodeInternalError"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"AWXSDKErrorCodeInternalError","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"AWXSDKErrorCodeInternalError","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"AWXSDKErrorCodeInternalError","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSDKErrorCode~1internalError\/title"},{"value":[{"text":"AWXSDKErrorCodeInternalError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSDKErrorCode~1internalError\/fragments"},{"value":"AWXSDKErrorCode","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSDKErrorCode\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSDKErrorCode\/fragments","value":[{"text":"AWXSDKErrorCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSDKErrorCode\/navigatorTitle","value":[{"text":"AWXSDKErrorCode","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}