{"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"component","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Display a single payment method component."},{"type":"text","text":" "},{"type":"text","text":"Requires "},{"type":"codeVoice","code":"paymentMethodName"},{"type":"text","text":" to be set on the configuration."}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/ElementType"]]},"metadata":{"externalID":"s:9Airwallex12AWXUIContextC11ElementTypeO9componentyA2EmF","role":"symbol","modules":[{"name":"Airwallex"}],"symbolKind":"case","title":"AWXUIContext.ElementType.component","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"component","kind":"identifier"}]},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/ElementType\/component"},"variants":[{"paths":["\/documentation\/airwallex\/awxuicontext\/elementtype\/component"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXUIContext":{"role":"symbol","url":"\/documentation\/airwallex\/awxuicontext","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXUIContext","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The main UI context for Airwallex payment flows."}],"title":"AWXUIContext","navigatorTitle":[{"text":"AWXUIContext","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXUIContext/ElementType":{"title":"AWXUIContext.ElementType","type":"topic","role":"symbol","navigatorTitle":[{"text":"ElementType","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxuicontext\/elementtype","abstract":[{"type":"text","text":"The type of payment flow to display."}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/ElementType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ElementType","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXUIContext/ElementType/component":{"title":"AWXUIContext.ElementType.component","type":"topic","role":"symbol","url":"\/documentation\/airwallex\/awxuicontext\/elementtype\/component","abstract":[{"type":"text","text":"Display a single payment method component."},{"type":"text","text":" "},{"type":"text","text":"Requires "},{"code":"paymentMethodName","type":"codeVoice"},{"type":"text","text":" to be set on the configuration."}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/ElementType\/component","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"component","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","url":"\/documentation\/airwallex","title":"Airwallex","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext\/title","value":"AWXUIContext"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext\/fragments","value":[{"text":"AWXUIContext","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext\/navigatorTitle","value":[{"text":"AWXUIContext","kind":"identifier"}]}]}]}