{"abstract":[{"type":"text","text":"Confirm the payment intent with payment method and consent."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confirmPaymentIntent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"paymentMethod","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"AWXPaymentMethod","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod","preciseIdentifier":"c:objc(cs)AWXPaymentMethod"},{"text":", ","kind":"text"},{"text":"paymentConsent","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AWXPaymentConsent","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentConsent","preciseIdentifier":"c:objc(cs)AWXPaymentConsent"},{"text":"?)","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"paymentMethod","content":[{"inlineContent":[{"text":"The payment method info.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"The payment consent info."}],"type":"paragraph"}],"name":"paymentConsent"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider\/confirmPaymentIntent(with:paymentConsent:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider"]]},"metadata":{"externalID":"c:objc(cs)AWXDefaultProvider(im)confirmPaymentIntentWithPaymentMethod:paymentConsent:","modules":[{"name":"Airwallex"}],"role":"symbol","symbolKind":"method","navigatorTitle":[{"text":"confirmPaymentIntentWithPaymentMethod:paymentConsent:","kind":"identifier"}],"roleHeading":"Instance Method","title":"confirmPaymentIntent(with:paymentConsent:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confirmPaymentIntent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AWXPaymentMethod","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPaymentMethod"},{"text":", ","kind":"text"},{"text":"paymentConsent","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AWXPaymentConsent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPaymentConsent"},{"text":"?)","kind":"text"}]},"sections":[],"variants":[{"paths":["\/documentation\/airwallex\/awxdefaultprovider\/confirmpaymentintent(with:paymentconsent:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxdefaultprovider\/confirmpaymentintent(with:paymentconsent:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentConsent":{"role":"symbol","type":"topic","title":"AWXPaymentConsent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentConsent"}],"navigatorTitle":[{"kind":"identifier","text":"AWXPaymentConsent"}],"kind":"symbol","abstract":[{"code":"AWXPaymentConsent","type":"codeVoice"},{"text":" includes the info of payment consent.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentConsent","url":"\/documentation\/airwallex\/awxpaymentconsent"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXDefaultProvider/confirmPaymentIntent(with:paymentConsent:)":{"abstract":[{"text":"Confirm the payment intent with payment method and consent.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider\/confirmPaymentIntent(with:paymentConsent:)","url":"\/documentation\/airwallex\/awxdefaultprovider\/confirmpaymentintent(with:paymentconsent:)","navigatorTitle":[{"text":"confirmPaymentIntentWithPaymentMethod:paymentConsent:","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confirmPaymentIntent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AWXPaymentMethod","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPaymentMethod"},{"text":", ","kind":"text"},{"text":"paymentConsent","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AWXPaymentConsent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPaymentConsent"},{"text":"?)","kind":"text"}],"kind":"symbol","title":"confirmPaymentIntent(with:paymentConsent:)"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentMethod":{"abstract":[{"type":"codeVoice","code":"AWXPaymentMethod"},{"type":"text","text":" includes the information of a payment method."}],"url":"\/documentation\/airwallex\/awxpaymentmethod","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod","navigatorTitle":[{"text":"AWXPaymentMethod","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPaymentMethod","kind":"identifier"}],"kind":"symbol","title":"AWXPaymentMethod"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","url":"\/documentation\/airwallex","abstract":[],"title":"Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXDefaultProvider":{"abstract":[{"type":"text","text":"A provider which handles payment business."}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider","url":"\/documentation\/airwallex\/awxdefaultprovider","navigatorTitle":[{"kind":"identifier","text":"AWXDefaultProvider"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXDefaultProvider"}],"kind":"symbol","title":"AWXDefaultProvider"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"confirmPaymentIntentWithPaymentMethod:paymentConsent:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"confirmPaymentIntentWithPaymentMethod:paymentConsent:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"confirmPaymentIntentWithPaymentMethod:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod","preciseIdentifier":"c:objc(cs)AWXPaymentMethod","text":"AWXPaymentMethod"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"paymentMethod"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentConsent:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentConsent","preciseIdentifier":"c:objc(cs)AWXPaymentConsent","text":"AWXPaymentConsent"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"paymentConsent"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"paymentMethod","content":[{"inlineContent":[{"text":"The payment method info.","type":"text"}],"type":"paragraph"}]},{"name":"paymentConsent","content":[{"inlineContent":[{"text":"The payment consent info.","type":"text"}],"type":"paragraph"}]}]},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"AWXPaymentConsent","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentConsent\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AWXPaymentConsent"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentConsent\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AWXPaymentConsent"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentConsent\/navigatorTitle"},{"op":"replace","value":"confirmPaymentIntentWithPaymentMethod:paymentConsent:","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider~1confirmPaymentIntent(with:paymentConsent:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"confirmPaymentIntentWithPaymentMethod:paymentConsent:"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider~1confirmPaymentIntent(with:paymentConsent:)\/fragments"},{"op":"replace","value":"AWXPaymentMethod","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethod\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AWXPaymentMethod"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethod\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AWXPaymentMethod"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethod\/navigatorTitle"},{"op":"replace","value":"AWXDefaultProvider","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AWXDefaultProvider"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AWXDefaultProvider"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}