{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentElement"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"element"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@Airwallex@objc(cs)AWXPaymentElement","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement","text":"AWXPaymentElement"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didCompleteFor"},{"kind":"text","text":" "},{"kind":"internalParam","text":"paymentMethod"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"status"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@AirwallexPaymentStatus","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexPaymentStatus","text":"AirwallexPaymentStatus"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?)"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The payment element that completed payment."}]}],"name":"element"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The name of the payment method used."}]}],"name":"paymentMethod"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The result status of the payment."}]}],"name":"status"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The error if payment failed, nil otherwise."}]}],"name":"error"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElementDelegate"]]},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElementDelegate\/paymentElement(_:didCompleteFor:with:error:)","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"Called when payment processing completes."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxpaymentelementdelegate\/paymentelement(_:didcompletefor:with:error:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxpaymentelementdelegate\/paymentelement(_:didcompletefor:with:error:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"symbolKind":"method","externalID":"c:@M@Airwallex@objc(pl)AWXPaymentElementDelegate(im)paymentElement:didCompleteFor:with:error:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentElement"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@Airwallex@objc(cs)AWXPaymentElement","text":"AWXPaymentElement"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didCompleteFor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@AirwallexPaymentStatus","text":"AirwallexPaymentStatus"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?)"}],"role":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"paymentElement:didCompleteFor:with:error:"}],"roleHeading":"Instance Method","title":"paymentElement(_:didCompleteFor:with:error:)","modules":[{"name":"Airwallex"}]},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexPaymentStatus":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AirwallexPaymentStatus"}],"role":"symbol","url":"\/documentation\/airwallex\/airwallexpaymentstatus","navigatorTitle":[{"text":"AirwallexPaymentStatus","kind":"identifier"}],"type":"topic","abstract":[],"title":"AirwallexPaymentStatus","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexPaymentStatus"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElementDelegate/paymentElement(_:didCompleteFor:with:error:)":{"title":"paymentElement(_:didCompleteFor:with:error:)","type":"topic","abstract":[{"text":"Called when payment processing completes.","type":"text"}],"url":"\/documentation\/airwallex\/awxpaymentelementdelegate\/paymentelement(_:didcompletefor:with:error:)","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElementDelegate\/paymentElement(_:didCompleteFor:with:error:)","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"paymentElement:didCompleteFor:with:error:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentElement"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@Airwallex@objc(cs)AWXPaymentElement","text":"AWXPaymentElement"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didCompleteFor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@AirwallexPaymentStatus","kind":"typeIdentifier","text":"AirwallexPaymentStatus"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?)"}],"required":true},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","abstract":[],"type":"topic","kind":"symbol","title":"Airwallex","role":"collection"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement":{"abstract":[{"text":"An embeddable payment element that can be added to any view hierarchy.","type":"text"}],"title":"AWXPaymentElement","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement","navigatorTitle":[{"kind":"identifier","text":"AWXPaymentElement"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentElement"}],"kind":"symbol","url":"\/documentation\/airwallex\/awxpaymentelement","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElementDelegate":{"abstract":[{"text":"Delegate protocol for receiving payment events from AWXPaymentElement.","type":"text"}],"title":"AWXPaymentElementDelegate","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElementDelegate","navigatorTitle":[{"kind":"identifier","text":"AWXPaymentElementDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentElementDelegate"}],"kind":"symbol","url":"\/documentation\/airwallex\/awxpaymentelementdelegate","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"paymentElement:didCompleteFor:with:error:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentElement:didCompleteFor:with:error:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"paymentElement:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@Airwallex@objc(cs)AWXPaymentElement","text":"AWXPaymentElement","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement"},{"text":" *) ","kind":"text"},{"text":"element","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didCompleteFor:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"paymentMethod"},{"kind":"text","text":" "},{"kind":"identifier","text":"with:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@AirwallexPaymentStatus","text":"AirwallexPaymentStatus","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexPaymentStatus"},{"kind":"text","text":") "},{"kind":"internalParam","text":"status"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"text":" *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The payment element that completed payment."}],"type":"paragraph"}],"name":"element"},{"content":[{"inlineContent":[{"type":"text","text":"The name of the payment method used."}],"type":"paragraph"}],"name":"paymentMethod"},{"content":[{"inlineContent":[{"type":"text","text":"The result status of the payment."}],"type":"paragraph"}],"name":"status"},{"content":[{"inlineContent":[{"type":"text","text":"The error if payment failed, nil otherwise."}],"type":"paragraph"}],"name":"error"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"AirwallexPaymentStatus","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexPaymentStatus\/title"},{"value":[{"kind":"identifier","text":"AirwallexPaymentStatus"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexPaymentStatus\/fragments"},{"value":[{"kind":"identifier","text":"AirwallexPaymentStatus"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexPaymentStatus\/navigatorTitle"},{"value":"paymentElement:didCompleteFor:with:error:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElementDelegate~1paymentElement(_:didCompleteFor:with:error:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentElement:didCompleteFor:with:error:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElementDelegate~1paymentElement(_:didCompleteFor:with:error:)\/fragments"},{"value":"AWXPaymentElement","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/title"},{"value":[{"kind":"identifier","text":"AWXPaymentElement"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/fragments"},{"value":[{"kind":"identifier","text":"AWXPaymentElement"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/navigatorTitle"},{"value":"AWXPaymentElementDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElementDelegate\/title"},{"value":[{"kind":"identifier","text":"AWXPaymentElementDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElementDelegate\/fragments"},{"value":[{"kind":"identifier","text":"AWXPaymentElementDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElementDelegate\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}