{"sections":[],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentElement","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AWXPaymentElement","preciseIdentifier":"c:@M@Airwallex@objc(cs)AWXPaymentElement","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"onProcessingStateChangedFor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"isProcessing","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"c:@M@Airwallex@objc(pl)AWXPaymentElementDelegate(im)paymentElement:onProcessingStateChangedFor:isProcessing:","role":"symbol","symbolKind":"method","navigatorTitle":[{"text":"paymentElement:onProcessingStateChangedFor:isProcessing:","kind":"identifier"}],"roleHeading":"Instance Method","modules":[{"name":"Airwallex"}],"title":"paymentElement(_:onProcessingStateChangedFor:isProcessing:)"},"abstract":[{"text":"Called when payment processing state changes.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxpaymentelementdelegate\/paymentelement(_:onprocessingstatechangedfor:isprocessing:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxpaymentelementdelegate\/paymentelement(_:onprocessingstatechangedfor:isprocessing:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElementDelegate"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElementDelegate\/paymentElement(_:onProcessingStateChangedFor:isProcessing:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentElement","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"element","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"AWXPaymentElement","preciseIdentifier":"c:@M@Airwallex@objc(cs)AWXPaymentElement","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement"},{"text":", ","kind":"text"},{"text":"onProcessingStateChangedFor","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"paymentMethod","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"isProcessing","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"element","content":[{"type":"paragraph","inlineContent":[{"text":"The payment element.","type":"text"}]}]},{"name":"paymentMethod","content":[{"type":"paragraph","inlineContent":[{"text":"The name of the payment method being used (e.g., “card”, “applepay”).","type":"text"}]}]},{"name":"isProcessing","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"code":"true","type":"codeVoice"},{"text":" when payment starts, ","type":"text"},{"code":"false","type":"codeVoice"},{"text":" when payment ends.","type":"text"}]}]}]},{"kind":"content","content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Implement this method to display a custom loading indicator during payment processing."},{"type":"text","text":" "},{"type":"text","text":"This method is called with "},{"type":"codeVoice","code":"isProcessing: true"},{"type":"text","text":" when payment starts, and"},{"type":"text","text":" "},{"type":"codeVoice","code":"isProcessing: false"},{"type":"text","text":" when payment completes (before "},{"type":"codeVoice","code":"didCompleteFor"},{"type":"text","text":" is called)."},{"type":"text","text":" "},{"type":"text","text":"If this method is not implemented, a default loading indicator will be shown."}]}]}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","abstract":[],"type":"topic","kind":"symbol","title":"Airwallex","role":"collection"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElementDelegate/paymentElement(_:onProcessingStateChangedFor:isProcessing:)":{"title":"paymentElement(_:onProcessingStateChangedFor:isProcessing:)","type":"topic","abstract":[{"type":"text","text":"Called when payment processing state changes."}],"url":"\/documentation\/airwallex\/awxpaymentelementdelegate\/paymentelement(_:onprocessingstatechangedfor:isprocessing:)","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElementDelegate\/paymentElement(_:onProcessingStateChangedFor:isProcessing:)","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"paymentElement:onProcessingStateChangedFor:isProcessing:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentElement"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@Airwallex@objc(cs)AWXPaymentElement","text":"AWXPaymentElement"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onProcessingStateChangedFor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isProcessing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement":{"abstract":[{"text":"An embeddable payment element that can be added to any view hierarchy.","type":"text"}],"title":"AWXPaymentElement","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement","navigatorTitle":[{"kind":"identifier","text":"AWXPaymentElement"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentElement"}],"kind":"symbol","url":"\/documentation\/airwallex\/awxpaymentelement","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElementDelegate":{"abstract":[{"text":"Delegate protocol for receiving payment events from AWXPaymentElement.","type":"text"}],"title":"AWXPaymentElementDelegate","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElementDelegate","navigatorTitle":[{"kind":"identifier","text":"AWXPaymentElementDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentElementDelegate"}],"kind":"symbol","url":"\/documentation\/airwallex\/awxpaymentelementdelegate","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"paymentElement:onProcessingStateChangedFor:isProcessing:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentElement:onProcessingStateChangedFor:isProcessing:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"paymentElement:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement","text":"AWXPaymentElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@Airwallex@objc(cs)AWXPaymentElement"},{"text":" *) ","kind":"text"},{"text":"element","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"onProcessingStateChangedFor:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"paymentMethod","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"isProcessing:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"text":"isProcessing","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The payment element.","type":"text"}]}],"name":"element"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The name of the payment method being used (e.g., “card”, “applepay”).","type":"text"}]}],"name":"paymentMethod"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"true"},{"type":"text","text":" when payment starts, "},{"type":"codeVoice","code":"false"},{"type":"text","text":" when payment ends."}]}],"name":"isProcessing"}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"op":"replace","value":"paymentElement:onProcessingStateChangedFor:isProcessing:","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElementDelegate~1paymentElement(_:onProcessingStateChangedFor:isProcessing:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElementDelegate~1paymentElement(_:onProcessingStateChangedFor:isProcessing:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentElement:onProcessingStateChangedFor:isProcessing:"}]},{"op":"replace","value":"AWXPaymentElement","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AWXPaymentElement"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AWXPaymentElement"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/navigatorTitle"},{"op":"replace","value":"AWXPaymentElementDelegate","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElementDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AWXPaymentElementDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElementDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AWXPaymentElementDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElementDelegate\/navigatorTitle"}]}]}