{"sections":[],"metadata":{"externalID":"c:@M@Airwallex@objc(pl)PaymentIntentProvider(im)createPaymentIntentWithCompletionHandler:","navigatorTitle":[{"text":"createPaymentIntentWithCompletionHandler:","kind":"identifier"}],"title":"createPaymentIntent()","role":"symbol","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"createPaymentIntent","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"preciseIdentifier":"c:objc(cs)AWXPaymentIntent","kind":"typeIdentifier","text":"AWXPaymentIntent"}],"required":true,"modules":[{"name":"Airwallex"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"createPaymentIntent","kind":"identifier"},{"kind":"text","text":"() "},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"text":"AWXPaymentIntent","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent","preciseIdentifier":"c:objc(cs)AWXPaymentIntent","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"anchor":"return-value","text":"Return Value","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"A fully initialized "},{"code":"AWXPaymentIntent","type":"codeVoice"},{"type":"text","text":" object"}]}],"kind":"content"},{"kind":"content","content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"inlineContent":[{"type":"text","text":"This method is called by the SDK when the payment intent is needed, typically just"},{"type":"text","text":" "},{"type":"text","text":"before payment confirmation. Implement this method to call your backend API and"},{"text":" ","type":"text"},{"type":"text","text":"create a payment intent with the Airwallex API."}],"type":"paragraph"},{"type":"heading","text":"Important","anchor":"Important","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"The returned payment intent must have:"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"code":"amount","type":"codeVoice"},{"text":" matching the ","type":"text"},{"code":"amount","type":"codeVoice"},{"text":" property","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":"currency"},{"type":"text","text":" matching the "},{"code":"currency","type":"codeVoice"},{"text":" property","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"code":"customerId","type":"codeVoice"},{"type":"text","text":" matching the "},{"type":"codeVoice","code":"customerId"},{"text":" property (if not nil)","type":"text"}]}]}]},{"inlineContent":[{"text":"If these values don’t match, the SDK will throw a validation error.","type":"text"}],"type":"paragraph"},{"type":"aside","content":[{"inlineContent":[{"text":"Any error that occurs during payment intent creation (e.g., network errors,","type":"text"},{"text":" ","type":"text"},{"text":"API errors). The error will be propagated to the payment flow.","type":"text"}],"type":"paragraph"}],"style":"note","name":"Throws"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentIntentProvider\/createPaymentIntent()","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/airwallex\/paymentintentprovider\/createpaymentintent()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/paymentintentprovider\/createpaymentintent()"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","abstract":[{"type":"text","text":"Creates a payment intent asynchronously."}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentIntentProvider"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentIntentProvider":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentIntentProvider","abstract":[{"text":"A protocol for providing payment intents on-demand during the payment flow.","type":"text"}],"url":"\/documentation\/airwallex\/paymentintentprovider","title":"PaymentIntentProvider","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentIntentProvider"}],"navigatorTitle":[{"kind":"identifier","text":"PaymentIntentProvider"}],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","title":"Airwallex","abstract":[],"type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentIntent":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent","abstract":[{"code":"AWXPaymentIntent","type":"codeVoice"},{"type":"text","text":" includes the information of payment intent."}],"url":"\/documentation\/airwallex\/awxpaymentintent","title":"AWXPaymentIntent","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPaymentIntent","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AWXPaymentIntent"}],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentIntentProvider/createPaymentIntent()":{"kind":"symbol","type":"topic","title":"createPaymentIntent()","navigatorTitle":[{"kind":"identifier","text":"createPaymentIntentWithCompletionHandler:"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentIntentProvider\/createPaymentIntent()","url":"\/documentation\/airwallex\/paymentintentprovider\/createpaymentintent()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createPaymentIntent","kind":"identifier"},{"kind":"text","text":"() "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"AWXPaymentIntent","preciseIdentifier":"c:objc(cs)AWXPaymentIntent"}],"abstract":[{"type":"text","text":"Creates a payment intent asynchronously."}],"required":true}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"createPaymentIntentWithCompletionHandler:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"createPaymentIntentWithCompletionHandler:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"createPaymentIntentWithCompletionHandler:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":" (^)(","kind":"text"},{"text":"AWXPaymentIntent","preciseIdentifier":"c:objc(cs)AWXPaymentIntent","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completionHandler","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":null,"path":"\/primaryContentSections\/1","op":"replace"},{"value":"PaymentIntentProvider","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentIntentProvider\/title","op":"replace"},{"op":"replace","value":[{"text":"PaymentIntentProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentIntentProvider\/fragments"},{"op":"replace","value":[{"text":"PaymentIntentProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentIntentProvider\/navigatorTitle"},{"op":"replace","value":"AWXPaymentIntent","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentIntent\/title"},{"op":"replace","value":[{"text":"AWXPaymentIntent","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentIntent\/fragments"},{"op":"replace","value":[{"text":"AWXPaymentIntent","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentIntent\/navigatorTitle"},{"op":"replace","value":"createPaymentIntentWithCompletionHandler:","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentIntentProvider~1createPaymentIntent()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"createPaymentIntentWithCompletionHandler:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentIntentProvider~1createPaymentIntent()\/fragments"}]}]}