{"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexNextTriggerByType","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/airwallex\/airwallexnexttriggerbytype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/airwallexnexttriggerbytype"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexNextTriggerByType\/customerType","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexNextTriggerByType\/merchantType"],"title":"Enumeration Cases","anchor":"Enumeration-Cases"},{"generated":true,"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexNextTriggerByType\/init(rawValue:)"],"title":"Initializers","anchor":"Initializers"},{"generated":true,"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexNextTriggerByType\/Equatable-Implementations","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexNextTriggerByType\/RawRepresentable-Implementations"],"title":"Default Implementations","anchor":"Default-Implementations"}],"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.Airwallex\/s15BitwiseCopyableP","doc:\/\/org.cocoapods.Airwallex\/SQ","doc:\/\/org.cocoapods.Airwallex\/SH","doc:\/\/org.cocoapods.Airwallex\/SY","doc:\/\/org.cocoapods.Airwallex\/s8SendableP","doc:\/\/org.cocoapods.Airwallex\/s16SendableMetatypeP"]}],"metadata":{"symbolKind":"enum","title":"AirwallexNextTriggerByType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AirwallexNextTriggerByType","kind":"identifier"}],"modules":[{"name":"Airwallex"}],"roleHeading":"Enumeration","externalID":"c:@E@AirwallexNextTriggerByType","role":"symbol","navigatorTitle":[{"text":"AirwallexNextTriggerByType","kind":"identifier"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AirwallexNextTriggerByType","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","references":{"doc://org.cocoapods.Airwallex/SH":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://org.cocoapods.Airwallex/s8SendableP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://org.cocoapods.Airwallex/s16SendableMetatypeP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s16SendableMetatypeP","title":"Swift.SendableMetatype","type":"unresolvable"},"doc://org.cocoapods.Airwallex/s15BitwiseCopyableP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s15BitwiseCopyableP","title":"Swift.BitwiseCopyable","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","type":"topic","url":"\/documentation\/airwallex","kind":"symbol","abstract":[],"title":"Airwallex"},"doc://org.cocoapods.Airwallex/SQ":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexNextTriggerByType/Equatable-Implementations":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexNextTriggerByType\/Equatable-Implementations","title":"Equatable Implementations","kind":"article","abstract":[],"url":"\/documentation\/airwallex\/airwallexnexttriggerbytype\/equatable-implementations","type":"topic","role":"collectionGroup"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexNextTriggerByType/merchantType":{"kind":"symbol","title":"AirwallexNextTriggerByType.merchantType","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"merchantType","kind":"identifier"}],"navigatorTitle":[{"text":"AirwallexNextTriggerByMerchantType","kind":"identifier"}],"url":"\/documentation\/airwallex\/airwallexnexttriggerbytype\/merchanttype","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexNextTriggerByType\/merchantType"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexNextTriggerByType/customerType":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexNextTriggerByType\/customerType","title":"AirwallexNextTriggerByType.customerType","type":"topic","role":"symbol","abstract":[],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customerType","kind":"identifier"}],"url":"\/documentation\/airwallex\/airwallexnexttriggerbytype\/customertype","navigatorTitle":[{"text":"AirwallexNextTriggerByCustomerType","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexNextTriggerByType/init(rawValue:)":{"abstract":[],"kind":"symbol","title":"init(rawValue:)","type":"topic","url":"\/documentation\/airwallex\/airwallexnexttriggerbytype\/init(rawvalue:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexNextTriggerByType\/init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":")","kind":"text"}]},"doc://org.cocoapods.Airwallex/SY":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexNextTriggerByType/RawRepresentable-Implementations":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexNextTriggerByType\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","kind":"article","abstract":[],"url":"\/documentation\/airwallex\/airwallexnexttriggerbytype\/rawrepresentable-implementations","type":"topic","role":"collectionGroup"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexNextTriggerByType":{"url":"\/documentation\/airwallex\/airwallexnexttriggerbytype","abstract":[],"title":"AirwallexNextTriggerByType","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AirwallexNextTriggerByType"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexNextTriggerByType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AirwallexNextTriggerByType"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","value":"AirwallexNextTriggerByType","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"AirwallexNextTriggerByType","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"AirwallexNextTriggerByType","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexNextTriggerByType\/customerType","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexNextTriggerByType\/merchantType"],"generated":true}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AirwallexNextTriggerByType","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexNextTriggerByType~1merchantType\/title","value":"AirwallexNextTriggerByMerchantType","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexNextTriggerByType~1merchantType\/fragments","value":[{"text":"AirwallexNextTriggerByMerchantType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexNextTriggerByType~1customerType\/title","value":"AirwallexNextTriggerByCustomerType","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexNextTriggerByType~1customerType\/fragments","value":[{"text":"AirwallexNextTriggerByCustomerType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexNextTriggerByType\/title","value":"AirwallexNextTriggerByType","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexNextTriggerByType\/fragments","value":[{"kind":"identifier","text":"AirwallexNextTriggerByType"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexNextTriggerByType\/navigatorTitle","value":[{"text":"AirwallexNextTriggerByType","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}