{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentRequest"},"metadata":{"externalID":"c:objc(cs)AWXConfirmPaymentIntentRequest","title":"AWXConfirmPaymentIntentRequest","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXConfirmPaymentIntentRequest","kind":"identifier"}],"symbolKind":"class","role":"symbol","roleHeading":"Class","modules":[{"name":"Airwallex"}],"navigatorTitle":[{"text":"AWXConfirmPaymentIntentRequest","kind":"identifier"}]},"abstract":[{"code":"AWXConfirmPaymentIntentRequest","type":"codeVoice"},{"text":" includes all of the parameters needed to confirm payment intent.","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXConfirmPaymentIntentRequest","kind":"identifier"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRequest"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/SQ","doc:\/\/org.cocoapods.Airwallex\/SH"],"type":"conformsTo"}],"topicSections":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentRequest\/consentOptions","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentRequest\/customerId","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentRequest\/device","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentRequest\/intentId","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentRequest\/options","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentRequest\/paymentConsent","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentRequest\/paymentMethod","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentRequest\/returnURL","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentRequest\/savePaymentMethod"]}],"variants":[{"paths":["\/documentation\/airwallex\/awxconfirmpaymentintentrequest"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxconfirmpaymentintentrequest"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.Airwallex/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.Airwallex/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXConfirmPaymentIntentRequest/paymentConsent":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentRequest\/paymentConsent","kind":"symbol","title":"paymentConsent","type":"topic","url":"\/documentation\/airwallex\/awxconfirmpaymentintentrequest\/paymentconsent","abstract":[{"text":"PaymentConsent method object.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentConsent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWXPaymentConsent","preciseIdentifier":"c:objc(cs)AWXPaymentConsent"},{"kind":"text","text":"?"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"paymentConsent"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXConfirmPaymentIntentRequest/intentId":{"abstract":[{"text":"Intent ID.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentRequest\/intentId","url":"\/documentation\/airwallex\/awxconfirmpaymentintentrequest\/intentid","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"intentId"}],"title":"intentId","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"intentId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXConfirmPaymentIntentRequest/savePaymentMethod":{"type":"topic","abstract":[{"text":"Save payment method.","type":"text"}],"url":"\/documentation\/airwallex\/awxconfirmpaymentintentrequest\/savepaymentmethod","navigatorTitle":[{"kind":"identifier","text":"savePaymentMethod"}],"kind":"symbol","role":"symbol","title":"savePaymentMethod","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentRequest\/savePaymentMethod","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"savePaymentMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"deprecated":true},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXConfirmPaymentIntentRequest/consentOptions":{"url":"\/documentation\/airwallex\/awxconfirmpaymentintentrequest\/consentoptions","abstract":[{"text":"object for simplified consent flow","type":"text"},{"text":" ","type":"text"},{"text":"info for The associated PaymentConsent to set up along with the PaymentIntent.","type":"text"}],"title":"consentOptions","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"consentOptions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentRequest\/consentOptions","type":"topic","navigatorTitle":[{"kind":"identifier","text":"consentOptions"}]},"doc://org.cocoapods.Airwallex/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SQ"},"doc://org.cocoapods.Airwallex/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SH"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRequest":{"url":"\/documentation\/airwallex\/awxrequest","navigatorTitle":[{"kind":"identifier","text":"AWXRequest"}],"title":"AWXRequest","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRequest","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXRequest"}],"abstract":[],"type":"topic","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXConfirmPaymentIntentRequest/customerId":{"url":"\/documentation\/airwallex\/awxconfirmpaymentintentrequest\/customerid","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customerId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentRequest\/customerId","abstract":[{"text":"Customer ID.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"customerId"}],"title":"customerId","kind":"symbol","role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXConfirmPaymentIntentRequest/options":{"abstract":[{"text":"Options object.","type":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentRequest\/options","type":"topic","url":"\/documentation\/airwallex\/awxconfirmpaymentintentrequest\/options","navigatorTitle":[{"kind":"identifier","text":"options"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPaymentMethodOptions","text":"AWXPaymentMethodOptions"},{"kind":"text","text":"?"}],"title":"options"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXConfirmPaymentIntentRequest/device":{"kind":"symbol","title":"device","abstract":[{"text":"Device object.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"device"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentRequest\/device","type":"topic","url":"\/documentation\/airwallex\/awxconfirmpaymentintentrequest\/device","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"device"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXDevice","text":"AWXDevice"},{"kind":"text","text":"?"}]},"doc://org.cocoapods.Airwallex/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXConfirmPaymentIntentRequest/paymentMethod":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWXPaymentMethod","preciseIdentifier":"c:objc(cs)AWXPaymentMethod"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentRequest\/paymentMethod","title":"paymentMethod","type":"topic","navigatorTitle":[{"kind":"identifier","text":"paymentMethod"}],"abstract":[{"type":"text","text":"Payment method object."}],"url":"\/documentation\/airwallex\/awxconfirmpaymentintentrequest\/paymentmethod","kind":"symbol"},"doc://org.cocoapods.Airwallex/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXConfirmPaymentIntentRequest/returnURL":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentRequest\/returnURL","url":"\/documentation\/airwallex\/awxconfirmpaymentintentrequest\/returnurl","title":"returnURL","kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Return url (only be valid for recurring)"}],"navigatorTitle":[{"kind":"identifier","text":"returnURL"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"returnURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","type":"topic","url":"\/documentation\/airwallex","kind":"symbol","abstract":[],"title":"Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXConfirmPaymentIntentRequest":{"type":"topic","navigatorTitle":[{"text":"AWXConfirmPaymentIntentRequest","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentRequest","abstract":[{"type":"codeVoice","code":"AWXConfirmPaymentIntentRequest"},{"type":"text","text":" includes all of the parameters needed to confirm payment intent."}],"url":"\/documentation\/airwallex\/awxconfirmpaymentintentrequest","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXConfirmPaymentIntentRequest","kind":"identifier"}],"title":"AWXConfirmPaymentIntentRequest"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"AWXConfirmPaymentIntentRequest","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"AWXConfirmPaymentIntentRequest"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"AWXConfirmPaymentIntentRequest","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentRequest\/consentOptions","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentRequest\/customerId","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentRequest\/device","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentRequest\/intentId","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentRequest\/options","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentRequest\/paymentConsent","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentRequest\/paymentMethod","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentRequest\/returnURL","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentRequest\/savePaymentMethod"],"anchor":"Instance-Properties"}],"op":"replace","path":"\/topicSections"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRequest"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXConfirmPaymentIntentRequest","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AWXRequest","text":"AWXRequest","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRequest"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentRequest~1paymentConsent\/title","value":"paymentConsent","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentRequest~1paymentConsent\/fragments","value":[{"kind":"identifier","text":"paymentConsent"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentRequest~1intentId\/title","value":"intentId","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentRequest~1intentId\/fragments","value":[{"text":"intentId","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentRequest~1savePaymentMethod\/title","value":"savePaymentMethod","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentRequest~1savePaymentMethod\/fragments","value":[{"text":"savePaymentMethod","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentRequest~1consentOptions\/title","value":"consentOptions","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentRequest~1consentOptions\/fragments","value":[{"kind":"identifier","text":"consentOptions"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRequest\/title","value":"AWXRequest","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRequest\/fragments","value":[{"kind":"identifier","text":"AWXRequest"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRequest\/navigatorTitle","value":[{"kind":"identifier","text":"AWXRequest"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentRequest~1customerId\/title","value":"customerId","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentRequest~1customerId\/fragments","value":[{"kind":"identifier","text":"customerId"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentRequest~1options\/title","value":"options","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentRequest~1options\/fragments","value":[{"kind":"identifier","text":"options"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentRequest~1device\/title","value":"device","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentRequest~1device\/fragments","value":[{"text":"device","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentRequest~1paymentMethod\/title","value":"paymentMethod","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentRequest~1paymentMethod\/fragments","value":[{"kind":"identifier","text":"paymentMethod"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentRequest~1returnURL\/title","value":"returnURL","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentRequest~1returnURL\/fragments","value":[{"kind":"identifier","text":"returnURL"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentRequest\/title","value":"AWXConfirmPaymentIntentRequest","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentRequest\/fragments","value":[{"kind":"identifier","text":"AWXConfirmPaymentIntentRequest"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentRequest\/navigatorTitle","value":[{"kind":"identifier","text":"AWXConfirmPaymentIntentRequest"}],"op":"replace"}]}]}