{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/classtohandlenextactionfortype(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/classtohandlenextactionfortype(_:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ClassToHandleNextActionForType","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"nextAction","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"AWXConfirmPaymentNextAction","preciseIdentifier":"c:objc(cs)AWXConfirmPaymentNextAction","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentNextAction","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"AnyClass","preciseIdentifier":"s:s8AnyClassa","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/ClassToHandleNextActionForType(_:)","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Function","symbolKind":"func","externalID":"c:@F@ClassToHandleNextActionForType","title":"ClassToHandleNextActionForType(_:)","navigatorTitle":[{"text":"ClassToHandleNextActionForType","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ClassToHandleNextActionForType","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AWXConfirmPaymentNextAction","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXConfirmPaymentNextAction"},{"text":") -> ","kind":"text"},{"text":"AnyClass","kind":"typeIdentifier","preciseIdentifier":"s:s8AnyClassa"}],"role":"symbol","modules":[{"name":"Airwallex"}]},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/ClassToHandleNextActionForType(_:)":{"role":"symbol","navigatorTitle":[{"text":"ClassToHandleNextActionForType","kind":"identifier"}],"title":"ClassToHandleNextActionForType(_:)","kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/ClassToHandleNextActionForType(_:)","url":"\/documentation\/airwallex\/classtohandlenextactionfortype(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ClassToHandleNextActionForType","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AWXConfirmPaymentNextAction","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXConfirmPaymentNextAction"},{"text":") -> ","kind":"text"},{"text":"AnyClass","kind":"typeIdentifier","preciseIdentifier":"s:s8AnyClassa"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXConfirmPaymentNextAction":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXConfirmPaymentNextAction"}],"type":"topic","abstract":[{"type":"codeVoice","code":"AWXConfirmPaymentNextAction"},{"type":"text","text":" includes the parameters for next action."}],"navigatorTitle":[{"kind":"identifier","text":"AWXConfirmPaymentNextAction"}],"role":"symbol","url":"\/documentation\/airwallex\/awxconfirmpaymentnextaction","title":"AWXConfirmPaymentNextAction","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentNextAction"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","type":"topic","url":"\/documentation\/airwallex","kind":"symbol","abstract":[],"title":"Airwallex"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Function"},{"op":"replace","path":"\/metadata\/title","value":"ClassToHandleNextActionForType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"func"},{"value":[{"kind":"identifier","text":"ClassToHandleNextActionForType"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Class","kind":"typeIdentifier","preciseIdentifier":"c:@T@Class"},{"text":" ","kind":"text"},{"text":"ClassToHandleNextActionForType","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentNextAction","text":"AWXConfirmPaymentNextAction","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXConfirmPaymentNextAction"},{"text":" * ","kind":"text"},{"text":"nextAction","kind":"internalParam"},{"text":");","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ClassToHandleNextActionForType","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1ClassToHandleNextActionForType(_:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1ClassToHandleNextActionForType(_:)\/fragments","op":"replace","value":[{"kind":"identifier","text":"ClassToHandleNextActionForType"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentNextAction\/title","op":"replace","value":"AWXConfirmPaymentNextAction"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentNextAction\/fragments","op":"replace","value":[{"kind":"identifier","text":"AWXConfirmPaymentNextAction"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentNextAction\/navigatorTitle","op":"replace","value":[{"text":"AWXConfirmPaymentNextAction","kind":"identifier"}]}]}]}