{"kind":"symbol","metadata":{"modules":[{"name":"Airwallex"}],"navigatorTitle":[{"kind":"identifier","text":"firstPaymentAmount"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"firstPaymentAmount","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDecimalNumber","text":"NSDecimalNumber"},{"kind":"text","text":"?"}],"role":"symbol","roleHeading":"Instance Property","externalID":"c:@M@Airwallex@objc(cs)TermsOfUse(py)firstPaymentAmount","title":"firstPaymentAmount","symbolKind":"property"},"abstract":[{"type":"text","text":"The first payment. It could include the costs associated with the first debited amount."},{"type":"text","text":" "},{"type":"text","text":"Optional if payment agreement type is VARIABLE."}],"variants":[{"paths":["\/documentation\/airwallex\/termsofuse\/firstpaymentamount"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/termsofuse\/firstpaymentamount"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"firstPaymentAmount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSDecimalNumber","preciseIdentifier":"c:objc(cs)NSDecimalNumber"},{"kind":"text","text":"?"}]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/TermsOfUse"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/TermsOfUse\/firstPaymentAmount"},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/TermsOfUse":{"navigatorTitle":[{"text":"TermsOfUse","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TermsOfUse","kind":"identifier"}],"title":"TermsOfUse","abstract":[{"text":"Terms to specify how this Payment Consent will be used","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/TermsOfUse","url":"\/documentation\/airwallex\/termsofuse","role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/TermsOfUse/firstPaymentAmount":{"navigatorTitle":[{"text":"firstPaymentAmount","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"firstPaymentAmount","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSDecimalNumber","preciseIdentifier":"c:objc(cs)NSDecimalNumber","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"The first payment. It could include the costs associated with the first debited amount."},{"type":"text","text":" "},{"type":"text","text":"Optional if payment agreement type is VARIABLE."}],"title":"firstPaymentAmount","kind":"symbol","type":"topic","url":"\/documentation\/airwallex\/termsofuse\/firstpaymentamount","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/TermsOfUse\/firstPaymentAmount","role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"kind":"symbol","abstract":[],"role":"collection","type":"topic","url":"\/documentation\/airwallex","title":"Airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"firstPaymentAmount"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"firstPaymentAmount"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSDecimalNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDecimalNumber"},{"text":" * ","kind":"text"},{"text":"firstPaymentAmount","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"TermsOfUse","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1TermsOfUse\/title"},{"op":"replace","value":[{"text":"TermsOfUse","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1TermsOfUse\/fragments"},{"op":"replace","value":[{"text":"TermsOfUse","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1TermsOfUse\/navigatorTitle"},{"op":"replace","value":"firstPaymentAmount","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1TermsOfUse~1firstPaymentAmount\/title"},{"op":"replace","value":[{"text":"firstPaymentAmount","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1TermsOfUse~1firstPaymentAmount\/fragments"}]}]}