{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"minPaymentAmount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSDecimalNumber","preciseIdentifier":"c:objc(cs)NSDecimalNumber"},{"kind":"text","text":"?"}],"languages":["swift"]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/TermsOfUse\/minPaymentAmount","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/airwallex\/termsofuse\/minpaymentamount"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/termsofuse\/minpaymentamount"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"The minimum payment amount that can be charged for a single payment."},{"type":"text","text":" "},{"type":"text","text":"Optional if payment agreement type is VARIABLE."}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/TermsOfUse"]]},"sections":[],"metadata":{"role":"symbol","roleHeading":"Instance Property","modules":[{"name":"Airwallex"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"minPaymentAmount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSDecimalNumber","preciseIdentifier":"c:objc(cs)NSDecimalNumber"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"minPaymentAmount"}],"externalID":"c:@M@Airwallex@objc(cs)TermsOfUse(py)minPaymentAmount","title":"minPaymentAmount"},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/TermsOfUse":{"url":"\/documentation\/airwallex\/termsofuse","title":"TermsOfUse","abstract":[{"type":"text","text":"Terms to specify how this Payment Consent will be used"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TermsOfUse","kind":"identifier"}],"navigatorTitle":[{"text":"TermsOfUse","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/TermsOfUse","type":"topic","role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/TermsOfUse/minPaymentAmount":{"url":"\/documentation\/airwallex\/termsofuse\/minpaymentamount","type":"topic","kind":"symbol","title":"minPaymentAmount","role":"symbol","abstract":[{"type":"text","text":"The minimum payment amount that can be charged for a single payment."},{"type":"text","text":" "},{"type":"text","text":"Optional if payment agreement type is VARIABLE."}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minPaymentAmount","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSDecimalNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDecimalNumber"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"minPaymentAmount","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/TermsOfUse\/minPaymentAmount"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","url":"\/documentation\/airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","kind":"symbol","role":"collection","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"minPaymentAmount"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"minPaymentAmount"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSDecimalNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDecimalNumber"},{"text":" * ","kind":"text"},{"text":"minPaymentAmount","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1TermsOfUse\/title","value":"TermsOfUse"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1TermsOfUse\/fragments","value":[{"kind":"identifier","text":"TermsOfUse"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1TermsOfUse\/navigatorTitle","value":[{"kind":"identifier","text":"TermsOfUse"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1TermsOfUse~1minPaymentAmount\/title","value":"minPaymentAmount"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1TermsOfUse~1minPaymentAmount\/fragments","value":[{"kind":"identifier","text":"minPaymentAmount"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}