{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/TermsOfUse"]]},"abstract":[{"text":"The agreed type of amounts for subsequent payment. Should be one of FIXED, VARIABLE.","type":"text"}],"variants":[{"paths":["\/documentation\/airwallex\/termsofuse\/paymentamounttype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/termsofuse\/paymentamounttype"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"modules":[{"name":"Airwallex"}],"role":"symbol","externalID":"c:@M@Airwallex@objc(cs)TermsOfUse(py)paymentAmountType","symbolKind":"property","title":"paymentAmountType","roleHeading":"Instance Property","navigatorTitle":[{"text":"paymentAmountType","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentAmountType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@Airwallex@E@PaymentAmountType","text":"PaymentAmountType"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentAmountType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PaymentAmountType","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentAmountType","kind":"typeIdentifier","preciseIdentifier":"c:@M@Airwallex@E@PaymentAmountType"}]}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/TermsOfUse\/paymentAmountType"},"kind":"symbol","references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/airwallex","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/TermsOfUse":{"abstract":[{"text":"Terms to specify how this Payment Consent will be used","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TermsOfUse"}],"navigatorTitle":[{"kind":"identifier","text":"TermsOfUse"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/TermsOfUse","kind":"symbol","title":"TermsOfUse","role":"symbol","url":"\/documentation\/airwallex\/termsofuse"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/TermsOfUse/paymentAmountType":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/TermsOfUse\/paymentAmountType","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentAmountType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PaymentAmountType","preciseIdentifier":"c:@M@Airwallex@E@PaymentAmountType"}],"kind":"symbol","type":"topic","title":"paymentAmountType","url":"\/documentation\/airwallex\/termsofuse\/paymentamounttype","abstract":[{"type":"text","text":"The agreed type of amounts for subsequent payment. Should be one of FIXED, VARIABLE."}],"navigatorTitle":[{"kind":"identifier","text":"paymentAmountType"}],"role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentAmountType":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentAmountType","kind":"symbol","type":"topic","navigatorTitle":[{"text":"PaymentAmountType","kind":"identifier"}],"url":"\/documentation\/airwallex\/paymentamounttype","title":"PaymentAmountType","abstract":[{"type":"text","text":"Payment amount type enumeration"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PaymentAmountType","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"paymentAmountType","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"paymentAmountType","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"PaymentAmountType","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentAmountType","preciseIdentifier":"c:@M@Airwallex@E@PaymentAmountType"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentAmountType"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1TermsOfUse\/title","value":"TermsOfUse","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1TermsOfUse\/fragments","value":[{"kind":"identifier","text":"TermsOfUse"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1TermsOfUse\/navigatorTitle","value":[{"text":"TermsOfUse","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1TermsOfUse~1paymentAmountType\/title","value":"paymentAmountType","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1TermsOfUse~1paymentAmountType\/fragments","value":[{"text":"paymentAmountType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentAmountType\/title","value":"PaymentAmountType","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentAmountType\/fragments","value":[{"kind":"identifier","text":"PaymentAmountType"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentAmountType\/navigatorTitle","value":[{"kind":"identifier","text":"PaymentAmountType"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}