{"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"The total number of billing cycles."},{"type":"text","text":" "},{"type":"text","text":"The mandate will continue indefinitely if totalBillingCycles is null."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/termsofuse\/totalbillingcycles"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/termsofuse\/totalbillingcycles"]}],"metadata":{"modules":[{"name":"Airwallex"}],"title":"totalBillingCycles","navigatorTitle":[{"kind":"identifier","text":"totalBillingCycles"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"totalBillingCycles"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"externalID":"c:@M@Airwallex@objc(cs)TermsOfUse(py)totalBillingCycles","role":"symbol","roleHeading":"Instance Property"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/TermsOfUse\/totalBillingCycles"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"totalBillingCycles"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/TermsOfUse"]]},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","role":"collection","url":"\/documentation\/airwallex","kind":"symbol","title":"Airwallex","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/TermsOfUse/totalBillingCycles":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The total number of billing cycles."},{"type":"text","text":" "},{"type":"text","text":"The mandate will continue indefinitely if totalBillingCycles is null."}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/TermsOfUse\/totalBillingCycles","url":"\/documentation\/airwallex\/termsofuse\/totalbillingcycles","title":"totalBillingCycles","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"totalBillingCycles","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"totalBillingCycles","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/TermsOfUse":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TermsOfUse","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TermsOfUse"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/TermsOfUse","title":"TermsOfUse","abstract":[{"type":"text","text":"Terms to specify how this Payment Consent will be used"}],"url":"\/documentation\/airwallex\/termsofuse","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"totalBillingCycles"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"totalBillingCycles"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":" ","kind":"text"},{"text":"totalBillingCycles","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1TermsOfUse~1totalBillingCycles\/title","op":"replace","value":"totalBillingCycles"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1TermsOfUse~1totalBillingCycles\/fragments","op":"replace","value":[{"text":"totalBillingCycles","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1TermsOfUse\/title","op":"replace","value":"TermsOfUse"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1TermsOfUse\/fragments","op":"replace","value":[{"text":"TermsOfUse","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1TermsOfUse\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TermsOfUse"}]}]}]}