{"kind":"symbol","metadata":{"modules":[{"name":"Airwallex"}],"externalID":"s:So11AWXFormTypeV8rawValueABSgSu_tcfc","title":"init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","symbolKind":"init","roleHeading":"Initializer"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXFormType\/init(rawValue:)"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXFormType"]]},"variants":[{"paths":["\/documentation\/airwallex\/awxformtype\/init(rawvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXFormType":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXFormType","role":"symbol","navigatorTitle":[{"text":"AWXFormType","kind":"identifier"}],"abstract":[],"title":"AWXFormType","type":"topic","url":"\/documentation\/airwallex\/awxformtype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXFormType","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXFormType/init(rawValue:)":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXFormType\/init(rawValue:)","type":"topic","kind":"symbol","abstract":[],"url":"\/documentation\/airwallex\/awxformtype\/init(rawvalue:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"title":"init(rawValue:)"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol","type":"topic","url":"\/documentation\/airwallex","role":"collection","abstract":[],"title":"Airwallex"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXFormType\/title","value":"AWXFormType"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXFormType\/fragments","value":[{"kind":"identifier","text":"AWXFormType"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXFormType\/navigatorTitle","value":[{"text":"AWXFormType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}