{"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand\/amex","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"amex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand","text":"AWXCardBrand","preciseIdentifier":"c:AWXConstants.h@T@AWXCardBrand"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"variants":[{"paths":["\/documentation\/airwallex\/awxcardbrand\/amex"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxcardbrand\/amex"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"amex","roleHeading":"Type Property","extendedModule":"Airwallex","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"amex","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWXCardBrand","kind":"typeIdentifier","preciseIdentifier":"c:AWXConstants.h@T@AWXCardBrand"}],"externalID":"c:@AWXCardBrandAmex","modules":[{"name":"Airwallex"}],"navigatorTitle":[{"text":"AWXCardBrandAmex","kind":"identifier"}],"symbolKind":"property"},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardBrand":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand","url":"\/documentation\/airwallex\/awxcardbrand","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXCardBrand"}],"type":"topic","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"AWXCardBrand"}],"title":"AWXCardBrand"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardBrand/amex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand\/amex","type":"topic","navigatorTitle":[{"text":"AWXCardBrandAmex","kind":"identifier"}],"title":"amex","abstract":[],"role":"symbol","url":"\/documentation\/airwallex\/awxcardbrand\/amex","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"amex","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:AWXConstants.h@T@AWXCardBrand","text":"AWXCardBrand","kind":"typeIdentifier"}],"kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"abstract":[],"type":"topic","url":"\/documentation\/airwallex","title":"Airwallex","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Global Variable","path":"\/metadata\/roleHeading","op":"replace"},{"value":"AWXCardBrandAmex","path":"\/metadata\/title","op":"replace"},{"value":"var","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"AWXCardBrandAmex"}],"path":"\/metadata\/fragments","op":"replace"},{"value":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"path":"\/hierarchy","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand","preciseIdentifier":"c:AWXConstants.h@T@AWXCardBrand","text":"AWXCardBrand"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXCardBrandAmex"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"AWXCardBrand","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardBrand\/title","op":"replace"},{"value":[{"text":"AWXCardBrand","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardBrand\/fragments","op":"replace"},{"value":[{"text":"AWXCardBrand","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardBrand\/navigatorTitle","op":"replace"},{"value":"AWXCardBrandAmex","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardBrand~1amex\/title","op":"replace"},{"value":[{"text":"AWXCardBrandAmex","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardBrand~1amex\/fragments","op":"replace"}]}]}