{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand\/discover"},"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"discover","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:AWXConstants.h@T@AWXCardBrand","text":"AWXCardBrand","kind":"typeIdentifier"}],"title":"discover","extendedModule":"Airwallex","role":"symbol","roleHeading":"Type Property","symbolKind":"property","navigatorTitle":[{"text":"AWXCardBrandDiscover","kind":"identifier"}],"modules":[{"name":"Airwallex"}],"externalID":"c:@AWXCardBrandDiscover"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"discover"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWXCardBrand","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand","preciseIdentifier":"c:AWXConstants.h@T@AWXCardBrand"}]}],"kind":"declarations"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxcardbrand\/discover"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxcardbrand\/discover"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand"]]},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol","type":"topic","url":"\/documentation\/airwallex","role":"collection","abstract":[],"title":"Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardBrand/discover":{"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"discover"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWXCardBrand","preciseIdentifier":"c:AWXConstants.h@T@AWXCardBrand"}],"abstract":[],"navigatorTitle":[{"text":"AWXCardBrandDiscover","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand\/discover","title":"discover","role":"symbol","url":"\/documentation\/airwallex\/awxcardbrand\/discover"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardBrand":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXCardBrand","kind":"identifier"}],"navigatorTitle":[{"text":"AWXCardBrand","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand","abstract":[],"url":"\/documentation\/airwallex\/awxcardbrand","kind":"symbol","type":"topic","title":"AWXCardBrand"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Global Variable","path":"\/metadata\/roleHeading","op":"replace"},{"value":"AWXCardBrandDiscover","path":"\/metadata\/title","op":"replace"},{"value":"var","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"AWXCardBrandDiscover","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"path":"\/hierarchy","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXCardBrand","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand","preciseIdentifier":"c:AWXConstants.h@T@AWXCardBrand","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXCardBrandDiscover","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"AWXCardBrandDiscover","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardBrand~1discover\/title","op":"replace"},{"value":[{"text":"AWXCardBrandDiscover","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardBrand~1discover\/fragments","op":"replace"},{"value":"AWXCardBrand","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardBrand\/title","op":"replace"},{"value":[{"text":"AWXCardBrand","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardBrand\/fragments","op":"replace"},{"value":[{"text":"AWXCardBrand","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardBrand\/navigatorTitle","op":"replace"}]}]}