{"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"text":"bindSession:additionalInfo:","kind":"identifier"}],"role":"symbol","modules":[{"name":"Airwallex"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bindSession","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AWXSession","preciseIdentifier":"c:objc(cs)AWXSession","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"additionalInfo","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]?)","kind":"text"}],"title":"bindSession(_:additionalInfo:)","externalID":"c:objc(cs)AWXAnalyticsLogger(im)bindSession:additionalInfo:","symbolKind":"method"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AnalyticsLogger"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bindSession"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"session"},{"kind":"text","text":": "},{"text":"AWXSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXSession","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession"},{"kind":"text","text":", "},{"text":"additionalInfo","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"info","kind":"internalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?)"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/analyticslogger\/bindsession(_:additionalinfo:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/analyticslogger\/bindsession(_:additionalinfo:)"]}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AnalyticsLogger\/bindSession(_:additionalInfo:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AnalyticsLogger/bindSession(_:additionalInfo:)":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AnalyticsLogger\/bindSession(_:additionalInfo:)","navigatorTitle":[{"kind":"identifier","text":"bindSession:additionalInfo:"}],"abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bindSession"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)AWXSession","kind":"typeIdentifier","text":"AWXSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"additionalInfo"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?)"}],"role":"symbol","type":"topic","url":"\/documentation\/airwallex\/analyticslogger\/bindsession(_:additionalinfo:)","title":"bindSession(_:additionalInfo:)","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AnalyticsLogger":{"navigatorTitle":[{"kind":"identifier","text":"AnalyticsLogger"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnalyticsLogger"}],"title":"AnalyticsLogger","abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AnalyticsLogger","url":"\/documentation\/airwallex\/analyticslogger","role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"kind":"symbol","abstract":[],"role":"collection","type":"topic","url":"\/documentation\/airwallex","title":"Airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSession":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWXSession"}],"abstract":[{"type":"codeVoice","code":"AWXSession"},{"type":"text","text":" is the base session."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AWXSession"}],"role":"symbol","type":"topic","url":"\/documentation\/airwallex\/awxsession","title":"AWXSession","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"bindSession:additionalInfo:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"bindSession:additionalInfo:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"bindSession:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)AWXSession","text":"AWXSession","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession"},{"text":" *) ","kind":"text"},{"text":"session","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"additionalInfo:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<NSString *,id>"},{"text":" *) ","kind":"text"},{"text":"info","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AnalyticsLogger~1bindSession(_:additionalInfo:)\/title","value":"bindSession:additionalInfo:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AnalyticsLogger~1bindSession(_:additionalInfo:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"bindSession:additionalInfo:","kind":"identifier"}]},{"value":"AWXAnalyticsLogger","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AnalyticsLogger\/title","op":"replace"},{"op":"replace","value":[{"text":"AWXAnalyticsLogger","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AnalyticsLogger\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AnalyticsLogger\/navigatorTitle","value":[{"kind":"identifier","text":"AWXAnalyticsLogger"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/title","value":"AWXSession"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/fragments","value":[{"text":"AWXSession","kind":"identifier"}],"op":"replace"},{"value":[{"text":"AWXSession","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}