{"variants":[{"paths":["\/documentation\/airwallex\/awxtextfieldtype\/lastname"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxtextfieldtype\/lastname"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lastName","kind":"identifier"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:@E@AWXTextFieldType@AWXTextFieldTypeLastName","modules":[{"name":"Airwallex"}],"role":"symbol","symbolKind":"case","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lastName","kind":"identifier"}],"navigatorTitle":[{"text":"AWXTextFieldTypeLastName","kind":"identifier"}],"title":"AWXTextFieldType.lastName"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/lastName"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType"]]},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXTextFieldType":{"url":"\/documentation\/airwallex\/awxtextfieldtype","type":"topic","abstract":[],"kind":"symbol","title":"AWXTextFieldType","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXTextFieldType","kind":"identifier"}],"navigatorTitle":[{"text":"AWXTextFieldType","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXTextFieldType/lastName":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/lastName","abstract":[],"url":"\/documentation\/airwallex\/awxtextfieldtype\/lastname","title":"AWXTextFieldType.lastName","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lastName","kind":"identifier"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"AWXTextFieldTypeLastName","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","type":"topic","role":"collection","title":"Airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"AWXTextFieldTypeLastName","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"AWXTextFieldTypeLastName","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"identifier","text":"AWXTextFieldTypeLastName"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"AWXTextFieldType","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType\/title"},{"value":[{"text":"AWXTextFieldType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType\/fragments"},{"value":[{"text":"AWXTextFieldType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType\/navigatorTitle"},{"value":"AWXTextFieldTypeLastName","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType~1lastName\/title"},{"value":[{"text":"AWXTextFieldTypeLastName","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType~1lastName\/fragments"}]}]}