{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRequestHandler","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxrequesthandler"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxrequesthandler"]}],"metadata":{"symbolKind":"typealias","title":"AWXRequestHandler","modules":[{"name":"Airwallex"}],"navigatorTitle":[{"text":"AWXRequestHandler","kind":"identifier"}],"roleHeading":"Type Alias","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXRequestHandler"}],"externalID":"c:AWXAPIClient.h@T@AWXRequestHandler","role":"symbol"},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"AWXRequestHandler","kind":"identifier"},{"text":" = (","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXResponse","text":"AWXResponse","preciseIdentifier":"c:objc(cs)AWXResponse"},{"kind":"text","text":"?, (any "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXResponse":{"abstract":[],"title":"AWXResponse","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXResponse","navigatorTitle":[{"kind":"identifier","text":"AWXResponse"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXResponse"}],"kind":"symbol","url":"\/documentation\/airwallex\/awxresponse","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRequestHandler":{"title":"AWXRequestHandler","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRequestHandler","navigatorTitle":[{"text":"AWXRequestHandler","kind":"identifier"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXRequestHandler","kind":"identifier"}],"type":"topic","url":"\/documentation\/airwallex\/awxrequesthandler","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","abstract":[],"type":"topic","kind":"symbol","title":"Airwallex","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Type Alias","path":"\/metadata\/roleHeading","op":"replace"},{"value":"AWXRequestHandler","path":"\/metadata\/title","op":"replace"},{"value":"typealias","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"AWXRequestHandler"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AWXRequestHandler"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"void (^)(AWXResponse *, NSError *)","preciseIdentifier":"c:BFv(#*$objc(cs)AWXResponse#*$objc(cs)NSError)"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXRequestHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"AWXResponse","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXResponse\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AWXResponse"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXResponse\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AWXResponse"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXResponse\/navigatorTitle","op":"replace"},{"value":"AWXRequestHandler","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRequestHandler\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AWXRequestHandler"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRequestHandler\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AWXRequestHandler"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRequestHandler\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}