{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxgetpaymentmethodsrequest\/pagesize"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxgetpaymentmethodsrequest\/pagesize"]}],"metadata":{"externalID":"c:objc(cs)AWXGetPaymentMethodsRequest(py)pageSize","role":"symbol","symbolKind":"property","title":"pageSize","navigatorTitle":[{"kind":"identifier","text":"pageSize"}],"modules":[{"name":"Airwallex"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"pageSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}]},"abstract":[{"type":"text","text":"Number of payment methods to be listed per page."}],"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodsRequest\/pageSize","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pageSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodsRequest"]]},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"abstract":[],"kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","url":"\/documentation\/airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentMethodsRequest":{"kind":"symbol","url":"\/documentation\/airwallex\/awxgetpaymentmethodsrequest","role":"symbol","type":"topic","navigatorTitle":[{"text":"AWXGetPaymentMethodsRequest","kind":"identifier"}],"title":"AWXGetPaymentMethodsRequest","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodsRequest","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXGetPaymentMethodsRequest","kind":"identifier"}],"abstract":[{"code":"AWXGetPaymentMethodsRequest","type":"codeVoice"},{"type":"text","text":" includes all of the parameters needed to get payment methods."}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentMethodsRequest/pageSize":{"abstract":[{"type":"text","text":"Number of payment methods to be listed per page."}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodsRequest\/pageSize","title":"pageSize","navigatorTitle":[{"kind":"identifier","text":"pageSize"}],"url":"\/documentation\/airwallex\/awxgetpaymentmethodsrequest\/pagesize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"pageSize","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"pageSize"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageSize"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodsRequest\/title","op":"replace","value":"AWXGetPaymentMethodsRequest"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodsRequest\/fragments","op":"replace","value":[{"kind":"identifier","text":"AWXGetPaymentMethodsRequest"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodsRequest\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AWXGetPaymentMethodsRequest"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodsRequest~1pageSize\/title","op":"replace","value":"pageSize"},{"value":[{"text":"pageSize","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodsRequest~1pageSize\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}