{"abstract":[{"type":"text","text":"Called when input validation fails, allowing the host app to scroll the first"},{"type":"text","text":" "},{"type":"text","text":"invalid field into the visible area."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/airwallex\/awxpaymentelementdelegate\/paymentelement(_:validationfailedfor:invalidinputview:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxpaymentelementdelegate\/paymentelement(_:validationfailedfor:invalidinputview:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElementDelegate\/paymentElement(_:validationFailedFor:invalidInputView:)"},"metadata":{"role":"symbol","symbolKind":"method","title":"paymentElement(_:validationFailedFor:invalidInputView:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentElement"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@Airwallex@objc(cs)AWXPaymentElement","text":"AWXPaymentElement"},{"kind":"text","text":", "},{"kind":"externalParam","text":"validationFailedFor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"invalidInputView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"paymentElement:validationFailedFor:invalidInputView:"}],"roleHeading":"Instance Method","modules":[{"name":"Airwallex"}],"externalID":"c:@M@Airwallex@objc(pl)AWXPaymentElementDelegate(im)paymentElement:validationFailedFor:invalidInputView:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentElement","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"element","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement","text":"AWXPaymentElement","preciseIdentifier":"c:@M@Airwallex@objc(cs)AWXPaymentElement","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"validationFailedFor","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"paymentMethod","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"invalidInputView","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The payment element.","type":"text"}]}],"name":"element"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The name of the payment method being validated (e.g., “card”).","type":"text"}]}],"name":"paymentMethod"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The view containing the first invalid input field that should be scrolled into view.","type":"text"}]}],"name":"invalidInputView"}],"kind":"parameters"},{"content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"inlineContent":[{"type":"text","text":"Since the payment element is embedded inside the host app’s view hierarchy,"},{"type":"text","text":" "},{"type":"text","text":"the SDK cannot determine how to scroll content into view. Implement this method"},{"type":"text","text":" "},{"type":"text","text":"to ensure the provided view is visible to the user (e.g., by calling"},{"type":"text","text":" "},{"type":"codeVoice","code":"scrollRectToVisible(_:animated:)"},{"type":"text","text":" on the enclosing scroll view, converting"},{"type":"text","text":" "},{"type":"text","text":"the view’s frame with "},{"type":"codeVoice","code":"convert(_:from:)"},{"type":"text","text":" as needed)."}],"type":"paragraph"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElementDelegate"]]},"kind":"symbol","sections":[],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement":{"role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentElement"}],"navigatorTitle":[{"kind":"identifier","text":"AWXPaymentElement"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement","url":"\/documentation\/airwallex\/awxpaymentelement","abstract":[{"type":"text","text":"An embeddable payment element that can be added to any view hierarchy."}],"title":"AWXPaymentElement"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElementDelegate":{"abstract":[{"type":"text","text":"Delegate protocol for receiving payment events from AWXPaymentElement."}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElementDelegate","url":"\/documentation\/airwallex\/awxpaymentelementdelegate","navigatorTitle":[{"kind":"identifier","text":"AWXPaymentElementDelegate"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentElementDelegate"}],"kind":"symbol","title":"AWXPaymentElementDelegate"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElementDelegate/paymentElement(_:validationFailedFor:invalidInputView:)":{"abstract":[{"type":"text","text":"Called when input validation fails, allowing the host app to scroll the first"},{"type":"text","text":" "},{"type":"text","text":"invalid field into the visible area."}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElementDelegate\/paymentElement(_:validationFailedFor:invalidInputView:)","url":"\/documentation\/airwallex\/awxpaymentelementdelegate\/paymentelement(_:validationfailedfor:invalidinputview:)","navigatorTitle":[{"kind":"identifier","text":"paymentElement:validationFailedFor:invalidInputView:"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentElement"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@Airwallex@objc(cs)AWXPaymentElement","text":"AWXPaymentElement"},{"kind":"text","text":", "},{"kind":"externalParam","text":"validationFailedFor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"invalidInputView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"kind":"text","text":")"}],"kind":"symbol","title":"paymentElement(_:validationFailedFor:invalidInputView:)"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","url":"\/documentation\/airwallex","abstract":[],"title":"Airwallex"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"paymentElement:validationFailedFor:invalidInputView:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"paymentElement:validationFailedFor:invalidInputView:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"paymentElement:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement","text":"AWXPaymentElement","preciseIdentifier":"c:@M@Airwallex@objc(cs)AWXPaymentElement","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"element","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"validationFailedFor:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"paymentMethod","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"invalidInputView:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"invalidInputView","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The payment element.","type":"text"}],"type":"paragraph"}],"name":"element"},{"content":[{"inlineContent":[{"text":"The name of the payment method being validated (e.g., “card”).","type":"text"}],"type":"paragraph"}],"name":"paymentMethod"},{"content":[{"inlineContent":[{"text":"The view containing the first invalid input field that should be scrolled into view.","type":"text"}],"type":"paragraph"}],"name":"invalidInputView"}]}},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/title","op":"replace","value":"AWXPaymentElement"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/fragments","op":"replace","value":[{"text":"AWXPaymentElement","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/navigatorTitle","op":"replace","value":[{"text":"AWXPaymentElement","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElementDelegate\/title","op":"replace","value":"AWXPaymentElementDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElementDelegate\/fragments","op":"replace","value":[{"text":"AWXPaymentElementDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElementDelegate\/navigatorTitle","op":"replace","value":[{"text":"AWXPaymentElementDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElementDelegate~1paymentElement(_:validationFailedFor:invalidInputView:)\/title","op":"replace","value":"paymentElement:validationFailedFor:invalidInputView:"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElementDelegate~1paymentElement(_:validationFailedFor:invalidInputView:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"paymentElement:validationFailedFor:invalidInputView:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}