{"kind":"symbol","sections":[],"metadata":{"role":"symbol","externalID":"c:objc(cs)AWXCreatePaymentConsentRequest(py)requiresCVC","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requiresCVC","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"modules":[{"name":"Airwallex"}],"title":"requiresCVC","symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"requiresCVC"}]},"abstract":[{"type":"text","text":"Whether it requires CVC."}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCreatePaymentConsentRequest"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiresCVC"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/airwallex\/awxcreatepaymentconsentrequest\/requirescvc"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxcreatepaymentconsentrequest\/requirescvc"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCreatePaymentConsentRequest\/requiresCVC"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCreatePaymentConsentRequest/requiresCVC":{"navigatorTitle":[{"text":"requiresCVC","kind":"identifier"}],"abstract":[{"type":"text","text":"Whether it requires CVC."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requiresCVC","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCreatePaymentConsentRequest\/requiresCVC","title":"requiresCVC","kind":"symbol","type":"topic","url":"\/documentation\/airwallex\/awxcreatepaymentconsentrequest\/requirescvc"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCreatePaymentConsentRequest":{"abstract":[{"type":"codeVoice","code":"AWXCreatePaymentConsentRequest"},{"type":"text","text":" includes the request of creating payment consent."}],"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXCreatePaymentConsentRequest","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxcreatepaymentconsentrequest","kind":"symbol","navigatorTitle":[{"text":"AWXCreatePaymentConsentRequest","kind":"identifier"}],"title":"AWXCreatePaymentConsentRequest","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCreatePaymentConsentRequest"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","url":"\/documentation\/airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol","title":"Airwallex","abstract":[],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"requiresCVC"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"requiresCVC","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"requiresCVC","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCreatePaymentConsentRequest~1requiresCVC\/title","op":"replace","value":"requiresCVC"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCreatePaymentConsentRequest~1requiresCVC\/fragments","op":"replace","value":[{"kind":"identifier","text":"requiresCVC"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCreatePaymentConsentRequest\/title","op":"replace","value":"AWXCreatePaymentConsentRequest"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCreatePaymentConsentRequest\/fragments","op":"replace","value":[{"kind":"identifier","text":"AWXCreatePaymentConsentRequest"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCreatePaymentConsentRequest\/navigatorTitle","op":"replace","value":[{"text":"AWXCreatePaymentConsentRequest","kind":"identifier"}]}]}]}