{"variants":[{"paths":["\/documentation\/airwallex\/awxredirectactionprovider\/confirmpaymentintent(with:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxredirectactionprovider\/confirmpaymentintent(with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"confirmPaymentIntent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"paymentMethodName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRedirectActionProvider\/confirmPaymentIntent(with:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRedirectActionProvider"]]},"metadata":{"externalID":"c:objc(cs)AWXRedirectActionProvider(im)confirmPaymentIntentWithPaymentMethodName:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"confirmPaymentIntent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"symbolKind":"method","title":"confirmPaymentIntent(with:)","modules":[{"name":"Airwallex"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"confirmPaymentIntentWithPaymentMethodName:","kind":"identifier"}],"role":"symbol"},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRedirectActionProvider":{"kind":"symbol","navigatorTitle":[{"text":"AWXRedirectActionProvider","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"AWXRedirectActionProvider"},{"type":"text","text":" handles Redirect flow."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXRedirectActionProvider","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/airwallex\/awxredirectactionprovider","title":"AWXRedirectActionProvider","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRedirectActionProvider"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"kind":"symbol","abstract":[],"role":"collection","type":"topic","url":"\/documentation\/airwallex","title":"Airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRedirectActionProvider/confirmPaymentIntent(with:)":{"url":"\/documentation\/airwallex\/awxredirectactionprovider\/confirmpaymentintent(with:)","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRedirectActionProvider\/confirmPaymentIntent(with:)","title":"confirmPaymentIntent(with:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"confirmPaymentIntentWithPaymentMethodName:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"confirmPaymentIntent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"kind":"symbol","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"confirmPaymentIntentWithPaymentMethodName:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"confirmPaymentIntentWithPaymentMethodName:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"confirmPaymentIntentWithPaymentMethodName:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"paymentMethodName","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRedirectActionProvider\/title","value":"AWXRedirectActionProvider","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRedirectActionProvider\/fragments","value":[{"text":"AWXRedirectActionProvider","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRedirectActionProvider\/navigatorTitle","value":[{"kind":"identifier","text":"AWXRedirectActionProvider"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRedirectActionProvider~1confirmPaymentIntent(with:)\/title","value":"confirmPaymentIntentWithPaymentMethodName:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRedirectActionProvider~1confirmPaymentIntent(with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"confirmPaymentIntentWithPaymentMethodName:"}],"op":"replace"}]}]}