{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxredirectactionprovider\/confirmpaymentintent(with:flow:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxredirectactionprovider\/confirmpaymentintent(with:flow:)"]}],"metadata":{"title":"confirmPaymentIntent(with:flow:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confirmPaymentIntent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"flow","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AWXPaymentMethodFlow","preciseIdentifier":"c:AWXConstants.h@T@AWXPaymentMethodFlow","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"Airwallex"}],"navigatorTitle":[{"text":"confirmPaymentIntentWithPaymentMethodName:flow:","kind":"identifier"}],"externalID":"c:objc(cs)AWXRedirectActionProvider(im)confirmPaymentIntentWithPaymentMethodName:flow:","symbolKind":"method","role":"symbol","roleHeading":"Instance Method"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRedirectActionProvider"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"confirmPaymentIntent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"paymentMethodName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"flow"},{"kind":"text","text":": "},{"preciseIdentifier":"c:AWXConstants.h@T@AWXPaymentMethodFlow","kind":"typeIdentifier","text":"AWXPaymentMethodFlow","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethodFlow"},{"kind":"text","text":")"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRedirectActionProvider\/confirmPaymentIntent(with:flow:)","interfaceLanguage":"swift"},"sections":[],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRedirectActionProvider":{"abstract":[{"code":"AWXRedirectActionProvider","type":"codeVoice"},{"text":" handles Redirect flow.","type":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRedirectActionProvider","role":"symbol","title":"AWXRedirectActionProvider","navigatorTitle":[{"text":"AWXRedirectActionProvider","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxredirectactionprovider","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXRedirectActionProvider","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentMethodFlow":{"url":"\/documentation\/airwallex\/awxpaymentmethodflow","navigatorTitle":[{"kind":"identifier","text":"AWXPaymentMethodFlow"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethodFlow","type":"topic","abstract":[],"role":"symbol","title":"AWXPaymentMethodFlow","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentMethodFlow"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRedirectActionProvider/confirmPaymentIntent(with:flow:)":{"abstract":[],"title":"confirmPaymentIntent(with:flow:)","url":"\/documentation\/airwallex\/awxredirectactionprovider\/confirmpaymentintent(with:flow:)","navigatorTitle":[{"text":"confirmPaymentIntentWithPaymentMethodName:flow:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRedirectActionProvider\/confirmPaymentIntent(with:flow:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confirmPaymentIntent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"flow","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AWXPaymentMethodFlow","preciseIdentifier":"c:AWXConstants.h@T@AWXPaymentMethodFlow","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"abstract":[],"url":"\/documentation\/airwallex","role":"collection","title":"Airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"confirmPaymentIntentWithPaymentMethodName:flow:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"confirmPaymentIntentWithPaymentMethodName:flow:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"confirmPaymentIntentWithPaymentMethodName:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"paymentMethodName","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"flow:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethodFlow","preciseIdentifier":"c:AWXConstants.h@T@AWXPaymentMethodFlow","text":"AWXPaymentMethodFlow","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"flow","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"AWXRedirectActionProvider","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRedirectActionProvider\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AWXRedirectActionProvider"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRedirectActionProvider\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AWXRedirectActionProvider"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRedirectActionProvider\/navigatorTitle","op":"replace"},{"value":"AWXPaymentMethodFlow","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethodFlow\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AWXPaymentMethodFlow"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethodFlow\/fragments","op":"replace"},{"value":[{"text":"AWXPaymentMethodFlow","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethodFlow\/navigatorTitle","op":"replace"},{"value":"confirmPaymentIntentWithPaymentMethodName:flow:","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRedirectActionProvider~1confirmPaymentIntent(with:flow:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"confirmPaymentIntentWithPaymentMethodName:flow:"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRedirectActionProvider~1confirmPaymentIntent(with:flow:)\/fragments","op":"replace"}]}]}