{"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXThreeDs\/deviceDataCollectionRes","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXThreeDs"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deviceDataCollectionRes","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"symbolKind":"property","role":"symbol","roleHeading":"Instance Property","externalID":"c:objc(cs)AWXThreeDs(py)deviceDataCollectionRes","navigatorTitle":[{"text":"deviceDataCollectionRes","kind":"identifier"}],"title":"deviceDataCollectionRes","modules":[{"name":"Airwallex"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceDataCollectionRes"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}]},"variants":[{"paths":["\/documentation\/airwallex\/awxthreeds\/devicedatacollectionres"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxthreeds\/devicedatacollectionres"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"type":"text","text":"Device data collection response."}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXThreeDs/deviceDataCollectionRes":{"abstract":[{"type":"text","text":"Device data collection response."}],"role":"symbol","title":"deviceDataCollectionRes","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXThreeDs\/deviceDataCollectionRes","url":"\/documentation\/airwallex\/awxthreeds\/devicedatacollectionres","navigatorTitle":[{"kind":"identifier","text":"deviceDataCollectionRes"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deviceDataCollectionRes","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXThreeDs":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXThreeDs","kind":"identifier"}],"role":"symbol","url":"\/documentation\/airwallex\/awxthreeds","navigatorTitle":[{"text":"AWXThreeDs","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXThreeDs","abstract":[{"code":"AWXThreeDs","type":"codeVoice"},{"type":"text","text":" includes the information of 3ds."}],"title":"AWXThreeDs","kind":"symbol","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol","type":"topic","url":"\/documentation\/airwallex","role":"collection","abstract":[],"title":"Airwallex"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"deviceDataCollectionRes"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"deviceDataCollectionRes"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"deviceDataCollectionRes","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXThreeDs~1deviceDataCollectionRes\/title","value":"deviceDataCollectionRes"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXThreeDs~1deviceDataCollectionRes\/fragments","value":[{"text":"deviceDataCollectionRes","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXThreeDs\/title","value":"AWXThreeDs"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXThreeDs\/fragments","value":[{"kind":"identifier","text":"AWXThreeDs"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXThreeDs\/navigatorTitle","value":[{"kind":"identifier","text":"AWXThreeDs"}]}]}]}