{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxpaymentelement\/delegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxpaymentelement\/delegate"]}],"metadata":{"symbolKind":"property","role":"symbol","modules":[{"name":"Airwallex"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWXPaymentElementDelegate","preciseIdentifier":"c:@M@Airwallex@objc(pl)AWXPaymentElementDelegate"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"delegate","kind":"identifier"}],"externalID":"c:@M@Airwallex@objc(cs)AWXPaymentElement(py)delegate","roleHeading":"Instance Property","title":"delegate"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/delegate"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWXPaymentElementDelegate","preciseIdentifier":"c:@M@Airwallex@objc(pl)AWXPaymentElementDelegate","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElementDelegate"},{"kind":"text","text":"?"}]}]}],"abstract":[{"text":"The delegate that receives payment lifecycle callbacks.","type":"text"}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElementDelegate":{"abstract":[{"type":"text","text":"Delegate protocol for receiving payment events from AWXPaymentElement."}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElementDelegate","url":"\/documentation\/airwallex\/awxpaymentelementdelegate","navigatorTitle":[{"kind":"identifier","text":"AWXPaymentElementDelegate"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentElementDelegate"}],"kind":"symbol","title":"AWXPaymentElementDelegate"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement/delegate":{"abstract":[{"type":"text","text":"The delegate that receives payment lifecycle callbacks."}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/delegate","url":"\/documentation\/airwallex\/awxpaymentelement\/delegate","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWXPaymentElementDelegate","preciseIdentifier":"c:@M@Airwallex@objc(pl)AWXPaymentElementDelegate","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","title":"delegate"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","url":"\/documentation\/airwallex","abstract":[],"title":"Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement":{"role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentElement"}],"navigatorTitle":[{"kind":"identifier","text":"AWXPaymentElement"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement","url":"\/documentation\/airwallex\/awxpaymentelement","abstract":[{"type":"text","text":"An embeddable payment element that can be added to any view hierarchy."}],"title":"AWXPaymentElement"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"delegate","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"delegate"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"weak","kind":"keyword"},{"text":") ","kind":"text"},{"text":"id<AWXPaymentElementDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@Airwallex@objc(pl)AWXPaymentElementDelegate"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"AWXPaymentElementDelegate","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElementDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AWXPaymentElementDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElementDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AWXPaymentElementDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElementDelegate\/navigatorTitle"},{"op":"replace","value":"delegate","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement~1delegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"delegate"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement~1delegate\/fragments"},{"op":"replace","value":"AWXPaymentElement","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AWXPaymentElement"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AWXPaymentElement"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}