{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"appearance"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement","text":"AWXPaymentElement","preciseIdentifier":"c:@M@Airwallex@objc(cs)AWXPaymentElement","kind":"typeIdentifier"},{"kind":"text","text":"."},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/Configuration","text":"Configuration","preciseIdentifier":"s:9Airwallex17AWXPaymentElementC13ConfigurationC","kind":"typeIdentifier"},{"text":".","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/Configuration\/Appearance-swift.class","text":"Appearance","preciseIdentifier":"s:9Airwallex17AWXPaymentElementC13ConfigurationC10AppearanceC","kind":"typeIdentifier"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Use this to customize the tint color used throughout the payment UI.","type":"text"},{"text":" ","type":"text"},{"text":"When launched with a configuration, ","type":"text"},{"code":"appearance.tintColor","type":"codeVoice"},{"text":" overrides ","type":"text"},{"code":"AWXTheme.shared().tintColor","type":"codeVoice"},{"type":"text","text":"."}]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/Configuration"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/Configuration\/appearance"},"abstract":[{"type":"text","text":"Appearance configuration for customizing the visual style."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxuicontext\/configuration\/appearance"]}],"metadata":{"externalID":"s:9Airwallex12AWXUIContextC13ConfigurationC10appearanceAA17AWXPaymentElementCADC10AppearanceCvp","title":"appearance","role":"symbol","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"appearance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@Airwallex@objc(cs)AWXPaymentElement","text":"AWXPaymentElement"},{"kind":"text","text":"."},{"text":"Configuration","preciseIdentifier":"s:9Airwallex17AWXPaymentElementC13ConfigurationC","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Appearance","preciseIdentifier":"s:9Airwallex17AWXPaymentElementC13ConfigurationC10AppearanceC","kind":"typeIdentifier"}],"roleHeading":"Instance Property","modules":[{"name":"Airwallex"}]},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXUIContext/Configuration/appearance":{"title":"appearance","type":"topic","role":"symbol","url":"\/documentation\/airwallex\/awxuicontext\/configuration\/appearance","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/Configuration\/appearance","kind":"symbol","abstract":[{"type":"text","text":"Appearance configuration for customizing the visual style."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"appearance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@Airwallex@objc(cs)AWXPaymentElement","text":"AWXPaymentElement"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:9Airwallex17AWXPaymentElementC13ConfigurationC","text":"Configuration"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:9Airwallex17AWXPaymentElementC13ConfigurationC10AppearanceC","text":"Appearance"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement/Configuration/Appearance-swift.class":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/Configuration\/Appearance-swift.class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Appearance","kind":"identifier"}],"navigatorTitle":[{"text":"Appearance","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxpaymentelement\/configuration\/appearance-swift.class","type":"topic","title":"AWXPaymentElement.Configuration.Appearance","abstract":[{"type":"text","text":"Appearance configuration for customizing the visual style."}],"role":"symbol","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXUIContext/Configuration":{"title":"AWXUIContext.Configuration","type":"topic","role":"symbol","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/Configuration","abstract":[{"type":"text","text":"Configuration options for launching the payment UI."}],"url":"\/documentation\/airwallex\/awxuicontext\/configuration","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXUIContext":{"role":"symbol","url":"\/documentation\/airwallex\/awxuicontext","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXUIContext","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The main UI context for Airwallex payment flows."}],"title":"AWXUIContext","navigatorTitle":[{"text":"AWXUIContext","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement":{"role":"symbol","url":"\/documentation\/airwallex\/awxpaymentelement","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentElement"}],"type":"topic","kind":"symbol","title":"AWXPaymentElement","abstract":[{"type":"text","text":"An embeddable payment element that can be added to any view hierarchy."}],"navigatorTitle":[{"kind":"identifier","text":"AWXPaymentElement"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement/Configuration":{"abstract":[{"text":"Configuration options for the embedded payment element.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"role":"symbol","title":"AWXPaymentElement.Configuration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Configuration"}],"type":"topic","url":"\/documentation\/airwallex\/awxpaymentelement\/configuration","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/Configuration"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","url":"\/documentation\/airwallex","title":"Airwallex","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext\/title","value":"AWXUIContext"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext\/fragments","value":[{"kind":"identifier","text":"AWXUIContext"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext\/navigatorTitle","value":[{"kind":"identifier","text":"AWXUIContext"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/title","value":"AWXPaymentElement"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/fragments","value":[{"kind":"identifier","text":"AWXPaymentElement"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/navigatorTitle","value":[{"kind":"identifier","text":"AWXPaymentElement"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}