{"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"primaryTextColor","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"primaryTextColor","kind":"identifier"}],"title":"primaryTextColor()","modules":[{"name":"Airwallex"}],"externalID":"c:objc(cs)AWXTheme(im)primaryTextColor","roleHeading":"Instance Method","symbolKind":"method"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"primaryTextColor","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/airwallex\/awxtheme\/primarytextcolor()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxtheme\/primarytextcolor()"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme\/primaryTextColor()"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXTheme":{"role":"symbol","abstract":[{"code":"AWXTheme","type":"codeVoice"},{"text":" manages text styles.","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXTheme","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxtheme","title":"AWXTheme","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme","kind":"symbol","navigatorTitle":[{"text":"AWXTheme","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXTheme/primaryTextColor()":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"primaryTextColor"}],"url":"\/documentation\/airwallex\/awxtheme\/primarytextcolor()","title":"primaryTextColor()","abstract":[],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme\/primaryTextColor()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"primaryTextColor"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"abstract":[],"type":"topic","url":"\/documentation\/airwallex","title":"Airwallex","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"primaryTextColor"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"primaryTextColor","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"primaryTextColor"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTheme\/title","value":"AWXTheme"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTheme\/fragments","value":[{"text":"AWXTheme","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTheme\/navigatorTitle","value":[{"text":"AWXTheme","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTheme~1primaryTextColor()\/title","value":"primaryTextColor"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTheme~1primaryTextColor()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"primaryTextColor"}]}]}]}