platform :ios, '10.0'

use_frameworks!

ENV['SWIFT_VERSION'] = '5'

target 'Examples' do

    # Pods for Examples
    pod 'Airwallex', :path => '../'
    pod 'SVProgressHUD', '2.2.5'
    pod 'IQKeyboardManager', '6.5.4'
end

# target 'ExamplesSwift' do
#
#    # Pods for ExamplesSwift
#    pod 'Airwallex', :path => '../'
#
# end
