platform :ios, '10.0'

use_frameworks!

target 'Examples' do

    # Pods for Examples
    pod 'Airwallex', :path => '../'
    pod 'SVProgressHUD', '2.2.5'

end

# target 'ExamplesSwift' do
#
#    # Pods for ExamplesSwift
#    pod 'Airwallex', :path => '../'
#
# end
