{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentAmountType\/Equatable-Implementations"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/paymentamounttype\/equatable-implementations"]}],"metadata":{"modules":[{"name":"Airwallex"}],"roleHeading":"API Collection","title":"Equatable Implementations","role":"collectionGroup"},"kind":"article","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentAmountType"]]},"topicSections":[{"generated":true,"title":"Operators","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentAmountType\/!=(_:_:)"],"anchor":"Operators"}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","abstract":[],"type":"topic","kind":"symbol","title":"Airwallex","role":"collection"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentAmountType/!=(_:_:)":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"!=(_:_:)","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentAmountType\/!=(_:_:)","type":"topic","abstract":[],"url":"\/documentation\/airwallex\/paymentamounttype\/!=(_:_:)"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentAmountType":{"title":"PaymentAmountType","abstract":[{"type":"text","text":"Payment amount type enumeration"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentAmountType","navigatorTitle":[{"text":"PaymentAmountType","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PaymentAmountType","kind":"identifier"}],"type":"topic","url":"\/documentation\/airwallex\/paymentamounttype","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"PaymentAmountType","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentAmountType\/title"},{"value":[{"kind":"identifier","text":"PaymentAmountType"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentAmountType\/fragments"},{"value":[{"kind":"identifier","text":"PaymentAmountType"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentAmountType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}