{"abstract":[{"type":"text","text":"The payment networks supported by the merchant, for example @[PKPaymentNetworkVisa, PKPaymentNetworkMasterCard]."},{"type":"text","text":" "},{"type":"text","text":"This property constrains payment cards that may fund the payment. Default value includes Visa, Mastercard, UnionPay, Amex, Discover and JCB."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/airwallex\/awxapplepayoptions\/supportednetworks"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxapplepayoptions\/supportednetworks"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions\/supportedNetworks"},"metadata":{"title":"supportedNetworks","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"Airwallex"}],"navigatorTitle":[{"kind":"identifier","text":"supportedNetworks"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"supportedNetworks"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@T@PKPaymentNetwork","kind":"typeIdentifier","text":"PKPaymentNetwork"},{"kind":"text","text":"]"}],"externalID":"c:objc(cs)AWXApplePayOptions(py)supportedNetworks"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"supportedNetworks"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@T@PKPaymentNetwork","kind":"typeIdentifier","text":"PKPaymentNetwork"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions"]]},"sections":[],"kind":"symbol","references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","url":"\/documentation\/airwallex","abstract":[],"title":"Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXApplePayOptions":{"role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXApplePayOptions","kind":"identifier"}],"navigatorTitle":[{"text":"AWXApplePayOptions","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions","url":"\/documentation\/airwallex\/awxapplepayoptions","title":"AWXApplePayOptions","abstract":[{"type":"text","text":"Object used to construct PKPaymentRequest for Apple Pay."}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXApplePayOptions/supportedNetworks":{"abstract":[{"type":"text","text":"The payment networks supported by the merchant, for example @[PKPaymentNetworkVisa, PKPaymentNetworkMasterCard]."},{"type":"text","text":" "},{"type":"text","text":"This property constrains payment cards that may fund the payment. Default value includes Visa, Mastercard, UnionPay, Amex, Discover and JCB."}],"url":"\/documentation\/airwallex\/awxapplepayoptions\/supportednetworks","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions\/supportedNetworks","navigatorTitle":[{"kind":"identifier","text":"supportedNetworks"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"supportedNetworks","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@T@PKPaymentNetwork","kind":"typeIdentifier","text":"PKPaymentNetwork"},{"kind":"text","text":"]"}],"kind":"symbol","title":"supportedNetworks"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"supportedNetworks","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"supportedNetworks"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSString *>"},{"kind":"text","text":" * "},{"kind":"identifier","text":"supportedNetworks"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"AWXApplePayOptions","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AWXApplePayOptions"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AWXApplePayOptions"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions\/navigatorTitle","op":"replace"},{"value":"supportedNetworks","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions~1supportedNetworks\/title","op":"replace"},{"value":[{"kind":"identifier","text":"supportedNetworks"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions~1supportedNetworks\/fragments","op":"replace"}]}]}