{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxapplepayoptions\/additionalpaymentsummaryitems"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxapplepayoptions\/additionalpaymentsummaryitems"]}],"metadata":{"role":"symbol","symbolKind":"property","modules":[{"name":"Airwallex"}],"navigatorTitle":[{"kind":"identifier","text":"additionalPaymentSummaryItems"}],"title":"additionalPaymentSummaryItems","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"additionalPaymentSummaryItems","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)PKPaymentSummaryItem","text":"PKPaymentSummaryItem","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"externalID":"c:objc(cs)AWXApplePayOptions(py)additionalPaymentSummaryItems","roleHeading":"Instance Property"},"abstract":[{"type":"text","text":"An additional array of payment summary item objects that summarize the amount of the payment. Default value is nil."}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions\/additionalPaymentSummaryItems"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"additionalPaymentSummaryItems","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)PKPaymentSummaryItem","text":"PKPaymentSummaryItem","kind":"typeIdentifier"},{"text":"]? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"The SDK will automatically construct a PKPaymentSummaryItem with the total amount from the session object and"},{"type":"text","text":" "},{"type":"text","text":"the label defined with the totalPriceLabel property. Please make sure the sum of all the items in the array equals the total amount"},{"type":"text","text":" "},{"type":"text","text":"you set on the session object."}],"type":"paragraph"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions"]]},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXApplePayOptions/additionalPaymentSummaryItems":{"abstract":[{"text":"An additional array of payment summary item objects that summarize the amount of the payment. Default value is nil.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions\/additionalPaymentSummaryItems","title":"additionalPaymentSummaryItems","navigatorTitle":[{"text":"additionalPaymentSummaryItems","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxapplepayoptions\/additionalpaymentsummaryitems","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"additionalPaymentSummaryItems","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)PKPaymentSummaryItem","text":"PKPaymentSummaryItem","kind":"typeIdentifier"},{"text":"]?","kind":"text"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXApplePayOptions":{"kind":"symbol","url":"\/documentation\/airwallex\/awxapplepayoptions","role":"symbol","type":"topic","navigatorTitle":[{"text":"AWXApplePayOptions","kind":"identifier"}],"title":"AWXApplePayOptions","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXApplePayOptions","kind":"identifier"}],"abstract":[{"type":"text","text":"Object used to construct PKPaymentRequest for Apple Pay."}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"abstract":[],"kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","url":"\/documentation\/airwallex"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"additionalPaymentSummaryItems","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"additionalPaymentSummaryItems","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<PKPaymentSummaryItem *>"},{"kind":"text","text":" * "},{"kind":"identifier","text":"additionalPaymentSummaryItems"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"additionalPaymentSummaryItems","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions~1additionalPaymentSummaryItems\/title"},{"value":[{"text":"additionalPaymentSummaryItems","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions~1additionalPaymentSummaryItems\/fragments"},{"value":"AWXApplePayOptions","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions\/title"},{"value":[{"text":"AWXApplePayOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions\/fragments"},{"value":[{"text":"AWXApplePayOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions\/navigatorTitle"}]}]}