{"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions"]]},"metadata":{"modules":[{"name":"Airwallex"}],"role":"symbol","title":"merchantIdentifier","roleHeading":"Instance Property","externalID":"c:objc(cs)AWXApplePayOptions(py)merchantIdentifier","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"merchantIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"text":"merchantIdentifier","kind":"identifier"}],"symbolKind":"property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"merchantIdentifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"abstract":[{"text":"Apple Pay merchant identifier.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxapplepayoptions\/merchantidentifier"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxapplepayoptions\/merchantidentifier"]}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions\/merchantIdentifier","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXApplePayOptions/merchantIdentifier":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions\/merchantIdentifier","abstract":[{"text":"Apple Pay merchant identifier.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"merchantIdentifier","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"title":"merchantIdentifier","kind":"symbol","url":"\/documentation\/airwallex\/awxapplepayoptions\/merchantidentifier","type":"topic","role":"symbol","navigatorTitle":[{"text":"merchantIdentifier","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXApplePayOptions":{"role":"symbol","title":"AWXApplePayOptions","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXApplePayOptions","kind":"identifier"}],"navigatorTitle":[{"text":"AWXApplePayOptions","kind":"identifier"}],"abstract":[{"text":"Object used to construct PKPaymentRequest for Apple Pay.","type":"text"}],"kind":"symbol","url":"\/documentation\/airwallex\/awxapplepayoptions","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"abstract":[],"type":"topic","url":"\/documentation\/airwallex","title":"Airwallex","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"merchantIdentifier","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"merchantIdentifier","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"merchantIdentifier","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions~1merchantIdentifier\/title","value":"merchantIdentifier","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions~1merchantIdentifier\/fragments","value":[{"text":"merchantIdentifier","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions\/title","value":"AWXApplePayOptions","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions\/fragments","value":[{"text":"AWXApplePayOptions","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions\/navigatorTitle","value":[{"kind":"identifier","text":"AWXApplePayOptions"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}