{"metadata":{"role":"symbol","symbolKind":"case","modules":[{"name":"Airwallex"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancel","kind":"identifier"}],"navigatorTitle":[{"text":"AirwallexPaymentStatusCancel","kind":"identifier"}],"externalID":"c:@E@AirwallexPaymentStatus@AirwallexPaymentStatusCancel","roleHeading":"Case","title":"AirwallexPaymentStatus.cancel"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexPaymentStatus"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexPaymentStatus\/cancel"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancel","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/airwallexpaymentstatus\/cancel"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/airwallexpaymentstatus\/cancel"]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","url":"\/documentation\/airwallex","abstract":[],"title":"Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexPaymentStatus/cancel":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexPaymentStatus\/cancel","url":"\/documentation\/airwallex\/airwallexpaymentstatus\/cancel","navigatorTitle":[{"text":"AirwallexPaymentStatusCancel","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancel","kind":"identifier"}],"kind":"symbol","title":"AirwallexPaymentStatus.cancel"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexPaymentStatus":{"role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AirwallexPaymentStatus"}],"navigatorTitle":[{"text":"AirwallexPaymentStatus","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexPaymentStatus","url":"\/documentation\/airwallex\/airwallexpaymentstatus","abstract":[],"title":"AirwallexPaymentStatus"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"AirwallexPaymentStatusCancel"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"AirwallexPaymentStatusCancel","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"AirwallexPaymentStatusCancel","kind":"identifier"}]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexPaymentStatus~1cancel\/title","op":"replace","value":"AirwallexPaymentStatusCancel"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexPaymentStatus~1cancel\/fragments","op":"replace","value":[{"text":"AirwallexPaymentStatusCancel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexPaymentStatus\/title","op":"replace","value":"AirwallexPaymentStatus"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexPaymentStatus\/fragments","op":"replace","value":[{"kind":"identifier","text":"AirwallexPaymentStatus"}]},{"value":[{"kind":"identifier","text":"AirwallexPaymentStatus"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexPaymentStatus\/navigatorTitle","op":"replace"}]}]}