{"metadata":{"symbolKind":"case","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"inProgress"}],"role":"symbol","externalID":"c:@E@AirwallexPaymentStatus@AirwallexPaymentStatusInProgress","title":"AirwallexPaymentStatus.inProgress","navigatorTitle":[{"text":"AirwallexPaymentStatusInProgress","kind":"identifier"}],"modules":[{"name":"Airwallex"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexPaymentStatus"]]},"variants":[{"paths":["\/documentation\/airwallex\/airwallexpaymentstatus\/inprogress"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/airwallexpaymentstatus\/inprogress"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"inProgress","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexPaymentStatus\/inProgress"},"sections":[],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexPaymentStatus/inProgress":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexPaymentStatus\/inProgress","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"inProgress","kind":"identifier"}],"url":"\/documentation\/airwallex\/airwallexpaymentstatus\/inprogress","type":"topic","role":"symbol","navigatorTitle":[{"text":"AirwallexPaymentStatusInProgress","kind":"identifier"}],"kind":"symbol","abstract":[],"title":"AirwallexPaymentStatus.inProgress"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexPaymentStatus":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexPaymentStatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AirwallexPaymentStatus","kind":"identifier"}],"type":"topic","url":"\/documentation\/airwallex\/airwallexpaymentstatus","role":"symbol","navigatorTitle":[{"text":"AirwallexPaymentStatus","kind":"identifier"}],"kind":"symbol","abstract":[],"title":"AirwallexPaymentStatus"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","type":"topic","role":"collection","title":"Airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"AirwallexPaymentStatusInProgress","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"AirwallexPaymentStatusInProgress"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AirwallexPaymentStatusInProgress"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"AirwallexPaymentStatusInProgress","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexPaymentStatus~1inProgress\/title"},{"value":[{"kind":"identifier","text":"AirwallexPaymentStatusInProgress"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexPaymentStatus~1inProgress\/fragments"},{"value":"AirwallexPaymentStatus","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexPaymentStatus\/title"},{"value":[{"kind":"identifier","text":"AirwallexPaymentStatus"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexPaymentStatus\/fragments"},{"value":[{"kind":"identifier","text":"AirwallexPaymentStatus"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexPaymentStatus\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}