{"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexPaymentStatus\/success","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexPaymentStatus"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"success","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"metadata":{"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"success"}],"title":"AirwallexPaymentStatus.success","roleHeading":"Case","role":"symbol","externalID":"c:@E@AirwallexPaymentStatus@AirwallexPaymentStatusSuccess","modules":[{"name":"Airwallex"}],"navigatorTitle":[{"text":"AirwallexPaymentStatusSuccess","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/airwallex\/airwallexpaymentstatus\/success"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/airwallexpaymentstatus\/success"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexPaymentStatus/success":{"title":"AirwallexPaymentStatus.success","url":"\/documentation\/airwallex\/airwallexpaymentstatus\/success","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexPaymentStatus\/success","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"success","kind":"identifier"}],"navigatorTitle":[{"text":"AirwallexPaymentStatusSuccess","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexPaymentStatus":{"navigatorTitle":[{"kind":"identifier","text":"AirwallexPaymentStatus"}],"title":"AirwallexPaymentStatus","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AirwallexPaymentStatus"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexPaymentStatus","type":"topic","url":"\/documentation\/airwallex\/airwallexpaymentstatus","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","type":"topic","url":"\/documentation\/airwallex","kind":"symbol","abstract":[],"title":"Airwallex"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AirwallexPaymentStatusSuccess"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"AirwallexPaymentStatusSuccess","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"AirwallexPaymentStatusSuccess"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexPaymentStatus~1success\/title","value":"AirwallexPaymentStatusSuccess"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexPaymentStatus~1success\/fragments","value":[{"text":"AirwallexPaymentStatusSuccess","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexPaymentStatus\/title","value":"AirwallexPaymentStatus"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexPaymentStatus\/fragments","value":[{"text":"AirwallexPaymentStatus","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexPaymentStatus\/navigatorTitle","value":[{"text":"AirwallexPaymentStatus","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}