{"metadata":{"role":"collectionGroup","modules":[{"name":"Airwallex"}],"roleHeading":"API Collection","title":"RawRepresentable Implementations"},"variants":[{"paths":["\/documentation\/airwallex\/airwallexmerchanttriggerreason\/rawrepresentable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexMerchantTriggerReason"]]},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexMerchantTriggerReason\/hashValue"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexMerchantTriggerReason\/hash(into:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexMerchantTriggerReason\/RawRepresentable-Implementations","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"article","references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexMerchantTriggerReason":{"type":"topic","navigatorTitle":[{"text":"AirwallexMerchantTriggerReason","kind":"identifier"}],"url":"\/documentation\/airwallex\/airwallexmerchanttriggerreason","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexMerchantTriggerReason","title":"AirwallexMerchantTriggerReason","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AirwallexMerchantTriggerReason","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","role":"collection","title":"Airwallex","type":"topic","url":"\/documentation\/airwallex","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexMerchantTriggerReason/hashValue":{"conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}]},"type":"topic","url":"\/documentation\/airwallex\/airwallexmerchanttriggerreason\/hashvalue","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexMerchantTriggerReason\/hashValue","title":"hashValue","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"role":"symbol","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexMerchantTriggerReason/hash(into:)":{"conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}]},"type":"topic","url":"\/documentation\/airwallex\/airwallexmerchanttriggerreason\/hash(into:)","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexMerchantTriggerReason\/hash(into:)","title":"hash(into:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:s6HasherV","text":"Hasher","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"AirwallexMerchantTriggerReason","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexMerchantTriggerReason\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AirwallexMerchantTriggerReason"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexMerchantTriggerReason\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AirwallexMerchantTriggerReason"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexMerchantTriggerReason\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}