{"sections":[],"metadata":{"role":"symbol","title":"AirwallexMerchantTriggerReason.unscheduled","externalID":"c:@E@AirwallexMerchantTriggerReason@AirwallexMerchantTriggerReasonUnscheduled","navigatorTitle":[{"kind":"identifier","text":"AirwallexMerchantTriggerReasonUnscheduled"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"unscheduled"}],"modules":[{"name":"Airwallex"}],"symbolKind":"case","roleHeading":"Case"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unscheduled","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexMerchantTriggerReason\/unscheduled","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/airwallexmerchanttriggerreason\/unscheduled"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/airwallexmerchanttriggerreason\/unscheduled"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexMerchantTriggerReason"]]},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexMerchantTriggerReason":{"abstract":[],"title":"AirwallexMerchantTriggerReason","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AirwallexMerchantTriggerReason","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"AirwallexMerchantTriggerReason","kind":"identifier"}],"url":"\/documentation\/airwallex\/airwallexmerchanttriggerreason","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexMerchantTriggerReason"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexMerchantTriggerReason/unscheduled":{"navigatorTitle":[{"text":"AirwallexMerchantTriggerReasonUnscheduled","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"unscheduled","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexMerchantTriggerReason\/unscheduled","type":"topic","abstract":[],"kind":"symbol","title":"AirwallexMerchantTriggerReason.unscheduled","url":"\/documentation\/airwallex\/airwallexmerchanttriggerreason\/unscheduled"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","title":"Airwallex","abstract":[],"type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"AirwallexMerchantTriggerReasonUnscheduled","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"AirwallexMerchantTriggerReasonUnscheduled"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"AirwallexMerchantTriggerReasonUnscheduled"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexMerchantTriggerReason\/title","value":"AirwallexMerchantTriggerReason","op":"replace"},{"value":[{"text":"AirwallexMerchantTriggerReason","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexMerchantTriggerReason\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexMerchantTriggerReason\/navigatorTitle","value":[{"kind":"identifier","text":"AirwallexMerchantTriggerReason"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexMerchantTriggerReason~1unscheduled\/title","value":"AirwallexMerchantTriggerReasonUnscheduled"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexMerchantTriggerReason~1unscheduled\/fragments","value":[{"kind":"identifier","text":"AirwallexMerchantTriggerReasonUnscheduled"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}