{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/ElementType"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/ElementType\/Equatable-Implementations"},"kind":"article","variants":[{"paths":["\/documentation\/airwallex\/awxpaymentelement\/elementtype\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/ElementType\/!=(_:_:)"],"title":"Operators","anchor":"Operators","generated":true}],"sections":[],"metadata":{"roleHeading":"API Collection","modules":[{"name":"Airwallex"}],"role":"collectionGroup","title":"Equatable Implementations"},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement/ElementType/!=(_:_:)":{"type":"topic","title":"!=(_:_:)","abstract":[],"url":"\/documentation\/airwallex\/awxpaymentelement\/elementtype\/!=(_:_:)","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/ElementType\/!=(_:_:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","abstract":[],"type":"topic","kind":"symbol","title":"Airwallex","role":"collection"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement":{"abstract":[{"text":"An embeddable payment element that can be added to any view hierarchy.","type":"text"}],"title":"AWXPaymentElement","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement","navigatorTitle":[{"kind":"identifier","text":"AWXPaymentElement"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentElement"}],"kind":"symbol","url":"\/documentation\/airwallex\/awxpaymentelement","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement/ElementType":{"type":"topic","title":"AWXPaymentElement.ElementType","abstract":[{"text":"The type of element to display.","type":"text"}],"url":"\/documentation\/airwallex\/awxpaymentelement\/elementtype","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/ElementType","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ElementType"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ElementType"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/title","value":"AWXPaymentElement","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/fragments","value":[{"text":"AWXPaymentElement","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/navigatorTitle","value":[{"text":"AWXPaymentElement","kind":"identifier"}],"op":"replace"}]}]}