{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethodFlow"]]},"metadata":{"roleHeading":"Type Property","navigatorTitle":[{"text":"AWXPaymentMethodFlowApp","kind":"identifier"}],"role":"symbol","modules":[{"name":"Airwallex"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"app","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWXPaymentMethodFlow","preciseIdentifier":"c:AWXConstants.h@T@AWXPaymentMethodFlow","kind":"typeIdentifier"}],"extendedModule":"Airwallex","title":"app","externalID":"c:@AWXPaymentMethodFlowApp","symbolKind":"property"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"app"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethodFlow","preciseIdentifier":"c:AWXConstants.h@T@AWXPaymentMethodFlow","kind":"typeIdentifier","text":"AWXPaymentMethodFlow"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxpaymentmethodflow\/app"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxpaymentmethodflow\/app"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethodFlow\/app"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentMethodFlow/app":{"url":"\/documentation\/airwallex\/awxpaymentmethodflow\/app","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethodFlow\/app","title":"app","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"AWXPaymentMethodFlowApp"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"app","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:AWXConstants.h@T@AWXPaymentMethodFlow","text":"AWXPaymentMethodFlow","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentMethodFlow":{"title":"AWXPaymentMethodFlow","url":"\/documentation\/airwallex\/awxpaymentmethodflow","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentMethodFlow"}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethodFlow","navigatorTitle":[{"kind":"identifier","text":"AWXPaymentMethodFlow"}],"abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"kind":"symbol","abstract":[],"role":"collection","type":"topic","url":"\/documentation\/airwallex","title":"Airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Global Variable","op":"replace"},{"path":"\/metadata\/title","value":"AWXPaymentMethodFlowApp","op":"replace"},{"path":"\/metadata\/symbolKind","value":"var","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"AWXPaymentMethodFlowApp","kind":"identifier"}],"op":"replace"},{"path":"\/hierarchy","value":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethodFlow","text":"AWXPaymentMethodFlow","preciseIdentifier":"c:AWXConstants.h@T@AWXPaymentMethodFlow","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPaymentMethodFlowApp","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethodFlow~1app\/title","value":"AWXPaymentMethodFlowApp","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethodFlow~1app\/fragments","value":[{"kind":"identifier","text":"AWXPaymentMethodFlowApp"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethodFlow\/title","value":"AWXPaymentMethodFlow","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethodFlow\/fragments","value":[{"text":"AWXPaymentMethodFlow","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethodFlow\/navigatorTitle","value":[{"kind":"identifier","text":"AWXPaymentMethodFlow"}],"op":"replace"}]}]}