{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession\/returnURL"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Return URL for redirecting users back to your app after external payment processing.","type":"text"}],"kind":"symbol","variants":[{"paths":["\/documentation\/airwallex\/awxsession\/returnurl"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxsession\/returnurl"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Property","role":"symbol","title":"returnURL","externalID":"c:objc(cs)AWXSession(py)returnURL","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"returnURL","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"modules":[{"name":"Airwallex"}],"navigatorTitle":[{"text":"returnURL","kind":"identifier"}],"symbolKind":"property"},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"returnURL"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"inlineContent":[{"type":"text","text":"This URL is required when payments are processed outside of your app and users need to be redirected back."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"URL Format Guidelines:"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Use universal links (recommended): https:\/\/example.com\/"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"Required for wechatpay"}],"type":"paragraph"}]}],"type":"unorderedList"}]},{"content":[{"inlineContent":[{"text":"Custom URL schemes (fallback): yourapp:\/\/payment\/return","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Must be registered in your app’s URL schemes or Associated Domains"}]}]}]},{"type":"paragraph","inlineContent":[{"text":"Note:","type":"text"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Universal links are strongly recommended over custom URL schemes for better user experience","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Can be nil if you only support in-app payment methods (Apple Pay, cards)","type":"text"}]}]}],"type":"unorderedList"}]}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSession":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession","role":"symbol","type":"topic","abstract":[{"type":"codeVoice","code":"AWXSession"},{"type":"text","text":" is the base session."}],"url":"\/documentation\/airwallex\/awxsession","title":"AWXSession","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXSession"}],"navigatorTitle":[{"kind":"identifier","text":"AWXSession"}],"kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","title":"Airwallex","abstract":[],"type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSession/returnURL":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"returnURL","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","abstract":[{"text":"Return URL for redirecting users back to your app after external payment processing.","type":"text"}],"type":"topic","kind":"symbol","title":"returnURL","url":"\/documentation\/airwallex\/awxsession\/returnurl","navigatorTitle":[{"text":"returnURL","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession\/returnURL"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"returnURL"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"returnURL","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"returnURL","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/title","value":"AWXSession","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/fragments","value":[{"text":"AWXSession","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/navigatorTitle","op":"replace","value":[{"text":"AWXSession","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession~1returnURL\/title","op":"replace","value":"returnURL"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession~1returnURL\/fragments","op":"replace","value":[{"kind":"identifier","text":"returnURL"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}