{"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSchedule\/Encodable-Implementations","interfaceLanguage":"swift"},"metadata":{"roleHeading":"API Collection","modules":[{"name":"Airwallex"}],"role":"collectionGroup","title":"Encodable Implementations"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"article","topicSections":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSchedule\/encode(to:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}],"variants":[{"paths":["\/documentation\/airwallex\/paymentschedule\/encodable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSchedule"]]},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentSchedule":{"title":"PaymentSchedule","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentSchedule"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSchedule","navigatorTitle":[{"text":"PaymentSchedule","kind":"identifier"}],"abstract":[{"type":"text","text":"Payment schedule configuration"}],"url":"\/documentation\/airwallex\/paymentschedule"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentSchedule/encode(to:)":{"kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentSchedule\/encode(to:)","url":"\/documentation\/airwallex\/paymentschedule\/encode(to:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"encode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"keyword","text":"any"},{"kind":"text","text":" "},{"preciseIdentifier":"s:s7EncoderP","kind":"typeIdentifier","text":"Encoder"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"title":"encode(to:)"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","abstract":[],"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/airwallex"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"PaymentSchedule","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSchedule\/title"},{"op":"replace","value":[{"text":"PaymentSchedule","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSchedule\/fragments"},{"op":"replace","value":[{"text":"PaymentSchedule","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentSchedule\/navigatorTitle"}]}]}