{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardCVCViewController"},"abstract":[{"type":"codeVoice","code":"AWXCardCVCViewController"},{"text":" provides a confirm button for user to finish checkout flow with payment consent.","type":"text"}],"topicSections":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardCVCViewController\/cvcCallback","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardCVCViewController\/paymentConsent"],"title":"Instance Properties","anchor":"Instance-Properties"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXCardCVCViewController"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"title":"AWXCardCVCViewController","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXCardCVCViewController"}],"externalID":"c:objc(cs)AWXCardCVCViewController","role":"symbol","navigatorTitle":[{"text":"AWXCardCVCViewController","kind":"identifier"}],"symbolKind":"class","modules":[{"name":"Airwallex"}]},"sections":[],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXViewController"],"kind":"relationships","title":"Inherits From"},{"type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSCoding","doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSExtensionRequestHandling","doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/SQ","doc:\/\/org.cocoapods.Airwallex\/SH","doc:\/\/org.cocoapods.Airwallex\/s8SendableP","doc:\/\/org.cocoapods.Airwallex\/s16SendableMetatypeP","doc:\/\/org.cocoapods.Airwallex\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.Airwallex\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.Airwallex\/objc(pl)UIContentContainer","doc:\/\/org.cocoapods.Airwallex\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.Airwallex\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.Airwallex\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.Airwallex\/objc(pl)UIStateRestoring","doc:\/\/org.cocoapods.Airwallex\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.Airwallex\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.Airwallex\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxcardcvcviewcontroller"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxcardcvcviewcontroller"]}],"references":{"doc://org.cocoapods.Airwallex/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://org.cocoapods.Airwallex/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)UIResponderStandardEditActions","type":"unresolvable","title":"UIKit.UIResponderStandardEditActions"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","type":"topic","role":"collection","title":"Airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol","abstract":[]},"doc://org.cocoapods.Airwallex/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/5UIKit23UITraitChangeObservableP","type":"unresolvable","title":"UIKit.UITraitChangeObservable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXViewController":{"url":"\/documentation\/airwallex\/awxviewcontroller","title":"AWXViewController","type":"topic","abstract":[{"code":"AWXViewController","type":"codeVoice"},{"text":" is the base view controller.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXViewController","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXViewController","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"AWXViewController","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)UIAppearanceContainer","type":"unresolvable","title":"UIKit.UIAppearanceContainer"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardCVCViewController/paymentConsent":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardCVCViewController\/paymentConsent","abstract":[{"text":"A payment consent.","type":"text"}],"url":"\/documentation\/airwallex\/awxcardcvcviewcontroller\/paymentconsent","title":"paymentConsent","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentConsent","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWXPaymentConsent","preciseIdentifier":"c:objc(cs)AWXPaymentConsent","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"paymentConsent","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.Airwallex/objc(pl)NSExtensionRequestHandling":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSExtensionRequestHandling","type":"unresolvable","title":"Foundation.NSExtensionRequestHandling"},"doc://org.cocoapods.Airwallex/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardCVCViewController/cvcCallback":{"url":"\/documentation\/airwallex\/awxcardcvcviewcontroller\/cvccallback","title":"cvcCallback","abstract":[],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cvcCallback","kind":"identifier"},{"text":": ((","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?","kind":"text"}],"navigatorTitle":[{"text":"cvcCallback","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardCVCViewController\/cvcCallback","type":"topic"},"doc://org.cocoapods.Airwallex/objc(pl)UIContentContainer":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)UIContentContainer","type":"unresolvable","title":"UIKit.UIContentContainer"},"doc://org.cocoapods.Airwallex/SQ":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://org.cocoapods.Airwallex/SH":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://org.cocoapods.Airwallex/objc(pl)NSCoding":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSCoding","type":"unresolvable","title":"Foundation.NSCoding"},"doc://org.cocoapods.Airwallex/objc(pl)UIStateRestoring":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)UIStateRestoring","type":"unresolvable","title":"UIKit.UIStateRestoring"},"doc://org.cocoapods.Airwallex/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)UITraitEnvironment","type":"unresolvable","title":"UIKit.UITraitEnvironment"},"doc://org.cocoapods.Airwallex/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.Airwallex/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting"},"doc://org.cocoapods.Airwallex/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)UIUserActivityRestoring","type":"unresolvable","title":"UIKit.UIUserActivityRestoring"},"doc://org.cocoapods.Airwallex/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.Airwallex/s8SendableP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://org.cocoapods.Airwallex/s16SendableMetatypeP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s16SendableMetatypeP","type":"unresolvable","title":"Swift.SendableMetatype"},"doc://org.cocoapods.Airwallex/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardCVCViewController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXCardCVCViewController"}],"navigatorTitle":[{"text":"AWXCardCVCViewController","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardCVCViewController","kind":"symbol","type":"topic","url":"\/documentation\/airwallex\/awxcardcvcviewcontroller","role":"symbol","title":"AWXCardCVCViewController","abstract":[{"code":"AWXCardCVCViewController","type":"codeVoice"},{"text":" provides a confirm button for user to finish checkout flow with payment consent.","type":"text"}]},"doc://org.cocoapods.Airwallex/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)UIFocusEnvironment","type":"unresolvable","title":"UIKit.UIFocusEnvironment"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"AWXCardCVCViewController","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"AWXCardCVCViewController"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AWXCardCVCViewController"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardCVCViewController\/cvcCallback","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardCVCViewController\/paymentConsent"],"generated":true}],"path":"\/topicSections","op":"replace"},{"value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXViewController"],"type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXCardCVCViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"AWXViewController","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXViewController","preciseIdentifier":"c:objc(cs)AWXViewController"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"AWXViewController","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXViewController\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AWXViewController"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXViewController\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AWXViewController"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXViewController\/navigatorTitle","op":"replace"},{"value":"paymentConsent","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardCVCViewController~1paymentConsent\/title","op":"replace"},{"value":[{"kind":"identifier","text":"paymentConsent"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardCVCViewController~1paymentConsent\/fragments","op":"replace"},{"value":"cvcCallback","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardCVCViewController~1cvcCallback\/title","op":"replace"},{"value":[{"kind":"identifier","text":"cvcCallback"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardCVCViewController~1cvcCallback\/fragments","op":"replace"},{"value":"AWXCardCVCViewController","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardCVCViewController\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AWXCardCVCViewController"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardCVCViewController\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AWXCardCVCViewController"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardCVCViewController\/navigatorTitle","op":"replace"}]}]}