{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AWXFormMapping","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/SQ","doc:\/\/org.cocoapods.Airwallex\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"sections":[],"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXFormMapping\/forms","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXFormMapping\/title"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true}],"metadata":{"externalID":"c:objc(cs)AWXFormMapping","role":"symbol","modules":[{"name":"Airwallex"}],"roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXFormMapping","kind":"identifier"}],"navigatorTitle":[{"text":"AWXFormMapping","kind":"identifier"}],"symbolKind":"class","title":"AWXFormMapping"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXFormMapping"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/airwallex\/awxformmapping"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxformmapping"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXFormMapping/title":{"role":"symbol","title":"title","type":"topic","abstract":[],"kind":"symbol","url":"\/documentation\/airwallex\/awxformmapping\/title","navigatorTitle":[{"text":"title","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"title","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXFormMapping\/title"},"doc://org.cocoapods.Airwallex/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject"},"doc://org.cocoapods.Airwallex/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXFormMapping/forms":{"type":"topic","abstract":[],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"forms","kind":"identifier"},{"text":": [","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"forms","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXFormMapping\/forms","url":"\/documentation\/airwallex\/awxformmapping\/forms","title":"forms"},"doc://org.cocoapods.Airwallex/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXFormMapping":{"url":"\/documentation\/airwallex\/awxformmapping","title":"AWXFormMapping","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXFormMapping"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXFormMapping","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWXFormMapping"}]},"doc://org.cocoapods.Airwallex/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP"},"doc://org.cocoapods.Airwallex/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SQ"},"doc://org.cocoapods.Airwallex/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SH"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","type":"topic","role":"collection","title":"Airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol","abstract":[]},"doc://org.cocoapods.Airwallex/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"AWXFormMapping","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AWXFormMapping"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AWXFormMapping"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXFormMapping\/forms","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXFormMapping\/title"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"],"title":"Inherits From"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXFormMapping"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXFormMapping~1title\/title","value":"title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXFormMapping~1title\/fragments","value":[{"kind":"identifier","text":"title"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXFormMapping~1forms\/title","value":"forms","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXFormMapping~1forms\/fragments","value":[{"kind":"identifier","text":"forms"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXFormMapping\/title","value":"AWXFormMapping","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXFormMapping\/fragments","value":[{"kind":"identifier","text":"AWXFormMapping"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXFormMapping\/navigatorTitle","value":[{"kind":"identifier","text":"AWXFormMapping"}],"op":"replace"}]}]}