{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"topicSections":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/Configuration"],"anchor":"Classes","title":"Classes"},{"generated":true,"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/delegate","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/view"],"anchor":"Instance-Properties","title":"Instance Properties"},{"generated":true,"title":"Type Methods","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/create(session:delegate:configuration:)"],"anchor":"Type-Methods"},{"generated":true,"title":"Enumerations","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/ElementType"],"anchor":"Enumerations"},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/AWXPaymentResultDelegate-Implementations"],"anchor":"Default-Implementations"}],"sections":[],"abstract":[{"text":"An embeddable payment element that can be added to any view hierarchy.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentElement"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"text":"Overview","type":"heading","level":2,"anchor":"overview"},{"inlineContent":[{"type":"codeVoice","code":"AWXPaymentElement"},{"text":" provides a flexible way to integrate Airwallex payment UI into your app.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Unlike "},{"code":"AWXUIContext.launchPayment()","type":"codeVoice"},{"type":"text","text":" which presents a full payment sheet as a view controller,"},{"type":"text","text":" "},{"type":"codeVoice","code":"AWXPaymentElement"},{"text":" returns a ","type":"text"},{"type":"codeVoice","code":"UIView"},{"text":" that you can embed in your own view hierarchy.","type":"text"}],"type":"paragraph"},{"text":"Usage","anchor":"Usage","level":2,"type":"heading"},{"code":["let configuration = AWXPaymentElement.Configuration()","configuration.layout = .accordion","","let element = try await AWXPaymentElement.create(","    session: session,","    delegate: self,","    configuration: configuration",")","containerView.addSubview(element.view)"],"syntax":"swift","type":"codeListing"},{"text":"Important Notes","anchor":"Important-Notes","level":2,"type":"heading"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The embedded view requires Auto Layout constraints for proper sizing","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The view’s height updates automatically based on content","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Keyboard handling is the host app’s responsibility","type":"text"}]}]}]}]}],"kind":"symbol","metadata":{"externalID":"c:@M@Airwallex@objc(cs)AWXPaymentElement","navigatorTitle":[{"text":"AWXPaymentElement","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AWXPaymentElement"}],"role":"symbol","title":"AWXPaymentElement","symbolKind":"class","modules":[{"name":"Airwallex"}],"roleHeading":"Class"},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"],"type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentResultDelegate","doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","doc:\/\/org.cocoapods.Airwallex\/s8CopyableP","doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/SQ","doc:\/\/org.cocoapods.Airwallex\/SH","doc:\/\/org.cocoapods.Airwallex\/s8SendableP"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/airwallex\/awxpaymentelement"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxpaymentelement"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement"},"references":{"doc://org.cocoapods.Airwallex/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SQ"},"doc://org.cocoapods.Airwallex/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement/view":{"url":"\/documentation\/airwallex\/awxpaymentelement\/view","abstract":[{"text":"The embeddable view containing the payment UI.","type":"text"}],"type":"topic","kind":"symbol","title":"view","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/view","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"view"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"}],"navigatorTitle":[{"kind":"identifier","text":"view"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement/create(session:delegate:configuration:)":{"url":"\/documentation\/airwallex\/awxpaymentelement\/create(session:delegate:configuration:)","type":"topic","navigatorTitle":[{"text":"createWithSession:delegate:configuration:completionHandler:","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"session","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AWXSession","text":"AWXSession","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AWXPaymentElementDelegate","preciseIdentifier":"c:@M@Airwallex@objc(pl)AWXPaymentElementDelegate","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:9Airwallex17AWXPaymentElementC13ConfigurationC","text":"Configuration","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"preciseIdentifier":"c:@M@Airwallex@objc(cs)AWXPaymentElement","text":"AWXPaymentElement","kind":"typeIdentifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/create(session:delegate:configuration:)","kind":"symbol","title":"create(session:delegate:configuration:)","abstract":[{"type":"text","text":"Creates an embedded payment element."}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","type":"topic","role":"collection","title":"Airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol","abstract":[]},"doc://org.cocoapods.Airwallex/s8SendableP":{"title":"Swift.Sendable","identifier":"doc:\/\/org.cocoapods.Airwallex\/s8SendableP","type":"unresolvable"},"doc://org.cocoapods.Airwallex/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SH","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement/delegate":{"url":"\/documentation\/airwallex\/awxpaymentelement\/delegate","type":"topic","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@Airwallex@objc(pl)AWXPaymentElementDelegate","kind":"typeIdentifier","text":"AWXPaymentElementDelegate"},{"kind":"text","text":"?"}],"role":"symbol","title":"delegate","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/delegate","kind":"symbol","abstract":[{"type":"text","text":"The delegate that receives payment lifecycle callbacks."}]},"doc://org.cocoapods.Airwallex/s8CopyableP":{"title":"Swift.Copyable","identifier":"doc:\/\/org.cocoapods.Airwallex\/s8CopyableP","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement/AWXPaymentResultDelegate-Implementations":{"url":"\/documentation\/airwallex\/awxpaymentelement\/awxpaymentresultdelegate-implementations","type":"topic","role":"collectionGroup","title":"AWXPaymentResultDelegate Implementations","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/AWXPaymentResultDelegate-Implementations","kind":"article","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement":{"title":"AWXPaymentElement","navigatorTitle":[{"text":"AWXPaymentElement","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxpaymentelement","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement","role":"symbol","abstract":[{"text":"An embeddable payment element that can be added to any view hierarchy.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPaymentElement","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement/ElementType":{"type":"topic","url":"\/documentation\/airwallex\/awxpaymentelement\/elementtype","kind":"symbol","abstract":[{"text":"The type of element to display.","type":"text"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ElementType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ElementType"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/ElementType","title":"AWXPaymentElement.ElementType"},"doc://org.cocoapods.Airwallex/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject","type":"unresolvable"},"doc://org.cocoapods.Airwallex/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","type":"unresolvable"},"doc://org.cocoapods.Airwallex/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","type":"unresolvable"},"doc://org.cocoapods.Airwallex/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentResultDelegate":{"url":"\/documentation\/airwallex\/awxpaymentresultdelegate","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AWXPaymentResultDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentResultDelegate"}],"role":"symbol","title":"AWXPaymentResultDelegate","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentResultDelegate","kind":"symbol","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement/Configuration":{"url":"\/documentation\/airwallex\/awxpaymentelement\/configuration","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"role":"symbol","title":"AWXPaymentElement.Configuration","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/Configuration","kind":"symbol","abstract":[{"type":"text","text":"Configuration options for the embedded payment element."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"AWXPaymentElement","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"AWXPaymentElement","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"AWXPaymentElement","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/delegate","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/view"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/create(session:delegate:configuration:)"],"anchor":"Type-Methods","title":"Type Methods","generated":true},{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/AWXPaymentResultDelegate-Implementations"],"anchor":"Default-Implementations","title":"Default Implementations","generated":true}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentResultDelegate"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentElement"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement~1view\/title","value":"view","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement~1view\/fragments","value":[{"text":"view","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement~1create(session:delegate:configuration:)\/title","value":"createWithSession:delegate:configuration:completionHandler:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement~1create(session:delegate:configuration:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createWithSession:delegate:configuration:completionHandler:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement~1delegate\/title","value":"delegate","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement~1delegate\/fragments","value":[{"text":"delegate","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/title","value":"AWXPaymentElement"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/fragments","value":[{"text":"AWXPaymentElement","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/navigatorTitle","value":[{"text":"AWXPaymentElement","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentResultDelegate\/title","value":"AWXPaymentResultDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentResultDelegate\/fragments","value":[{"text":"AWXPaymentResultDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentResultDelegate\/navigatorTitle","value":[{"text":"AWXPaymentResultDelegate","kind":"identifier"}],"op":"replace"}]}]}