{"variants":[{"paths":["\/documentation\/airwallex\/awxpaymentelementdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxpaymentelementdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentElementDelegate"}],"externalID":"c:@M@Airwallex@objc(pl)AWXPaymentElementDelegate","roleHeading":"Protocol","symbolKind":"protocol","title":"AWXPaymentElementDelegate","modules":[{"name":"Airwallex"}],"navigatorTitle":[{"kind":"identifier","text":"AWXPaymentElementDelegate"}]},"topicSections":[{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElementDelegate\/paymentElement(_:didCompleteFor:with:error:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElementDelegate\/paymentElement(_:didCompleteFor:withPaymentConsentId:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElementDelegate\/paymentElement(_:onProcessingStateChangedFor:isProcessing:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElementDelegate\/paymentElement(_:validationFailedFor:invalidInputView:)"],"generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentElementDelegate"}],"platforms":["iOS"]}]},{"content":[{"type":"heading","level":2,"anchor":"overview","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This delegate replaces "},{"type":"codeVoice","code":"AWXPaymentResultDelegate"},{"type":"text","text":" for AWXPaymentElement,"},{"type":"text","text":" "},{"type":"text","text":"providing payment lifecycle notifications with method information."}]}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElementDelegate","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"abstract":[{"type":"text","text":"Delegate protocol for receiving payment events from AWXPaymentElement."}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElementDelegate/paymentElement(_:onProcessingStateChangedFor:isProcessing:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"paymentElement:onProcessingStateChangedFor:isProcessing:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentElement"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@Airwallex@objc(cs)AWXPaymentElement","text":"AWXPaymentElement"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onProcessingStateChangedFor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isProcessing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElementDelegate\/paymentElement(_:onProcessingStateChangedFor:isProcessing:)","url":"\/documentation\/airwallex\/awxpaymentelementdelegate\/paymentelement(_:onprocessingstatechangedfor:isprocessing:)","title":"paymentElement(_:onProcessingStateChangedFor:isProcessing:)","type":"topic","abstract":[{"type":"text","text":"Called when payment processing state changes."}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","type":"topic","role":"collection","title":"Airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElementDelegate/paymentElement(_:didCompleteFor:withPaymentConsentId:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"paymentElement:didCompleteFor:withPaymentConsentId:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentElement"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@Airwallex@objc(cs)AWXPaymentElement","text":"AWXPaymentElement"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didCompleteFor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withPaymentConsentId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElementDelegate\/paymentElement(_:didCompleteFor:withPaymentConsentId:)","url":"\/documentation\/airwallex\/awxpaymentelementdelegate\/paymentelement(_:didcompletefor:withpaymentconsentid:)","title":"paymentElement(_:didCompleteFor:withPaymentConsentId:)","type":"topic","abstract":[{"type":"text","text":"Called when a payment consent is created."}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElementDelegate":{"type":"topic","abstract":[{"text":"Delegate protocol for receiving payment events from AWXPaymentElement.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentElementDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"AWXPaymentElementDelegate"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElementDelegate","url":"\/documentation\/airwallex\/awxpaymentelementdelegate","title":"AWXPaymentElementDelegate"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElementDelegate/paymentElement(_:didCompleteFor:with:error:)":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"paymentElement:didCompleteFor:with:error:"}],"title":"paymentElement(_:didCompleteFor:with:error:)","required":true,"role":"symbol","abstract":[{"text":"Called when payment processing completes.","type":"text"}],"url":"\/documentation\/airwallex\/awxpaymentelementdelegate\/paymentelement(_:didcompletefor:with:error:)","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElementDelegate\/paymentElement(_:didCompleteFor:with:error:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentElement","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AWXPaymentElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@Airwallex@objc(cs)AWXPaymentElement"},{"text":", ","kind":"text"},{"text":"didCompleteFor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"text":"AirwallexPaymentStatus","kind":"typeIdentifier","preciseIdentifier":"c:@E@AirwallexPaymentStatus"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?)"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElementDelegate/paymentElement(_:validationFailedFor:invalidInputView:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentElement"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@Airwallex@objc(cs)AWXPaymentElement","text":"AWXPaymentElement"},{"kind":"text","text":", "},{"kind":"externalParam","text":"validationFailedFor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"invalidInputView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"paymentElement:validationFailedFor:invalidInputView:"}],"url":"\/documentation\/airwallex\/awxpaymentelementdelegate\/paymentelement(_:validationfailedfor:invalidinputview:)","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElementDelegate\/paymentElement(_:validationFailedFor:invalidInputView:)","type":"topic","abstract":[{"type":"text","text":"Called when input validation fails, allowing the host app to scroll the first"},{"type":"text","text":" "},{"type":"text","text":"invalid field into the visible area."}],"title":"paymentElement(_:validationFailedFor:invalidInputView:)","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"value":"AWXPaymentElementDelegate","path":"\/metadata\/title","op":"replace"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"AWXPaymentElementDelegate"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AWXPaymentElementDelegate"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElementDelegate\/paymentElement(_:didCompleteFor:with:error:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElementDelegate\/paymentElement(_:didCompleteFor:withPaymentConsentId:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElementDelegate\/paymentElement(_:onProcessingStateChangedFor:isProcessing:)","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElementDelegate\/paymentElement(_:validationFailedFor:invalidInputView:)"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true}],"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPaymentElementDelegate","kind":"identifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"paymentElement:onProcessingStateChangedFor:isProcessing:","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElementDelegate~1paymentElement(_:onProcessingStateChangedFor:isProcessing:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentElement:onProcessingStateChangedFor:isProcessing:"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElementDelegate~1paymentElement(_:onProcessingStateChangedFor:isProcessing:)\/fragments","op":"replace"},{"value":"paymentElement:didCompleteFor:withPaymentConsentId:","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElementDelegate~1paymentElement(_:didCompleteFor:withPaymentConsentId:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentElement:didCompleteFor:withPaymentConsentId:"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElementDelegate~1paymentElement(_:didCompleteFor:withPaymentConsentId:)\/fragments","op":"replace"},{"value":"AWXPaymentElementDelegate","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElementDelegate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AWXPaymentElementDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElementDelegate\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AWXPaymentElementDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElementDelegate\/navigatorTitle","op":"replace"},{"value":"paymentElement:didCompleteFor:with:error:","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElementDelegate~1paymentElement(_:didCompleteFor:with:error:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentElement:didCompleteFor:with:error:"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElementDelegate~1paymentElement(_:didCompleteFor:with:error:)\/fragments","op":"replace"},{"value":"paymentElement:validationFailedFor:invalidInputView:","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElementDelegate~1paymentElement(_:validationFailedFor:invalidInputView:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentElement:validationFailedFor:invalidInputView:"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElementDelegate~1paymentElement(_:validationFailedFor:invalidInputView:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}