{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handle"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"nextAction"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentNextAction","preciseIdentifier":"c:objc(cs)AWXConfirmPaymentNextAction","kind":"typeIdentifier","text":"AWXConfirmPaymentNextAction"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/airwallex\/awxnextactionhandler\/handle(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxnextactionhandler\/handle(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXNextActionHandler"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXNextActionHandler\/handle(_:)"},"kind":"symbol","metadata":{"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handle"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)AWXConfirmPaymentNextAction","kind":"typeIdentifier","text":"AWXConfirmPaymentNextAction"},{"kind":"text","text":")"}],"modules":[{"name":"Airwallex"}],"title":"handle(_:)","role":"symbol","roleHeading":"Instance Method","externalID":"c:objc(cs)AWXNextActionHandler(im)handleNextAction:","navigatorTitle":[{"kind":"identifier","text":"handleNextAction:"}]},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXNextActionHandler/handle(_:)":{"url":"\/documentation\/airwallex\/awxnextactionhandler\/handle(_:)","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXNextActionHandler\/handle(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"handle","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AWXConfirmPaymentNextAction","preciseIdentifier":"c:objc(cs)AWXConfirmPaymentNextAction","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"handleNextAction:","kind":"identifier"}],"title":"handle(_:)","kind":"symbol","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXNextActionHandler":{"role":"symbol","title":"AWXNextActionHandler","url":"\/documentation\/airwallex\/awxnextactionhandler","abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXNextActionHandler","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXNextActionHandler","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AWXNextActionHandler"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/airwallex","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXConfirmPaymentNextAction":{"url":"\/documentation\/airwallex\/awxconfirmpaymentnextaction","kind":"symbol","abstract":[{"code":"AWXConfirmPaymentNextAction","type":"codeVoice"},{"text":" includes the parameters for next action.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWXConfirmPaymentNextAction"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentNextAction","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXConfirmPaymentNextAction"}],"type":"topic","title":"AWXConfirmPaymentNextAction"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"handleNextAction:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"handleNextAction:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"handleNextAction:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AWXConfirmPaymentNextAction","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentNextAction","preciseIdentifier":"c:objc(cs)AWXConfirmPaymentNextAction"},{"text":" *) ","kind":"text"},{"text":"nextAction","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"handleNextAction:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXNextActionHandler~1handle(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"handleNextAction:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXNextActionHandler~1handle(_:)\/fragments"},{"value":"AWXNextActionHandler","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXNextActionHandler\/title"},{"value":[{"text":"AWXNextActionHandler","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXNextActionHandler\/fragments"},{"value":[{"kind":"identifier","text":"AWXNextActionHandler"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXNextActionHandler\/navigatorTitle"},{"value":"AWXConfirmPaymentNextAction","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentNextAction\/title"},{"value":[{"text":"AWXConfirmPaymentNextAction","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentNextAction\/fragments"},{"value":[{"text":"AWXConfirmPaymentNextAction","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentNextAction\/navigatorTitle"}]}]}