{"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetAvailableBanksRequest"]]},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetAvailableBanksRequest\/countryCode","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"countryCode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","abstract":[{"text":"Flow.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxgetavailablebanksrequest\/countrycode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxgetavailablebanksrequest\/countrycode"]}],"metadata":{"title":"countryCode","symbolKind":"property","role":"symbol","modules":[{"name":"Airwallex"}],"navigatorTitle":[{"text":"countryCode","kind":"identifier"}],"roleHeading":"Instance Property","externalID":"c:objc(cs)AWXGetAvailableBanksRequest(py)countryCode","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"countryCode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetAvailableBanksRequest/countryCode":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetAvailableBanksRequest\/countryCode","title":"countryCode","type":"topic","navigatorTitle":[{"text":"countryCode","kind":"identifier"}],"abstract":[{"type":"text","text":"Flow."}],"role":"symbol","url":"\/documentation\/airwallex\/awxgetavailablebanksrequest\/countrycode","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"countryCode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetAvailableBanksRequest":{"abstract":[{"code":"AWXGetPaymentMethodTypeRequest","type":"codeVoice"},{"text":" includes all of the parameters needed to get payment method type.","type":"text"}],"role":"symbol","type":"topic","title":"AWXGetAvailableBanksRequest","url":"\/documentation\/airwallex\/awxgetavailablebanksrequest","navigatorTitle":[{"text":"AWXGetAvailableBanksRequest","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetAvailableBanksRequest","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXGetAvailableBanksRequest","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","kind":"symbol","url":"\/documentation\/airwallex","abstract":[],"title":"Airwallex","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"countryCode","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"countryCode","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"countryCode"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetAvailableBanksRequest~1countryCode\/title","value":"countryCode","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetAvailableBanksRequest~1countryCode\/fragments","value":[{"kind":"identifier","text":"countryCode"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetAvailableBanksRequest\/title","value":"AWXGetAvailableBanksRequest","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetAvailableBanksRequest\/fragments","value":[{"text":"AWXGetAvailableBanksRequest","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetAvailableBanksRequest\/navigatorTitle","value":[{"text":"AWXGetAvailableBanksRequest","kind":"identifier"}],"op":"replace"}]}]}