{"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"handle","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"nextAction","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"AWXConfirmPaymentNextAction","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentNextAction","preciseIdentifier":"c:objc(cs)AWXConfirmPaymentNextAction"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"nextAction","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The response including next action."}]}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultActionProvider\/handle(_:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxdefaultactionprovider\/handle(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxdefaultactionprovider\/handle(_:)"]}],"abstract":[{"type":"text","text":"Start next action."}],"kind":"symbol","metadata":{"modules":[{"name":"Airwallex"}],"externalID":"c:objc(cs)AWXDefaultActionProvider(im)handleNextAction:","navigatorTitle":[{"text":"handleNextAction:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"handle","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AWXConfirmPaymentNextAction","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXConfirmPaymentNextAction"},{"kind":"text","text":")"}],"title":"handle(_:)","symbolKind":"method","roleHeading":"Instance Method","role":"symbol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultActionProvider"]]},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXDefaultActionProvider":{"type":"topic","navigatorTitle":[{"text":"AWXDefaultActionProvider","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultActionProvider","kind":"symbol","title":"AWXDefaultActionProvider","abstract":[{"text":"A provider which handles next action business.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXDefaultActionProvider"}],"role":"symbol","url":"\/documentation\/airwallex\/awxdefaultactionprovider"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXConfirmPaymentNextAction":{"url":"\/documentation\/airwallex\/awxconfirmpaymentnextaction","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXConfirmPaymentNextAction"}],"navigatorTitle":[{"text":"AWXConfirmPaymentNextAction","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentNextAction","title":"AWXConfirmPaymentNextAction","role":"symbol","abstract":[{"code":"AWXConfirmPaymentNextAction","type":"codeVoice"},{"text":" includes the parameters for next action.","type":"text"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/airwallex","title":"Airwallex","role":"collection"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXDefaultActionProvider/handle(_:)":{"role":"symbol","url":"\/documentation\/airwallex\/awxdefaultactionprovider\/handle(_:)","navigatorTitle":[{"kind":"identifier","text":"handleNextAction:"}],"title":"handle(_:)","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultActionProvider\/handle(_:)","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"handle","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)AWXConfirmPaymentNextAction","text":"AWXConfirmPaymentNextAction","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Start next action."}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"handleNextAction:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"handleNextAction:"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"handleNextAction:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AWXConfirmPaymentNextAction","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXConfirmPaymentNextAction","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentNextAction"},{"text":" *) ","kind":"text"},{"text":"nextAction","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The response including next action.","type":"text"}],"type":"paragraph"}],"name":"nextAction"}]}},{"value":"AWXDefaultActionProvider","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultActionProvider\/title"},{"op":"replace","value":[{"text":"AWXDefaultActionProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultActionProvider\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultActionProvider\/navigatorTitle","value":[{"kind":"identifier","text":"AWXDefaultActionProvider"}]},{"value":"AWXConfirmPaymentNextAction","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentNextAction\/title","op":"replace"},{"value":[{"text":"AWXConfirmPaymentNextAction","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentNextAction\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentNextAction\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AWXConfirmPaymentNextAction"}]},{"value":"handleNextAction:","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultActionProvider~1handle(_:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultActionProvider~1handle(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"handleNextAction:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}