{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextTriggerByType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@AirwallexNextTriggerByType","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexNextTriggerByType","text":"AirwallexNextTriggerByType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"Next trigger By type."}],"variants":[{"paths":["\/documentation\/airwallex\/awxcreatepaymentconsentrequest\/nexttriggerbytype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxcreatepaymentconsentrequest\/nexttriggerbytype"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCreatePaymentConsentRequest\/nextTriggerByType"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCreatePaymentConsentRequest"]]},"metadata":{"roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"nextTriggerByType"}],"role":"symbol","title":"nextTriggerByType","modules":[{"name":"Airwallex"}],"externalID":"c:objc(cs)AWXCreatePaymentConsentRequest(py)nextTriggerByType","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nextTriggerByType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AirwallexNextTriggerByType","kind":"typeIdentifier","preciseIdentifier":"c:@E@AirwallexNextTriggerByType"}]},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","kind":"symbol","url":"\/documentation\/airwallex","abstract":[],"title":"Airwallex","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexNextTriggerByType":{"abstract":[],"title":"AirwallexNextTriggerByType","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"AirwallexNextTriggerByType","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"AirwallexNextTriggerByType","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexNextTriggerByType","url":"\/documentation\/airwallex\/airwallexnexttriggerbytype"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCreatePaymentConsentRequest/nextTriggerByType":{"navigatorTitle":[{"kind":"identifier","text":"nextTriggerByType"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCreatePaymentConsentRequest\/nextTriggerByType","type":"topic","url":"\/documentation\/airwallex\/awxcreatepaymentconsentrequest\/nexttriggerbytype","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextTriggerByType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@AirwallexNextTriggerByType","text":"AirwallexNextTriggerByType"}],"abstract":[{"type":"text","text":"Next trigger By type."}],"role":"symbol","title":"nextTriggerByType","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCreatePaymentConsentRequest":{"role":"symbol","navigatorTitle":[{"text":"AWXCreatePaymentConsentRequest","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXCreatePaymentConsentRequest","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCreatePaymentConsentRequest","url":"\/documentation\/airwallex\/awxcreatepaymentconsentrequest","title":"AWXCreatePaymentConsentRequest","kind":"symbol","abstract":[{"type":"codeVoice","code":"AWXCreatePaymentConsentRequest"},{"type":"text","text":" includes the request of creating payment consent."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"nextTriggerByType","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"nextTriggerByType","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"text":") ","kind":"text"},{"text":"AirwallexNextTriggerByType","preciseIdentifier":"c:@E@AirwallexNextTriggerByType","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexNextTriggerByType"},{"text":" ","kind":"text"},{"text":"nextTriggerByType","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"AirwallexNextTriggerByType","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexNextTriggerByType\/title"},{"value":[{"text":"AirwallexNextTriggerByType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexNextTriggerByType\/fragments"},{"value":[{"kind":"identifier","text":"AirwallexNextTriggerByType"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexNextTriggerByType\/navigatorTitle"},{"value":"nextTriggerByType","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCreatePaymentConsentRequest~1nextTriggerByType\/title"},{"value":[{"kind":"identifier","text":"nextTriggerByType"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCreatePaymentConsentRequest~1nextTriggerByType\/fragments"},{"value":"AWXCreatePaymentConsentRequest","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCreatePaymentConsentRequest\/title"},{"value":[{"text":"AWXCreatePaymentConsentRequest","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCreatePaymentConsentRequest\/fragments"},{"value":[{"text":"AWXCreatePaymentConsentRequest","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCreatePaymentConsentRequest\/navigatorTitle"}]}]}