{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transactionCurrency","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypesRequest\/transactionCurrency"},"abstract":[{"text":"A currency code.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypesRequest"]]},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxgetpaymentmethodtypesrequest\/transactioncurrency"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxgetpaymentmethodtypesrequest\/transactioncurrency"]}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transactionCurrency","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","roleHeading":"Instance Property","title":"transactionCurrency","externalID":"c:objc(cs)AWXGetPaymentMethodTypesRequest(py)transactionCurrency","symbolKind":"property","navigatorTitle":[{"text":"transactionCurrency","kind":"identifier"}],"modules":[{"name":"Airwallex"}]},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","role":"collection","url":"\/documentation\/airwallex","kind":"symbol","title":"Airwallex","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentMethodTypesRequest/transactionCurrency":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypesRequest\/transactionCurrency","abstract":[{"text":"A currency code.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"transactionCurrency"}],"title":"transactionCurrency","kind":"symbol","type":"topic","url":"\/documentation\/airwallex\/awxgetpaymentmethodtypesrequest\/transactioncurrency","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"transactionCurrency"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentMethodTypesRequest":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXGetPaymentMethodTypesRequest"}],"type":"topic","role":"symbol","abstract":[{"type":"codeVoice","code":"AWXGetPaymentMethodTypesRequest"},{"type":"text","text":" includes all of the parameters needed to get payment method types."}],"navigatorTitle":[{"kind":"identifier","text":"AWXGetPaymentMethodTypesRequest"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypesRequest","url":"\/documentation\/airwallex\/awxgetpaymentmethodtypesrequest","title":"AWXGetPaymentMethodTypesRequest"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"transactionCurrency","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"transactionCurrency"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"transactionCurrency"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"transactionCurrency","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypesRequest~1transactionCurrency\/title"},{"op":"replace","value":[{"text":"transactionCurrency","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypesRequest~1transactionCurrency\/fragments"},{"op":"replace","value":"AWXGetPaymentMethodTypesRequest","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypesRequest\/title"},{"op":"replace","value":[{"text":"AWXGetPaymentMethodTypesRequest","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypesRequest\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AWXGetPaymentMethodTypesRequest"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypesRequest\/navigatorTitle"}]}]}