{"kind":"symbol","abstract":[{"text":"Device object.","type":"text"}],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"device"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWXDevice","preciseIdentifier":"c:objc(cs)AWXDevice"},{"kind":"text","text":"?"}],"externalID":"c:objc(cs)AWXVerifyPaymentConsentRequest(py)device","symbolKind":"property","navigatorTitle":[{"text":"device","kind":"identifier"}],"title":"device","modules":[{"name":"Airwallex"}],"roleHeading":"Instance Property"},"variants":[{"paths":["\/documentation\/airwallex\/awxverifypaymentconsentrequest\/device"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxverifypaymentconsentrequest\/device"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXVerifyPaymentConsentRequest"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"device"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDevice","text":"AWXDevice","preciseIdentifier":"c:objc(cs)AWXDevice"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}]}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXVerifyPaymentConsentRequest\/device","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXVerifyPaymentConsentRequest/device":{"abstract":[{"type":"text","text":"Device object."}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXVerifyPaymentConsentRequest\/device","title":"device","navigatorTitle":[{"kind":"identifier","text":"device"}],"url":"\/documentation\/airwallex\/awxverifypaymentconsentrequest\/device","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"device","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWXDevice","preciseIdentifier":"c:objc(cs)AWXDevice","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXVerifyPaymentConsentRequest":{"url":"\/documentation\/airwallex\/awxverifypaymentconsentrequest","kind":"symbol","abstract":[{"type":"codeVoice","code":"AWXVerifyPaymentConsentRequest"},{"type":"text","text":" includes the request of verifying payment consent."}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AWXVerifyPaymentConsentRequest","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AWXVerifyPaymentConsentRequest"}],"title":"AWXVerifyPaymentConsentRequest","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXVerifyPaymentConsentRequest"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"abstract":[],"kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","url":"\/documentation\/airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXDevice":{"kind":"symbol","url":"\/documentation\/airwallex\/awxdevice","abstract":[{"code":"AWXDevice","type":"codeVoice"},{"text":" includes the information of device.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXDevice"}],"navigatorTitle":[{"kind":"identifier","text":"AWXDevice"}],"title":"AWXDevice","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDevice"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"device"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"device"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXDevice","text":"AWXDevice","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDevice"},{"kind":"text","text":" * "},{"kind":"identifier","text":"device"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXVerifyPaymentConsentRequest~1device\/title","value":"device"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXVerifyPaymentConsentRequest~1device\/fragments","value":[{"kind":"identifier","text":"device"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXVerifyPaymentConsentRequest\/title","value":"AWXVerifyPaymentConsentRequest"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXVerifyPaymentConsentRequest\/fragments","value":[{"kind":"identifier","text":"AWXVerifyPaymentConsentRequest"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXVerifyPaymentConsentRequest\/navigatorTitle","value":[{"kind":"identifier","text":"AWXVerifyPaymentConsentRequest"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDevice\/title","value":"AWXDevice"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDevice\/fragments","value":[{"kind":"identifier","text":"AWXDevice"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDevice\/navigatorTitle","value":[{"kind":"identifier","text":"AWXDevice"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}