{"sections":[],"metadata":{"externalID":"c:objc(cs)AWXViewController(im)startAnimating","roleHeading":"Instance Method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startAnimating","kind":"identifier"},{"text":"()","kind":"text"}],"modules":[{"name":"Airwallex"}],"navigatorTitle":[{"text":"startAnimating","kind":"identifier"}],"title":"startAnimating()","symbolKind":"method"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startAnimating"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXViewController\/startAnimating()","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/airwallex\/awxviewcontroller\/startanimating()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxviewcontroller\/startanimating()"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","abstract":[{"text":"Show loading activity.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXViewController"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXViewController/startAnimating()":{"kind":"symbol","type":"topic","title":"startAnimating()","navigatorTitle":[{"text":"startAnimating","kind":"identifier"}],"role":"symbol","url":"\/documentation\/airwallex\/awxviewcontroller\/startanimating()","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXViewController\/startAnimating()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startAnimating","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[{"text":"Show loading activity.","type":"text"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXViewController":{"navigatorTitle":[{"kind":"identifier","text":"AWXViewController"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXViewController"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXViewController","type":"topic","abstract":[{"code":"AWXViewController","type":"codeVoice"},{"text":" is the base view controller.","type":"text"}],"kind":"symbol","url":"\/documentation\/airwallex\/awxviewcontroller","title":"AWXViewController"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","title":"Airwallex","abstract":[],"type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"startAnimating","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"startAnimating","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"startAnimating","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"startAnimating","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXViewController~1startAnimating()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"startAnimating","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXViewController~1startAnimating()\/fragments","op":"replace"},{"value":"AWXViewController","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXViewController\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AWXViewController"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXViewController\/fragments","op":"replace"},{"value":[{"text":"AWXViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXViewController\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}