{"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"navigatorTitle":[{"text":"toolbarColor","kind":"identifier"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toolbarColor","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"symbolKind":"method","roleHeading":"Instance Method","title":"toolbarColor()","externalID":"c:objc(cs)AWXTheme(im)toolbarColor","modules":[{"name":"Airwallex"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toolbarColor","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme"]]},"variants":[{"paths":["\/documentation\/airwallex\/awxtheme\/toolbarcolor()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxtheme\/toolbarcolor()"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme\/toolbarColor()","interfaceLanguage":"swift"},"sections":[],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXTheme/toolbarColor()":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme\/toolbarColor()","abstract":[],"url":"\/documentation\/airwallex\/awxtheme\/toolbarcolor()","title":"toolbarColor()","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toolbarColor"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"toolbarColor"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","abstract":[],"role":"collection","url":"\/documentation\/airwallex","title":"Airwallex","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXTheme":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXTheme"}],"navigatorTitle":[{"kind":"identifier","text":"AWXTheme"}],"abstract":[{"code":"AWXTheme","type":"codeVoice"},{"type":"text","text":" manages text styles."}],"type":"topic","kind":"symbol","title":"AWXTheme","url":"\/documentation\/airwallex\/awxtheme","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"toolbarColor"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"toolbarColor","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"toolbarColor"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTheme~1toolbarColor()\/title","value":"toolbarColor"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTheme~1toolbarColor()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"toolbarColor","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTheme\/title","value":"AWXTheme"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTheme\/fragments","value":[{"kind":"identifier","text":"AWXTheme"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTheme\/navigatorTitle","value":[{"kind":"identifier","text":"AWXTheme"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}