{"metadata":{"modules":[{"name":"Airwallex"}],"navigatorTitle":[{"kind":"identifier","text":"AWXRequiredBillingContactFieldName"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"name","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@AWXRequiredBillingContactFields","text":"RequiredBillingContactFields","kind":"typeIdentifier"}],"role":"symbol","roleHeading":"Type Property","externalID":"c:@E@AWXRequiredBillingContactFields@AWXRequiredBillingContactFieldName","title":"name","symbolKind":"property"},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/RequiredBillingContactFields","kind":"typeIdentifier","text":"RequiredBillingContactFields","preciseIdentifier":"c:@E@AWXRequiredBillingContactFields"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/RequiredBillingContactFields"]]},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/RequiredBillingContactFields\/name","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/requiredbillingcontactfields\/name"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/requiredbillingcontactfields\/name"]}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/RequiredBillingContactFields":{"kind":"symbol","navigatorTitle":[{"text":"RequiredBillingContactFields","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RequiredBillingContactFields","kind":"identifier"}],"abstract":[],"title":"RequiredBillingContactFields","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/RequiredBillingContactFields","url":"\/documentation\/airwallex\/requiredbillingcontactfields"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"kind":"symbol","abstract":[],"role":"collection","type":"topic","url":"\/documentation\/airwallex","title":"Airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/RequiredBillingContactFields/name":{"url":"\/documentation\/airwallex\/requiredbillingcontactfields\/name","title":"name","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/RequiredBillingContactFields\/name","abstract":[],"navigatorTitle":[{"text":"AWXRequiredBillingContactFieldName","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"name","kind":"identifier"},{"kind":"text","text":": "},{"text":"RequiredBillingContactFields","kind":"typeIdentifier","preciseIdentifier":"c:@E@AWXRequiredBillingContactFields"}],"kind":"symbol","role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"AWXRequiredBillingContactFieldName","path":"\/metadata\/title"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"AWXRequiredBillingContactFieldName","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"AWXRequiredBillingContactFieldName","kind":"identifier"}]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1RequiredBillingContactFields\/title","value":"AWXRequiredBillingContactFields","op":"replace"},{"op":"replace","value":[{"text":"AWXRequiredBillingContactFields","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1RequiredBillingContactFields\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AWXRequiredBillingContactFields"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1RequiredBillingContactFields\/navigatorTitle"},{"op":"replace","value":"AWXRequiredBillingContactFieldName","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1RequiredBillingContactFields~1name\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AWXRequiredBillingContactFieldName"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1RequiredBillingContactFields~1name\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}