{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"phone"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/RequiredBillingContactFields","preciseIdentifier":"c:@E@AWXRequiredBillingContactFields","text":"RequiredBillingContactFields"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/requiredbillingcontactfields\/phone"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/requiredbillingcontactfields\/phone"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/RequiredBillingContactFields\/phone"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/RequiredBillingContactFields"]]},"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"AWXRequiredBillingContactFieldPhone"}],"modules":[{"name":"Airwallex"}],"title":"phone","externalID":"c:@E@AWXRequiredBillingContactFields@AWXRequiredBillingContactFieldPhone","symbolKind":"property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"phone"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RequiredBillingContactFields","preciseIdentifier":"c:@E@AWXRequiredBillingContactFields"}],"roleHeading":"Type Property","role":"symbol"},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","abstract":[],"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/RequiredBillingContactFields":{"title":"RequiredBillingContactFields","role":"symbol","url":"\/documentation\/airwallex\/requiredbillingcontactfields","navigatorTitle":[{"text":"RequiredBillingContactFields","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RequiredBillingContactFields","kind":"identifier"}],"abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/RequiredBillingContactFields"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/RequiredBillingContactFields/phone":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/RequiredBillingContactFields\/phone","kind":"symbol","title":"phone","url":"\/documentation\/airwallex\/requiredbillingcontactfields\/phone","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWXRequiredBillingContactFieldPhone"}],"type":"topic","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"phone","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@AWXRequiredBillingContactFields","text":"RequiredBillingContactFields","kind":"typeIdentifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"AWXRequiredBillingContactFieldPhone","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AWXRequiredBillingContactFieldPhone"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"AWXRequiredBillingContactFieldPhone","kind":"identifier"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1RequiredBillingContactFields\/title","value":"AWXRequiredBillingContactFields","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1RequiredBillingContactFields\/fragments","value":[{"kind":"identifier","text":"AWXRequiredBillingContactFields"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1RequiredBillingContactFields\/navigatorTitle","value":[{"text":"AWXRequiredBillingContactFields","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1RequiredBillingContactFields~1phone\/title","value":"AWXRequiredBillingContactFieldPhone","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1RequiredBillingContactFields~1phone\/fragments","value":[{"text":"AWXRequiredBillingContactFieldPhone","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}