{"sections":[],"topicSections":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXHTTPMethod\/hashValue"]},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXHTTPMethod\/hash(into:)"]}],"metadata":{"role":"collectionGroup","roleHeading":"API Collection","modules":[{"name":"Airwallex"}],"title":"RawRepresentable Implementations"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXHTTPMethod"]]},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXHTTPMethod\/RawRepresentable-Implementations","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"article","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxhttpmethod\/rawrepresentable-implementations"]}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXHTTPMethod":{"navigatorTitle":[{"text":"AWXHTTPMethod","kind":"identifier"}],"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXHTTPMethod","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXHTTPMethod","kind":"symbol","url":"\/documentation\/airwallex\/awxhttpmethod","title":"AWXHTTPMethod","abstract":[{"type":"text","text":"Http request"}],"role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","url":"\/documentation\/airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol","title":"Airwallex","abstract":[],"role":"collection"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXHTTPMethod/hash(into:)":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXHTTPMethod\/hash(into:)","role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hasher","kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV"},{"text":")","kind":"text"}],"kind":"symbol","title":"hash(into:)","url":"\/documentation\/airwallex\/awxhttpmethod\/hash(into:)","conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}]}},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXHTTPMethod/hashValue":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXHTTPMethod\/hashValue","abstract":[],"kind":"symbol","role":"symbol","conformance":{"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}]},"title":"hashValue","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"url":"\/documentation\/airwallex\/awxhttpmethod\/hashvalue","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXHTTPMethod\/title","value":"AWXHTTPMethod"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXHTTPMethod\/fragments","value":[{"text":"AWXHTTPMethod","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXHTTPMethod\/navigatorTitle","value":[{"kind":"identifier","text":"AWXHTTPMethod"}]}]}]}