{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Airwallex"]]},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Airwallex\/disableAnalytics()","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableAnalytics"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"text":"Disable analytics.","type":"text"}],"metadata":{"externalID":"c:objc(cs)Airwallex(cm)disableAnalytics","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disableAnalytics","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","symbolKind":"method","roleHeading":"Type Method","modules":[{"name":"Airwallex"}],"navigatorTitle":[{"text":"disableAnalytics","kind":"identifier"}],"title":"disableAnalytics()"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/airwallex\/disableanalytics()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/airwallex\/disableanalytics()"]}],"sections":[],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","role":"collection","url":"\/documentation\/airwallex","kind":"symbol","title":"Airwallex","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/Airwallex":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Airwallex","kind":"symbol","title":"Airwallex","url":"\/documentation\/airwallex\/airwallex","abstract":[{"code":"Airwallex","type":"codeVoice"},{"type":"text","text":" contains the base configuration the SDK needs."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Airwallex","kind":"identifier"}],"navigatorTitle":[{"text":"Airwallex","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/Airwallex/disableAnalytics()":{"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Airwallex\/disableAnalytics()","role":"symbol","title":"disableAnalytics()","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disableAnalytics","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"disableAnalytics","kind":"identifier"}],"url":"\/documentation\/airwallex\/airwallex\/disableanalytics()","abstract":[{"type":"text","text":"Disable analytics."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","value":"disableAnalytics","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"disableAnalytics","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"disableAnalytics"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Airwallex\/title","op":"replace","value":"Airwallex"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Airwallex\/fragments","op":"replace","value":[{"kind":"identifier","text":"Airwallex"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Airwallex\/navigatorTitle","op":"replace","value":[{"text":"Airwallex","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Airwallex~1disableAnalytics()\/title","op":"replace","value":"disableAnalytics"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Airwallex~1disableAnalytics()\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"disableAnalytics"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}