{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cardOptions","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWXCardOptions","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXCardOptions","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardOptions"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"kind":"symbol","sections":[],"abstract":[{"text":"The options for card.","type":"text"}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethodOptions\/cardOptions","interfaceLanguage":"swift"},"metadata":{"externalID":"c:objc(cs)AWXPaymentMethodOptions(py)cardOptions","role":"symbol","roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"Airwallex"}],"navigatorTitle":[{"text":"cardOptions","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cardOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWXCardOptions","preciseIdentifier":"c:objc(cs)AWXCardOptions"},{"kind":"text","text":"?"}],"title":"cardOptions"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethodOptions"]]},"variants":[{"paths":["\/documentation\/airwallex\/awxpaymentmethodoptions\/cardoptions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxpaymentmethodoptions\/cardoptions"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentMethodOptions":{"type":"topic","title":"AWXPaymentMethodOptions","navigatorTitle":[{"kind":"identifier","text":"AWXPaymentMethodOptions"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethodOptions","kind":"symbol","url":"\/documentation\/airwallex\/awxpaymentmethodoptions","abstract":[{"type":"codeVoice","code":"AWXPaymentMethodOptions"},{"type":"text","text":" includes the information of payment method options"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentMethodOptions"}],"role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentMethodOptions/cardOptions":{"abstract":[{"type":"text","text":"The options for card."}],"title":"cardOptions","url":"\/documentation\/airwallex\/awxpaymentmethodoptions\/cardoptions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cardOptions"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AWXCardOptions","text":"AWXCardOptions","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"cardOptions","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethodOptions\/cardOptions","type":"topic","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol","type":"topic","url":"\/documentation\/airwallex","role":"collection","abstract":[],"title":"Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardOptions":{"title":"AWXCardOptions","type":"topic","url":"\/documentation\/airwallex\/awxcardoptions","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardOptions","role":"symbol","navigatorTitle":[{"text":"AWXCardOptions","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXCardOptions","kind":"identifier"}],"abstract":[{"code":"AWXCardOptions","type":"codeVoice"},{"text":" includes the options of card.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"cardOptions"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"cardOptions","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardOptions","preciseIdentifier":"c:objc(cs)AWXCardOptions","text":"AWXCardOptions"},{"kind":"text","text":" * "},{"kind":"identifier","text":"cardOptions"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethodOptions\/title","value":"AWXPaymentMethodOptions"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethodOptions\/fragments","value":[{"text":"AWXPaymentMethodOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethodOptions\/navigatorTitle","value":[{"text":"AWXPaymentMethodOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethodOptions~1cardOptions\/title","value":"cardOptions"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethodOptions~1cardOptions\/fragments","value":[{"kind":"identifier","text":"cardOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardOptions\/title","value":"AWXCardOptions"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardOptions\/fragments","value":[{"text":"AWXCardOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardOptions\/navigatorTitle","value":[{"text":"AWXCardOptions","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}