{"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"brand"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forCardNumber"},{"kind":"text","text":" "},{"kind":"internalParam","text":"cardNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrand","preciseIdentifier":"c:objc(cs)AWXBrand","text":"AWXBrand"}]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardValidator"]]},"variants":[{"paths":["\/documentation\/airwallex\/awxcardvalidator\/brand(forcardnumber:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxcardvalidator\/brand(forcardnumber:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"roleHeading":"Instance Method","role":"symbol","externalID":"c:objc(cs)AWXCardValidator(im)brandForCardNumber:","modules":[{"name":"Airwallex"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"brand","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forCardNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AWXBrand","text":"AWXBrand","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"brandForCardNumber:","kind":"identifier"}],"title":"brand(forCardNumber:)","symbolKind":"method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardValidator\/brand(forCardNumber:)"},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXBrand":{"abstract":[{"code":"AWXBrand","type":"codeVoice"},{"text":" manages the card scheme brand.","type":"text"}],"url":"\/documentation\/airwallex\/awxbrand","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrand","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXBrand","kind":"identifier"}],"title":"AWXBrand","role":"symbol","navigatorTitle":[{"text":"AWXBrand","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","abstract":[],"role":"collection","url":"\/documentation\/airwallex","title":"Airwallex","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardValidator/brand(forCardNumber:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardValidator\/brand(forCardNumber:)","kind":"symbol","role":"symbol","abstract":[],"title":"brand(forCardNumber:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"brand","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forCardNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AWXBrand","text":"AWXBrand","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"brandForCardNumber:"}],"url":"\/documentation\/airwallex\/awxcardvalidator\/brand(forcardnumber:)"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardValidator":{"kind":"symbol","abstract":[{"type":"codeVoice","code":"AWXCardValidator"},{"text":" manages the card info.","type":"text"}],"url":"\/documentation\/airwallex\/awxcardvalidator","navigatorTitle":[{"text":"AWXCardValidator","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardValidator","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXCardValidator","kind":"identifier"}],"title":"AWXCardValidator","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"brandForCardNumber:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"brandForCardNumber:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrand","preciseIdentifier":"c:objc(cs)AWXBrand","text":"AWXBrand"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"brandForCardNumber:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cardNumber"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"AWXBrand","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrand\/title","op":"replace"},{"value":[{"text":"AWXBrand","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrand\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AWXBrand"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrand\/navigatorTitle","op":"replace"},{"value":"brandForCardNumber:","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardValidator~1brand(forCardNumber:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"brandForCardNumber:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardValidator~1brand(forCardNumber:)\/fragments","op":"replace"},{"value":"AWXCardValidator","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardValidator\/title","op":"replace"},{"value":[{"text":"AWXCardValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardValidator\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AWXCardValidator"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardValidator\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}