{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"metadata":{"navigatorTitle":[{"text":"possibleBrandTypesForCardNumber:","kind":"identifier"}],"title":"possibleBrandTypes(forCardNumber:)","modules":[{"name":"Airwallex"}],"roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"possibleBrandTypes","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forCardNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> [","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"role":"symbol","externalID":"c:objc(cs)AWXCardValidator(im)possibleBrandTypesForCardNumber:"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardValidator"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"possibleBrandTypes","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forCardNumber","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"cardNumber","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") -> [","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/airwallex\/awxcardvalidator\/possiblebrandtypes(forcardnumber:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxcardvalidator\/possiblebrandtypes(forcardnumber:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardValidator\/possibleBrandTypes(forCardNumber:)","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"title":"Airwallex","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/airwallex","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardValidator/possibleBrandTypes(forCardNumber:)":{"title":"possibleBrandTypes(forCardNumber:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"possibleBrandTypesForCardNumber:"}],"abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"possibleBrandTypes"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forCardNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"]"}],"kind":"symbol","type":"topic","url":"\/documentation\/airwallex\/awxcardvalidator\/possiblebrandtypes(forcardnumber:)","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardValidator\/possibleBrandTypes(forCardNumber:)"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardValidator":{"navigatorTitle":[{"text":"AWXCardValidator","kind":"identifier"}],"kind":"symbol","type":"topic","title":"AWXCardValidator","abstract":[{"type":"codeVoice","code":"AWXCardValidator"},{"type":"text","text":" manages the card info."}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardValidator","url":"\/documentation\/airwallex\/awxcardvalidator","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXCardValidator","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"possibleBrandTypesForCardNumber:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"possibleBrandTypesForCardNumber:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSArray<NSNumber *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"possibleBrandTypesForCardNumber:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cardNumber"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardValidator~1possibleBrandTypes(forCardNumber:)\/title","value":"possibleBrandTypesForCardNumber:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardValidator~1possibleBrandTypes(forCardNumber:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"possibleBrandTypesForCardNumber:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardValidator\/title","value":"AWXCardValidator"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardValidator\/fragments","value":[{"text":"AWXCardValidator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardValidator\/navigatorTitle","value":[{"text":"AWXCardValidator","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}