{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider\/complete(with:error:)"},"abstract":[{"type":"text","text":"Complete the payment flow."}],"kind":"symbol","metadata":{"roleHeading":"Instance Method","modules":[{"name":"Airwallex"}],"navigatorTitle":[{"kind":"identifier","text":"completeWithResponse:error:"}],"role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AWXDefaultProvider(im)completeWithResponse:error:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"complete"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXConfirmPaymentIntentResponse","text":"AWXConfirmPaymentIntentResponse"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")?)"}],"title":"complete(with:error:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"complete","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"response","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"AWXConfirmPaymentIntentResponse","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentResponse","preciseIdentifier":"c:objc(cs)AWXConfirmPaymentIntentResponse"},{"text":"?, ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": (any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"response","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The payment response."}]}]},{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The error of payment flow."}]}]}]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxdefaultprovider\/complete(with:error:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxdefaultprovider\/complete(with:error:)"]}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","url":"\/documentation\/airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol","title":"Airwallex","abstract":[],"role":"collection"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXDefaultProvider":{"url":"\/documentation\/airwallex\/awxdefaultprovider","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXDefaultProvider","kind":"identifier"}],"abstract":[{"type":"text","text":"A provider which handles payment business."}],"navigatorTitle":[{"text":"AWXDefaultProvider","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider","title":"AWXDefaultProvider","type":"topic","role":"symbol","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXDefaultProvider/complete(with:error:)":{"role":"symbol","url":"\/documentation\/airwallex\/awxdefaultprovider\/complete(with:error:)","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Complete the payment flow."}],"navigatorTitle":[{"kind":"identifier","text":"completeWithResponse:error:"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider\/complete(with:error:)","title":"complete(with:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"complete"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWXConfirmPaymentIntentResponse","preciseIdentifier":"c:objc(cs)AWXConfirmPaymentIntentResponse"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?)"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXConfirmPaymentIntentResponse":{"type":"topic","title":"AWXConfirmPaymentIntentResponse","kind":"symbol","navigatorTitle":[{"text":"AWXConfirmPaymentIntentResponse","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxconfirmpaymentintentresponse","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentResponse","role":"symbol","abstract":[{"code":"AWXConfirmPaymentIntentResponse","type":"codeVoice"},{"text":" includes the result of payment flow.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXConfirmPaymentIntentResponse","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"completeWithResponse:error:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"completeWithResponse:error:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"completeWithResponse:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)AWXConfirmPaymentIntentResponse","text":"AWXConfirmPaymentIntentResponse","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentResponse"},{"text":" *) ","kind":"text"},{"text":"response","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The payment response."}]}],"name":"response"},{"content":[{"inlineContent":[{"text":"The error of payment flow.","type":"text"}],"type":"paragraph"}],"name":"error"}]},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"AWXDefaultProvider","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AWXDefaultProvider"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider\/fragments","op":"replace"},{"value":[{"text":"AWXDefaultProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider\/navigatorTitle","op":"replace"},{"value":"completeWithResponse:error:","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider~1complete(with:error:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"completeWithResponse:error:"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider~1complete(with:error:)\/fragments","op":"replace"},{"value":"AWXConfirmPaymentIntentResponse","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentResponse\/title","op":"replace"},{"value":[{"text":"AWXConfirmPaymentIntentResponse","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentResponse\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AWXConfirmPaymentIntentResponse"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentResponse\/navigatorTitle","op":"replace"}]}]}