{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxdefaultprovider\/confirmpaymentintent(with:paymentconsent:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxdefaultprovider\/confirmpaymentintent(with:paymentconsent:completion:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider"]]},"abstract":[{"text":"Confirm the payment intent with payment method and consent as well as a custom completion block.","type":"text"}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider\/confirmPaymentIntent(with:paymentConsent:completion:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"confirmPaymentIntent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"paymentMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod","text":"AWXPaymentMethod","preciseIdentifier":"c:objc(cs)AWXPaymentMethod"},{"kind":"text","text":", "},{"kind":"externalParam","text":"paymentConsent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentConsent","text":"AWXPaymentConsent","preciseIdentifier":"c:objc(cs)AWXPaymentConsent"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"keyword","text":"@escaping"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRequestHandler","text":"AWXRequestHandler","preciseIdentifier":"c:AWXAPIClient.h@T@AWXRequestHandler"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]},{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"confirmPaymentIntent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"paymentMethod"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AWXPaymentMethod","kind":"typeIdentifier","text":"AWXPaymentMethod","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod"},{"kind":"text","text":", "},{"kind":"externalParam","text":"paymentConsent"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentConsent","kind":"typeIdentifier","text":"AWXPaymentConsent","preciseIdentifier":"c:objc(cs)AWXPaymentConsent"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXResponse","kind":"typeIdentifier","text":"AWXResponse","preciseIdentifier":"c:objc(cs)AWXResponse"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"paymentMethod","content":[{"inlineContent":[{"text":"The payment method info.","type":"text"}],"type":"paragraph"}]},{"name":"paymentConsent","content":[{"inlineContent":[{"type":"text","text":"The payment consent info."}],"type":"paragraph"}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The completion block to be called with the response and error."}]}]}]}],"metadata":{"title":"confirmPaymentIntent(with:paymentConsent:completion:)","symbolKind":"method","navigatorTitle":[{"text":"confirmPaymentIntentWithPaymentMethod:paymentConsent:completion:","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Method","externalID":"c:objc(cs)AWXDefaultProvider(im)confirmPaymentIntentWithPaymentMethod:paymentConsent:completion:","modules":[{"name":"Airwallex"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confirmPaymentIntent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AWXPaymentMethod","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPaymentMethod"},{"text":", ","kind":"text"},{"text":"paymentConsent","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AWXPaymentConsent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPaymentConsent"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWXRequestHandler","preciseIdentifier":"c:AWXAPIClient.h@T@AWXRequestHandler"},{"kind":"text","text":")"}]},"kind":"symbol","references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRequestHandler":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRequestHandler","url":"\/documentation\/airwallex\/awxrequesthandler","type":"topic","abstract":[],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXRequestHandler"}],"navigatorTitle":[{"kind":"identifier","text":"AWXRequestHandler"}],"title":"AWXRequestHandler"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXResponse":{"role":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXResponse","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXResponse","title":"AWXResponse","kind":"symbol","url":"\/documentation\/airwallex\/awxresponse","navigatorTitle":[{"text":"AWXResponse","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXDefaultProvider":{"navigatorTitle":[{"text":"AWXDefaultProvider","kind":"identifier"}],"abstract":[{"type":"text","text":"A provider which handles payment business."}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider","url":"\/documentation\/airwallex\/awxdefaultprovider","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXDefaultProvider","kind":"identifier"}],"type":"topic","title":"AWXDefaultProvider","role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXDefaultProvider/confirmPaymentIntent(with:paymentConsent:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"confirmPaymentIntentWithPaymentMethod:paymentConsent:completion:"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"confirmPaymentIntent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWXPaymentMethod","preciseIdentifier":"c:objc(cs)AWXPaymentMethod"},{"kind":"text","text":", "},{"kind":"externalParam","text":"paymentConsent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWXPaymentConsent","preciseIdentifier":"c:objc(cs)AWXPaymentConsent"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWXRequestHandler","preciseIdentifier":"c:AWXAPIClient.h@T@AWXRequestHandler"},{"kind":"text","text":")"}],"kind":"symbol","abstract":[{"type":"text","text":"Confirm the payment intent with payment method and consent as well as a custom completion block."}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider\/confirmPaymentIntent(with:paymentConsent:completion:)","role":"symbol","url":"\/documentation\/airwallex\/awxdefaultprovider\/confirmpaymentintent(with:paymentconsent:completion:)","title":"confirmPaymentIntent(with:paymentConsent:completion:)"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"abstract":[],"url":"\/documentation\/airwallex","role":"collection","title":"Airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","type":"topic","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentConsent":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentConsent","navigatorTitle":[{"kind":"identifier","text":"AWXPaymentConsent"}],"title":"AWXPaymentConsent","role":"symbol","abstract":[{"type":"codeVoice","code":"AWXPaymentConsent"},{"type":"text","text":" includes the info of payment consent."}],"url":"\/documentation\/airwallex\/awxpaymentconsent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentConsent"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentMethod":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPaymentMethod","kind":"identifier"}],"title":"AWXPaymentMethod","url":"\/documentation\/airwallex\/awxpaymentmethod","navigatorTitle":[{"text":"AWXPaymentMethod","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"code":"AWXPaymentMethod","type":"codeVoice"},{"type":"text","text":" includes the information of a payment method."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"confirmPaymentIntentWithPaymentMethod:paymentConsent:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"confirmPaymentIntentWithPaymentMethod:paymentConsent:completion:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"confirmPaymentIntentWithPaymentMethod:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod","kind":"typeIdentifier","text":"AWXPaymentMethod","preciseIdentifier":"c:objc(cs)AWXPaymentMethod"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"paymentMethod"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentConsent:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentConsent","kind":"typeIdentifier","text":"AWXPaymentConsent","preciseIdentifier":"c:objc(cs)AWXPaymentConsent"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"paymentConsent"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRequestHandler","kind":"typeIdentifier","text":"AWXRequestHandler","preciseIdentifier":"c:AWXAPIClient.h@T@AWXRequestHandler"},{"kind":"text","text":") "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"paymentMethod","content":[{"type":"paragraph","inlineContent":[{"text":"The payment method info.","type":"text"}]}]},{"name":"paymentConsent","content":[{"inlineContent":[{"text":"The payment consent info.","type":"text"}],"type":"paragraph"}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The completion block to be called with the response and error."}]}]}],"kind":"parameters"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRequestHandler\/title","value":"AWXRequestHandler"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRequestHandler\/fragments","value":[{"text":"AWXRequestHandler","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRequestHandler\/navigatorTitle","value":[{"text":"AWXRequestHandler","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXResponse\/title","value":"AWXResponse"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXResponse\/fragments","value":[{"text":"AWXResponse","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXResponse\/navigatorTitle","value":[{"kind":"identifier","text":"AWXResponse"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider\/title","value":"AWXDefaultProvider"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider\/fragments","value":[{"text":"AWXDefaultProvider","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider\/navigatorTitle","value":[{"text":"AWXDefaultProvider","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider~1confirmPaymentIntent(with:paymentConsent:completion:)\/title","value":"confirmPaymentIntentWithPaymentMethod:paymentConsent:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider~1confirmPaymentIntent(with:paymentConsent:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"confirmPaymentIntentWithPaymentMethod:paymentConsent:completion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentConsent\/title","value":"AWXPaymentConsent"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentConsent\/fragments","value":[{"kind":"identifier","text":"AWXPaymentConsent"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentConsent\/navigatorTitle","value":[{"text":"AWXPaymentConsent","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethod\/title","value":"AWXPaymentMethod"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethod\/fragments","value":[{"text":"AWXPaymentMethod","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethod\/navigatorTitle","value":[{"text":"AWXPaymentMethod","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}