{"metadata":{"roleHeading":"Initializer","navigatorTitle":[{"kind":"identifier","text":"initWithDelegate:session:"}],"externalID":"c:objc(cs)AWXDefaultProvider(im)initWithDelegate:session:","modules":[{"name":"Airwallex"}],"title":"init(delegate:session:)","role":"symbol","symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"delegate"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","text":"AWXProviderDelegate","preciseIdentifier":"c:objc(pl)AWXProviderDelegate"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"session"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXSession","text":"AWXSession"},{"kind":"text","text":")"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxdefaultprovider\/init(delegate:session:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxdefaultprovider\/init(delegate:session:)"]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": any "},{"text":"AWXProviderDelegate","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXProviderDelegate","preciseIdentifier":"c:objc(pl)AWXProviderDelegate"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"session"},{"kind":"text","text":": "},{"text":"AWXSession","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession","preciseIdentifier":"c:objc(cs)AWXSession"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider\/init(delegate:session:)"},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXProviderDelegate":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXProviderDelegate","abstract":[{"type":"text","text":"A delegate which handles checkout results."}],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/airwallex\/awxproviderdelegate","navigatorTitle":[{"text":"AWXProviderDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXProviderDelegate","kind":"identifier"}],"title":"AWXProviderDelegate"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSession":{"type":"topic","url":"\/documentation\/airwallex\/awxsession","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AWXSession","kind":"identifier"}],"navigatorTitle":[{"text":"AWXSession","kind":"identifier"}],"title":"AWXSession","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession","kind":"symbol","role":"symbol","abstract":[{"code":"AWXSession","type":"codeVoice"},{"type":"text","text":" is the base session."}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXDefaultProvider":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider","kind":"symbol","title":"AWXDefaultProvider","abstract":[{"type":"text","text":"A provider which handles payment business."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXDefaultProvider","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxdefaultprovider","navigatorTitle":[{"text":"AWXDefaultProvider","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","url":"\/documentation\/airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","kind":"symbol","role":"collection","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXDefaultProvider/init(delegate:session:)":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider\/init(delegate:session:)","kind":"symbol","title":"init(delegate:session:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"AWXProviderDelegate","preciseIdentifier":"c:objc(pl)AWXProviderDelegate","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"session","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AWXSession","preciseIdentifier":"c:objc(cs)AWXSession","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/airwallex\/awxdefaultprovider\/init(delegate:session:)","navigatorTitle":[{"text":"initWithDelegate:session:","kind":"identifier"}],"type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"initWithDelegate:session:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDelegate:session:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithDelegate:"},{"text":"(","kind":"text"},{"text":"id<AWXProviderDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)AWXProviderDelegate"},{"text":") ","kind":"text"},{"text":"delegate","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"session:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXSession","text":"AWXSession"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"session"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"AWXProviderDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXProviderDelegate\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXProviderDelegate\/fragments","op":"replace","value":[{"text":"AWXProviderDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXProviderDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"AWXProviderDelegate"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/title","value":"AWXSession"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/fragments","value":[{"kind":"identifier","text":"AWXSession"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/navigatorTitle","value":[{"text":"AWXSession","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider\/title","op":"replace","value":"AWXDefaultProvider"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider\/fragments","op":"replace","value":[{"kind":"identifier","text":"AWXDefaultProvider"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AWXDefaultProvider"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider~1init(delegate:session:)\/title","value":"initWithDelegate:session:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDelegate:session:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider~1init(delegate:session:)\/fragments"}]}]}