{"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"not used anymore"}]}],"abstract":[{"text":"whether should show this payment directly.","type":"text"}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider\/showPaymentDirectly","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxdefaultprovider\/showpaymentdirectly"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxdefaultprovider\/showpaymentdirectly"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showPaymentDirectly"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"title":"showPaymentDirectly","platforms":[{"message":"not used anymore","unavailable":false,"deprecated":true,"beta":false}],"externalID":"c:objc(cs)AWXDefaultProvider(py)showPaymentDirectly","modules":[{"name":"Airwallex"}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"showPaymentDirectly"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"showPaymentDirectly"}]},"sections":[],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXDefaultProvider":{"abstract":[{"text":"A provider which handles payment business.","type":"text"}],"title":"AWXDefaultProvider","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider","navigatorTitle":[{"kind":"identifier","text":"AWXDefaultProvider"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXDefaultProvider"}],"kind":"symbol","url":"\/documentation\/airwallex\/awxdefaultprovider","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","abstract":[],"type":"topic","kind":"symbol","title":"Airwallex","role":"collection"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXDefaultProvider/showPaymentDirectly":{"title":"showPaymentDirectly","abstract":[{"type":"text","text":"whether should show this payment directly."}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider\/showPaymentDirectly","navigatorTitle":[{"kind":"identifier","text":"showPaymentDirectly"}],"deprecated":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showPaymentDirectly"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","type":"topic","url":"\/documentation\/airwallex\/awxdefaultprovider\/showpaymentdirectly"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[{"unavailable":false,"beta":false,"deprecated":true}],"op":"replace","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"showPaymentDirectly","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"showPaymentDirectly"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"showPaymentDirectly","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":[{"type":"paragraph","inlineContent":[{"type":"text","text":"not used anymore"}]}],"path":"\/deprecationSummary","op":"replace"},{"value":"AWXDefaultProvider","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AWXDefaultProvider"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AWXDefaultProvider"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider\/navigatorTitle","op":"replace"},{"value":"showPaymentDirectly","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider~1showPaymentDirectly\/title","op":"replace"},{"value":[{"kind":"identifier","text":"showPaymentDirectly"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider~1showPaymentDirectly\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}