{"sections":[],"variants":[{"paths":["\/documentation\/airwallex\/awxconfirmpaymentintentresponse\/latestpaymentattempt"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxconfirmpaymentintentresponse\/latestpaymentattempt"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"The latest payment attempt object."}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentResponse"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"latestPaymentAttempt","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AWXPaymentAttempt","text":"AWXPaymentAttempt","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentAttempt"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"metadata":{"role":"symbol","title":"latestPaymentAttempt","externalID":"c:objc(cs)AWXConfirmPaymentIntentResponse(py)latestPaymentAttempt","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"latestPaymentAttempt","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AWXPaymentAttempt","text":"AWXPaymentAttempt","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"symbolKind":"property","navigatorTitle":[{"text":"latestPaymentAttempt","kind":"identifier"}],"modules":[{"name":"Airwallex"}],"roleHeading":"Instance Property"},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentResponse\/latestPaymentAttempt"},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"abstract":[],"url":"\/documentation\/airwallex","role":"collection","title":"Airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","type":"topic","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentAttempt":{"title":"AWXPaymentAttempt","type":"topic","role":"symbol","url":"\/documentation\/airwallex\/awxpaymentattempt","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentAttempt","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPaymentAttempt","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"AWXPaymentAttempt"},{"text":" includes the information of payment attempt.","type":"text"}],"navigatorTitle":[{"text":"AWXPaymentAttempt","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXConfirmPaymentIntentResponse/latestPaymentAttempt":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentResponse\/latestPaymentAttempt","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"latestPaymentAttempt","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWXPaymentAttempt","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPaymentAttempt"},{"text":"?","kind":"text"}],"kind":"symbol","title":"latestPaymentAttempt","type":"topic","abstract":[{"type":"text","text":"The latest payment attempt object."}],"role":"symbol","navigatorTitle":[{"text":"latestPaymentAttempt","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxconfirmpaymentintentresponse\/latestpaymentattempt"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXConfirmPaymentIntentResponse":{"navigatorTitle":[{"text":"AWXConfirmPaymentIntentResponse","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxconfirmpaymentintentresponse","abstract":[{"type":"codeVoice","code":"AWXConfirmPaymentIntentResponse"},{"type":"text","text":" includes the result of payment flow."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXConfirmPaymentIntentResponse","kind":"identifier"}],"title":"AWXConfirmPaymentIntentResponse","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentResponse","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"latestPaymentAttempt","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"latestPaymentAttempt","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"AWXPaymentAttempt","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentAttempt","preciseIdentifier":"c:objc(cs)AWXPaymentAttempt"},{"kind":"text","text":" * "},{"kind":"identifier","text":"latestPaymentAttempt"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"AWXPaymentAttempt","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentAttempt\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AWXPaymentAttempt"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentAttempt\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AWXPaymentAttempt"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentAttempt\/navigatorTitle"},{"op":"replace","value":"latestPaymentAttempt","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentResponse~1latestPaymentAttempt\/title"},{"op":"replace","value":[{"kind":"identifier","text":"latestPaymentAttempt"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentResponse~1latestPaymentAttempt\/fragments"},{"op":"replace","value":"AWXConfirmPaymentIntentResponse","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentResponse\/title"},{"op":"replace","value":[{"text":"AWXConfirmPaymentIntentResponse","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentResponse\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AWXConfirmPaymentIntentResponse"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentResponse\/navigatorTitle"}]}]}