{"metadata":{"modules":[{"name":"Airwallex"}],"title":"paymentConsentId","roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"paymentConsentId"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentConsentId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"externalID":"c:objc(cs)AWXConfirmPaymentIntentResponse(py)paymentConsentId","symbolKind":"property"},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentResponse\/paymentConsentId","interfaceLanguage":"swift"},"abstract":[{"text":"ID of the PaymentConsent related to this PaymentIntent","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxconfirmpaymentintentresponse\/paymentconsentid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxconfirmpaymentintentresponse\/paymentconsentid"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentResponse"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentConsentId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXConfirmPaymentIntentResponse":{"url":"\/documentation\/airwallex\/awxconfirmpaymentintentresponse","title":"AWXConfirmPaymentIntentResponse","type":"topic","abstract":[{"type":"codeVoice","code":"AWXConfirmPaymentIntentResponse"},{"type":"text","text":" includes the result of payment flow."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXConfirmPaymentIntentResponse"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentResponse","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWXConfirmPaymentIntentResponse"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXConfirmPaymentIntentResponse/paymentConsentId":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentConsentId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"title":"paymentConsentId","navigatorTitle":[{"text":"paymentConsentId","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxconfirmpaymentintentresponse\/paymentconsentid","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentResponse\/paymentConsentId","abstract":[{"text":"ID of the PaymentConsent related to this PaymentIntent","type":"text"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","type":"topic","role":"collection","title":"Airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"paymentConsentId","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"paymentConsentId","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"paymentConsentId"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentResponse\/title","value":"AWXConfirmPaymentIntentResponse","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentResponse\/fragments","value":[{"text":"AWXConfirmPaymentIntentResponse","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentResponse\/navigatorTitle","value":[{"text":"AWXConfirmPaymentIntentResponse","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentResponse~1paymentConsentId\/title","value":"paymentConsentId","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentResponse~1paymentConsentId\/fragments","value":[{"text":"paymentConsentId","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}