{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentResponse"]]},"metadata":{"symbolKind":"property","roleHeading":"Instance Property","externalID":"c:objc(cs)AWXConfirmPaymentIntentResponse(py)status","title":"status","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"status","kind":"identifier"}],"modules":[{"name":"Airwallex"}]},"abstract":[{"text":"Payment status.","type":"text"}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxconfirmpaymentintentresponse\/status"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxconfirmpaymentintentresponse\/status"]}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentResponse\/status","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","role":"collection","title":"Airwallex","url":"\/documentation\/airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXConfirmPaymentIntentResponse/status":{"title":"status","abstract":[{"text":"Payment status.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"status"}],"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentResponse\/status","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"kind":"symbol","url":"\/documentation\/airwallex\/awxconfirmpaymentintentresponse\/status"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXConfirmPaymentIntentResponse":{"role":"symbol","abstract":[{"type":"codeVoice","code":"AWXConfirmPaymentIntentResponse"},{"text":" includes the result of payment flow.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXConfirmPaymentIntentResponse"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"AWXConfirmPaymentIntentResponse"}],"kind":"symbol","title":"AWXConfirmPaymentIntentResponse","url":"\/documentation\/airwallex\/awxconfirmpaymentintentresponse","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentResponse"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"status"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"status"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"status","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentResponse~1status\/title","value":"status"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentResponse~1status\/fragments","value":[{"text":"status","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentResponse\/title","value":"AWXConfirmPaymentIntentResponse"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentResponse\/fragments","value":[{"kind":"identifier","text":"AWXConfirmPaymentIntentResponse"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentResponse\/navigatorTitle","value":[{"text":"AWXConfirmPaymentIntentResponse","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}