{"kind":"symbol","abstract":[{"type":"text","text":"The payment amount as an NSDecimalNumber value."}],"variants":[{"paths":["\/documentation\/airwallex\/paymentintentprovider\/amount"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/paymentintentprovider\/amount"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"amount"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSDecimalNumber","preciseIdentifier":"c:objc(cs)NSDecimalNumber"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This value must be available immediately and should match the amount"},{"type":"text","text":" "},{"type":"text","text":"of the payment intent that will be created by "},{"code":"createPaymentIntent()","type":"codeVoice"},{"text":".","type":"text"}]},{"style":"important","type":"aside","name":"Important","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Should be zero for recurring-only payments (no immediate charge)."},{"type":"text","text":" "},{"type":"text","text":"Must match the amount in the created payment intent."}]}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentIntentProvider"]]},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"amount"},{"text":": ","kind":"text"},{"text":"NSDecimalNumber","preciseIdentifier":"c:objc(cs)NSDecimalNumber","kind":"typeIdentifier"}],"symbolKind":"property","title":"amount","required":true,"roleHeading":"Instance Property","role":"symbol","externalID":"c:@M@Airwallex@objc(pl)PaymentIntentProvider(py)amount","modules":[{"name":"Airwallex"}],"navigatorTitle":[{"text":"amount","kind":"identifier"}]},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentIntentProvider\/amount","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentIntentProvider/amount":{"url":"\/documentation\/airwallex\/paymentintentprovider\/amount","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentIntentProvider\/amount","abstract":[{"text":"The payment amount as an NSDecimalNumber value.","type":"text"}],"type":"topic","required":true,"role":"symbol","title":"amount","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"amount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSDecimalNumber","preciseIdentifier":"c:objc(cs)NSDecimalNumber"}],"navigatorTitle":[{"kind":"identifier","text":"amount"}],"kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentIntentProvider":{"kind":"symbol","abstract":[{"text":"A protocol for providing payment intents on-demand during the payment flow.","type":"text"}],"url":"\/documentation\/airwallex\/paymentintentprovider","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentIntentProvider"}],"navigatorTitle":[{"kind":"identifier","text":"PaymentIntentProvider"}],"title":"PaymentIntentProvider","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentIntentProvider"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"abstract":[],"kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","url":"\/documentation\/airwallex"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"amount","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"amount"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSDecimalNumber","preciseIdentifier":"c:objc(cs)NSDecimalNumber"},{"kind":"text","text":" * "},{"kind":"identifier","text":"amount"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"amount","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentIntentProvider~1amount\/title"},{"op":"replace","value":[{"kind":"identifier","text":"amount"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentIntentProvider~1amount\/fragments"},{"op":"replace","value":"PaymentIntentProvider","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentIntentProvider\/title"},{"op":"replace","value":[{"text":"PaymentIntentProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentIntentProvider\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentIntentProvider\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"PaymentIntentProvider"}]}]}]}