{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxsession\/requirescvc()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxsession\/requirescvc()"]}],"metadata":{"platforms":[{"deprecated":true,"unavailable":false,"message":"requiresCVC will be determined by consent returned by server (numberType), passing requiresCVC as a parameter is no longer needed","beta":false}],"navigatorTitle":[{"kind":"identifier","text":"requiresCVC"}],"extendedModule":"Airwallex","title":"requiresCVC()","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AWXSession(im)requiresCVC","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"requiresCVC","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"modules":[{"name":"Airwallex"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession\/requiresCVC()"},"deprecationSummary":[{"inlineContent":[{"text":"requiresCVC will be determined by consent returned by server (numberType), passing requiresCVC as a parameter is no longer needed","type":"text"}],"type":"paragraph"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requiresCVC","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"text":"Return whether it requres CVC.","type":"text"}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSession/requiresCVC()":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"requiresCVC","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"deprecated":true,"url":"\/documentation\/airwallex\/awxsession\/requirescvc()","abstract":[{"type":"text","text":"Return whether it requres CVC."}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession\/requiresCVC()","type":"topic","title":"requiresCVC()","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"requiresCVC"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSession":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AWXSession"}],"abstract":[{"type":"codeVoice","code":"AWXSession"},{"type":"text","text":" is the base session."}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession","url":"\/documentation\/airwallex\/awxsession","role":"symbol","type":"topic","title":"AWXSession","navigatorTitle":[{"kind":"identifier","text":"AWXSession"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/airwallex","title":"Airwallex","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":[{"deprecated":true,"unavailable":false,"beta":false}],"path":"\/metadata\/platforms"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"requiresCVC"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"requiresCVC"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"text":"requiresCVC","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","value":[{"type":"paragraph","inlineContent":[{"type":"text","text":"requiresCVC will be determined by consent returned by server (numberType), passing requiresCVC as a parameter is no longer needed"}]}],"path":"\/deprecationSummary"},{"op":"replace","value":"requiresCVC","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession~1requiresCVC()\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession~1requiresCVC()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"requiresCVC","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/title","value":"AWXSession"},{"op":"replace","value":[{"kind":"identifier","text":"AWXSession"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AWXSession"}]}]}]}