{"kind":"symbol","metadata":{"modules":[{"name":"Airwallex"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"cardNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"expiryMonth","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"expiryYear","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"cvc","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"extendedModule":"Airwallex","role":"symbol","roleHeading":"Initializer","externalID":"s:So7AWXCardC9AirwallexE4name10cardNumber11expiryMonth0F4Year3cvcABSS_S4Stcfc","title":"init(name:cardNumber:expiryMonth:expiryYear:cvc:)","symbolKind":"init"},"variants":[{"paths":["\/documentation\/airwallex\/awxcard\/init(name:cardnumber:expirymonth:expiryyear:cvc:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cardNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"expiryMonth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"expiryYear","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"cvc","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCard"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCard\/init(name:cardNumber:expiryMonth:expiryYear:cvc:)"},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCard/init(name:cardNumber:expiryMonth:expiryYear:cvc:)":{"kind":"symbol","role":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cardNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"expiryMonth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"expiryYear"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cvc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"abstract":[],"title":"init(name:cardNumber:expiryMonth:expiryYear:cvc:)","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCard\/init(name:cardNumber:expiryMonth:expiryYear:cvc:)","url":"\/documentation\/airwallex\/awxcard\/init(name:cardnumber:expirymonth:expiryyear:cvc:)"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCard":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCard","navigatorTitle":[{"kind":"identifier","text":"AWXCard"}],"abstract":[{"type":"codeVoice","code":"AWXCard"},{"text":" includes the information of a card.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXCard"}],"role":"symbol","type":"topic","url":"\/documentation\/airwallex\/awxcard","title":"AWXCard","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"kind":"symbol","abstract":[],"role":"collection","type":"topic","url":"\/documentation\/airwallex","title":"Airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"}},"variantOverrides":[{"patch":[{"op":"replace","value":"AWXCard","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCard\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AWXCard"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCard\/fragments"},{"value":[{"text":"AWXCard","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCard\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}