{"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","variants":[{"paths":["\/documentation\/airwallex\/analyticslogger\/logerror(withname:url:response:additionalinfo:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/analyticslogger\/logerror(withname:url:response:additionalinfo:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"logError","kind":"identifier"},{"kind":"text","text":"("},{"text":"withName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"url","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"text":"response","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXAPIErrorResponse","text":"AWXAPIErrorResponse"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"additionalInfo"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?)"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"logErrorWithName:url:response:additionalInfo:"}],"externalID":"c:objc(cs)AWXAnalyticsLogger(im)logErrorWithName:url:response:additionalInfo:","roleHeading":"Instance Method","title":"logError(withName:url:response:additionalInfo:)","modules":[{"name":"Airwallex"}],"symbolKind":"method"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"logError"},{"text":"(","kind":"text"},{"text":"withName","kind":"externalParam"},{"kind":"text","text":" "},{"text":"eventName","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"url","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"response","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"errorResponse","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AWXAPIErrorResponse","text":"AWXAPIErrorResponse","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAPIErrorResponse","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"additionalInfo","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]?)","kind":"text"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AnalyticsLogger"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AnalyticsLogger\/logError(withName:url:response:additionalInfo:)"},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXAPIErrorResponse":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXAPIErrorResponse","kind":"identifier"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"AWXAPIErrorResponse","kind":"identifier"}],"kind":"symbol","title":"AWXAPIErrorResponse","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAPIErrorResponse","abstract":[{"text":"An ","type":"text"},{"type":"codeVoice","code":"AWXAPIErrorResponse"},{"text":" includes error details.","type":"text"}],"url":"\/documentation\/airwallex\/awxapierrorresponse"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AnalyticsLogger/logError(withName:url:response:additionalInfo:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"logError"},{"text":"(","kind":"text"},{"text":"withName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"url"},{"kind":"text","text":": "},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"response"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AWXAPIErrorResponse","text":"AWXAPIErrorResponse","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"additionalInfo"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]?)","kind":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AnalyticsLogger\/logError(withName:url:response:additionalInfo:)","kind":"symbol","url":"\/documentation\/airwallex\/analyticslogger\/logerror(withname:url:response:additionalinfo:)","title":"logError(withName:url:response:additionalInfo:)","abstract":[],"navigatorTitle":[{"text":"logErrorWithName:url:response:additionalInfo:","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/airwallex","title":"Airwallex","role":"collection"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AnalyticsLogger":{"title":"AnalyticsLogger","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AnalyticsLogger","navigatorTitle":[{"text":"AnalyticsLogger","kind":"identifier"}],"abstract":[],"url":"\/documentation\/airwallex\/analyticslogger","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AnalyticsLogger"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"logErrorWithName:url:response:additionalInfo:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"logErrorWithName:url:response:additionalInfo:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"logErrorWithName:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"eventName","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"url:"},{"text":"(","kind":"text"},{"text":"NSURL","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"url"},{"text":" ","kind":"text"},{"kind":"identifier","text":"response:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAPIErrorResponse","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXAPIErrorResponse","text":"AWXAPIErrorResponse"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"errorResponse"},{"kind":"text","text":" "},{"text":"additionalInfo:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSDictionary<NSString *,id>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"additionalInfo"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIErrorResponse\/title","value":"AWXAPIErrorResponse","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIErrorResponse\/fragments","value":[{"text":"AWXAPIErrorResponse","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIErrorResponse\/navigatorTitle","op":"replace","value":[{"text":"AWXAPIErrorResponse","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AnalyticsLogger~1logError(withName:url:response:additionalInfo:)\/title","value":"logErrorWithName:url:response:additionalInfo:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AnalyticsLogger~1logError(withName:url:response:additionalInfo:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"logErrorWithName:url:response:additionalInfo:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"AWXAnalyticsLogger","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AnalyticsLogger\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AnalyticsLogger\/fragments","value":[{"kind":"identifier","text":"AWXAnalyticsLogger"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AnalyticsLogger\/navigatorTitle","value":[{"kind":"identifier","text":"AWXAnalyticsLogger"}]}]}]}