{"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"logPaymentMethodView"},{"text":"(","kind":"text"},{"text":"withName","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"name"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/analyticslogger\/logpaymentmethodview(withname:)"]},{"paths":["\/documentation\/airwallex\/analyticslogger\/logpaymentmethodview(withname:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"logPaymentMethodViewWithName:"}],"roleHeading":"Instance Method","modules":[{"name":"Airwallex"}],"title":"logPaymentMethodView(withName:)","role":"symbol","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"logPaymentMethodView"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withName"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"externalID":"c:objc(cs)AWXAnalyticsLogger(im)logPaymentMethodViewWithName:"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AnalyticsLogger\/logPaymentMethodView(withName:)"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AnalyticsLogger"]]},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AnalyticsLogger/logPaymentMethodView(withName:)":{"role":"symbol","kind":"symbol","url":"\/documentation\/airwallex\/analyticslogger\/logpaymentmethodview(withname:)","type":"topic","navigatorTitle":[{"text":"logPaymentMethodViewWithName:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AnalyticsLogger\/logPaymentMethodView(withName:)","abstract":[],"title":"logPaymentMethodView(withName:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logPaymentMethodView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withName","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/airwallex","title":"Airwallex","role":"collection"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AnalyticsLogger":{"title":"AnalyticsLogger","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AnalyticsLogger","navigatorTitle":[{"text":"AnalyticsLogger","kind":"identifier"}],"abstract":[],"url":"\/documentation\/airwallex\/analyticslogger","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AnalyticsLogger"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"logPaymentMethodViewWithName:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"logPaymentMethodViewWithName:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"logPaymentMethodViewWithName:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"name","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AnalyticsLogger~1logPaymentMethodView(withName:)\/title","value":"logPaymentMethodViewWithName:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"logPaymentMethodViewWithName:"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AnalyticsLogger~1logPaymentMethodView(withName:)\/fragments","op":"replace"},{"op":"replace","value":"AWXAnalyticsLogger","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AnalyticsLogger\/title"},{"value":[{"text":"AWXAnalyticsLogger","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AnalyticsLogger\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AWXAnalyticsLogger"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AnalyticsLogger\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}