{"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"transactionMode"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"abstract":[{"text":"Return transaction mode.","type":"text"}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession\/transactionMode()","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxsession\/transactionmode()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxsession\/transactionmode()"]}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"transactionMode"}],"symbolKind":"method","modules":[{"name":"Airwallex"}],"title":"transactionMode()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"transactionMode"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"roleHeading":"Instance Method","role":"symbol","externalID":"c:objc(cs)AWXSession(im)transactionMode"},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSession":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXSession","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxsession","type":"topic","navigatorTitle":[{"text":"AWXSession","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"AWXSession"},{"text":" is the base session.","type":"text"}],"kind":"symbol","title":"AWXSession"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","url":"\/documentation\/airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol","title":"Airwallex","abstract":[],"role":"collection"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSession/transactionMode()":{"role":"symbol","url":"\/documentation\/airwallex\/awxsession\/transactionmode()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transactionMode","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"transactionMode()","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession\/transactionMode()","type":"topic","navigatorTitle":[{"kind":"identifier","text":"transactionMode"}],"abstract":[{"text":"Return transaction mode.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"transactionMode","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"transactionMode"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"transactionMode","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/title","value":"AWXSession","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/fragments","value":[{"kind":"identifier","text":"AWXSession"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/navigatorTitle","value":[{"text":"AWXSession","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession~1transactionMode()\/title","value":"transactionMode","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession~1transactionMode()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"transactionMode"}],"op":"replace"}]}]}