{"kind":"article","metadata":{"role":"collectionGroup","roleHeading":"API Collection","title":"AWXPageViewTrackable Implementations","modules":[{"name":"Airwallex"}]},"variants":[{"paths":["\/documentation\/airwallex\/awxshippingviewcontroller\/awxpageviewtrackable-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxshippingviewcontroller\/awxpageviewtrackable-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXShippingViewController\/AWXPageViewTrackable-Implementations","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXShippingViewController\/pageName"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXShippingViewController"]]},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXShippingViewController/pageName":{"role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pageName","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"navigatorTitle":[{"text":"pageName","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXShippingViewController\/pageName","url":"\/documentation\/airwallex\/awxshippingviewcontroller\/pagename","title":"pageName","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","url":"\/documentation\/airwallex","abstract":[],"title":"Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXShippingViewController":{"role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXShippingViewController"}],"navigatorTitle":[{"kind":"identifier","text":"AWXShippingViewController"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXShippingViewController","url":"\/documentation\/airwallex\/awxshippingviewcontroller","title":"AWXShippingViewController","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXShippingViewController\/pageName"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXShippingViewController~1pageName\/title","value":"pageName","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXShippingViewController~1pageName\/fragments","value":[{"text":"pageName","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXShippingViewController\/title","value":"AWXShippingViewController","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXShippingViewController\/fragments","value":[{"text":"AWXShippingViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXShippingViewController\/navigatorTitle","value":[{"text":"AWXShippingViewController","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}