{"variants":[{"paths":["\/documentation\/airwallex\/awxshippingviewcontroller\/shipping"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxshippingviewcontroller\/shipping"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXShippingViewController\/shipping","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@Airwallex@objc(cs)AWXShippingViewController(py)shipping","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"Airwallex"}],"navigatorTitle":[{"text":"shipping","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shipping","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWXPlaceDetails","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPlaceDetails"},{"text":"?","kind":"text"}],"title":"shipping"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shipping"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPlaceDetails","preciseIdentifier":"c:objc(cs)AWXPlaceDetails","text":"AWXPlaceDetails"},{"kind":"text","text":"?"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXShippingViewController"]]},"kind":"symbol","sections":[],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXShippingViewController/shipping":{"role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shipping","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWXPlaceDetails","preciseIdentifier":"c:objc(cs)AWXPlaceDetails","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"shipping","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXShippingViewController\/shipping","url":"\/documentation\/airwallex\/awxshippingviewcontroller\/shipping","abstract":[],"title":"shipping"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXShippingViewController":{"role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXShippingViewController"}],"navigatorTitle":[{"kind":"identifier","text":"AWXShippingViewController"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXShippingViewController","url":"\/documentation\/airwallex\/awxshippingviewcontroller","title":"AWXShippingViewController","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPlaceDetails":{"role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPlaceDetails"}],"navigatorTitle":[{"kind":"identifier","text":"AWXPlaceDetails"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPlaceDetails","url":"\/documentation\/airwallex\/awxplacedetails","title":"AWXPlaceDetails","abstract":[{"code":"AWXPlaceDetails","type":"codeVoice"},{"type":"text","text":" includes the information of a billing address."}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","url":"\/documentation\/airwallex","abstract":[],"title":"Airwallex"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"shipping","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"shipping","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"AWXPlaceDetails","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPlaceDetails","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPlaceDetails"},{"text":" * ","kind":"text"},{"text":"shipping","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"shipping","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXShippingViewController~1shipping\/title"},{"value":[{"text":"shipping","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXShippingViewController~1shipping\/fragments"},{"value":"AWXShippingViewController","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXShippingViewController\/title"},{"value":[{"text":"AWXShippingViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXShippingViewController\/fragments"},{"value":[{"text":"AWXShippingViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXShippingViewController\/navigatorTitle"},{"value":"AWXPlaceDetails","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPlaceDetails\/title"},{"value":[{"text":"AWXPlaceDetails","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPlaceDetails\/fragments"},{"value":[{"text":"AWXPlaceDetails","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPlaceDetails\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}