{"metadata":{"symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"AWXCreatePaymentConsentRequest"}],"externalID":"c:objc(cs)AWXCreatePaymentConsentRequest","modules":[{"name":"Airwallex"}],"title":"AWXCreatePaymentConsentRequest","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AWXCreatePaymentConsentRequest","kind":"identifier"}],"role":"symbol","roleHeading":"Class"},"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRequest"]},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Airwallex\/SQ","doc:\/\/org.cocoapods.Airwallex\/SH"]}],"variants":[{"paths":["\/documentation\/airwallex\/awxcreatepaymentconsentrequest"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxcreatepaymentconsentrequest"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCreatePaymentConsentRequest\/currency","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCreatePaymentConsentRequest\/customerId","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCreatePaymentConsentRequest\/merchantTriggerReason","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCreatePaymentConsentRequest\/nextTriggerByType","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCreatePaymentConsentRequest\/paymentMethod","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCreatePaymentConsentRequest\/requiresCVC"],"generated":true}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCreatePaymentConsentRequest"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"codeVoice","code":"AWXCreatePaymentConsentRequest"},{"type":"text","text":" includes the request of creating payment consent."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXCreatePaymentConsentRequest"}],"languages":["swift"]}]}],"kind":"symbol","references":{"doc://org.cocoapods.Airwallex/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCreatePaymentConsentRequest":{"type":"topic","abstract":[{"code":"AWXCreatePaymentConsentRequest","type":"codeVoice"},{"type":"text","text":" includes the request of creating payment consent."}],"title":"AWXCreatePaymentConsentRequest","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCreatePaymentConsentRequest","navigatorTitle":[{"kind":"identifier","text":"AWXCreatePaymentConsentRequest"}],"url":"\/documentation\/airwallex\/awxcreatepaymentconsentrequest","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXCreatePaymentConsentRequest"}],"kind":"symbol"},"doc://org.cocoapods.Airwallex/SH":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCreatePaymentConsentRequest/merchantTriggerReason":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCreatePaymentConsentRequest\/merchantTriggerReason","role":"symbol","title":"merchantTriggerReason","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"merchantTriggerReason","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AirwallexMerchantTriggerReason","kind":"typeIdentifier","preciseIdentifier":"c:@E@AirwallexMerchantTriggerReason"}],"type":"topic","url":"\/documentation\/airwallex\/awxcreatepaymentconsentrequest\/merchanttriggerreason","abstract":[{"type":"text","text":"Merchant trigger reason"}],"navigatorTitle":[{"text":"merchantTriggerReason","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCreatePaymentConsentRequest/nextTriggerByType":{"type":"topic","abstract":[{"type":"text","text":"Next trigger By type."}],"title":"nextTriggerByType","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCreatePaymentConsentRequest\/nextTriggerByType","navigatorTitle":[{"text":"nextTriggerByType","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxcreatepaymentconsentrequest\/nexttriggerbytype","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nextTriggerByType","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@AirwallexNextTriggerByType","text":"AirwallexNextTriggerByType"}],"kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCreatePaymentConsentRequest/currency":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"currency"}],"url":"\/documentation\/airwallex\/awxcreatepaymentconsentrequest\/currency","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCreatePaymentConsentRequest\/currency","title":"currency","abstract":[{"type":"text","text":"A currency code."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currency"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"role":"symbol","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCreatePaymentConsentRequest/requiresCVC":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"requiresCVC"}],"url":"\/documentation\/airwallex\/awxcreatepaymentconsentrequest\/requirescvc","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCreatePaymentConsentRequest\/requiresCVC","title":"requiresCVC","abstract":[{"type":"text","text":"Whether it requires CVC."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiresCVC"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"role":"symbol","kind":"symbol"},"doc://org.cocoapods.Airwallex/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.Airwallex/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","role":"collection","title":"Airwallex","type":"topic","url":"\/documentation\/airwallex","abstract":[]},"doc://org.cocoapods.Airwallex/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/s7CVarArgP","title":"Swift.CVarArg"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCreatePaymentConsentRequest/paymentMethod":{"type":"topic","abstract":[{"type":"text","text":"Payment method object."}],"title":"paymentMethod","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCreatePaymentConsentRequest\/paymentMethod","navigatorTitle":[{"kind":"identifier","text":"paymentMethod"}],"url":"\/documentation\/airwallex\/awxcreatepaymentconsentrequest\/paymentmethod","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWXPaymentMethod","preciseIdentifier":"c:objc(cs)AWXPaymentMethod"}],"kind":"symbol"},"doc://org.cocoapods.Airwallex/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.Airwallex\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRequest":{"type":"topic","abstract":[],"title":"AWXRequest","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRequest","navigatorTitle":[{"text":"AWXRequest","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxrequest","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXRequest","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCreatePaymentConsentRequest/customerId":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCreatePaymentConsentRequest\/customerId","role":"symbol","title":"customerId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customerId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"type":"topic","url":"\/documentation\/airwallex\/awxcreatepaymentconsentrequest\/customerid","abstract":[{"type":"text","text":"Customer ID."}],"navigatorTitle":[{"kind":"identifier","text":"customerId"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"AWXCreatePaymentConsentRequest","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"AWXCreatePaymentConsentRequest"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AWXCreatePaymentConsentRequest"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCreatePaymentConsentRequest\/currency","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCreatePaymentConsentRequest\/customerId","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCreatePaymentConsentRequest\/merchantTriggerReason","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCreatePaymentConsentRequest\/nextTriggerByType","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCreatePaymentConsentRequest\/paymentMethod","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCreatePaymentConsentRequest\/requiresCVC"],"generated":true}],"path":"\/topicSections"},{"op":"replace","value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRequest"]}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXCreatePaymentConsentRequest","kind":"identifier"},{"text":" : ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRequest","preciseIdentifier":"c:objc(cs)AWXRequest","text":"AWXRequest","kind":"typeIdentifier"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"AWXCreatePaymentConsentRequest","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCreatePaymentConsentRequest\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AWXCreatePaymentConsentRequest"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCreatePaymentConsentRequest\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AWXCreatePaymentConsentRequest"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCreatePaymentConsentRequest\/navigatorTitle"},{"op":"replace","value":"merchantTriggerReason","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCreatePaymentConsentRequest~1merchantTriggerReason\/title"},{"op":"replace","value":[{"kind":"identifier","text":"merchantTriggerReason"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCreatePaymentConsentRequest~1merchantTriggerReason\/fragments"},{"op":"replace","value":"nextTriggerByType","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCreatePaymentConsentRequest~1nextTriggerByType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"nextTriggerByType"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCreatePaymentConsentRequest~1nextTriggerByType\/fragments"},{"op":"replace","value":"currency","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCreatePaymentConsentRequest~1currency\/title"},{"op":"replace","value":[{"kind":"identifier","text":"currency"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCreatePaymentConsentRequest~1currency\/fragments"},{"op":"replace","value":"requiresCVC","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCreatePaymentConsentRequest~1requiresCVC\/title"},{"op":"replace","value":[{"kind":"identifier","text":"requiresCVC"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCreatePaymentConsentRequest~1requiresCVC\/fragments"},{"op":"replace","value":"paymentMethod","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCreatePaymentConsentRequest~1paymentMethod\/title"},{"op":"replace","value":[{"kind":"identifier","text":"paymentMethod"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCreatePaymentConsentRequest~1paymentMethod\/fragments"},{"op":"replace","value":"AWXRequest","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRequest\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AWXRequest"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRequest\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AWXRequest"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRequest\/navigatorTitle"},{"op":"replace","value":"customerId","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCreatePaymentConsentRequest~1customerId\/title"},{"op":"replace","value":[{"kind":"identifier","text":"customerId"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCreatePaymentConsentRequest~1customerId\/fragments"}]}]}