{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxbrandtype\/allavailable"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrandType"]]},"metadata":{"modules":[{"name":"Airwallex"}],"extendedModule":"Airwallex","role":"symbol","roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allAvailable"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AWXBrandType","preciseIdentifier":"c:@E@AWXBrandType"},{"kind":"text","text":"]"}],"title":"allAvailable","symbolKind":"property","externalID":"s:So12AWXBrandTypeV9AirwallexE12allAvailableSayABGvpZ"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allAvailable","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@E@AWXBrandType","text":"AWXBrandType","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrandType"},{"text":"] { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrandType\/allAvailable"},"kind":"symbol","sections":[],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","abstract":[],"type":"topic","kind":"symbol","title":"Airwallex","role":"collection"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXBrandType/allAvailable":{"type":"topic","title":"allAvailable","abstract":[],"url":"\/documentation\/airwallex\/awxbrandtype\/allavailable","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrandType\/allAvailable","kind":"symbol","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allAvailable","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@E@AWXBrandType","text":"AWXBrandType","kind":"typeIdentifier"},{"text":"]","kind":"text"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXBrandType":{"title":"AWXBrandType","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrandType","navigatorTitle":[{"text":"AWXBrandType","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXBrandType","kind":"identifier"}],"type":"topic","url":"\/documentation\/airwallex\/awxbrandtype","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"AWXBrandType","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrandType\/title","op":"replace"},{"value":[{"text":"AWXBrandType","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrandType\/fragments","op":"replace"},{"value":[{"text":"AWXBrandType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrandType\/navigatorTitle"}]}]}