{"metadata":{"navigatorTitle":[{"text":"AWXBrandTypeJCB","kind":"identifier"}],"modules":[{"name":"Airwallex"}],"symbolKind":"case","externalID":"c:@E@AWXBrandType@AWXBrandTypeJCB","roleHeading":"Case","title":"AWXBrandType.JCB","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"JCB"}],"role":"symbol"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrandType"]]},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrandType\/JCB","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxbrandtype\/jcb"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxbrandtype\/jcb"]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JCB","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol","type":"topic","url":"\/documentation\/airwallex","role":"collection","abstract":[],"title":"Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXBrandType/JCB":{"title":"AWXBrandType.JCB","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrandType\/JCB","abstract":[],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/airwallex\/awxbrandtype\/jcb","navigatorTitle":[{"text":"AWXBrandTypeJCB","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"JCB"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXBrandType":{"navigatorTitle":[{"text":"AWXBrandType","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrandType","url":"\/documentation\/airwallex\/awxbrandtype","role":"symbol","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXBrandType","kind":"identifier"}],"title":"AWXBrandType","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AWXBrandTypeJCB"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AWXBrandTypeJCB"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"AWXBrandTypeJCB","kind":"identifier"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrandType~1JCB\/title","value":"AWXBrandTypeJCB"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrandType~1JCB\/fragments","value":[{"text":"AWXBrandTypeJCB","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrandType\/title","value":"AWXBrandType"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrandType\/fragments","value":[{"text":"AWXBrandType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrandType\/navigatorTitle","value":[{"kind":"identifier","text":"AWXBrandType"}]}]}]}