{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"supportedCardBrands","kind":"identifier"},{"text":": [","kind":"text"},{"text":"AWXCardBrand","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand","preciseIdentifier":"c:AWXConstants.h@T@AWXCardBrand"},{"text":"]","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"inlineContent":[{"text":"Only applies when ","type":"text"},{"type":"codeVoice","code":"elementType"},{"text":" is ","type":"text"},{"type":"codeVoice","code":".addCard"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"Defaults to all available card brands.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/Configuration"]]},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/Configuration\/supportedCardBrands","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Supported card brands for card payment."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/airwallex\/awxpaymentelement\/configuration\/supportedcardbrands"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"externalID":"s:9Airwallex17AWXPaymentElementC13ConfigurationC19supportedCardBrandsSaySo12AWXCardBrandaGvp","role":"symbol","modules":[{"name":"Airwallex"}],"symbolKind":"property","title":"supportedCardBrands","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"supportedCardBrands","kind":"identifier"},{"text":": [","kind":"text"},{"text":"AWXCardBrand","preciseIdentifier":"c:AWXConstants.h@T@AWXCardBrand","kind":"typeIdentifier"},{"text":"]","kind":"text"}]},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","url":"\/documentation\/airwallex","title":"Airwallex","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement":{"role":"symbol","url":"\/documentation\/airwallex\/awxpaymentelement","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentElement"}],"type":"topic","kind":"symbol","title":"AWXPaymentElement","abstract":[{"type":"text","text":"An embeddable payment element that can be added to any view hierarchy."}],"navigatorTitle":[{"kind":"identifier","text":"AWXPaymentElement"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement/Configuration":{"abstract":[{"text":"Configuration options for the embedded payment element.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"role":"symbol","title":"AWXPaymentElement.Configuration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Configuration"}],"type":"topic","url":"\/documentation\/airwallex\/awxpaymentelement\/configuration","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/Configuration"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement/Configuration/supportedCardBrands":{"abstract":[{"text":"Supported card brands for card payment.","type":"text"}],"kind":"symbol","role":"symbol","title":"supportedCardBrands","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"supportedCardBrands"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:AWXConstants.h@T@AWXCardBrand","text":"AWXCardBrand"},{"kind":"text","text":"]"}],"type":"topic","url":"\/documentation\/airwallex\/awxpaymentelement\/configuration\/supportedcardbrands","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/Configuration\/supportedCardBrands"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardBrand":{"abstract":[],"kind":"symbol","title":"AWXCardBrand","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXCardBrand"}],"navigatorTitle":[{"kind":"identifier","text":"AWXCardBrand"}],"url":"\/documentation\/airwallex\/awxcardbrand"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"AWXPaymentElement","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/title"},{"op":"replace","value":[{"text":"AWXPaymentElement","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/navigatorTitle","value":[{"text":"AWXPaymentElement","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardBrand\/title","value":"AWXCardBrand"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardBrand\/fragments","op":"replace","value":[{"text":"AWXCardBrand","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardBrand\/navigatorTitle","op":"replace","value":[{"text":"AWXCardBrand","kind":"identifier"}]}]}]}