{"metadata":{"externalID":"s:9Airwallex12AWXUIContextC13ConfigurationC19supportedCardBrandsSaySo12AWXCardBrandaGvp","title":"supportedCardBrands","role":"symbol","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"supportedCardBrands","kind":"identifier"},{"text":": [","kind":"text"},{"text":"AWXCardBrand","kind":"typeIdentifier","preciseIdentifier":"c:AWXConstants.h@T@AWXCardBrand"},{"text":"]","kind":"text"}],"roleHeading":"Instance Property","modules":[{"name":"Airwallex"}]},"abstract":[{"type":"text","text":"Supported card brands. Only applies when paymentMethodName is “card”."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/Configuration"]]},"variants":[{"paths":["\/documentation\/airwallex\/awxuicontext\/configuration\/supportedcardbrands"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/Configuration\/supportedCardBrands"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"supportedCardBrands","kind":"identifier"},{"text":": [","kind":"text"},{"text":"AWXCardBrand","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand","preciseIdentifier":"c:AWXConstants.h@T@AWXCardBrand"},{"text":"]","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}]}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","url":"\/documentation\/airwallex","title":"Airwallex","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXUIContext/Configuration/supportedCardBrands":{"title":"supportedCardBrands","type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/Configuration\/supportedCardBrands","abstract":[{"type":"text","text":"Supported card brands. Only applies when paymentMethodName is “card”."}],"url":"\/documentation\/airwallex\/awxuicontext\/configuration\/supportedcardbrands","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"supportedCardBrands","kind":"identifier"},{"text":": [","kind":"text"},{"text":"AWXCardBrand","preciseIdentifier":"c:AWXConstants.h@T@AWXCardBrand","kind":"typeIdentifier"},{"text":"]","kind":"text"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXUIContext":{"role":"symbol","url":"\/documentation\/airwallex\/awxuicontext","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXUIContext","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The main UI context for Airwallex payment flows."}],"title":"AWXUIContext","navigatorTitle":[{"text":"AWXUIContext","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXUIContext/Configuration":{"title":"AWXUIContext.Configuration","type":"topic","role":"symbol","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/Configuration","abstract":[{"type":"text","text":"Configuration options for launching the payment UI."}],"url":"\/documentation\/airwallex\/awxuicontext\/configuration","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardBrand":{"abstract":[],"kind":"symbol","title":"AWXCardBrand","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardBrand","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXCardBrand"}],"navigatorTitle":[{"kind":"identifier","text":"AWXCardBrand"}],"url":"\/documentation\/airwallex\/awxcardbrand"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext\/title","value":"AWXUIContext"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext\/fragments","value":[{"kind":"identifier","text":"AWXUIContext"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext\/navigatorTitle","value":[{"kind":"identifier","text":"AWXUIContext"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardBrand\/title","value":"AWXCardBrand"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardBrand\/fragments","value":[{"kind":"identifier","text":"AWXCardBrand"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardBrand\/navigatorTitle","value":[{"kind":"identifier","text":"AWXCardBrand"}]}]}]}