{"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringWithIntentSession\/requiresCVC()"},"metadata":{"externalID":"c:objc(cs)AWXRecurringWithIntentSession(im)requiresCVC","symbolKind":"method","title":"requiresCVC()","role":"symbol","platforms":[{"deprecated":true,"message":"requiresCVC will be determined by consent returned by server (numberType), passing requiresCVC as a parameter is no longer needed","unavailable":false,"beta":false}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requiresCVC","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"modules":[{"name":"Airwallex"}]},"sections":[],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"requiresCVC will be determined by consent returned by server (numberType), passing requiresCVC as a parameter is no longer needed","type":"text"}]}],"variants":[{"paths":["\/documentation\/airwallex\/awxrecurringwithintentsession\/requirescvc()"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requiresCVC","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringWithIntentSession"]]},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","abstract":[],"title":"Airwallex","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRecurringWithIntentSession":{"role":"symbol","abstract":[{"type":"codeVoice","code":"AWXRecurringWithIntentSession"},{"type":"text","text":" is the session used for recurring with intent."}],"kind":"symbol","navigatorTitle":[{"text":"AWXRecurringWithIntentSession","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxrecurringwithintentsession","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringWithIntentSession","title":"AWXRecurringWithIntentSession","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXRecurringWithIntentSession","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRecurringWithIntentSession/requiresCVC()":{"title":"requiresCVC()","deprecated":true,"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiresCVC"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"role":"symbol","url":"\/documentation\/airwallex\/awxrecurringwithintentsession\/requirescvc()","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringWithIntentSession\/requiresCVC()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRecurringWithIntentSession\/title","op":"replace","value":"AWXRecurringWithIntentSession"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRecurringWithIntentSession\/fragments","op":"replace","value":[{"kind":"identifier","text":"AWXRecurringWithIntentSession"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRecurringWithIntentSession\/navigatorTitle","op":"replace","value":[{"text":"AWXRecurringWithIntentSession","kind":"identifier"}]}]}]}