{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringWithIntentSession\/setRequiresCVC(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setRequiresCVC","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"requiresCVC","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"requiresCVC will be determined by consent returned by server (numberType), passing requiresCVC as a parameter is no longer needed"}],"type":"paragraph"}],"sections":[],"metadata":{"roleHeading":"Instance Method","externalID":"c:objc(cs)AWXRecurringWithIntentSession(im)setRequiresCVC:","platforms":[{"beta":false,"unavailable":false,"message":"requiresCVC will be determined by consent returned by server (numberType), passing requiresCVC as a parameter is no longer needed","deprecated":true}],"title":"setRequiresCVC(_:)","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setRequiresCVC","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"Airwallex"}],"role":"symbol"},"variants":[{"paths":["\/documentation\/airwallex\/awxrecurringwithintentsession\/setrequirescvc(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringWithIntentSession"]]},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRecurringWithIntentSession/setRequiresCVC(_:)":{"url":"\/documentation\/airwallex\/awxrecurringwithintentsession\/setrequirescvc(_:)","kind":"symbol","type":"topic","deprecated":true,"abstract":[],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setRequiresCVC","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringWithIntentSession\/setRequiresCVC(_:)","title":"setRequiresCVC(_:)"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","abstract":[],"title":"Airwallex","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRecurringWithIntentSession":{"role":"symbol","abstract":[{"type":"codeVoice","code":"AWXRecurringWithIntentSession"},{"type":"text","text":" is the session used for recurring with intent."}],"kind":"symbol","navigatorTitle":[{"text":"AWXRecurringWithIntentSession","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxrecurringwithintentsession","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringWithIntentSession","title":"AWXRecurringWithIntentSession","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXRecurringWithIntentSession","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRecurringWithIntentSession\/title","op":"replace","value":"AWXRecurringWithIntentSession"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRecurringWithIntentSession\/fragments","op":"replace","value":[{"kind":"identifier","text":"AWXRecurringWithIntentSession"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRecurringWithIntentSession\/navigatorTitle","op":"replace","value":[{"text":"AWXRecurringWithIntentSession","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}