{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"nextTriggeredBy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexNextTriggerByType","preciseIdentifier":"c:@E@AirwallexNextTriggerByType","text":"AirwallexNextTriggerByType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"merchantTriggerReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexMerchantTriggerReason","preciseIdentifier":"c:@E@AirwallexMerchantTriggerReason","text":"AirwallexMerchantTriggerReason"},{"kind":"text","text":" = .undefined, "},{"kind":"externalParam","text":"termsOfUse"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/TermsOfUse","preciseIdentifier":"c:@M@Airwallex@objc(cs)TermsOfUse","text":"TermsOfUse"},{"kind":"text","text":"? = nil)"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Specifies which party will trigger subsequent payments.","type":"text"},{"text":" ","type":"text"},{"text":"Use ","type":"text"},{"code":".merchantType","type":"codeVoice"},{"text":" when merchant initiates future payments,","type":"text"},{"text":" ","type":"text"},{"text":"or ","type":"text"},{"code":".customerType","type":"codeVoice"},{"text":" when customer initiates future payments.","type":"text"}]}],"name":"nextTriggeredBy"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Indicates whether subsequent payments are scheduled.","type":"text"},{"text":" ","type":"text"},{"text":"Only applicable when nextTriggeredBy is ","type":"text"},{"code":".merchantType","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"Default value is ","type":"text"},{"code":".undefined","type":"codeVoice"},{"text":".","type":"text"}]}],"name":"merchantTriggerReason"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Terms to specify how this Payment Consent will be used.","type":"text"}]}],"name":"termsOfUse"}]}],"abstract":[{"type":"text","text":"Creates a new payment consent options instance for recurring payments."}],"metadata":{"symbolKind":"init","modules":[{"name":"Airwallex"}],"title":"init(nextTriggeredBy:merchantTriggerReason:termsOfUse:)","role":"symbol","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"nextTriggeredBy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@AirwallexNextTriggerByType","text":"AirwallexNextTriggerByType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"merchantTriggerReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@AirwallexMerchantTriggerReason","text":"AirwallexMerchantTriggerReason"},{"kind":"text","text":", "},{"kind":"externalParam","text":"termsOfUse"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@Airwallex@objc(cs)TermsOfUse","text":"TermsOfUse"},{"kind":"text","text":"?)"}],"externalID":"c:@M@Airwallex@objc(cs)PaymentConsentOptions(im)initWithNextTriggeredBy:merchantTriggerReason:termsOfUse:","navigatorTitle":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNextTriggeredBy:merchantTriggerReason:termsOfUse:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentConsentOptions"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentConsentOptions\/init(nextTriggeredBy:merchantTriggerReason:termsOfUse:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/paymentconsentoptions\/init(nexttriggeredby:merchanttriggerreason:termsofuse:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/paymentconsentoptions\/init(nexttriggeredby:merchanttriggerreason:termsofuse:)"]}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexMerchantTriggerReason":{"title":"AirwallexMerchantTriggerReason","type":"topic","role":"symbol","navigatorTitle":[{"text":"AirwallexMerchantTriggerReason","kind":"identifier"}],"url":"\/documentation\/airwallex\/airwallexmerchanttriggerreason","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexMerchantTriggerReason","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AirwallexMerchantTriggerReason","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentConsentOptions/init(nextTriggeredBy:merchantTriggerReason:termsOfUse:)":{"abstract":[{"type":"text","text":"Creates a new payment consent options instance for recurring payments."}],"kind":"symbol","title":"init(nextTriggeredBy:merchantTriggerReason:termsOfUse:)","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentConsentOptions\/init(nextTriggeredBy:merchantTriggerReason:termsOfUse:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"nextTriggeredBy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@AirwallexNextTriggerByType","text":"AirwallexNextTriggerByType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"merchantTriggerReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@AirwallexMerchantTriggerReason","text":"AirwallexMerchantTriggerReason"},{"kind":"text","text":", "},{"kind":"externalParam","text":"termsOfUse"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@Airwallex@objc(cs)TermsOfUse","text":"TermsOfUse"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"text":"- ","kind":"text"},{"text":"initWithNextTriggeredBy:merchantTriggerReason:termsOfUse:","kind":"identifier"}],"url":"\/documentation\/airwallex\/paymentconsentoptions\/init(nexttriggeredby:merchanttriggerreason:termsofuse:)"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","url":"\/documentation\/airwallex","title":"Airwallex","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexNextTriggerByType":{"title":"AirwallexNextTriggerByType","type":"topic","role":"symbol","navigatorTitle":[{"text":"AirwallexNextTriggerByType","kind":"identifier"}],"url":"\/documentation\/airwallex\/airwallexnexttriggerbytype","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexNextTriggerByType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AirwallexNextTriggerByType","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/PaymentConsentOptions":{"kind":"symbol","type":"topic","abstract":[{"text":"Options for payment consents","type":"text"}],"role":"symbol","url":"\/documentation\/airwallex\/paymentconsentoptions","title":"PaymentConsentOptions","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/PaymentConsentOptions","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PaymentConsentOptions","kind":"identifier"}],"navigatorTitle":[{"text":"PaymentConsentOptions","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/TermsOfUse":{"role":"symbol","url":"\/documentation\/airwallex\/termsofuse","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/TermsOfUse","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TermsOfUse"}],"kind":"symbol","type":"topic","title":"TermsOfUse","abstract":[{"type":"text","text":"Terms to specify how this Payment Consent will be used"}],"navigatorTitle":[{"kind":"identifier","text":"TermsOfUse"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"initWithNextTriggeredBy:merchantTriggerReason:termsOfUse:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNextTriggeredBy:merchantTriggerReason:termsOfUse:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithNextTriggeredBy:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@AirwallexNextTriggerByType","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexNextTriggerByType","text":"AirwallexNextTriggerByType","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"nextTriggeredBy","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"merchantTriggerReason:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@AirwallexMerchantTriggerReason","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexMerchantTriggerReason","text":"AirwallexMerchantTriggerReason","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"merchantTriggerReason","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"termsOfUse:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@Airwallex@objc(cs)TermsOfUse","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/TermsOfUse","text":"TermsOfUse","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"termsOfUse","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"Specifies which party will trigger subsequent payments.","type":"text"},{"text":" ","type":"text"},{"text":"Use ","type":"text"},{"code":".merchantType","type":"codeVoice"},{"text":" when merchant initiates future payments,","type":"text"},{"text":" ","type":"text"},{"text":"or ","type":"text"},{"code":".customerType","type":"codeVoice"},{"text":" when customer initiates future payments.","type":"text"}],"type":"paragraph"}],"name":"nextTriggeredBy"},{"content":[{"inlineContent":[{"text":"Indicates whether subsequent payments are scheduled.","type":"text"},{"text":" ","type":"text"},{"text":"Only applicable when nextTriggeredBy is ","type":"text"},{"code":".merchantType","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"Default value is ","type":"text"},{"code":".undefined","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}],"name":"merchantTriggerReason"},{"content":[{"inlineContent":[{"text":"Terms to specify how this Payment Consent will be used.","type":"text"}],"type":"paragraph"}],"name":"termsOfUse"}]},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"AirwallexMerchantTriggerReason","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexMerchantTriggerReason\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AirwallexMerchantTriggerReason"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexMerchantTriggerReason\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AirwallexMerchantTriggerReason"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexMerchantTriggerReason\/navigatorTitle","op":"replace"},{"value":"initWithNextTriggeredBy:merchantTriggerReason:termsOfUse:","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentConsentOptions~1init(nextTriggeredBy:merchantTriggerReason:termsOfUse:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNextTriggeredBy:merchantTriggerReason:termsOfUse:"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentConsentOptions~1init(nextTriggeredBy:merchantTriggerReason:termsOfUse:)\/fragments","op":"replace"},{"value":"AirwallexNextTriggerByType","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexNextTriggerByType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AirwallexNextTriggerByType"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexNextTriggerByType\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AirwallexNextTriggerByType"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexNextTriggerByType\/navigatorTitle","op":"replace"},{"value":"PaymentConsentOptions","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentConsentOptions\/title","op":"replace"},{"value":[{"kind":"identifier","text":"PaymentConsentOptions"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentConsentOptions\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"PaymentConsentOptions"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1PaymentConsentOptions\/navigatorTitle","op":"replace"},{"value":"TermsOfUse","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1TermsOfUse\/title","op":"replace"},{"value":[{"kind":"identifier","text":"TermsOfUse"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1TermsOfUse\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1TermsOfUse\/navigatorTitle","value":[{"kind":"identifier","text":"TermsOfUse"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}