{"kind":"symbol","metadata":{"role":"symbol","symbolKind":"property","modules":[{"name":"Airwallex"}],"navigatorTitle":[{"kind":"identifier","text":"textFieldType"}],"title":"textFieldType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textFieldType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@AWXTextFieldType","text":"AWXTextFieldType"}],"externalID":"c:objc(cs)AWXForm(py)textFieldType","roleHeading":"Instance Property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxform\/textfieldtype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxform\/textfieldtype"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXForm"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textFieldType","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType","text":"AWXTextFieldType","preciseIdentifier":"c:@E@AWXTextFieldType","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXForm\/textFieldType"},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXForm/textFieldType":{"kind":"symbol","url":"\/documentation\/airwallex\/awxform\/textfieldtype","role":"symbol","type":"topic","navigatorTitle":[{"text":"textFieldType","kind":"identifier"}],"title":"textFieldType","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXForm\/textFieldType","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textFieldType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWXTextFieldType","preciseIdentifier":"c:@E@AWXTextFieldType","kind":"typeIdentifier"}],"abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"abstract":[],"kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","url":"\/documentation\/airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXTextFieldType":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXTextFieldType","kind":"identifier"}],"title":"AWXTextFieldType","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType","abstract":[],"url":"\/documentation\/airwallex\/awxtextfieldtype","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"AWXTextFieldType","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXForm":{"abstract":[],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXForm","title":"AWXForm","navigatorTitle":[{"kind":"identifier","text":"AWXForm"}],"url":"\/documentation\/airwallex\/awxform","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXForm"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"textFieldType","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"textFieldType","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":") "},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType","kind":"typeIdentifier","text":"AWXTextFieldType","preciseIdentifier":"c:@E@AWXTextFieldType"},{"kind":"text","text":" "},{"kind":"identifier","text":"textFieldType"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"textFieldType","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXForm~1textFieldType\/title","op":"replace"},{"value":[{"text":"textFieldType","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXForm~1textFieldType\/fragments","op":"replace"},{"value":"AWXTextFieldType","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType\/title","op":"replace"},{"value":[{"text":"AWXTextFieldType","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType\/fragments","op":"replace"},{"value":[{"text":"AWXTextFieldType","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType\/navigatorTitle","op":"replace"},{"value":"AWXForm","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXForm\/title","op":"replace"},{"value":[{"text":"AWXForm","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXForm\/fragments","op":"replace"},{"value":[{"text":"AWXForm","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXForm\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}