{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSDKErrorCode"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSDKErrorCode\/userCancelled"},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxsdkerrorcode\/usercancelled"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxsdkerrorcode\/usercancelled"]}],"metadata":{"externalID":"c:@E@AWXSDKErrorCode@AWXSDKErrorCodeUserCancelled","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"userCancelled"}],"title":"AWXSDKErrorCode.userCancelled","symbolKind":"case","modules":[{"name":"Airwallex"}],"roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"AWXSDKErrorCodeUserCancelled"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userCancelled","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}]}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSDKErrorCode/userCancelled":{"type":"topic","abstract":[],"title":"AWXSDKErrorCode.userCancelled","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSDKErrorCode\/userCancelled","navigatorTitle":[{"kind":"identifier","text":"AWXSDKErrorCodeUserCancelled"}],"url":"\/documentation\/airwallex\/awxsdkerrorcode\/usercancelled","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"userCancelled"}],"kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","role":"collection","title":"Airwallex","type":"topic","url":"\/documentation\/airwallex","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSDKErrorCode":{"type":"topic","abstract":[],"title":"AWXSDKErrorCode","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSDKErrorCode","navigatorTitle":[{"kind":"identifier","text":"AWXSDKErrorCode"}],"url":"\/documentation\/airwallex\/awxsdkerrorcode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXSDKErrorCode"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/platforms","op":"add","value":null},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"AWXSDKErrorCodeUserCancelled","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"AWXSDKErrorCodeUserCancelled"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AWXSDKErrorCodeUserCancelled"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSDKErrorCode~1userCancelled\/title","op":"replace","value":"AWXSDKErrorCodeUserCancelled"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSDKErrorCode~1userCancelled\/fragments","op":"replace","value":[{"text":"AWXSDKErrorCodeUserCancelled","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSDKErrorCode\/title","op":"replace","value":"AWXSDKErrorCode"},{"op":"replace","value":[{"text":"AWXSDKErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSDKErrorCode\/fragments"},{"op":"replace","value":[{"text":"AWXSDKErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSDKErrorCode\/navigatorTitle"}]}]}