{"kind":"symbol","metadata":{"title":"items","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"items","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)AWXPaymentMethodType","text":"AWXPaymentMethodType","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"externalID":"c:objc(cs)AWXGetPaymentMethodTypesResponse(py)items","role":"symbol","modules":[{"name":"Airwallex"}],"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"items"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypesResponse"]]},"abstract":[{"text":"Payment methods.","type":"text"}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypesResponse\/items","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"items","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)AWXPaymentMethodType","text":"AWXPaymentMethodType","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethodType"},{"text":"] { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxgetpaymentmethodtypesresponse\/items"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxgetpaymentmethodtypesresponse\/items"]}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentMethodType":{"abstract":[{"code":"AWXPaymentMethodType","type":"codeVoice"},{"text":" includes the information of a payment method.","type":"text"}],"title":"AWXPaymentMethodType","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethodType","navigatorTitle":[{"kind":"identifier","text":"AWXPaymentMethodType"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentMethodType"}],"kind":"symbol","url":"\/documentation\/airwallex\/awxpaymentmethodtype","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentMethodTypesResponse/items":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"items"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPaymentMethodType","text":"AWXPaymentMethodType"},{"kind":"text","text":"]"}],"title":"items","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypesResponse\/items","type":"topic","navigatorTitle":[{"kind":"identifier","text":"items"}],"abstract":[{"type":"text","text":"Payment methods."}],"url":"\/documentation\/airwallex\/awxgetpaymentmethodtypesresponse\/items"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXGetPaymentMethodTypesResponse":{"title":"AWXGetPaymentMethodTypesResponse","abstract":[{"type":"codeVoice","code":"AWXGetPaymentMethodTypesResponse"},{"type":"text","text":" includes the list of payment methods."}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXGetPaymentMethodTypesResponse","navigatorTitle":[{"text":"AWXGetPaymentMethodTypesResponse","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXGetPaymentMethodTypesResponse","kind":"identifier"}],"type":"topic","url":"\/documentation\/airwallex\/awxgetpaymentmethodtypesresponse","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","abstract":[],"type":"topic","kind":"symbol","title":"Airwallex","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"items","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"items","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<AWXPaymentMethodType *>"},{"kind":"text","text":" * "},{"kind":"identifier","text":"items"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"AWXPaymentMethodType","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethodType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AWXPaymentMethodType"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethodType\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AWXPaymentMethodType"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethodType\/navigatorTitle","op":"replace"},{"value":"items","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypesResponse~1items\/title","op":"replace"},{"value":[{"kind":"identifier","text":"items"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypesResponse~1items\/fragments","op":"replace"},{"value":"AWXGetPaymentMethodTypesResponse","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypesResponse\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AWXGetPaymentMethodTypesResponse"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypesResponse\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AWXGetPaymentMethodTypesResponse"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXGetPaymentMethodTypesResponse\/navigatorTitle","op":"replace"}]}]}