{"kind":"symbol","metadata":{"roleHeading":"Operator","role":"symbol","title":"!=(_:_:)","symbolKind":"op","extendedModule":"Swift","externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::s:9Airwallex12AWXUIContextC13PaymentLayoutO","modules":[{"relatedModules":["Swift"],"name":"Airwallex"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"Equatable.!=(_:_:)","type":"codeVoice"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/PaymentLayout"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"lhs","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"rhs","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/PaymentLayout\/!=(_:_:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxuicontext\/paymentlayout\/!=(_:_:)"]}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXUIContext/PaymentLayout":{"navigatorTitle":[{"text":"PaymentLayout","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxuicontext\/paymentlayout","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PaymentLayout","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/PaymentLayout","abstract":[{"type":"text","text":"Defines the layout style for payment method selection."}],"title":"AWXUIContext.PaymentLayout"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXUIContext/PaymentLayout/!=(_:_:)":{"type":"topic","title":"!=(_:_:)","role":"symbol","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext\/PaymentLayout\/!=(_:_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"url":"\/documentation\/airwallex\/awxuicontext\/paymentlayout\/!=(_:_:)"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/airwallex","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXUIContext":{"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXUIContext","kind":"symbol","abstract":[{"type":"text","text":"The main UI context for Airwallex payment flows."}],"role":"symbol","url":"\/documentation\/airwallex\/awxuicontext","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXUIContext","kind":"identifier"}],"navigatorTitle":[{"text":"AWXUIContext","kind":"identifier"}],"title":"AWXUIContext"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext\/title","value":"AWXUIContext"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext\/fragments","value":[{"text":"AWXUIContext","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXUIContext\/navigatorTitle","value":[{"text":"AWXUIContext","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}