{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentAttempt"]]},"abstract":[{"text":"3DS authentication data.","type":"text"}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentAttempt\/authenticationData","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"authenticationData","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAuthenticationData","preciseIdentifier":"c:objc(cs)AWXAuthenticationData","text":"AWXAuthenticationData","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/airwallex\/awxpaymentattempt\/authenticationdata"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxpaymentattempt\/authenticationdata"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"authenticationData","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWXAuthenticationData","preciseIdentifier":"c:objc(cs)AWXAuthenticationData","kind":"typeIdentifier"}],"modules":[{"name":"Airwallex"}],"role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"text":"authenticationData","kind":"identifier"}],"title":"authenticationData","externalID":"c:objc(cs)AWXPaymentAttempt(py)authenticationData","symbolKind":"property"},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentAttempt/authenticationData":{"type":"topic","kind":"symbol","title":"authenticationData","url":"\/documentation\/airwallex\/awxpaymentattempt\/authenticationdata","abstract":[{"text":"3DS authentication data.","type":"text"}],"navigatorTitle":[{"text":"authenticationData","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentAttempt\/authenticationData","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"authenticationData","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWXAuthenticationData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXAuthenticationData"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","abstract":[],"title":"Airwallex","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXAuthenticationData":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXAuthenticationData"}],"url":"\/documentation\/airwallex\/awxauthenticationdata","abstract":[{"code":"AWXAuthenticationData","type":"codeVoice"},{"text":" includes the parameters for 3ds authentication.","type":"text"}],"role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AWXAuthenticationData"}],"title":"AWXAuthenticationData","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAuthenticationData"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentAttempt":{"title":"AWXPaymentAttempt","url":"\/documentation\/airwallex\/awxpaymentattempt","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentAttempt","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPaymentAttempt","kind":"identifier"}],"role":"symbol","abstract":[{"type":"codeVoice","code":"AWXPaymentAttempt"},{"type":"text","text":" includes the information of payment attempt."}],"kind":"symbol","navigatorTitle":[{"text":"AWXPaymentAttempt","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"authenticationData","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"authenticationData","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAuthenticationData","text":"AWXAuthenticationData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXAuthenticationData"},{"text":" * ","kind":"text"},{"text":"authenticationData","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"authenticationData","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentAttempt~1authenticationData\/title"},{"op":"replace","value":[{"text":"authenticationData","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentAttempt~1authenticationData\/fragments"},{"op":"replace","value":"AWXAuthenticationData","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAuthenticationData\/title"},{"op":"replace","value":[{"text":"AWXAuthenticationData","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAuthenticationData\/fragments"},{"value":[{"kind":"identifier","text":"AWXAuthenticationData"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAuthenticationData\/navigatorTitle"},{"value":"AWXPaymentAttempt","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentAttempt\/title"},{"value":[{"text":"AWXPaymentAttempt","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentAttempt\/fragments"},{"value":[{"text":"AWXPaymentAttempt","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentAttempt\/navigatorTitle"}]}]}