{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"previewMode","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexSDKMode\/previewMode"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexSDKMode"]]},"metadata":{"externalID":"c:@E@AirwallexSDKMode@AirwallexSDKPreviewMode","symbolKind":"case","modules":[{"name":"Airwallex"}],"role":"symbol","navigatorTitle":[{"text":"AirwallexSDKPreviewMode","kind":"identifier"}],"roleHeading":"Case","title":"AirwallexSDKMode.previewMode","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewMode"}]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/airwallexsdkmode\/previewmode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/airwallexsdkmode\/previewmode"]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexSDKMode/previewMode":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewMode"}],"title":"AirwallexSDKMode.previewMode","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AirwallexSDKPreviewMode"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexSDKMode\/previewMode","url":"\/documentation\/airwallex\/airwallexsdkmode\/previewmode","type":"topic","abstract":[],"role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexSDKMode":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexSDKMode","url":"\/documentation\/airwallex\/airwallexsdkmode","navigatorTitle":[{"kind":"identifier","text":"AirwallexSDKMode"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AirwallexSDKMode"}],"kind":"symbol","title":"AirwallexSDKMode"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","url":"\/documentation\/airwallex","abstract":[],"title":"Airwallex"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"AirwallexSDKPreviewMode","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"AirwallexSDKPreviewMode"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"AirwallexSDKPreviewMode"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"AirwallexSDKPreviewMode","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexSDKMode~1previewMode\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AirwallexSDKPreviewMode"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexSDKMode~1previewMode\/fragments"},{"op":"replace","value":"AirwallexSDKMode","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexSDKMode\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AirwallexSDKMode"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexSDKMode\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AirwallexSDKMode"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexSDKMode\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}