{"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"variants":[{"paths":["\/documentation\/airwallex\/awxproviderdelegate\/provider(_:didinitializepaymentintentid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxproviderdelegate\/provider(_:didinitializepaymentintentid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXProviderDelegate"]]},"metadata":{"symbolKind":"method","modules":[{"name":"Airwallex"}],"roleHeading":"Instance Method","role":"symbol","externalID":"c:objc(pl)AWXProviderDelegate(im)provider:didInitializePaymentIntentId:","navigatorTitle":[{"kind":"identifier","text":"provider:didInitializePaymentIntentId:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"provider"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AWXDefaultProvider","preciseIdentifier":"c:objc(cs)AWXDefaultProvider"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didInitializePaymentIntentId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"provider(_:didInitializePaymentIntentId:)","required":true},"abstract":[{"type":"text","text":"This method is called when it is generated new payment intent."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"provider","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"provider","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"AWXDefaultProvider","preciseIdentifier":"c:objc(cs)AWXDefaultProvider","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider"},{"text":", ","kind":"text"},{"text":"didInitializePaymentIntentId","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"paymentIntentId","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The provider handling payment."}],"type":"paragraph"}],"name":"provider"},{"content":[{"inlineContent":[{"type":"text","text":"The new payment intent id."}],"type":"paragraph"}],"name":"paymentIntentId"}],"kind":"parameters"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXProviderDelegate\/provider(_:didInitializePaymentIntentId:)"},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXProviderDelegate":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXProviderDelegate","title":"AWXProviderDelegate","abstract":[{"text":"A delegate which handles checkout results.","type":"text"}],"url":"\/documentation\/airwallex\/awxproviderdelegate","navigatorTitle":[{"kind":"identifier","text":"AWXProviderDelegate"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXProviderDelegate","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXDefaultProvider":{"navigatorTitle":[{"kind":"identifier","text":"AWXDefaultProvider"}],"abstract":[{"text":"A provider which handles payment business.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXDefaultProvider"}],"url":"\/documentation\/airwallex\/awxdefaultprovider","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider","kind":"symbol","title":"AWXDefaultProvider","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXProviderDelegate/provider(_:didInitializePaymentIntentId:)":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXProviderDelegate\/provider(_:didInitializePaymentIntentId:)","required":true,"url":"\/documentation\/airwallex\/awxproviderdelegate\/provider(_:didinitializepaymentintentid:)","navigatorTitle":[{"text":"provider:didInitializePaymentIntentId:","kind":"identifier"}],"type":"topic","title":"provider(_:didInitializePaymentIntentId:)","kind":"symbol","abstract":[{"type":"text","text":"This method is called when it is generated new payment intent."}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"provider"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXDefaultProvider","text":"AWXDefaultProvider"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didInitializePaymentIntentId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","abstract":[],"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/airwallex"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"provider:didInitializePaymentIntentId:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"provider:didInitializePaymentIntentId:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"provider:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AWXDefaultProvider","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXDefaultProvider"},{"text":" *) ","kind":"text"},{"text":"provider","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didInitializePaymentIntentId:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"paymentIntentId","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The provider handling payment."}]}],"name":"provider"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The new payment intent id.","type":"text"}]}],"name":"paymentIntentId"}],"kind":"parameters"}},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXProviderDelegate\/title","op":"replace","value":"AWXProviderDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXProviderDelegate\/fragments","op":"replace","value":[{"text":"AWXProviderDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXProviderDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AWXProviderDelegate"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider\/title","op":"replace","value":"AWXDefaultProvider"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider\/fragments","op":"replace","value":[{"kind":"identifier","text":"AWXDefaultProvider"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider\/navigatorTitle","op":"replace","value":[{"text":"AWXDefaultProvider","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXProviderDelegate~1provider(_:didInitializePaymentIntentId:)\/title","op":"replace","value":"provider:didInitializePaymentIntentId:"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXProviderDelegate~1provider(_:didInitializePaymentIntentId:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"provider:didInitializePaymentIntentId:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}