{"abstract":[{"type":"text","text":"This method is called when new controller is required."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"provider","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"provider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWXDefaultProvider","preciseIdentifier":"c:objc(cs)AWXDefaultProvider","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider"},{"text":", ","kind":"text"},{"text":"shouldPresent","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"forceToDismiss"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"text":"withAnimation","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The provider handling payment."}]}],"name":"provider"},{"content":[{"inlineContent":[{"text":"The view controller will be presented.","type":"text"}],"type":"paragraph"}],"name":"controller"},{"content":[{"inlineContent":[{"text":"Whether the presenting view controller needs be dismissed forcibly.","type":"text"}],"type":"paragraph"}],"name":"forceToDismiss"}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXProviderDelegate"]]},"variants":[{"paths":["\/documentation\/airwallex\/awxproviderdelegate\/provider(_:shouldpresent:forcetodismiss:withanimation:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxproviderdelegate\/provider(_:shouldpresent:forcetodismiss:withanimation:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"title":"provider(_:shouldPresent:forceToDismiss:withAnimation:)","modules":[{"name":"Airwallex"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"provider","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AWXDefaultProvider","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXDefaultProvider"},{"text":", ","kind":"text"},{"text":"shouldPresent","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":"?, ","kind":"text"},{"text":"forceToDismiss","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"withAnimation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"externalID":"c:objc(pl)AWXProviderDelegate(im)provider:shouldPresentViewController:forceToDismiss:withAnimation:","platforms":[{"name":"iOS","deprecated":false,"introducedAt":"2.0","unavailable":false,"beta":false},{"name":"iPadOS","deprecated":false,"introducedAt":"2.0","unavailable":false,"beta":false},{"name":"Mac Catalyst","deprecated":false,"introducedAt":"2.0","unavailable":false,"beta":false}],"role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"text":"provider:shouldPresentViewController:forceToDismiss:withAnimation:","kind":"identifier"}],"symbolKind":"method"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXProviderDelegate\/provider(_:shouldPresent:forceToDismiss:withAnimation:)"},"sections":[],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXProviderDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXProviderDelegate"}],"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXProviderDelegate","url":"\/documentation\/airwallex\/awxproviderdelegate","abstract":[{"type":"text","text":"A delegate which handles checkout results."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWXProviderDelegate"}],"title":"AWXProviderDelegate"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXDefaultProvider":{"url":"\/documentation\/airwallex\/awxdefaultprovider","abstract":[{"text":"A provider which handles payment business.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXDefaultProvider"}],"navigatorTitle":[{"kind":"identifier","text":"AWXDefaultProvider"}],"kind":"symbol","title":"AWXDefaultProvider","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXProviderDelegate/provider(_:shouldPresent:forceToDismiss:withAnimation:)":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXProviderDelegate\/provider(_:shouldPresent:forceToDismiss:withAnimation:)","role":"symbol","type":"topic","abstract":[{"text":"This method is called when new controller is required.","type":"text"}],"url":"\/documentation\/airwallex\/awxproviderdelegate\/provider(_:shouldpresent:forcetodismiss:withanimation:)","title":"provider(_:shouldPresent:forceToDismiss:withAnimation:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"provider","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AWXDefaultProvider","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXDefaultProvider"},{"text":", ","kind":"text"},{"text":"shouldPresent","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":"?, ","kind":"text"},{"text":"forceToDismiss","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"withAnimation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"provider:shouldPresentViewController:forceToDismiss:withAnimation:","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","title":"Airwallex","abstract":[],"type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"provider:shouldPresentViewController:forceToDismiss:withAnimation:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"provider:shouldPresentViewController:forceToDismiss:withAnimation:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"provider:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXDefaultProvider","text":"AWXDefaultProvider"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"provider"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldPresentViewController:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"controller"},{"text":" ","kind":"text"},{"text":"forceToDismiss:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"forceToDismiss","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"withAnimation:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"withAnimation"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The provider handling payment.","type":"text"}]}],"name":"provider"},{"content":[{"inlineContent":[{"type":"text","text":"The view controller will be presented."}],"type":"paragraph"}],"name":"controller"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Whether the presenting view controller needs be dismissed forcibly."}]}],"name":"forceToDismiss"}]},"path":"\/primaryContentSections\/1"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXProviderDelegate\/title","op":"replace","value":"AWXProviderDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXProviderDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"AWXProviderDelegate"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXProviderDelegate\/navigatorTitle","op":"replace","value":[{"text":"AWXProviderDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider\/title","op":"replace","value":"AWXDefaultProvider"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider\/fragments","value":[{"kind":"identifier","text":"AWXDefaultProvider"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider\/navigatorTitle","value":[{"text":"AWXDefaultProvider","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXProviderDelegate~1provider(_:shouldPresent:forceToDismiss:withAnimation:)\/title","value":"provider:shouldPresentViewController:forceToDismiss:withAnimation:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXProviderDelegate~1provider(_:shouldPresent:forceToDismiss:withAnimation:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"provider:shouldPresentViewController:forceToDismiss:withAnimation:"}],"op":"replace"}]}]}