{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"merchantIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxapplepayoptions\/init(merchantidentifier:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxapplepayoptions\/init(merchantidentifier:)"]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"symbolKind":"init","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"merchantIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"externalID":"c:objc(cs)AWXApplePayOptions(im)initWithMerchantIdentifier:","roleHeading":"Initializer","title":"init(merchantIdentifier:)","navigatorTitle":[{"kind":"identifier","text":"initWithMerchantIdentifier:"}],"modules":[{"name":"Airwallex"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions\/init(merchantIdentifier:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions"]]},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"title":"Airwallex","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/airwallex","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXApplePayOptions/init(merchantIdentifier:)":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions\/init(merchantIdentifier:)","title":"init(merchantIdentifier:)","navigatorTitle":[{"kind":"identifier","text":"initWithMerchantIdentifier:"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"merchantIdentifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"type":"topic","abstract":[],"url":"\/documentation\/airwallex\/awxapplepayoptions\/init(merchantidentifier:)","role":"symbol","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXApplePayOptions":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions","title":"AWXApplePayOptions","abstract":[{"type":"text","text":"Object used to construct PKPaymentRequest for Apple Pay."}],"role":"symbol","navigatorTitle":[{"text":"AWXApplePayOptions","kind":"identifier"}],"type":"topic","url":"\/documentation\/airwallex\/awxapplepayoptions","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXApplePayOptions","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"initWithMerchantIdentifier:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMerchantIdentifier:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithMerchantIdentifier:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"merchantIdentifier","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions~1init(merchantIdentifier:)\/title","value":"initWithMerchantIdentifier:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMerchantIdentifier:"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions~1init(merchantIdentifier:)\/fragments"},{"op":"replace","value":"AWXApplePayOptions","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AWXApplePayOptions"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions\/fragments"},{"op":"replace","value":[{"text":"AWXApplePayOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}