{"kind":"symbol","metadata":{"role":"symbol","roleHeading":"Initializer","externalID":"c:objc(cs)AWXPaymentFormViewModel(im)initWithSession:paymentMethod:formMapping:","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"session","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AWXSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXSession"},{"text":", ","kind":"text"},{"text":"paymentMethod","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AWXPaymentMethod","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPaymentMethod"},{"text":", ","kind":"text"},{"text":"formMapping","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AWXFormMapping","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXFormMapping"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithSession:paymentMethod:formMapping:","kind":"identifier"}],"modules":[{"name":"Airwallex"}],"title":"init(session:paymentMethod:formMapping:)","symbolKind":"init"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentFormViewModel"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxpaymentformviewmodel\/init(session:paymentmethod:formmapping:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxpaymentformviewmodel\/init(session:paymentmethod:formmapping:)"]}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentFormViewModel\/init(session:paymentMethod:formMapping:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"session","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AWXSession","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession","preciseIdentifier":"c:objc(cs)AWXSession"},{"text":", ","kind":"text"},{"text":"paymentMethod","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AWXPaymentMethod","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod","preciseIdentifier":"c:objc(cs)AWXPaymentMethod"},{"text":", ","kind":"text"},{"text":"formMapping","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AWXFormMapping","preciseIdentifier":"c:objc(cs)AWXFormMapping","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXFormMapping","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentMethod":{"title":"AWXPaymentMethod","role":"symbol","abstract":[{"type":"codeVoice","code":"AWXPaymentMethod"},{"type":"text","text":" includes the information of a payment method."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPaymentMethod","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"AWXPaymentMethod","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod","url":"\/documentation\/airwallex\/awxpaymentmethod"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXFormMapping":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXFormMapping"}],"navigatorTitle":[{"text":"AWXFormMapping","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXFormMapping","title":"AWXFormMapping","abstract":[],"type":"topic","url":"\/documentation\/airwallex\/awxformmapping"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSession":{"abstract":[{"code":"AWXSession","type":"codeVoice"},{"text":" is the base session.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXSession"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWXSession"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession","type":"topic","role":"symbol","title":"AWXSession","url":"\/documentation\/airwallex\/awxsession"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol","type":"topic","url":"\/documentation\/airwallex","role":"collection","abstract":[],"title":"Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentFormViewModel":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentFormViewModel","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWXPaymentFormViewModel"}],"url":"\/documentation\/airwallex\/awxpaymentformviewmodel","abstract":[],"title":"AWXPaymentFormViewModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentFormViewModel"}],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentFormViewModel/init(session:paymentMethod:formMapping:)":{"url":"\/documentation\/airwallex\/awxpaymentformviewmodel\/init(session:paymentmethod:formmapping:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"session","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AWXSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXSession"},{"text":", ","kind":"text"},{"text":"paymentMethod","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AWXPaymentMethod","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPaymentMethod"},{"text":", ","kind":"text"},{"text":"formMapping","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AWXFormMapping","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXFormMapping"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithSession:paymentMethod:formMapping:","kind":"identifier"}],"abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentFormViewModel\/init(session:paymentMethod:formMapping:)","title":"init(session:paymentMethod:formMapping:)","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"initWithSession:paymentMethod:formMapping:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithSession:paymentMethod:formMapping:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithSession:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AWXSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXSession","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession"},{"text":" *) ","kind":"text"},{"text":"session","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"paymentMethod:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AWXPaymentMethod","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPaymentMethod","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod"},{"text":" *) ","kind":"text"},{"text":"paymentMethod","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"formMapping:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AWXFormMapping","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXFormMapping","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXFormMapping"},{"text":" *) ","kind":"text"},{"text":"formMapping","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethod\/title","value":"AWXPaymentMethod","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethod\/fragments","value":[{"text":"AWXPaymentMethod","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethod\/navigatorTitle","value":[{"text":"AWXPaymentMethod","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXFormMapping\/title","value":"AWXFormMapping","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXFormMapping\/fragments","value":[{"text":"AWXFormMapping","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXFormMapping\/navigatorTitle","value":[{"kind":"identifier","text":"AWXFormMapping"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/title","value":"AWXSession","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/fragments","value":[{"kind":"identifier","text":"AWXSession"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/navigatorTitle","value":[{"text":"AWXSession","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentFormViewModel\/title","value":"AWXPaymentFormViewModel","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentFormViewModel\/fragments","value":[{"text":"AWXPaymentFormViewModel","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentFormViewModel\/navigatorTitle","value":[{"kind":"identifier","text":"AWXPaymentFormViewModel"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentFormViewModel~1init(session:paymentMethod:formMapping:)\/title","value":"initWithSession:paymentMethod:formMapping:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentFormViewModel~1init(session:paymentMethod:formMapping:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithSession:paymentMethod:formMapping:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}