{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxpaymentformviewmodel\/session"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxpaymentformviewmodel\/session"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentFormViewModel"]]},"metadata":{"modules":[{"name":"Airwallex"}],"roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"text":"session","kind":"identifier"}],"title":"session","externalID":"c:objc(cs)AWXPaymentFormViewModel(py)session","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"session","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWXSession","preciseIdentifier":"c:objc(cs)AWXSession","kind":"typeIdentifier"}]},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentFormViewModel\/session","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"session"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AWXSession","text":"AWXSession","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol","type":"topic","url":"\/documentation\/airwallex","role":"collection","abstract":[],"title":"Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentFormViewModel":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentFormViewModel","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWXPaymentFormViewModel"}],"url":"\/documentation\/airwallex\/awxpaymentformviewmodel","abstract":[],"title":"AWXPaymentFormViewModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentFormViewModel"}],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSession":{"abstract":[{"code":"AWXSession","type":"codeVoice"},{"text":" is the base session.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXSession"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWXSession"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession","type":"topic","role":"symbol","title":"AWXSession","url":"\/documentation\/airwallex\/awxsession"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentFormViewModel/session":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"session"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWXSession","preciseIdentifier":"c:objc(cs)AWXSession"}],"navigatorTitle":[{"kind":"identifier","text":"session"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentFormViewModel\/session","title":"session","abstract":[],"type":"topic","url":"\/documentation\/airwallex\/awxpaymentformviewmodel\/session"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"session"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"session"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"AWXSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXSession","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession"},{"text":" * ","kind":"text"},{"text":"session","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentFormViewModel\/title","value":"AWXPaymentFormViewModel"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentFormViewModel\/fragments","value":[{"kind":"identifier","text":"AWXPaymentFormViewModel"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentFormViewModel\/navigatorTitle","value":[{"text":"AWXPaymentFormViewModel","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/title","value":"AWXSession"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/fragments","value":[{"kind":"identifier","text":"AWXSession"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/navigatorTitle","value":[{"kind":"identifier","text":"AWXSession"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentFormViewModel~1session\/title","value":"session"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentFormViewModel~1session\/fragments","value":[{"text":"session","kind":"identifier"}]}]}]}