{"metadata":{"title":"matchesPrefix(_:)","navigatorTitle":[{"kind":"identifier","text":"matchesPrefix:"}],"externalID":"c:objc(cs)AWXBrand(im)matchesPrefix:","roleHeading":"Instance Method","modules":[{"name":"Airwallex"}],"role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"matchesPrefix","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrand\/matchesPrefix(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"matchesPrefix","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"number","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]}],"kind":"declarations"}],"sections":[],"variants":[{"paths":["\/documentation\/airwallex\/awxbrand\/matchesprefix(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxbrand\/matchesprefix(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrand"]]},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXBrand":{"title":"AWXBrand","abstract":[{"code":"AWXBrand","type":"codeVoice"},{"type":"text","text":" manages the card scheme brand."}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrand","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXBrand","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/airwallex\/awxbrand","type":"topic","navigatorTitle":[{"text":"AWXBrand","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXBrand/matchesPrefix(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"matchesPrefix"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","abstract":[],"url":"\/documentation\/airwallex\/awxbrand\/matchesprefix(_:)","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrand\/matchesPrefix(_:)","navigatorTitle":[{"kind":"identifier","text":"matchesPrefix:"}],"role":"symbol","title":"matchesPrefix(_:)","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","abstract":[],"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/airwallex"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"matchesPrefix:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"matchesPrefix:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"matchesPrefix:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"number","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrand\/title","value":"AWXBrand"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrand\/fragments","value":[{"text":"AWXBrand","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrand\/navigatorTitle","value":[{"text":"AWXBrand","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrand~1matchesPrefix(_:)\/title","value":"matchesPrefix:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrand~1matchesPrefix(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"matchesPrefix:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}