{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shadowColor","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme\/shadowColor()"},"kind":"symbol","variants":[{"paths":["\/documentation\/airwallex\/awxtheme\/shadowcolor()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxtheme\/shadowcolor()"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"symbolKind":"method","externalID":"c:objc(cs)AWXTheme(im)shadowColor","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shadowColor","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"shadowColor"}],"roleHeading":"Instance Method","title":"shadowColor()","modules":[{"name":"Airwallex"}]},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","abstract":[],"type":"topic","kind":"symbol","title":"Airwallex","role":"collection"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXTheme":{"abstract":[{"code":"AWXTheme","type":"codeVoice"},{"text":" manages text styles.","type":"text"}],"title":"AWXTheme","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme","navigatorTitle":[{"kind":"identifier","text":"AWXTheme"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXTheme"}],"kind":"symbol","url":"\/documentation\/airwallex\/awxtheme","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXTheme/shadowColor()":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shadowColor"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}],"title":"shadowColor()","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTheme\/shadowColor()","type":"topic","navigatorTitle":[{"kind":"identifier","text":"shadowColor"}],"abstract":[],"url":"\/documentation\/airwallex\/awxtheme\/shadowcolor()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"shadowColor","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"shadowColor"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"shadowColor"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTheme\/title","op":"replace","value":"AWXTheme"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTheme\/fragments","value":[{"kind":"identifier","text":"AWXTheme"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTheme\/navigatorTitle","value":[{"kind":"identifier","text":"AWXTheme"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTheme~1shadowColor()\/title","value":"shadowColor","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTheme~1shadowColor()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"shadowColor"}],"op":"replace"}]}]}