{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"navigatorTitle":[{"text":"AirwallexWeChatPayVersionString","kind":"identifier"}],"roleHeading":"Global Variable","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AirwallexWeChatPayVersionString","kind":"identifier"},{"text":": <<error type>>","kind":"text"}],"title":"AirwallexWeChatPayVersionString","externalID":"c:@AirwallexWeChatPayVersionString","symbolKind":"var","role":"symbol","modules":[{"name":"Airwallex"}]},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexWeChatPayVersionString","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"AirwallexWeChatPayVersionString"},{"kind":"text","text":": <<error type>>"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"]]},"abstract":[{"type":"text","text":"Project version string for WeChatPay."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/airwallexwechatpayversionstring"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/airwallexwechatpayversionstring"]}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","abstract":[],"role":"collection","url":"\/documentation\/airwallex","title":"Airwallex","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexWeChatPayVersionString":{"kind":"symbol","url":"\/documentation\/airwallex\/airwallexwechatpayversionstring","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexWeChatPayVersionString","abstract":[{"type":"text","text":"Project version string for WeChatPay."}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"AirwallexWeChatPayVersionString"},{"kind":"text","text":": <<error type>>"}],"title":"AirwallexWeChatPayVersionString","navigatorTitle":[{"kind":"identifier","text":"AirwallexWeChatPayVersionString"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"AirwallexWeChatPayVersionString"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"AirwallexWeChatPayVersionString","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"unsigned char","preciseIdentifier":"c:c"},{"kind":"text","text":" "},{"kind":"identifier","text":"AirwallexWeChatPayVersionString"},{"kind":"text","text":"[];"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexWeChatPayVersionString\/title","value":"AirwallexWeChatPayVersionString"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexWeChatPayVersionString\/fragments","value":[{"text":"AirwallexWeChatPayVersionString","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}