{"variants":[{"paths":["\/documentation\/airwallex\/airwallexsdkmode\/init(rawvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"role":"symbol","modules":[{"name":"Airwallex"}],"externalID":"s:So16AirwallexSDKModeV8rawValueABSgSi_tcfc","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"roleHeading":"Initializer","title":"init(rawValue:)"},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexSDKMode\/init(rawValue:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexSDKMode"]]},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/airwallex","title":"Airwallex","role":"collection"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexSDKMode/init(rawValue:)":{"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexSDKMode\/init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/airwallex\/airwallexsdkmode\/init(rawvalue:)","abstract":[],"title":"init(rawValue:)"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexSDKMode":{"kind":"symbol","navigatorTitle":[{"text":"AirwallexSDKMode","kind":"identifier"}],"url":"\/documentation\/airwallex\/airwallexsdkmode","title":"AirwallexSDKMode","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexSDKMode","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AirwallexSDKMode","kind":"identifier"}],"abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexSDKMode\/title","value":"AirwallexSDKMode","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexSDKMode\/fragments","value":[{"kind":"identifier","text":"AirwallexSDKMode"}]},{"value":[{"kind":"identifier","text":"AirwallexSDKMode"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexSDKMode\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}