{"sections":[],"metadata":{"roleHeading":"API Collection","title":"RawRepresentable Implementations","modules":[{"name":"Airwallex"}],"role":"collectionGroup"},"kind":"article","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexSDKMode"]]},"topicSections":[{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexSDKMode\/hashValue"],"generated":true},{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexSDKMode\/hash(into:)"],"generated":true}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexSDKMode\/RawRepresentable-Implementations"},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/airwallex\/airwallexsdkmode\/rawrepresentable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexSDKMode":{"navigatorTitle":[{"text":"AirwallexSDKMode","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexSDKMode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AirwallexSDKMode","kind":"identifier"}],"title":"AirwallexSDKMode","kind":"symbol","type":"topic","url":"\/documentation\/airwallex\/airwallexsdkmode","abstract":[],"role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"abstract":[],"type":"topic","url":"\/documentation\/airwallex","title":"Airwallex","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexSDKMode/hash(into:)":{"url":"\/documentation\/airwallex\/airwallexsdkmode\/hash(into:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexSDKMode\/hash(into:)","abstract":[],"title":"hash(into:)","conformance":{"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":".","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}]},"type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:s6HasherV","text":"Hasher","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexSDKMode/hashValue":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexSDKMode\/hashValue","type":"topic","title":"hashValue","url":"\/documentation\/airwallex\/airwallexsdkmode\/hashvalue","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"kind":"symbol","abstract":[],"conformance":{"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}]}}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"AirwallexSDKMode","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexSDKMode\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AirwallexSDKMode"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexSDKMode\/fragments"},{"op":"replace","value":[{"text":"AirwallexSDKMode","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexSDKMode\/navigatorTitle"}]}]}