{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"device"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDevice","text":"AWXDevice","preciseIdentifier":"c:objc(cs)AWXDevice"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}]}],"variants":[{"paths":["\/documentation\/airwallex\/awxconfirmpaymentintentrequest\/device"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxconfirmpaymentintentrequest\/device"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Device object."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentRequest\/device"},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"externalID":"c:objc(cs)AWXConfirmPaymentIntentRequest(py)device","title":"device","role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"text":"device","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"device"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWXDevice","preciseIdentifier":"c:objc(cs)AWXDevice"},{"kind":"text","text":"?"}],"symbolKind":"property","modules":[{"name":"Airwallex"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentRequest"]]},"sections":[],"kind":"symbol","references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXConfirmPaymentIntentRequest":{"type":"topic","abstract":[{"code":"AWXConfirmPaymentIntentRequest","type":"codeVoice"},{"type":"text","text":" includes all of the parameters needed to confirm payment intent."}],"title":"AWXConfirmPaymentIntentRequest","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentRequest","navigatorTitle":[{"kind":"identifier","text":"AWXConfirmPaymentIntentRequest"}],"url":"\/documentation\/airwallex\/awxconfirmpaymentintentrequest","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXConfirmPaymentIntentRequest"}],"kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXConfirmPaymentIntentRequest/device":{"type":"topic","abstract":[{"text":"Device object.","type":"text"}],"title":"device","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentIntentRequest\/device","navigatorTitle":[{"kind":"identifier","text":"device"}],"url":"\/documentation\/airwallex\/awxconfirmpaymentintentrequest\/device","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"device"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AWXDevice","kind":"typeIdentifier","text":"AWXDevice"},{"kind":"text","text":"?"}],"kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","role":"collection","title":"Airwallex","type":"topic","url":"\/documentation\/airwallex","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXDevice":{"type":"topic","navigatorTitle":[{"text":"AWXDevice","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxdevice","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDevice","title":"AWXDevice","abstract":[{"code":"AWXDevice","type":"codeVoice"},{"type":"text","text":" includes the information of device."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXDevice"}],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"device","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"device"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"AWXDevice","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDevice","preciseIdentifier":"c:objc(cs)AWXDevice"},{"kind":"text","text":" * "},{"kind":"identifier","text":"device"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"AWXConfirmPaymentIntentRequest","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentRequest\/title"},{"value":[{"kind":"identifier","text":"AWXConfirmPaymentIntentRequest"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentRequest\/fragments"},{"value":[{"kind":"identifier","text":"AWXConfirmPaymentIntentRequest"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentRequest\/navigatorTitle"},{"value":"device","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentRequest~1device\/title"},{"op":"replace","value":[{"kind":"identifier","text":"device"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentIntentRequest~1device\/fragments"},{"op":"replace","value":"AWXDevice","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDevice\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AWXDevice"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDevice\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AWXDevice"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDevice\/navigatorTitle"}]}]}