{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider"]]},"abstract":[{"text":"Create a new payment consent and confirm the payment intent with payment method.","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createPaymentConsentAndConfirmIntent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"paymentMethod","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod","preciseIdentifier":"c:objc(cs)AWXPaymentMethod","text":"AWXPaymentMethod","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The payment method info."}]}],"name":"paymentMethod"}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxdefaultprovider\/createpaymentconsentandconfirmintent(with:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxdefaultprovider\/createpaymentconsentandconfirmintent(with:)"]}],"metadata":{"externalID":"c:objc(cs)AWXDefaultProvider(im)createPaymentConsentAndConfirmIntentWithPaymentMethod:","modules":[{"name":"Airwallex"}],"title":"createPaymentConsentAndConfirmIntent(with:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createPaymentConsentAndConfirmIntent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AWXPaymentMethod","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPaymentMethod"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"text":"createPaymentConsentAndConfirmIntentWithPaymentMethod:","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider\/createPaymentConsentAndConfirmIntent(with:)"},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentMethod":{"type":"topic","role":"symbol","url":"\/documentation\/airwallex\/awxpaymentmethod","title":"AWXPaymentMethod","abstract":[{"code":"AWXPaymentMethod","type":"codeVoice"},{"type":"text","text":" includes the information of a payment method."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentMethod"}],"navigatorTitle":[{"kind":"identifier","text":"AWXPaymentMethod"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXDefaultProvider":{"role":"symbol","type":"topic","title":"AWXDefaultProvider","url":"\/documentation\/airwallex\/awxdefaultprovider","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXDefaultProvider","kind":"identifier"}],"navigatorTitle":[{"text":"AWXDefaultProvider","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider","abstract":[{"text":"A provider which handles payment business.","type":"text"}],"kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXDefaultProvider/createPaymentConsentAndConfirmIntent(with:)":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider\/createPaymentConsentAndConfirmIntent(with:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createPaymentConsentAndConfirmIntent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AWXPaymentMethod","text":"AWXPaymentMethod","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"createPaymentConsentAndConfirmIntentWithPaymentMethod:","kind":"identifier"}],"title":"createPaymentConsentAndConfirmIntent(with:)","url":"\/documentation\/airwallex\/awxdefaultprovider\/createpaymentconsentandconfirmintent(with:)","type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Create a new payment consent and confirm the payment intent with payment method."}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","abstract":[],"role":"collection","url":"\/documentation\/airwallex","title":"Airwallex","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"createPaymentConsentAndConfirmIntentWithPaymentMethod:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"createPaymentConsentAndConfirmIntentWithPaymentMethod:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"createPaymentConsentAndConfirmIntentWithPaymentMethod:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod","preciseIdentifier":"c:objc(cs)AWXPaymentMethod","text":"AWXPaymentMethod","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"paymentMethod","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The payment method info."}]}],"name":"paymentMethod"}],"kind":"parameters"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethod\/title","value":"AWXPaymentMethod"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethod\/fragments","value":[{"kind":"identifier","text":"AWXPaymentMethod"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethod\/navigatorTitle","value":[{"kind":"identifier","text":"AWXPaymentMethod"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider\/title","value":"AWXDefaultProvider"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider\/fragments","value":[{"text":"AWXDefaultProvider","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider\/navigatorTitle","value":[{"text":"AWXDefaultProvider","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider~1createPaymentConsentAndConfirmIntent(with:)\/title","value":"createPaymentConsentAndConfirmIntentWithPaymentMethod:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider~1createPaymentConsentAndConfirmIntent(with:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"createPaymentConsentAndConfirmIntentWithPaymentMethod:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}