{"metadata":{"symbolKind":"method","navigatorTitle":[{"text":"createPaymentConsentAndConfirmIntentWithPaymentMethod:completion:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createPaymentConsentAndConfirmIntent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AWXPaymentMethod","kind":"typeIdentifier","text":"AWXPaymentMethod"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"preciseIdentifier":"c:objc(cs)AWXResponse","kind":"typeIdentifier","text":"AWXResponse"},{"kind":"text","text":"?, (any "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":")?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"modules":[{"name":"Airwallex"}],"role":"symbol","externalID":"c:objc(cs)AWXDefaultProvider(im)createPaymentConsentAndConfirmIntentWithPaymentMethod:completion:","roleHeading":"Instance Method","title":"createPaymentConsentAndConfirmIntent(with:completion:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider\/createPaymentConsentAndConfirmIntent(with:completion:)"},"abstract":[{"text":"Create a new payment consent and confirm the payment intent with payment method as well as a custom completion block.","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","variants":[{"paths":["\/documentation\/airwallex\/awxdefaultprovider\/createpaymentconsentandconfirmintent(with:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxdefaultprovider\/createpaymentconsentandconfirmintent(with:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createPaymentConsentAndConfirmIntent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"paymentMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod","preciseIdentifier":"c:objc(cs)AWXPaymentMethod","text":"AWXPaymentMethod"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping "},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXResponse","preciseIdentifier":"c:objc(cs)AWXResponse","text":"AWXResponse"},{"kind":"text","text":"?, (any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]},{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createPaymentConsentAndConfirmIntent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"paymentMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod","preciseIdentifier":"c:objc(cs)AWXPaymentMethod","text":"AWXPaymentMethod"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"AWXResponse","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXResponse","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXResponse"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"paymentMethod","content":[{"inlineContent":[{"text":"The payment method info.","type":"text"}],"type":"paragraph"}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"text":"The completion block to be called with the response and error.","type":"text"}]}]}],"kind":"parameters"}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","abstract":[],"role":"collection","url":"\/documentation\/airwallex","title":"Airwallex","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentMethod":{"type":"topic","role":"symbol","url":"\/documentation\/airwallex\/awxpaymentmethod","title":"AWXPaymentMethod","abstract":[{"code":"AWXPaymentMethod","type":"codeVoice"},{"type":"text","text":" includes the information of a payment method."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentMethod"}],"navigatorTitle":[{"kind":"identifier","text":"AWXPaymentMethod"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXDefaultProvider/createPaymentConsentAndConfirmIntent(with:completion:)":{"abstract":[{"text":"Create a new payment consent and confirm the payment intent with payment method as well as a custom completion block.","type":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider\/createPaymentConsentAndConfirmIntent(with:completion:)","navigatorTitle":[{"kind":"identifier","text":"createPaymentConsentAndConfirmIntentWithPaymentMethod:completion:"}],"kind":"symbol","url":"\/documentation\/airwallex\/awxdefaultprovider\/createpaymentconsentandconfirmintent(with:completion:)","title":"createPaymentConsentAndConfirmIntent(with:completion:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createPaymentConsentAndConfirmIntent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AWXPaymentMethod","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPaymentMethod"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:objc(cs)AWXResponse","text":"AWXResponse","kind":"typeIdentifier"},{"text":"?, (any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRequestHandler":{"navigatorTitle":[{"text":"AWXRequestHandler","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRequestHandler","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXRequestHandler","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxrequesthandler","type":"topic","kind":"symbol","role":"symbol","title":"AWXRequestHandler"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXDefaultProvider":{"role":"symbol","type":"topic","title":"AWXDefaultProvider","url":"\/documentation\/airwallex\/awxdefaultprovider","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXDefaultProvider","kind":"identifier"}],"navigatorTitle":[{"text":"AWXDefaultProvider","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider","abstract":[{"text":"A provider which handles payment business.","type":"text"}],"kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXResponse":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXResponse","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXResponse","title":"AWXResponse","navigatorTitle":[{"text":"AWXResponse","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/airwallex\/awxresponse","type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"createPaymentConsentAndConfirmIntentWithPaymentMethod:completion:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createPaymentConsentAndConfirmIntentWithPaymentMethod:completion:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"createPaymentConsentAndConfirmIntentWithPaymentMethod:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)AWXPaymentMethod","kind":"typeIdentifier","text":"AWXPaymentMethod","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"paymentMethod"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:AWXAPIClient.h@T@AWXRequestHandler","kind":"typeIdentifier","text":"AWXRequestHandler","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRequestHandler"},{"kind":"text","text":") "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The payment method info."}]}],"name":"paymentMethod"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The completion block to be called with the response and error.","type":"text"}]}],"name":"completion"}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"AWXPaymentMethod","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethod\/title"},{"value":[{"kind":"identifier","text":"AWXPaymentMethod"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethod\/fragments"},{"value":[{"text":"AWXPaymentMethod","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethod\/navigatorTitle"},{"value":"createPaymentConsentAndConfirmIntentWithPaymentMethod:completion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider~1createPaymentConsentAndConfirmIntent(with:completion:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"createPaymentConsentAndConfirmIntentWithPaymentMethod:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider~1createPaymentConsentAndConfirmIntent(with:completion:)\/fragments"},{"value":"AWXRequestHandler","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRequestHandler\/title"},{"value":[{"text":"AWXRequestHandler","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRequestHandler\/fragments"},{"value":[{"text":"AWXRequestHandler","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRequestHandler\/navigatorTitle"},{"value":"AWXDefaultProvider","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider\/title"},{"value":[{"kind":"identifier","text":"AWXDefaultProvider"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider\/fragments"},{"value":[{"text":"AWXDefaultProvider","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider\/navigatorTitle"},{"value":"AWXResponse","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXResponse\/title"},{"value":[{"text":"AWXResponse","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXResponse\/fragments"},{"value":[{"kind":"identifier","text":"AWXResponse"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXResponse\/navigatorTitle"}]}]}