{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider"]]},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider\/init(delegate:session:paymentMethodType:)","interfaceLanguage":"swift"},"metadata":{"externalID":"c:objc(cs)AWXDefaultProvider(im)initWithDelegate:session:paymentMethodType:","modules":[{"name":"Airwallex"}],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"AWXProviderDelegate","preciseIdentifier":"c:objc(pl)AWXProviderDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"session"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWXSession","preciseIdentifier":"c:objc(cs)AWXSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"paymentMethodType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWXPaymentMethodType","preciseIdentifier":"c:objc(cs)AWXPaymentMethodType"},{"kind":"text","text":"?)"}],"title":"init(delegate:session:paymentMethodType:)","navigatorTitle":[{"text":"initWithDelegate:session:paymentMethodType:","kind":"identifier"}],"roleHeading":"Initializer","symbolKind":"init"},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","text":"AWXProviderDelegate","preciseIdentifier":"c:objc(pl)AWXProviderDelegate","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXProviderDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"session"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWXSession","preciseIdentifier":"c:objc(cs)AWXSession","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"paymentMethodType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWXPaymentMethodType","preciseIdentifier":"c:objc(cs)AWXPaymentMethodType","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethodType"},{"kind":"text","text":"?)"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxdefaultprovider\/init(delegate:session:paymentmethodtype:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxdefaultprovider\/init(delegate:session:paymentmethodtype:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentMethodType":{"title":"AWXPaymentMethodType","navigatorTitle":[{"text":"AWXPaymentMethodType","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","abstract":[{"code":"AWXPaymentMethodType","type":"codeVoice"},{"text":" includes the information of a payment method.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethodType","url":"\/documentation\/airwallex\/awxpaymentmethodtype","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPaymentMethodType","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSession":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXSession"}],"navigatorTitle":[{"kind":"identifier","text":"AWXSession"}],"role":"symbol","abstract":[{"code":"AWXSession","type":"codeVoice"},{"type":"text","text":" is the base session."}],"title":"AWXSession","kind":"symbol","type":"topic","url":"\/documentation\/airwallex\/awxsession","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","role":"collection","url":"\/documentation\/airwallex","kind":"symbol","title":"Airwallex","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXDefaultProvider":{"abstract":[{"type":"text","text":"A provider which handles payment business."}],"type":"topic","navigatorTitle":[{"text":"AWXDefaultProvider","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxdefaultprovider","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXDefaultProvider","kind":"identifier"}],"title":"AWXDefaultProvider","role":"symbol","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXDefaultProvider/init(delegate:session:paymentMethodType:)":{"title":"init(delegate:session:paymentMethodType:)","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider\/init(delegate:session:paymentMethodType:)","abstract":[],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/airwallex\/awxdefaultprovider\/init(delegate:session:paymentmethodtype:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)AWXProviderDelegate","text":"AWXProviderDelegate","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"session","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AWXSession","text":"AWXSession","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"paymentMethodType","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AWXPaymentMethodType","text":"AWXPaymentMethodType","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithDelegate:session:paymentMethodType:"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXProviderDelegate":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXProviderDelegate","role":"symbol","kind":"symbol","url":"\/documentation\/airwallex\/awxproviderdelegate","abstract":[{"text":"A delegate which handles checkout results.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXProviderDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"AWXProviderDelegate"}],"type":"topic","title":"AWXProviderDelegate"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"initWithDelegate:session:paymentMethodType:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithDelegate:session:paymentMethodType:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithDelegate:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<AWXProviderDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)AWXProviderDelegate"},{"text":") ","kind":"text"},{"text":"delegate","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"session:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)AWXSession","text":"AWXSession","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"session","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"paymentMethodType:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)AWXPaymentMethodType","text":"AWXPaymentMethodType","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethodType","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"paymentMethodType","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"AWXPaymentMethodType","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethodType\/title"},{"op":"replace","value":[{"text":"AWXPaymentMethodType","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethodType\/fragments"},{"op":"replace","value":[{"text":"AWXPaymentMethodType","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethodType\/navigatorTitle"},{"op":"replace","value":"AWXSession","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/title"},{"op":"replace","value":[{"text":"AWXSession","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AWXSession"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/navigatorTitle"},{"op":"replace","value":"AWXDefaultProvider","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AWXDefaultProvider"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider\/fragments"},{"op":"replace","value":[{"text":"AWXDefaultProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider\/navigatorTitle"},{"op":"replace","value":"initWithDelegate:session:paymentMethodType:","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider~1init(delegate:session:paymentMethodType:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDelegate:session:paymentMethodType:"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider~1init(delegate:session:paymentMethodType:)\/fragments"},{"op":"replace","value":"AWXProviderDelegate","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXProviderDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AWXProviderDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXProviderDelegate\/fragments"},{"op":"replace","value":[{"text":"AWXProviderDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXProviderDelegate\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}