{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enableTapToDismiss","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Enable user to tap the view to dismiss view controller."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXViewController\/enableTapToDismiss()"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXViewController"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxviewcontroller\/enabletaptodismiss()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxviewcontroller\/enabletaptodismiss()"]}],"metadata":{"title":"enableTapToDismiss()","externalID":"c:objc(cs)AWXViewController(im)enableTapToDismiss","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enableTapToDismiss","kind":"identifier"},{"text":"()","kind":"text"}],"modules":[{"name":"Airwallex"}],"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"enableTapToDismiss"}],"symbolKind":"method"},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXViewController":{"kind":"symbol","abstract":[{"type":"codeVoice","code":"AWXViewController"},{"type":"text","text":" is the base view controller."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXViewController"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXViewController","navigatorTitle":[{"kind":"identifier","text":"AWXViewController"}],"title":"AWXViewController","url":"\/documentation\/airwallex\/awxviewcontroller","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","url":"\/documentation\/airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","kind":"symbol","role":"collection","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXViewController/enableTapToDismiss()":{"url":"\/documentation\/airwallex\/awxviewcontroller\/enabletaptodismiss()","type":"topic","kind":"symbol","title":"enableTapToDismiss()","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXViewController\/enableTapToDismiss()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableTapToDismiss"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"enableTapToDismiss"}],"abstract":[{"type":"text","text":"Enable user to tap the view to dismiss view controller."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"enableTapToDismiss"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enableTapToDismiss"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"enableTapToDismiss","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXViewController\/title","value":"AWXViewController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXViewController\/fragments","value":[{"kind":"identifier","text":"AWXViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXViewController\/navigatorTitle","value":[{"kind":"identifier","text":"AWXViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXViewController~1enableTapToDismiss()\/title","value":"enableTapToDismiss"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXViewController~1enableTapToDismiss()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enableTapToDismiss"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}