{"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentAttempt\/id","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentAttempt"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Attempt id.","type":"text"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxpaymentattempt\/id"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxpaymentattempt\/id"]}],"metadata":{"roleHeading":"Instance Property","role":"symbol","title":"id","externalID":"c:objc(cs)AWXPaymentAttempt(py)Id","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"modules":[{"name":"Airwallex"}],"navigatorTitle":[{"text":"Id","kind":"identifier"}],"symbolKind":"property"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","title":"Airwallex","abstract":[],"type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentAttempt":{"role":"symbol","title":"AWXPaymentAttempt","abstract":[{"code":"AWXPaymentAttempt","type":"codeVoice"},{"text":" includes the information of payment attempt.","type":"text"}],"url":"\/documentation\/airwallex\/awxpaymentattempt","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPaymentAttempt","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentAttempt","type":"topic","navigatorTitle":[{"text":"AWXPaymentAttempt","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentAttempt/id":{"type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"url":"\/documentation\/airwallex\/awxpaymentattempt\/id","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentAttempt\/id","navigatorTitle":[{"text":"Id","kind":"identifier"}],"abstract":[{"type":"text","text":"Attempt id."}],"kind":"symbol","title":"id"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"Id"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"Id","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"Id"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentAttempt\/title","value":"AWXPaymentAttempt"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentAttempt\/fragments","value":[{"text":"AWXPaymentAttempt","kind":"identifier"}]},{"op":"replace","value":[{"text":"AWXPaymentAttempt","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentAttempt\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentAttempt~1id\/title","value":"Id"},{"op":"replace","value":[{"kind":"identifier","text":"Id"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentAttempt~1id\/fragments"}]}]}