{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXVerifyPaymentConsentResponse"]]},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXVerifyPaymentConsentResponse\/nextAction","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"Airwallex"}],"role":"symbol","title":"nextAction","symbolKind":"property","externalID":"c:objc(cs)AWXVerifyPaymentConsentResponse(py)nextAction","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nextAction","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AWXConfirmPaymentNextAction","text":"AWXConfirmPaymentNextAction","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"nextAction"}],"roleHeading":"Instance Property"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextAction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWXConfirmPaymentNextAction","preciseIdentifier":"c:objc(cs)AWXConfirmPaymentNextAction","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentNextAction"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxverifypaymentconsentresponse\/nextaction"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxverifypaymentconsentresponse\/nextaction"]}],"kind":"symbol","sections":[],"abstract":[{"text":"Next action.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","kind":"symbol","url":"\/documentation\/airwallex","abstract":[],"title":"Airwallex","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXVerifyPaymentConsentResponse":{"abstract":[{"code":"AWXVerifyPaymentConsentResponse","type":"codeVoice"},{"text":" includes the response of payment consent.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXVerifyPaymentConsentResponse"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWXVerifyPaymentConsentResponse"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXVerifyPaymentConsentResponse","url":"\/documentation\/airwallex\/awxverifypaymentconsentresponse","type":"topic","title":"AWXVerifyPaymentConsentResponse"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXVerifyPaymentConsentResponse/nextAction":{"url":"\/documentation\/airwallex\/awxverifypaymentconsentresponse\/nextaction","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXVerifyPaymentConsentResponse\/nextAction","abstract":[{"type":"text","text":"Next action."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nextAction","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWXConfirmPaymentNextAction","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXConfirmPaymentNextAction"},{"text":"?","kind":"text"}],"title":"nextAction","navigatorTitle":[{"text":"nextAction","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXConfirmPaymentNextAction":{"type":"topic","url":"\/documentation\/airwallex\/awxconfirmpaymentnextaction","title":"AWXConfirmPaymentNextAction","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXConfirmPaymentNextAction"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWXConfirmPaymentNextAction"}],"abstract":[{"type":"codeVoice","code":"AWXConfirmPaymentNextAction"},{"type":"text","text":" includes the parameters for next action."}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentNextAction","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"nextAction"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"nextAction"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXConfirmPaymentNextAction","preciseIdentifier":"c:objc(cs)AWXConfirmPaymentNextAction","text":"AWXConfirmPaymentNextAction"},{"kind":"text","text":" * "},{"kind":"identifier","text":"nextAction"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXVerifyPaymentConsentResponse\/title","value":"AWXVerifyPaymentConsentResponse"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXVerifyPaymentConsentResponse\/fragments","value":[{"text":"AWXVerifyPaymentConsentResponse","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXVerifyPaymentConsentResponse\/navigatorTitle","value":[{"text":"AWXVerifyPaymentConsentResponse","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXVerifyPaymentConsentResponse~1nextAction\/title","value":"nextAction"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXVerifyPaymentConsentResponse~1nextAction\/fragments","value":[{"text":"nextAction","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentNextAction\/title","value":"AWXConfirmPaymentNextAction"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentNextAction\/fragments","value":[{"kind":"identifier","text":"AWXConfirmPaymentNextAction"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXConfirmPaymentNextAction\/navigatorTitle","value":[{"text":"AWXConfirmPaymentNextAction","kind":"identifier"}]}]}]}