{"kind":"symbol","abstract":[{"type":"text","text":"The payment intent to handle."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentIntent","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent","preciseIdentifier":"c:objc(cs)AWXPaymentIntent","text":"AWXPaymentIntent","kind":"typeIdentifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session"]]},"metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentIntent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPaymentIntent","text":"AWXPaymentIntent"}],"externalID":"c:@M@Airwallex@objc(cs)Session(py)paymentIntent","navigatorTitle":[{"kind":"identifier","text":"paymentIntent"}],"roleHeading":"Instance Property","role":"symbol","modules":[{"name":"Airwallex"}],"symbolKind":"property","title":"paymentIntent"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session\/paymentIntent"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/session\/paymentintent"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/session\/paymentintent"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentIntent":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent","navigatorTitle":[{"text":"AWXPaymentIntent","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"codeVoice","code":"AWXPaymentIntent"},{"type":"text","text":" includes the information of payment intent."}],"title":"AWXPaymentIntent","url":"\/documentation\/airwallex\/awxpaymentintent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentIntent"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/airwallex","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/Session/paymentIntent":{"title":"paymentIntent","type":"topic","url":"\/documentation\/airwallex\/session\/paymentintent","abstract":[{"type":"text","text":"The payment intent to handle."}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentIntent"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AWXPaymentIntent","kind":"typeIdentifier","text":"AWXPaymentIntent"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"paymentIntent"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session\/paymentIntent","role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/Session":{"navigatorTitle":[{"text":"Session","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Session"}],"title":"Session","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/Session","type":"topic","url":"\/documentation\/airwallex\/session","abstract":[{"type":"codeVoice","code":"Session"},{"type":"text","text":" is a specialized subclass of "},{"type":"codeVoice","code":"AWXSession"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"paymentIntent"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"paymentIntent"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPaymentIntent","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent","text":"AWXPaymentIntent"},{"kind":"text","text":" * "},{"kind":"identifier","text":"paymentIntent"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"AWXPaymentIntent","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentIntent\/title"},{"value":[{"text":"AWXPaymentIntent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentIntent\/fragments"},{"value":[{"kind":"identifier","text":"AWXPaymentIntent"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentIntent\/navigatorTitle"},{"value":"paymentIntent","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session~1paymentIntent\/title"},{"value":[{"kind":"identifier","text":"paymentIntent"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session~1paymentIntent\/fragments"},{"value":"Session","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session\/title"},{"value":[{"text":"Session","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session\/fragments"},{"value":[{"text":"Session","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1Session\/navigatorTitle"}]}]}