{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/Configuration","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/Configuration\/Appearance-swift.class"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/Configuration\/Appearance-swift.class\/tintColor"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tintColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"inlineContent":[{"type":"text","text":"Defaults to the SDK’s built-in theme color."}],"type":"paragraph"}],"kind":"content"}],"metadata":{"externalID":"s:9Airwallex17AWXPaymentElementC13ConfigurationC10AppearanceC9tintColorSo7UIColorCvp","modules":[{"name":"Airwallex"}],"title":"tintColor","role":"symbol","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tintColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}],"roleHeading":"Instance Property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxpaymentelement\/configuration\/appearance-swift.class\/tintcolor"]}],"kind":"symbol","abstract":[{"type":"text","text":"The primary brand color used throughout the payment element."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement":{"type":"topic","url":"\/documentation\/airwallex\/awxpaymentelement","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AWXPaymentElement","kind":"identifier"}],"navigatorTitle":[{"text":"AWXPaymentElement","kind":"identifier"}],"title":"AWXPaymentElement","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"An embeddable payment element that can be added to any view hierarchy."}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","url":"\/documentation\/airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","kind":"symbol","role":"collection","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement/Configuration":{"type":"topic","url":"\/documentation\/airwallex\/awxpaymentelement\/configuration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/Configuration","kind":"symbol","title":"AWXPaymentElement.Configuration","role":"symbol","abstract":[{"type":"text","text":"Configuration options for the embedded payment element."}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement/Configuration/Appearance-swift.class/tintColor":{"type":"topic","url":"\/documentation\/airwallex\/awxpaymentelement\/configuration\/appearance-swift.class\/tintcolor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tintColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}],"title":"tintColor","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/Configuration\/Appearance-swift.class\/tintColor","role":"symbol","abstract":[{"type":"text","text":"The primary brand color used throughout the payment element."}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement/Configuration/Appearance-swift.class":{"type":"topic","url":"\/documentation\/airwallex\/awxpaymentelement\/configuration\/appearance-swift.class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Appearance"}],"navigatorTitle":[{"kind":"identifier","text":"Appearance"}],"title":"AWXPaymentElement.Configuration.Appearance","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement\/Configuration\/Appearance-swift.class","role":"symbol","abstract":[{"type":"text","text":"Appearance configuration for customizing the visual style."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"AWXPaymentElement","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AWXPaymentElement"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AWXPaymentElement"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/navigatorTitle","op":"replace"}]}]}