{"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"metadata":{"symbolKind":"property","modules":[{"name":"Airwallex"}],"externalID":"c:objc(cs)AWXVerifyPaymentConsentRequest(py)consent","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"consent"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AWXPaymentConsent","kind":"typeIdentifier","text":"AWXPaymentConsent"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"consent"}],"roleHeading":"Instance Property","title":"consent"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXVerifyPaymentConsentRequest"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"consent","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWXPaymentConsent","preciseIdentifier":"c:objc(cs)AWXPaymentConsent","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentConsent"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxverifypaymentconsentrequest\/consent"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxverifypaymentconsentrequest\/consent"]}],"abstract":[{"type":"text","text":"Payment consent object."}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXVerifyPaymentConsentRequest\/consent","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentConsent":{"navigatorTitle":[{"text":"AWXPaymentConsent","kind":"identifier"}],"type":"topic","abstract":[{"type":"codeVoice","code":"AWXPaymentConsent"},{"type":"text","text":" includes the info of payment consent."}],"url":"\/documentation\/airwallex\/awxpaymentconsent","title":"AWXPaymentConsent","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPaymentConsent","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentConsent","role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXVerifyPaymentConsentRequest/consent":{"url":"\/documentation\/airwallex\/awxverifypaymentconsentrequest\/consent","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"consent","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWXPaymentConsent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPaymentConsent"},{"text":"?","kind":"text"}],"title":"consent","navigatorTitle":[{"text":"consent","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"Payment consent object.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXVerifyPaymentConsentRequest\/consent"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXVerifyPaymentConsentRequest":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXVerifyPaymentConsentRequest","url":"\/documentation\/airwallex\/awxverifypaymentconsentrequest","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXVerifyPaymentConsentRequest"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWXVerifyPaymentConsentRequest"}],"kind":"symbol","abstract":[{"code":"AWXVerifyPaymentConsentRequest","type":"codeVoice"},{"text":" includes the request of verifying payment consent.","type":"text"}],"type":"topic","title":"AWXVerifyPaymentConsentRequest"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol","type":"topic","url":"\/documentation\/airwallex","role":"collection","abstract":[],"title":"Airwallex"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"consent","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"consent"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"AWXPaymentConsent","preciseIdentifier":"c:objc(cs)AWXPaymentConsent","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentConsent"},{"text":" * ","kind":"text"},{"text":"consent","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentConsent\/title","value":"AWXPaymentConsent","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentConsent\/fragments","value":[{"kind":"identifier","text":"AWXPaymentConsent"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentConsent\/navigatorTitle","value":[{"kind":"identifier","text":"AWXPaymentConsent"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXVerifyPaymentConsentRequest~1consent\/title","value":"consent","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXVerifyPaymentConsentRequest~1consent\/fragments","value":[{"kind":"identifier","text":"consent"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXVerifyPaymentConsentRequest\/title","value":"AWXVerifyPaymentConsentRequest","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXVerifyPaymentConsentRequest\/fragments","value":[{"text":"AWXVerifyPaymentConsentRequest","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXVerifyPaymentConsentRequest\/navigatorTitle","value":[{"text":"AWXVerifyPaymentConsentRequest","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}