{"abstract":[{"type":"text","text":"Payment method object."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"options"},{"text":": ","kind":"text"},{"text":"AWXPaymentMethod","preciseIdentifier":"c:objc(cs)AWXPaymentMethod","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXVerifyPaymentConsentRequest\/options","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxverifypaymentconsentrequest\/options"]},{"paths":["\/documentation\/airwallex\/awxverifypaymentconsentrequest\/options"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXVerifyPaymentConsentRequest"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"roleHeading":"Instance Property","symbolKind":"property","title":"options","externalID":"c:objc(cs)AWXVerifyPaymentConsentRequest(py)options","navigatorTitle":[{"text":"options","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"options","kind":"identifier"},{"kind":"text","text":": "},{"text":"AWXPaymentMethod","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPaymentMethod"},{"text":"?","kind":"text"}],"modules":[{"name":"Airwallex"}],"role":"symbol"},"kind":"symbol","references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXVerifyPaymentConsentRequest/options":{"role":"symbol","navigatorTitle":[{"text":"options","kind":"identifier"}],"title":"options","abstract":[{"type":"text","text":"Payment method object."}],"url":"\/documentation\/airwallex\/awxverifypaymentconsentrequest\/options","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"options","kind":"identifier"},{"kind":"text","text":": "},{"text":"AWXPaymentMethod","preciseIdentifier":"c:objc(cs)AWXPaymentMethod","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXVerifyPaymentConsentRequest\/options","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/airwallex","title":"Airwallex","role":"collection"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXVerifyPaymentConsentRequest":{"navigatorTitle":[{"text":"AWXVerifyPaymentConsentRequest","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXVerifyPaymentConsentRequest","kind":"symbol","abstract":[{"type":"codeVoice","code":"AWXVerifyPaymentConsentRequest"},{"text":" includes the request of verifying payment consent.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXVerifyPaymentConsentRequest"}],"role":"symbol","url":"\/documentation\/airwallex\/awxverifypaymentconsentrequest","title":"AWXVerifyPaymentConsentRequest"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentMethod":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AWXPaymentMethod","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWXPaymentMethod"}],"url":"\/documentation\/airwallex\/awxpaymentmethod","abstract":[{"code":"AWXPaymentMethod","type":"codeVoice"},{"type":"text","text":" includes the information of a payment method."}],"title":"AWXPaymentMethod","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"options","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"text":"options","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPaymentMethod","text":"AWXPaymentMethod","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethod"},{"text":" * ","kind":"text"},{"text":"options","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"options","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXVerifyPaymentConsentRequest~1options\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXVerifyPaymentConsentRequest~1options\/fragments","op":"replace","value":[{"text":"options","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXVerifyPaymentConsentRequest\/title","value":"AWXVerifyPaymentConsentRequest"},{"value":[{"text":"AWXVerifyPaymentConsentRequest","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXVerifyPaymentConsentRequest\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AWXVerifyPaymentConsentRequest"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXVerifyPaymentConsentRequest\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethod\/title","value":"AWXPaymentMethod"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethod\/fragments","op":"replace","value":[{"text":"AWXPaymentMethod","kind":"identifier"}]},{"value":[{"text":"AWXPaymentMethod","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethod\/navigatorTitle","op":"replace"}]}]}