{"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Apple Pay options.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applePayOptions","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWXApplePayOptions","preciseIdentifier":"c:objc(cs)AWXApplePayOptions","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"metadata":{"modules":[{"name":"Airwallex"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"applePayOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWXApplePayOptions","preciseIdentifier":"c:objc(cs)AWXApplePayOptions"},{"kind":"text","text":"?"}],"externalID":"c:objc(cs)AWXSession(py)applePayOptions","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"applePayOptions"}],"symbolKind":"property","title":"applePayOptions","role":"symbol"},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession\/applePayOptions","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxsession\/applepayoptions"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxsession\/applepayoptions"]}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSession":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXSession"}],"navigatorTitle":[{"text":"AWXSession","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxsession","type":"topic","title":"AWXSession","abstract":[{"code":"AWXSession","type":"codeVoice"},{"type":"text","text":" is the base session."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/airwallex","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXApplePayOptions":{"title":"AWXApplePayOptions","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXApplePayOptions","kind":"identifier"}],"navigatorTitle":[{"text":"AWXApplePayOptions","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Object used to construct PKPaymentRequest for Apple Pay."}],"type":"topic","url":"\/documentation\/airwallex\/awxapplepayoptions"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSession/applePayOptions":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applePayOptions","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWXApplePayOptions","preciseIdentifier":"c:objc(cs)AWXApplePayOptions","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","kind":"symbol","title":"applePayOptions","navigatorTitle":[{"text":"applePayOptions","kind":"identifier"}],"abstract":[{"text":"Apple Pay options.","type":"text"}],"url":"\/documentation\/airwallex\/awxsession\/applepayoptions","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession\/applePayOptions","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"applePayOptions","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"applePayOptions"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXApplePayOptions","preciseIdentifier":"c:objc(cs)AWXApplePayOptions","text":"AWXApplePayOptions"},{"kind":"text","text":" * "},{"kind":"identifier","text":"applePayOptions"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"AWXSession","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/title"},{"value":[{"kind":"identifier","text":"AWXSession"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/fragments"},{"value":[{"text":"AWXSession","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/navigatorTitle"},{"value":"AWXApplePayOptions","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions\/title"},{"value":[{"kind":"identifier","text":"AWXApplePayOptions"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions\/fragments"},{"value":[{"text":"AWXApplePayOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXApplePayOptions\/navigatorTitle"},{"value":"applePayOptions","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession~1applePayOptions\/title"},{"value":[{"kind":"identifier","text":"applePayOptions"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession~1applePayOptions\/fragments"}]}]}