{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession\/ValidationError\/recoverySuggestion"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recoverySuggestion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"kind":"symbol","metadata":{"role":"symbol","extendedModule":"Foundation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recoverySuggestion"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","modules":[{"relatedModules":["Foundation"],"name":"Airwallex"}],"title":"recoverySuggestion","symbolKind":"property","externalID":"s:10Foundation14LocalizedErrorPAAE18recoverySuggestionSSSgvp::SYNTHESIZED::s:So10AWXSessionC9AirwallexE15ValidationErrorO","platforms":[{"beta":false,"name":"iOS","introducedAt":"8.0","deprecated":false,"unavailable":false},{"beta":false,"name":"iPadOS","introducedAt":"8.0","deprecated":false,"unavailable":false},{"beta":false,"name":"Mac Catalyst","introducedAt":"8.0","deprecated":false,"unavailable":false},{"beta":false,"name":"macOS","introducedAt":"10.10","deprecated":false,"unavailable":false},{"beta":false,"name":"tvOS","introducedAt":"9.0","deprecated":false,"unavailable":false},{"beta":false,"name":"watchOS","introducedAt":"2.0","deprecated":false,"unavailable":false}]},"sections":[],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"LocalizedError.recoverySuggestion","type":"codeVoice"},{"text":".","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxsession\/validationerror\/recoverysuggestion"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession\/ValidationError"]]},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSession/ValidationError/recoverySuggestion":{"type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession\/ValidationError\/recoverySuggestion","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recoverySuggestion"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"role":"symbol","url":"\/documentation\/airwallex\/awxsession\/validationerror\/recoverysuggestion","kind":"symbol","title":"recoverySuggestion"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","abstract":[],"role":"collection","url":"\/documentation\/airwallex","title":"Airwallex","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSession":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXSession"}],"abstract":[{"code":"AWXSession","type":"codeVoice"},{"text":" is the base session.","type":"text"}],"kind":"symbol","url":"\/documentation\/airwallex\/awxsession","title":"AWXSession","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession","navigatorTitle":[{"kind":"identifier","text":"AWXSession"}],"role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSession/ValidationError":{"type":"topic","url":"\/documentation\/airwallex\/awxsession\/validationerror","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSession\/ValidationError","kind":"symbol","navigatorTitle":[{"text":"ValidationError","kind":"identifier"}],"role":"symbol","abstract":[],"title":"AWXSession.ValidationError","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ValidationError","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"AWXSession","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AWXSession"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/fragments","op":"replace"},{"value":[{"text":"AWXSession","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSession\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}