{"metadata":{"symbolKind":"case","modules":[{"name":"Airwallex"}],"title":"AWXTextFieldType.nameOnCard","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nameOnCard","kind":"identifier"}],"navigatorTitle":[{"text":"AWXTextFieldTypeNameOnCard","kind":"identifier"}],"externalID":"c:@E@AWXTextFieldType@AWXTextFieldTypeNameOnCard","roleHeading":"Case"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType"]]},"variants":[{"paths":["\/documentation\/airwallex\/awxtextfieldtype\/nameoncard"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxtextfieldtype\/nameoncard"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"nameOnCard"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/nameOnCard","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"abstract":[],"type":"topic","url":"\/documentation\/airwallex","title":"Airwallex","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXTextFieldType":{"abstract":[],"title":"AWXTextFieldType","url":"\/documentation\/airwallex\/awxtextfieldtype","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXTextFieldType","kind":"identifier"}],"navigatorTitle":[{"text":"AWXTextFieldType","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXTextFieldType/nameOnCard":{"abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"nameOnCard"}],"kind":"symbol","type":"topic","title":"AWXTextFieldType.nameOnCard","navigatorTitle":[{"kind":"identifier","text":"AWXTextFieldTypeNameOnCard"}],"url":"\/documentation\/airwallex\/awxtextfieldtype\/nameoncard","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/nameOnCard"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"AWXTextFieldTypeNameOnCard"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"AWXTextFieldTypeNameOnCard"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"AWXTextFieldTypeNameOnCard"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType\/title","op":"replace","value":"AWXTextFieldType"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType\/fragments","op":"replace","value":[{"text":"AWXTextFieldType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AWXTextFieldType"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType~1nameOnCard\/title","op":"replace","value":"AWXTextFieldTypeNameOnCard"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType~1nameOnCard\/fragments","op":"replace","value":[{"text":"AWXTextFieldTypeNameOnCard","kind":"identifier"}]}]}]}