{"metadata":{"externalID":"c:@E@AWXTextFieldType@AWXTextFieldTypePhoneNumber","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"phoneNumber","kind":"identifier"}],"modules":[{"name":"Airwallex"}],"navigatorTitle":[{"kind":"identifier","text":"AWXTextFieldTypePhoneNumber"}],"title":"AWXTextFieldType.phoneNumber","symbolKind":"case","role":"symbol"},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/phoneNumber","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"phoneNumber","kind":"identifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/airwallex\/awxtextfieldtype\/phonenumber"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxtextfieldtype\/phonenumber"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"kind":"symbol","abstract":[],"role":"collection","type":"topic","url":"\/documentation\/airwallex","title":"Airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXTextFieldType":{"url":"\/documentation\/airwallex\/awxtextfieldtype","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType","title":"AWXTextFieldType","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"AWXTextFieldType"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXTextFieldType"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXTextFieldType/phoneNumber":{"title":"AWXTextFieldType.phoneNumber","url":"\/documentation\/airwallex\/awxtextfieldtype\/phonenumber","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"phoneNumber","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/phoneNumber","navigatorTitle":[{"text":"AWXTextFieldTypePhoneNumber","kind":"identifier"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"AWXTextFieldTypePhoneNumber"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"AWXTextFieldTypePhoneNumber"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"AWXTextFieldTypePhoneNumber"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"AWXTextFieldType","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType\/title"},{"value":[{"text":"AWXTextFieldType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType\/fragments"},{"value":[{"text":"AWXTextFieldType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType\/navigatorTitle"},{"value":"AWXTextFieldTypePhoneNumber","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType~1phoneNumber\/title"},{"value":[{"text":"AWXTextFieldTypePhoneNumber","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType~1phoneNumber\/fragments"}]}]}