{"metadata":{"title":"AWXTextFieldType.CVC","role":"symbol","externalID":"c:@E@AWXTextFieldType@AWXTextFieldTypeCVC","symbolKind":"case","roleHeading":"Case","modules":[{"name":"Airwallex"}],"navigatorTitle":[{"text":"AWXTextFieldTypeCVC","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"CVC"}]},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/CVC","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CVC","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxtextfieldtype\/cvc"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxtextfieldtype\/cvc"]}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"title":"Airwallex","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/airwallex","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXTextFieldType/CVC":{"kind":"symbol","abstract":[],"url":"\/documentation\/airwallex\/awxtextfieldtype\/cvc","title":"AWXTextFieldType.CVC","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/CVC","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CVC"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWXTextFieldTypeCVC"}],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXTextFieldType":{"navigatorTitle":[{"text":"AWXTextFieldType","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXTextFieldType","kind":"identifier"}],"title":"AWXTextFieldType","type":"topic","abstract":[],"kind":"symbol","url":"\/documentation\/airwallex\/awxtextfieldtype","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"AWXTextFieldTypeCVC"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"AWXTextFieldTypeCVC"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"AWXTextFieldTypeCVC"}]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType~1CVC\/title","op":"replace","value":"AWXTextFieldTypeCVC"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType~1CVC\/fragments","op":"replace","value":[{"kind":"identifier","text":"AWXTextFieldTypeCVC"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType\/title","op":"replace","value":"AWXTextFieldType"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType\/fragments","op":"replace","value":[{"kind":"identifier","text":"AWXTextFieldType"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType\/navigatorTitle","op":"replace","value":[{"text":"AWXTextFieldType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}