{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"street","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","metadata":{"symbolKind":"case","title":"AWXTextFieldType.street","modules":[{"name":"Airwallex"}],"role":"symbol","navigatorTitle":[{"text":"AWXTextFieldTypeStreet","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"street","kind":"identifier"}],"roleHeading":"Case","externalID":"c:@E@AWXTextFieldType@AWXTextFieldTypeStreet"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxtextfieldtype\/street"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxtextfieldtype\/street"]}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/street","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType"]]},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXTextFieldType":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXTextFieldType","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"AWXTextFieldType","kind":"identifier"}],"abstract":[],"type":"topic","url":"\/documentation\/airwallex\/awxtextfieldtype","title":"AWXTextFieldType","role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXTextFieldType/street":{"url":"\/documentation\/airwallex\/awxtextfieldtype\/street","title":"AWXTextFieldType.street","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"AWXTextFieldTypeStreet","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"street","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXTextFieldType\/street","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","role":"collection","title":"Airwallex","url":"\/documentation\/airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AWXTextFieldTypeStreet"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"AWXTextFieldTypeStreet","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"AWXTextFieldTypeStreet"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType\/title","value":"AWXTextFieldType"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType\/fragments","value":[{"kind":"identifier","text":"AWXTextFieldType"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType\/navigatorTitle","value":[{"text":"AWXTextFieldType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType~1street\/title","value":"AWXTextFieldTypeStreet"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXTextFieldType~1street\/fragments","value":[{"text":"AWXTextFieldTypeStreet","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}