{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxcreatepaymentconsentrequest\/merchanttriggerreason"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxcreatepaymentconsentrequest\/merchanttriggerreason"]}],"abstract":[{"text":"Merchant trigger reason","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"navigatorTitle":[{"text":"merchantTriggerReason","kind":"identifier"}],"roleHeading":"Instance Property","externalID":"c:objc(cs)AWXCreatePaymentConsentRequest(py)merchantTriggerReason","title":"merchantTriggerReason","symbolKind":"property","modules":[{"name":"Airwallex"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"merchantTriggerReason","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AirwallexMerchantTriggerReason","kind":"typeIdentifier","preciseIdentifier":"c:@E@AirwallexMerchantTriggerReason"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"merchantTriggerReason","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexMerchantTriggerReason","text":"AirwallexMerchantTriggerReason","kind":"typeIdentifier","preciseIdentifier":"c:@E@AirwallexMerchantTriggerReason"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCreatePaymentConsentRequest"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCreatePaymentConsentRequest\/merchantTriggerReason"},"sections":[],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCreatePaymentConsentRequest":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"AWXCreatePaymentConsentRequest","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"AWXCreatePaymentConsentRequest"},{"text":" includes the request of creating payment consent.","type":"text"}],"url":"\/documentation\/airwallex\/awxcreatepaymentconsentrequest","title":"AWXCreatePaymentConsentRequest","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCreatePaymentConsentRequest","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXCreatePaymentConsentRequest","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCreatePaymentConsentRequest/merchantTriggerReason":{"type":"topic","navigatorTitle":[{"text":"merchantTriggerReason","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxcreatepaymentconsentrequest\/merchanttriggerreason","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"merchantTriggerReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@AirwallexMerchantTriggerReason","text":"AirwallexMerchantTriggerReason"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCreatePaymentConsentRequest\/merchantTriggerReason","title":"merchantTriggerReason","role":"symbol","kind":"symbol","abstract":[{"text":"Merchant trigger reason","type":"text"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexMerchantTriggerReason":{"url":"\/documentation\/airwallex\/airwallexmerchanttriggerreason","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"AirwallexMerchantTriggerReason","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AirwallexMerchantTriggerReason","kind":"identifier"}],"title":"AirwallexMerchantTriggerReason","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexMerchantTriggerReason","abstract":[],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","type":"topic","role":"collection","title":"Airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"merchantTriggerReason","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"merchantTriggerReason","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"text":") ","kind":"text"},{"text":"AirwallexMerchantTriggerReason","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexMerchantTriggerReason","kind":"typeIdentifier","preciseIdentifier":"c:@E@AirwallexMerchantTriggerReason"},{"text":" ","kind":"text"},{"text":"merchantTriggerReason","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"AWXCreatePaymentConsentRequest","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCreatePaymentConsentRequest\/title"},{"value":[{"text":"AWXCreatePaymentConsentRequest","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCreatePaymentConsentRequest\/fragments"},{"value":[{"text":"AWXCreatePaymentConsentRequest","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCreatePaymentConsentRequest\/navigatorTitle"},{"value":"merchantTriggerReason","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCreatePaymentConsentRequest~1merchantTriggerReason\/title"},{"value":[{"text":"merchantTriggerReason","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCreatePaymentConsentRequest~1merchantTriggerReason\/fragments"},{"value":"AirwallexMerchantTriggerReason","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexMerchantTriggerReason\/title"},{"value":[{"text":"AirwallexMerchantTriggerReason","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexMerchantTriggerReason\/fragments"},{"value":[{"kind":"identifier","text":"AirwallexMerchantTriggerReason"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexMerchantTriggerReason\/navigatorTitle"}]}]}