{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrandType\/unknown"},"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"externalID":"c:@E@AWXBrandType@AWXBrandTypeUnknown","modules":[{"name":"Airwallex"}],"role":"symbol","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"AWXBrandTypeUnknown"}],"title":"AWXBrandType.unknown","symbolKind":"case"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrandType"]]},"variants":[{"paths":["\/documentation\/airwallex\/awxbrandtype\/unknown"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxbrandtype\/unknown"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","role":"collection","title":"Airwallex","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXBrandType":{"abstract":[],"url":"\/documentation\/airwallex\/awxbrandtype","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXBrandType"}],"role":"symbol","title":"AWXBrandType","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrandType","navigatorTitle":[{"kind":"identifier","text":"AWXBrandType"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXBrandType/unknown":{"abstract":[],"title":"AWXBrandType.unknown","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXBrandType\/unknown","navigatorTitle":[{"text":"AWXBrandTypeUnknown","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/airwallex\/awxbrandtype\/unknown"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"AWXBrandTypeUnknown"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"AWXBrandTypeUnknown","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"AWXBrandTypeUnknown","kind":"identifier"}]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrandType\/title","op":"replace","value":"AWXBrandType"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrandType\/fragments","op":"replace","value":[{"kind":"identifier","text":"AWXBrandType"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrandType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AWXBrandType"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrandType~1unknown\/title","op":"replace","value":"AWXBrandTypeUnknown"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXBrandType~1unknown\/fragments","op":"replace","value":[{"text":"AWXBrandTypeUnknown","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}