{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentElement"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"element"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement","text":"AWXPaymentElement","preciseIdentifier":"c:@M@Airwallex@objc(cs)AWXPaymentElement"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didCompleteFor"},{"kind":"text","text":" "},{"kind":"internalParam","text":"paymentMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withPaymentConsentId"},{"kind":"text","text":" "},{"kind":"internalParam","text":"paymentConsentId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The payment element.","type":"text"}]}],"name":"element"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The name of the payment method used.","type":"text"}]}],"name":"paymentMethod"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The ID of the created payment consent.","type":"text"}]}],"name":"paymentConsentId"}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElementDelegate"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElementDelegate\/paymentElement(_:didCompleteFor:withPaymentConsentId:)"},"abstract":[{"text":"Called when a payment consent is created.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxpaymentelementdelegate\/paymentelement(_:didcompletefor:withpaymentconsentid:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxpaymentelementdelegate\/paymentelement(_:didcompletefor:withpaymentconsentid:)"]}],"metadata":{"externalID":"c:@M@Airwallex@objc(pl)AWXPaymentElementDelegate(im)paymentElement:didCompleteFor:withPaymentConsentId:","title":"paymentElement(_:didCompleteFor:withPaymentConsentId:)","navigatorTitle":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentElement:didCompleteFor:withPaymentConsentId:"}],"role":"symbol","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentElement"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AWXPaymentElement","preciseIdentifier":"c:@M@Airwallex@objc(cs)AWXPaymentElement"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didCompleteFor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withPaymentConsentId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","modules":[{"name":"Airwallex"}]},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElementDelegate/paymentElement(_:didCompleteFor:withPaymentConsentId:)":{"kind":"symbol","type":"topic","abstract":[{"text":"Called when a payment consent is created.","type":"text"}],"role":"symbol","url":"\/documentation\/airwallex\/awxpaymentelementdelegate\/paymentelement(_:didcompletefor:withpaymentconsentid:)","title":"paymentElement(_:didCompleteFor:withPaymentConsentId:)","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElementDelegate\/paymentElement(_:didCompleteFor:withPaymentConsentId:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentElement","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@Airwallex@objc(cs)AWXPaymentElement","text":"AWXPaymentElement","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didCompleteFor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"withPaymentConsentId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"- ","kind":"text"},{"text":"paymentElement:didCompleteFor:withPaymentConsentId:","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","url":"\/documentation\/airwallex","title":"Airwallex","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElement":{"role":"symbol","url":"\/documentation\/airwallex\/awxpaymentelement","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentElement"}],"type":"topic","kind":"symbol","title":"AWXPaymentElement","abstract":[{"type":"text","text":"An embeddable payment element that can be added to any view hierarchy."}],"navigatorTitle":[{"kind":"identifier","text":"AWXPaymentElement"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentElementDelegate":{"title":"AWXPaymentElementDelegate","type":"topic","role":"symbol","navigatorTitle":[{"text":"AWXPaymentElementDelegate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElementDelegate","url":"\/documentation\/airwallex\/awxpaymentelementdelegate","kind":"symbol","abstract":[{"text":"Delegate protocol for receiving payment events from AWXPaymentElement.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPaymentElementDelegate","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"paymentElement:didCompleteFor:withPaymentConsentId:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentElement:didCompleteFor:withPaymentConsentId:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"paymentElement:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentElement","preciseIdentifier":"c:@M@Airwallex@objc(cs)AWXPaymentElement","text":"AWXPaymentElement"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"element"},{"kind":"text","text":" "},{"kind":"identifier","text":"didCompleteFor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"paymentMethod"},{"kind":"text","text":" "},{"kind":"identifier","text":"withPaymentConsentId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"paymentConsentId"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The payment element.","type":"text"}]}],"name":"element"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The name of the payment method used.","type":"text"}]}],"name":"paymentMethod"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The ID of the created payment consent.","type":"text"}]}],"name":"paymentConsentId"}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElementDelegate~1paymentElement(_:didCompleteFor:withPaymentConsentId:)\/title","value":"paymentElement:didCompleteFor:withPaymentConsentId:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElementDelegate~1paymentElement(_:didCompleteFor:withPaymentConsentId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentElement:didCompleteFor:withPaymentConsentId:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/title","value":"AWXPaymentElement"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/fragments","value":[{"kind":"identifier","text":"AWXPaymentElement"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElement\/navigatorTitle","value":[{"kind":"identifier","text":"AWXPaymentElement"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElementDelegate\/title","value":"AWXPaymentElementDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElementDelegate\/fragments","value":[{"kind":"identifier","text":"AWXPaymentElementDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentElementDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"AWXPaymentElementDelegate"}]}]}]}