{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxcardprovider\/confirmpaymentintent(withpaymentconsentid:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxcardprovider\/confirmpaymentintent(withpaymentconsentid:)"]}],"metadata":{"externalID":"c:objc(cs)AWXCardProvider(im)confirmPaymentIntentWithPaymentConsentId:","role":"symbol","platforms":[{"deprecated":true,"beta":false,"unavailable":false,"message":"Will be removed in next major version release, use AirwallexPayment.CardProvider instead"}],"symbolKind":"method","title":"confirmPaymentIntent(withPaymentConsentId:)","navigatorTitle":[{"kind":"identifier","text":"confirmPaymentIntentWithPaymentConsentId:"}],"modules":[{"name":"Airwallex"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"confirmPaymentIntent","kind":"identifier"},{"kind":"text","text":"("},{"text":"withPaymentConsentId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}]},"abstract":[{"text":"Confirm the payment intent with payment consent ID.","type":"text"}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Will be removed in next major version release, use AirwallexPayment.CardProvider instead"}]}],"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardProvider\/confirmPaymentIntent(withPaymentConsentId:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"confirmPaymentIntent"},{"kind":"text","text":"("},{"text":"withPaymentConsentId","kind":"externalParam"},{"kind":"text","text":" "},{"text":"paymentConsentId","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"ID of the PaymentConsent."}],"type":"paragraph"}],"name":"paymentConsentId"}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardProvider"]]},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"abstract":[],"kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","url":"\/documentation\/airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardProvider/confirmPaymentIntent(withPaymentConsentId:)":{"url":"\/documentation\/airwallex\/awxcardprovider\/confirmpaymentintent(withpaymentconsentid:)","kind":"symbol","abstract":[{"type":"text","text":"Confirm the payment intent with payment consent ID."}],"type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confirmPaymentIntent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withPaymentConsentId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"confirmPaymentIntentWithPaymentConsentId:","kind":"identifier"}],"deprecated":true,"title":"confirmPaymentIntent(withPaymentConsentId:)","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardProvider\/confirmPaymentIntent(withPaymentConsentId:)"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardProvider":{"kind":"symbol","url":"\/documentation\/airwallex\/awxcardprovider","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AWXCardProvider"}],"deprecated":true,"title":"AWXCardProvider","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardProvider","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AWXCardProvider","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"AWXCardProvider"},{"type":"text","text":" is a provider to handle payment method with card."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":[{"deprecated":true,"beta":false,"unavailable":false}],"path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"confirmPaymentIntentWithPaymentConsentId:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"confirmPaymentIntentWithPaymentConsentId:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"confirmPaymentIntentWithPaymentConsentId:"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"paymentConsentId"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"paymentConsentId","content":[{"inlineContent":[{"text":"ID of the PaymentConsent.","type":"text"}],"type":"paragraph"}]}]}},{"path":"\/deprecationSummary","value":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Will be removed in next major version release, use AirwallexPayment.CardProvider instead"}]}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardProvider~1confirmPaymentIntent(withPaymentConsentId:)\/title","value":"confirmPaymentIntentWithPaymentConsentId:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardProvider~1confirmPaymentIntent(withPaymentConsentId:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"confirmPaymentIntentWithPaymentConsentId:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardProvider\/title","value":"AWXCardProvider"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardProvider\/fragments","value":[{"text":"AWXCardProvider","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardProvider\/navigatorTitle","value":[{"text":"AWXCardProvider","kind":"identifier"}]}]}]}