{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardOptions\/threeDs"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"threeDs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXThreeDs","text":"AWXThreeDs","preciseIdentifier":"c:objc(cs)AWXThreeDs"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"metadata":{"modules":[{"name":"Airwallex"}],"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"threeDs"}],"externalID":"c:objc(cs)AWXCardOptions(py)threeDs","title":"threeDs","symbolKind":"property","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"threeDs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXThreeDs","text":"AWXThreeDs"},{"kind":"text","text":"?"}]},"variants":[{"paths":["\/documentation\/airwallex\/awxcardoptions\/threeds"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxcardoptions\/threeds"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardOptions"]]},"abstract":[{"type":"text","text":"ThreeDs object."}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXThreeDs":{"navigatorTitle":[{"text":"AWXThreeDs","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxthreeds","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXThreeDs","title":"AWXThreeDs","type":"topic","abstract":[{"type":"codeVoice","code":"AWXThreeDs"},{"type":"text","text":" includes the information of 3ds."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXThreeDs","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","url":"\/documentation\/airwallex","role":"collection","kind":"symbol","abstract":[],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardOptions/threeDs":{"abstract":[{"type":"text","text":"ThreeDs object."}],"type":"topic","title":"threeDs","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardOptions\/threeDs","url":"\/documentation\/airwallex\/awxcardoptions\/threeds","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"threeDs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXThreeDs","text":"AWXThreeDs"},{"kind":"text","text":"?"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"threeDs"}],"role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCardOptions":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXCardOptions","kind":"identifier"}],"kind":"symbol","title":"AWXCardOptions","abstract":[{"type":"codeVoice","code":"AWXCardOptions"},{"type":"text","text":" includes the options of card."}],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCardOptions","navigatorTitle":[{"text":"AWXCardOptions","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxcardoptions"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"threeDs","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"threeDs","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"AWXThreeDs","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXThreeDs","preciseIdentifier":"c:objc(cs)AWXThreeDs"},{"text":" * ","kind":"text"},{"text":"threeDs","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"AWXThreeDs","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXThreeDs\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXThreeDs\/fragments","op":"replace","value":[{"kind":"identifier","text":"AWXThreeDs"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXThreeDs\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AWXThreeDs"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardOptions~1threeDs\/title","op":"replace","value":"threeDs"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardOptions~1threeDs\/fragments","op":"replace","value":[{"text":"threeDs","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardOptions\/title","op":"replace","value":"AWXCardOptions"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardOptions\/fragments","op":"replace","value":[{"text":"AWXCardOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCardOptions\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AWXCardOptions"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}