{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confirmPaymentIntent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"paymentMethodName","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"additionalInfo","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]?)","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRedirectActionProvider"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRedirectActionProvider\/confirmPaymentIntent(with:additionalInfo:)"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxredirectactionprovider\/confirmpaymentintent(with:additionalinfo:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxredirectactionprovider\/confirmpaymentintent(with:additionalinfo:)"]}],"metadata":{"externalID":"c:objc(cs)AWXRedirectActionProvider(im)confirmPaymentIntentWithPaymentMethodName:additionalInfo:","title":"confirmPaymentIntent(with:additionalInfo:)","navigatorTitle":[{"text":"- ","kind":"text"},{"text":"confirmPaymentIntentWithPaymentMethodName:additionalInfo:","kind":"identifier"}],"role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confirmPaymentIntent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"additionalInfo","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]?)","kind":"text"}],"roleHeading":"Instance Method","modules":[{"name":"Airwallex"}]},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"type":"topic","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","url":"\/documentation\/airwallex","title":"Airwallex","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRedirectActionProvider/confirmPaymentIntent(with:additionalInfo:)":{"kind":"symbol","type":"topic","abstract":[],"role":"symbol","url":"\/documentation\/airwallex\/awxredirectactionprovider\/confirmpaymentintent(with:additionalinfo:)","title":"confirmPaymentIntent(with:additionalInfo:)","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRedirectActionProvider\/confirmPaymentIntent(with:additionalInfo:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confirmPaymentIntent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"additionalInfo","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]?)","kind":"text"}],"navigatorTitle":[{"kind":"text","text":"- "},{"kind":"identifier","text":"confirmPaymentIntentWithPaymentMethodName:additionalInfo:"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRedirectActionProvider":{"kind":"symbol","type":"topic","abstract":[{"code":"AWXRedirectActionProvider","type":"codeVoice"},{"text":" handles Redirect flow.","type":"text"}],"role":"symbol","url":"\/documentation\/airwallex\/awxredirectactionprovider","title":"AWXRedirectActionProvider","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRedirectActionProvider","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXRedirectActionProvider","kind":"identifier"}],"navigatorTitle":[{"text":"AWXRedirectActionProvider","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"confirmPaymentIntentWithPaymentMethodName:additionalInfo:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"confirmPaymentIntentWithPaymentMethodName:additionalInfo:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"confirmPaymentIntentWithPaymentMethodName:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"paymentMethodName","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"additionalInfo:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSDictionary<NSString *,NSString *>","preciseIdentifier":"c:Q$objc(cs)NSDictionary","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"additionalInfo","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRedirectActionProvider~1confirmPaymentIntent(with:additionalInfo:)\/title","op":"replace","value":"confirmPaymentIntentWithPaymentMethodName:additionalInfo:"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRedirectActionProvider~1confirmPaymentIntent(with:additionalInfo:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"confirmPaymentIntentWithPaymentMethodName:additionalInfo:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRedirectActionProvider\/title","op":"replace","value":"AWXRedirectActionProvider"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRedirectActionProvider\/fragments","op":"replace","value":[{"text":"AWXRedirectActionProvider","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRedirectActionProvider\/navigatorTitle","op":"replace","value":[{"text":"AWXRedirectActionProvider","kind":"identifier"}]}]}]}