{"sections":[],"metadata":{"roleHeading":"Instance Property","externalID":"c:objc(cs)AWXFormMapping(py)forms","navigatorTitle":[{"text":"forms","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"forms","kind":"identifier"},{"text":": [","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"title":"forms","symbolKind":"property","role":"symbol","modules":[{"name":"Airwallex"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"forms","kind":"identifier"},{"text":": [","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"] { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXFormMapping\/forms","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","variants":[{"paths":["\/documentation\/airwallex\/awxformmapping\/forms"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxformmapping\/forms"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXFormMapping"]]},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXFormMapping/forms":{"type":"topic","abstract":[],"title":"forms","role":"symbol","navigatorTitle":[{"text":"forms","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXFormMapping\/forms","kind":"symbol","url":"\/documentation\/airwallex\/awxformmapping\/forms","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"forms","kind":"identifier"},{"text":": [","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXFormMapping":{"navigatorTitle":[{"text":"AWXFormMapping","kind":"identifier"}],"abstract":[],"url":"\/documentation\/airwallex\/awxformmapping","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXFormMapping","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"AWXFormMapping","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXFormMapping"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","type":"topic","url":"\/documentation\/airwallex","kind":"symbol","abstract":[],"title":"Airwallex"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"forms","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"forms","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray","preciseIdentifier":"c:objc(cs)NSArray","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"forms","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"forms","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXFormMapping~1forms\/title","op":"replace"},{"value":[{"text":"forms","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXFormMapping~1forms\/fragments","op":"replace"},{"value":"AWXFormMapping","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXFormMapping\/title","op":"replace"},{"value":[{"text":"AWXFormMapping","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXFormMapping\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AWXFormMapping"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXFormMapping\/navigatorTitle","op":"replace"}]}]}