{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"activeField"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}]}],"variants":[{"paths":["\/documentation\/airwallex\/awxviewcontroller\/activefield()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxviewcontroller\/activefield()"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Return the active field"}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXViewController\/activeField()","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"c:objc(cs)AWXViewController(im)activeField","title":"activeField()","role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"text":"- ","kind":"text"},{"text":"activeField","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"activeField"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"symbolKind":"method","modules":[{"name":"Airwallex"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXViewController"]]},"sections":[],"kind":"symbol","references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","role":"collection","title":"Airwallex","type":"topic","url":"\/documentation\/airwallex","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXViewController":{"type":"topic","abstract":[{"code":"AWXViewController","type":"codeVoice"},{"type":"text","text":" is the base view controller."}],"title":"AWXViewController","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXViewController","navigatorTitle":[{"text":"AWXViewController","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXViewController","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXViewController/activeField()":{"type":"topic","abstract":[{"type":"text","text":"Return the active field"}],"title":"activeField()","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXViewController\/activeField()","navigatorTitle":[{"kind":"text","text":"- "},{"kind":"identifier","text":"activeField"}],"url":"\/documentation\/airwallex\/awxviewcontroller\/activefield()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"activeField"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"activeField"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"activeField"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"activeField"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXViewController\/title","op":"replace","value":"AWXViewController"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"AWXViewController"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AWXViewController"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXViewController~1activeField()\/title","op":"replace","value":"activeField"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXViewController~1activeField()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"activeField"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}