{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXViewController"]]},"abstract":[{"text":"Unregister keyboard listener","type":"text"}],"variants":[{"paths":["\/documentation\/airwallex\/awxviewcontroller\/unregisterkeyboard()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxviewcontroller\/unregisterkeyboard()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXViewController\/unregisterKeyboard()"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unregisterKeyboard","kind":"identifier"},{"text":"()","kind":"text"}]}],"kind":"declarations"}],"sections":[],"metadata":{"navigatorTitle":[{"text":"unregisterKeyboard","kind":"identifier"}],"title":"unregisterKeyboard()","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unregisterKeyboard"},{"kind":"text","text":"()"}],"externalID":"c:objc(cs)AWXViewController(im)unregisterKeyboard","modules":[{"name":"Airwallex"}],"roleHeading":"Instance Method","role":"symbol"},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXViewController":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXViewController","kind":"identifier"}],"title":"AWXViewController","role":"symbol","navigatorTitle":[{"text":"AWXViewController","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXViewController","kind":"symbol","abstract":[{"code":"AWXViewController","type":"codeVoice"},{"type":"text","text":" is the base view controller."}],"url":"\/documentation\/airwallex\/awxviewcontroller"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXViewController/unregisterKeyboard()":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXViewController\/unregisterKeyboard()","abstract":[{"text":"Unregister keyboard listener","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"unregisterKeyboard"}],"role":"symbol","url":"\/documentation\/airwallex\/awxviewcontroller\/unregisterkeyboard()","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unregisterKeyboard"},{"kind":"text","text":"()"}],"title":"unregisterKeyboard()"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/airwallex","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"unregisterKeyboard","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"unregisterKeyboard","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"unregisterKeyboard","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"AWXViewController","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXViewController\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AWXViewController"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXViewController\/fragments","op":"replace"},{"value":[{"text":"AWXViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXViewController\/navigatorTitle","op":"replace"},{"value":"unregisterKeyboard","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXViewController~1unregisterKeyboard()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"unregisterKeyboard","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXViewController~1unregisterKeyboard()\/fragments","op":"replace"}]}]}