{"topicSections":[{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSDKErrorCode\/hashValue"],"title":"Instance Properties"},{"anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSDKErrorCode\/hash(into:)"],"title":"Instance Methods"}],"variants":[{"paths":["\/documentation\/airwallex\/awxsdkerrorcode\/rawrepresentable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"article","identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSDKErrorCode\/RawRepresentable-Implementations","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSDKErrorCode"]]},"sections":[],"metadata":{"modules":[{"name":"Airwallex"}],"roleHeading":"API Collection","role":"collectionGroup","title":"RawRepresentable Implementations"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","type":"topic","role":"collection","title":"Airwallex","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSDKErrorCode/hash(into:)":{"url":"\/documentation\/airwallex\/awxsdkerrorcode\/hash(into:)","title":"hash(into:)","abstract":[],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:s6HasherV","text":"Hasher","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSDKErrorCode\/hash(into:)","type":"topic","conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":".","type":"text"}]}},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSDKErrorCode":{"url":"\/documentation\/airwallex\/awxsdkerrorcode","title":"AWXSDKErrorCode","abstract":[],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXSDKErrorCode","kind":"identifier"}],"navigatorTitle":[{"text":"AWXSDKErrorCode","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSDKErrorCode","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXSDKErrorCode/hashValue":{"url":"\/documentation\/airwallex\/awxsdkerrorcode\/hashvalue","title":"hashValue","abstract":[],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXSDKErrorCode\/hashValue","type":"topic","conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":".","type":"text"}]}}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSDKErrorCode\/title","value":"AWXSDKErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSDKErrorCode\/fragments","value":[{"text":"AWXSDKErrorCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXSDKErrorCode\/navigatorTitle","value":[{"text":"AWXSDKErrorCode","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}