{"sections":[],"abstract":[{"type":"text","text":"Prepay id"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepayId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXWeChatPaySDKResponse"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxwechatpaysdkresponse\/prepayid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxwechatpaysdkresponse\/prepayid"]}],"metadata":{"externalID":"c:objc(cs)AWXWeChatPaySDKResponse(py)prepayId","title":"prepayId","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"prepayId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"modules":[{"name":"Airwallex"}],"navigatorTitle":[{"kind":"identifier","text":"prepayId"}],"roleHeading":"Instance Property","symbolKind":"property","role":"symbol"},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXWeChatPaySDKResponse\/prepayId","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXWeChatPaySDKResponse/prepayId":{"title":"prepayId","type":"topic","url":"\/documentation\/airwallex\/awxwechatpaysdkresponse\/prepayid","navigatorTitle":[{"kind":"identifier","text":"prepayId"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXWeChatPaySDKResponse\/prepayId","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepayId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"role":"symbol","abstract":[{"type":"text","text":"Prepay id"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXWeChatPaySDKResponse":{"navigatorTitle":[{"text":"AWXWeChatPaySDKResponse","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXWeChatPaySDKResponse","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxwechatpaysdkresponse","title":"AWXWeChatPaySDKResponse","abstract":[{"code":"AWXWeChatPaySDKResponse","type":"codeVoice"},{"text":" includes the parameters for WeChatSDK.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXWeChatPaySDKResponse"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","url":"\/documentation\/airwallex","role":"collection","kind":"symbol","abstract":[],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"prepayId","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"prepayId","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"prepayId"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXWeChatPaySDKResponse~1prepayId\/title","value":"prepayId","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXWeChatPaySDKResponse~1prepayId\/fragments","value":[{"text":"prepayId","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXWeChatPaySDKResponse\/title","value":"AWXWeChatPaySDKResponse","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXWeChatPaySDKResponse\/fragments","value":[{"kind":"identifier","text":"AWXWeChatPaySDKResponse"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXWeChatPaySDKResponse\/navigatorTitle","value":[{"kind":"identifier","text":"AWXWeChatPaySDKResponse"}],"op":"replace"}]}]}