{"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentMethodType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWXPaymentMethodType","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethodType","preciseIdentifier":"c:objc(cs)AWXPaymentMethodType","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/airwallex\/awxdefaultprovider\/paymentmethodtype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxdefaultprovider\/paymentmethodtype"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Original payment method response","type":"text"}],"metadata":{"navigatorTitle":[{"text":"paymentMethodType","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentMethodType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPaymentMethodType","text":"AWXPaymentMethodType"},{"kind":"text","text":"?"}],"externalID":"c:objc(cs)AWXDefaultProvider(py)paymentMethodType","role":"symbol","roleHeading":"Instance Property","symbolKind":"property","title":"paymentMethodType","modules":[{"name":"Airwallex"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider"]]},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider\/paymentMethodType","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXDefaultProvider/paymentMethodType":{"title":"paymentMethodType","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider\/paymentMethodType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentMethodType"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AWXPaymentMethodType","kind":"typeIdentifier","text":"AWXPaymentMethodType"},{"kind":"text","text":"?"}],"kind":"symbol","role":"symbol","url":"\/documentation\/airwallex\/awxdefaultprovider\/paymentmethodtype","navigatorTitle":[{"kind":"identifier","text":"paymentMethodType"}],"type":"topic","abstract":[{"text":"Original payment method response","type":"text"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXDefaultProvider":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXDefaultProvider"}],"navigatorTitle":[{"text":"AWXDefaultProvider","kind":"identifier"}],"type":"topic","url":"\/documentation\/airwallex\/awxdefaultprovider","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXDefaultProvider","title":"AWXDefaultProvider","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"A provider which handles payment business."}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","abstract":[],"title":"Airwallex","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentMethodType":{"role":"symbol","url":"\/documentation\/airwallex\/awxpaymentmethodtype","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPaymentMethodType","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"AWXPaymentMethodType"},{"type":"text","text":" includes the information of a payment method."}],"kind":"symbol","navigatorTitle":[{"text":"AWXPaymentMethodType","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethodType","type":"topic","title":"AWXPaymentMethodType"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"paymentMethodType","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"paymentMethodType","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentMethodType","kind":"typeIdentifier","text":"AWXPaymentMethodType","preciseIdentifier":"c:objc(cs)AWXPaymentMethodType"},{"kind":"text","text":" * "},{"kind":"identifier","text":"paymentMethodType"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"paymentMethodType","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider~1paymentMethodType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"paymentMethodType"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider~1paymentMethodType\/fragments"},{"op":"replace","value":"AWXDefaultProvider","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider\/title"},{"op":"replace","value":[{"text":"AWXDefaultProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider\/fragments"},{"op":"replace","value":[{"text":"AWXDefaultProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXDefaultProvider\/navigatorTitle"},{"op":"replace","value":"AWXPaymentMethodType","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethodType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AWXPaymentMethodType"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethodType\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AWXPaymentMethodType"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentMethodType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}