{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"Airwallex"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"consentId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"consentId","navigatorTitle":[{"kind":"identifier","text":"consentId"}],"role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AWXRetrievePaymentConsentRequest(py)consentId"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRetrievePaymentConsentRequest\/consentId"},"abstract":[{"text":"Consent ID.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxretrievepaymentconsentrequest\/consentid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxretrievepaymentconsentrequest\/consentid"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRetrievePaymentConsentRequest"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"consentId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRetrievePaymentConsentRequest":{"kind":"symbol","title":"AWXRetrievePaymentConsentRequest","abstract":[{"type":"codeVoice","code":"AWXRetrievePaymentConsentRequest"},{"type":"text","text":" includes the request of payment consent."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXRetrievePaymentConsentRequest"}],"navigatorTitle":[{"text":"AWXRetrievePaymentConsentRequest","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRetrievePaymentConsentRequest","url":"\/documentation\/airwallex\/awxretrievepaymentconsentrequest"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRetrievePaymentConsentRequest/consentId":{"navigatorTitle":[{"kind":"identifier","text":"consentId"}],"url":"\/documentation\/airwallex\/awxretrievepaymentconsentrequest\/consentid","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"consentId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRetrievePaymentConsentRequest\/consentId","abstract":[{"text":"Consent ID.","type":"text"}],"title":"consentId"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","abstract":[],"title":"Airwallex","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"consentId"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"consentId","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"consentId"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRetrievePaymentConsentRequest\/title","op":"replace","value":"AWXRetrievePaymentConsentRequest"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRetrievePaymentConsentRequest\/fragments","op":"replace","value":[{"text":"AWXRetrievePaymentConsentRequest","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRetrievePaymentConsentRequest\/navigatorTitle","op":"replace","value":[{"text":"AWXRetrievePaymentConsentRequest","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRetrievePaymentConsentRequest~1consentId\/title","op":"replace","value":"consentId"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRetrievePaymentConsentRequest~1consentId\/fragments","op":"replace","value":[{"kind":"identifier","text":"consentId"}]}]}]}