{"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"country"}],"role":"symbol","roleHeading":"Instance Property","externalID":"c:objc(cs)AWXCountryListViewController(py)country","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"country","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AWXCountry","text":"AWXCountry","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"modules":[{"name":"Airwallex"}],"title":"country"},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCountryListViewController\/country"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCountryListViewController"]]},"variants":[{"paths":["\/documentation\/airwallex\/awxcountrylistviewcontroller\/country"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxcountrylistviewcontroller\/country"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"A country has been selected."}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"country","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWXCountry","preciseIdentifier":"c:objc(cs)AWXCountry","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCountry"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCountryListViewController":{"kind":"symbol","url":"\/documentation\/airwallex\/awxcountrylistviewcontroller","abstract":[{"type":"codeVoice","code":"AWXCountryListViewController"},{"text":" includes a list of countries.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"AWXCountryListViewController"}],"title":"AWXCountryListViewController","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCountryListViewController","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXCountryListViewController","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCountryListViewController/country":{"kind":"symbol","navigatorTitle":[{"text":"country","kind":"identifier"}],"title":"country","abstract":[{"type":"text","text":"A country has been selected."}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"country","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AWXCountry","text":"AWXCountry","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCountryListViewController\/country","role":"symbol","url":"\/documentation\/airwallex\/awxcountrylistviewcontroller\/country"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","abstract":[],"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCountry":{"type":"topic","title":"AWXCountry","navigatorTitle":[{"kind":"identifier","text":"AWXCountry"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCountry","kind":"symbol","url":"\/documentation\/airwallex\/awxcountry","abstract":[{"type":"codeVoice","code":"AWXCountry"},{"type":"text","text":" includes the information of a country."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXCountry"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"country","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"country","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"AWXCountry","preciseIdentifier":"c:objc(cs)AWXCountry","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCountry"},{"text":" * ","kind":"text"},{"text":"country","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCountryListViewController\/title","value":"AWXCountryListViewController","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCountryListViewController\/fragments","value":[{"text":"AWXCountryListViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCountryListViewController\/navigatorTitle","value":[{"kind":"identifier","text":"AWXCountryListViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCountryListViewController~1country\/title","value":"country","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCountryListViewController~1country\/fragments","value":[{"kind":"identifier","text":"country"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCountry\/title","value":"AWXCountry","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCountry\/fragments","value":[{"kind":"identifier","text":"AWXCountry"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCountry\/navigatorTitle","value":[{"kind":"identifier","text":"AWXCountry"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}