{"variants":[{"paths":["\/documentation\/airwallex\/awxpaymentformviewcontroller\/formmapping"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxpaymentformviewcontroller\/formmapping"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"roleHeading":"Instance Property","role":"symbol","externalID":"c:objc(cs)AWXPaymentFormViewController(py)formMapping","symbolKind":"property","navigatorTitle":[{"text":"formMapping","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"formMapping"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWXFormMapping","preciseIdentifier":"c:objc(cs)AWXFormMapping"}],"title":"formMapping","modules":[{"name":"Airwallex"}]},"sections":[],"abstract":[{"text":"Form mapping which render the UI of payment form.","type":"text"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"formMapping","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWXFormMapping","preciseIdentifier":"c:objc(cs)AWXFormMapping","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXFormMapping"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentFormViewController\/formMapping","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentFormViewController"]]},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentFormViewController":{"abstract":[{"type":"codeVoice","code":"AWXPaymentFormViewController"},{"text":" handles payment form.","type":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentFormViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXPaymentFormViewController","kind":"identifier"}],"title":"AWXPaymentFormViewController","navigatorTitle":[{"text":"AWXPaymentFormViewController","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/airwallex\/awxpaymentformviewcontroller","role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentFormViewController/formMapping":{"type":"topic","title":"formMapping","abstract":[{"text":"Form mapping which render the UI of payment form.","type":"text"}],"url":"\/documentation\/airwallex\/awxpaymentformviewcontroller\/formmapping","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"formMapping","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWXFormMapping","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXFormMapping"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentFormViewController\/formMapping","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"formMapping","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXFormMapping":{"type":"topic","title":"AWXFormMapping","url":"\/documentation\/airwallex\/awxformmapping","kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXFormMapping","navigatorTitle":[{"kind":"identifier","text":"AWXFormMapping"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AWXFormMapping","kind":"identifier"}],"role":"symbol","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","role":"collection","title":"Airwallex","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"formMapping","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"formMapping","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"AWXFormMapping","preciseIdentifier":"c:objc(cs)AWXFormMapping","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXFormMapping","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"formMapping","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"AWXPaymentFormViewController","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentFormViewController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AWXPaymentFormViewController"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentFormViewController\/fragments"},{"op":"replace","value":[{"text":"AWXPaymentFormViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentFormViewController\/navigatorTitle"},{"op":"replace","value":"formMapping","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentFormViewController~1formMapping\/title"},{"op":"replace","value":[{"kind":"identifier","text":"formMapping"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentFormViewController~1formMapping\/fragments"},{"op":"replace","value":"AWXFormMapping","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXFormMapping\/title"},{"op":"replace","value":[{"text":"AWXFormMapping","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXFormMapping\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AWXFormMapping"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXFormMapping\/navigatorTitle"}]}]}