{"abstract":[{"type":"text","text":"Payment intent id."}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialPaymentIntentId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"externalID":"c:objc(cs)AWXVerifyPaymentConsentResponse(py)initialPaymentIntentId","title":"initialPaymentIntentId","symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"initialPaymentIntentId"}],"role":"symbol","modules":[{"name":"Airwallex"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialPaymentIntentId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxverifypaymentconsentresponse\/initialpaymentintentid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxverifypaymentconsentresponse\/initialpaymentintentid"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXVerifyPaymentConsentResponse"]]},"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXVerifyPaymentConsentResponse\/initialPaymentIntentId","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXVerifyPaymentConsentResponse":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXVerifyPaymentConsentResponse","navigatorTitle":[{"text":"AWXVerifyPaymentConsentResponse","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"code":"AWXVerifyPaymentConsentResponse","type":"codeVoice"},{"text":" includes the response of payment consent.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXVerifyPaymentConsentResponse","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxverifypaymentconsentresponse","title":"AWXVerifyPaymentConsentResponse"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","type":"topic","url":"\/documentation\/airwallex","kind":"symbol","abstract":[],"title":"Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXVerifyPaymentConsentResponse/initialPaymentIntentId":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXVerifyPaymentConsentResponse\/initialPaymentIntentId","role":"symbol","navigatorTitle":[{"text":"initialPaymentIntentId","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxverifypaymentconsentresponse\/initialpaymentintentid","abstract":[{"text":"Payment intent id.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialPaymentIntentId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"title":"initialPaymentIntentId","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"initialPaymentIntentId"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"initialPaymentIntentId","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"initialPaymentIntentId","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXVerifyPaymentConsentResponse\/title","value":"AWXVerifyPaymentConsentResponse"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXVerifyPaymentConsentResponse\/fragments","value":[{"text":"AWXVerifyPaymentConsentResponse","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXVerifyPaymentConsentResponse\/navigatorTitle","value":[{"text":"AWXVerifyPaymentConsentResponse","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXVerifyPaymentConsentResponse~1initialPaymentIntentId\/title","value":"initialPaymentIntentId"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXVerifyPaymentConsentResponse~1initialPaymentIntentId\/fragments","value":[{"text":"initialPaymentIntentId","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}