{"sections":[],"abstract":[{"type":"text","text":"The configuration required."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"role":"symbol","title":"configuration","externalID":"c:objc(cs)AWXAPIClient(py)configuration","navigatorTitle":[{"text":"configuration","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"configuration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AWXAPIClientConfiguration","kind":"typeIdentifier","text":"AWXAPIClientConfiguration"}],"modules":[{"name":"Airwallex"}],"symbolKind":"property","roleHeading":"Instance Property"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@NSCopying"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"configuration"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAPIClientConfiguration","kind":"typeIdentifier","text":"AWXAPIClientConfiguration","preciseIdentifier":"c:objc(cs)AWXAPIClientConfiguration"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAPIClient\/configuration","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/airwallex\/awxapiclient\/configuration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxapiclient\/configuration"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAPIClient"]]},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXAPIClient":{"role":"symbol","title":"AWXAPIClient","abstract":[{"type":"codeVoice","code":"AWXAPIClient"},{"type":"text","text":" is a http request client."}],"url":"\/documentation\/airwallex\/awxapiclient","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXAPIClient"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAPIClient","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AWXAPIClient"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXAPIClient/configuration":{"role":"symbol","title":"configuration","abstract":[{"text":"The configuration required.","type":"text"}],"url":"\/documentation\/airwallex\/awxapiclient\/configuration","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXAPIClientConfiguration","text":"AWXAPIClientConfiguration"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAPIClient\/configuration","type":"topic","navigatorTitle":[{"kind":"identifier","text":"configuration"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXAPIClientConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AWXAPIClientConfiguration","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAPIClientConfiguration","url":"\/documentation\/airwallex\/awxapiclientconfiguration","kind":"symbol","abstract":[{"type":"codeVoice","code":"AWXAPIClientConfiguration"},{"text":" contains the base configuration the API client needs.","type":"text"}],"navigatorTitle":[{"text":"AWXAPIClientConfiguration","kind":"identifier"}],"title":"AWXAPIClientConfiguration"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","title":"Airwallex","abstract":[],"type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"configuration","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"configuration","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXAPIClientConfiguration","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAPIClientConfiguration","text":"AWXAPIClientConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"configuration"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"AWXAPIClient","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIClient\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AWXAPIClient"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIClient\/fragments","op":"replace"},{"value":[{"text":"AWXAPIClient","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIClient\/navigatorTitle","op":"replace"},{"value":"configuration","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIClient~1configuration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"configuration"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIClient~1configuration\/fragments","op":"replace"},{"value":"AWXAPIClientConfiguration","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIClientConfiguration\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIClientConfiguration\/fragments","op":"replace","value":[{"text":"AWXAPIClientConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIClientConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AWXAPIClientConfiguration"}]}]}]}