name: Push release to Cocoapods

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  cocoapods:
    runs-on: macos-12
    timeout-minutes: 10
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        
      - uses: michaelhenry/deploy-to-cocoapods-github-action@1.0.10
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
