name: Push release to Cocoapods

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  cocoapods:
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
      - name: Checkout project
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # 3.6.0
        
      - name: Deploy to CocoaPods
        run: |
          set -eo pipefail
          gem install cocoapods
          pod lib lint --allow-warnings
          pod trunk push --allow-warnings
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
