# This is a basic workflow to help you get started with Actions

name: Run Tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize ]
  push:
    branches:
      - build/development

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: macOS-latest
    timeout-minutes: 20

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Cocoapods
      run: pod install
    - name: Build
      run: xcodebuild build-for-testing -workspace Airwallex.xcworkspace -scheme Examples-Demo -destination "platform=iOS Simulator,name=iPhone 12"
    - name: Test
      run: xcodebuild test-without-building -workspace Airwallex.xcworkspace -scheme AirwallexTests -destination "platform=iOS Simulator,name=iPhone 12"
