name: Run Tests

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize ]
  push:
    branches:
      - build/development
      - develop

jobs:
  build:
    runs-on: macOS-latest
    timeout-minutes: 20

    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    
    - name: Cocoapods
      run: pod install --verbose --repo-update
      
    - name: Build
      run: xcodebuild build-for-testing -workspace Airwallex.xcworkspace -scheme Examples-Demo -destination "platform=iOS Simulator,name=iPhone 12"
      
    - name: Test
      run: xcodebuild clean test -workspace Airwallex.xcworkspace -scheme AirwallexTests -destination "platform=iOS Simulator,name=iPhone 12"
