{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextTriggerByType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexNextTriggerByType","text":"AirwallexNextTriggerByType","preciseIdentifier":"c:@E@AirwallexNextTriggerByType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringWithIntentSession\/nextTriggerByType","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"nextTriggerByType","kind":"identifier"}],"title":"nextTriggerByType","symbolKind":"property","modules":[{"name":"Airwallex"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nextTriggerByType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AirwallexNextTriggerByType","kind":"typeIdentifier","preciseIdentifier":"c:@E@AirwallexNextTriggerByType"}],"externalID":"c:objc(cs)AWXRecurringWithIntentSession(py)nextTriggerByType","roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringWithIntentSession"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/airwallex\/awxrecurringwithintentsession\/nexttriggerbytype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxrecurringwithintentsession\/nexttriggerbytype"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Next trigger by.","type":"text"}],"kind":"symbol","references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRecurringWithIntentSession":{"role":"symbol","abstract":[{"type":"codeVoice","code":"AWXRecurringWithIntentSession"},{"type":"text","text":" is the session used for recurring with intent."}],"kind":"symbol","navigatorTitle":[{"text":"AWXRecurringWithIntentSession","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxrecurringwithintentsession","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringWithIntentSession","title":"AWXRecurringWithIntentSession","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXRecurringWithIntentSession","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AirwallexNextTriggerByType":{"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AirwallexNextTriggerByType","kind":"identifier"}],"title":"AirwallexNextTriggerByType","navigatorTitle":[{"text":"AirwallexNextTriggerByType","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexNextTriggerByType","role":"symbol","url":"\/documentation\/airwallex\/airwallexnexttriggerbytype","abstract":[]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRecurringWithIntentSession/nextTriggerByType":{"role":"symbol","abstract":[{"text":"Next trigger by.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"nextTriggerByType","kind":"identifier"}],"title":"nextTriggerByType","url":"\/documentation\/airwallex\/awxrecurringwithintentsession\/nexttriggerbytype","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringWithIntentSession\/nextTriggerByType","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nextTriggerByType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AirwallexNextTriggerByType","preciseIdentifier":"c:@E@AirwallexNextTriggerByType","kind":"typeIdentifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","abstract":[],"title":"Airwallex","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"nextTriggerByType","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"nextTriggerByType"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@E@AirwallexNextTriggerByType","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AirwallexNextTriggerByType","text":"AirwallexNextTriggerByType","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"nextTriggerByType","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"AWXRecurringWithIntentSession","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRecurringWithIntentSession\/title","op":"replace"},{"value":[{"text":"AWXRecurringWithIntentSession","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRecurringWithIntentSession\/fragments","op":"replace"},{"value":[{"text":"AWXRecurringWithIntentSession","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRecurringWithIntentSession\/navigatorTitle","op":"replace"},{"value":"AirwallexNextTriggerByType","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexNextTriggerByType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AirwallexNextTriggerByType"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexNextTriggerByType\/fragments","op":"replace"},{"value":[{"text":"AirwallexNextTriggerByType","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AirwallexNextTriggerByType\/navigatorTitle","op":"replace"},{"value":"nextTriggerByType","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRecurringWithIntentSession~1nextTriggerByType\/title","op":"replace"},{"value":[{"text":"nextTriggerByType","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRecurringWithIntentSession~1nextTriggerByType\/fragments","op":"replace"}]}]}