{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringWithIntentSession\/requiresCVC"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringWithIntentSession"]]},"abstract":[{"text":"Only applicable when next_triggered_by is customer and the payment_method.type is card. If true, the customer must provide cvc for the subsequent payment with this PaymentConsent.","type":"text"},{"text":" ","type":"text"},{"text":"Default: NO","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiresCVC"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"metadata":{"externalID":"c:objc(cs)AWXRecurringWithIntentSession(py)requiresCVC","symbolKind":"property","role":"symbol","platforms":[{"beta":false,"deprecated":true,"unavailable":false}],"fragments":[{"kind":"identifier","text":"requiresCVC"}],"modules":[{"name":"Airwallex"}],"title":"requiresCVC","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"requiresCVC"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","variants":[{"paths":["\/documentation\/airwallex\/awxrecurringwithintentsession\/requirescvc"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRecurringWithIntentSession/requiresCVC":{"title":"requiresCVC","fragments":[{"text":"requiresCVC","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Only applicable when next_triggered_by is customer and the payment_method.type is card. If true, the customer must provide cvc for the subsequent payment with this PaymentConsent."},{"type":"text","text":" "},{"type":"text","text":"Default: NO"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringWithIntentSession\/requiresCVC","type":"topic","url":"\/documentation\/airwallex\/awxrecurringwithintentsession\/requirescvc"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXRecurringWithIntentSession":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXRecurringWithIntentSession","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXRecurringWithIntentSession","kind":"identifier"}],"navigatorTitle":[{"text":"AWXRecurringWithIntentSession","kind":"identifier"}],"title":"AWXRecurringWithIntentSession","url":"\/documentation\/airwallex\/awxrecurringwithintentsession","role":"symbol","abstract":[{"code":"AWXRecurringWithIntentSession","type":"codeVoice"},{"text":" is the session used for recurring with intent.","type":"text"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"abstract":[],"type":"topic","url":"\/documentation\/airwallex","title":"Airwallex","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRecurringWithIntentSession\/title","op":"replace","value":"AWXRecurringWithIntentSession"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRecurringWithIntentSession\/fragments","op":"replace","value":[{"text":"AWXRecurringWithIntentSession","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXRecurringWithIntentSession\/navigatorTitle","op":"replace","value":[{"text":"AWXRecurringWithIntentSession","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}