{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCountryListViewControllerDelegate\/countryListViewController(_:didSelect:)"},"sections":[],"abstract":[{"text":"This method is called when a country has been selected.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxcountrylistviewcontrollerdelegate\/countrylistviewcontroller(_:didselect:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxcountrylistviewcontrollerdelegate\/countrylistviewcontroller(_:didselect:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCountryListViewControllerDelegate"]]},"metadata":{"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"countryListViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AWXCountryListViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXCountryListViewController"},{"text":", ","kind":"text"},{"text":"didSelect","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AWXCountry","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXCountry"},{"text":")","kind":"text"}],"externalID":"c:objc(pl)AWXCountryListViewControllerDelegate(im)countryListViewController:didSelectCountry:","modules":[{"name":"Airwallex"}],"role":"symbol","symbolKind":"method","navigatorTitle":[{"text":"countryListViewController:didSelectCountry:","kind":"identifier"}],"roleHeading":"Instance Method","title":"countryListViewController(_:didSelect:)"},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"countryListViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"AWXCountryListViewController","preciseIdentifier":"c:objc(cs)AWXCountryListViewController","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCountryListViewController"},{"text":", ","kind":"text"},{"text":"didSelect","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"country","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"AWXCountry","preciseIdentifier":"c:objc(cs)AWXCountry","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCountry"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The country list view controller.","type":"text"}]}],"name":"controller"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The selected country."}]}],"name":"country"}]}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","abstract":[],"title":"Airwallex","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCountryListViewControllerDelegate/countryListViewController(_:didSelect:)":{"abstract":[{"text":"This method is called when a country has been selected.","type":"text"}],"type":"topic","title":"countryListViewController(_:didSelect:)","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCountryListViewControllerDelegate\/countryListViewController(_:didSelect:)","navigatorTitle":[{"text":"countryListViewController:didSelectCountry:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"countryListViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AWXCountryListViewController","preciseIdentifier":"c:objc(cs)AWXCountryListViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didSelect","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AWXCountry","preciseIdentifier":"c:objc(cs)AWXCountry","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/airwallex\/awxcountrylistviewcontrollerdelegate\/countrylistviewcontroller(_:didselect:)","required":true,"role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCountry":{"navigatorTitle":[{"text":"AWXCountry","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCountry","title":"AWXCountry","abstract":[{"type":"codeVoice","code":"AWXCountry"},{"text":" includes the information of a country.","type":"text"}],"kind":"symbol","url":"\/documentation\/airwallex\/awxcountry","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXCountry","kind":"identifier"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCountryListViewControllerDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXCountryListViewControllerDelegate"}],"navigatorTitle":[{"text":"AWXCountryListViewControllerDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"A delegate which handles selected country."}],"type":"topic","title":"AWXCountryListViewControllerDelegate","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCountryListViewControllerDelegate","url":"\/documentation\/airwallex\/awxcountrylistviewcontrollerdelegate","role":"symbol","kind":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCountryListViewController":{"abstract":[{"type":"codeVoice","code":"AWXCountryListViewController"},{"type":"text","text":" includes a list of countries."}],"navigatorTitle":[{"text":"AWXCountryListViewController","kind":"identifier"}],"title":"AWXCountryListViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXCountryListViewController","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCountryListViewController","url":"\/documentation\/airwallex\/awxcountrylistviewcontroller","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"countryListViewController:didSelectCountry:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"countryListViewController:didSelectCountry:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"countryListViewController:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)AWXCountryListViewController","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCountryListViewController","text":"AWXCountryListViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":" "},{"kind":"identifier","text":"didSelectCountry:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)AWXCountry","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCountry","text":"AWXCountry"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"country"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"controller","content":[{"inlineContent":[{"type":"text","text":"The country list view controller."}],"type":"paragraph"}]},{"name":"country","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The selected country."}]}]}],"kind":"parameters"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCountryListViewControllerDelegate~1countryListViewController(_:didSelect:)\/title","value":"countryListViewController:didSelectCountry:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCountryListViewControllerDelegate~1countryListViewController(_:didSelect:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"countryListViewController:didSelectCountry:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCountry\/title","value":"AWXCountry"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCountry\/fragments","value":[{"text":"AWXCountry","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCountry\/navigatorTitle","value":[{"kind":"identifier","text":"AWXCountry"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCountryListViewControllerDelegate\/title","value":"AWXCountryListViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCountryListViewControllerDelegate\/fragments","value":[{"text":"AWXCountryListViewControllerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCountryListViewControllerDelegate\/navigatorTitle","value":[{"text":"AWXCountryListViewControllerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCountryListViewController\/title","value":"AWXCountryListViewController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCountryListViewController\/fragments","value":[{"text":"AWXCountryListViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCountryListViewController\/navigatorTitle","value":[{"text":"AWXCountryListViewController","kind":"identifier"}]}]}]}