{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLSessionConfiguration","preciseIdentifier":"c:objc(cs)NSURLSessionConfiguration"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAPIClientConfiguration\/sessionConfiguration"},"metadata":{"roleHeading":"Instance Property","title":"sessionConfiguration","externalID":"c:objc(cs)AWXAPIClientConfiguration(py)sessionConfiguration","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sessionConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"URLSessionConfiguration","preciseIdentifier":"c:objc(cs)NSURLSessionConfiguration","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","symbolKind":"property","modules":[{"name":"Airwallex"}],"navigatorTitle":[{"text":"sessionConfiguration","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAPIClientConfiguration"]]},"abstract":[{"text":"Optional session configuration","type":"text"}],"variants":[{"paths":["\/documentation\/airwallex\/awxapiclientconfiguration\/sessionconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxapiclientconfiguration\/sessionconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXAPIClientConfiguration":{"type":"topic","url":"\/documentation\/airwallex\/awxapiclientconfiguration","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXAPIClientConfiguration"}],"abstract":[{"code":"AWXAPIClientConfiguration","type":"codeVoice"},{"type":"text","text":" contains the base configuration the API client needs."}],"navigatorTitle":[{"text":"AWXAPIClientConfiguration","kind":"identifier"}],"title":"AWXAPIClientConfiguration","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAPIClientConfiguration"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXAPIClientConfiguration/sessionConfiguration":{"abstract":[{"text":"Optional session configuration","type":"text"}],"title":"sessionConfiguration","url":"\/documentation\/airwallex\/awxapiclientconfiguration\/sessionconfiguration","type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXAPIClientConfiguration\/sessionConfiguration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLSessionConfiguration","text":"URLSessionConfiguration"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"sessionConfiguration"}],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"url":"\/documentation\/airwallex","role":"collection","title":"Airwallex","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"sessionConfiguration","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"sessionConfiguration","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSURLSessionConfiguration","kind":"typeIdentifier","text":"NSURLSessionConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"sessionConfiguration"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"AWXAPIClientConfiguration","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIClientConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AWXAPIClientConfiguration"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIClientConfiguration\/fragments","op":"replace"},{"value":[{"text":"AWXAPIClientConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIClientConfiguration\/navigatorTitle","op":"replace"},{"value":"sessionConfiguration","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIClientConfiguration~1sessionConfiguration\/title","op":"replace"},{"value":[{"text":"sessionConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXAPIClientConfiguration~1sessionConfiguration\/fragments","op":"replace"}]}]}