{"kind":"symbol","abstract":[{"text":"Indicates whether card saving is enabled by default. Defaults to YES.","type":"text"}],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoSaveCardForFuturePayments"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"externalID":"c:objc(cs)AWXOneOffSession(py)autoSaveCardForFuturePayments","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"autoSaveCardForFuturePayments"}],"platforms":[{"deprecated":true,"unavailable":false,"beta":false,"message":"Will be removed in next major version release, use AirwallexPayment.Session instead"}],"title":"autoSaveCardForFuturePayments","roleHeading":"Instance Property","modules":[{"name":"Airwallex"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airwallex\/awxoneoffsession\/autosavecardforfuturepayments"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airwallex\/awxoneoffsession\/autosavecardforfuturepayments"]}],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Will be removed in next major version release, use AirwallexPayment.Session instead"}],"type":"paragraph"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXOneOffSession"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"autoSaveCardForFuturePayments","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXOneOffSession\/autoSaveCardForFuturePayments"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"abstract":[],"kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","url":"\/documentation\/airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXOneOffSession/autoSaveCardForFuturePayments":{"url":"\/documentation\/airwallex\/awxoneoffsession\/autosavecardforfuturepayments","abstract":[{"text":"Indicates whether card saving is enabled by default. Defaults to YES.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoSaveCardForFuturePayments"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"autoSaveCardForFuturePayments"}],"deprecated":true,"title":"autoSaveCardForFuturePayments","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXOneOffSession\/autoSaveCardForFuturePayments"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXOneOffSession":{"url":"\/documentation\/airwallex\/awxoneoffsession","abstract":[{"code":"AWXOneOffSession","type":"codeVoice"},{"text":" is the session used for one-off payment.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXOneOffSession"}],"navigatorTitle":[{"kind":"identifier","text":"AWXOneOffSession"}],"deprecated":true,"title":"AWXOneOffSession","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXOneOffSession"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[{"unavailable":false,"beta":false,"deprecated":true}]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"autoSaveCardForFuturePayments"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"autoSaveCardForFuturePayments","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoSaveCardForFuturePayments"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/deprecationSummary","value":[{"inlineContent":[{"text":"Will be removed in next major version release, use AirwallexPayment.Session instead","type":"text"}],"type":"paragraph"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXOneOffSession~1autoSaveCardForFuturePayments\/title","value":"autoSaveCardForFuturePayments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXOneOffSession~1autoSaveCardForFuturePayments\/fragments","value":[{"text":"autoSaveCardForFuturePayments","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXOneOffSession\/title","value":"AWXOneOffSession"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXOneOffSession\/fragments","value":[{"text":"AWXOneOffSession","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXOneOffSession\/navigatorTitle","value":[{"text":"AWXOneOffSession","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}