{"identifier":{"url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXOneOffSession\/paymentIntent","interfaceLanguage":"swift"},"deprecationSummary":[{"inlineContent":[{"text":"Will be removed in next major version release, use AirwallexPayment.Session instead","type":"text"}],"type":"paragraph"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"type":"text","text":"The payment intent to handle."}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXOneOffSession"]]},"kind":"symbol","metadata":{"role":"symbol","platforms":[{"beta":false,"deprecated":true,"unavailable":false,"message":"Will be removed in next major version release, use AirwallexPayment.Session instead"}],"externalID":"c:objc(cs)AWXOneOffSession(py)paymentIntent","modules":[{"name":"Airwallex"}],"symbolKind":"property","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentIntent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPaymentIntent","text":"AWXPaymentIntent"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"paymentIntent"}],"title":"paymentIntent"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentIntent"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AWXPaymentIntent","kind":"typeIdentifier","text":"AWXPaymentIntent","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/airwallex\/awxoneoffsession\/paymentintent"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airwallex\/awxoneoffsession\/paymentintent"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXOneOffSession":{"kind":"symbol","url":"\/documentation\/airwallex\/awxoneoffsession","abstract":[{"type":"codeVoice","code":"AWXOneOffSession"},{"type":"text","text":" is the session used for one-off payment."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWXOneOffSession","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXOneOffSession","title":"AWXOneOffSession","role":"symbol","deprecated":true,"navigatorTitle":[{"text":"AWXOneOffSession","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXOneOffSession/paymentIntent":{"abstract":[{"type":"text","text":"The payment intent to handle."}],"title":"paymentIntent","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXOneOffSession\/paymentIntent","url":"\/documentation\/airwallex\/awxoneoffsession\/paymentintent","type":"topic","navigatorTitle":[{"kind":"identifier","text":"paymentIntent"}],"deprecated":true,"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentIntent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AWXPaymentIntent","text":"AWXPaymentIntent"},{"kind":"text","text":"?"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXPaymentIntent":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent","navigatorTitle":[{"text":"AWXPaymentIntent","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"codeVoice","code":"AWXPaymentIntent"},{"type":"text","text":" includes the information of payment intent."}],"title":"AWXPaymentIntent","url":"\/documentation\/airwallex\/awxpaymentintent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXPaymentIntent"}]},"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","title":"Airwallex","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/airwallex","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":[{"unavailable":false,"beta":false,"deprecated":true}],"op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"paymentIntent","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"paymentIntent","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXPaymentIntent","text":"AWXPaymentIntent","preciseIdentifier":"c:objc(cs)AWXPaymentIntent"},{"kind":"text","text":" * "},{"kind":"identifier","text":"paymentIntent"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/deprecationSummary","value":[{"type":"paragraph","inlineContent":[{"text":"Will be removed in next major version release, use AirwallexPayment.Session instead","type":"text"}]}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXOneOffSession\/title","value":"AWXOneOffSession","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXOneOffSession\/fragments","value":[{"text":"AWXOneOffSession","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXOneOffSession\/navigatorTitle","value":[{"kind":"identifier","text":"AWXOneOffSession"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXOneOffSession~1paymentIntent\/title","value":"paymentIntent","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXOneOffSession~1paymentIntent\/fragments","value":[{"kind":"identifier","text":"paymentIntent"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentIntent\/title","value":"AWXPaymentIntent","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentIntent\/fragments","value":[{"kind":"identifier","text":"AWXPaymentIntent"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXPaymentIntent\/navigatorTitle","value":[{"text":"AWXPaymentIntent","kind":"identifier"}],"op":"replace"}]}]}