{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCard","doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCard\/NumberType-swift.enum"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","abstract":[{"type":"text","text":"for consent payment, NumberType.PAN requires CVC"}],"variants":[{"paths":["\/documentation\/airwallex\/awxcard\/numbertype-swift.enum\/pan"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PAN","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCard\/NumberType-swift.enum\/PAN"},"sections":[],"metadata":{"symbolKind":"property","externalID":"s:So7AWXCardC9AirwallexE10NumberTypeO3PANSSvpZ","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"PAN"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"roleHeading":"Type Property","role":"symbol","title":"PAN","modules":[{"name":"Airwallex"}]},"references":{"doc://org.cocoapods.Airwallex/documentation/Airwallex":{"role":"collection","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex","type":"topic","url":"\/documentation\/airwallex","kind":"symbol","abstract":[],"title":"Airwallex"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCard":{"abstract":[{"type":"codeVoice","code":"AWXCard"},{"type":"text","text":" includes the information of a card."}],"title":"AWXCard","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWXCard"}],"url":"\/documentation\/airwallex\/awxcard","navigatorTitle":[{"kind":"identifier","text":"AWXCard"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCard"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCard/NumberType-swift.enum/PAN":{"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"PAN"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCard\/NumberType-swift.enum\/PAN","abstract":[{"type":"text","text":"for consent payment, NumberType.PAN requires CVC"}],"url":"\/documentation\/airwallex\/awxcard\/numbertype-swift.enum\/pan","title":"PAN"},"doc://org.cocoapods.Airwallex/documentation/Airwallex/AWXCard/NumberType-swift.enum":{"type":"topic","navigatorTitle":[{"text":"NumberType","kind":"identifier"}],"title":"AWXCard.NumberType","identifier":"doc:\/\/org.cocoapods.Airwallex\/documentation\/Airwallex\/AWXCard\/NumberType-swift.enum","abstract":[],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NumberType","kind":"identifier"}],"url":"\/documentation\/airwallex\/awxcard\/numbertype-swift.enum","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCard\/title","value":"AWXCard","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCard\/fragments","value":[{"kind":"identifier","text":"AWXCard"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.Airwallex~1documentation~1Airwallex~1AWXCard\/navigatorTitle","value":[{"kind":"identifier","text":"AWXCard"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}